### ISSUE TITLE
protoc_gen_swagger openapiv2_field definition ignores the type option

### ISSUE THREAD

**Issue by snowzach** [grpc-ecosystem/grpc-gateway#1002]
I am using an int64 type inside of my proto specification, I have overriden the JSON encoder/decoder to use a number instead of a string(int64) as I am okay with the 56bit JSON limit but I want it bigger than 32 bit.

I would like the the swagger definition to reflect the proper value. 

```
message Test {
  int64 mynumber = 1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {type: NUMBER}];
}
```

The model in swagger still shows `string(int64)`. Ideally it should instead show something like `integer($int32)` 

It would be ideal if it respected the type option.

**Comment by johanbrandhorst** [comment]
Cool, sounds like a great first contribution! The source for this logic is in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go, please feel free to look around and see if you could contribute this fix! Let me know if you have any questions!

**Comment by snowzach** [comment]
Sure started #1003

**Comment by snowzach** [comment]
Thanks. All handled now.
