### ISSUE TITLE
Update integration test dependencies

### ISSUE THREAD

**Issue by wenbozhu** [grpc-ecosystem/grpc-gateway#1004]
Vulnerable dependency reported:  

"

Known high severity security vulnerability detected in nokogiri < 1.10.4 defined in Gemfile.lock.
--
Gemfile.lock update suggested: nokogiri ~> 1.10.4.

"

**Comment by johanbrandhorst** [comment]
Hi Wenbo! We're not so worried about this one as we only use ruby for the integration tests. Should probably sort it out anyway, but nothing that affects the security of the application.

**Comment by johanbrandhorst** [comment]
Dupe of #832
