### ISSUE TITLE
Allow final url path parameter to be optional

### ISSUE THREAD

**Issue by veqryn** [grpc-ecosystem/grpc-gateway#1005]
I might be doing something wrong, but I was sort of expecting to be able to have the last url path parameter be optional.

Example:
If you have the rest endpoint `/customers`, it will return information on all customers.
And if you have the rest endpoint `/customers/123`, it will return information on customer id `123`

```proto
syntax = "proto3";

package stuff;

import "google/api/annotations.proto";

service MyAPI {
	rpc CustomersGet(CustomersGetReq) returns (CustomersGetResp) {
		option (google.api.http) = {
			get: "/customers/{id}"
		};
	}
}

message CustomersGetReq {
	uint64 id = 1;
}

message CustomersGetResp {
	repeated CustomerDetail customers = 1;
}

message CustomerDetail {
	uint64 id = 1;
	string name = 2;
	// etc with more info
}
```

Any attempt to curl just `/customers` returns a 404, with that endpoint not existing.

In the end, this worked:
```proto
	rpc CustomersGet(CustomersGetReq) returns (CustomersGetResp) {
		option (google.api.http) = {
			get: "/customers"
			additional_bindings {
			  get: "/customers/{id}"
			}
		};
	}
```

But the downside is that the above produces two swagger endpoint definitions, and also allows things like this, which should not be allowed: `/customers?id=123`

So, is there a way to do this, without creating a second rpc definition with a new name and new request parameter?

**Comment by johanbrandhorst** [comment]
This is not something I'm sure we should support. What you're describing sounds to me like two different RPCs, CustomersGet and CustomersList (using your terminology). Why not have two endpoints? Presumably the response types will be different?

**Comment by johanbrandhorst** [comment]
I will close this, please let me know if you're still interested in this.
