### ISSUE TITLE
Fuzzit CI job is failing unexpectedly

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#1019]
Two recent jobs (https://circleci.com/gh/grpc-ecosystem/grpc-gateway/3946 and https://circleci.com/gh/grpc-ecosystem/grpc-gateway/3948) suffered from fuzzit failures that were unrelated to the changes made. We should investigate and fix the issue.

cc @yevgenypats

**Comment by yevgenypats** [comment]
I'm on it. I think this is connected to go-fuzz and go modules support. I'll push a fix now.
https://github.com/dvyukov/go-fuzz/pull/263

**Comment by johanbrandhorst** [comment]
Fixed by #1022
