### ISSUE TITLE
FieldMask paths for PATCH endpoints are being transformed to PascalCase

### ISSUE THREAD

**Issue by william-plano-oxb** [grpc-ecosystem/grpc-gateway#1034]
## Steps you follow to reproduce the error

1. Create a grpc service with a method that accepts a field mask.
1. Add a PATCH endpoint for this method using grpc-gateway.
1. Call the method via the gateway.
1. Observe that the field mask's paths have been transformed into PascalCase.

## What did you expect to happen instead

1. I would expect the original case in the proto definition to be preserved.

## What's your theory on why it isn't working

This seems to be done explicitly in [runtime/fieldmask.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/fieldmask.go)

I have provided some example code to illustrate the problem here: https://github.com/william-plano-oxb/grpc-gateway-patch-issue 
see the [README.md](https://github.com/william-plano-oxb/grpc-gateway-patch-issue/blob/master/README.md) file for details.

**Comment by johanbrandhorst** [comment]
Yeah I agree this is a bug, would you be interested in changing it? It _is_ a backward compatibility breaking change but fixing bugs is still okay. @dmacthedestroyer @razamiDev since you implemented this (and I reviewed it), do you have any opinion on this proposal?

**Comment by william-plano-oxb** [comment]
For some extra context, the reason this is a problem for us is that our gPRC service is implemented in python, so PascalCase makes no sense there, I can see that if we had a go service then ultimately the case will need to be mapped to match the generated go names, but I think that should be done in the service itself.

Yes, I'm happy to have a go at making this change.

**Comment by johanbrandhorst** [comment]
> For some extra context, the reason this is a problem for us is that our gPRC service is implemented in python, so PascalCase makes no sense there, I can see that if we had a go service then ultimately the case will need to be mapped to match the generated go names, but I think that should be done in the service itself.
> 
> Yes, I'm happy to have a go at making this change.

Thanks for the background, but as someone who mostly works with Go services, I still think the mapping is both unnecessary and wrong. The canonical name for a field is the one in the proto file, and that is what we should be mapping into the `Paths` field. Your case just emphasizes why it is wrong.

**Comment by johanbrandhorst** [comment]
I think this was fixed :thinking:
