### ISSUE TITLE
JSONSchema does not cover all atributes of OpenAPIv2 SchemaObject: missing enum

### ISSUE THREAD

**Issue by OscarHanzely** [grpc-ecosystem/grpc-gateway#1037]
I believe this object 
https://github.com/grpc-ecosystem/grpc-gateway/blob/82dc0837d5ecce71198123cbf94fb6eaff7698f6/protoc-gen-swagger/options/openapiv2.proto#L161

should cover all fields from https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject

However there is one property in specificaiton called enum. It allows to list allowableValues and is handy in swagger generated files to parse the selection of parameter. Was it omitted on purpose ?

Swagger editor complies to it and it treats enum as allowableValues as well 
![image](https://user-images.githubusercontent.com/39314151/64568961-5f6af900-d319-11e9-8050-9a97d9934e42.png)

When tried with proto file it got expected error:

> Error while parsing option value for "openapiv2_schema": Message type "grpc.gateway.protoc_gen_swagger.options.JSONSchema" has no field named "enum".

**Comment by achew22** [comment]
If you want your field to be an enum, is it possible to use a proto enum value? I believe we handle that case correctly.

Also, it would be useful if you could provide a sample of your `.proto` file, I'm just guessing at what your inputs are here.

**Comment by OscarHanzely** [comment]
Thanks for the reply @achew22 . Using Enum field type in message is not the same as enum property of the field. Enum field type only allows to define numeric in32 enumeration.

The reason why swagger allows to have enum as attribute of property is to document/describe any message field type. If you have string type in message and you allow only certain values you describe/annotate them in enum of that type.

Sample proto message
`message SampleMEssage {
    //  Sort field. One of the following options:
    //  "id"   
    //	"userId"
    //	"username"
    //	"email"
    //	"created_at"
    string sort = 1;
}`

It is a string parameter that is allowed to be of certain values only.

What we want to be generated is following swagger file, syntactically and semantically correct:
`"parameters": [
          {
            "name": "sort",
            "description": "Sort field. One of the following options,
            "in": "query",
            "required": false,
            "type": "string"
            "enum": [
                 "id",
                 "userId",
                 "username",
                 "email",
                 "created_at" 
            ]
          }
        ],`

I was hoping I can accomplish it by updating proto file to
`message SampleMEssage {
    //  Sort field. One of the following options:
    //  "id"   
    //	"userId"
    //	"username"
    //	"email"
    //	"created_at"
    string sort = 1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {enum: ["id","userId","username","email","created_at"]}];
}`
but that was throwing error on parsing the enum 
> Error while parsing option value for "openapiv2_schema": Message type "grpc.gateway.protoc_gen_swagger.options.JSONSchema" has no field named "enum".

**Comment by achew22** [comment]
> Enum field type only allows to define numeric in32 enumeration.

I don't believe that is entirely the case. Proto should accept both the string and the numeric form of any enum. From the [proto language guide](https://developers.google.com/protocol-buffers/docs/proto3#json)

> The name of the enum value as specified in proto is used. Parsers accept both enum names and integer values.

Could you try:

```proto
message SampleMessage {
  enum InnerEnum {
    UNKNOWN = 0;
    ID = 1;
    USER_ID = 2;
  }
  InnerEnum inner = 1;
}
```

and report back on how grpc-gateway handles a post with the inner field equaling the literal string `ID`?

**Comment by OscarHanzely** [comment]
grpc-gateway handles both string and numeric values on Enums, however there are few drawbacks:
1. the enum is a const and does not accept string as "+id" or -id (prefered sorting options we implemented) 
![image](https://user-images.githubusercontent.com/39314151/64573275-fb9bfc80-d327-11e9-9d73-5d530a4ab03e.png)

2. the swagged documentation does not show enum list on generated property as possible values since it is spearate object in section `definitions": {}`

I see why you would prefer the enum to be used for type that has only allowed values to be passed through, and it could be a dirty fix for this case if it would allow to be any string (beyond alhpanumeric characters). But it would be nice to allow actually documenting the standard basic type(not just this string) in proto to allowed values. Parser should allow all types mentioned in https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
