### ISSUE TITLE
Question: Override TransientFailure error with friendlier response

### ISSUE THREAD

**Issue by ddibiase** [grpc-ecosystem/grpc-gateway#1047]
Hi there, I was wondering if there was a way to override the default TransientFailure message that grpc-gateway responds with when the grpc server is not available. Suggestions for the most effective way to handle this are appreciated.

**Comment by johanbrandhorst** [comment]
Hi David, thanks for your issue. I think this is something that is best explained over chat, could you join the #grpc-gateway chat on the gophers slack? The link is https://invite.slack.golangbridge.org/.
