### ISSUE TITLE
json Custom output support (with examples)

### ISSUE THREAD

**Issue by a97077088** [grpc-ecosystem/grpc-gateway#1051]
```
	gohook.Hook(runtime.ForwardResponseMessage, func(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, req *http.Request, resp proto.Message, opts ...func(context.Context, http.ResponseWriter, proto.Message) error) {
		bt,err:=marshaler.Marshal(resp)
		if err!=nil{
			return
		}
		rmsg:=make(map[string]interface{})
		err=marshaler.Unmarshal(bt,&rmsg)
		if err!=nil{
			return
		}
		rmsg["err"]=0
		rmsg["msg"]="r ok"
		newbt,err:=marshaler.Marshal(rmsg)
		if err!=nil{
			return
		}
		w.Write([]byte(newbt))
		w.WriteHeader(200)
	},nil)
  ```
  ```
	{"Msg":"state ok","err":0,"msg":"r ok"}
  ```
	
Is it possible to add runtime.ForwardResponseMessage here to support custom format json, such as "err": 0, "msg": "r ok", or convert them all to lowercase or uppercase This should be the right choice

**Comment by johanbrandhorst** [comment]
I'm not sure I understand the question. As you've done in this example, you can use ForwardResponseMessage to configure the output. If you're unhappy with the JSON mapping of your field names, you need to go back to your proto files or your marshaller configuration. You maybe using `OrigName: true/false` when you don't want to.

If you need more help, please pop by the #grpc-gateway channel on Gophers slack and I can maybe help you understand what you're asking.

**Comment by a97077088** [comment]
Thank you for your answer. The current question is that ForwardResponseMessage function can not be replaced dynamically. It can only be implemented by hook. How should I replace ForwardResponseMessage dynamically?

**Comment by johanbrandhorst** [comment]
I suppose you could call another function in it which you can reassign to dynamically? It sounds like a pretty bad idea. What are you trying to do? I still think this would be easier to handle on slack.

**Comment by a97077088** [comment]
Implement runtime.WithProtoErrorHandler

runtime.WithForwardResponseMessage similar function, I saw a night yesterday seems to need to change the main code or gohook can achieve the effect

**Comment by a97077088** [comment]
If you use runtime.WithForwardResponseOption(), multiple returns will be said.

{"Error": 0, "Error": "Runs normally", } {// pbret}

**Comment by a97077088** [comment]
![kf](https://user-images.githubusercontent.com/18098725/65895043-5bdd0600-e3dd-11e9-918c-a88b8d850eaa.png)

Add the interception function style of runtime.ForwardResponseMessage here to support the custom json format.

**Comment by comeonjy** [comment]
My solution is:

Use the grpc interceptor to distinguish the source of the request

```
runtime.WithMetadata(func(ctx context.Context, request *http.Request) metadata.MD {
	return metadata.New(map[string]string{
	        httpClientReqMDName: httpClientReqMDValue,
	})
})

func grpcResponse(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
	resp, err = handler(ctx, req)
	if err == nil {
		var client string
		if mdIn, ok := metadata.FromIncomingContext(ctx); ok {
			if t := mdIn.Get(httpClientReqMDName); len(t) > 0 {
				client = t[0]
			}
		}
		if client == httpClientReqMDValue {
			m, ok := resp.(proto.Message)
			if ok {
				any, err := anypb.New(m)
				if err == nil {
					return &v1.Response{
						Code: 100,
						Msg:  "success",
						Data: any,
					}, nil
				}
			}
		}
	}
	return resp, err
}
```

**Comment by bourne-3** [comment]
> ![kf](https://user-images.githubusercontent.com/18098725/65895043-5bdd0600-e3dd-11e9-918c-a88b8d850eaa.png)
> 
> Add the interception function style of runtime.ForwardResponseMessage here to support the custom json format.

i use this way to deal，but the response show like below
```
{
    "code": 0,
    "msg": "success",
    "data": {
        "isSucc": false
    }
}{
    "isSucc": false
}
```

how to eliminate the
```
{
    "isSucc": false
}
```
