### ISSUE TITLE
How to support custom output, implementation

### ISSUE THREAD

**Issue by a97077088** [grpc-ecosystem/grpc-gateway#1055]
How to support custom output, implementation

runtime.ForwardResponseMessage=func(xx)

How should I achieve this effect?

**Comment by johanbrandhorst** [comment]
Hi @a97077088. I answered you before, and I encouraged you to join the Gophers slack so that I could understand your question. Please don't open more issues with the same question. Join on https://invite.slack.golangbridge.org/ and then join the #grpc-gateway channel and I can help you directly.
