### ISSUE TITLE
handleForwardResponseOptions not called by DefaultHTTPError

### ISSUE THREAD

**Issue by movsb** [grpc-ecosystem/grpc-gateway#1064]
[handleForwardResponseOptions](https://github.com/grpc-ecosystem/grpc-gateway/blob/8115cdbcfe0a56abf367bbb9372a1dd2a7f2f8ab/runtime/handler.go#L158-L169) is called by both [ForwardResponseStream](https://github.com/grpc-ecosystem/grpc-gateway/blob/8115cdbcfe0a56abf367bbb9372a1dd2a7f2f8ab/runtime/handler.go#L37) and [ForwardResponseMessage](https://github.com/grpc-ecosystem/grpc-gateway/blob/8115cdbcfe0a56abf367bbb9372a1dd2a7f2f8ab/runtime/handler.go#L134) but not [DefaultHTTPError](https://github.com/grpc-ecosystem/grpc-gateway/blob/8115cdbcfe0a56abf367bbb9372a1dd2a7f2f8ab/runtime/errors.go#L131-L139). Is there a reason why? Is it intended?

FYI: `handleForwardResponseServerMetadata`, `handleForwardResponseTrailerHeader` and `handleForwardResponseTrailer` are called by `ForwardResponseMessage` and `DefaultHTTPError`.

### Steps you follow to reproduce the error:

1. Register a forwardResponseOption:

  ```go
  mux := runtime.NewServeMux(runtime.WithForwardResponseOption(myCallback))
  ```

2. Return an error from GRPC handler.

### What did you expect to happen instead:

`myCallback` gets called on all response-related functions like `ForwardResponseMessage`, `ForwardResponseStream` and `DefaultHTTPError`.

**Comment by johanbrandhorst** [comment]
Hm, yea this might be a reasonable proposal, but I don't think we can really change this without breaking users. Might have to be another one for the v2 dust heap :grimacing:.

**Comment by movsb** [comment]
If I'm the first one who filed this issue, maybe I can guess they don't use this feature yet? 😂 Otherwise, they must encounter this. @johanbrandhorst

**Comment by johanbrandhorst** [comment]
Nah, this feature is definitely used I'm afraid. I use it myself for many applications and never actually wanted this behaviour. I'm afraid you'll have to overwrite DefaultHTTPError with a function that does what you want :(.

**Comment by johanbrandhorst** [comment]
I'm hesitant to add more knobs when there is a work around and not a great deal of demand. Does it not work to just assign `runtime.HTTPError` to a function that calls your function and wraps `runtime.DefaultHTTPError`?

**Comment by movsb** [comment]
Thanks! It does work.

```go
runtime.HTTPError = func(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, req *http.Request, err error) {
    for _, opt := range mux.GetForwardResponseOptions() {
        // The response body (message) is always nil here
        if err := opt(ctx, w, nil); err != nil {
            return
        }
    }
    runtime.DefaultHTTPError(ctx, mux, marshaler, w, req, err)
}
```
