### ISSUE TITLE
third_party/googleapis is missing from package

### ISSUE THREAD

**Issue by ggilley** [grpc-ecosystem/grpc-gateway#1065]
I'm installing the latest packages. third_party/googleapis is missing from the package:

```
$ ls github.com/grpc-ecosystem/grpc-gateway/       
LICENSE.txt             internal                protoc-gen-swagger      runtime                 utilities

```

So I can't compile anything because it depends on those files existing:

```
protoc -I/usr/local/include -I. \
  -I$GOPATH/src \
  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
  --ruby_out=. \
  path/to/your_service.proto
```

**Comment by johanbrandhorst** [comment]
Define "latest package" here? Is this in your vendor folder or something?

**Comment by ggilley** [comment]
What I mean is, I follow the instructions: 

```
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
go get -u github.com/golang/protobuf/protoc-gen-go
```

And when I try to generate:

```
protoc -I/usr/local/include -I. \
  -I$GOPATH/src \
  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
  --go_out=plugins=grpc:. \
  path/to/your_service.proto

```

The /grpc-gateway/third_party/googleapis files do not exist.

**Comment by johanbrandhorst** [comment]
Yes these files are not tracked by go since they are proto files. The recommendation is to manually include them in your repository. Alternatively you can use bazel which solves most of this.

**Comment by ggilley** [comment]
Okay, then the instructions on the website need to be corrected. They don't mention this step at all and I wasted a bunch of time trying to figure out what I was doing wrong.

Plus, I think it's a silly decision since you can't use the grpc-gateway without them. Just makes everything harder for no reason.

**Comment by johanbrandhorst** [comment]
I'm sorry that the instructions were lacking in this case, would you be interested in contributing some better instructions to help the next person? I'd be happy to help you get a PR in.

As for this being a "silly decision", it's unfortunately out of our hands, there's no way to track proto files with go modules. Maybe you know a better way?

**Comment by ggilley** [comment]
Okay, I didn't realize it was a technical limitation. I'll investigate.

**Comment by johanbrandhorst** [comment]
This is a very go-centric solution, and it is far from a standard approach to versioning protobuf. Unless it becomes more widespread in the community we're unlikely to follow this model.

**Comment by BelarminoClearbanc** [comment]
👍

**Comment by aviddiviner** [comment]
I was able to resolve this by doing:
`-I=$GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.12.1/third_party/googleapis`

That version number will change depending on what you have installed.

**Comment by Vlad-Shevliakov** [comment]
I had the same problem
I liked this solution: https://www.youtube.com/watch?v=Zf9G2KzYs7w
He just copied from "github.com/grpc-ecosystem/grpc-gateway@v1.14.6/third_party/googleapis/"
cp -r google ~/your_project_path

Works fine for me!

**Comment by jextrevor** [comment]
this is an ugly solution, and is turning me away from working with protobuf/grpc in general

**Comment by elchappo** [comment]
I have to admit is really hard to work with this sort of changes, each time I want to use it I have to invest time to fix it first :( pretty disappointed

**Comment by johanbrandhorst** [comment]
Hi everyone. We recently updated the repository to use [buf](https://github.com/bufbuild/buf) to manage the protobuf dependencies, which should make this much easier. Have you tried going through the README recently?

**Comment by oxygenz6** [comment]
> Hi everyone. We recently updated the repository to use [buf](https://github.com/bufbuild/buf) to manage the protobuf dependencies, which should make this much easier. Have you tried going through the README recently?
> 
> EDIT: Disclaimer: I work at buf.

Thanks to the unfair sanctions over people of Iran, Open-source software is restricted in our country and we can not use `buf`! This is what sucks about the modern software.

**Comment by Danoctum** [comment]
Hi all, using buf.build I've just added the following to my generating options:
`include_imports: true`

This makes protoc also generate the protofiles you have imported in your protofile, and put them in the correct folder the import is referencing.
