### ISSUE TITLE
jfbrandhorst/grpc-gateway-build-env image can't run on Windows

### ISSUE THREAD

**Issue by someone1** [grpc-ecosystem/grpc-gateway#1073]
The `jfbrandhorst/grpc-gateway-build-env:1.13` image can't be pulled in a Windows docker environment:

```powershell
PS C:\> docker pull jfbrandhorst/grpc-gateway-build-env:1.13
Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
```
And running it as described in the contributing doc from a linux environment errors with:

```bash
protoc -I /usr/local/bin//../include -I. -Ithird_party/googleapis --plugin=bin/protoc-gen-swagger --swagger_out=logtostderr=true,allow_repeated_fields_in_body=true,use_go_templates=true,Mgoogle/protobuf/field_mask.proto=google.golang.org/genproto/protobuf/field_mask,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor,Mexamples/proto/sub/message.proto=github.com/grpc-ecosystem/grpc-gateway/examples/proto/sub,grpc_api_configuration=examples/proto/examplepb/unannotated_echo_service.yaml:. examples/proto/examplepb/echo_service.proto examples/proto/examplepb/a_bit_of_everything.proto examples/proto/examplepb/wrappers.proto examples/proto/examplepb/stream.proto examples/proto/examplepb/unannotated_echo_service.proto examples/proto/examplepb/use_go_template.proto examples/proto/examplepb/response_body_service.proto
generate -i examples/proto/examplepb/echo_service.swagger.json \
    -l go -o examples/clients/echo --additional-properties packageName=echo
make: generate: Command not found
make: *** [Makefile:169: examples/clients/echo/client.go] Error 127
```

_Originally posted by @someone1 in https://github.com/grpc-ecosystem/grpc-gateway/pull/1072#issuecomment-548820266_

**Comment by achew22** [comment]
@johanbrandhorst could I have you move this over to the other repo?

**Comment by johanbrandhorst** [comment]
The first error is because of a docker hub issue. I would like to move the image hosting to GitHub once the package registry is GA (13th of Nov AFAIK). The second error I'm not so sure about, but I will have a look when I have time.

@achew22 not sure what you mean by moving the image?

**Comment by achew22** [comment]
Sorry, I was talking about the *issue* not the image. Words are hard. Please leave this until you're back and settled at home

**Comment by johanbrandhorst** [comment]
I've re-pushed the 1.13 image, and it should now be pullable: https://hub.docker.com/r/jfbrandhorst/grpc-gateway-build-env/tags.

I've opened a PR to fix the generation instructions: https://github.com/grpc-ecosystem/grpc-gateway/pull/1074. This should fix the issue. Thanks for the report @someone1. Let me know if you still have issues.
