### ISSUE TITLE
 How do I load balance call grpc service?

### ISSUE THREAD

**Issue by ya0yy** [grpc-ecosystem/grpc-gateway#1081]

**Comment by johanbrandhorst** [comment]
Hi @ya0yy. This question isn't directly relevant to the grpc-gateway project, so I'm going to close it. Please take a look at the grpc documentation for more information on load balancing options: https://grpc.io/docs/ https://grpc.io/blog/loadbalancing/

**Comment by ya0yy** [comment]
> Hi @ya0yy. This question isn't directly relevant to the grpc-gateway project, so I'm going to close it. Please take a look at the grpc documentation for more information on load balancing options: https://grpc.io/docs/ https://grpc.io/blog/loadbalancing/

thanks reply, but I mean http request to grpc-gateway, grpc-gateway load balance for call grpc service, as look like a client lb

**Comment by johanbrandhorst** [comment]
Normally the grpc-gateway is colocated with the gRPC server it exposes, but it is of course possible to specify the same sort of load balancing options as with any other gRPC client. In any case, this is not a question for the grpc-gateway project. You can specify gRPC DialOptions to the gateway generated code.
