### ISSUE TITLE
extract protoc-gen-swagger to separate repo

### ISSUE THREAD

**Issue by vtolstov** [grpc-ecosystem/grpc-gateway#1083]
can you extract protoc-gen-swagger to separate repo ?
I think that in this case contributors can easy adopt it and also able to move forward to openapi v3

**Comment by johanbrandhorst** [comment]
Hi Vasiliy, thanks for the suggestion. I think we're hesitant to do this without a good reason, what is it that you think is holding back contributors right now?

**Comment by vtolstov** [comment]
main thing that stops me - i think about generator that it parses proto description, fills the some go structs and run marshal json on it. but protoc-gen-swagger uses another approach...
also it tightly connected to grpc-gateway, but i'm not need grpc-gateway and want to have path parameters in streaming requests..

**Comment by johanbrandhorst** [comment]
Sounds like there's space for an alternative protoc-gen-openapi implementation then. Our swagger generator will probably always be tightly coupled to our handlers.

**Comment by vtolstov** [comment]
yeah, thanks
