### ISSUE TITLE
Generate java grpc gateway code.

### ISSUE THREAD

**Issue by xin-au** [grpc-ecosystem/grpc-gateway#1097]
Wondering is there a plan for generating a java grpc gateway code? If not, is it worth to do it? CC: @johanbrandhorst

**Comment by achew22** [comment]
No, there is no plan to do that. There are other projects on GitHub that claim to do that for Java in various frameworks, but since I've not used any of them I do not want to endorse them. If you find one you truly love, feel free to comment on this issue to tell us how it went.

**Comment by xin-au** [comment]
@achew22 , got it. Thanks for the info!
