### ISSUE TITLE
Any example or doc of sending large data from Postman (json) to the server using client side streaming?

### ISSUE THREAD

**Issue by cyantarek** [grpc-ecosystem/grpc-gateway#1100]
Hello,

I want to send a very large string to the server. Instead of sending it once, I thought to send it through client side streaming. So my protobuf looks like kind of this one:

```protobuf
service AbcService {
    rpc Send(stream Request) returns (Response) {
        option (google.api.http) = {
            post: "/api/data/send"
            body: "*"
        };
    }
}

message Request {
    string body = 1;
}

message Response {
    string status = 1;
}
```

Now I want to send the request with large string inside a json through Postman using Client Side Streaming. How can I do this? I can not find any examples in the repo and I don't know how to achieve what I want.

Thanks.

**Comment by johanbrandhorst** [comment]
Hi @cyantarek. Unfortunately client side streaming isn't supported by browsers or many HTTP clients. I don't know how to use Postman for this. You can however use this in the gateway. See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/stream.pb.gw.go#L36 for a generated code implementation, and https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/stream.proto#L12 for the proto definition. The Gateway parser will expect the messages to be sent in the body.

**Comment by johanbrandhorst** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/integration/integration_test.go#L446 this shows a test example of this.

**Comment by cyantarek** [comment]
Thanks for super quick response. I like your dedication Johan Brandhorst. I'll definitely check out.

**Comment by camerondurham** [comment]
Thanks again for your help! Updated links for example directories in 2020:
* Proto definition: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/stream.proto
* Generated code implementation: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/stream.pb.gw.go
