### ISSUE TITLE
protoc-gen-swagger: support multiple files

### ISSUE THREAD

**Issue by nonpcnpc** [grpc-ecosystem/grpc-gateway#1104]
I have multiple services that I want to compose under single server and I want to have single swagger definition instead of each individual service having its own. Is there a way to generate single swagger schema from multiple services?

**Comment by johanbrandhorst** [comment]
Hi! We currently don't support this with protoc-gen-swagger but I imagine you could do it with a tool like `jq`. This has been requested before as a feature, so if you're interested in implementing it we'd be happy to review it!

**Comment by nonpcnpc** [comment]
ok, thanks for the info. in the end, i think i will use separate schemas...something like this http://swagger-net-test-multiapiversions.azurewebsites.net/swagger/ui/index
