### ISSUE TITLE
Why is metadataAnnotators not []func(metadata.MD, *http.Request)

### ISSUE THREAD

**Issue by liov** [grpc-ecosystem/grpc-gateway#1107]
I don't think 
```go
for _, mda := range mux.metadataAnnotators {
		md = metadata.Join(md, mda(ctx, req))
	}
```
 is better than 
```go
for _, mda := range mux.metadataAnnotators {
		mda(md, req)
	}
```

**Comment by achew22** [comment]
Unfortunately there is no enough information in this issue to determine what you think is wrong nor how we would go about fixing it. In the future, please use the issue template. If you would like to fill in the issue template and reopen I'm also receptive to that.
