### ISSUE TITLE
Streaming responses are put in `x-stream-definitions` rather than `/components/schema`, which tools do not support

### ISSUE THREAD

**Issue by seanlaff** [grpc-ecosystem/grpc-gateway#1109]
The gateway wraps streaming responses in a "result" object
```ts
{
  result?: <T>;
  error?: RuntimeStreamError;
}
```

In the generated swagger json, these intermediary wrappers are put into `/x-stream-definitions`. It was decided to put them there because there could potentially be a name conflict by putting them into `/components/schema` (see https://github.com/grpc-ecosystem/grpc-gateway/pull/850)

However, it's uncommon for codegen tools to have support for extension fields: for instance
- https://github.com/OpenAPITools/openapi-generator
- https://github.com/contiamo/restful-react

Since these schemas are not an extension to the openapi spec itself, I think a better developer experience would be to place them in `/components/schema`, and give them a prefixed name that is unlikely to collide. I.e `StreamResponseMyResponseType`.

**Comment by johanbrandhorst** [comment]
Hi Sean, thanks for raising this discussion. Do these tools natively support any sort of streaming results? It wouldn't be worth moving these if it didn't actually add capabilities.

**Comment by seanlaff** [comment]
Hey @johanbrandhorst the grpc-gateway correctly turns streams into json in a usable way and we want to leverage this in our clients. Protoc-gen-swagger generates the necessary types as mentioned in #850, however since they end up in a custom field, downstream code-generating tools cannot generate valid types since they only look in well-known locations.

We've given this problem a little more thought and I think we have a better solution that avoids any collision problems. Instead of generating the stream-definitions as a separate schema with a ref link, we propose generating the streaming response wrapper inline, e.g.

```diff
       "content": {
         "application/json": {
           "schema": {
-            "$ref": "#/x-stream-definitions/eventListEventsResponse"
+            "properties": {
+              "error": {
+                "$ref": "#/components/schemas/runtimeStreamError"
+              },
+              "result": {
+                "$ref": "#/components/schemas/eventListEventsResponse"
+              }
+            },
+            "title": "Streamingresponse",
+            "type": "object"
           }
         }
       }

```

As a short-term workaround, we've written a jq filter that will transform an existing spec into the format we're proposing, which works with the code-gen tools.

```jq
.paths[][].responses[]?.content[].schema |= 
    if .["$ref"] != null and (.["$ref"] | startswith("#/x-stream-definitions/"))
    then {
        type: "object",
        properties: {
            result: (.["$ref"] |= sub("#/x-stream-definitions/"; "#/components/schemas/")),
            error: {"$ref": "#/components/schemas/runtimeStreamError"}
        },
        title: "Streamingresponse"
    }
    else .
    end
```

With this change we can drop `x-stream-definitions` altogether if we wanted.

**Comment by johanbrandhorst** [comment]
The inline solution looks great to me, I'd be happy to accept that contribution.
