### ISSUE TITLE
all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:50051: connect: connection refused\"

### ISSUE THREAD

**Issue by shumintao** [grpc-ecosystem/grpc-gateway#1111]
Hope someone can solve it

**Comment by johanbrandhorst** [comment]
This is an environment problem. It's a generic error that happens when you're dialling the wrong port on your computer. This is not the right forum for this sort of debugging, please join #grpc-gateway on Gophers slack for assistance.
