### ISSUE TITLE
Gateway does not parse oneof types correctly when using camelCase

### ISSUE THREAD

**Issue by seanlaff** [grpc-ecosystem/grpc-gateway#1113]
Enums like 

```proto
message GetRolesRequest {
  oneof get {
    // roles's project
    string project_id = 4;
    // cluster roles
    bool cluster = 5;
  }
}
```

will not be parsed correctly through the gateway with the `camelCase` flag. `project_id` succeeds but `projectId` does not.

The issue looks to be here :
https://github.com/grpc-ecosystem/grpc-gateway/blob/7f57073b1543f1b5a5077437aa57b92b6cfc04a6/runtime/query.go#L120-L128

There's a map of `oneof`s that we loop over, however they key of the map is the name with the underscore, so given a camelCase param, it will never find it.

**Comment by johanbrandhorst** [comment]
Nice find. Have you looked at implementing a fix? I would be happy to review it.
