### ISSUE TITLE
protoc-gen-swagger: Support for repeated custom message in url params

### ISSUE THREAD

**Issue by DenisGlot** [grpc-ecosystem/grpc-gateway#1119]
I'm trying to use pagination with gRPC like this
```
rpc ListThing (ListThingRequest) returns (ListThingResponse) {
    option (google.api.http).get = "/v1/things"
}

message ListThingRequest {
    int32 page_number = 1;
    int32 page_size = 2;
    repeated OrderField sort = 3;
}
message OrderField {
    string field = 1;
    Order order = 2;
}

enum Order {
    ASC = 0;
    DESC = 1;
}
```
but the `sort` doesn't get generated. PR with support for map not merged yet...
What are the options?

**Comment by johanbrandhorst** [comment]
Could perhaps use specific types for the fields you want to order? Do you need to support more than one field order at a time?

**Comment by DenisGlot** [comment]
Yeah, I need to support more than one field in one query for sorting. What do you mean by `specific types`?

**Comment by johanbrandhorst** [comment]
`AgeOrder`, `NameOrder`... the more specific you can make it the safer it will be to consume your API. More dynamic = less guarantees.
