### ISSUE TITLE
Support for custom query parameters parsers

### ISSUE THREAD

**Issue by wp0pw** [grpc-ecosystem/grpc-gateway#1128]
Hello, currently generated code handles query parameters by calling 
`runtime.PopulateQueryParameters(&protoReq, req.Form, filters)` and that works great but I'm currently trying to proto some deeply nested messages and I don't want to expose that complexity to the external users - would you be interested in making this more configurable - akin to the model used for Marshalers?

Unless there is a way to already intercept that code somehow that I don't see. I will be happy to contribute if this is something you would be interesed in adding to the gateway.

Thanks.

**Comment by johanbrandhorst** [comment]
If we can find a nice way to integrate this without changing existing users it might be possible yeah. I'm weary of giving any promises until I've seen the damage but I'm optimistic that if it's not too heavy weight we could merge it :). I know there have been some discussion around alternative query parsers in the past too.

**Comment by wp0pw** [comment]
Great. By not changing existing users - do you mean the generated code being the same? I was thinking about going the `runtime.ServerMuxOption` and hving this information on the mux so we would get the specific `PopulateQueryParameters` instance from mux in the Handler, does that sound plausible?

I may not know all the usecases however, so may be long way off here. I can give it a quick stab in coming days and do an early PR too if needed be.

**Comment by johanbrandhorst** [comment]
No, I mean that whatever is the default now must remain the default in the future so existing users upgrading don't have their query parameter parsing changed.

**Comment by wp0pw** [comment]
@johanbrandhorst sorry for radio silence, was quite busy - I've create pr with the changes - #1138 
let me know what you think.
