### ISSUE TITLE
Is grpc-gateway a stateless application?

### ISSUE THREAD

**Issue by zxgm** [grpc-ecosystem/grpc-gateway#1139]
Is grpc-gateway a stateless application?Is grpc-gateway easy to scale? How to support stateful service requests if it is a stateless application？

**Comment by johanbrandhorst** [comment]
The gateway is stateless, and you can usually just deploy them 1:1 with your backend deployments, or even build it into your application like most of the examples do. Stateful requests have to be handled by the backing gRPC server implementation, it's no different from other proxies in that matter.

Please field more questions like this on the official support chat, see the link in the issue template.
