### ISSUE TITLE
Feature request: support of go protocol buffer v2

### ISSUE THREAD

**Issue by strobil** [grpc-ecosystem/grpc-gateway#1147]
Hello!
Do you plan to migrate to this new [protobuf-go](https://github.com/protocolbuffers/protobuf-go) module?

Thank you.

**Comment by johanbrandhorst** [comment]
We haven't looked at the consequences yet, but I think we may want to stay on `golang/protobuf@v1.4.0` when it comes out, rather than making a slightly breaking change and move to the new import. We'll see what our users need.

**Comment by johanbrandhorst** [comment]
Thanks Stale bot, as it turns out, we're going to be doing this in the v2 release of the gateway. The v2 branch is already using the new protobuf API.

**Comment by johanbrandhorst** [comment]
This is merged into v2, so closing this.
