### ISSUE TITLE
google.api.http option not picked up/mapped correctly?

### ISSUE THREAD

**Issue by catper** [grpc-ecosystem/grpc-gateway#1148]
The proxy doesn't generate HTTP bindings as expected when using an annotation like this:
```
    rpc GetAccount (GetAccountReq) returns (Account) {
        option (google.api.http) = {
            get: "/v1/{name=accounts/*}"
        };
    }
```
According to the first example in Google's [http.proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) this should map to 

`GET /v1/accounts/123456` 

with 123456 being assigned to the `name` field of `Account`. However, attempting to curl the above results in a 404 being returned.

I notice that the version of http.proto that is included in grpc-gateway is different from the one I linked above and that it doesn't contain any annotations of this type. I also don't see any occurence of this type of annotation anywhere in the examples. 

The question thus is if grpc-gateway supports this annotation or not? If not, are there any plans to include support for it? If this is supported, is there some special magic I need to apply to expose the binding?

**Comment by johanbrandhorst** [comment]
Hi, thanks for the issue report.

To be clear, I think the first example says that the value `accounts/123456` should be set to the field `name` of `Account`, correct?

We are talking about this line, right? https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L88.

As for the gateways handling of this, I would definitely expect this to work. Do you have a minimally reproducible example that shows this not working?

**Comment by catper** [comment]
> To be clear, I think the first example says that the value accounts/123456 should be set to the field name of Account, correct?

Correct, sorry for being unclear. 

Will be back with a mini example.

**Comment by catper** [comment]
turns out this is just me getting my wires crossed vis a vis which ports lead where. am now quietly going to recede into a corner in shame.

kudos on the super quick feedback though, that's impressive!

**Comment by johanbrandhorst** [comment]
Glad it worked out, and thanks for using the project! Join the #grpc-gateway channel on the Gophers slack for even quicker feedback next time :smile:.
