### ISSUE TITLE
1.14.x breaks clay

### ISSUE THREAD

**Issue by utrack** [grpc-ecosystem/grpc-gateway#1161]
Hi! After 1.14.0's internalization [protoc-gen-goclay](https://github.com/utrack/clay) is broken in a same way #1154 was - it depends on [genswagger](https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger/internal/genswagger) package, which was moved behind internal/.

Is there any way to retrieve `[]byte` of a Swagger definition without invoking `genswagger` directly?

I'm wondering if it'd be worth it to split `protoc-gen-swagger` to a separate package. I feel that it may be useful for other languages since JSON spec is more or less standard.

**Comment by johanbrandhorst** [comment]
Hi, sorry about breaking your build. I'll move it back into the public namespace and release 1.14.2.

> I'm wondering if it'd be worth it to split protoc-gen-swagger to a separate package. I feel that it may be useful for other languages since JSON spec is more or less standard.

What do you mean by this? It translates proto options to a swagger file, in some case our internal options. I don't know how generic it can really be made.

**Comment by utrack** [comment]
Thank you, that works perfectly :) 

Ah, I didn't account for options defined by grpc-gateway.
Without them, `google.api.http` and protobuf-to-JSON schema should work the same for all languages.
