### ISSUE TITLE
Swagger definition is broken if there's no default error response set

### ISSUE THREAD

**Issue by utrack** [grpc-ecosystem/grpc-gateway#1162]
Introduced by #1127 , refs [utrack/clay#81](https://github.com/utrack/clay/issues/81)

Right now gen-swagger generates broken Swagger def if there's no `.grpc.gateway.runtime.Error` set ([lookup code](https://github.com/grpc-ecosystem/grpc-gateway/pull/1127/files#diff-d419038d63db0fdabc61f0d6cc6683aeR1051)).
Every handler has a link to error definition as "default" response, even if `Error` was not discovered. 

I guess it's better to drop error response definition if `Error` was not found, but still emit a warning (`no message found: Error`). What do you think?
I can send a PR with fix if you're OK with that.

Also, the message can be made better (in fact, generator tries to resolve `.grpc.gateway.runtime.Error`, not just `Error`).

**Comment by johanbrandhorst** [comment]
Hm, don't think I meant to close this.

**Comment by johanbrandhorst** [comment]
@utrack I'd be happy to accept a PR that fixes this, and please include a minimal test example that reproduces the error so we can verify that it fixes the issue.

I thought the error was always linked in, so I'm curious how this happened.
