### ISSUE TITLE
Swagger doc generation got stuck for infinite time if a message refers itself.

### ISSUE THREAD

**Issue by adithya66** [grpc-ecosystem/grpc-gateway#1167]
message FilterNode {
    string Data = 1;
    FilterNode Left = 2;
    FilterNode Right = 3;
}

for this message it is not working.

**Comment by johanbrandhorst** [comment]
Hi Adithya, thanks for the bug report! Would you be interested in fixing this? A first step would be to create a test that reproduces the error, which you're well on your way to doing already! You can try and copy something like https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template_test.go#L974-L1093 into a new function that specifies this message structure and see what happens. From there it should be possible to iterate on a fix :). How does that sound?

**Comment by adithya66** [comment]
Once you introduce such kind of message in protobuf, Generation itself went into infinite loop, so it not possible to write test case.

**Comment by johanbrandhorst** [comment]
That doesn't sound right, I'm sure `protoc-gen-go` is normally able to handle recursive messages. Do you mean `protoc-gen-swagger`?

**Comment by adithya66** [comment]
Yes, protoc-gen-swagger.

**Comment by johanbrandhorst** [comment]
Can you create a minimal reproducible example of this error?

**Comment by adithya66** [comment]
no, we cannot.

**Comment by Romeren** [comment]
Hello good people of grpc-ecosystem!

I ran into the same issue by accident.

I investigated the origin of the issue as well. It is not so much that recursive messages are not allowed, but rather **the combination of recursive messages and the get annotation**.

Example:
```
**  1 syntax = "proto3";           
  2 package swaggerissue;        
  3 
  4 import "google/api/annotations.proto";                                                                       
  5   
  6   
  7 service IssueService {
  8     rpc Issue(Request) returns (Response) {        
  9         option (google.api.http) = {
 10              post: "/api/v1/issue"
 11         };
 12     }
 13 }
 14 
 15 
 16 message Request {
 17     Request request = 1;
 18 }
 19 
 20 message Response {
 21 }
 22 
```
Does work!
However:
```
  1 syntax = "proto3";           
  2 package swaggerissue;        
  3 
  4 import "google/api/annotations.proto";                                                                       
  5   
  6   
  7 service IssueService {
  8     rpc Issue(Request) returns (Response) {        
  9         option (google.api.http) = {
 10              get: "/api/v1/issue"
 11         };
 12     }
 13 }
 14 
 15 
 16 message Request {
 17     Request request = 1;
 18 }
 19 
 20 message Response {
 21 }
```
Does not work, and makes the **protoc-gen-swagger** command run a infinite loop.

Thinking a bit about of what im asking the here, I would argue that it would make no sense to have a recursive message pattern in a HTTP GET query and that the request should be using POST with JSON-body instead.

However, i would also also expect protoc-gen-swagger to spit out a error message saying that recursive messages are not allowed with GET (If you guys agree with my view point that it makes no sense to have them in the first place) and that the annotation should be changed to post.

**Comment by johanbrandhorst** [comment]
Hi @Romeren, thanks a lot! That should allow a test case to be built from which a fix can be implemented. Would you be interesting in contributing this? I agree that an error sounds like the right behaviour here.

**Comment by Romeren** [comment]
Sure.... I havent look to much into the internals of this project, but i expect i would be able to locate the origin of the issue and make a bug fix.
