### ISSUE TITLE
protoc-gen-swagger: lost comment when merging proto files

### ISSUE THREAD

**Issue by coolyrat** [grpc-ecosystem/grpc-gateway#1173]
![image](https://user-images.githubusercontent.com/1881159/76645386-de284380-6593-11ea-86a0-a92dd53a57ad.png)

![image](https://user-images.githubusercontent.com/1881159/76645099-3ad72e80-6593-11ea-850e-f1806bb3971b.png)

[test case](https://github.com/coolyrat/grpc-gateway-merge-test)

**Comment by johanbrandhorst** [comment]
Probably related to https://github.com/grpc-ecosystem/grpc-gateway/issues/746. Would you be interested in contributing a fix for this?

**Comment by coolyrat** [comment]
#1174
