### ISSUE TITLE
protoc-gen-grpc-gateway should warn or fail if a selector does not exist

### ISSUE THREAD

**Issue by andrascz** [grpc-ecosystem/grpc-gateway#1175]
### Steps you follow to reproduce the error:

1.  specify a service config with a selector which does not exist (mistype rpc service name)
2.  generate gateway code
3.  generation does not fail, but ignores the endpoint with a not matched selector

### What did you expect to happen instead:

Generation fails or at least warns me about a non-matched selector

### What's your theory on why it isn't working:

Currently non-matched selectors are gracefully ignored.

**Comment by johanbrandhorst** [comment]
Hi, thanks for the bug report! I take it this affects the yaml configuration only?

Would you be interested in adding this capability?

**Comment by andrascz** [comment]
I assume this can not happen when you annotate the proto file, as you define the binding directly on the rpc of your choice.
But probably the swagger generator should behave the same way.

I can raise a PR although first I need to familiarize myself with the code a bit.

**Comment by andrascz** [comment]
I have a working patchset at https://github.com/Strivacity/grpc-gateway/tree/error-on-unbound-rules-or-methods, as soon as I solved the CLA issue I will raise a PR.
Currently our company is dealing with transitioning to home office because of COVID-19 so processes a bit slower than usual.

**Comment by johanbrandhorst** [comment]
Thanks, no rush from our side, stay safe :slightly_smiling_face:.
