### ISSUE TITLE
Support for custom routing taken from request parameters

### ISSUE THREAD

**Issue by raffis** [grpc-ecosystem/grpc-gateway#1179]
### Description
I would like to have the possibility to route a request with the same verb and path to different grpc methods. This could be done by configuring additional values in an optional option for the gateway in the protobuf specs.

example proto spec:
```
    // Get multiple sessions
    rpc Get(GetSessionListRequest) returns (SessionList) {
        option (google.api.http) = {
            get: "/api/v1/sessions"
        };
    }    // Watch sessions
    rpc Watch(GetSessionListRequest) returns (stream SessionChangeStream) {
        option (google.api.http) = {
            get: "/api/v1/sessions"
        };
    }    // Stream sessions
    rpc Stream(GetSessionListRequest) returns (stream Session) {
        option (google.api.http) = {
            get: "/api/v1/sessions"
        };
    }
```

### Current situation

A request to the endpoint is handled by the first matching rcp method which is `Get()` in the given example.
```
curl http://localhost:8081/api/v1/sessions 
```

There is no way to call the `Stream()` method via the grpc gateway.

### Expected 

It should be possible to route a rest request to different matching rpc services based on the request and not just the verb and the path. For example using a header or a query string.

For example:
```
curl http://localhost:8081/api/v1/sessions -v -H "Accept: application/json" => `Get()`
curl http://localhost:8081/api/v1/sessions -v -H "Accept: application/json+watch" => `Watch()`
curl http://localhost:8081/api/v1/sessions -v -H "Accept: application/json+stream" => `Stream()`
```

While the request parameters are the same `GetSessionListRequest`, the output might be different. This is not really supported in swagger v2 (but it is in openapi v3 where different responses for different content-types may be configured). However in swagger v2 the response would just describe the default response and all other possible responses are not in the schema. 
For example this is the case in the kubernetes swagger spec.

It should be possible to define request parameters which get used to match a handler. This might be header values and/or query string values. Possibly more.

Example spec:
```
    // Get multiple sessions
    rpc Get(GetSessionListRequest) returns (SessionList) {
        option (google.api.http) = {
            get: "/api/v1/sessions"
        };
        option (custom_option) = {
            header: {
              "Accept": "application/json"
           }
        };
    }   

    // Watch sessions
    rpc Watch(GetSessionListRequest) returns (stream SessionChangeStream) {
        option (google.api.http) = {
            get: "/api/v1/sessions"
        };
        option (custom_option) = {
            header: {
              "Accept": "application/json+watch"
           }
        };
    }   

    // Stream sessions
    rpc Stream(GetSessionListRequest) returns (stream Session) {
        option (google.api.http) = {
            get: "/api/v1/sessions"
        };
        option (custom_option) = {
            header: {
              "Accept": "application/json+stream"
           }
        };
    }
```

Note I provided a short example which partially integrates this behaviour, posted on the [slack channel](https://gophers.slack.com/archives/CBATURP1D/p1584544730146200).

**Comment by johanbrandhorst** [comment]
Hi, thanks for opening the discussion. Before we go too far into potential implementations, I'd like to explore how much of this we could solve with existing tools. Did you try to do anything with the custom marshaler/forwardresponseoption I mentioned?
