### ISSUE TITLE
protoc-gen-grpc-gateway-ts plugin for generating Typescript types

### ISSUE THREAD

**Issue by majelbstoat** [grpc-ecosystem/grpc-gateway#1182]
grpc-gateway to JSON using the standard JSON marshaller. Unfortunately, the JS implementation of protobuf appends `List` to the field names of `repeated` fields (see https://github.com/protocolbuffers/protobuf/issues/6773). This means that typescript definitions from those protos don't work. e.g.

```proto
// ontology_service.proto
syntax = "proto3";
package pinian;

import "pinian/question.proto";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

service Ontology {
  rpc GetQuestions (google.protobuf.Empty) returns (QuestionsResponse) {
    option (google.api.http) = {
      get: "/v1/questions"
    };
  }
```

```ts
// ontology_service_pb.d.ts
import * as pinian_question_pb from "../pinian/question_pb";

export namespace QuestionsResponse {
    export type AsObject = {
        questionsList: Array<pinian_question_pb.Question.AsObject>, // wrong
    }
}
```

In addition, it treats int64s as numbers, instead of strings.

The result of this is that we can't strongly type responses from the gateway. I think you're actually doing the right thing, so I wrote a protoc plugin to generate grpc-gateway Typescript types.

Given the same input, it will output:

```ts
// ontology_service_gw.ts
import { Question } from '../pinian/question_gw'

export type QuestionsResponse = {
  questions: Question[]
}
```

Not submitted as a PR, because it's pretty ropey and I don't know if you want it in core. It works well enough for me, but YMMV. Either way, the code is [here](https://gist.github.com/majelbstoat/5f73f58a057123c8d46db66ebbaae987), and maybe it will be helpful for folks even if it doesn't get merged.

**Comment by johanbrandhorst** [comment]
Hey Jamie, thanks for the issue! Are these types generated straight from the proto? We usually see users generate typescript types and functions using the generated swagger file as an intermediate. Maybe that would work for your use case too?

As you surmise I'm not sure we want to take on this in the main repo, especially since it can just live as a third party plugin.

**Comment by majelbstoat** [comment]
Yeah, these are generated straight from the proto :)

**Comment by achew22** [comment]
Jamie, I would be happy to add a link to your repo in the README. WDYT?

**Comment by majelbstoat** [comment]
Oh yeah, you're welcome to. It's a gist, because I don't want to give anyone the impression it's fully supported. Understand if that changes your decision. 😂

https://gist.github.com/majelbstoat/5f73f58a057123c8d46db66ebbaae987

**Comment by achew22** [comment]
Ah, my mistake. I think we should only promote it if it has its own repo with issue tracking.

**Comment by guyisra** [comment]
just my 2 cents - we had the same issue. 
ended up regex the List away after generation
