### ISSUE TITLE
Reference not imported properly

### ISSUE THREAD

**Issue by sgtsquiggs** [grpc-ecosystem/grpc-gateway#1190]
Example project here: https://github.com/sgtsquiggs/grpc-gateway-bug

This is the offending line: https://github.com/sgtsquiggs/grpc-gateway-bug/blob/master/genout/gate/proto/gate.pb.gw.go#L52

`RateType_value` should be `proto_0.RateType_value`

**Comment by sgtsquiggs** [comment]
This should be reopened

**Comment by sgtsquiggs** [comment]
Reproduced this again w/o gogo: https://github.com/sgtsquiggs/grpc_gateway_bug

**Comment by johanbrandhorst** [comment]
Can you try v2-beta.3? https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.0.0-beta.3

**Comment by johanbrandhorst** [comment]
I think the error is probably on this line: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L365. Would you be interested in submitting a PR to fix this? It should be quite easy for you to reproduce with your example.

**Comment by johanbrandhorst** [comment]
https://github.com/sgtsquiggs/grpc-gateway-bug/blob/master/genout/gate/proto/gate.pb.gw.go#L58 this line is also wrong. Corresponding line: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L379

**Comment by sgtsquiggs** [comment]
I believe I fixed this here: https://github.com/grpc-ecosystem/grpc-gateway/issues/1203#issuecomment-642331837

**Comment by johanbrandhorst** [comment]
Closing as dupe (though this one is older)
