### ISSUE TITLE
OpenAPI Models are generated for all grpc messages

### ISSUE THREAD

**Issue by dharmjit** [grpc-ecosystem/grpc-gateway#1192]
There are some grpc methods which I don't intend to use from web and hence I have not annotated them with http rule. 
```
  rpc UpsertInstance(UpsertInstanceRequest) returns (UpsertInstanceResponse) {
  }
```
The swagger that is generated doesn't have any API Paths for this method which is okay. But the messages that belong to this ignored grpc method are still there as schema definitions/models. This makes swagger somtimes unreadable when HTTP APIs are less and there are lot of grpc messages.
```
    "v1UpsertApplicationRequest": {
      "type": "object",
      "properties": {
        "application_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "scope": {
          "type": "string"
        }
      }
    },
```

**Comment by johanbrandhorst** [comment]
I think we iterate over all the types, to fix this we'd have to iterate over all the methods with the annotations and the look at the request and response types and recursively find all the types used. Would you be interested in contributing a fix for this?
