### ISSUE TITLE
No longer generate register...Server function in pb.gw.go?

### ISSUE THREAD

**Issue by chaowanggrab** [grpc-ecosystem/grpc-gateway#1195]
I have protoc 3.11.4 and latest grpc-gateway

We used to run something like 
`protoc -I/usr/local/include -I. \
 -I$GOPATH/src \
 -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
 --go_out=plugins=grpc:. \
 --grpc-gateway_out=logtostderr=true:. \
 --swagger_out=logtostderr=true:. \
 example/echo_service.proto` in order to update the apis. 

Before, it generates Register...Server(ctx context.Context, mux *runtime.ServeMux, server {{$svc.GetName}}Server) error {} function (https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L564). However, now the generated pb.gw.go does not have the server related functions.

I simply follow the readme and it would not get to service related functions too. But I am not sure it's only happen on mine or not. I noticed in the examples folder, the server related functions are still occur in pb.gw.go.

Did I miss anything?

**Comment by johanbrandhorst** [comment]
Hi, that is very strange. Is it possible that you removed the http annotations from your protofile? It definitely should still be there. Maybe you could join the #grpc-gateway channel on gophers slack (https://invite.slack.golangbridge.org/) and I can help you debug it? This is not the right medium.

**Comment by chaowanggrab** [comment]
Yeah sure. thanks.

Here is my protofile:
`syntax = "proto3";

package example;

import "google/api/annotations.proto";

message StringMessage {
    string value = 1;
}

service EchoService {
    rpc Echo(StringMessage) returns (StringMessage) {
        option (google.api.http) = {
          post: "/v1/example/echo"
          body: "*"
        };
    }
}
`
