### ISSUE TITLE
swagger: support path parameters in streaming request

### ISSUE THREAD

**Issue by vtolstov** [grpc-ecosystem/grpc-gateway#1196]
now protoc-gen-swagger does not allow path parameters in streaming. i know that grpc-gateway does not support it, but for example go-micro supports it via api gateway.(websocket based). What you think about allow to generate swagger with path parameters in streaming, but with some warning?

**Comment by johanbrandhorst** [comment]
Is this request streaming or response streaming? I didn't know the grpc-gateway didn't support path parameters in _response_ streaming requests?

**Comment by vtolstov** [comment]
request steaming

**Comment by johanbrandhorst** [comment]
Sorry, until the grpc-gateway supports this natively I don't think we're going to add anything to annotate our generated swagger files. There is currently no one working on supporting this, AFAIK. You can, however, use the websocket wrapper library for this: https://github.com/tmc/grpc-websocket-proxy.

**Comment by vtolstov** [comment]
but why?

**Comment by johanbrandhorst** [comment]
It will add maintenance burden (extra code, could be buggy). It will add user burden (extra flag/documentation). The cost is higher than the benefit.

**Comment by vtolstov** [comment]
we already ave all needed code, we need only modify one line to display log and continue

**Comment by johanbrandhorst** [comment]
OK, if I missed how easy this would be to implement, could you make a PR that adds this feature? We can review it then and decide :slightly_smiling_face:.
