### ISSUE TITLE
Use different field name in gateway

### ISSUE THREAD

**Issue by Glyphack** [grpc-ecosystem/grpc-gateway#1197]
Is it possible to use different name from proto file for a field In gateway?
Suppose I have a message with a field named `new_name`, I want to be able use `old_name` field in gateway for this field.
Can gateway marshaller fill the `new_name` field with value in the `old_name`?

**Comment by johanbrandhorst** [comment]
Could you please reach out to us on the #grpc-gateway slack channel on Gophers slack (https://invite.slack.golangbridge.org/) for these type of support questions? The issue tracker is not the right place.
