### ISSUE TITLE
1.14 breaks protoc-gen-go-json

### ISSUE THREAD

**Issue by vivangkumar** [grpc-ecosystem/grpc-gateway#1199]
Hi there!

After moving public packages into `internal` as part of https://github.com/grpc-ecosystem/grpc-gateway/pull/1146, [protoc-gen-go-json](https://github.com/mitchellh/protoc-gen-go-json) is now broken because it depended on the [`codegenerator`](https://github.com/mitchellh/protoc-gen-go-json/blob/master/main.go#L12) and [`descriptor`](https://github.com/mitchellh/protoc-gen-go-json/blob/master/main.go#L13) packages.

This is very similar to: https://github.com/grpc-ecosystem/grpc-gateway/issues/1161 and https://github.com/grpc-ecosystem/grpc-gateway/issues/1154

I think it would require moving the package back into the public namespace for the package to not be broken.

**Comment by johanbrandhorst** [comment]
Hi Vivan, thanks for raising the issue. I'll move those packages back to the public API. Unfortunately I'm not able to make a patch release right now, so you'll have to use an older release.

**Comment by vivangkumar** [comment]
@johanbrandhorst Thanks for the very quick response! Appreciate it - i'll follow this thread for any updates when you've moved the packages back into the public namespace.

**Comment by johanbrandhorst** [comment]
As I mentioned, I can't make a patch release for this right now, so please use 1.13 until https://github.com/grpc-ecosystem/grpc-gateway/pull/1193#issuecomment-610243761 is resolved.

**Comment by johanbrandhorst** [comment]
(Unless you want to use master, which is also fine)

**Comment by vivangkumar** [comment]
That works, thank you!

**Comment by sesposito** [comment]
Could these packages be made public again in a future release please? 

I've relied on them to build a custom generator and would like to upgrade it to use the protobuf v2 libs, but I'm stuck because these packages have now been made internal.
