### ISSUE TITLE
Go gRPC Gateway - Type of one field in JSON is not same as in proto

### ISSUE THREAD

**Issue by xs2tarunkukreja** [grpc-ecosystem/grpc-gateway#1201]
We have one gRPC Go server which is wrapped by Grpc Gateway. So, out web portal is communicated with Gateway in Http protocol and internally gRPC gateway and gRPC server are communicating by gRPC protocol.

Most of the call is working fine. Only one call response is having an issue. Type specified in proto file is integer but JSON response having type as String.

Some useful details -
We are having 2 protos file - One file is imported in another proto file.

Type issue is coming in imported file message.

**Comment by johanbrandhorst** [comment]
I'm reading between the lines here, but I assume you're using a `int64` or `uint64` type for this field? See https://github.com/grpc-ecosystem/grpc-gateway/issues/438 for more discussion, but the short answer is, JSON doesn't support the full range of 64bit integers, so we're forced to use strings to be accurate for large numbers. I will preemptively close this, but please let me know if I've misunderstood.

**Comment by xs2tarunkukreja** [comment]
Yeah, we are using int64. But the value of the same is small. In past, before using go, code was written in Node JS and JSON was supporting that value.

**Comment by johanbrandhorst** [comment]
You can use an `int32` type and it will use an integer in the return value.
