### ISSUE TITLE
response_body of http rule is ignored in case of server streaming

### ISSUE THREAD

**Issue by adasari** [grpc-ecosystem/grpc-gateway#1202]
HI Team,

response_body field of http rule is ignored in case of server streaming. i checked the template.go and handler.go, seems they are not checking ResponseBody type.

[template.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c9d3eb7ca8e28a7c8db327d6ef63902bfbfd778/protoc-gen-grpc-gateway/internal/gengateway/template.go#L669)
[handler.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c9d3eb7ca8e28a7c8db327d6ef63902bfbfd778/runtime/handler.go#L64)

Also noticed stream response is wrapped in a map [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c9d3eb7ca8e28a7c8db327d6ef63902bfbfd778/runtime/handler.go#L193). is there any specific reason ?

Thanks

**Comment by johanbrandhorst** [comment]
Hi Anil, thanks for the issue report! I think when we first added support for the `response_body` (https://github.com/grpc-ecosystem/grpc-gateway/pull/712) we didn't consider it in the light of streaming RPCs. There may be a sensible way to implement this for streaming APIs, so lets discuss!

The reason we're using a wrapper by default for streaming responses is so that users can use a single type to marshal the chunks, while still allowing us to return an error at any point in the stream. This means the error has to always be there.

If a user were to use the ResponseBody though, we would allow the user to stream whatever they want.

What ideas do you have for how to implement this? I can't promise it will be merged, but feel free to open a Pull Request and we can take a look together.

**Comment by adasari** [comment]
At high level, below changes should work. (not tested yet)

1. Following code in [handler.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c9d3eb7ca8e28a7c8db327d6ef63902bfbfd778/runtime/handler.go#L64)
```
var buf []byte
switch {
case resp == nil:
	buf, err = marshaler.Marshal(errorChunk(streamError(ctx, mux.streamErrorHandler, errEmptyResponse)))
default:
	if rb, ok := resp.(responseBody); ok {
		buf, err = marshaler.Marshal(rb.XXX_ResponseBody())
	} else {
		buf, err = marshaler.Marshal(map[string]proto.Message{"result": resp})
	}
}
```
2.  In if block in [template.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c9d3eb7ca8e28a7c8db327d6ef63902bfbfd778/protoc-gen-grpc-gateway/internal/gengateway/template.go#L669)

```
{{ if $b.ResponseBody }}
forward_{{$svc.GetName}}_{{$m.GetName}}_{{$b.Index}}(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { 
	res, err := resp.Recv() 
	return response_{{$svc.GetName}}_{{$m.GetName}}_{{$b.Index}}{res}, err
}, mux.GetForwardResponseOptions()...)
{{ else }}
forward_{{$svc.GetName}}_{{$m.GetName}}_{{$b.Index}}(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)
{{end}}
```

**Comment by johanbrandhorst** [comment]
It's hard to me to say from here, but we definitely would need a test for this. How about adding a test to the existing test server?

We could add a new RPC that returns a stream of `ResponseBody` [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/response_body_service.proto#L57), and then add a test that uses this [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/integration/integration_test.go#L1467).

**Comment by adasari** [comment]
cool. will work on it. thanks.

**Comment by adasari** [comment]
@johanbrandhorst raised CL (https://github.com/grpc-ecosystem/grpc-gateway/pull/1205). please take a look.

generate step failed to due to proto error. not sure if this is something related to changes. pleae take a look and suggest. thanks.

**Comment by johanbrandhorst** [comment]
If the generate step failed it will be related to the changes.

**Comment by johanbrandhorst** [comment]
Please try regenerating locally by following the instructions in CONTRIBUTING.md

**Comment by adasari** [comment]
after latest pull, seems it is failing in local too. But i didnt understand the error. i can see data in ResponseBodyIn. this is not new.would you mind helping in pointing the error ? 
```protoc -I /usr/local/bin//../include -I. -Ithird_party/googleapis --plugin=bin/protoc-gen-grpc-gateway --grpc-gateway_out=logtostderr=true,allow_repeated_fields_in_body=true,Mgoogle/protobuf/field_mask.proto=google.golang.org/genproto/protobuf/field_mask,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor,Mexamples/internal/proto/sub/message.proto=github.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/sub,grpc_api_configuration=examples/internal/proto/examplepb/unannotated_echo_service.yaml:. examples/internal/proto/examplepb/echo_service.proto examples/internal/proto/examplepb/a_bit_of_everything.proto examples/internal/proto/examplepb/stream.proto examples/internal/proto/examplepb/flow_combination.proto examples/internal/proto/examplepb/non_standard_names.proto examples/internal/proto/examplepb/wrappers.proto examples/internal/proto/examplepb/unannotated_echo_service.proto examples/internal/proto/examplepb/use_go_template.proto examples/internal/proto/examplepb/response_body_service.proto
W0409 14:53:12.460320     419 services.go:38] No HttpRule found for method: ABitOfEverythingService.NoBindings
W0409 14:53:12.467545     419 services.go:38] No HttpRule found for method: AnotherServiceWithNoBindings.NoBindings
--grpc-gateway_out: no field "data" found in ResponseBodyOut
```

**Comment by adasari** [comment]
i found the issue. not sure why it is there. let me fix. thanks.

**Comment by johanbrandhorst** [comment]
Fixed by https://github.com/grpc-ecosystem/grpc-gateway/pull/1208
