### ISSUE TITLE
api annotation placeholder character case

### ISSUE THREAD

**Issue by vtolstov** [grpc-ecosystem/grpc-gateway#1207]
does grpc-gateway  have rules for path syntax in proto annotations?
all examples have lowercase {uuid}/{name} or so if request struct have SomeComelCase field, in which case i need to specify placeholder in path ? 
Thanks!

**Comment by johanbrandhorst** [comment]
I think it just has to match the field _name_ directly. Note that it is standard protobuf practice to use snake_case for field names and it may break assumptions somewhere.

If that doesn't work, please raise a bug.
