### ISSUE TITLE
Feature request: Reject call if there are parameters/fields that don't exist in the protobuf

### ISSUE THREAD

**Issue by veqryn** [grpc-ecosystem/grpc-gateway#1210]
I would like the grpc-gateway to have the ability to reject http calls that are made, where there are fields (http query parameters, body fields, etc) specified that do not match the allowed fields.

For example, this could be in the form of a `ServeMuxOption` that returns a 400 response.

My use case is that clients often don't know they have misspelled fields in their request (such as filters, etc), because the request is not rejected. By the time my handlers receive the request, they don't even know if there were any wrong fields specified.

**Comment by johanbrandhorst** [comment]
Sounds like a great feature! Is this possible with a JSON marshaller that's configured to disallow unknown fields?

**Comment by veqryn** [comment]
I have no idea honestly, I'll have to take a look.

**Comment by srenatus** [comment]
💯 I'd love that, too. It's so easy to mistakenly send a (just slightly) wrong payload and it ends up creating much confusion with API users.

**Comment by johanbrandhorst** [comment]
Wait we already have this: https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#DisallowUnknownFields

**Comment by johanbrandhorst** [comment]
Please report back if this doesn't already fix your issue

**Comment by paskozdilar** [comment]
For future readers:

It seems like this feature was added in v1.9.3, but doesn't exist in v2.
The [PR removing it](https://github.com/grpc-ecosystem/grpc-gateway/pull/1386) says it's now controlled by marshaller options.

The options I've used for this purpose are:

```go
mux := runtime.NewServeMux(runtime.WithMarshalerOption(
	runtime.MIMEWildcard, &runtime.JSONPb{
		UnmarshalOptions: protojson.UnmarshalOptions{
			AllowPartial:   true,
			DiscardUnknown: false,
		},
	},
))
```
