### ISSUE TITLE
custom unmarshal response error

### ISSUE THREAD

**Issue by FunnyDevP** [grpc-ecosystem/grpc-gateway#1211]
# how to custom http response error. when cannot unmarshal http request data to model

Ex.
```
From...
{
    "error": "json: cannot unmarshal number into Go value of type string",
    "code": 3,
    "message": "json: cannot unmarshal number into Go value of type string"
}
To...
{
  "error": {
    "field1": 11013,
    "field2": 1401,
    "field3": 0,
    "field4": "unmarshal type error"
  }
}
```

**Comment by johanbrandhorst** [comment]
Hi @FunnyDevP, thanks for raising your issue. There is a section on our documentation site about how to configure a custom error handler: https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html

**Comment by Manask322** [comment]
New Link to Documentation -  https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/
