### ISSUE TITLE
Regeneration commands don't regenerate all files

### ISSUE THREAD

**Issue by AyushG3112** [grpc-ecosystem/grpc-gateway#1229]
I am working on https://github.com/grpc-ecosystem/grpc-gateway/pull/1228, and would like to regenerate `examples/internal/helloworld/helloworld.pb.gw.go`

I ran the commands as per [this](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes), and it renegerated all examples except that one

**Comment by johanbrandhorst** [comment]
Huh, that really should regenerate all of them, if it doesn't regenerate that one it's a bug! Let me have a look around.

**Comment by AyushG3112** [comment]
@johanbrandhorst any command I can run specifically to that for now so that I can proceed further?

**Comment by johanbrandhorst** [comment]
Just ignore it for now, I think I found the issue and we can rebase later.
