### ISSUE TITLE
proto function not define in yaml then grpc-gateway_out err

### ISSUE THREAD

**Issue by xuchunhua-com** [grpc-ecosystem/grpc-gateway#1233]
aggregate.proto
service AggregateService {
    rpc InternalFunc (base.Empty) returns (HomeResp);
    rpc GetHotKeyword (base.Empty) returns (GetHotKeywordResp);
}

app.yaml
type: google.api.Service
config_version: 3
http:
  rules:
    - selector: aggregate.AggregateService.GetHotKeyword
      post: /goAppApi/aggregate/getHotKeyword
      body: "*"

protoc -I/usr/local/include -Iproto --grpc-gateway_out=logtostderr=true,paths=source_relative,grpc_api_configuration=./proto/app.yaml:gen/gw/app/ ./proto/aggregate/aggregate.proto

--grpc-gateway_out: HTTP rules without a matching selector: AggregateService .InternalFunc

**Comment by johanbrandhorst** [comment]
Does your `proto` file have a package? This is an error when you try to map to a function that is not found.

Try:
```protobuf
syntax="proto3";

package aggregate;

service AggregateService {
rpc InternalFunc (base.Empty) returns (HomeResp);
rpc GetHotKeyword (base.Empty) returns (GetHotKeywordResp);
}
```

**Comment by johanbrandhorst** [comment]
See https://github.com/grpc-ecosystem/grpc-gateway/pull/1178 for more information

**Comment by xuchunhua-com** [comment]
> See #1178 for more information

thanks
i use old version,       it's work
