### ISSUE TITLE
What is the proper way to manage the Google proto dependencies?

### ISSUE THREAD

**Issue by thecodejunkie** [grpc-ecosystem/grpc-gateway#1240]
Hi

I'm quite new to this (protobuf and Go) and I was wondering what the proper way is to handle the dependency on the Google annotations.proto file?

The documentation mentions

> Add a google.api.http annotation to your .proto file

but there's no context on how I am supposed to make sure that file is available when I run protoc? Is the intention that I should download a local copy of the file and store it with the rest of my code?  I can't find any info on a Go module I could use to get the files locally on my machine either and (as I've understood it) the annotations.proto file isn't or of the well-known types so it's not available out of the box either

Thanks for any advice on how to properly manage the 3rd party proto dependencies that are required by grpc-gateway

**Comment by johanbrandhorst** [comment]
Hi Andreas, thanks for your interest in the project! I recently added a section on this to the README:

> You will need to provide the required third party protobuf files to the protoc compiler. They are included in this repo under the third_party/googleapis folder, and we recommend copying them into your protoc generation file structure. If you've structured your protofiles according to something like the Buf style guide, you could copy the files into a top-level ./google folder.

This is visible under step 3 of the "usage" instructions: https://github.com/grpc-ecosystem/grpc-gateway#usage.

Evidently, this was not enough for you to find it, so I'd love some feedback on a better place to add this. Would you like to contribute something?

Finally, let me be the first to say that I'm not happy with this as a solution, but there isn't really anything better available right now. Something like the [buf schema registry](https://buf.build/docs/roadmap#buf-schema-registry) should help with this in the long term but that isn't available yet.

**Comment by thecodejunkie** [comment]
Hi

Oh, yeah I did completely missed that part 😒 I think my brain was looking for it in the text for the second step and then scanned down to the code examples in the third one.

Maybe the paragraph, that you quoted, should be moved up to the end of the second step and kept as a quote (to make it stand out)? And maybe also add a commend the path should be referenced using the `protoc` parameter `-I` ? Happy to send a PR if you agree. 

I'm using a `tools.go` to track my build dependencies and a Makefile to build, so what I ended up doing was grabbing the `grcp-gateway` version from my `go.mod` using

```make
PROTOC_GEN_GATEWAY_VERSION := "$(shell grep "grpc-gateway" go.mod | awk '{print $$2}')"
```

and then in my make target, that I used to build, I pass the path to `protoc` (my Makefile runs `go mod download` if needed)

```make
-I ${GOPATH}/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@${PROTOC_GEN_GATEWAY_VERSION}/third_party/googleapis/ \
```

This way I ensure that I always include the files from the version of `grpc-gateway` that I am referencing in my `tools.go` (+ me and my team will all get the same experience)

**Comment by johanbrandhorst** [comment]
Yeah that is certainly one way to do it, but it makes some assumptions about the implementation details of go modules and I personally don't use it like that. I'm glad it works for you though.

> Maybe the paragraph, that you quoted, should be moved up to the end of the second step and kept as a quote (to make it stand out)? And maybe also add a commend the path should be referenced using the protoc parameter -I ? Happy to send a PR if you agree.

The first suggestion sounds good, the second one I think is implied in the suggestion about using the Buf style guide layout (it doesn't need to be included explicitly if all dependencies are in the same tree). Please do submit a PR!

**Comment by thecodejunkie** [comment]
> Yeah that is certainly one way to do it, but it makes some assumptions about the implementation details of go modules and I personally don't use it like that. I'm glad it works for you though.

I totally understand that this is a very esoteric solution 😄 Mostly posted it here in-case someone else ends up here from Google and doesn't want to manage a copy of the files.

> Please do submit a PR!

Done https://github.com/grpc-ecosystem/grpc-gateway/pull/1241

Keep up the great work!
