### ISSUE TITLE
how to get customezing header

### ISSUE THREAD

**Issue by jackwener** [grpc-ecosystem/grpc-gateway#1244]
## phenomenon 

send HTTP request with customezing header
(add by postman)
"id": "123456"

I achieve this function by the following code：
```go
md, ok := metadata.FromIncomingContext(ctx)
fmt.Prlnln(md)
```
but output don't include customezing header kv

**Comment by johanbrandhorst** [comment]
Hi @jackwener, thanks for your issue. If you want to map a custom header, you can either prefix it with `Grpc-metadata-` and have it translated automatically:
```
"Grpc-metadata-id": "123456"
```
```go
md, ok := metadata.FromIncomingContext(ctx)
// md["grpcgateway-id"] == "123456"
```

Or add an [IncomingHeaderMatcher](https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime?tab=doc#WithIncomingHeaderMatcher). We have a section on how to do that in the documentation: https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html.

**Comment by jackwener** [comment]
> Hi @jackwener, thanks for your issue. If you want to map a custom header, you can either prefix it with `Grpc-metadata-` and have it translated automatically:
> 
> ```
> "Grpc-metadata-id": "123456"
> ```
> 
> ```go
> md, ok := metadata.FromIncomingContext(ctx)
> // md["grpcgateway-id"] == "123456"
> ```
> 
> Or add an [IncomingHeaderMatcher](https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime?tab=doc#WithIncomingHeaderMatcher). We have a section on how to do that in the documentation: https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html.

thanks,  I'm sorry I didn't read the document carefully。
But it seem that ` translated automatically`  not in document.

**Comment by johanbrandhorst** [comment]
The first part is in the README: https://github.com/grpc-ecosystem/grpc-gateway#features

**Comment by mispon** [comment]
@johanbrandhorst hi! 
Isn't `Grpc-Metadata-` not trimmed and the rest of the header passed on?

I send `curl -H "Grpc-Metadata-Custom-Data: test" ...` and receive `custom-data: test` in incoming context, because of https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/mux.go#L147-L148

**Comment by johanbrandhorst** [comment]
Yes, that is true for incoming headers. For outgoing gRPC metadata, we prefix with `grpcgateway-` before sending as a response header.

**Comment by mispon** [comment]
@johanbrandhorst  Thanks for the reply!
If it's not too much trouble, can you please expand on why multiple branches of behavior are needed?

1. If the header is in “permanent”, then it is propagated with the grpcgateway prefix, e.g. Accept => grpcgateway-Accept
2. If HTTP header itself arrives with Grpc-Medatada prefix, it is cut off and forwarded as it is, e.g. Grpc-Metadata-User-Id => User-Id.
3. If the first two cases failed, then the header is not thrown through at all.

Why can't we unify this behavior, for example, so that all HTTP headers are always thrown to gRPC metadata with the same prefix?

**Comment by johanbrandhorst** [comment]
It's already possible for you to configure the gateway to include all HTTP headers in the gRPC metadata with a custom [IncomingHeaderMatcher](https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#WithIncomingHeaderMatcher). I don't remember exactly why we don't do it automatically already (could be security reasons), but we can't change that behavior now without breaking users.
