### ISSUE TITLE
HTTP GET with query params error

### ISSUE THREAD

**Issue by jackwener** [grpc-ecosystem/grpc-gateway#1245]
https://github.com/grpc-ecosystem/grpc-gateway/blob/ead3fc06c322daada4418abcbe00e07e5017e80a/third_party/googleapis/google/api/http.proto#L117

I found it is supported in above document.

but something went wrong in practice

## phenomenon

``` yaml
get: /dyeing/appid/{appid}/id_type/{id_type}?page_num={page_num}&page_size={page_size}
```

error

`--grpc-gateway_out: unexpected token "?page_num=" after segments "dyeing/appid/{appid}/id_type/{id_type}": /dyeing/appid/{appid}/id_type/{id_type}?page_num={page_num}&page_size={page_size}`

**Comment by johanbrandhorst** [comment]
Hi again @jackwener, in the future could you please join the support channel on Gophers slack (#grpc-gateway) like the issue template asks? This is not a bug but a simple misunderstanding.

See https://github.com/grpc-ecosystem/grpc-gateway/blob/ead3fc06c322daada4418abcbe00e07e5017e80a/third_party/googleapis/google/api/http.proto#L93-L95. The query parameters are implicitly bound to any variables not specified in the path. What you're looking for is

```
get: /dyeing/appid/{appid}/id_type/{id_type}
```
That should allow
```
GET /dyeing/appid/{appid}/id_type/{id_type}?page_num={page_num}&page_size={page_size}
```
To work.
