### ISSUE TITLE
Remove result/error envelope in streaming RPC response

### ISSUE THREAD

**Issue by adasari** [grpc-ecosystem/grpc-gateway#1254]
grpc-gateway wraps stream response in result/error envelope. 

```
{"result": {"data": {}}, "error": {}}
```
Does result/error envelope required ? nice to have an option to skip result/error envelope ?
Could you help me to understand the reasons behind result/error envelope design ?

in case http byte stream apis (ex: download rpc), this extra envelope is not useful.

**Comment by johanbrandhorst** [comment]
You should be able to use [`google/api/httpbody.proto`](https://github.com/googleapis/googleapis/blob/master/google/api/httpbody.proto) as the return stream type and use https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/marshal_httpbodyproto.go and it will not wrap your messages. I've not tested this with streaming RPCs but it should work I think?

**Comment by adasari** [comment]
Sure. let me find some examples and try it. thanks.

**Comment by adasari** [comment]
i was reading https://grpc-ecosystem.github.io/grpc-gateway/docs/httpbody.html, can we use it with gRPC stream ? basically i am building download rpc which works as gRPC stream for clients and http byte stream for http clients.

**Comment by johanbrandhorst** [comment]
If it doesn't already work with streaming we should try to make sure it can work. Can you test it?

**Comment by adasari** [comment]
i couldn't find examples. Can you point me to right examples ? thanks.

**Comment by johanbrandhorst** [comment]
Doesn't look like we have any, but we have this: https://grpc-ecosystem.github.io/grpc-gateway/docs/httpbody.html

**Comment by adasari** [comment]
Seems not working.

```
 rpc Download(HelloRequest) returns (stream google.api.HttpBody) {
    option (google.api.http) = {
      post : "/v1/download"
      body: "*"
		};
  }
```
gRPC implementation

```
func (s *server) Download(req *testpb.HelloRequest, stream testpb.Greeter_DownloadServer) error {
	stream.Send(&httpbody.HttpBody{
		ContentType: "text/html",
		Data:        []byte("124353"),
	})

	return nil
}

```
response 

```
{
    "result": {
        "content_type": "text/html",
        "data": "MTI0MzUz"
    }
}
```

mux is

```
mux := http.NewServeMux()
	gwmux := runtime.NewServeMux(runtime.WithIncomingHeaderMatcher(CustomMatcher), runtime.WithOutgoingHeaderMatcher(CustomOutMatcher))
	runtime.SetHTTPBodyMarshaler(gwmux)
	mux.Handle("/", gwmux)
``` 

httpbody.HttpBody type conversion is not ok. hence else block is executed.
```
func (h *HTTPBodyMarshaler) Marshal(v interface{}) ([]byte, error) {
	if httpBody, ok := v.(*httpbody.HttpBody); ok {
		return httpBody.Data, nil
	}
	return h.Marshaler.Marshal(v)
}
```

**Comment by johanbrandhorst** [comment]
Okay, lets try and get this in for v2, if you'd like.

**Comment by johanbrandhorst** [comment]
This is fixed in v2
