### ISSUE TITLE
How to implement field validation for optional parameter

### ISSUE THREAD

**Issue by eldad87** [grpc-ecosystem/grpc-gateway#1256]
Hi,
I'm trying to implement a request with optional (omit) parameters with validation constrains.
As far as I understand, optional field can be achieved using [oneof](https://stackoverflow.com/questions/42622015/how-to-define-an-optional-field-in-protobuf-3).
In addition, protoc-gen-validate supports [oneof](https://github.com/envoyproxy/protoc-gen-validate/#oneofs).

Unfortunately, when using oneof, the swagger definition and grpc-ecosystem are changed and I can't use the original field name.

Given the following proto:
```
syntax = "proto3";
package pb;

import "google/api/annotations.proto";
import "github.com/envoyproxy/protoc-gen-validate/validate/validate.proto";

service Account {
    rpc Update(UpdateRequest) returns (UpdateResponse) {
        option (google.api.http) = {
          put: "/v1/account/{ID}"
          body: "*"
        };
    }
}

message ID {
    uint32 ID = 1 [(validate.rules).uint32.gte = 0];
};

message UpdateRequest {
    int32 ID = 1;
    string FirstName = 2 [(validate.rules).string.min_len = 2];
    oneof LastName {
        bool LastNameNull = 3;
        string LastNameValue = 4 [(validate.rules).string.min_len = 2];
    }
}

message UpdateResponse {
    int32 ID = 1;
    string FirstName = 2;
    string LastName = 3;
}
```

1. Whenever there is a oneof in the protobuf definition all the keys are simply added to the object: LastNameNull & LastNameValue.  In other words, My request payload should contain `LastNameValue` instead of simply `LastName`. 
Keep in mind that my Request struct fields should have the same naming as my DB struct for marshaling purposes, therefore the following will not work for me As it adds `LastNameValue isUpdateRequest_LastNameValue` to the generated struct: 
```
    oneof LastNameValue {
        bool LastNameNull = 3;
        string LastName = 4 [(validate.rules).string.min_len = 2];
    }
```

2. If I try to send a request with `FirstName` defined, I get the following error `json: cannot unmarshal string into Go value of type pb.isUpdateRequest_LastName`.
According to @ivucica's [comment](https://github.com/grpc-ecosystem/grpc-gateway/issues/723#issuecomment-413909595) I should implement UnmarshalJSONPB for that object. Unfortunately `pb.isUpdateRequest_LastName` is an interface and therefore his suggestion is not applicable.

Please advise how to handle this situation,
Thanks!

**Comment by johanbrandhorst** [comment]
I would suggest using `google.protobuf.StringValue last_name = 1` from the Well Known Type `google/protobuf/wrappers.proto`: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto. That should still work with your validation and will allow it to be nullable.

**Comment by eldad87** [comment]
Hi @johanbrandhorst ,
Thank for your input. I will definitely give it a try.

The next issue I'm facing is how to unify the DB & API validation errors. Both using different structs which can result in different naming.
I've wrote the following Interceptor to try and minimaize the situation:
- gRPC incoming request ([src](https://github.com/eldad87/go-boilerplate/blob/master/src/pkg/grpc/middleware/validator/protoc_gen_validate/server_interceptors.go))
- gRPC interceptor that check if the "upstream" response type is v9.ValidationErrors and convert it go grpcErrors.NewBadRequest ([src](https://github.com/eldad87/go-boilerplate/blob/master/src/pkg/grpc/middleware/status/validator.v9/server_interceptors.go))

But still, I'm using different structs and therefore there will be different Naming in the errors.

**Comment by johanbrandhorst** [comment]
I would say that the conversion of database validation errors into gRPC error is the responsibility of your gRPC server layer, not a gRPC interceptor. Whatever is returned from the gRPC server implementation should ideally already be a gRPC status. But this is the sort of thing that the #grpc channel on Gophers slack is great for discussing, so I'm going to close this issue.
