### ISSUE TITLE
Flaky Timeout test

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#1258]
As illustrated by https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/281/workflows/57fdb518-e3ee-4f16-9a55-0f417732ca80/jobs/7654/steps, one of the integration tests is sometimes failing with the wrong error. We should figure out why this is happening and fix it.

This should be a good issue to get introduced to the codebase. The test is here: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/integration/integration_test.go#L1302

**Comment by Abhi-khandelwal** [comment]
Any idea why I am getting this error?

`WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	           A future release of golang/protobuf will delete this package,
	           which has long been excluded from the compatibility promise.`

**Comment by Abhi-khandelwal** [comment]
I think we should use the "google.golang.org/protobuf/compiler/protogen" package as adviced

https://github.com/golang/protobuf/blob/d04d7b157bb510b1e0c10132224b616ac0e26b17/protoc-gen-go/generator/generator.go#L10-L11

**Comment by johanbrandhorst** [comment]
Hi Abhi, indeed, we've replaced the use of that package in our `v2` branch, which we're close to making a first release of soon.

On another note, I think this was fixed by changing the ports used for some of the tests, so I'm going to close it.
