### ISSUE TITLE
Getting parsed runtime.Pattern from server mux

### ISSUE THREAD

**Issue by sadlil** [grpc-ecosystem/grpc-gateway#127]
On development one of my scenario is to develop - one URL pattern to handle both usual verbs and OPTIONS verbs to allow CORS request for that specifi URL. Probably one of the way is to implement http.custom type for handle this request. But this request doesn't need any server side processing. only some common task as [this](http://www.html5rocks.com/en/tutorials/cors/). we can get the options request done from the gateway without sending it to server. For this we need the processed runtime.Patterns that are auto generated from the proto file. I was able to do this by hand by writing a file in same paclkage with *.pb.gw.go as i couldn't find anything to get the processed patterns. But this looks dirty.

it would be good if there is a way that can return those process Patterns.

**Comment by yugui** [comment]
`mux` is just an implementation of `http.Handler`.  So you can wrap it with anything you want as you can do in generic `http.Handler`s.

**Comment by achew22** [comment]
Just doing a little bit of tidying. I hope that your question was answered in a way that let your project continue. If you have any more questions feel free to open another issue.
