### ISSUE TITLE
Issue with use of field_mask when using protoc-gen-swagger

### ISSUE THREAD

**Issue by bvwells** [grpc-ecosystem/grpc-gateway#1379]
While implementing a patch request using grpc-gateway I was following the documentation here:

https://grpc-ecosystem.github.io/grpc-gateway/docs/patch.html

The documentation states that it is possible to hide the field mask from the generated open api spec:

> If you want to use PATCH with fieldmask hidden from REST request only include the request message in the body.
...

When I following the example, the type ```protobufFieldMask``` is always generated in the open api specification from the protoc-gen-swagger generator.

### Steps you follow to reproduce the error:

Take the following proto definition:

```html
syntax = "proto3";
option go_package = "github.com/bvwells/grpc-gateway-example/proto/beers";

import "google/api/annotations.proto";
import "google/protobuf/field_mask.proto";

message Thing {
  string id = 1;
  string name = 2;
}

message UpdateThingRequest {
    Thing thing = 1;
    google.protobuf.FieldMask update_mask = 2;
}

message UpdateThingResponse {
    Thing thing = 1;
}

// Thing service.
service ThingService {

    // UpdateThing updates a thing given its ID.
    rpc UpdateThing(UpdateThingRequest) returns (UpdateThingResponse) {
        option (google.api.http) = {
            patch: "/api/v1/things/{thing.id}"
            body: "thing"
        };
    }
}
```

Run the protoc-gen-swagger generator:

```
protoc -I. --swagger_out=disable_default_errors=true,logtostderr=true:./ api.proto
```

### What did you expect to happen instead:

I expected the open api type ```protobufFieldMask``` not to be part of the api definition as it is not used.

Let me know if you require any further information.

**Comment by bconway** [comment]
Did you ever find closure on this? Based on my reading of other bugs/PRs, it appears that this is intentionally populated in the OpenAPI spec (see the few bugs on correct FieldMask descriptions), but I also expected it to be *hidden* as the documentation describes.

The best workaround I've employed so far is something like:
```
  // Fields to update. Automatically populated by a PATCH request.
  google.protobuf.FieldMask update_mask = 2;
```

Any other ideas?
