### ISSUE TITLE
generate OpenAPI/swagger documentation at run time?

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#138]
it'd be nice to easily serve up a live representation of the OpenAPI/swagger specification versus going to disk.

**Comment by joeblew99** [comment]
+1

This would be nice. I presume you mean the swagger-ui ?

**Comment by philips** [comment]
@joeblew99 @tmc You can just build it into the binary as I do in grpc-gateway-example: https://github.com/philips/grpc-gateway-example/blob/master/echopb/swagger.go

**Comment by tmc** [comment]
@joeblew99 I meant the actual specs. It should be out of scope to include swagger-ui in this project.

@philips yeah, I go-rice my specs into the binary now but it's a bit janky.

**Comment by achew22** [comment]
@tmc This seems to me like it might be a problem better solved by your build system. I have implemented it myself using https://bazel.build. I assume that the //go:generate directive would allow you to achieve the same result but I have no real experience with it so I can't be sure.

I'm going to close this to try to get the bug list down to a single page but feel free to reopen if you have more thoughts on the topic.
