### ISSUE TITLE
question: tensorflow serving

### ISSUE THREAD

**Issue by Arnold1** [grpc-ecosystem/grpc-gateway#1425]
Hi,

Does grpc-gateway support tensorflow serving as grpc service?

**Comment by johanbrandhorst** [comment]
Hi Arnold,

I don't know what the tensorflow gRPC service is, but the grpc-gateway can support arbitrary gRPC servers via the code generation from the proto file. If you have access to the proto file you can generate a client that you can put in front of the gRPC service. If you are not able to edit the protofile you can use https://grpc-ecosystem.github.io/grpc-gateway/docs/grpcapiconfiguration.html.

Hope that helps. Next time, for this sort of question, could you use the #grpc-gateway support channel on Gophers slack?
