### ISSUE TITLE
Trying to generate properties using the camelCase from underscores

### ISSUE THREAD

**Issue by zoubarevm** [grpc-ecosystem/grpc-gateway#1426]
## 📚 Documentation

I'm not entirely sure if this is a documentation issue, but the current proposed suggested method is to generate message using the undescore convention:
e.g.
```
message CreateUserRequest {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
}
```
When I generate this using:

```
protoc --go_out=plugins=grpc,paths=source_relative:. \
--grpc-gateway_out=logtostderr=true,paths=source_relative:. \
--swagger_out=logtostderr=true,json_names_for_fields=true,fqn_for_swagger_name=true:.
```

I get this in the *.pb.go file:
```
type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName       string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email           string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}
```

For some reason, I can't get the flags to line up between the protofbuf json and the json marshal, specifically the `json=firstName` and `json:"first_name,omitempty"`

Am I missing something from a documentation perspective? Is there a flag I need to set?

**Comment by johanbrandhorst** [comment]
Hi Michael,

I'm a little confused, the struct definition you've shared isn't something I'd have expected from `protoc-gen-go` using the message you shared. Take a look at `helloworld.proto`:

https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/examples/internal/helloworld/helloworld.proto#L58-L60

and it's generated counterpart:

https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/examples/internal/helloworld/helloworld.pb.go#L149-L154

The `json` field is not set in the `protobuf` struct tag unless you manually override it in your protofile.

Furthermore, why are you invoking `protoc-gen-swagger` the way you are? I don't think we recommend those settings anywhere in our docs, please correct me if I'm wrong. If you follow the instructions in the README, you should end up with a working gateway, and what you're showing me now has deviated a bit from that.

Having said all of that, this is not an issue with this project, as we do not control the `protoc-gen-go` generator. I'd be happy to help understand your issue in #protobuf or #grpc-gateway on the Gophers slack (https://invite.slack.golangbridge.org/), but this is not the right place for a support/configuration issue such as this.

**Comment by zoubarevm** [comment]
Sounds good. I’ll post my question on slack and aim to figure out how to solve my problem there. Im still new to the grpc world, but I have noticed that none of your examples have underscores for the field names in message. Any chance you have an example using that? See https://developers.google.com/protocol-buffers/docs/style#message-and-field-names

Thanks for quick feedback.

**Comment by johanbrandhorst** [comment]
Haha I had the same thought when I went through the examples. It's not important, but I thought it was funny that we didn't, you're right. Again, it's not really our responsibility to test that part, it's part of the official Google go protobuf project.
