### ISSUE TITLE
Support setting whole messages and repeated nested messages in URL parameters

### ISSUE THREAD

**Issue by jasonewang** [grpc-ecosystem/grpc-gateway#1448]
## 🚀 Feature
Setting repeated nested messages in URL parameters supports RPCs that are semantically equivalent GET that have repeated messages as part of the request, such as when implementing a filter.

Although the [HTTPRule spec] (https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#google.api.HttpRule) states that

> fields which are mapped to URL query parameters must have a primitive type or a repeated primitive type or a non-repeated message type

being able to set repeated messages through URL query parameters is a legitimate use case, such as in the usage below for setting multiple filters.

Setting whole messages in non-repeated fields support should be straightforward once  for setting repeated nested messages is supported.

## Example
Given a service
```grpc
rpc Filter (FilterRequest) returns (FilterResponse) {
    option (google.api.http) = {
        get: "/all"
    };
}

message Filter {
    string matches = 1;
    int64 before = 2;
    int64 after = 3;
}

message FilterRequest {
    repeated Filter filter = 1;
}

message FilterResponse {...}
```

The HTTP request to `/all?filter=%7B%22matches%22%3A%22foo%22%2C%22before%22%3A10%2C%22after%22%3A4%7D&filter=%7B%22matches%22%3A%22bar%22%2C%22before%22%3A25%2C%22after%22%3A12%7D`
(which when decoded is `?filter={"matches":"foo","before":10,"after":4}&filter={"matches":"bar","before":25,"after":12}`) 

should result in the request

```go
&FilterRequest{
    Filter: []*Filter{
        &Filter{
            Matches: "foo",
            Before: 10,
            After: 4,
        },
        &Filter{
            Matches: "bar",
            Before: 25,
            After: 12,
        },
    },
}
```

**Comment by johanbrandhorst** [comment]
I sympathize with this request, but there's a lot of complexity I'm not sure you're seeing here;

* Adding JSON parsing into the query parameters also opens the question of how we should support the various JSON cases and formattings that exist. How would a user configure the marshaller?
* Adding this support in excess of the definitions of the http.proto document sets a precedent about adding more features on top, and what if the http.proto spec changes to allow this? Then we probably end up with an incompatible existing implementation, making it impossible to remain spec compliant.
* Filtering is an interesting example, because the Google AIP guide has a page on how they recommend you do filtering: https://google.aip.dev/160. Indeed, it states explicitly:
    > It is tempting to define a structure to handle the precise filtering needs for each API. However, filtering requirements evolve frequently, and therefore it is prudent to use a string field with a structured syntax accessible to a non-technical audience. This allows updates to be able to be made transparently, without waiting for UI or client updates.
* If you really want to use structured data in your GET requests, you can use the PathLengthFallback to convert a POST request to a GET:
    ```shell
    $ curl -X POST -H "X-HTTP-Method-Override: GET" -H "ContentType: application/x-www-form-urlencoded" -d 'filter={"matches":"foo","before":10,"after":4}&filter={"matches":"bar","before":25,"after":12}' https://yourhost.com/all
    ```
    Note I haven't tested ^ but with my reading of the code it might work :shrug:.

Tentatively I'm going to decline this proposal. I hope I've laid out my reasons clearly enough.

**Comment by jasonewang** [comment]
>     * Adding JSON parsing into the query parameters also opens the question of how we should support the various JSON cases and formattings that exist. How would a user configure the marshaller?

My understanding is that a runtime.Marshaler is available for requests based on the Content-Type header, though it's unclear if the Content-Type header also applies to query parameters.

>     * Adding this support in excess of the definitions of the http.proto document sets a precedent about adding more features on top, and what if the http.proto spec changes to allow this? Then we probably end up with an incompatible existing implementation, making it impossible to remain spec compliant.

That's fair.

>     * If you really want to use structured data in your GET requests, you can use the PathLengthFallback to convert a POST request to a GET...

This parses the body as query parameters, but the runtime is still unable to bind nested/repeated nested query parameters.

(Tangentially, using "X-HTTP-Method-Override: GET" results in the body not being parsed as the runtime mux changes the request method to GET before the query params are parsed and Go's HTTP library doesn't attempt to parse the body as a query param string if the method isn't (POST|PUT|PATCH)).

> Tentatively I'm going to decline this proposal. I hope I've laid out my reasons clearly enough.

Yep, I understand where you're coming from.

**Comment by jasonewang** [comment]
What we're really looking for is just a way to set fields in repeated messages from GETs, so any existing workarounds or PR suggestions would be helpful.

**Comment by johanbrandhorst** [comment]
I've tried to do a similar thing to your filtering and I think it's the one case where this sort of question comes up. Really you might be better off just using a string filter, it made things easier for us in the long run.
