### ISSUE TITLE
Boolean type should not have a format (OAS)

### ISSUE THREAD

**Issue by ozraza** [grpc-ecosystem/grpc-gateway#1463]
## 🐛 Bug Report

According to [OAS specifications](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#dataTypes), boolean types should not have a format. Presence of format for boolean results in [IBM OpenAPI Validator](https://github.com/IBM/openapi-validator) failing on boolean type/format verification. Turning off `invalid_type_format_pair` schema rule is not an option as it disables the data type/format rules.

https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L68

## Prerequisities

- Install ibm-openapi-validator
`npm install -g ibm-openapi-validator`

- Install protobuf 3.7.0
https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-linux-x86_64.zip

- Get latest version of protoc-gen-swagger
https://github.com/grpc-ecosystem/grpc-gateway

## To Reproduce

1. Define a message with a boolean type

```
message Test {
    bool field = 1;
}
```

2. Generate swagger.json file using protoc-gen-swagger

3. Perform openapi validation
`lint-openapi <path-to-swagger.json>`

```
  Message :   Schema of type boolean should not have a format.
  Path    :   definitions.<definition>.properties.<message-param>.type
  Line    :   172
```

## Expected behavior

Boolean format is not present to comply with OAS specifications thereby allowing openapi validation to pass.

## Actual Behavior

Boolean format is present thereby causing openapi validation to fail.

## Your Environment

MacOS Catalina 10.15.4

**Comment by achew22** [comment]
@ozraza very interesting. We generate OpenAPI v2 definitions, is this also true for the v2 spec?

**Comment by ozraza** [comment]
@achew22 yes, this is also the case for the [v2 specs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types). As far as I am aware, OpenAPI has never leveraged the format field for type boolean.

**Comment by achew22** [comment]
I believe the fix here is as simple as updating our [internal mapping](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L68) to reflect the correct value. Would you be willing to send in a PR to address this?

**Comment by ozraza** [comment]
Yes, I am willing to submit a PR with the fix.

**Comment by ozraza** [comment]
PR is open for review: https://github.com/grpc-ecosystem/grpc-gateway/pull/1466
