### ISSUE TITLE
How to JSON Transcode Protos With Naming Equal to Generated Typescript Repeated Fields

### ISSUE THREAD

**Issue by rauljordan** [grpc-ecosystem/grpc-gateway#1465]
## 📚 Documentation

Hi all, currently I have this protobuf:

```
message FooResponse {
  repeated int foo = 1;
}
```
Which gets compiled into the following typescript definition using proto-gen-ts
```js
export class FooResponse extends jspb.Message {
  getFooList(): Array<int>;
  setFooList(value: Array<int>): void;
  clearFooList(): void;
  addFoo(value?: int, index?: number): APIKey;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): FooResponse.AsObject;
  static toObject(includeInstance: boolean, msg: FooResponse): FooResponse.AsObject;
  static serializeBinaryToWriter(message: FooResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): FooResponse;
  static deserializeBinaryFromReader(message: FooResponse, reader: jspb.BinaryReader): FooResponse;
}

export namespace FooResponse {
  export type AsObject = {
    fooList: Array<int>,
  }
}
```
I want to be able to use this type in my front-end, but the JSON data returned by my grpc-gateway looks like this:

```js
{ foo: [1, 2, 3] }
```
Instead of the expected
```js
{ fooList: [1, 2, 3] }
```
Any way around this? Would I need to implement a custom marshaler just to achieve this desired result?

**Comment by achew22** [comment]
It looks like you're trying to file a bug against the proto-gen-ts project. Unfortunately this is the grpc-gateway project. Closing this bug since it is unrelated to this project, but if I'm wrong please reopen and we can discuss the interaction of grpc-gateway. 

Have a good one 🙂

**Comment by rauljordan** [comment]
Hey @achew22 just wondering, isn't this something the gateway can handle? i.e. the JSON transcoding of 

```
message FooResponse {
  repeated int foo = 1;
}
```
Should have an option of matching the generated protobufs so that it looks like `{ fooList: [1, 2, 3] }` instead of `{ foo: [1, 2, 3] }`? What do you think?

**Comment by johanbrandhorst** [comment]
Hi @rauljordan, I think that option would not be something we want to support, since it's not using any of the official protobuf JSON names. I would sooner suggest you find some way to remove the `List` suffix in your JSON (and it looks like you've raised an issue).
