### ISSUE TITLE
should it support jsonp?

### ISSUE THREAD

**Issue by t2krew** [grpc-ecosystem/grpc-gateway#1480]
## 🚀 Feature

I have a service need to use grpc, but there are some api support jsonp for frontend. If change to use grpc protocol and it should support http(s) too, but I found this project not support jsonp.

**Comment by johanbrandhorst** [comment]
What is jsonp?

**Comment by t2krew** [comment]
@johanbrandhorst 

https://en.m.wikipedia.org/wiki/JSONP

**Comment by johanbrandhorst** [comment]
Looks to me like you can implement your own marshaler and use a custom content-type to support this. I don't think we'll add first class support for this. Please have a look at https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html for an example.

**Comment by t2krew** [comment]
@johanbrandhorst the custom marshaler can only get the response message from handle, but the JSONP's response also need the callback function name from the url query. so how can I transfer the value from http.Request to the marshal graceful ?

**Comment by johanbrandhorst** [comment]
We don't currently have that capability, no, but there was some discussion around adding a `ctx` parameter to the marshaler for v2, so that things like per-method marshalling could be performed. Would you be interested in contributing something like this?

**Comment by t2krew** [comment]
yes, of course interested if I can, let me first understand your discussion about the second edition, and then try to do it.
