### ISSUE TITLE
protoc-gen-swagger with allow_merge=true: `--swagger_out: inconsistent package names: alice bob`

### ISSUE THREAD

**Issue by moul** [grpc-ecosystem/grpc-gateway#1492]
## 🐛 Bug Report

`protoc-gen-swagger` with `allow_merge=true` only accept protobuf files with the same go package name

## To Reproduce

See *Actual Behavior* below

## Expected behavior

I'm adding OpenAPI documentation support on `bertymessenger.proto` and `bertyprotocol.proto` from this dir -> https://github.com/berty/berty/tree/master/api

We want these two files to be generated in different go directories, but they are both started on under the same gRPC server (https://github.com/berty/berty/blob/4e728517a996f4987659fd3e2bf396f2ff5d7f97/go/cmd/berty/main.go#L453-L469); we want to provide unique OpenAPI documentation for these two services.

## Actual Behavior

In have an open PR (https://github.com/berty/berty/pull/2129), I successfully set up the generation of two distinct files but when I try to use only one protoc call with `allow_merge=true` (https://github.com/berty/berty/pull/2129/files#diff-68a7f9edd4ffbca6adb99e2c165cfd52R47), I get the following error:

```console
$ protoc -I ../vendor/github.com/grpc-ecosystem/grpc-gateway:../api:../vendor:/protobuf --swagger_out=allow_delete_body=true,allow_merge=true:. ../api/bertymessenger.proto ../api/bertyprotocol.proto
--swagger_out: inconsistent package names: bertymessenger bertyprotocol
```

I understand why this option makes sense when used with `protoc-gen-grpc-gateway` but I think that we should allow using this merging strategy without caring about package name when using `protoc-gen-swagger`

## Your Environment

Everything runs in a the following Docker image: https://github.com/berty/berty/blob/master/tool/docker-protoc/Dockerfile

---

Thank you!

**Comment by johanbrandhorst** [comment]
Hi Manfred!

That sounds like it would be nice to have, what can I do to help you make this contribution happen?

**Comment by moul** [comment]
Just confirm that the idea is not bad so I don't spend time implementing something that will be trashed :)

I'll open a PR soon

**Comment by johanbrandhorst** [comment]
Great, please keep any new features to the v2 branch, we don't want to add anything new to v1.

**Comment by moul** [comment]
Just FYI, since I'm still not using the V2, I will wait for a little bit more to switch at least one project on V2 before making the change and opening a PR

I don't know if you prefer to keep this issue open or close it to clean up your issue list
