### ISSUE TITLE
Need help in enabling log in grpc-gateway application

### ISSUE THREAD

**Issue by subrat96** [grpc-ecosystem/grpc-gateway#1495]
Is it possible to enable log for each request coming to grpc-gateway ?

After running grpc-gateway application I am not able to see any logs.

**Comment by johanbrandhorst** [comment]
There are several ways, none that are built into the gateway:
* You can wrap the grpc-gateway mux in a http.Handler that logs all the requests made to it.
* You can implement a gRPC client-side interceptor which logs requests.
