### ISSUE TITLE
Cannot specify root path in proto file

### ISSUE THREAD

**Issue by Smirl** [grpc-ecosystem/grpc-gateway#1500]
## 🐛 Bug Report

I would like to expose a gRPC method on the root path of the gateway. i.e. `localhost:9090/` but have ran into a few issues.

## To Reproduce

**Cannot specify `"/"`**

When having a trailing slash we get a `--grpc-gateway_out: segment neither wildcards, literal or variable: expected "{" but got "\x00": /`. Which is expected as per the specification and https://github.com/grpc-ecosystem/grpc-gateway/issues/370. However a special case for the root path might be needed?

```
service Infrabin {
    rpc Root(Empty) returns (Response) {
        option (google.api.http) = {
            get: "/"
        };
    }
}
```

**Cannot specify `""`**

When having an empty path, there is no error. However the route is completely removed and there is a 404. This PR aims to fix this but I'm not sure it did. https://github.com/grpc-ecosystem/grpc-gateway/issues/414

```
service Infrabin {
    rpc Root(Empty) returns (Response) {
        option (google.api.http) = {
            get: ""
        };
    }
}
```

**Cannot specify `"//"` as first match**

When having `//` as the path, there is no error. Requests to `localhost:9090/` **DO** work. However `Root` is also matched for all other routes up to the first segment. `/bar/bar` would work.

The generated pattern is
```
pattern_Infrabin_Root_0 = runtime.MustPattern(runtime.NewPattern(1, []int{1, 0}, []string(nil), "", runtime.AssumeColonVerbOpt(true)))
```

```
service Infrabin {
    rpc Root(Empty) returns (Response) {
        option (google.api.http) = {
            get: "//"
        };
    }
    rpc Foo(Empty) returns (Response) {
        option (google.api.http) = {
            get: "/foo"
        }
    }
}
```

**Cannot specify `"//"` as last match**

Same as above, but with **either** setting `mux := runtime.NewServeMux(runtime.WithLastMatchWins())` **or** putting this match as the last match (like in the proto below). This **Does** work for `localhost:9090/` and `localhost:9090/foo`. However, it **also** matches `localhost:9090/blahblahblah` routing to `Root`.

```
service Infrabin {
    rpc Foo(Empty) returns (Response) {
        option (google.api.http) = {
            get: "/foo"
        }
    }
    rpc Root(Empty) returns (Response) {
        option (google.api.http) = {
            get: "//"
        };
    }
}
```

## Your Environment

```
go version go1.14.3 darwin/amd64
```

```
	github.com/golang/protobuf v1.4.1
	github.com/gorilla/mux v1.7.3
	github.com/grpc-ecosystem/grpc-gateway v1.14.6
	google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
	google.golang.org/grpc v1.30.0
	google.golang.org/protobuf v1.25.0
```

**Comment by Smirl** [comment]
A "workaround" I have found is the following (referring to these docs not on master https://github.com/grpc-ecosystem/grpc-gateway/issues/1087).

The only worry I have is this is very specific to `grpc-gateway`.

```
func forwardRootResponse(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, req *http.Request, resp proto.Message, opts ...func(context.Context, http.ResponseWriter, proto.Message) error) {
	if req.URL.Path != "/" {
		e := fmt.Sprintf("Not returning root as path is %s", req.URL.Path)
		http.Error(w, e, http.StatusNotFound)
		return
	}
	runtime.ForwardResponseMessage(ctx, mux, marshaler, w, req, resp, opts...)
}

func init() {
	forward_Infrabin_Root_0 = forwardRootResponse
}
```

**Comment by johanbrandhorst** [comment]
Hi @Smirl, is this allowed by the `http.proto` spec? See https://github.com/googleapis/googleapis/blob/master/google/api/http.proto. If so, we should try to support it too.

**Comment by Smirl** [comment]
It isn't clear that it is or isn't. The only part of the spec which is relevant is:

> The path variables **must not** capture the leading "/" character. The reason
> is that the most common use case "{var}" does not capture the leading "/"
> character. For consistency, all path variables must share the same behavior.

Which suggests that perhaps `""` should work. As you can see from the referenced PR, in the end I added a pattern override.

**Comment by johanbrandhorst** [comment]
I admit I'm in a little over my depth, but what exactly would you like us to do here? It sounds like maybe you want us to fix `get: ""`? Is there anything else?

**Comment by Smirl** [comment]
Would you know how best to ask the maintainers of `google.api.http`? If it isn't supported perhaps I can just raise a PR with docs, or just close this issues off as I have a workaround.

**Comment by johanbrandhorst** [comment]
Might have to raise an issue on the googleapis repo. Otherwise no idea, sorry!

**Comment by gkarthiks** [comment]
Hi All, is there a solution for this? I am still having the issue of not able to reference the root path in my proto.

```
go version go1.16.4 darwin/amd64
protoc-gen-go v1.26.0
protoc-gen-grpc-gateway Version 2.4.0
protoc-gen-go-grpc 1.1.0
protoc-gen-openapiv2 Version 2.4.0
```

Below is the sample proto

```go
service PetService {
  rpc GetPets(google.protobuf.Empty) returns (Pets) {
    option (google.api.http) = {
      get: "/"
    };
  }
}
```

the error message is `--grpc-gateway_out: segment neither wildcards, literal or variable: expected "{" but got "\x00": /`
