### ISSUE TITLE
does this support grpc-node?

### ISSUE THREAD

**Issue by Rchan0100** [grpc-ecosystem/grpc-gateway#1525]
## 🚀 Feature

I was wondering if there was any node middleware support with grpc-node, or any similar alternatives in order to log grpc-node proto request times.

**Comment by achew22** [comment]
This repo is singularly targeting golang as the HTTP layer. You can, of course, use node as the backend for grpc-gateway, but we don't emit anything special for interoperability with node. Best of luck finding a solution that meets your need!
