### ISSUE TITLE
Flaky test: examples/internal/integration/integration_test.go:TestTimeout

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#1527]
## 🐛 Bug Report

The `TestTimeout` test is sometimes failing randomly.

## To Reproduce

```shell
$ go test -run TestTimeout -count 100 ./examples/internal/integration
```

## Expected behavior

Test not to be flaky

## Actual Behavior

The tests fails with an incorrect status code error:
```
integration_test.go:1395: resp.StatusCode = 500; want 504
```

See https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/993/workflows/f7328257-19fe-436c-8cd4-8f2274bcb535/jobs/13566.

**Comment by Tamiraltshuler** [comment]
Hey,
first time contributor made a pr#2247  to fix this issue
