### ISSUE TITLE
reverse gateway file not getting generated (.pb.gw.go) not getting generated no error just warning 

### ISSUE THREAD

**Issue by gautam-shipt** [grpc-ecosystem/grpc-gateway#1530]
Hi Team 
  I am trying to use the REST proxy with my Grpc service .. here is what my Proto file looks likes 
syntax = "proto3";

Proto file = healthcheck.proto

```
package main;
option go_package = "./proto-gen;proto_gen";
import "google/api/annotations.proto";

service HealthV1 {
  rpc Check(HealthCheckRequest) returns (HealthCheckResponse) {
    option (google.api.http) = {
      get: "/api/v1/healthcheck"
    };
  };
}

message HealthCheckRequest {}

message HealthCheckResponse {}

```

I am using the following to generate the files 

**Reverse proxy Gateway generation** 
`protoc -I. -I proto/ -I ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --grpc-gateway_out=logtostderr=true,paths=source_relative:../proto-gen proto/healthcheck.proto
`
**ERROR** 

WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.

the proto compiler is not generating the expected reverse proxy file (healthcheck.pb.gw.go) 

protoc version  libprotoc 3.12.3

**Comment by johanbrandhorst** [comment]
Could you join the support channel #grpc-gateway on Gophers slack for support questions like this? This isn't a great forum for it. I'm going to close this issue.
