### ISSUE TITLE
Can not use evans cli or other grpc gui tool when using http annotations

### ISSUE THREAD

**Issue by cyantarek** [grpc-ecosystem/grpc-gateway#1535]
It's annoying that, when I serve with http annotations, any other grpc CLI tool like evans cli or grpc gui tool shows errors that it can not find "annotations.proto, http.proto" files when using grpc reflection mode.

What is the work around?

**Comment by johanbrandhorst** [comment]
I just tested this locally and grpc reflection definitely works even with the annotations in the proto file. To help debug this issue, could you please join the #grpc-gateway channel on Gophers slack instead? Thanks.
