### ISSUE TITLE
Log spam during attempt to append remote address to the XFF header when the transport is a unix domain socket

### ISSUE THREAD

**Issue by janzantinge** [grpc-ecosystem/grpc-gateway#1538]
## 🐛 Bug Report

The `annotateContext` function cannot append the request's remote address if the request arrives via a Unix Domain Socket. The [code](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/context.go#L125) attempts to parse the `req.remoteAddr` field and fails. This is not really a big problem except that an [info level log message](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/context.go#L132) is printed every time the `req.remoteAddr` cannot be parsed.

## To Reproduce

1. Send a request to the gateway via a Unix Domain Socket (abstract in my case)

## Expected behavior

No info level log, maybe update the `X-Forwarded-For` header (though I'm not sure if appending the Unix Domain Socket path to the header contents is valid)

## Actual Behavior

While running a high traffic service, a lot of log messages are generated that look like this: `invalid remote addr: @`

## Your Environment

Linux (container running in kubernetes)

**Comment by johanbrandhorst** [comment]
Hi Jan, thanks for raising this issue. That sounds really annoying! Would it be better if we downgraded this to a debug log? Or would you like to have it removed? What can I do to help you bring this contribution in?

**Comment by janzantinge** [comment]
I'm happy to fix this! I'm wondering if there is any reason to try to verify whether the request's transport is a Unix Domain Socket and, if so, append the loopback address to the XFF header. Otherwise, I think removing the log message is fine since it's probably not useful. LMK what you think!

**Comment by johanbrandhorst** [comment]
Yeah I don't think we're going to try to parse it as a domain socket, so lets just remove the message then.

**Comment by janzantinge** [comment]
Sounds good, PR submitted!
