### ISSUE TITLE
v1/v2: FieldMask query parameter is not parsed correctly if specified multiple times

### ISSUE THREAD

**Issue by krosen040** [grpc-ecosystem/grpc-gateway#1559]
## 🐛 Bug Report

When using a `FieldMask` as a query parameter, the paths are not parsed correctly if the query parameter is specified multiple times, e.g. `&mask=foo&mask=bar`.

## To Reproduce

Create a `proto` file with a service that takes a message containing a `google.protobuf.FieldMask` as a query parameter:

```
syntax = "proto3";

package test;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";

service Foo {
    rpc Bar(Request) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            get: "/bar"
        };
    }
}

message Request {
    google.protobuf.FieldMask mask = 1;
}
```

2. [Implement service and generate gateway per instructions.](https://github.com/grpc-ecosystem/grpc-gateway#usage)

3. Call the endpoint and specify the mask multiple times:

`curl  http://<host>:<port>/bar?mask=x&mask=y`

## Expected behavior

I expected `Mask.Paths` to contain both `x` and `y`. This would be consistent to how other repeated string fields work. As a side note, these produce the expected result:

* `?mask=x,y`
* `?mask.paths=x&mask.paths=y`

## Actual Behavior

In v1, the `Mask.Paths` field of the generated proto will only contain `x` and not `y`. In v2 I believe [the grpc-gateway code returns an error to the caller](https://github.com/grpc-ecosystem/grpc-gateway/blob/v2.0.0-beta.3/runtime/query.go#L119), but I haven't verified this.

## Your Environment

go version go1.14.4 darwin/amd64
github.com/grpc-ecosystem/grpc-gateway v1.14.6

**Comment by johanbrandhorst** [comment]
Thanks for raising this issue. I think we'll need a special case for the field mask here if we want to support this. I'm not entirely sure we do want to special case the whole query parser when we do have a workaround, but you're welcome to play around with the code and see if you can make it work in a nice way. We do still want to return an error for non-slice or map fields that have multiple entries in the query string generally.
