### ISSUE TITLE
protoc-gen-swagger: Add prefix to all paths

### ISSUE THREAD

**Issue by amaurymartiny** [grpc-ecosystem/grpc-gateway#1567]
## 🚀 Feature

I have the following simple service

```protobuf
service MyService {
  rpc MyEndpoint(MyReq) returns (MyRes) {
    option (google.api.http).get = "/myservice";
  }
}
```

However, I'm mounting the entire gRPC gateway on a prefixed router: `/grpc/*`, so that I access the above endpoint at `/grpc/myservice`. In the generated swagger jsons, the prefix `/grpc/*` does not appear.

I can of course, in the protobuf annotations, add `option (google.api.http).get = "/grpc/myservice"`, but since I have 100+ services, I was wondering if there was an option in `protoc-gen-swagger` to add a prefix to all paths.

**Comment by johanbrandhorst** [comment]
You can specify a `base_path` per-file like so:

```protobuf
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
   base_path = "/grpc"
};
```

Ref: https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/protoc-gen-openapiv2/options/openapiv2.proto#L59-L68 (v2 link)
