### ISSUE TITLE
Use headers for routing

### ISSUE THREAD

**Issue by jhspaybar** [grpc-ecosystem/grpc-gateway#157]
Some RPC systems like those used by AWS expect a header to determine the method being invoked.  It doesn't look like this is actually part of the google protobuf option used to generate the proxy, but I had envisioned something like headers: [["foo", "bar"], ["other", "val"]] which would allow me to trigger  routing if the header foo=bar and other=val.  Is this the right place to discuss something like this, or should I make an issue in the googleapis repo?

**Comment by yugui** [comment]
I never add the feature unless it is "standardized" in googleapis repo or I realize that the use case is common enough.
For now, I'm not sure if the use case is really common.

In my understanding, such custom dispatch tends to be implemented as a custom `VERB`.
https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L210

For uncommon use cases, you can combine any custom Go http handler with top of the one `grpc-gateway` generates.
e.g.
```
func TagVerbFilter(h http.Handler) http.Handler {
  func http.HandlerFunc(func(w http.ResponseWriter, r *http.Request){
    if r.Header.Get("foo") == "bar" && r.Header.Get("other") == "val" {
    }
  })
}
```

**Comment by achew22** [comment]
Just doing a little bit of tidying. I hope that your question was answered in a way that let your project continue. If you have any more questions feel free to open another issue.
