### ISSUE TITLE
FieldMask Generation causes a 400 when a google.protobuf.Struct field has populated values

### ISSUE THREAD

**Issue by talanknight** [grpc-ecosystem/grpc-gateway#1570]
## 🐛 Bug Report

grpc gateway supports [field mask generation](https://grpc-ecosystem.github.io/grpc-gateway/docs/patch.html).  When the item being used to generate the field mask contains a google.protobuf.Struct with populated values grpc gateway returns a 400.  

## To Reproduce

With the following service definition:

```
service TestService {
	rpc PatchTest (PatchTestRequest) returns (PatchTestResponse) {
		option (google.api.http) = {
      patch: "/test"
      body: "item"
    };
	}
}

message Item {
	string foo = 1;
	google.protobuf.Struct struct = 2;
}

message PatchTestRequest {
	Item item = 1;
	google.protobuf.FieldMask update_mask = 2;
}

message PatchTestResponse {}
```

Run the following test.

```
func TestStructFieldMask(t *testing.T) {
	mux := runtime.NewServeMux()
	pbs.RegisterTestServiceHandlerServer(context.Background(), mux, &pbs.UnimplementedTestServiceServer{})
	req := httptest.NewRequest("PATCH", "http://127.0.0.1/test", strings.NewReader(`{"foo": "val1", "struct": {"key1": "val2"}}`))
	resp := httptest.NewRecorder()
	mux.ServeHTTP(resp, req)
	if resp.Code != http.StatusNotImplemented {
		body, _ := ioutil.ReadAll(resp.Body)
		t.Errorf("Expected Not implemented: Got response %d %q", resp.Code, body)
	}
}
```

## Expected behavior

I expected the test to pass.

## Actual Behavior
The test fails with the following error:

> Expected Not implemented: Got response 400 "{\"code\":3, \"message\":\"could not find field \\\"key1\\\" in \\\"google.protobuf.Struct\\\"\", \"details\":[]}"

## Your Environment

mac os, grpc gateway v2, go version go1.14 darwin/amd64

## Additional Information

For my purpose the ideal behavior would populate the field mask to match the json structure and not depend on the proto structure.  For example a request like this:

```
{
  "key1": "val",
  "key2": {
          "key3":"val2",
          "key4": {"key5": "val3"}
   }
}
```

would result in a field mask containing the following paths: `key1, key2.key3, key2.key4.key5` regardless if the protos looked like
```
message item {
  string key1 =1;
  google.protobuf.Struct key2 = 2;
}
```
or
```
message item {
  string key1 = 1;
  message item2 {
    string key3 = 1;
    message item3 {
      string key5 = 1;
    }
    item3 key4 = 2;
  }
  item2 key2 = 2;
}
```

**Comment by johanbrandhorst** [comment]
I think it would be nice for us to handle this as a special case for the type `google.protobuf.Struct`, and maybe by extension the `google.protobuf.Value` etc types in `struct.proto`, since they are used for dynamic JSON like this. I'm not sure how much work it would be to implement.

The error at the moment is from https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/runtime/fieldmask.go#L52, I expect it would be interesting to add a special check for the type name in here and switch to some special logic. The first step would be to create a failing test, which you've already done, so half the battle is won! What can I do to help you bring this contribution in?

**Comment by jefferai** [comment]
I think this can be closed fully as #1595 was merged. @talanknight agree?

**Comment by talanknight** [comment]
I agree. Thank you!

**Comment by yousseftelda** [comment]
@johanbrandhorst Does this feature also imply that a `google.protobuf.Struct` can be populated from query params or is it specific to patch and fieldMasks? If not, I have a use case where populating a `google.protobuf.Struct` from query parameters would be very useful, and I am willing to add the feature, with guidance of course.

**Comment by johanbrandhorst** [comment]
Right now it's specific to the patch field-mask translation. Doing it from query parameters would have to utilize a separate part of the code (runtime/query.go). For query parameter parsing we also already allow configuring a custom parser, so I'm not sure we want to add the extra complexity this would require to our default parser.
