### ISSUE TITLE
Addition of Prettier GitHub action to prettified the markdown files

### ISSUE THREAD

**Issue by iamrajiv** [grpc-ecosystem/grpc-gateway#1575]

**Comment by johanbrandhorst** [comment]
Sounds like a good idea. Some things to consider:

* It needs to be easy to apply by users if they've made docs changes, even if they're not used to using it. At the least something like a `docker run` oneliner we can add to `CONTRIBUTING.md` or of equivalent ease.
* It needs to be run in CI as well to ensure it's applied consistently. Perhaps a new CI job with a similar docker one-liner.
