### ISSUE TITLE
[v2] expose defaultHTTPErrorHandler (and perhaps defaultStreamErrorHandler)

### ISSUE THREAD

**Issue by Azuka** [grpc-ecosystem/grpc-gateway#1576]
## 🚀 Feature

`runtime.DefaultHTTPError` was previously exposed in v1, which allowed a user to use something like:

```go
func init() {
	runtime.HTTPError = defaultHTTPError
}

func defaultHTTPError(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {

	if err != nil {
		apm.CaptureError(ctx, errors.WithStack(err)).Send()
	}

	runtime.DefaultHTTPError(ctx, mux, marshaler, w, r, err)
}
```

It is very helpful to capture an error which possibly contains a stack trace right before it gets transformed into a status, and replicating the other things the default http error handler does (e.g. trailers) is non-trivial and would also mean not getting any changes from bug fixes.

I can open a PR (trivial task), but wanted to confirm that's ok.

**Comment by johanbrandhorst** [comment]
We don't want to reintroduce the assignment in init as that's a very unidiomatic mechanism rife with issues. Is there any reason you can't use https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/runtime/mux.go#L110?

**Comment by Azuka** [comment]
> We don't want to reintroduce the assignment in init as that's a very unidiomatic mechanism rife with issues. Is there any reason you can't use https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/runtime/mux.go#L110?

Actually, I just realized it's currently open (https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/runtime/errors.go#L78), but I'm getting an old version since no new tag/release for v2 has been created since May. #1507 has the change I'm looking for.

**Comment by johanbrandhorst** [comment]
I can tag another release candidate :)

**Comment by Azuka** [comment]
Thanks @johanbrandhorst
