### ISSUE TITLE
Swagger definitions don't handle parameters that are not explicitly required in the url

### ISSUE THREAD

**Issue by achew22** [grpc-ecosystem/grpc-gateway#159]
``` proto
message Message {
  string message = 1;
}

message GetMessageRequest {
  message SubMessage {
    string subfield = 1;
  }
  string message_id = 1; // mapped to the URL
  int64 revision = 2;    // becomes a parameter
  SubMessage sub = 3;    // `sub.subfield` becomes a parameter
}

service Messaging {
  rpc GetMessage(GetMessageRequest) returns (Message) {
    option (google.api.http) = {
      get: "/v1/messages/{message_id}"
    };
  }
}
```

This should enable a HTTP JSON to RPC mapping as below:

| HTTP | RPC |
| --- | --- |
| `GET /v1/messages/123456?revision=2&sub.subfield=foo` | `GetMessage(message_id: "123456" revision: 2 sub: SubMessage(subfield: "foo"))` |

Presently it does not work

**Comment by hasLeland** [comment]
I'd like to add my support for this. Right now *no query parameters are added at all* for the generated `paths` in any swagger spec. This makes most all swagger specs useless, unless you map every field in every `message` to path parameters, which is very dirty solution indeed.

**Comment by johanbrandhorst** [comment]
The workaround right now is to pretty much use POST for all your HTTP endpoints, as far as I can tell. I second the need for this fix.

**Comment by rgarcia** [comment]
Opened a PR that attempts to address this #199

**Comment by ambarc** [comment]
+1

**Comment by jhayotte** [comment]
+1,
@johanbrandhorst your workaround removes the possibility to have a REST API, I don't see that as a solution. 
This PR https://github.com/grpc-ecosystem/grpc-gateway/issues/159 matches our expectation... Please merge it,

We really something like below working 
```
service Messaging {
  rpc GetMessage(GetMessageRequest) returns (Message) {
    option (google.api.http) = {
      get: "/v1/messages?type={type_id}&limit={limit}"
    };
  }
}
```

**Comment by AlekSi** [comment]
I think that issue can be closed?

**Comment by achew22** [comment]
Yep, I think this can be closed. Thanks!
