### ISSUE TITLE
How to elegant rewrite/custom resp body from gRPC resp ? 

### ISSUE THREAD

**Issue by zhangjie2012** [grpc-ecosystem/grpc-gateway#1610]
My business scene want all http resp format like: 

```json
{ "code": "0/1", "data": {}, "error": ""}
```

**For error response**, I use `runtime.WithProtoErrorHandler` get grpc error, and custom it, work well.

but, **For success response**, I did not find suitable ones, I tried `runtime.WithForwardResponseOption`, it work like a 
hook. When I call `w.Write`, it will output data _twice copy_. like:

```json
{"code": 1, "data": {"key": "hello"}, "error": ""}{"key": "hello"}
``` 

So, I check out source, found https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/handler.go#L128 `ForwardResponseMessage`.  It realy like a hook. 

A hack skill to fixed my problem, all resp proxy by `runtime.WithProtoErrorHandler`:

``` go
type StandardResp struct {
	Code  int         `json:"code"`
	Data  interface{} `json:"data"`
	Error string      `json:"error"`
}

const (
	proxyFlag = "__succ__"
)

func HttpSuccHandler(ctx context.Context, w http.ResponseWriter, p proto.Message) error {
	resp := StandardResp{
		Code:  0,
		Data:  p,
		Error: "",
	}
	bs, _ := json.Marshal(&resp)
	return errors.New(proxyFlag + string(bs))
}

func HttpErrorHandler(ctx context.Context, mux *runtime.ServeMux, m runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
	w.Header().Set("Content-Type", "application/json")

	// success proxy
	raw := err.Error()
	if strings.HasPrefix(raw, proxyFlag) {
		raw = raw[len(proxyFlag):]
		w.Write([]byte(raw))
		return
	}

	// error handler
	s, ok := status.FromError(err)
	if !ok {
		s = status.New(codes.Unknown, err.Error())
	}
	resp := StandardResp{
		Code:  1,
		Data:  nil,
		Error: s.Message(),
	}
	bs, _ := json.Marshal(&resp)
	w.Write(bs)
}
```

It worked for me, but I don't think it's a elegant way. 

So, my question is can I custom resp body by more direct or simple way, similar programmer can define a `ForwardResponseMessage` method, framework provide a `DefaultForwardResponseMessage` method.

go version go1.14.7 darwin/amd64,  grpc-gateway v1.14.7

**Comment by zhangjie2012** [comment]
other issues:

- https://github.com/grpc-ecosystem/grpc-gateway/issues/1051

**Comment by achew22** [comment]
If you would like your responses to be shaped in one way, I believe the elegant solution is to define those as a part of your response in every message.

```
message HelloWorldWrapper {
  int code = 1;
  HelloWorldResponse data = 2;
  string error = 3;
}

message HelloWorldResponse {
  string key = 1;
}
```

This way the type is correctly encoded in your type definitions in your application, in your api definitions and in your clients.

**Comment by YeRuyi** [comment]
I have to active this issue, did have any way to solve it ?

Because I do have a situation for union processing response data

**Comment by YeRuyi** [comment]
@achew22 pls help.

**Comment by kaydxh** [comment]
Is the issue solved ?@stale @YeRuyi @zhangjie2012

**Comment by YeRuyi** [comment]
solved it. @kaydxh 

I have to change my company mind for response formatter. Using pb IDL as common response struct. But using same error response when svr facing error.

**Comment by kaydxh** [comment]
Yea, I know use pb IDL can solve it. But I want to slove it using middleware.
To define common response in pb, need to add  the response filed in every message. I think it is not graceful.@YeRuyi

**Comment by YeRuyi** [comment]
Using interceptor. grpc chainUnaryServer, You can get resp when you handle req, like nodejs koa arch for req and resp.


在 2021年8月22日 ***@***.***> 写道：


Yea, I know use pb IDL can solve it. But I want to slove it using middleware.
 To define common response in pb, need to add the response filed in every message. I think it is not ***@***.***
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YeRuyi** [comment]
Using interceptor. grpc chainUnaryServer, You can get resp when you handle req, like nodejs koa arch for req and resp.

**Comment by kaydxh** [comment]
Using interceptor will get a problem. https://github.com/grpc-ecosystem/grpc-gateway/issues/1610#issue-684346445, ForwardResponseMessage method, can not rewrite response, only append message to response

**Comment by china-xs** [comment]
> My business scene want all http resp format like:
> 
> ```json
> { "code": "0/1", "data": {}, "error": ""}
> ```
> 
> **For error response**, I use `runtime.WithProtoErrorHandler` get grpc error, and custom it, work well.
> 
> but, **For success response**, I did not find suitable ones, I tried `runtime.WithForwardResponseOption`, it work like a hook. When I call `w.Write`, it will output data _twice copy_. like:
> 
> ```json
> {"code": 1, "data": {"key": "hello"}, "error": ""}{"key": "hello"}
> ```
> 
> So, I check out source, found https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/handler.go#L128 `ForwardResponseMessage`. It realy like a hook.
> 
> A hack skill to fixed my problem, all resp proxy by `runtime.WithProtoErrorHandler`:
> 
> ```go
> type StandardResp struct {
> 	Code  int         `json:"code"`
> 	Data  interface{} `json:"data"`
> 	Error string      `json:"error"`
> }
> 
> const (
> 	proxyFlag = "__succ__"
> )
> 
> func HttpSuccHandler(ctx context.Context, w http.ResponseWriter, p proto.Message) error {
> 	resp := StandardResp{
> 		Code:  0,
> 		Data:  p,
> 		Error: "",
> 	}
> 	bs, _ := json.Marshal(&resp)
> 	return errors.New(proxyFlag + string(bs))
> }
> 
> func HttpErrorHandler(ctx context.Context, mux *runtime.ServeMux, m runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
> 	w.Header().Set("Content-Type", "application/json")
> 
> 	// success proxy
> 	raw := err.Error()
> 	if strings.HasPrefix(raw, proxyFlag) {
> 		raw = raw[len(proxyFlag):]
> 		w.Write([]byte(raw))
> 		return
> 	}
> 
> 	// error handler
> 	s, ok := status.FromError(err)
> 	if !ok {
> 		s = status.New(codes.Unknown, err.Error())
> 	}
> 	resp := StandardResp{
> 		Code:  1,
> 		Data:  nil,
> 		Error: s.Message(),
> 	}
> 	bs, _ := json.Marshal(&resp)
> 	w.Write(bs)
> }
> ```
> 
> It worked for me, but I don't think it's a elegant way.
> 
> So, my question is can I custom resp body by more direct or simple way, similar programmer can define a `ForwardResponseMessage` method, framework provide a `DefaultForwardResponseMessage` method.
> 
> go version go1.14.7 darwin/amd64, grpc-gateway v1.14.7



你好,最后有解决这个问题吗,我现在也遇到这个问题

**Comment by json7** [comment]
type Response struct {
	Code codes.Code  `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

var (
	EmptyError = errors.New("empty error") //查看文档和issue,基本确定grpc gateway无法修改正常返回值的结构,错误情况下是可以的,它提供了option.
)

func CustomHTTPError(ctx context.Context, sm *runtime.ServeMux, m runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
	const fallback = `{"error": "failed to marshal error message"}`

	w.Header().Set("Content-type", m.ContentType(r))

	w.WriteHeader(200)

	if err == EmptyError {
		return
	}

	resp := &Response{
		Code: status.Code(err),
		Msg:  grpc.ErrorDesc(err),
	}

	jErr := json.NewEncoder(w).Encode(resp)

	if jErr != nil {
		w.Write([]byte(fallback))
	}
}

func CustomHTTPNormal(ctx context.Context, w http.ResponseWriter, m proto.Message) error {
	buf, err := json.Marshal(Response{
		Code: codes.Code(0),
		Data: m,
		Msg:  "success",
	})
	if err != nil {
		return err
	}
	w.Write(buf)
	return EmptyError
}

**Comment by optimistic9527** [comment]
how to fix it?

**Comment by johanbrandhorst** [comment]
I'm not sure what you're asking for? You can exert full control over responses with https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#WithForwardResponseOption.

**Comment by cgapu** [comment]
1. define an empty marshaler with nil output in Marshal func:
```
type EmptyMarshaler struct{}

func (m *EmptyMarshaler) Marshal(v interface{}) ([]byte, error) {
	return nil, nil
}

func (m *EmptyMarshaler) Unmarshal(data []byte, v interface{}) error {
	return nil
}

func (m *EmptyMarshaler) NewDecoder(r io.Reader) runtime.Decoder {
	return new(runtime.DecoderFunc)
}

func (m *EmptyMarshaler) NewEncoder(w io.Writer) runtime.Encoder {
	return new(runtime.EncoderFunc)
}

func (m *EmptyMarshaler) ContentType(v interface{}) string {
	return ""
}

```

2. new server mux with the EmptyMarshaler, and we can print anything in our CustomHttpResponseModifier :
```
mux := runtime.NewServeMux(
                runtime.WithForwardResponseOption(CustomHttpResponseModifier),
		runtime.WithMarshalerOption("*", &EmptyMarshaler{}),
	)
```

**Comment by mc-zhangyang** [comment]
@cgapu It worked for me. But there is a small problem, due to the omitempty flag, it is ignored when the field is empty. Is there any good solution?

**Comment by chidangit** [comment]
> @cgapu It worked for me. But there is a small problem, due to the omitempty flag, it is ignored when the field is empty. Is there any good solution?

```
package customize

import (
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

type NilMarshaler struct {
	runtime.Marshaler
}

func (m *NilMarshaler) Marshal(v interface{}) ([]byte, error) {
	return nil, nil
}

func (m *NilMarshaler) Unmarshal(data []byte, v interface{}) error {
	return nil
}
```

you can init marshaler with option
```
runtime.WithMarshalerOption(runtime.MIMEWildcard, &customize.NilMarshaler{
			Marshaler: &runtime.JSONPb{
				MarshalOptions: protojson.MarshalOptions{
					EmitUnpopulated: true,
				},
				UnmarshalOptions: protojson.UnmarshalOptions{
					DiscardUnknown: true,
				},
			},
		}),
```

**Comment by mc-zhangyang** [comment]
@chidangit It doesn't seem to work well. It still ignores the empty field.

**Comment by cgapu** [comment]
> @cgapu It worked for me. But there is a small problem, due to the omitempty flag, it is ignored when the field is empty. Is there any good solution?


If you use json.Marshal, you could not write those fields that with omitempty json tag. You can remove omitempty json tag from generated golang files with some magic methods. Or you can implement your own marshal function in which you could read the json tag and write whatever you want.
Since these methods are not very easy to do, I suggest to honestly define your rpc return message.

**Comment by cgapu** [comment]
@mc-zhangyang Here is an example that writes fields which marked with omitempty json tag by implementing the MarshalJSON function, even if their value is empty.
```
type Response struct {
	Code int32         `json:"code"`
	Msg  string        `json:"msg"`
	Data proto.Message `json:"data"`
}

func (r *Response) MarshalJSON() ([]byte, error) {
	mm := runtime.JSONPb{
		MarshalOptions: protojson.MarshalOptions{
			EmitUnpopulated: true,
		},
	}
	buf := []byte("{")
	st := reflect.TypeOf(*r)
	vt := reflect.ValueOf(*r)
	for i := 0; i < st.NumField(); i++ {
		if i != 0 {
			buf = append(buf, ',')
		}
		field := st.Field(i)
		tag := field.Tag.Get("json")
		buf = append(buf, []byte("\""+tag+"\": ")...)
		value := vt.Field(i).Interface()
		var vBuf []byte
		if tag == "data" {
			vBuf, _ = mm.Marshal(r.Data)
		} else {
			vBuf, _ = json.Marshal(value)
		}
		buf = append(buf, vBuf...)
	}
	end := []byte{'}'}
	buf = append(buf, end...)
	return buf, nil
}

func CustomHttpResponseModifier(ctx context.Context, w http.ResponseWriter, p proto.Message) error {
	rsp := &Response{}
	rsp.Data = p
	buf, _ := json.Marshal(rsp)
	w.Write(buf)
	return nil
}

type CustomMarshaler struct {
	runtime.JSONPb
}

func (m *CustomMarshaler) Marshal(v interface{}) ([]byte, error) {
	return nil, nil
}
```

```
mux := runtime.NewServeMux(
		runtime.WithForwardResponseOption(CustomHttpResponseModifier),
		runtime.WithMarshalerOption("*", &CustomMarshaler{}),
	)
```

**Comment by mc-zhangyang** [comment]
> @mc-zhangyang Here is an example that writes fields which marked with omitempty json tag by implementing the MarshalJSON function, even if their value is empty.
> 
> ```
> type Response struct {
> 	Code int32         `json:"code"`
> 	Msg  string        `json:"msg"`
> 	Data proto.Message `json:"data"`
> }
> 
> func (r *Response) MarshalJSON() ([]byte, error) {
> 	mm := runtime.JSONPb{
> 		MarshalOptions: protojson.MarshalOptions{
> 			EmitUnpopulated: true,
> 		},
> 	}
> 	buf := []byte("{")
> 	st := reflect.TypeOf(*r)
> 	vt := reflect.ValueOf(*r)
> 	for i := 0; i < st.NumField(); i++ {
> 		if i != 0 {
> 			buf = append(buf, ',')
> 		}
> 		field := st.Field(i)
> 		tag := field.Tag.Get("json")
> 		buf = append(buf, []byte("\""+tag+"\": ")...)
> 		value := vt.Field(i).Interface()
> 		var vBuf []byte
> 		if tag == "data" {
> 			vBuf, _ = mm.Marshal(r.Data)
> 		} else {
> 			vBuf, _ = json.Marshal(value)
> 		}
> 		buf = append(buf, vBuf...)
> 	}
> 	end := []byte{'}'}
> 	buf = append(buf, end...)
> 	return buf, nil
> }
> 
> func CustomHttpResponseModifier(ctx context.Context, w http.ResponseWriter, p proto.Message) error {
> 	rsp := &Response{}
> 	rsp.Data = p
> 	buf, _ := json.Marshal(rsp)
> 	w.Write(buf)
> 	return nil
> }
> 
> type CustomMarshaler struct {
> 	runtime.JSONPb
> }
> 
> func (m *CustomMarshaler) Marshal(v interface{}) ([]byte, error) {
> 	return nil, nil
> }
> ```
> 
> ```
> mux := runtime.NewServeMux(
> 		runtime.WithForwardResponseOption(CustomHttpResponseModifier),
> 		runtime.WithMarshalerOption("*", &CustomMarshaler{}),
> 	)
> ```

@cgapu Thanks. This is the correct solution about rewrite resp body

**Comment by mc-zhangyang** [comment]
@cgapu Be inspired by you, I thought of another way, which I think is more efficient. Of course, rewriting **Marshal** of `runtime.JSONPb` is needed.
```
func CustomNormalHandler(ctx context.Context, w http.ResponseWriter, m proto.Message) error {
	marshaler := runtime.JSONPb{
		MarshalOptions: protojson.MarshalOptions{
			EmitUnpopulated: true,
			UseProtoNames:   true,
		},
	}
	jsonBytes, _ := marshaler.Marshal(m)
	buf, err := json.Marshal(Response{
		Code: 0,
		Msg:  "success",
		Data: json.RawMessage(jsonBytes),
	})
	if err != nil {
		return err
	}
	w.Write(buf)
	return nil
}
```

**Comment by bourne-3** [comment]
> @cgapu Be inspired by you, I thought of another way, which I think is more efficient. Of course, rewriting **Marshal** of `runtime.JSONPb` is needed.
> 
> ```
> func CustomNormalHandler(ctx context.Context, w http.ResponseWriter, m proto.Message) error {
> 	marshaler := runtime.JSONPb{
> 		MarshalOptions: protojson.MarshalOptions{
> 			EmitUnpopulated: true,
> 			UseProtoNames:   true,
> 		},
> 	}
> 	jsonBytes, _ := marshaler.Marshal(m)
> 	buf, err := json.Marshal(Response{
> 		Code: 0,
> 		Msg:  "success",
> 		Data: json.RawMessage(jsonBytes),
> 	})
> 	if err != nil {
> 		return err
> 	}
> 	w.Write(buf)
> 	return nil
> }
> ```

i use this way to deal，but the response show like below
```
{
    "code": 0,
    "msg": "success",
    "data": {
        "isSucc": false
    }
}{
    "isSucc": false
}
```
how to eliminate the 
```
{
    "isSucc": false
}
```

**Comment by agambondan** [comment]
> > @cgapu Be inspired by you, I thought of another way, which I think is more efficient. Of course, rewriting **Marshal** of `runtime.JSONPb` is needed.
> > ```
> > func CustomNormalHandler(ctx context.Context, w http.ResponseWriter, m proto.Message) error {
> > 	marshaler := runtime.JSONPb{
> > 		MarshalOptions: protojson.MarshalOptions{
> > 			EmitUnpopulated: true,
> > 			UseProtoNames:   true,
> > 		},
> > 	}
> > 	jsonBytes, _ := marshaler.Marshal(m)
> > 	buf, err := json.Marshal(Response{
> > 		Code: 0,
> > 		Msg:  "success",
> > 		Data: json.RawMessage(jsonBytes),
> > 	})
> > 	if err != nil {
> > 		return err
> > 	}
> > 	w.Write(buf)
> > 	return nil
> > }
> > ```
> 
> i use this way to deal，but the response show like below
> 
> ```
> {
>     "code": 0,
>     "msg": "success",
>     "data": {
>         "isSucc": false
>     }
> }{
>     "isSucc": false
> }
> ```
> 
> how to eliminate the
> 
> ```
> {
>     "isSucc": false
> }
> ```

![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/37768596/e1b60a0d-7a34-44e7-af33-11441d1dd2c0)

you can't custom response writer, cause pb gw will call this method :
[ForwardResponseMessage](https://github.com/grpc-ecosystem/grpc-gateway/blob/4c10d2a5bffd64a1db363c6ac31da14568ba862e/runtime/handler.go#L136)

**Comment by DouFuJuShi** [comment]
import (
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/genproto/googleapis/rpc/status"
	"google.golang.org/protobuf/proto"
)
type Response struct {
	Code    int32            `json:"code"`
	Message string        `json:"message"`
	Data    proto.Message `json:"data,omitempty"`
}

type CustomMarshaler struct {
	*runtime.JSONPb
}

func (cm *CustomMarshaler) Marshal(v interface{}) ([]byte, error) {
	var resp *Response
	if typedV, ok := v.(*status.Status); ok {
		resp = &Response{
			Code:    typedV.GetCode(),
			Message: typedV.GetMessage(),
		}
	} else {
		resp = &Response{
			Code:    0,
			Message: "OK",
			Data:    v.(proto.Message),
		}
	}
	return cm.JSONPb.Marshal(resp)
}

func (cm *CustomMarshaler) Unmarshal(data []byte, v interface{}) error {
	return cm.JSONPb.Unmarshal(data, v)
}

func (cm *CustomMarshaler) NewDecoder(r io.Reader) runtime.Decoder {
	return cm.JSONPb.NewDecoder(r)
}

func (cm *CustomMarshaler) NewEncoder(w io.Writer) runtime.Encoder {
	return cm.JSONPb.NewEncoder(w)
}

func (cm *CustomMarshaler) ContentType(v interface{}) string {
	return runtime.MIMEWildcard
}

mux := runtime.NewServeMux(
       runtime.WithMarshalerOption("*", &CustomMarshaler{}),
)

**Comment by DouFuJuShi** [comment]
`import (
"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
"google.golang.org/genproto/googleapis/rpc/status"
"google.golang.org/protobuf/proto"
)
type Response struct {
Code int32 json:"code"
Message string json:"message"
Data proto.Message json:"data,omitempty"
}

type CustomMarshaler struct {
*runtime.JSONPb
}

func (cm *CustomMarshaler) Marshal(v interface{}) ([]byte, error) {
var resp *Response
if typedV, ok := v.(*status.Status); ok {
resp = &Response{
Code: typedV.GetCode(),
Message: typedV.GetMessage(),
}
} else {
resp = &Response{
Code: 0,
Message: "OK",
Data: v.(proto.Message),
}
}
return cm.JSONPb.Marshal(resp)
}

func (cm *CustomMarshaler) Unmarshal(data []byte, v interface{}) error {
return cm.JSONPb.Unmarshal(data, v)
}

func (cm *CustomMarshaler) NewDecoder(r io.Reader) runtime.Decoder {
return cm.JSONPb.NewDecoder(r)
}

func (cm *CustomMarshaler) NewEncoder(w io.Writer) runtime.Encoder {
return cm.JSONPb.NewEncoder(w)
}

func (cm *CustomMarshaler) ContentType(v interface{}) string {
return runtime.MIMEWildcard
}

mux := runtime.NewServeMux(
runtime.WithMarshalerOption("*", &CustomMarshaler{}),
)`

**Comment by DouFuJuShi** [comment]
`package main

import (
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/genproto/googleapis/rpc/status"
	"google.golang.org/protobuf/proto"
	"io"
)

type Response struct {
	Code    int32         `json:"code"`
	Message string        `json:"message"`
	Data    proto.Message `json:"data,omitempty"`
}

type CustomMarshaler struct {
	*runtime.JSONPb
}

func (cm *CustomMarshaler) Marshal(v interface{}) ([]byte, error) {
	var resp *Response
	if typedV, ok := v.(*status.Status); ok {
		resp = &Response{
			Code:    typedV.GetCode(),
			Message: typedV.GetMessage(),
		}
	} else {
		resp = &Response{
			Code:    0,
			Message: "OK",
			Data:    v.(proto.Message),
		}
	}
	return cm.JSONPb.Marshal(resp)
}

func (cm *CustomMarshaler) Unmarshal(data []byte, v interface{}) error {
	return cm.JSONPb.Unmarshal(data, v)
}

func (cm *CustomMarshaler) NewDecoder(r io.Reader) runtime.Decoder {
	return cm.JSONPb.NewDecoder(r)
}

func (cm *CustomMarshaler) NewEncoder(w io.Writer) runtime.Encoder {
	return cm.JSONPb.NewEncoder(w)
}

func (cm *CustomMarshaler) ContentType(v interface{}) string {
	return runtime.MIMEWildcard
}

func main() {
   mux  := runtime.NewServeMux(
		    runtime.WithMarshalerOption("*", &CustomMarshaler{}),
	    )
.........
}
`
