### ISSUE TITLE
Use grpc gateway to create rest API whose body is a list

### ISSUE THREAD

**Issue by ganeshdipdumbare** [grpc-ecosystem/grpc-gateway#1617]
## 📚 Documentation

I am not able to find documentation as well as any example in case I want to accept list in the body of rest api as follows -
`[
    {
      "email": "Hello"
    },
    {
      "email": "Hello"
    }
]`

I am not sure if it is possible to create proto message to have such a rest api. Please let me know if it is not possible as I am working with api call where 3rd party caller is sending array directly as above.

**Comment by johanbrandhorst** [comment]
Lists at the top level will probably require you to use `google.protobuf.ListValue` as request type. See https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto for these types. They have special case handling in the gateway marshaler. I speak briefly about the special case handling of the well known types in my GopherCon UK 2019 talk: https://www.youtube.com/watch?v=Pq1paKC-fXk.

If you need more assistance, please reach out on the #grpc-gateway support channel on Gophers slack.
