### ISSUE TITLE
same field in params

### ISSUE THREAD

**Issue by DjanFey** [grpc-ecosystem/grpc-gateway#1621]
## 🚀 Feature

thank you for providing such an awsome lib., I want to know how to get the same field in params, such as {"user":{"id":1},"order":{"id":1}}, I define the proto file like 
```
    message User {
        int32 id = 1;
    }
    
    message Order {
        int32 id = 1;
    }

    message Req{
        User user = 1;
        Order order = 2;
    }
```
I want to transport the params in body like 
```
{"user":{"id":1},"order":{"id":1}}
```
but i get nothing at backend server

**Comment by johanbrandhorst** [comment]
That looks right to me, maybe you could join our support slack channel and we could figure out what's wrong? This isn't a great forum for this sort of debugging.
