### ISSUE TITLE
`runtime.WithForwardResponseOption()` is not respected

### ISSUE THREAD

**Issue by labsvisual** [grpc-ecosystem/grpc-gateway#1625]
## 🐛 Bug Report

When forward response options are provided to the runtime, they are not executed. 

## To Reproduce

```go
mux := runtime.NewServeMux(
	runtime.WithForwardResponseOption(httpResponseModifier),
)
```

Here, `httpResponseModifier` has the following definition (this is a [direct copy of the related documentation](https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html)):

```go
func httpResponseModifier(ctx context.Context, w http.ResponseWriter, p protoiface.MessageV1) error {
        fmt.Println("in response modifier") // debug:withContext(debugger::parent)

	md, ok := runtime.ServerMetadataFromContext(ctx)
	if !ok {
		return nil
	}

	// set http status code
	if vals := md.HeaderMD.Get("x-http-code"); len(vals) > 0 {
		code, err := strconv.Atoi(vals[0])
		if err != nil {
			return err
		}
		w.WriteHeader(code)

		// delete the headers to not expose any grpc-metadata in http response
		delete(md.HeaderMD, "x-http-code")
		delete(w.Header(), "Grpc-Metadata-X-Http-Code")
	}

	return nil
}
```

The piece in the documentation uses `proto.Message` but that throws an error:
<img width="1674" alt="Screen Shot 2020-08-28 at 8 24 35 PM" src="https://user-images.githubusercontent.com/13390457/91581814-95f7b480-e96c-11ea-9885-812a585c02d7.png">

## Expected behavior

The forward response options should be executed. 

## Actual Behavior

The `httpResponseModifier` function does not execute. I tried adding code to the actual package to help me with debugging and `mux.forwardResponseOptions` does have a `len() > 1` so I am not sure what's happening here.

## Your Environment

macOS 10.15.5 (19F101)
go version go1.14.7 darwin/amd64
grpc-gateway 1.14.7

**Comment by johanbrandhorst** [comment]
Hi Shreyansh, this is likely happening because you're using the APIv2 protobuf stack. Please try again with grpc-gateway v2: https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.0.0-beta.4. See https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/docs/_docs/v2-migration.md for the migration guide.

**Comment by labsvisual** [comment]
Just updated the stack to v2, the error (in the image) went but the forwardResponseOptions are still not being executed. The code is absolutely the same (save the import as "github.com/grpc-ecosystem/grpc-gateway/v2/runtime".)

**Comment by johanbrandhorst** [comment]
This would be easier to help with on our Slack support channel, #grpc-gateway on Gophers Slack. This isn't the best forum for this sort of debugging. Could we move this conversation there?
