### ISSUE TITLE
Update v2 generator for new protoc-gen-go-grpc API

### ISSUE THREAD

**Issue by veith** [grpc-ecosystem/grpc-gateway#1655]
## 🚀 Feature

protoc-gen-go-grpc produces files which are slightly different to the ones which are generated by protoc-gen-go (with plugin grpc). 

[A sample of the needed change can be seen here](https://github.com/veith/grpc-gateway/commit/323bfae3f9d29447450f0e841a113289c610a89d). I posted it to show what i meant. I ask for the flag, because this change can be made without breaking in v1 too.

**Comment by f-zou** [comment]
that is a good idea. It would be great if it could be added.

**Comment by johanbrandhorst** [comment]
We'll make these changes for v2 only, as one of the major reasons v2 exists is to deal with this transition to APIv2. This is the whole reason we're waiting for protoc-gen-go-grpc to be stable before tagging v2. Thanks for sketching out the changes, if you'd like to open a PR we can update our protoc-gen-go-grpc version at the same time.

**Comment by MarcOmlin** [comment]
Im facing the same differences. It would be great if this flag could be added.

**Comment by veith** [comment]
> We'll make these changes for v2 only, as one of the major reasons v2 exists is to deal with this transition to APIv2. This is the whole reason we're waiting for protoc-gen-go-grpc to be stable before tagging v2. Thanks for sketching out the changes, if you'd like to open a PR we can update our protoc-gen-go-grpc version at the same time.

I will check out the v2 branch and test the changes on v2@3f53bccf030cc87af1a0e357734b4e5ba167c411 using google.golang.org/grpc v1.32.0

**Comment by johanbrandhorst** [comment]
Note that if you're getting a build error it is because you're using a very recent version of protoc-gen-go-grpc, that does not have a stable release yet. You can use the same version that we're using with v2 by inspecting our go.mod file. We're not going to keep updating it (unless by community contributions) until a stable version has been released, as we anticipate more breaking changes.

**Comment by veith** [comment]
The changes work with 
google.golang.org/grpc/cmd/protoc-gen-go-grpc v0.0.0-20200826230536-d31b6710005d (latest)
github.com/grpc-ecosystem/grpc-gateway/v2 v2.0.0-beta.4.0.20200909005528-3f53bccf030c

[source changes](https://github.com/veith/grpc-gateway/commit/6b3744cd439b0bc1e04628d1bbdb34059f5e57e5)
[changes in go mod](https://github.com/veith/grpc-gateway/commit/112459272cdc1cc6974e38e05d2140f0177c12e3)

I sadly do not know how to run your tests. Maybe you can give me a hint. I tested it "manually" with a trivial service and the following command. The resulting pb files are working with  .../v2/runtime

``` bash
protoc --proto_path=./ \
--plugin=../../../bin/protoc-gen-go-grpc \
-I. \
-I../../../dependencies/github.com/theNorstroem/furoBaseSpecs/dist/proto/Messages \
-I$GOPATH/src/github.com/googleapis/googleapis \
-I/usr/local/include \
-I$GOPATH/src \
-I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
-I../Messages \
--go-grpc_out=\
Mauth/auth.proto=$DOMAINTYPESPATH/auth,\
Msample/sample.proto=$DOMAINTYPESPATH/sample,\
:$TMPDIR \
--go_out=\
Mauth/auth.proto=$DOMAINTYPESPATH/auth,\
Msample/sample.proto=$DOMAINTYPESPATH/sample,\
:$TMPDIR \
--grpc-gateway_out=logtostderr=true:$TMPDIR  $f
```

**Comment by johanbrandhorst** [comment]
See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes for a guide to regenerating all the files and how to run the tests. Could you create a pull request with the source changes please? I'm not accustomed to manually comparing trees.

**Comment by veith** [comment]
> See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes for a guide to regenerating all the files and how to run the tests. Could you create a pull request with the source changes please? I'm not accustomed to manually comparing trees.

Yes, after running the tests. I assume that the changes will not work with --go_out=plugins=grpc

**Comment by johanbrandhorst** [comment]
:man_shrugging: I like to let the CI tests figure out if I messed up. Don't worry about having some failing tests in the PR while we iterate on it.

**Comment by johanbrandhorst** [comment]
The v2 Makefile is [already instrumented](https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/Makefile#L166) to use the new generator, all you need to do is run the commands listed in CONTRIBUTING.md.

**Comment by veith** [comment]
Can i do something on the failed checks by my own?

- ci/circleci: bazel — Your tests failed on CircleCI
- ci/circleci: fuzzit — Your tests failed on CircleCI
- ci/circleci: generate — Your tests failed on CircleCI

**Comment by johanbrandhorst** [comment]
This is done
