### ISSUE TITLE
protoc-gen-swagger: allow `-output` dir

### ISSUE THREAD

**Issue by anilCSE** [grpc-ecosystem/grpc-gateway#1679]
Current `protoc-gen-swagger` doesn't have support for custom directory for generated files. It generates swagger files in the same directory structure as proto files. Moving them into a separate folder is an extra task for developers. Having a `-output` flag to specify the output dir can solve this and improve the experience

**Comment by johanbrandhorst** [comment]
Hi, thanks for your interest in the project! Isn't this already supported? Looking at [the README example](https://github.com/grpc-ecosystem/grpc-gateway#usage):

```
protoc -I . --swagger_out ./gen/swagger --swagger_opt logtostderr=true your/service/v1/your_service.proto
```

The value provided to `--swagger_out` is where the output of the file should go (in this case, `./gen/swagger`). Does that work for you?

**Comment by anilCSE** [comment]
Thank you very much @johanbrandhorst for your help. I was using it wrongly.
