### ISSUE TITLE
Sending NULL for int64/uint64 types calls gRPC server with zero-value

### ISSUE THREAD

**Issue by maja42** [grpc-ecosystem/grpc-gateway#1681]
## 🐛 Bug Report

When defining a gRPC server whose request message contains an integer type (tested with int64 and uint64), the grpc-gateway interprets null-values as zero.

## To Reproduce

1. Define a gRPC endpoint with only a POST-http-mapping. The request message should look like this:

```
message Request {
    int64 i64 = 1;
    uint64 ui64 = 2;
}
```

2. Generate and start the grpc-gateway
3. Perform a POST-call and send the following json request body:
```
{"i64": null, "ui64": null}
```

## Expected behavior

I expect the same behaviour as if I would send any other invalid value (for example the string `"text"` or the boolean `true`):
- The RPC-call should NOT be performed
- The response should be 400 (Bad Request) with an error body "code: 3 (invalid argument)" and a message containing `"invalid value for int64 type"`

## Actual Behavior

The same as if I sent the value zero.

## Your Environment

Im using github.com/grpc-ecosystem/grpc-gateway/v2 v2.0.0-beta.4

## Notes:

I suspect that the "null" value is interpreted as if the field is not present in the request body at all and therefore the protobuf marshaller uses the zero-value for that field.

It's unclear to me if this should actually be the desired behaviour and if it wouldn't make more sense to treat "null" different to "field does not exist".

Alternatively it might make sense to add a json-marshaller option that says "all mandatory (non-nullable) protobuf fields must be present in the request", meaning that zero-values must be sent explicitly.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your bug report :smile:. The JSON marshalling behaviour is controlled by the instrumented JSON marshaller, which on v2 is https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson. If you want to change the behaviour of the marshaller, I suggest raising an issue with that project or creating your own marshaller and using it with https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2@v2.0.0-beta.4/runtime#WithMarshalerOption.

Hope that helps.
