### ISSUE TITLE
Add option to remove (or remove) package comment in generated .pb.gw.go files

### ISSUE THREAD

**Issue by olivierlemasle** [grpc-ecosystem/grpc-gateway#1701]
## 🚀 Feature

Please add the option to remove (or remove) the package comment from generated `.pb.gw.go` files:

```go
/*
Package xxx is a reverse proxy.
It translates gRPC into RESTful JSON APIs.
*/
package xxx
```

Actually, this was already proposed by @RJPercival in its PR #1103, which went stale.

Here is an example of what causes current behavior, on project chef/automate (NOT my project, I just looked to one of the [adopters](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/ADOPTERS.md)):

`.gw.go` files generated by protoc-gen-grpc-gateway are saved in the same directory as the `.proto` source file, the gRPC `.pb.go` file and other generated files: see https://github.com/chef/automate/tree/b059b29/api/external/applications

However, since the protoc-gen-grpc-gateway has a package documentation comment (applicable for a whole package, not for a file), the whole package is documented "Package applications is a reverse proxy.", which does not make sense.

See https://pkg.go.dev/github.com/chef/automate/api/external for the documentation of such a package.

**Comment by johanbrandhorst** [comment]
CC @srenatus :joy:. This sounds like a reasonable request to avoid this sort of thing. I'd love to review a PR that adds this capability.

**Comment by srenatus** [comment]
Hehe, good find. Never occurred to me to look at those packages' godoc. Yeah, let's get rid of these :+1:

**Comment by olivierlemasle** [comment]
Actually, there's already PR #1103, but it is closed and needs rebase. Should I open a new PR?

**Comment by johanbrandhorst** [comment]
Yes please, we can't reopen users pull requests without explicit license to use the code, so it'd be easiest to create a new one. Thanks!

**Comment by RJPercival** [comment]
I'm happy to reopen that PR, if someone would like to rebase it?

**Comment by olivierlemasle** [comment]
@RJPercival Thank you, but not being a maintainer, I can not edit your PR to rebase it, so I've just created a new one #1702.
