### ISSUE TITLE
Error when trying to call endpoint with empty parameter of Enum array

### ISSUE THREAD

**Issue by ghostiam** [grpc-ecosystem/grpc-gateway#1711]
## 🐛 Bug Report

Error when trying to call endpoint with empty parameter of Enum array (select `--` from Swagger UI)

```curl
curl -X GET "http://127.0.0.1:3000/endpoint?entities="
```
```json
{
  "code": 3,
  "message": "parsing list \"entities\": \"\" is not a valid value"
}
```

Function that returns an error: `Parse -> populateFieldValueFromPath`
https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/runtime/query.go#L53

I think we can ignore all empty parameters, since grpc does not distinguish nil from the default value (as far as I know, I may be wrong).
If you agree, I can fix this bug.

## To Reproduce

```proto
enum LogEntity {
  UNSPECIFIED = 0;
  SPOT = 1;
  GROUP = 2;
}

message Request{
  repeated LogEntity entities = 1;
}
message Response{
}

service Test {
  rpc Endpoint (Request) returns (Response) {
    option (google.api.http) = {
      get: "/endpoint"
    };
  }
}
```

```curl
curl -X GET "http://127.0.0.1:3000/endpoint?entities="
```

### From debugger

```
?actions=&entities=
```
![Снимок экрана 2020-10-02 в 16 53 02](https://user-images.githubusercontent.com/12181586/94900423-ee702380-04cf-11eb-991c-816b2661e5da.jpg)

## Expected behavior

Empty fields should be ignored.

## Actual Behavior

Error: parsing list "entities": "" is not a valid value.

## Your Environment

grpc-gateway v2@v2.0.0-beta.5

## UPD: 🙈 Crutch

```go
emptyValueFixer := runtime.WithMetadata(func(ctx context.Context, req *http.Request) metadata.MD {
	_ = req.ParseForm()

	values := req.Form
	for k, v := range values {
		if len(v) == 1 && v[0] == "" {
			delete(values, k)
		}
	}

	return nil
})
```

**Comment by johanbrandhorst** [comment]
I'm not convinced this is a bug. You're right that proto3 doesn't distinguish between unset and default, but the default for an enum is not the empty string. I don't think using an empty string for a enum lookup would result in the default value anywhere else you try to do that conversion.

If this is a problem for you we have the ability to configure the query parser with https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2@v2.0.0-beta.5/runtime#SetQueryParameterParser.

I'm going to close this issue, but please feel free to let us know if you disagree and want to continue the discussion.

**Comment by ghostiam** [comment]
@johanbrandhorst, my problem is not empty enum value but empty value when using enum array.
I think `SetQueryParameterParser` is not quite suitable for me, since I have to copy a lot of code, just to ignore the empty field (I can't reuse the current code, it's private).

**Comment by johanbrandhorst** [comment]
The way the query parser works for repeated types is that each entry is provided separately, e.g. `entities="bla1"&entities="bla2"`. So there isn't a matter of parsing a query array from `entities=""`, it will always try to parse it as an enum. I don't think we can special case this.
