### ISSUE TITLE
too many arguments in call to runtime.NewPattern and  undefined: runtime.AssumeColonVerbOpt

### ISSUE THREAD

**Issue by josvegit** [grpc-ecosystem/grpc-gateway#1723]
Installing according to your docs
![image](https://user-images.githubusercontent.com/24354568/95205874-436cac00-07e6-11eb-933f-81e4d5dfa17a.png)

protoc version
![image](https://user-images.githubusercontent.com/24354568/95205990-6c8d3c80-07e6-11eb-995f-14c45170933c.png)

gateway code errors
![image](https://user-images.githubusercontent.com/24354568/95206079-8a5aa180-07e6-11eb-87c9-8419e8e79e8a.png)

Looking through the issues maybe there is some version issue or something ? Not sure its a bug but would be nice with some guidance

**Comment by johanbrandhorst** [comment]
Our docs haven't recommended this way of installing for a long time. Can you try again following https://github.com/grpc-ecosystem/grpc-gateway#installation? The issue is a version mismatch between the generator and the runtime library.

**Comment by josvegit** [comment]
> Our docs haven't recommended this way of installing for a long time. Can you try again following https://github.com/grpc-ecosystem/grpc-gateway#installation? The issue is a version mismatch between the generator and the runtime library.

Thanks alot, sry

**Comment by josvegit** [comment]
Getting same error now that I use go modules
![image](https://user-images.githubusercontent.com/24354568/95208736-c80cf980-07e9-11eb-8857-4eb19aa39c6b.png)
