### ISSUE TITLE
https://github.com/grpc-ecosystem/grpc-gateway/issues/1723

### ISSUE THREAD

**Issue by josvegit** [grpc-ecosystem/grpc-gateway#1724]
https://github.com/grpc-ecosystem/grpc-gateway/issues/1723

Followed the installation instructions using go modules
![image](https://user-images.githubusercontent.com/24354568/95210273-9f85ff00-07eb-11eb-9762-ca24e383bb3c.png)

still getting 
![image](https://user-images.githubusercontent.com/24354568/95210317-a90f6700-07eb-11eb-9996-13fccb0569a5.png)

install
![image](https://user-images.githubusercontent.com/24354568/95210758-1de2a100-07ec-11eb-9353-c03571378c66.png)

sample from generated code
![image](https://user-images.githubusercontent.com/24354568/95211045-626e3c80-07ec-11eb-8395-e2fb0aa6b912.png)

**Comment by josvegit** [comment]
![Uploading image.png…]()

**Comment by josvegit** [comment]
should proto-gen-go and grpc-gateway have the exact same version ?

**Comment by johanbrandhorst** [comment]
No, but `github.com/grpc-ecosystem/grpc-gateway` and `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` has to be the same versions. Are you installing using `go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` from the same folder as the `go.mod` you just created?

This is the sort of debugging that would be better served on our slack support channel btw; #grpc-gateway on [Gophers Slack](https://invite.slack.golangbridge.org/). Could you jump on there instead?

I'm going to close this as it's probably an environment issue.

**Comment by josvegit** [comment]
I was going to use your slack channel but I only get 

![image](https://user-images.githubusercontent.com/24354568/95213627-4e780a00-07ef-11eb-8aa5-0f783f7256be.png)

**Comment by josvegit** [comment]
> No, but `github.com/grpc-ecosystem/grpc-gateway` and `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` has to be the same versions. Are you installing using `go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` from the same folder as the `go.mod` you just created?
> 
> This is the sort of debugging that would be better served on our slack support channel btw; #grpc-gateway on [Gophers Slack](https://invite.slack.golangbridge.org/). Could you jump on there instead?
> 
> I'm going to close this as it's probably an environment issue.

That link does not work, yes I'm using go install in the same place as the go.mod is located.

**Comment by josvegit** [comment]
> > No, but `github.com/grpc-ecosystem/grpc-gateway` and `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` has to be the same versions. Are you installing using `go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` from the same folder as the `go.mod` you just created?
> > This is the sort of debugging that would be better served on our slack support channel btw; #grpc-gateway on [Gophers Slack](https://invite.slack.golangbridge.org/). Could you jump on there instead?
> > I'm going to close this as it's probably an environment issue.
> 
> That link does not work, yes I'm using go install in the same place as the go.mod is located.

Tried everything in a docker container, same result

**Comment by josvegit** [comment]
Nothing wrong with the generated code @johanbrandhorst, the project I was using them in had an old dep on an old version of the grpc-gateway... sry

**Comment by johanbrandhorst** [comment]
Glad to hear you figured it out, I'm confused that link didn't work, maybe try the link in our README? https://join.slack.com/t/gophers/shared_invite/zt-gmw97q11-1OWgj2Dqsc13eqoSPwvNDQ. We'd love to have you in the Slack channel if you need any help in the future :smile:.
