### ISSUE TITLE
support annotating fields as required (in swagger/oapi generation)?

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#175]
Obviously proto3 doesn't have required fields so this might not be a fit or be appropriate but it might be nice to allow more detailed annotation of fields. Thoughts?

**Comment by johanbrandhorst** [comment]
You can put comments in your proto files and the swagger generator will put those comments in your swagger.json. See https://github.com/gengo/grpc-gateway/blob/master/examples/examplepb/echo_service.proto for an example of how to format the comments.

**Comment by achew22** [comment]
@tmc additionally yugui has stated that she doesn't want to implement any features in here that aren't in the spec as defined by Google. Right now they don't have required fields. If their spec changes to support that I think we should implement this feature then.  Again, I'm going to close this just to tidy up a bit. If you decide to file an issue upstream with the google repo, would you please comment on here to indicate that you did it. I would love to track the progress and implement if their schema changes.
