### ISSUE TITLE
GOPATH: Build is broken by grpc-gateway/v2/runtime

### ISSUE THREAD

**Issue by lajtovo** [grpc-ecosystem/grpc-gateway#1763]
## 🐛 Bug Report

Our builds started to fail. 

```
Error compiling gateway: gateway/build/gopath/src/broker/broker.pb.gw.go:16:2: cannot find package "github.com/grpc-ecosystem/grpc-gateway/v2/runtime
```

Is there any quick fix for that? 
we are aware you are not supporting gopath since v.2.0.0 but a non-functioning build is very problematic

**Comment by johanbrandhorst** [comment]
Sorry that your build is broken. If you wish to continue consuming the grpc-gateway in a GOPATH project, you will need to stick to the v1 releases. If you use vendor you can pin to https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.15.1. Make sure your generator and runtime dependency are using the same version.

**Comment by tjgykhulj** [comment]
I got the same problem, checkout to v1.15.1 made my project works well.

**Comment by darlandieterich** [comment]
I have same problem², how solved this? my file persist dir "v2".
