### ISSUE TITLE
why was swagger removed

### ISSUE THREAD

**Issue by yearm** [grpc-ecosystem/grpc-gateway#1765]
## 📚 Documentation
why was swagger removed

**Comment by johanbrandhorst** [comment]
https://grpc-ecosystem.github.io/grpc-gateway/docs/v2-migration.html

**Comment by eccles** [comment]
That link is broken...

**Comment by johanbrandhorst** [comment]
I've updated the link, sorry for the inconvenience. In general, my responses on issues will be proportional to the effort the issue reporter has made to find an answer themselves. If OP had read any of our release notes or delved into the documentation at all they would see that we've just renamed `protoc-gen-swagger` to `protoc-gen-openapiv2`.

**Comment by vivekpatani** [comment]
The link still seems to be broken (or maybe I'm missing something?).

**Comment by johanbrandhorst** [comment]
Not sure why the link changed again but I've updated it again, sorry.
