### ISSUE TITLE
grpc-gateway v2 misreads grpc protobuf field_mask behavior, breaks existing valid behavior

### ISSUE THREAD

**Issue by irridia** [grpc-ecosystem/grpc-gateway#1766]
## 🐛 Bug Report

In v2, repeated fields are now only allowed once per global scope:

[https://github.com/grpc-ecosystem/grpc-gateway/blob/4a35071321dc8a3fc19e8042ed54110fd1a42835/runtime/fieldmask.go#L77-L82](https://github.com/grpc-ecosystem/grpc-gateway/blob/4a35071321dc8a3fc19e8042ed54110fd1a42835/runtime/fieldmask.go#L77-L82)

There is a single comment in the protobuf spec that mentions this behavior _on a per-path basis_, not globally. Additionally, [further reading of that same document](https://github.com/protocolbuffers/protobuf/blob/6b0ff74ecf63e26c7315f6745de36aff66deb59d/src/google/protobuf/field_mask.proto#L152-L153) explains the specifics of this behavior, and that this behavior can be modified by an implementation.

While it may make sense that repeated fields can't be duplicated per path, enforcing a single repeated field globally IMHO contradicts both the standard and the explicitly described flexibility.

Multiple repeated fields have been allowed and properly supported by grpc and grpc-gateway for years, and changing this behavior, as it does in my case, makes the protobuf-supported use of field_masks impossible with grpc-gateway, effectively removing it as a reliable feature and breaking existing code bases.

AFAICT, aligning to this behavior would require multiple requests for a single update under logic described by grpc-gateway. This would require API consumers to know that they're hitting a specific new grpc-gateway implementation, and add implementation-specific logic and additional round-trips to work around the issue.

Just as a single person/company data point, this is a permanent hard-blocker for grpc-gateway v2. I absolutely understand the value of grpc-gw v2 as well as the middleware v2 work that I was slightly involved with, so I'd much rather not use v1 in the long term.

Thanks in advance for feedback!

## To Reproduce

Specify an update request with multiple repeated fields, e.g.,

```
{
  "entity0": {
    "field0": {
      "name": "Field Name 0",
      "entries" [
        "entry0",
        "entry1"
      ],
      "category": "entity"
    },
    "field1": {
      "name": "Field Name 1",
      "entries" [
        "entry2",
        "entry3"
      ],
      "category": "otherEntity"
    },
    "requestType": "update"
}
```

## Expected behavior

grpc-gateway v2 should populate field masks in the same compliant and functional way in which v1 performed this operation.

## Actual Behavior

&{Code:3 Details:[] Error: Message:only one repeated value is allowed per field_mask}

## Your Environment

Docker (Linux), go 1.15.3, grpc-gateway v2.0.0, protobuf v1.25.0, grpc v1.33.0

**Comment by johanbrandhorst** [comment]
Thank you for raising this issue! I implemented the new field mask parsing in v2 and it's certainly possible that I misunderstood the spec. I'd be happy to accept a fix for this behaviour, but to be clear, what would you expect `paths` to look like in the example you shared? According to the wording of the document any repeated fields must be in the last part of the paths. Doesn't that contradict wanting to set two different repeated fields, since then one of them is not in the last part of the paths? Or is your request that we allow this behaviour to be overridden via the, as specified, implementation specific default behaviour?

**Comment by nashikb** [comment]
For the paths above, to me these are consistent with the spec:
```
entity0.field0.entries.[entry0,entry1]
entity1.field1.entries.[entry2,entry3]
```
The limitation is on the end of _a_ path, not that there can only be one repeated fields in _all_ paths, at least to my reading. And also to the fact that multiple paths have been and are supported by protobuf/grpc, and v1 supports it. :-)

I can take a look at the code as time allows, if that's the preference.

Thanks!

**Comment by irridia** [comment]
For the paths above, to me these are consistent with the spec:
```
entity0.field0.entries[entry0, entry1]
entity1.field1.entries[entry2, entry3]
```
What would _not_ be consistent, I think, would be:
```
entity0.field0.entries[entry0, entry1]
entity0.field0.entriesB[entry4, entry5]
```

The limitation is on the end of _a_ path, not that there can only be one repeated fields in _all_ paths, at least to my reading. And also to the fact that multiple paths have been and are supported by protobuf/grpc, and v1 supports it. :-)

I can take a look at the code as time allows, if that's the preference.

Thanks!

**Comment by johanbrandhorst** [comment]
I'd love to be able to delegate to `google.golang.org/protobuf` for this logic if we could, the https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/known/fieldmaskpb package was not available when I originally wrote this logic. Have you tested these paths with that parser?

**Comment by johanbrandhorst** [comment]
I had a quick play around with the official field mask helpers and I don't think we can use them until https://github.com/golang/protobuf/issues/1227 is resolved.

**Comment by irridia** [comment]
Makes sense, thanks. Perhaps a more surgical "code borrow" would be sane in the interim.

**Comment by johanbrandhorst** [comment]
Not sure what you're suggesting, but it will not be trivial to copy the v1 logic into the current master logic. A good place to start the work on this would be to add a failing test case to `runtime/fieldmask_test.go`. I'd first verify that the paths you suggested are valid paths as defined by the behaviour of `fieldmaskpb.New`, as I don't think we should introduce any new behaviour here until that's been asserted.

**Comment by johanbrandhorst** [comment]
The answer from the protobuf team was that they were not going to do anything about this in their repo until there's a wider acceptance around this in the protobuf community. As such, I don't think we can rely on `fieldmaskpb.New` anytime soon.

To get back to the core issue, I think I agree that this is a bug, though I won't have the time available to fix this anytime soon. As usual, the easiest way to start working on a fix is to add a failing test case, which should be easy in this case. The logic is well isolated to `./runtime/fieldmask.go` which is tested by `./runtime/fieldmask_test.go`. I'd be happy to provide more guidance to anyone who wants to tackle this, but it seems pretty straightforward to me. The biggest question is just which adjustments are necessary to the current queue based generator.

**Comment by topherCantrell** [comment]
Thanks for your awesome work here! The protobuffer folks have corrected their comments on the "only one" limitation. The restriction is about individual paths -- not the field mask as a whole. I have created a pull request to fix this issue:

https://github.com/grpc-ecosystem/grpc-gateway/pull/1921

**Comment by irridia** [comment]
FYI, grpc v2 now seems to test out in my environment, so please feel free to close this issue. Thanks, all!

**Comment by johanbrandhorst** [comment]
Thank you for reporting back!
