### ISSUE TITLE
Possible way to access request header key,value 

### ISSUE THREAD

**Issue by sandakith** [grpc-ecosystem/grpc-gateway#1780]
I read  and tested CustomMatcher as for your documentation, is there a way to access both key and value of a custom request header. For example if we are to implement JWT autherizer at the gateway level trying to find a way if we can access the token content value also together with key ...

**Comment by johanbrandhorst** [comment]
https://github.com/grpc-ecosystem/grpc-gateway#supported has a section on the automatic translation of headers - there is a special case in place for the `Authorization` header, it is forwarded into gRPC metadata without any modifications, so you can use it as in this example with a gRPC interceptor: https://jbrandhorst.com/post/grpc-auth/.
