### ISSUE TITLE
[ACTION Required] Moving to grpc-ecosystem

### ISSUE THREAD

**Issue by yugui** [grpc-ecosystem/grpc-gateway#179]
Dear contributors, I need your actions.

Currently we are thinking of moving the repository of grpc-gateway to [grpc-ecosystem](https://github.com/grpc-ecosystem) because it is helpful for users if they can find grpc-related products in a single place.

But it requires that contributors to grpc-gateway sign [CLA](https://cla.developers.google.com/clas).

@willtrking, @mattn, @cuongdo, @ivucica, @sunkuet02, @FabianHinz, @vvakame, @JohanSJA, @hbchai 
Would you mind signing the CLA and reply in this issue to let me know that?

**Comment by JohanSJA** [comment]
Just signed.

**Comment by mattn** [comment]
The CLA form, Address point to `golang-nuts@googlegroups.com`. Is this right? I should write my state/location into it?

**Comment by sunkuet02** [comment]
Just Signed

**Comment by yugui** [comment]
@mattn it is intended to be the same CLA as GRPC itself. I think it should be your state/location.

https://github.com/grpc/grpc-go/blob/master/CONTRIBUTING.md

**Comment by mattn** [comment]
Done

**Comment by achew22** [comment]
@yugui, can you speak a little bit about what grpc-ecosystem is and how it fits into the preexisting grpc project? Specifically I am interested in these questions

Will work on these things be done in a public way? On github?
What does governance look like?
What license will they be releasing future code under?
What will this organization do with patentable materials?
Is there a code of conduct for this organization? What behavior is considered acceptable or unacceptable?

**Comment by yugui** [comment]
@achew22 Good question.

> Will work on these things be done in a public way? On github?
> What does governance look like?
> What license will they be releasing future code under?
> What will this organization do with patentable materials?
> Is there a code of conduct for this organization? What behavior is considered acceptable or unacceptable?

It keeps to be public on github, and there's no license change.
For other questions, @zinuga has better answers.

**Comment by FabianHinz** [comment]
signed.

**Comment by vvakame** [comment]
I signed it already.

**Comment by ivucica** [comment]
I'm a Googler, so no CLA is required.

My future patches will be authored by my work address. (It's a bit too messy to edit the old patches.)

**Comment by mattn** [comment]
ping @willtrking, @cuongdo, @hbchai

**Comment by cuongdo** [comment]
signed

**Comment by willtrking** [comment]
Signed

**Comment by hbchai** [comment]
Signed

**Comment by zinuga** [comment]
On other stuff, yes work on this will done in public and license, patents will be governed by CLA. See this guidelines doc on how we will accept contributions to grpc-ecosystem.
https://github.com/grpc/grpc-contrib/blob/master/CONTRIBUTING.md.

**Comment by yugui** [comment]
To summarize,

> Will work on these things be done in a public way? On github?

It will be done in public in the github organization, grpc-ecosystem.

> What does governance look like?

* Contributors are expected to follow the contributor guideline of gRPC, https://github.com/grpc/grpc-contrib/blob/master/CONTRIBUTING.md.
* Decision will be made in github issues.

> What license will they be releasing future code under?

* No license change when we distribute grpc-gateway in github.
* There's a section about license in CLA

> What will this organization do with patentable materials?

* patent will be covered by CLA

> Is there a code of conduct for this organization? What behavior is considered acceptable or unacceptable?

* No explicit code of conduct to apply.

@zinuga Could you correct me if something is wrong?
@achew22 Is everything clear for you?

**Comment by yugui** [comment]
Done.

Thank you for your contributions and cooperation!
