### ISSUE TITLE
Does grpc-gateway support in-body POST parameters? If so I'm not able to figure out how.

### ISSUE THREAD

**Issue by irridia** [grpc-ecosystem/grpc-gateway#1790]
## 📚 Documentation

I have one special case where I want to receive a POST to a grpc-gw service, but this request (which is outside my control) POSTs query parameters in the body, rather than JSON.

Is this supported by grpc-gateway (via annotations, presumably)? If so, it would be great to have that process more clearly documented.

If not, maybe a simple mention in the docs would be useful.

And apologies if this is documented somewhere: I spent a couple of hours going through docs and code and experiments and wasn't able to figure it out.

Thanks!

**Comment by johanbrandhorst** [comment]
Do you mean that the request is using the `application/x-www-form-urlencoded` content type? If so, this is solvable by specifying a custom marshaller for this content type at ServeMux creation time; see https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#NewServeMux and https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption.

If this works for your use case I'd love if you'd contribute a little blurb about it for our documentation page. Thanks!

**Comment by irridia** [comment]
Apologies for the delayed response.

I ended up spending quite a bit of time on this late last year.

The goal for me was to have an easy way to add a ~single trivial "non-schema-ed" endpoint to a grpc-gw service using protobuf defs. But it ends up a rabbit hole that, in my estimation, is too far from the letter and spirit of protobufs and the gw.

It is indeed possible to implement a `application/x-www-form-urlencoded` endpoint, and thanks Johan for calling out the content type—I can never remember it, and trying to search the interwebs with that content type was so much more revealing.

However, one of two things must be true:

1. The entire payload must be loaded into one field, ala: `message URLEncoded { string payload = 1; }`. At that point, server code would then parse out the URL query from Request.GetPayload() and do the needful. While this works, it actually takes a lot more complicated (and thus less maintainable) code than just adding a single router/handler on a mux for an endpoint. And it requires queries to be single-valued, ala `foo.com/api?payload=`. At best, you could urlencode a JSON blob on that one query parameter.
2. Protobuf relies on explicit field ordering for efficient encoding. URL query strings obviously do not have this constraint, unless Protobuf client/server libraries are written to encode payloads in query strings rather than JSON. For me, this is where I realized this approach was nonsense—multiple encodings add complexity, confusion, at least doubles maintenance costs, and is deeply inconsistent with the Protobuf premise, IMHO. In technical terms, it's just dumb.

This issue is already marked stale, but I wanted to add some background on why ultimately one should use GRPC-GW for JSON-encoded Protobufs, and standard routers on a mux for REST. I believe there's enough information already out there to allow someone to dig the same hole I did, so I rescind my request for further documentation. :)
