### ISSUE TITLE
add version information at compile-time

### ISSUE THREAD

**Issue by qianguodong** [grpc-ecosystem/grpc-gateway#1803]
## 🐛 Bug Report
I want to add version information at compile-time, but it does not take effect when using the following command:
```
$ go get -ldflags="-X github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway.version=v2.0.1" github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.0.1
```

any comments?

**Comment by johanbrandhorst** [comment]
You can see the logic we're using for the versioning here: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/main.go#L39-L43. If you download one of the precompiled versions from the releases it will have the version set.

**Comment by qianguodong** [comment]
thx, it works when I use the command as follows:

```
go get -ldflags="-X 'main.version=v2.0.1'" github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.0.1
```
