### ISSUE TITLE
Cannot resolve import 'google/api/http.proto'

### ISSUE THREAD

**Issue by bytegriffin** [grpc-ecosystem/grpc-gateway#1809]
## 🐛 Bug Report
Cannot resolve import 'google/api/http.proto'

## To Reproduce
An error occurred When I copy the proto file in third_party/googleapis/ directory.

## Expected behavior
Why does annotations.proto file prompt that it can't be found http.proto file?

## Actual Behavior
![test](https://user-images.githubusercontent.com/5327447/98909765-376abd00-24fd-11eb-861a-09e36defa2bb.jpg)

## Your Environment
OS：Windows 10
Go version go1.15.4 windows/amd64   
IDE：Goland 2020.2

**Comment by johanbrandhorst** [comment]
I expect you probably need to add `proto` as a protobuf import path in Goland - this sort of support issue is generally outside the scope of our repository, and if you continue to have issues I suggest talking to Jetbrains support.

**Comment by bytegriffin** [comment]
Thank you. It works.

**Comment by std-c** [comment]
> Thank you. It works.

大兄弟，如何處理的？

**Comment by yiwenlong** [comment]
> > Thank you. It works.
> 
> 大兄弟，如何處理的？

![image](https://user-images.githubusercontent.com/9609929/120732401-d564ba00-c517-11eb-9789-1b19205cc76d.png)
把proto文件路径添加进去就可以了。

**Comment by yiwenlong** [comment]
> > Thank you. It works.
> 
> 大兄弟，如何處理的？

![image](https://user-images.githubusercontent.com/9609929/120732694-50c66b80-c518-11eb-885b-1acf4532788e.png)
大兄弟，这么处理，我也刚搞定。
