### ISSUE TITLE
`generate_unbound_methods` option and FieldMask fields don't work together.

### ISSUE THREAD

**Issue by zoido** [grpc-ecosystem/grpc-gateway#1816]
## 🐛 Bug Report

There seems to be inconsistency between generated OpenAPI specs and jsonproto Unmarshaler specs.

`wktSchemas` do says that:
> The schemas must match with the behavior of the JSON unmarshaler in https://github.com/protocolbuffers/protobuf-go/blob/v1.25.0/encoding/protojson/well_known_types.go

Docs in the Umarshaler specification say that:
> The JSON representation for a FieldMask is a JSON string where paths are separated by a comma.

When the `generate_unbound_methods=true` option is used, generated OpenAPI spec has fieldmask fields as:
```json
{
	"type": "array",
	"items": {
		"type": "string"
	}
}
```

This causes when failures when requests that adhere to the generated specification arrive to the server (see the reproduction step below).
When the generated client code is type-checked, there's usually no way to override the content of the request body.

I am willing to help with this issue. I am not sure at this point what else the change that would change the type in the OpenAPI spec affect.

### References

https://github.com/grpc-ecosystem/grpc-gateway/blob/26104fd424bf45f44d498149b071ef657d604f2b/protoc-gen-openapiv2/internal/genopenapi/template.go#L27-L36

https://github.com/protocolbuffers/protobuf-go/blob/3f7a61f89bb6813f89d981d1870ed68da0b3c3f1/encoding/protojson/well_known_types.go#L833-L836

## To Reproduce

1. Have a minimal proto:
	```proto
	// api/v1/example.proto
	syntax = "proto3";
	
	package zoido.example;
	option go_package = "api/v1;example";
	
	import "google/protobuf/field_mask.proto";
	
	service Example {
	  rpc Update(UpdateRequest) returns(UpdateResponse) {}
	}
	
	message UpdateRequest {
	  string name = 1;
	  google.protobuf.FieldMask update_mask = 2;
	}
	message UpdateResponse {}
	
	```

1. Generate code:
	```sh
	protoc --go_out=:. --go-grpc_out=:. \
    	--grpc-gateway_out=:. --grpc-gateway_opt=generate_unbound_methods=true \
	    --openapiv2_out=:. --openapiv2_opt=generate_unbound_methods=true \
	    api/v1/*.proto
	
	```
1. Inspect the swagger definition:
	relevant part:
	```json
	{
      "definitions": {
        "exampleUpdateRequest": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "updateMask": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }

	```
1. Have a simple app:
	```go
	// main.go
	package main
	
	import (
		"context"
		"log"
		"net/http"
	
		"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
		"google.golang.org/grpc"
	
		example "github.com/zoido/fieldmask-example/api/v1"
	)
	
	func main() {
		conn, err := grpc.Dial("localhost:1111", grpc.WithInsecure())
		if err != nil {
			log.Fatalf("%+v", err)
		}
	
		mux := runtime.NewServeMux()
		err = example.RegisterExampleHandler(context.Background(), mux, conn)
		if err != nil {
			log.Fatalf("%+v", err)
		}
	
		srv := &http.Server{
			Addr:    ":5000",
			Handler: mux,
		}
		err = srv.ListenAndServe()
		if err != http.ErrServerClosed {
			log.Fatalf("%+v", err)
		}
	}
	```
1. Start the app:
	```sh
	go run main.go
	```
1. Call the gateway:
	```sh
	curl -X POST http://localhost:5000/zoido.example.Example/Update \
		--data-raw '{"name": "Foo", "update_mask":["name"]}'
	```
1. Reponse:
	```json
	{"code":3,"message":"proto: syntax error (line 1:31): unexpected token [","details":[]}
	```

## Expected behavior

This case should work.

Generated specification would have FieldMask field spec in the form that works with the used Marshaler

or

There would be some runtime mechanism that would process fields before passing them to the Marshaler.

## Actual Behavior

Requests fail in marhsaling/unmarhaling phase.

## Your Environment

`v2.0.1`

**Comment by johanbrandhorst** [comment]
Looking at the fieldMask decoding tests in protojson, it appears that the fieldmask is expected to be a comma-separated string, not an array of items. Perhaps all we need to do here is change the `wktSchema` definition to `string`?

Ref: https://github.com/protocolbuffers/protobuf-go/blob/v1.25.0/encoding/protojson/decode_test.go#L1903-L1915
