### ISSUE TITLE
if there a flag set the metadata first letter not change to uppower

### ISSUE THREAD

**Issue by damozhiying** [grpc-ecosystem/grpc-gateway#1830]
if there a flag,set the metadata first letter not change to uppower,
```
grpc.SetHeader(ctx, metadata.Pairs("Grpc-Metadata-Some-Key", "222222222xxxxxxxxxx"))
	grpc.SetHeader(ctx, metadata.Pairs("WWW-Authenticate", "222222222xxxxxxxxxx"))
	grpc.SendHeader(ctx, metadata.Pairs("ABC-WWW-Authenticate", "222222222xxxxxxxxxx"))
```
browser f12 show 
```
Content-Type →application/json
Lxf--Abc-Www-Authenticate →222222222xxxxxxxxxx
Lxf--Content-Type →application/grpc
Lxf--Grpc-Metadata-Some-Key →222222222xxxxxxxxxx
Lxf--Www-Authenticate →222222222xxxxxxxxxx
```
i need not change the header key ,is there a method?

**Comment by johanbrandhorst** [comment]
HTTP headers are case-insensitive according to the spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html. We use the Go standard library to produce the HTTP headers, but trying to produce case sensitive headers is not going to work, I'm afraid. Certain proxies will rewrite all headers to be lower case (envoy does this).

Closing as we can't/won't change this in the grpc-gateway.
