### ISSUE TITLE
Link to v2 migration guide broken

### ISSUE THREAD

**Issue by jrgirvan** [grpc-ecosystem/grpc-gateway#1836]
## 📚 Documentation

There are a few links to the Migration guide, notably on https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.0.0
But the link results in a 404

Broken Link
https://grpc-ecosystem.github.io/grpc-gateway/docs/v2-migration.html

Should point to
https://grpc-ecosystem.github.io/grpc-gateway/docs/development/v2-migration/

**Comment by johanbrandhorst** [comment]
Doh, thanks for the issue! This was caused by us reorganizing the links a bit. Will do a pass and clean up any missing references.

**Comment by vibhordubey333** [comment]
> ## 📚 Documentation
> There are a few links to the Migration guide, notably on https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.0.0
> But the link results in a 404
> 
> Broken Link
> https://grpc-ecosystem.github.io/grpc-gateway/docs/v2-migration.html
> 
> Should point to
> https://grpc-ecosystem.github.io/grpc-gateway/docs/development/v2-migration/

None of above link is working now. :-(

**Comment by johanbrandhorst** [comment]
The correct link is https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/, I will go around and update the release notes.
