### ISSUE TITLE
protobuf enumerated values now returned as strings instead of numbers.

### ISSUE THREAD

**Issue by rlmcpherson** [grpc-ecosystem/grpc-gateway#186]
Previously, at least on commit id b94f713a92a8e7d8e336586dc31753e52c02f025 (2016-2-18), enumerated values were returned in http responses as numbers. Now they are returned as the strings corresponding to those values. While this is better behavior, it is also a breaking change. Is there any way to disable this behavior while still updating to the latest version of the package? When was this change introduced? 

I suspect that this may have to do with the move to jsonpb by default but setting the ServeMux option to use the built-in Marshaler for json does not appear to have any effect. Is there a workaround for this issue?

**Comment by yugui** [comment]
You can use a custom instance of `JSONPb` marshaler and pass it as an option when you instantiate `Mux`.

```
m := &runtime.JSONPb{
  OrigName: true,
  EnumsAsInts: true,
}
mux := runtime.NewServeMux(runtime.WithMarshalerOption("application/json", m))
...
```

**Comment by achew22** [comment]
@rlmcpherson, I'm going to mark this issue as closed. If there is any more information you need, please feel free to reopen it.

@yugui, thank you for getting this one.
