### ISSUE TITLE
Poor error message when using message in path parameter

### ISSUE THREAD

**Issue by th-m** [grpc-ecosystem/grpc-gateway#1863]
## 📚 Documentation

`--grpc-gateway_out: aggregate type TYPE_MESSAGE in parameter of ScheduleAPI.BookAppointment: LocationID`

rpc looks like this 

```
 rpc BookAppointment(schedule.ScheduleRequest) returns (schedule.BookAppointmentResponse) {
    option (google.api.http) = {
      post: "/schedule/v2/{LocationID}/bookings/schedule-links"
    };
  }
```

```
import "protorepo/messages/shared/uuid.proto";

message ScheduleRequest {
  shared.UUID LocationID = 1;
  google.protobuf.Timestamp DateTime = 2;
  google.protobuf.Duration Duration = 3;
 ...
}
```

Given the example rpc and message I get the aforementioned error. I am unable to find any documentation on how to resolve this or what it means.

**Comment by johanbrandhorst** [comment]
I think the issue is the use of the type `shared.UUID` in a path parameter. I don't think we support this. The error message definitely needs improving, but I expect changing `LocationID` to string should fix your issue.

**Comment by gunadhya** [comment]
Hi @johanbrandhorst, I'm new to this project and I'd like to work on this issue. I think the error is framed on this line https://github.com/grpc-ecosystem/grpc-gateway/blob/26104fd424bf45f44d498149b071ef657d604f2b/internal/descriptor/services.go#L251

Could you help me figure out a better format?

**Comment by johanbrandhorst** [comment]
Hi @gunadhya, yes that seems like the place. I think for users that encounter this error we should make it clear that they can't use that protobuf type for a path parameter, and also maybe suggest a fix? How about
```go
fmt.Errorf("%s.%s: %s is a protobuf message type. Protobuf message types cannot be used as path parameters, use a scalar value type (such as string) instead". meth.Service.GetName(), meth.GetName(), path)
```
