### ISSUE TITLE
Load Balancing with multiple instances of a grpc-server.

### ISSUE THREAD

**Issue by vu-nhan** [grpc-ecosystem/grpc-gateway#1875]
Hi all,

I really sorry if I miss documents.

Currently I am deploy a grpc-gateway service and 1 grpc-server.
My grpc-gateway will route Http request to grpc-server.

Now I scale my grpc-server from 1 to 3 instances, how I config my grpc-gateway routes request to 3 instances?

Thank you so much.

**Comment by johanbrandhorst** [comment]
Hi! This will depend on how you've set up your gRPC-Gateway to connect to the gRPC server. If you're using DNS, you can do load balancing to the gRPC server between the gateway and gRPC server. If you're connecting on a local unix socket or localhost, you'll probably end up deploying 1 gateway for each gRPC server. There's no general answer here, and there's nothing specific to the gRPC-Gateway either, this is just networking. As such, this is probably not the best place to ask, and I'm going to close this issue. Please refer to our Slack channel if you need more help and we can maybe help point you to the right place to ask.
