### ISSUE TITLE
Move generator and descriptor packages into the public API

### ISSUE THREAD

**Issue by sesposito** [grpc-ecosystem/grpc-gateway#1877]
Could the generator and descriptor packages be moved into the public API again in a future release please?

I've relied on them to build a custom generator and would like to upgrade it to use the protobuf v2 libs, but I'm stuck because these packages have now been made internal.

**Comment by johanbrandhorst** [comment]
Hi Simon, thanks for your issue. I think you'd have to make an extremely good case for us to make these public again, as they were one of the major reasons we wanted to make a v2 release. I think if you want to upgrade your generator to v2 I would recommend rewriting it in the new protogen framework, from scratch: https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/compiler/protogen. If you must, we have a permissive license and as long as you include the original license you can copy the parts you want from our code.
