### ISSUE TITLE
jsonPB is not supporting in grpc gateway v2 migration

### ISSUE THREAD

**Issue by likhita809** [grpc-ecosystem/grpc-gateway#1878]
## 🐛 Bug Report

While migrating to grpc gateway v2 in cosmos sdk, I found that v2 is not supporting JSONPb

## Expected behavior

Migration to grpc gateway v2

## Actual Behavior

JSONPb is not supporting

**Comment by johanbrandhorst** [comment]
Hi @likhita809. The Go protobuf APIv2 has a new JSON marshaller package that you need to use. You can find it here: https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/encoding/protojson. If this is unclear in our documentation, I'd be happy to review a submission that makes this clear.
