### ISSUE TITLE
Data is Getting Encoded while returning response  as HTML

### ISSUE THREAD

**Issue by vijay8059** [grpc-ecosystem/grpc-gateway#1880]
## 🐛 Bug Report

While Returning the response as content-type : application/html data is getting encoded

## To Reproduce
Set the headers 
header := metadata.Pairs("X-Content-Type", "application/html")
	grpc.SetHeader(ctx, header)
Steps : 
  rpc Create (RegId) returns (Resp);
message RegId {
  string id = 1;
}

message Resp {
  string response = 1;
}
Above is my proto definition, in the response i am sending the `<html><b> Hey Developer </b></html>` but it's retuning response as. {"response":"\u003chtml\u003e\u003cb\u003e Hey Developer \u003c/b\u003e\u003c/html\u003e"}

## Expected behavior

{"response":"<html><b> Hey Developer </b></html>"}

And also is there is a way to return just the value as response instead of key value pair, something like this "<html><b> Hey Developer </b></html>"

**Comment by johanbrandhorst** [comment]
Looks like what you're looking for is the HTTPBody marshaler behaviour :). This is automatically enabled if you use the `google.api.HttpBody` type. See our documentation for an example: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/httpbody_messages/
