### ISSUE TITLE
How To return text/html from grpc gateway to browser

### ISSUE THREAD

**Issue by vijay8059** [grpc-ecosystem/grpc-gateway#1881]
## 🚀 Feature

header := metadata.Pairs("X-Content-Type", "application/html")
grpc.SetHeader(ctx, header)
Steps :
rpc Create (RegId) returns(google.api.HttpBody);
message RegId {
string id = 1;
}

Above is my proto definition, in the response i am sending the <html><b> Hey Developer </b></html> but it's retuning response as.{
    "content_type": "text/html",
    "data": "PGh0bWw+PGI+IEhleSBWaWpheSA8L2I+PC9odG1sPg==",
    "extensions": []
}

**Comment by johanbrandhorst** [comment]
This should be working as you describe on v2, what version of the gateway are you using?

**Comment by vijay8059** [comment]
> This should be working as you describe on v2, what version of the gateway are you using?

@johanbrandhorst i am using v1.16.0of grpc-gateway

**Comment by johanbrandhorst** [comment]
If you're using v1.16 you need to explicitly configure the `HTTPBodyMarshaler` as your marshaler of choice when creating the runtime. See `runtime.SetHTTPBodyMarshaler`.

**Comment by vijay8059** [comment]
@johanbrandhorst any sample code where i can refer this?
