### ISSUE TITLE
Ignore some fields in HTTP Response and OpenAPI

### ISSUE THREAD

**Issue by AntoineToussaint** [grpc-ecosystem/grpc-gateway#1886]
## 🚀 Feature

There may be a way to do that already but couldn't find documentation.

The goal would be to ignore fields (that are used only internally or not ready yet to be shown to customer of the REST API.

**Comment by AntoineToussaint** [comment]
Note that I tried with [json_name="-"] which could be one way to define it but it doesn't work.

**Comment by johanbrandhorst** [comment]
I can't think of an appropriate way for us to signal that a field should be ignored - we don't have any custom annotations for the grpc-gateway logic, and we're not going to introduce it for this feature. I would recommend wrapping your internal service with a separate grpc server that implements the interface you want to expose to customers.
