### ISSUE TITLE
README.md links to https://pkg.go.dev/github.com/golang/protobuf/jsonpb which does not exist

### ISSUE THREAD

**Issue by bjanders** [grpc-ecosystem/grpc-gateway#1901]
## 📚 Documentation

In README.md section "Mapping gRPC to HTTP" the text "While configurable, the default {un,}marshaling uses jsonpb with OrigName: true" links to https://pkg.go.dev/github.com/golang/protobuf/jsonpb. Clicking this link gives "404 not found".

**Comment by bjanders** [comment]
It's possible that this is actually a bug with jsonpb. It's available at https://godoc.org/github.com/golang/protobuf/jsonpb, and should probably be available at the link mentioned in README.md, but isn't.

**Comment by johanbrandhorst** [comment]
We should update this documentation to point to protojson, the new marshaler in v2.
