### ISSUE TITLE
Custom incoming header matcher isn't working as expected

### ISSUE THREAD

**Issue by shuz** [grpc-ecosystem/grpc-gateway#1902]
## 🐛 Bug Report

I'm trying to upgrade my project from grpc-gateway 1.x to grpc-gateway 2.1. We have a custom HeaderMatcher that forwards all HTTP headers, but it stopped working in grpc-gateway 2.1.

## To Reproduce

We created a custom header matcher, and registered it as an incoming header matcher:

```
func HeaderMatcher(key string) (string, bool) {
	k, ok := runtime.DefaultHeaderMatcher(key)
	if ok {
		return k, ok
	}
	key = textproto.CanonicalMIMEHeaderKey(key)
	return "Forwarded-header-" + key, true
}

...
	gwmuxOpts := []runtime.ServeMuxOption{
		runtime.WithIncomingHeaderMatcher(HeaderMatcher),
```

Then I register the service using the HandlerFromEndpoint function:

```
func (s *Service) Register(ctx context.Context, mux *runtime.ServeMux, addr string, opts []grpc.DialOption) error {
	return xxxpb.RegisterXXXServiceHandlerFromEndpoint(ctx, mux, addr, opts)
}
```

The incoming MD doesn't contain the header that is mapped. After debugging, I find the generated code is different in XXX_HandlerClient and XXX_Handler_Server. The ServiceHandlerClient is called, but `AnnotateIncomingContext` function is never called.

In XXX_HandlerClient, it says:
```
func RegisterXXXServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client XXXServiceClient) error {
	mux.Handle("GET", pattern_XXXService_Func_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		...
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/xxx")
		...
```
In XXX_HandlerServer, it says:
```
func RegisterXXXServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server XXXServiceServer) error {

	mux.Handle("GET", pattern_XXXService_Func_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		...
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/xxx")
```

## Expected behavior

The following code should allow us to access the incoming headers:
```
		m, ok := metadata.FromIncomingContext(ctx)
		if !ok {
			...
		}
		customHeader := m.Get("Forwarded-header-customheader")
```

## Actual Behavior

The header is not available from metadata of IncomingContext. 

## Your Environment

OS: macos
Version: grpc-gateway 2.1

**Comment by shuz** [comment]
I find a work around, the header matcher only works if I map the headers to begin with `runtime.MetadataHeaderPrefix`:
```
func HeaderMatcher(key string) (string, bool) {
	k, ok := runtime.DefaultHeaderMatcher(key)
	if ok {
		return k, ok
	}
	key = textproto.CanonicalMIMEHeaderKey(key)
	return runtime.MetadataHeaderPrefix + "fwd-" + key, true
}
```

**Comment by johanbrandhorst** [comment]
Hm, I'm not sure if this is a bug or not, but if it was a change in behaviour between v1 and v2 I apologize, I don't think that was intentional. I don't think we changed any of this code so I'm not sure why it should've changed, but I don't think we can change it back now, so perhaps the best solution is to document this behaviour better? Would you be willing to contribute something to our docs? Looks like we have something already, is this still working? https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#mapping-from-http-request-headers-to-grpc-client-metadata.

**Comment by shuz** [comment]
No, per my testing, it's no longer working unless the mapped header starts with `runtime.MetadataHeaderPrefix`. 

Maybe you need to document this behavior. We are adapting this workaround to upgrade to v2.1.

```
func CustomMatcher(key string) (string, bool) {
	switch key {
	case "X-Custom-Header2":
		return "custom-header2", true
	default:
		return key, false
	}
}

...

		m, ok := metadata.FromIncomingContext(ctx)
		if !ok {
			...
		}
		customHeader := m.Get("custom-header2")  // it's empty.
```

Our work around is:

```
func CustomMatcher(key string) (string, bool) {
	switch key {
	case "X-Custom-Header2":
		return "Grpc-Metadata-custom-header2", true
	default:
		return key, false
	}
}

...

		m, ok := metadata.FromIncomingContext(ctx)
		if !ok {
			...
		}
		customHeader := m.Get("Grpc-Metadata-custom-header2")  // it's empty.
```

**Comment by shuz** [comment]
Nevermind, I tries to further dig into it and nothing seems wrong. I then changed the code back to the original prefix and surprisingly it still works. I must be messing something up when I get hit by this error. Sorry for confusing.

I'll close this ticket.
