### ISSUE TITLE
F

### ISSUE THREAD

**Issue by fylo5** [grpc-ecosystem/grpc-gateway#1917]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

(Environment name, version and operating system.)

**Comment by johanbrandhorst** [comment]
🤔
