### ISSUE TITLE
Patch request with field_masks

### ISSUE THREAD

**Issue by renyijiu** [grpc-ecosystem/grpc-gateway#1930]
## 📚 Documentation

I have an api defined as follows:
```
  rpc UpdateMission(UpdateMissionRequest)
      returns (Mission) {
    option (google.api.http) = {
      patch: "/v1alpha2/{mission.name=missions/*}"
      body: "*"
    };
  }

message UpdateMissionRequest {
  Mission mission = 1;
  google.protobuf.FieldMask update_mask = 2;
}
```

according to the [https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature), if i send a request with body as follows:
```
{
    "mission": {
        "name": "missions/5ceebd25-b73f-40fb-8597-e36657e24275",
        "driver": {
            "email": "hello"
        }
    },
    "update_mask": "driver"
}

```
it works fine and updates record success. But if i use update_mask with `paths` then will get error
```
{
    "mission": {
        "name": "missions/5ceebd25-b73f-40fb-8597-e36657e24275",
        "driver": {
            "email": "hello"
        }
    },
    "update_mask": {
        "paths": [
            "driver"
        ]
    }
}
```

#### response
```
{
    "code": 3,
    "message": "proto: syntax error (line 8:20): unexpected token {"
}
```

So i want to know v2 no longer support the `paths`  grammar or i miss something ? thanks.

**Comment by johanbrandhorst** [comment]
That looks like a generic JSON marshalling error, which will be down to how your configured marshaler (by default, `runtime.JSONPb`) unmarshals that message. I expect it probably has a special case for handling how the well known field mask type should be unmarshalled from JSON. In any case, it's not something that the grpc-gateway can control, you'll have to reach out to the maintainers of https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson if you want to know more, which is at https://github.com/golang/protobuf/issues.
