### ISSUE TITLE
google/api/annotations.proto: File not found.

### ISSUE THREAD

**Issue by gautam-shipt** [grpc-ecosystem/grpc-gateway#1935]
I am trying to build a GRPC service with reverse proxy this worked fine before till i updated to the version 2 
im using this command to generate the code 
I did the following 
go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc
then tried to generate the stub with 
protoc -I proto/ -I /usr/local/include -I ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api proto/*.proto --go_out=plugins=grpc:.

i get the error 
/Users/gautamdey/golang-project/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api: warning: directory does not exist.
google/api/annotations.proto: File not found.
healthcheck.proto:4:1: Import "google/api/annotations.proto" was not found or had errors.

one interesting i noticed that the src/github.com folder do not contain the grpc-ecosystem instead i see the folder in pkg ... 
i tried to point that to pkg as well still it failed with same error

**Comment by achew22** [comment]
Have you tried generating the stubs using [buf](https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/generating_stubs/using_buf/)? Maybe that would be easier?

**Comment by gautam-shipt** [comment]
I tried to copy the grpc-ecosystem along with the the protos in the src folder as mention above and it resolved the error i was getting .. However I got blocked again with this error 
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC
I used the command 
protoc -I proto/ -I ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis proto/*.proto --go_out=plugins=grpc:.
Unfortunately there is not much of documentation around this so digging through different issues and stackoverflow i found this link which 
https://stackoverflow.com/questions/60578892/protoc-gen-go-grpc-program-not-found-or-is-not-executable
I updated the modules using 
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
go install google.golang.org/protobuf/cmd/protoc-gen-go
and updated the command to 
protoc -I proto/ -I ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis proto/*.proto ----go-grpc_out=${GOPATH}/src/github.com/shipt/infra-tool-auth
im still getting this error 
protoc-gen---go-grpc: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
----go-grpc_out: protoc-gen---go-grpc: Plugin failed with status code 1.

**Comment by johanbrandhorst** [comment]
Hi @gautam-shipt, have you tried our new tutorial? https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/introduction/. The issue with your latest post is that you're using too many dashes. You need `--go-grpc_out`. But this sort of thing is a bit easier with the buf generator (full disclosure: I work at Buf). Please try the tutorial and let us know if that helps.

**Comment by protango** [comment]
If you are using Buf, then you need to add these lines to your buf.yaml file, directly underneath the `version` tag:

```
name: buf.build/yourorg/myprotos
deps:
  - buf.build/beta/googleapis
```

Additionally, you must always run `buf beta mod update` after adding a dependency to your buf.yaml.

**Comment by jsonbruce** [comment]
The `grpc-gateway v2.3.0` has removed the `third_party` folder, see [v2.3.0 Release Note](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.3.0).

Below are some solutions works for me:

- **Solution 1:** Switch to `buf` from `protoc`

- **Solution 2:** Use an older version.  `grpc-gateway <= v2.2.0` in your go.mod

- **Solution 3:** Copy `google/api/annotations.proto` and `google/api/http.proto` to your project. Checkout previous version [v2.2.0](https://github.com/grpc-ecosystem/grpc-gateway/tree/v2.2.0/third_party/googleapis/google/api) you can get these files

**Comment by RhickMercado** [comment]
I try this:
	protoc -I$GOPATH/src/github.com/golang/protobuf/ptypes/timestamp \
	 -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	 --proto_path=proto proto/*.proto --go_out=plugins=grpc:pb

**Comment by johanbrandhorst** [comment]
I think we have enough workarounds in here now that we can close this issue. Don't hesitate to write if you're still running into issues!
