### ISSUE TITLE
Non official implementation

### ISSUE THREAD

**Issue by rodoufu** [grpc-ecosystem/grpc-gateway#1940]
## 📚 Documentation

Do you have a wiki page for non-official implementations in other languages? Such as:
- https://www.npmjs.com/package/rest2grpc

That's a Typescript / Javascript implementation.

**Comment by johanbrandhorst** [comment]
Hi @rodoufu, we don't have anything like that in the documentation at the moment, but we could add something like "related projects" to the docs if you think it'd be helpful to users. I'd be happy to review such a PR 😄.

**Comment by rodoufu** [comment]
> Hi @rodoufu, we don't have anything like that in the documentation at the moment, but we could add something like "related projects" to the docs if you think it'd be helpful to users. I'd be happy to review such a PR .

https://github.com/grpc-ecosystem/grpc-gateway/pull/1943
