### ISSUE TITLE
can we add HTTPStatusFromCode to mux?

### ISSUE THREAD

**Issue by elvizlai** [grpc-ecosystem/grpc-gateway#1954]
## 🚀 Feature

We use status.New(1001, "xxxx") for grpc service response.

What we want is when code between [1000,9999] should be http status 400 and keep body `{"code":1001, "message":"lol, bad user name"}`

1. The HTTPStatusFromCode convert code larger than _maxCode = 17 to http status 500, which is not we want. Because 500 looks like not a logical error status.

2. But WithErrorHandler is missing exportable method handleForwardResponseServerMetadata or mux.outgoingHeaderMatcher.

Any suggestion about this feature?

**Comment by johanbrandhorst** [comment]
Hi @elvizlai, thanks for your issue. This is a very strange use case, and not one we're likely to add new features around. In the past I've recommended users copy the logic of `handleForwardResponseServerMetadata` into their error handlers if they require this, would this work for you? We're trying to avoid adding more to the public API right now.

**Comment by elvizlai** [comment]
> Hi @elvizlai, thanks for your issue. This is a very strange use case, and not one we're likely to add new features around. In the past I've recommended users copy the logic of `handleForwardResponseServerMetadata` into their error handlers if they require this, would this work for you? We're trying to avoid adding more to the public API right now.

I'm now using lua to rewrite response status.
