### ISSUE TITLE
Gateway protoc does not generate protoreflect.ProtoMessage messages

### ISSUE THREAD

**Issue by ivanjaros** [grpc-ecosystem/grpc-gateway#1959]
My entire system blew up. I had to update gw because suddenly it was generating methods with wrong number of arguments and now I am getting Foo does not implement protoreflect.ProtoMessage (missing ProtoReflect method) errors. What do i need to update or how?

**Comment by charlie-paxos** [comment]
Also seeing this issue. Seems like latest (v2.2.0) has a regression, or is there something we need to do on our end to get past this?

**Comment by charlie-paxos** [comment]
Try this: `go get -u github.com/golang/protobuf/protoc-gen-go`

**Comment by ivanjaros** [comment]
yeah, seems like that was it. thanks.

**Comment by ivucica** [comment]
Note that GitHub issues are not a support forum.
