### ISSUE TITLE
Build fails with error: use of internal package not allowed

### ISSUE THREAD

**Issue by vyshane** [grpc-ecosystem/grpc-gateway#197]
I'm getting the following error when I try to build the gateway:

```
package my-grpc-gateway
        imports github.com/gengo/grpc-gateway/runtime
        imports github.com/grpc-ecosystem/grpc-gateway/runtime/internal: use of internal package not allowed
```

**Comment by yugui** [comment]
grpc-gateway has moved to `github.com/grpc-ecosystem/grpc-ecosystem`.
Could you regenerate your gateway `my-grpc-gateway` with the latest revision of `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway`?

**Comment by vyshane** [comment]
Thanks, switching to `github.com/grpc-ecosystem/grpc-gateway` fixed it.
