### ISSUE TITLE
Grpc healthcheck docs are unclear 

### ISSUE THREAD

**Issue by Pryanishnik** [grpc-ecosystem/grpc-gateway#1977]
https://grpc-ecosystem.github.io/grpc-gateway/docs/operations/health_check/

From this doc I can not understand where I have to put imports and register service.
Also, I don't understand if I have to make separate healthcheck service.
Why we can not use DefaultHealthCheck? 
It probab;y make sense to make "transparent" call of default healthcheck from outer REST. I.E. Amazon Load Balancer uses it for determining instance state.
Or if we can, please clarify how to enable it

**Comment by johanbrandhorst** [comment]
Hi @Pryanishnik, thanks for your issue. The docs are talking about implementing the gRPC health check protocol, which may not be what you want. If you want to simply add a `/health` handler to your Go service, you can do that using a normal `http.ServeMux` where you add a handler explicitly and pass in our `runtime.ServeMux` separately. For example:


```go
gwmux := runtime.NewServeMux()
err := gw.RegisterYourServiceHandlerFromEndpoint(ctx, gwmux,  *grpcServerEndpoint, opts)
if err != nil {
    log.Fatalln("failed to register gateway:", err)
}
mux := http.NewServeMux()
mux.Handle("/", gwmux)
mux.Handle("/health", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)
})
http.ListenAndServe(":3000", mux)
```

Does that make sense?

**Comment by Pryanishnik** [comment]
Thank you for reply @johanbrandhorst. Not exactly.  I want to use gRPC healthcheck protocol. ACtually, how I do it now using 
https://github.com/salrashid123/grpc_health_proxy.
![image](https://user-images.githubusercontent.com/43049295/108343140-43dd7080-71e4-11eb-9a7f-249367709b58.png)

In this case, architecture becomes pretty complicated. I want to remove this health proxy and is wondering if I can get health proxy functionality in gRPC gateway?

**Comment by johanbrandhorst** [comment]
The grpc-gateway doesn't have any built in functionality to translate this. You could take the existing grpc health check protofile and generate some REST annotations for it using the `generate_unbound_methods` option and then serve that. It may not give you the signature that you want though, in which case you either have to define your own proto service wrapper or just use a custom handler as I suggested in my first reply. Does that make sense?

**Comment by Pryanishnik** [comment]
Yes, it clarifies a bit, thank you! But for future it makes sense to implement this translation. I.E. AWS Load Balancer will not work with server for autosacling, coz it needs healthchecks. If we use REST we can not do default grpc healthchecks, and in this case we have to implement own workaround for REST healthchecks. But anyway, thank you!

**Comment by johanbrandhorst** [comment]
If you'd like to contribute something to the docs I'd be very grateful. I agree that the health checks section is pretty poor. I've never implemented it myself though so I don't know what to put.
