### ISSUE TITLE
../proto/api/proto/service.pb.gw.go:129:95: cannot use *StringMessage value as type protoreflect.ProtoMessage in return argument: 	*StringMessage does not implement protoreflect.ProtoMessage (missing ProtoReflect method)

### ISSUE THREAD

**Issue by xx132917** [grpc-ecosystem/grpc-gateway#1989]
../proto/api/proto/service.pb.gw.go:129:95: cannot use *StringMessage value as type protoreflect.ProtoMessage in return argument:
	*StringMessage does not implement protoreflect.ProtoMessage (missing ProtoReflect method)

**Comment by johanbrandhorst** [comment]
This happens if you're using the old Go protobuf generator with v2 of the grpc-gateway. If you want to keep using the old generator, you need to use v1 of the grpc-gateway. If you want to use v2, please follow the installation instructions in the README.

**Comment by garystafford** [comment]
I've seen this error dismissed twice for using the old protobuf generator. I have carefully followed the instructions in the latest README as of 2021-06-28, even removing and reinstalling packages several times. I am confident I am using the latest packages, however cannot seem to avoid this error either. Any thoughts?

protoc --version
libprotoc 3.17.3

buf --version
0.43.2

go list -m all
google.golang.org/grpc v1.38.0
google.golang.org/protobuf v1.25.0

`../../../../../go/pkg/mod/github.com/garystafford/protobuf@v0.0.0-20210628012658-a5a7cd0949b2/greeting/v2/greeting.pb.gw.go:39:2: cannot use msg (type *GreetingResponse) as type protoreflect.ProtoMessage in return argument:
	*GreetingResponse does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
../../../../../go/pkg/mod/github.com/garystafford/protobuf@v0.0.0-20210628012658-a5a7cd0949b2/greeting/v2/greeting.pb.gw.go:48:2: cannot use msg (type *GreetingResponse) as type protoreflect.ProtoMessage in return argument:
	*GreetingResponse does not implement protoreflect.ProtoMessage (missing ProtoReflect method)`
