### ISSUE TITLE
Get http path defined in proto

### ISSUE THREAD

**Issue by lemonlinger** [grpc-ecosystem/grpc-gateway#2005]
## 🚀 Feature

We'd like to take the mapping http path defined in proto as the label value of request metrics. E.g. proto below:
```
	rpc GetMessageWithBody(MessageWithBody) returns (google.protobuf.Empty) {
		option (google.api.http) = {
			post: "/v2/example/withbody/{id}",
			body: "data"
		};
	}
```
We need `/v2/example/withbody/{id}` as the label value of request metrics.

Can we put the mapping http path into context or http headers ?

**Comment by lemonlinger** [comment]
I see rpc method has been injected into the incoming context. Is it possible to add the mapping HTTP path too ?

**Comment by johanbrandhorst** [comment]
We don't currently have any way to do this. It may be possible to write a HTTP middleware handler that can extract the ID from the request path for each specific path.

If you'd like to help build something more general purpose we could discuss it too. This question comes up every now and then.

**Comment by lemonlinger** [comment]
Here's a possible solution. First, implement a method for `Pattern` like `func Path() string` which could construct the mapping HTTP path. And then we could use a similar way of RPC method injection to handle the mapping HTTP path. 
Below code shows how to inject RPC method into incoming context.
```
     mux.Handle("GET", pattern_Greeter_SayHello_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
         ctx, cancel := context.WithCancel(req.Context())
         defer cancel()
         inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
         rctx, err := runtime.AnnotateContext(ctx, mux, req, "/grpc.gateway.examples.internal.helloworld.Greeter/SayHello")
         if err != nil {
             runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
             return
         }
         resp, md, err := request_Greeter_SayHello_0(rctx, inboundMarshaler, client, req, pathParams)
         ctx = runtime.NewServerMetadataContext(ctx, md)
         if err != nil {
             runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
             return
         }

         forward_Greeter_SayHello_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

     })
```
We change it slightly to support HTTP path injection.
```
rctx, err := runtime.AnnotateContext(ctx, mux, req, pattern_Greeter_SayHello_0.Path(), "/grpc.gateway.examples.internal.helloworld.Greeter/SayHello")
```
@johanbrandhorst

**Comment by johanbrandhorst** [comment]
Yeah, I like this, we can easily add it to the context without breaking backwards compatibility. Would you like to prototype this change?

**Comment by lemonlinger** [comment]
Yes,  will do.  Thanks for your quick response.

**Comment by lemonlinger** [comment]
Ops...Does it break backwards compatibility to change 
`func AnnotateIncomingContext(ctx context.Context, mux *ServeMux, req *http.Request, rpcMethodName string)` 
to 
`func AnnotateIncomingContext(ctx context.Context, mux *ServeMux, req *http.Request, httpPath, rpcMethodName string)`?

**Comment by lemonlinger** [comment]
In this solution, both `protoc-gen-grpc-gateway` and `grpc-gateway` have to be modified. If a user upgrades `grpc-gateway` but with go files generated by an older `protoc-gen-grpc-gateway`，it will cause compiling failure.

**Comment by johanbrandhorst** [comment]
> In this solution, both `protoc-gen-grpc-gateway` and `grpc-gateway` have to be modified. If a user upgrades `grpc-gateway` but with go files generated by an older `protoc-gen-grpc-gateway`，it will cause compiling failure.

Yes, good point, we can't do that. We'd need another function or some way to infer the information from the already provided parameters.

**Comment by krosen040** [comment]
+1 to this, we would also like to be able to access the matched route in a middleware somehow. Our use case is about distributed tracing, and setting the path as the span operation name.

**Comment by kirinse** [comment]
I think we can use runtime.WithMetadata(annotator) to inject http.Request.RequestURI

**Comment by krosen040** [comment]
That wouldn't give us the path pattern. It's easy to get a path like `/users/12345`, but we need the matched route, like `/users/{id}`.

**Comment by lemonlinger** [comment]
I'm still working on it and will make a pr in a couple of days.
