### ISSUE TITLE
v2.3.0: protobuf branch reference in go.mod; third-party gone

### ISSUE THREAD

**Issue by nashikb** [grpc-ecosystem/grpc-gateway#2007]
## 🐛 Bug Report

The protobuf reference in go.mod is a branch reference, which isn't ideal, but also breaks dependencies in Go 1.16.

The third-party directory is missing. I couldn't find documentation of this change, and it's pretty likely a breaker for most people.

## To Reproduce

Try to use it like v2.2. :-)

## Expected behavior

* protobuf in go.mod references a proper version tag
* third-party directory is restored, or an alternative well-documented

## Actual Behavior

N/A

## Your Environment

N/A

**Comment by johanbrandhorst** [comment]
We've updated the installation instructions since removing the third_party directory: https://github.com/grpc-ecosystem/grpc-gateway#usage.

**Comment by nashikb** [comment]
I can understand the decision behind third-party being removed, but I didn't see any mention of this on the surface of the release notes. If I missed it, my apologies. The visibility is important IMHO because introducing a separate build flow for third-party (well-known-types) will require project retooling before 2.3.0 uptake.

The buf link in the directions is broken (404). I see "if you are using buf" in the docs—is the official approach to use buf, or are there others?

Thx!

**Comment by johanbrandhorst** [comment]
You're right we should've mentioned it in the release notes, that was an oversight. You're also right that one of the links in the README is wrong, I'll sort that out. Here's a working link in the meantime: https://github.com/bufbuild/buf.

We support both `buf` and `protoc`. If you're using `protoc` you'll need to provide the third party dependencies, the usage instructions includes how to do this, though it skims over some details that make `protoc` annoying to use. I would recommend using `buf`, but I work for Buf, so take that with a grain of salt 😄.

**Comment by johanbrandhorst** [comment]
I've updated the README and the release notes. Do you think we need to add anything else?

**Comment by nashikb** [comment]
Nope, all makes sense. Thanks!
