### ISSUE TITLE
Update install section of docs to match new directory structure

### ISSUE THREAD

**Issue by absecure** [grpc-ecosystem/grpc-gateway#2013]
I believe the README.md needs to be updated (at least in one spot) with new directory structure. The installation section:

```
// +build tools

package tools

import (
    _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"
    _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2"
    _ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
    _ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
...
$ go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc

```

Is incorrect, as it references v2/ (which doesn't exist). It should be:

```
// +build tools

package tools

import (
    _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
    _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2"
    _ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
    _ "google.golang.org/protobuf/cmd/protoc-gen-go"
)

$ go install \
    github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2 \
    google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc
```

**Comment by absecure** [comment]
I think this is the same issue as https://github.com/grpc-ecosystem/grpc-gateway/pull/1997, closing

**Comment by johanbrandhorst** [comment]
Hi @absecure, since #1997 is stuck waiting on the original contributor, I'd be happy to review your own contribution to help fix this issue.

**Comment by johanbrandhorst** [comment]
Also, uh, I don't think this is right. We do need to include the `v2`, it's the name of the module.

**Comment by absecure** [comment]
Basically, I am getting the same issue as https://github.com/grpc-ecosystem/grpc-gateway/issues/1992 
Dropping the v2 means that go get/go install succeeds, but this isn't right. Without a properly set up Go environment, the documented commands are failing. However, I'm not sure if setting up your Go environment correctly is within the scope of the docs.

I never was able to figure out how to install the gateway.

**Comment by johanbrandhorst** [comment]
I'm really confused, what version of Go is it not working with? Is this new behaviour in 1.16?

**Comment by xansec** [comment]
Here's my environment info:

`$ go version
go version go1.15.8 linux/amd64
$ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
cannot find package "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" in any of:
	/usr/lib/go/src/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway (from $GOROOT)
	/home/user/go/src/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway (from $GOPATH)
cannot find package "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2" in any of:
	/usr/lib/go/src/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 (from $GOROOT)
	/home/user/go/src/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 (from $GOPATH)
$ go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2
$ echo $?
0
`

**Comment by johanbrandhorst** [comment]
`go install` will only work if you have a `tools.go`, which is the first step in the installation instructions, is that in place?

**Comment by johanbrandhorst** [comment]
If you don't want to use `tools.go` you can use `go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway`

**Comment by xansec** [comment]
Go get fails as well:

```
$ go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
cannot find package "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" in any of:
	/usr/lib/go/src/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway (from $GOROOT)
	/home/user/go/src/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway (from $GOPATH)
```

Running go get with the tools.go:

```
go:generate go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc

package tools

import (
    _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"
    _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2"
    _ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
    _ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
```

is successful. 
```
$ go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
go: found github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway in github.com/grpc-ecosystem/grpc-gateway/v2 v2.3.0
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
```

I think it's fair closing and pointing to the other issues, as I think they capture all of the information.
