### ISSUE TITLE
Documentation on support grpc+grpc gateway on the same port

### ISSUE THREAD

**Issue by amit-chandak-unskript** [grpc-ecosystem/grpc-gateway#2020]
## 📚 Documentation

Is there a documentation on how to run grpc+grpc gateway on the same port? I saw [this](https://github.com/philips/grpc-gateway-example/blob/master/cmd/serve.go), however it didnt work for me. I am thinking mostly because i didnt enable TLS. Wanted to know if TLS is a requirement?

**Comment by iamrajiv** [comment]
@amit-chandak-unskript You can serve gRPC and the gRPC-Gateway on the same port using something like cmux to multiplex at the listener level but I think you still have to manage TLS at the layer above gRPC. This might help https://github.com/johanbrandhorst/grpc-postgres/blob/5fafe0383f990269a0d569c4313281acd154e6f7/main.go.

**Comment by iamrajiv** [comment]
@amit-chandak-unskript You can serve gRPC and the gRPC-Gateway on the same port using cmux but I think you still have to manage TLS at the layer above gRPC. This might help https://github.com/johanbrandhorst/grpc-postgres/blob/5fafe0383f990269a0d569c4313281acd154e6f7/main.go.

**Comment by amit-chandak-unskript** [comment]
Thanks @iamrajiv for the quick response, in my microservice, i dont want to turn on TLS, was wondering if TLS is a MUST to support this? As i saw [this](https://golang.org/pkg/net/http/#Server.Serve) comment in http documentation, specifically 
```
HTTP/2 support is only enabled if the Listener returns *tls.Conn connections and they were configured with "h2" in the TLS Config.NextProtos.

```

**Comment by amit-chandak-unskript** [comment]
Found the way to get this working [here](https://github.com/philips/grpc-gateway-example/issues/22#issuecomment-490733965)
