### ISSUE TITLE
"use of internal package" error, after moving to grpc-ecosystem

### ISSUE THREAD

**Issue by igateno** [grpc-ecosystem/grpc-gateway#203]
Last week we moved our references from `gengo/grpc-gateway` to `grpc-ecosystem/grpc-gateway`. It was working great, and today I got this error again.

```
isaac@Isaacs-MacBook-Pro-2
± % go get ./...
package github.com/goforward/api/auth/auth
        imports github.com/grpc-ecosystem/grpc-gateway/runtime
        imports github.com/grpc-ecosystem/grpc-gateway/runtime/internal: use of internal package not allowed

isaac@Isaacs-MacBook-Pro-2
± % git --no-pager grep gengo

isaac@Isaacs-MacBook-Pro-2
± %
```

As you can see from the `git grep` call, the string `gengo` no longer appears in our repo. Any help would be greatly appreciated. Thanks!

**Comment by ehernandez-xk** [comment]
@igateno  did you resolve it?
Try to re-generate the stub with the new url, probably you have the old url in the .pb.go and pb.gw.go files.

**Comment by igateno** [comment]
This issue kept showing up when I was trying to generate the stub. It only went away after I did an `rm -rf $GOPATH/*` and cloned my repo fresh. 

As I was debugging, I noticed that the proto package is still `gengo.grpc.gateway`. Is there a reason it wasn't changed to `grpc-ecosystem.grpc.gateway`? Could this be causing issues?

**Comment by yugui** [comment]
@igateno Something is wrong because there are no active reference to "gengo.grpc.gateway" in the source of grpc-gateway.

**Comment by achew22** [comment]
@igateno If you're still experiencing this, please reopen it or file a new issue with more information but I'm going to close it for now.
