### ISSUE TITLE
How to set a header on http transcoded zip content response?

### ISSUE THREAD

**Issue by ghevge** [grpc-ecosystem/grpc-gateway#2034]
## 🐛 Bug Report

I have a download zip file grpc service and I'm using envoy to transcode to http. The proto file service definition looks something like this:

  ```
 // Download build
  //
  // Download build
  rpc DownloadBuild(DownloadBuildRequest) returns (stream DownloadResponse) {
    option (google.api.http) = {
      get : "/v4/projects/{projectId}/types/{buildType}/builds/{buildVersion}/.download"
      headers: {}
    };
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
      description: "Download build.";
      summary: "Download build.";
      tags: "Builds";
      produces: "application/zip";
      responses: {
        key: "200"
        headers: []
        value: {
          description: "Download build";
        }
      }
      responses: {
        key: "401"
        value: {
          description: "Request could not be authorized";
        }
      }
      responses: {
        key: "404"
        value: {
          description: "Build not found";
        }
      }
      responses: {
        key: "500"
        value: {
          description: "Internal server error";
        }
      }
    };
  }

```

 I've tried to define a content type header at the http API response level, but not luck so far.

I keep getting errors like below when I try to compile my proto file with the headers field in it, no matter where I put that field. 

`Error while parsing option value for "http": Message type "google.api.HttpRule" has no field named "headers".`

Looking at the [openapiv2 proto definition](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/options/openapiv2.proto) , headers seems to be supported.

Any idea how I can set the application/zip header at a http transcoded API level?

Thanks

**Comment by johanbrandhorst** [comment]
Hi, if you're using envoy to do the HTTP transcoding there's nothing we can do to help, envoy doesn't use the grpc-gateway for the transcoding.
