### ISSUE TITLE
oneof parameter in path generated code missing package

### ISSUE THREAD

**Issue by elvizlai** [grpc-ecosystem/grpc-gateway#2042]
## To Reproduce

```
package api.svc;

option go_package = "api/svc";

  rpc GetTrieNode(api.infra.GetTrieNodeReq) returns (api.infra.KVNode) {
    option (google.api.http) = {
      post: "/trie/node:get"
      body: "*"
      additional_bindings {
        get: "/trie/node/{id}"
      }
      additional_bindings {
        get: "/trie/node/path/{path}"
      }
    };
  }
```

```
package api.infra;

option go_package = "api/infra";

message GetTrieNodeReq {
  oneof x {
    string id   = 1;
    string path = 2;
  }
}
```

## Expected behavior
`*GetTrieNodeReq_Id` should has pkg prefix `*infra.GetTrieNodeReq_Id`

## Actual Behavior

```
	if protoReq.X == nil {
		protoReq.X = &GetTrieNodeReq_Id{}
	} else if _, ok := protoReq.X.(*GetTrieNodeReq_Id); !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "expect type: *GetTrieNodeReq_Id, but: %t\n", protoReq.X)
	}
	protoReq.X.(*GetTrieNodeReq_Id).Id, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}
```

## Your Environment

```
./protoc-gen-grpc-gateway -version
Version 2.3.0, commit bcc34ef50bda81faae5d4bbfca2e7ea8fe4700c8, built at 2021-02-25T18:32:39Z
```

**Comment by elvizlai** [comment]
The key point maybe https://github.com/grpc-ecosystem/grpc-gateway/blob/9814f850088dcaaa6018446a366d8337f396aacb/internal/descriptor/types.go#L378-L380

**Comment by johanbrandhorst** [comment]
Hi Yongzheng, thanks for the bug report! This does indeed look like a bug, and we should try to fix it :). I see you've already done a bit of digging, the first step to submitting a fix would be to try and produce a failing test. I would try to look at the existing tests in https://github.com/grpc-ecosystem/grpc-gateway/blob/9814f850088dcaaa6018446a366d8337f396aacb/internal/descriptor/types_test.go and see if any can be copied and adapted to reproduce your bug, and then we can start iterating on a fix for it. How does that sound?

**Comment by xwjdsh** [comment]
I tried to fix this problem, follow the code, I found the package prefix is related to the `standalone` option. When I set `--grpc-gateway_opt standalone=true`, then everything is OK, generated code as below. I found this issue  https://github.com/grpc-ecosystem/grpc-gateway/issues/1931, It seems to be so designed, and setting the option standalone to true is the workaround of the case.
``` 
package svc

import (
	extInfra "api/infra"
...
)
...

	if protoReq.X == nil {
		protoReq.X = &extInfra.GetTrieNodeReq_Id{}
	} else if _, ok := protoReq.X.(*extInfra.GetTrieNodeReq_Id); !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "expect type: *extInfra.GetTrieNodeReq_Id, but: %t\n", protoReq.X)
	}
	protoReq.X.(*extInfra.GetTrieNodeReq_Id).Id, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

```

**Comment by johanbrandhorst** [comment]
Oh yes, that makes sense, thanks for reporting back!
