### ISSUE TITLE
error:protoc-gen-grpc-gateway: program not found or is not executable

### ISSUE THREAD

**Issue by killjason** [grpc-ecosystem/grpc-gateway#205]
got error when run the following cmd:
"protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --grpc-gateway_out=logtostderr=true:. ./helloworld.proto"
ERROR INFO:
"protoc-gen-grpc-gateway: program not found or is not executable
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1."

**Comment by achew22** [comment]
Can you confirm that `protoc-gen-grpc-gateway` is in a folder that is on your path?

What is the output of `which protoc-gen-grpc-gateway`?

```
protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --plugin=protoc-gen-grpc-gateway=$GOPATH/bin/protoc-gen-grpc-gateway  --grpc-gateway_out=logtostderr=true:. ./helloworld.proto
```

This presumes that your gopath is configured correctly. If not, make --plugin=protoc-gen-grpc-gateway= point to your actual protoc-grpc-gateway binary.

**Comment by killjason** [comment]
Thank youi, I tried your cmd, it worked.

**Comment by killjason** [comment]
@achew22 , I I tried your cmd, no error. but the xxx.pb.go file still not generated.

**Comment by achew22** [comment]
protoc-gen-grpc-gateway creates the grpc-gateway files, xxx.pb.go files are created by [protoc-gen-go](https://github.com/golang/protobuf/tree/master/protoc-gen-go). Hope that helps!

**Comment by AyushSisodiaRZP** [comment]
> What is the output of `which protoc-gen-grpc-gateway`?

protoc-gen-grpc-gateway not found

**Comment by johanbrandhorst** [comment]
You probably need to add something like
```
export PATH:$PATH:~/go/bin
```
To your `~/.bashrc` file or similar.
