### ISSUE TITLE
map values of message type is not validated for unknown fields

### ISSUE THREAD

**Issue by powerman** [grpc-ecosystem/grpc-gateway#2058]
## 🐛 Bug Report

Usually sending unknown field name result in error `could not find field "bad" in "my.pkg.name.MyType"`. But this won't happens for `map<string, MyType>` fields (unknown fields are just ignored in this case).

## Your Environment

Linux, go1.16.2, grpc-gateway v2.3.0.

**Comment by johanbrandhorst** [comment]
Could you detail your set up a bit more? Is this also related to PATCH requests like #2056?

**Comment by powerman** [comment]
Yes, I was testing PATCH when I noticed this. I'm not sure is it specific to PATCH or apply to any request - I just uppose such a validation logic should be same everywhere and thus didn't mention concrete method.

**Comment by powerman** [comment]
Looks like I realized what's going on. I had the (wrong) impression grpc-gateway is strict and returns error when it gets unknown JSON fields from a client. But in fact it looks like such errors are produced while generating value for a fieldmask. So it's strict only if we use PATCH+fieldmask, and only for fields supported by fieldmask (but message fields within map value mentioned in this issue shouldn't be included in fieldmask, thus I don't get an error in this case).

So, looks like this bugreport is invalid.

Anyway, we do need strict valudation and errors when client send unknown fields in JSON - any idea is this a good new feature for grpc-gateway, is it in scope of grpc-gateway (or it's depends on unmarshal implementation outside of grpc-gateway code), or any hints how to implement this feature outside of grpc-gateway in my code?

**Comment by johanbrandhorst** [comment]
There are several things going on here:
1. The gRPC-gateway has a custom PATCH -> field mask parser. This could be buggy for some use cases
2. The default JSON marshaler is https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson. This has an option to "DiscardUnknown" which kind of implies that it should not allow unknown fields by default. This may not behave the way you expect, and if necessary you can configure your own marshaler when creating the servemux.

I don't think there's much we can do in the gateway unless it's a buggy PATCH ->  field mask parser problem. A concrete example would help, a reproducible failing test would be best.

**Comment by powerman** [comment]
I don't think it's buggy related to this issue - fields within map shouldn't be included in fieldmask, so no surprise they're not checked.

But it looks like behaviour of this field mask parser is not compatible with parsing other fields in same request. Both as described in #2056 (I'll take a look at the code when I'll have some spare time), and this issue too - I mean if default JSON marshaller is configured to not return errors on unknown fields then why this parser returns such errors? At a glance it looks like both should work in same way - either return such errors or ignore unknown fields. And this, of course, should be configurable by user, i.e. if user will manually disable DiscardUnknown option as shown in https://github.com/grpc-ecosystem/grpc-gateway/blob/b4d54a0e3d1ea061661de197ce13e09e27ba8c41/docs/docs/development/grpc-gateway_v2_migration_guide.md#runtimedisallowunknownfields-has-been-removed then there should be a way to force same behaviour for field mask parser.
