### ISSUE TITLE
protoc-gen-openapiv2 swagger doc request parameters with field_behavior annotation not working as expected

### ISSUE THREAD

**Issue by elvizlai** [grpc-ecosystem/grpc-gateway#2066]
## 🐛 Bug Report

protoc-gen-openapiv2 annotation `(google.api.field_behavior) = OUTPUT_ONLY` generated swagger doc request parameters not working as not expected. Looks like it only works for `scalar type`, not for `message` or `oneof` embedded.

## To Reproduce

define message
```
syntax = "proto3";

package ttt;

option go_package = "ttt";

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

message XXX {
  message YYY {
    string id = 1;
    // not working as expected
    string ass_id = 2[(google.api.field_behavior) = OUTPUT_ONLY];
  }

   message ZZZ {
      oneof x {
        string id = 1;
        // not working as expected
        string name = 2[(google.api.field_behavior) = OUTPUT_ONLY];
      }
    }

    message MMM {
        string id = 1;
    }

  string id = 1;
  // this works
  map<string,string> kv = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
  YYY yyy = 3;
  ZZZ zzz = 4;
  // not working as expected
  MMM mmm = 5  [(google.api.field_behavior) = OUTPUT_ONLY];
}

service TTTService {
  rpc TTT(XXX) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      get: "/xxx/yyy"
    };
  };
}
```

gen doc
```
protoc -I=include:.  \
    --experimental_allow_proto3_optional \
    --openapiv2_out=. \
    --openapiv2_opt logtostderr=true,allow_merge=true,merge_file_name=generated_doc \
    *.proto
```

## Expected behavior

The swagger doc request json parameters should not shown `kv, yyy.ass_id, zzz.name, mmm`

## Actual Behavior

The request json parameters `yyy.ass_id, zzz.name, mmm` has been shown

## Your Environment

```
protoc --version
libprotoc 3.15.6

./protoc-gen-openapiv2 -version
Version dev, commit unknown, built at unknown
(I use go get with tag v2.3.0)
```

**Comment by johanbrandhorst** [comment]
Thanks for your bug report. Could you share what the output swagger document looks like?

The logic for assigning the swagger properties for field_behavior properties is here: https://github.com/grpc-ecosystem/grpc-gateway/blob/5f64681589f0d6c31895905578d3266c3dc6ef20/protoc-gen-openapiv2/internal/genopenapi/template.go#L2213-L2233. If you could write a failing test (maybe here: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template_test.go#L2940), it would greatly help in debugging and fixing the issue.

CC @ewhauser

**Comment by zzerjae** [comment]
.
