### ISSUE TITLE
How can I define a query param as mandatory?

### ISSUE THREAD

**Issue by ghevge** [grpc-ecosystem/grpc-gateway#2086]
## 🐛 Bug Report

I'm using protoc-gen-swagger V1.16.0 to compile my swagger docs file, out of my proto file. 
My problem is that I cannot find a way to define a query param as mandatory. 

Any idea how I can do it?

## To Reproduce

Basically I want the appId field to be a query param and I want it to be marked as mandatory in the swagger UI. What I've tried so far is to define it like this:

rpc DownloadApplicationConfig(DownloadApplicationConfigRequest) returns (stream google.api.HttpBody) {
    option (google.api.http) = {
      get : "/v4/app-configs/{configId}/.download?appId={appId}"
    };
    ......

message DownloadApplicationConfigRequest {
  option (grpc.gateway.protoc_gen_swagger.options.openapiv2_schema) = {
    json_schema: {
      description: "Object used by the Download Application Config request"
    }
  };
  string configId = 1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {description: "ID of config to download"}];
  string appId = 2 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {description: "Runtime app id"}];
}

But the compiler fails with the error:

[INFO] --- protobuf-maven-plugin:0.6.1:compile-custom (swagger) @ mix-api-endpoint ---
[INFO] Compiling 1 proto file(s) to /opt/RD/MIX/mix-api/api/target/generated-sources/protobuf/swagger
[ERROR] PROTOC FAILED: --swagger_out: segment neither wildcards, literal or variable: expected "{" but got ".download?appId=": /v4/app-configs/{configId}/.download?appId={appId}

[ERROR] /opt/RD/MIX/mix-api/api/src/main/proto/mix-api/mix-api.proto [0:0]: --swagger_out: segment neither wildcards, literal or variable: expected "{" but got ".download?appId=": /v4/app-configs/{configId}/.download?appId={appId}

**Comment by johanbrandhorst** [comment]
This isn't supported by the grpc-gateway as far as I know, nor is it supported by [http.proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) the underlying spec for our parser.

**Comment by ghevge** [comment]
I've found a way to do it. This worked for me.

`string appId = 2 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {​​​​​​​description: "Runtime app id", required: ["appId"]}​​​​​​​];`

**Comment by johanbrandhorst** [comment]
Glad to hear it.
