### ISSUE TITLE
protoc-gen-swagger does not parse query params of a PUT HTTP rpc definition into swagger.json file

### ISSUE THREAD

**Issue by ghevge** [grpc-ecosystem/grpc-gateway#2093]
Hi,
If I try to define a query param  on a PUT method as follows, the protoc-gen-swagger will not generate the swagger code related to the query param

```
syntax="proto3";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

service ABC {

    rpc PutConfigs(PutConfigsRequest) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            put: "/api/v1/abc"
        };
    }
}

message PutConfigsRequest {
    int32 whatever = 1;
}
```

There was a similar problem reported on DELTE and POST methods (https://github.com/grpc-ecosystem/grpc-gateway/issues/559), which was fixed(I can confirm the fix for POST at least), but it seems PUT still has the issue

I am using protoc-gen-swagger-v1.16.0-linux-x86_64 to generate the swagger code.

Thanks

**Comment by ghevge** [comment]
Some more details, it seems the issue only behaves if a body is not defined. I can see the same behavior on POST methods too. If I define a body, the query params are being considered.

**Comment by johanbrandhorst** [comment]
Hm, that definitely sounds wrong, it should be adding the parameters to the query parameters regardless of whether a body is specified or not. Do you have a failing test you could contribute? Similar to how fixing #559 started by adding a failing test: https://github.com/grpc-ecosystem/grpc-gateway/commit/8e387f70817dad4991cf76a9f970320a324de3a2#diff-0330d83e3109c5c0a8cb78a2a980db731e973c738da7851d34a88e00244a4b5eR1696.

**Comment by ghevge** [comment]
I would love too, but I don't have much go experience. And to set up and ramp up on the project it will take me some time, which I don't have at this moment.
