### ISSUE TITLE
protoc-gen-swagger nested struct in post body or response

### ISSUE THREAD

**Issue by shashank-sachan** [grpc-ecosystem/grpc-gateway#2094]
Hi,

I have defined a GRPC rest endpoint like below:
```
rpc CreateMessage(CreateRequest) returns (CreateResponse) {
    option (google.api.http) = {
      post : "/api/v1/message"
      body : "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Create Message"
      description: "Create Message for users"
      tags: "Message"
    };
  };

message CreateRequest {
  string site = 1;
  Message message = 2;
}

message Message {
  string id = 1;
  string title = 2;
  User user = 15;
}
```
If you see above I have nested fields => Message -> User -> This can contain other struct and so on
Now when I generate swagger, in the request body it shows all the nested fields for `Users` but I just to limit those fields in swagger doc.

Current swagger request body JSON:
```
{
 "id": "string",
 "title": "string",
 "user": {
    "id": "string",
    "name": "string",
    "email": "string",
    "address": {
      "city": "string",
      "pincode": "string"
    }
 }
}
```

Required (Don't want to show the other fields/nested fields in the swagger UI):
```
{
 "id": "string",
 "title": "string",
 "user": {
    "id": "string",
    "name": "string",
 }
}
```

The same things is with the message response.
Is it possible to handle it using protoc-gen-swagger?

Thanks

**Comment by johanbrandhorst** [comment]
Hi, thanks for your interest in the project! It's not currently possible to prevent any part of the inputs from being shown, if you only want to show a smaller part, you'll have to change your message definitions.

Hope that helps.
