### ISSUE TITLE
Adding api prefix runtime

### ISSUE THREAD

**Issue by Cosby86** [grpc-ecosystem/grpc-gateway#2097]
Hello all
is there any way to add a prefix on runtime to all my exposed API?

For instance, on my proto i have something similar to: 
/v1/auth/myapi/api1
/v1/auth/myapi/api2
/v1/auth/myapi/api3

and, on rutime, when i create the server I would like to add a prefix to pre defined API:
myprefix/v1/auth/myapi/api1
myprefix/v1/auth/myapi/api2
myprefix/v1/auth/myapi/api3

Can you help me?

**Comment by johanbrandhorst** [comment]
Hi, you can do this with a `http.ServeMux` from the standard library. The grpc-gateway mux implements `http.Handler` so you can simply do something like

```go

mux := http.NewServeMux()
gwMux := runtime.NewServeMux()
myproto.RegisterXXXBlabla(gwMux)
mux.Handle("/myprefix", http.StripPrefix("/myprefix", gwMux))
```

I've not tested the above but the general design should do what you want.

**Comment by Cosby86** [comment]
Doing as you suggested I receive a "not found" API I did exactly you suggested

`
mux := http.NewServeMux()

	gwmux := runtime.NewServeMux()
	aa = RegisterSomething(context.Background(), gwmux, conn)
	if err != nil {
		fmt.Println(aa)
	}

	mux.Handle("/myprefix", http.StripPrefix("/myprefix", gwmux))
`

**Comment by Cosby86** [comment]
Thank you..I made just few fixed by the concept worked.

**Comment by johanbrandhorst** [comment]
Would you like to share how you fixed it?
