### ISSUE TITLE
List out available API

### ISSUE THREAD

**Issue by Cosby86** [grpc-ecosystem/grpc-gateway#2100]
Hello everybody,
on my proto file i have many API. Is there any way to list them from code. basically I would like to have the whole list of exposed REST api from the code. I need them to configure on runtime my reverse proxy

Can you help me?

**Comment by johanbrandhorst** [comment]
You can enable gRPC reflection on your service and use those methods to list the available APIs (https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md). You can even expose the grpc reflection service as a REST server if you want to with our external configuration files: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/grpc_api_configuration/#using-an-external-configuration-file.
