### ISSUE TITLE
Add option to omit `code` from HTTP error response

### ISSUE THREAD

**Issue by mcquackers** [grpc-ecosystem/grpc-gateway#2104]
## 🚀 Feature

DefaultHTTPErrorHandler is a marvelous turnkey handler, but I can't seem to find a way to prevent it from outputting the GRPC code (outside of completely writing a new error handler).

DefaultHTTPErrorHandler is coupled to status.Status, which, while tagged with `omitempty` on code, message, and details, can _never_ omit the code field, as when Code == 0, the entire marshalling process is halted as it's assumed to be a success, as 0 == OK.

It's arguable if the juice is worth the squeeze on this one, as clients can just ignore the `code` field and prefer the HTTP Status Code, but it'd be nice to not expose artifacts of our engineering process to clients and customers.

**Comment by johanbrandhorst** [comment]
Hi Brian, thanks for the colourful issue 😄. To be clear, you're looking for a way to configure the default error handler, but you're not so keen that you'll design your own error handler and configure it via https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#WithErrorHandler? I would argue that it should be very straightforward to just copy the contents of DefaultHTTPErrorHandler and adjust as desired, would that allow you to do what you want?

**Comment by mcquackers** [comment]
@johanbrandhorst I think I should have examined the DefaultHTTPErrorHandler with a less-exhausted mind.  I was worried ripping out
`buf, merr := marshaler.Marshal(pb)
	if merr != nil {
		grpclog.Infof("Failed to marshal error message %q: %v", s, merr)
		w.WriteHeader(http.StatusInternalServerError)
		if _, err := io.WriteString(w, fallback); err != nil {
			grpclog.Infof("Failed to write response: %v", err)
		}
		return
	}`

would lose me some of the more advanced proto mechanisms, but looking at it with a clearer head, it looks like `buf` is only used to marshal into the http.ResponseWriter, and nothing else, which means I could then just rip it out and marshal the error into the ResponseWriter.

Thanks for being my 🦆 haha
