### ISSUE TITLE
Custom Inbound Marshaler not being used for transcoding

### ISSUE THREAD

**Issue by 0xKiwi** [grpc-ecosystem/grpc-gateway#2115]
## 🐛 Bug Report
After setting a custom marshaler for encoding/decoding within the grpc-gateway, I've noticed the inbound marshaler is not used at all within the compiled gateway files. Not sure if I'm missing something or if this is an oversight.

The inbound marshaler is not used at all for `pathParams` here: https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/eth/v1/beacon_chain_service.pb.gw.go#L57

Yet it is used as part of `runtime.ForwardResponseMessage` here: https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/eth/v1/beacon_chain_service.pb.gw.go#L2289

It is also unused for endpoints that take in a protobuf message struct here: https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/eth/v1/beacon_chain_service.pb.gw.go#L861

But also used for the return.

## To Reproduce
1. Set custom marshaler using gwmux.
2. Query API with a message that depends on marshaler.
3. Query will fail because the input is not being marshaled, only the output.

## Expected behavior
One would expect the marshaler to be used, with the input/output both being transcoded through the assigned marshaler.

## Actual Behavior
The marshaler is only used for the outbound messages, not the inbound, see here:
The marshaler (which changes base64 to hex) output here:
```
 kiwi@kiwi   ~/Work/prysm     change-to-gocast    15  curl -H 'Accept: application/json' localhost:3500/eth/v1/beacon/genesis
{
"data": {
"genesis_fork_version": "0x00002009",
"genesis_time": "2020-11-18T12:00:07Z",
"genesis_validators_root": "0x9436e8a630e3162b7ed4f449b12b8a5a368a4b95bc46b941ae65c11613bfa4c1"
}
}%   
```

Yet, when I try passing a field body or struct to a GET:
```
curl -H 'Accept: application/json' localhost:3500/eth/v1/beacon/states/0x0780527577054a5323d530d8c4216efdd28e9ffed39bc309214c6d75702515a1/root
> {"code":3,"details":[],"message":"type mismatch, parameter: state_id, error: illegal base64 data at input byte 64"}%  
```

## Your Environment

Ubuntu Linux, using a fork of grpc-gateway from latest master.

**Comment by johanbrandhorst** [comment]
Looking at your [protobuf schema](https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/eth/v1/beacon_chain_service.proto#L133), I can see that your definition looks like this:

```
rpc SubmitAttestations(SubmitAttestationsRequest) returns (google.protobuf.Empty) {
   option (google.api.http) = {post: "/eth/v1/beacon/pool/attestations"};
 }
```

This will not parse anything from the body, because you haven't [specified any body parameters](https://github.com/googleapis/googleapis/blob/5deb21826a6645d278010dc384a8d5dd942dfebd/google/api/http.proto#L124-L168). Simply changing your definition to the following should allow you to use your custom marshaler:


```
rpc SubmitAttestations(SubmitAttestationsRequest) returns (google.protobuf.Empty) {
  option (google.api.http) = {
    post: "/eth/v1/beacon/pool/attestations"
    body: "*"
  };
}
```

This is covered in many of our examples and in the introduction in the README, but if you think there's some way for us to make this clearer to the user I would love a contribution to our docs from you 😄.

**Comment by 0xKiwi** [comment]
Hello!! Thank you! I thought I was missing something haha 

Trying to add it to the get requests which use path params and I'm getting:
```
--grpc-gateway_out: must not set request body when http method is GET: ListValidators
```

Is it possible for me to use marshalers on messages like this? I need the marshaler to be used on the path param. 
https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/eth/v1/beacon_chain_service.proto#L52

Thank you!

**Comment by johanbrandhorst** [comment]
You can use https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime?utm_source=godoc#SetQueryParameterParser to configure your query parameter parser. You can't use `body` with GET, since the HTTP spec requires that any body sent with a GET request should be ignored.

**Comment by 0xKiwi** [comment]
Thank you!!! Is that detailed anywhere?

I'm passing in my modified parser here: https://github.com/prysmaticlabs/prysm/blob/transcoding/beacon-chain/gateway/gateway.go#L76. Its the default parser with some small changes to accept hex, but for some reason its not being used (checked through logging). Is anything else needed? [Heres the parser](https://github.com/prysmaticlabs/prysm/blob/transcoding/beacon-chain/gateway/pathparser.go).

**Comment by johanbrandhorst** [comment]
Not sure if your question was regarding the HTTP spec or the parameter parser, but no, you shouldn't need to do anything else to use your custom parameter parser. For the HTTP question, see https://stackoverflow.com/questions/978061/http-get-with-request-body. If your parser isn't being used I don't know why that would be, as far as I know that part is working.

**Comment by 0xKiwi** [comment]
I meant the parser. My bad! 

Ok, thank you. I'm not sure whats going on either but I will investigate further. Thank you! I think its fine to close this issue :smile:

**Comment by 0xKiwi** [comment]
I'm not sure why but I'm not seeing this compiled output in my .gw.pb.go files. 
Output I'm expecting to see
https://github.com/grpc-ecosystem/grpc-gateway/pull/1138/files/1aeb9b74e8eea51ca7a0482bc62650dc5d2271da

Actual output
https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/eth/v1/beacon_chain_service.pb.gw.go#L57

**Comment by johanbrandhorst** [comment]
You're probably using an old version of the generator. I'm not sure how you version the generator but https://github.com/prysmaticlabs/ethereumapis/blob/gen-go-cast/tools/ethereumapi_dependencies.bzl#L424-L436 lists two different versions. You'll need at least v2 to use the custom query parameter parser. Also, note that we already have bazel support directly, you don't need to include it as a go_repsitory.

**Comment by 0xKiwi** [comment]
I believe I'm using v2. I've just had to fork it to make other modifications. 

Why isn't the custom parser used here? I don't see it used anywhere in the template.

https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L392

Am I looking at the wrong code?

**Comment by johanbrandhorst** [comment]
Yeah I think that code is just a red herring, it sets a global which is what's being called when `runtime.PopulateQueryParameters` is called: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L392.

**Comment by 0xKiwi** [comment]
Ahh, I see. I will investigate why my parser isn't being used. Thank you for your time!

**Comment by 0xKiwi** [comment]
Ah, I'm facing issues because the generated grpc-gateway code attempts decoding from base64 even if a parser is set. Seems impossible to change from base64 without modifying the grpc-gateway plugin...

**Comment by johanbrandhorst** [comment]
That's a path parameter, not a query parameter. We don't have a configurable path parameter parser yet. Would you like to make one?

**Comment by 0xKiwi** [comment]
Oh, my bad. I'm not super familiar with HTTP terminology. It would be fantastic to allow custom parsing for path parameters :smiley:

**Comment by johanbrandhorst** [comment]
Agreed, that is clearly a feature the gateway is missing today. It may be complicated to introduce in a backwards compatible manner, but maybe something like what we're doing for the query parameter parser will work. I think it'd probably take a `map[string]string` from the existing `pathParams`. I don't think it'll be trivial to work out exactly which parameters need to be parsed, right now that seems to be determined at generation time. I don't have many spare cycles for designing this sort of thing, but feel free to play around with it and let me know if you need any pointers.

**Comment by 0xKiwi** [comment]
Hello @johanbrandhorst! I've submitted a WIP PR of a very crude implementation of a path parser. I've tested it locally and it seems to work: 
```
 kiwi@kiwi   ~/Work/prysm     transcoding    15  curl -H 'Accept: application/json' localhost:3500/eth/v1/beacon/states/0x20347d59328cc1331dc5c7850eb34f9cc16db0c374c98168cc46741e002f1885/root
{"data":{"state_root":"0x20347d59328cc1331dc5c7850eb34f9cc16db0c374c98168cc46741e002f1885"}}%  
```

Would appreciate your guidance on a cleaner way to integrate. The go-template is rather complex. 

Thank you!
