### ISSUE TITLE
documentation of semantics of endpoint declarations

### ISSUE THREAD

**Issue by sdemos** [grpc-ecosystem/grpc-gateway#212]
After working with this project for a little while, I finally found [Google's description of the semantics](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) that are used in this package. It would be super helpful if that (or a better version of that) were linked to prominently in the README.md. It would be even better if the specific way that this library implemented that description was documented, so that someone learning how to use this library doesn't have to just mess around with the library to see how it works. The implicit generation of query parameters especially threw me, I didn't realize that this library could even do that until someone mentioned it in another issue.

**Comment by yugui** [comment]
Thank you for your feedback. We should definitely have had such documentation.

**Comment by BrianHicks** [comment]
@sdemos thank you so much for that link. I was having the same problem with finding documentation.

**Comment by philips** [comment]
@sdemos are you going to submit a PR to close this out?
