### ISSUE TITLE
default url in swagger UI

### ISSUE THREAD

**Issue by keith6014** [grpc-ecosystem/grpc-gateway#2126]
The url on the UI is keep defaulting to: https://petstore.swagger.io/v2/swagger.json
How can I change it to something else? I prefer it to default to localhost:port/api/swagger.json

```
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
    host:"localhost:8080";
    info: {
      title: "grpc-rest-openapi-demo";
      version: "1.0";
      contact: {
        name: "Some Name";
        url: "http://someplace.com";
        email: "example@example.com";
      };
    };
    schemes: HTTP;
    schemes: HTTPS;
    consumes: "application/json";
    produces: "application/json";
};
```

**Comment by johanbrandhorst** [comment]
Depending on what UI you're using, you probably need to manually edit the JS. The `swagger-ui` hardcodes the URL: https://github.com/swagger-api/swagger-ui/blob/4acec8dff77fb1fccf8baa4b6d284b99a7eb2809/dist/index.html#L42. Are you suggesting there is anything wrong with the gateways swagger file generation?

**Comment by keith6014** [comment]
Exactly. So, there is no way to set the url to my .json?

**Comment by johanbrandhorst** [comment]
I think you have to edit the `index.html` before you serve it. In my grpc-gateway-boilerplate example you can see what I have done so, and replaced it with a locally served swagger file: https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/ce686e6fbff2cff971c9762612c9be624eda8da2/third_party/OpenAPI/index.html#L42.

**Comment by johanbrandhorst** [comment]
Given that I don't think there's anything specific to the grpc-gateway here, I'm going to close this issue.

**Comment by keith6014** [comment]
thanks mate. great product
