### ISSUE TITLE
Meta image of gRPC-Gateway repository is not generating correct image

### ISSUE THREAD

**Issue by iamrajiv** [grpc-ecosystem/grpc-gateway#2135]
Meta image of [gRPC-Gateway repository](https://github.com/grpc-ecosystem/grpc-gateway) generates an older gRPC-Gateway architecture image though it has been updated with a new image. It should generate this image https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/assets/images/architecture_introduction_diagram.svg.

![Screenshot 2021-05-08 at 9 22 51 PM](https://user-images.githubusercontent.com/42106787/117545474-8d9b6180-b043-11eb-9064-e71c40367ab0.jpg)

References:

- https://cards-dev.twitter.com/validator
- https://metatags.io

**Comment by johanbrandhorst** [comment]
Can we change this?

**Comment by iamrajiv** [comment]
Yeah, @johanbrandhorst, we can do that. Go to setting of repository and edit Social preview image.

![Screenshot 2021-05-10 at 3 59 17 PM](https://user-images.githubusercontent.com/42106787/117646805-d2d9a380-b1a9-11eb-9309-b3ad2c620c0e.jpg)

I have converted the [architecture diagram](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/assets/images/architecture_introduction_diagram.svg) into a PNG format because we cannot upload in SVG format.

Below image is an architecture diagram in PNG format (1280×640px):

![architecture_introduction_diagram](https://user-images.githubusercontent.com/42106787/117647267-627f5200-b1aa-11eb-9832-8ba21c9df2ad.png)

**Comment by johanbrandhorst** [comment]
This has been fixed, though instead of squishing our existing one I just added whitespace.
