### ISSUE TITLE
Exclude some proto files when generating openapi files

### ISSUE THREAD

**Issue by tozh** [grpc-ecosystem/grpc-gateway#2139]
## 🚀 Feature

Right now, `protoc-gen-openapiv2` generates swagger files for each proto file, no matter if there is an `openapiv2_swagger` option in the file. A lot of empty swagger files are generated. Is there any way we can exclude proto files which don't have the `openapiv2_swagger` file option?

**Comment by johanbrandhorst** [comment]
This is actually a matter of how you invoke your generator. What does your generation command look like? Do you use `protoc` or `buf`?
