### ISSUE TITLE
Example of working with Bazel

### ISSUE THREAD

**Issue by mikeamosov** [grpc-ecosystem/grpc-gateway#2140]
## 📚 Documentation

Hello. Where can I find an example of how to use the library with Bazel.

0. I tried the examples from `examples/internal`, but didn't understand how to generate Go and Swagger files. In the example, these files are already there, when I try to collect them from myself, I just have the Go files collected in the Bazel cache.
Is there an example of an echo server with automatic generation of these files?

1. How to use ' grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation ' together with Bazel?
I get the following error:
```bash
ERROR: /example/BUILD.bazel:5:14: no such package 'protoc-gen-openapiv2/options': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /protoc-gen-openapiv2/options and referenced by '//example:example_proto'
```

2. How do I get the generated files to the folder with the .proto file? I don't understand how you can write code in the IDE without it. As I understand it, only write a script that will take files out of the assembly?

**Comment by videlanicolas** [comment]
There's no documentation on how to get started with this using bazel. I have a bazel setup + gazelle and I'm still getting errors while building a simple example.

I'll post the work that I'm doing in order to have something submitted to this codebase.

**Comment by johanbrandhorst** [comment]
Sorry for the radio silence here, you're right that the bazel documentation is definitely lacking. I'm not personally very experience with its use so I would appreciate any contributions that could help newcomers use our bazel tooling.

**Comment by pbsf** [comment]
I just created a dummy repository that uses bazel to import grpc-gateway and generate the openapiv2 documentation from a proto file: https://github.com/pbsf/protoc-gen-openapi-bazel-example. I hope that helps.

The protobuffer, go and gazelle versions are important, so are the commands order on the WORKSPACE.
