### ISSUE TITLE
protoc-gen-openapiv2: path parameters appear in body and path

### ISSUE THREAD

**Issue by berlund** [grpc-ecosystem/grpc-gateway#2152]
## 🐛 Bug Report

Specifying the body with asteriks in the `google.api.http` does not ignore the fields already present in the path, resulting in duplicated fields in the generated swagger document.

## To Reproduce
Having a proto definition like this:

```
rpc AMethod (MethodRequest) returns (SomeResponse) {
    option (google.api.http) = {
      post: "/v1/projects/{project_id=*}/someotherpath"
      body: "*"
    };
}

message AMessage {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema:{
      title: "A message
      description: "A message"
    };
  };
  string project_id = 1 [(google.api.field_behavior) = REQUIRED];
  string other_field = 2 [(google.api.field_behavior) = REQUIRED];
}
```

will generate a swagger with the `project_id` both as a path parameter and as part of the body. 

## Expected behavior

From the documentation I expected that project_id will not be rendered as a body param since it's already part of the path. Or is that only true for the generated proxy code? The proxy happily ignores the param in the body and takes the one given in the path.

## Actual Behavior

The swagger contains the parameter both as a path parameter and in the body.

**Comment by johanbrandhorst** [comment]
Thanks for your report! This sounds like a bug in the openapiv2 generator. Glad to hear that the proxy is still doing the right thing. The first step to fixing an issue in the generator is to create a failing test. Do you think you could put together a reproduction of this bug as a test in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template_test.go?
