### ISSUE TITLE
Detecting request from gateway

### ISSUE THREAD

**Issue by FedorLap2006** [grpc-ecosystem/grpc-gateway#2159]
Hello everyone. I'm making wrapping my REST API with some authentication interceptors (as server interceptors). And I'm stuck in dead end. Any idea how to **properly** detect that the request came from the internal RPC or from the gateway.
I've seen that I for example can check for metadata headers like `x-forwarded` or `grpcgateway-user-agent`, but how do it intended way?

By the way, if grpc-gateway doesn't have this functionality, that would be cool if we could check in the future if request came from RPC or gateway without throwing additional headers through http handlers or messing around with MD

**Comment by johanbrandhorst** [comment]
Hi!

We're not setting any headers or anything that you can rely on existing that I know, but I have to ask, what do you want to do? If you want to have special authentication for the requests hitting the grpc-gateway, you could add a client-side interceptor to your gRPC connection. That would be called on every request made between the gateway and your gRPC backend. Would that work?

**Comment by FedorLap2006** [comment]
> you could add a client-side interceptor to your gRPC connection. That would be called on every request made between the gateway and your gRPC backend. Would that work?

Probably. But I should try it first.

**Comment by FedorLap2006** [comment]
Anyways, took a long time to respond, but yeah, that worked, thanks.
