### ISSUE TITLE
Response body as a single field

### ISSUE THREAD

**Issue by BrianHicks** [grpc-ecosystem/grpc-gateway#217]
Part of the API I'm covering needs to be able to return just bytes. Right now I have something similar to the following:

```protobuf
message Content {
  string content = 1;
}
```

for RPC, that's just fine; the client can unwrap it. However, over HTTP I don't want a wrapping JSON, I *only* want that `content` field. Is there a way to specify this in the gateway configuration?

**Comment by yugui** [comment]
You can write a [custom marshaler](https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#Marshaler) to do that.
Also, what grpc-gateway generates is an ordinary HTTP handler in Golang.  So you can do whatever you want by wrapping the handler.

**Comment by BrianHicks** [comment]
Is there documentation or an example of where to put the custom marshaller? It doesn't jump out at me where it should go.

**Comment by skylarbpayne** [comment]
Hey @BrianHicks , I see your question was never answered. You can use the WithMarshalerOption in your entry point: https://github.com/grpc-ecosystem/grpc-gateway/blob/acebe0f9ff5993e130b141ee60e83e592839ca22/runtime/marshaler_registry.go#L85

Hope that helps :).
