### ISSUE TITLE
Go Dependencies in Gradle?

### ISSUE THREAD

**Issue by lsmith24** [grpc-ecosystem/grpc-gateway#2172]
Hi, does anyone know how to set this up without using Go? I am using gradle and java for my project and I cannot find the equivalent dependencies for Gradle. If anyone knows if this is possible to do without using Go that would be great thanks!

**Comment by johanbrandhorst** [comment]
The gateway itself has to be built using Go, but it can proxy to an arbitrary backend gRPC server. See https://github.com/johanbrandhorst/grpc-gateway-boilerplate#running-the-standalone-server for an example of using an external gRPC server.

What problem are you having exactly? Is it an issue with generating the protobuf files? We have a support channel (#grpc-gateway) on the [Gophers Slack](https://invite.slack.golangbridge.org/) where we may be able to give you better help.

**Comment by lsmith24** [comment]
Ah ok. I already have proto files and a java server, I was just wondering if there is a way to include these dependencies in a build.gradle file instead of Go but it seems not

**Comment by johanbrandhorst** [comment]
Indeed, this is not possible today. I will close this issue but don't hesitate to reply if you need more help.
