### ISSUE TITLE
Can not build python library if openapi options are used in proto definition.

### ISSUE THREAD

**Issue by daicoden** [grpc-ecosystem/grpc-gateway#2173]
## 🐛 Bug Report

Unable to build python libraries when a proto is defined with options using the protoc-gen-openapiv2/options:options_proto.

This is somewhat related to https://github.com/bazelbuild/bazel/issues/3935 and https://github.com/bazelbuild/bazel/issues/6841

To use https://github.com/protocolbuffers/protobuf/blob/master/protobuf.bzl, you must define the protobuf in this repo to have access to the source files. However, this fails to build due to the hyphen in the directory naming.

There is a grpc implementation py_proto_library which allows you to define the rule in your own repository because it doesn't need the source files, but alas, fails in a similar fashion.

I was able to get things working in my own project by renaming `protoc-gen-openapiv2` to `protoc_gen_openapiv2`, and updating the imports.

## To Reproduce

Create a python library in a project which uses openapiv2 options.

```
syntax = "proto3";

package cfhtapi.types;
// https://github.com/golang/protobuf
option go_package = "cfhtapi/common";
option java_package = "edu.hawaii.cfht.protos.types";
option java_outer_classname = "TypesProtos";
option java_multiple_files = true;
option java_generic_services = true;

import "protoc-gen-openapiv2/options/annotations.proto";

message SkyCoordinate {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        json_schema: {
            title: "Sky Coordinate"
            description: "Specify an on sky location via right ascension and declination."
        }
    };

    /* Right Ascension, in degrees */
    double ra = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
        title: "Right Ascension"
...
}
```

You can see the root problem via:
1. Checkout https://github.com/CFHT/grpc-gateway/commit/9c2188e28d0d85d89748579b3b47753dbd5cdc60
2. `bazelisk build protoc-gen-openapiv2/options:options_py_proto`

## Expected behavior

Python libraries would still function after adding openapiv2 options.

## Actual Behavior

Python libraries are no longer valid.

```
____ ERROR collecting client_lib/python/cfht_cli/test/unit/request_test.py _____
client_lib/python/cfht_cli/test/unit/request_test.py:6: in <module>
    from cfht_cli.cli.cli import CLI
...
client_lib/python/cfht_sdk/src/cfhtapi/types_pb2.py:18: in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
../pip_pypi__protobuf/google/protobuf/descriptor.py:983: in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
E   TypeError: Couldn't build proto file into descriptor pool!
E   Invalid proto descriptor for file "cfhtapi/types.proto":
E     protoc-gen-openapiv2/options/annotations.proto: Import "protoc-gen-openapiv2/options/annotations.proto" has not been loaded.
```

## Your Environment

macos, bazel 3.5.

**Comment by johanbrandhorst** [comment]
I'm confused, doesn't this imply that python cannot support protobuf files with dashes in their import path? That sounds insane. We can't change this import path now without breaking existing users. There must be another way?

**Comment by daicoden** [comment]
Alas, it does for the `py_proto_library` rule.  https://github.com/bazelbuild/bazel/issues/6841. I would be very happy if I was wrong... but I haven't figured out anyway to get it to work because the `py_proto_library` is operating on the `.proto` sources, which refer to eachother with the hyphen imports, but then the final generated packaging needs to be underscores.

However, the grpc team created a different definition of py_proto_library, which lets you operate on the intermediate descriptor bin files (i.e. like go_proto_libary), and has some replacements of `-` for `_`. I ran into a snag for my use case, but I could try a little harder.

cc @gnossen this may be out of your wheelhouse... but should integrations be using the `py_proto_library` from GRPC to work around the bazel implementation limitations? Is there something that can be done to move the decision one way or the other on the canonical `py_proto_libary` to use?

**Comment by daicoden** [comment]
Actually... https://github.com/protocolbuffers/protobuf/issues/7061 would also fix the issue.
