### ISSUE TITLE
Access to the complete REST URI in the gRPC server middleware

### ISSUE THREAD

**Issue by shivasishdas** [grpc-ecosystem/grpc-gateway#2174]
## 🚀 Feature
We have been using the `grpc.UnaryServerInterceptor` in the middleware to enrich our context logging. There has been a use case where we needed to access the `complete HTTP REST URI` before it gets translated to its equivalent RPC. The middleware only gives access to its equivalent RPC name. If possible can we enrich either the **context** before forwarding the request or add this metadata to some other info **struct{}**.

**For example, refer to the [proto](https://github.com/razorpay/metro-proto/blob/7bf7d8f94cea8e6207b2993a581b5bbc17e2a0c7/metro/proto/v1/spec.proto#L105
) definition:**
`/v1/{name=projects/*/topics/*}` gets translated to `v1.Publisher.CreateTopic`
Actual REST call made in this case:
`{{HOST}}/{{VERSION}}/projects/{{$guid}}/topics/{{$guid}}`
^^ Need access to this complete REST URI as made available incase of an HTTP server.

Not sure if any such feature already exists via some middleware ELSE would love to submit a PR if someone can point me in direction of how to get started on this feature.

Reference to an already existing middleware [usage](https://github.com/razorpay/metro/blob/3d82ed887f4d38152f130c2f8cae368401a9d7c6/internal/interceptors/tags.go#L23) in the project.

**Comment by johanbrandhorst** [comment]
I replied on another issue, but I think the best you can to today is to wrap the `runtime.ServeMux` with custom HTTP middleware.

**Comment by shivasishdas** [comment]
This is solved now. https://grpc-ecosystem.github.io/grpc-gateway/docs/operations/annotated_context/
