### ISSUE TITLE
protoc-gen-openapiv2 creates incorrect schema for google.protobuf.Any

### ISSUE THREAD

**Issue by dan-j** [grpc-ecosystem/grpc-gateway#2177]
## 🐛 Bug Report

I have a message containing a `google.protobuf.Any`, and the resultant `swagger.json` file contains a definition for `protobufAny` with a property `typeUrl` instead of `@type`.

If I use the swagger-ui to make a request following the schema, my grpc-gateway proxy ends up failing because the `Any` field is omitted from the request. If I manually change the request body so that `@type` is defined instead of `typeUrl`, everything works.

## To Reproduce

Create a message like so:

```proto
import "google/protobuf/any.proto";

message MyMessage {
  string id = 1;
  google.protobuf.Any config = 2;
}
```

Running `protoc-gen-openapiv2` using buf (following the instructions from the `README.md`), and I end up with a field in the `definitions` object of the swagger.json:

```json
{
  ...
  "protobufAny": {
      "type": "object",
      "properties": {
        "typeUrl": {
          "type": "string",
          "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n`path/google.protobuf.Duration`). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme `http`, `https`, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n* If no scheme is provided, `https` is assumed.\n* An HTTP GET on the URL must yield a [google.protobuf.Type][]\n  value in binary format, or produce an error.\n* Applications are allowed to cache lookup results based on the\n  URL, or have them precompiled into a binary to avoid any\n  lookup. Therefore, binary compatibility needs to be preserved\n  on changes to types. (Use versioned type names to manage\n  breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com.\n\nSchemes other than `http`, `https` (or the empty scheme) might be\nused with implementation specific semantics."
        },
        "value": {
          "type": "string",
          "format": "byte",
          "description": "Must be a valid serialized protocol buffer of the above specified type."
        }
      },
      "description": "`Any` contains an arbitrary serialized protocol buffer message along with a\nURL that describes the type of the serialized message.\n\nProtobuf library provides support to pack/unpack Any values in the form\nof utility functions or additional generated methods of the Any type.\n\nExample 1: Pack and unpack a message in C++.\n\n    Foo foo = ...;\n    Any any;\n    any.PackFrom(foo);\n    ...\n    if (any.UnpackTo(\u0026foo)) {\n      ...\n    }\n\nExample 2: Pack and unpack a message in Java.\n\n    Foo foo = ...;\n    Any any = Any.pack(foo);\n    ...\n    if (any.is(Foo.class)) {\n      foo = any.unpack(Foo.class);\n    }\n\n Example 3: Pack and unpack a message in Python.\n\n    foo = Foo(...)\n    any = Any()\n    any.Pack(foo)\n    ...\n    if any.Is(Foo.DESCRIPTOR):\n      any.Unpack(foo)\n      ...\n\n Example 4: Pack and unpack a message in Go\n\n     foo := \u0026pb.Foo{...}\n     any, err := anypb.New(foo)\n     if err != nil {\n       ...\n     }\n     ...\n     foo := \u0026pb.Foo{}\n     if err := any.UnmarshalTo(foo); err != nil {\n       ...\n     }\n\nThe pack methods provided by protobuf library will by default use\n'type.googleapis.com/full.type.name' as the type URL and the unpack\nmethods only use the fully qualified type name after the last '/'\nin the type URL, for example \"foo.bar.com/x/y.z\" will yield type\nname \"y.z\".\n\n\nJSON\n====\nThe JSON representation of an `Any` value uses the regular\nrepresentation of the deserialized, embedded message, with an\nadditional field `@type` which contains the type URL. Example:\n\n    package google.profile;\n    message Person {\n      string first_name = 1;\n      string last_name = 2;\n    }\n\n    {\n      \"@type\": \"type.googleapis.com/google.profile.Person\",\n      \"firstName\": \u003cstring\u003e,\n      \"lastName\": \u003cstring\u003e\n    }\n\nIf the embedded message type is well-known and has a custom JSON\nrepresentation, that representation will be embedded adding a field\n`value` which holds the custom JSON in addition to the `@type`\nfield. Example (for message [google.protobuf.Duration][]):\n\n    {\n      \"@type\": \"type.googleapis.com/google.protobuf.Duration\",\n      \"value\": \"1.212s\"\n    }"
    }
...
}
```

## Expected behavior

The `typeUrl` field within `protobufAny` should be `@type`.

## Actual Behavior

The `@type` field is missing.

## Your Environment

Go 1.16
Windows 10
I'm not sure how to find out the version of protoc-gen-openapiv2 I'm using, but this is a new project today so I'm guessing up-to-date.

**Comment by johanbrandhorst** [comment]
Sounds like a bug! Would you be willing to help fix it? I suspect we could add something to `wktSchemas` (https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template.go#L34) and maybe a few special cases like we have for `.google.protobuf.Empty`. The first step would be to produce a failing test case. We have a few test cases that may make for a good basis (https://github.com/grpc-ecosystem/grpc-gateway/blob/a1902721a191140680ff3168354f8005382fa6d9/protoc-gen-openapiv2/internal/genopenapi/template_test.go#L3342-L3360). Please let me know if you need anymore pointers!

**Comment by dan-j** [comment]
Thanks @johanbrandhorst! No problem, I'll be looking at this this afternoon since it's blocking my actual task at my company.

Will keep you posted.

**Comment by dan-j** [comment]
Hey @johanbrandhorst... So I've got the repo cloned, ran the following command, and then I have a load of changes to be committed.

```sh
make install && make clean && make generate
```

After trying to build, I get this error to do with go-resty/resty:

```
$ go build ./...                  
examples/internal/clients/abe/api_client.go:32:2: no required module provides package github.com/go-resty/resty; to add it:
        go get github.com/go-resty/resty
$ go get -u github.com/go-resty/resty
go get: github.com/go-resty/resty@v1.8.0 updating to
        github.com/go-resty/resty@v1.12.0: parsing go.mod:
        module declares its path as: gopkg.in/resty.v1
                but was required as: github.com/go-resty/resty
```

Turns out one of the newly generated files is  `examples/internal/clients/echo/api_client.go` which imports resty. Not really sure how to proceed :/

**Comment by dan-j** [comment]
Oh, just looked into how CircleCI works and noticed it's using an older version of swagger-codegen. Let's see how this goes...

**Comment by dan-j** [comment]
Yep, well, my version was an old version (thought I'd got the latest). Using 2.4.8 and everything is building now with no unexpected changes 👍

**Comment by dan-j** [comment]
I've made some progress in understanding how everything works, and it's not straight forward. I have a solution which I'll make an MR for, but still needs tests (I was struggling to understand the tests so made some temporary changes to make the existing tests fail and that helped more 😅).

So, you can't just add a new entry into `wktSchemas` because then it removes the `protobufAny` definition and inlines every usage, i.e. `rpcStatus.details` is no longer a `ref` to `#/definitions/protobufAny`, it's now another nested schema object. This isn't necessarily an issue, but could result in a lot of bloat if you had a lot of RPCs/messages referencing `google.protobuf.Any`.

If you don't add an entry into `wktSchemas` (i.e. the current behaviour), the `google.protobuf.Any` message is added to `customRefs` to be processed at the end. This results in using the same method, `renderMessageAsDefinition()`, which ends up reflecting over all the fields which is where the `typeUrl` and `value` properties come from.

I think I have a workaround, not sure if it's suitable, but we have a new global map `wktReferencedSchemas` which contains our proper `protobufAny` schema. Within `renderMessageAsDefinition()`, if we're processing a type which is already in `customRefs`, we lookup the value from `wktReferencedSchemas`. If it exists we use that, otherwise we proceed to reflect over each field and build the schema up as normal.

**Comment by dan-j** [comment]
Created a new PR #2292 which fixes this with less confusing changes.
