### ISSUE TITLE
Example with Java server

### ISSUE THREAD

**Issue by lsmith24** [grpc-ecosystem/grpc-gateway#2183]
Hi, I was wondering if anyone has an example where they have the gateway connected to a Java server? I followed the boilerplate code and I cannot seem to get mine to work with the command they give for a standalone server. My server is still gRPC but it is running locally on its own. Thanks

**Comment by johanbrandhorst** [comment]
I don't think we have an example of a standalone Java server, that would be really cool to add to the documentation! Lets try and figure this out in the boilerpate repo first, but I'd love to see a concrete example contributed to our docs afterwards :).
