### ISSUE TITLE
Unmarshal response from streaming

### ISSUE THREAD

**Issue by pavolloffay** [grpc-ecosystem/grpc-gateway#2189]
## 🚀 Feature

The streaming response is wrapped into `result` object (see https://github.com/grpc-ecosystem/grpc-gateway/issues/1254, applies for v1 and v2). This makes it impossible to unmarshal (via JSONPb) the response body into protoc generated objects (`MyResponse`) in this case. The response can be unmarshalled only if the "result" envelope is removed (e.g. string manipulation). 

```proto
message MyResponse {
  string message = 1;
}

service QueryService {
  rpc Get(Request) returns (stream MyResponse) {}
}
```

The response body looks like:
```json
{
  "result": {
    "message": "hello"
}
```

Is there a way we could improve this? I have tried to define a proto message (see below) that could be used to remove the envelope. 

```proto
message ResultWrapper {
  bytes result = 1;
// google.protobuf.Any result = 1; // does not work either bc the JSON does not have type annotation https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto#L110
}
```

**Comment by johanbrandhorst** [comment]
An alternative way to unmarshal it is to wrap your response message type in the envelope type manually:
```
type Envelope struct {
    Result *yourpb.YourType `json:"result"`
    Error *statuspb.Status `json:"error"`
}
```

**Comment by johanbrandhorst** [comment]
You can use jsonpb with a custom type too. Another alternative is to generate the openapiv2 spec and then generate a client using that, it should be able to parse the streaming messages too.

**Comment by Prabhjot-Sethi** [comment]
> An alternative way to unmarshal it is to wrap your response message type in the envelope type manually:
> 
> ```
> type Envelope struct {
>     Result *yourpb.YourType `json:"result"`
>     Error *statuspb.Status `json:"error"`
> }
> ```

Is there any documentation on how error reporting per entry works, can server control how and what error goes to client.
usually grpc only provides mechanism to report error while starting the stream

**Comment by Prabhjot-Sethi** [comment]
> An alternative way to unmarshal it is to wrap your response message type in the envelope type manually:
> 
> ```
> type Envelope struct {
>     Result *yourpb.YourType `json:"result"`
>     Error *statuspb.Status `json:"error"`
> }
> ```

Is there any documentation on how error reporting per entry works, can server control how and what error goes to client.
usually grpc only provides mechanism to report error while starting the stream

**Comment by Prabhjot-Sethi** [comment]
> An alternative way to unmarshal it is to wrap your response message type in the envelope type manually:
> 
> ```
> type Envelope struct {
>     Result *yourpb.YourType `json:"result"`
>     Error *statuspb.Status `json:"error"`
> }
> ```

Is there any documentation on how error reporting per entry works, can server control how and what error goes to client.
usually grpc only provides mechanism to report error while starting the stream

**Comment by johanbrandhorst** [comment]
gRPC generally supports returning an error at any point in the streaming, so the grpc-gateway must also be able to return an error at any point in the streaming.
