### ISSUE TITLE
protoc_gen_openapiv2 Should Accept a List of Proto Libraries?

### ISSUE THREAD

**Issue by amitz** [grpc-ecosystem/grpc-gateway#2190]
## 🚀 Feature

At the moment, the `proto` [attribute](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/defs.bzl#L213) in the `protoc_gen_openapiv2` Bazel rule - is set to label. I assume the original design, was to wrap couple of Protobuf files in a single `proto_library` like [so](https://github.com/grpc-ecosystem/grpc-gateway/blob/317b2dcf4fd267d60cd69e56ff29a92695a97b8c/examples/internal/proto/examplepb/BUILD.bazel#L42). However, there's a Bazel [recommendation](https://docs.bazel.build/versions/main/be/protocol-buffer.html#proto_library) to use a single `proto_library` rule, per .proto file. For example, the Google API Bazel BUILD [file](https://github.com/googleapis/googleapis/blob/master/google/api/BUILD.bazel#L9), follow that recommendation. 

I follow the same  recommendation in my own project, and I'm having hard time to use `protoc_gen_openapiv2`. I had to create a Bazel Macro, that calls `protoc_gen_openapiv2` multiple times (once per proto_library/protobuf file). This also makes `single_output` un-usable.  It sounds to me like the `proto` attribute should be a list, rather then a single label?

**Comment by amitz** [comment]
While this is still inconvenient, #2208 somehow made it better by using an external `proto_library`. So if that's not easy to fix, I think it can be closed as `wontfix`.

**Comment by johanbrandhorst** [comment]
I don't think we have the bandwidth for this, but I'm happy to hear that you found a minor workaround
