### ISSUE TITLE
HTTPS no longer works

### ISSUE THREAD

**Issue by jeremyje** [grpc-ecosystem/grpc-gateway#220]
There's no example for HTTPS but there was https://github.com/philips/grpc-gateway-example. It no longer works with the new gRPC in TLS mode. I've tried with self signed (the example stated above) and certificates derived from a self signed CA certificate. Both give the same error.

Errors running the example.
```
2016/09/04 04:19:07 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: write tcp [::1]:57512->[::1]:10000: write: broken pipe"; Reconnecting to {"localhost:10000" <nil>}
2016/09/04 04:19:08 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
```

**Comment by MikeLeonard** [comment]
Hi I've had the same error messages trying to get https://github.com/philips/grpc-gateway-example working with a Comodo CA certificate. Just thought I'd flag that here. My certificates work fine as an ssllabs.com test passes fine when I use the certs in a node.js app I have, hence it's definitely something golang/grpc-related. I'm afraid I'm a newbie with go so can't look into in depth.

Jeremyje - In case it's helpful, I did get https working fine by just taking the main.go from the examples folder of this repo and changing http.ListenAndServe to http.ListenAndServeTLS (and entering my .crt and .key file paths in http.ListenAndServeTLS). Hope that helps.

**Comment by kalbasit** [comment]
this is caused by a regression in Go 1.7. See https://github.com/philips/grpc-gateway-example/commit/e1dfd2244c42e44a2220bfc28393f3a7d25ddc0d

**Comment by ehernandez-xk** [comment]
Now we need to explicitly enable HTTP2 when TLS is set.
This issue should be closed?

```
TLSConfig: &tls.Config{
  Certificates: []tls.Certificate{*demoKeyPair},
  NextProtos:   []string{"h2"},
},
```

**Comment by johanbrandhorst** [comment]
This should be closed
