### ISSUE TITLE
Proto_library deps are being ignored

### ISSUE THREAD

**Issue by amitz** [grpc-ecosystem/grpc-gateway#2208]
## 🐛 Bug Report

`protoc_gen_openapiv2` won't generate OpenAPI specification file for `proto_library` targets without `srcs` attribute. The official `proto_library` documentation mention:

> One usecase where srcs can be empty is an alias-library. This is a proto_library rule having one or more other proto_library in deps. This pattern can be used to e.g. export a public api under a persistent name. 

## To Reproduce
Consider the following BUILD file. I have 3 files, of whom 2 are public API to which I want to generate OpenAPIv2 specification for.

```
proto_library(
  name = "public_api1_proto",
  srcs = ["public_api1.proto"],
)

proto_library(
  name = "public_api2_proto",
  srcs = ["public_api2.proto"],
)
#
proto_library(
  name = "private_api_proto",
  srcs = ["private_api.proto"],
)

proto_library(
  name = "service_api_proto"
  deps = [":public_api1_proto", ":public_api2_proto"],
)
```

Now adding `protoc_gen_openapiv2` to to the public api target:
```
protoc_gen_openapiv2(
  name = "service_openapiv2_specification"
  proto = ":service_api_proto"
```

## Expected behavior
OpenAPI specification files get created for `public_api1.proto` and `public_api2.proto`. 

## Actual Behavior
Nothing is being generated. That's probably due to that:

https://github.com/grpc-ecosystem/grpc-gateway/blob/4bb7a7e2aae2e86f7a95b29288ab1232597b35a7/protoc-gen-openapiv2/defs.bzl#L30

Only direct sources are being collected. I quickly hack it locally using `check_deps_sources.to_list()]` to pick dependencies instead, and that solve the problem. Perhaps I can share a PR after you guys decide how exactly you want to handle that (if there's `srcs` use `srcs` and if not use `deps`?). 

## Your Environment
MacOS, Bazel 3.4.1

**Comment by johanbrandhorst** [comment]
Thanks for the bug report, would you be willing to help fix this?

**Comment by amitz** [comment]
Yea sure, but my experience with Bazel\Starlark is limited. There's 3 options here:

- proto_library is being used with srcs only:
OpenAPI specification will get generated from the referenced `srcs` files (what's currently happen).

- proto_library is being used with just deps ("public API pattern"):
OpenAPI specification will get generated from the stated `deps` targets.

- proto_library is being used with srcs and deps:
Look like this should still be handled like the first case, only referenced `src` files will get generated. 

If that works for you, the fix is quite simple, replacing ProtoInfo `direct_sources` with `check_deps_sources.to_list()` (it returns the `srcs` if there's any, else - deps).

The only part I'm not sure about is this piece of code:

https://github.com/grpc-ecosystem/grpc-gateway/blob/83d0cf2246d64b4b73fe8160a4a2083c4b7787a9/protoc-gen-openapiv2/defs.bzl#L32-L45

It checks for `proto_source_root`, an options no longer supported since Bazel 1.0. Do you still want to support version post 1.0? do you guys have tests that verify that old Bazel builds? if not - I probably need to install Bazel < 1 to verify that fix...

Thanks.

**Comment by johanbrandhorst** [comment]
CC @achew22

**Comment by amitz** [comment]
I added a PR just in case - something @achew22 can review. I did some testing with Bazel < 1.0, and it isn't really working. Your using a `rules-go` that force at least 3.X:

`Current Bazel version is 0.29.1, expected at least 3.0.0`

So to me it sounds like the Bazel < 1 code section can be removed, but again - waiting for @achew22.

**Comment by amitz** [comment]
Thank you @achew22. @johanbrandhorst, I can open another PR to remove the code that handles Bazel < 1.0 in `protoc_gen_openapiv2`, but there's a possibility there's multiple places this older version is referenced that also worth cleaning up.
