### ISSUE TITLE
Using runtime.HTTPPathPattern(ctx) returns empty pattern

### ISSUE THREAD

**Issue by shivasishdas** [grpc-ecosystem/grpc-gateway#2222]
## 🐛 Bug Report

Tried using the `runtime.WithMetadata` as per https://grpc-ecosystem.github.io/grpc-gateway/docs/operations/annotated_context/, 
```
if pattern, ok := runtime.HTTPPathPattern(ctx); ok {
			md["pattern"] = pattern // /v1/example/login
		}

```
but the `pattern` always came up as `empty`. Instead had to use the below to get the request URI.
```
if r.RequestURI != "" {
			md["uri"] = r.RequestURI
		}
```

**Comment by johanbrandhorst** [comment]
Could you share the version of the generator you're using? If you're using an older generator version the path will not have been added to the context.

**Comment by shivasishdas** [comment]
using BUF_VERSION:= 0.43.2

others,
google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0
google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.5.0
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.5.0

**Comment by johanbrandhorst** [comment]
Not sure what else the problem could be TBH. Could you share a minimal reproducible example?

**Comment by irl-segfault** [comment]
what version of the generator is supposed to enable this context annotation?  Not working for me either on all @latest

**Comment by irl-segfault** [comment]
you may just need to recreate your proto gens using the new version.  That did it for me.
