### ISSUE TITLE
Question: how to add parameters (for header parameter) to openapiv2 generated file ?

### ISSUE THREAD

**Issue by alexisvisco** [grpc-ecosystem/grpc-gateway#2223]
Hi ! 

I have a simple question: in some of my endpoints I need to explicitly say that there is a parameter in the header, I don´t mind if the gateway doesn't bind it, I just want to tell our users that this endpoint needs a key in the header. 

I saw that in the open API operation option the 'parameter' part is marked reserved, why you don't allow adding parameters, I don't understand ??

Thanks.

**Comment by johanbrandhorst** [comment]
The gateway, as you suspect, does not support parsing parameters out of the headers. We recently [added support](https://github.com/grpc-ecosystem/grpc-gateway/pull/1841) for annotating your protobuf file in a way that response headers appear in the generated OpenAPI files. Maybe you'd be interested in exploring adding something similar for input headers? There is of course a concern that allowing users to completely control the parameters will let them create OpenAPI definitions that cannot be supported by the grpc gateway, but we can look at when implementing it, if you want.

**Comment by alexisvisco** [comment]
> The gateway, as you suspect, does not support parsing parameters out of the headers. We recently [added support](https://github.com/grpc-ecosystem/grpc-gateway/pull/1841) for annotating your protobuf file in a way that response headers appear in the generated OpenAPI files. Maybe you'd be interested in exploring adding something similar for input headers? There is of course a concern that allowing users to completely control the parameters will let them create OpenAPI definitions that cannot be supported by the grpc gateway, but we can look at when implementing it, if you want.

I don't expect the gateway to parse the header from requests. I just expect that the openapiv2 protoc generator can add headers on top of responses parameters. 

The link of the pr you linked seems to provide the response headers but what about request?

Thank you for your time. :)


---------
Nothing to do with headers and all that but I am writing a protoc plugin and I saw that the protoc binary call multiples times my plugin if there is multiple packages is it normal ? 

If it is normal how do you achieve the merging open API files ?

**Comment by tmc** [comment]
One use-case I can imagine here would be if a service parses some fields out of grpc metadata fields which /are/ handled and passed along -- an extension of the openapi extensions to enable/allow some description of those fields could be useful. 

@alexisvisco is that something you'd be interested in helping out with?

**Comment by tmc** [comment]
One use-case I can imagine here would be if a service parses some fields out of grpc metadata fields which /are/ handled and passed along -- an extension of the openapi extensions to enable/allow some description of those fields could be useful. 

@alexisvisco is that something you'd be interested in helping out with?
