### ISSUE TITLE
Map in GET request

### ISSUE THREAD

**Issue by fdhadzh** [grpc-ecosystem/grpc-gateway#223]
I have proto file like this: 

```proto

service List {
  rpc ListBuckets(Request) returns (Reply) {
    option (google.api.http) = {
      get: "/v1/search"
    };
  }


message Request {
  map<string, string> filter = 1;
}

message Reply {
  repeated string results = 1;
}
```

This does not work:
```
localhost:8000/v1/search?filter[field]=value
```

How I can do request?

**Comment by yugui** [comment]
Thank you for your question.

The short answer is "No, you can do that. We don't have any plant to support that".
For longer answer, I have added a FAQ entry which describes a workaround. https://github.com/grpc-ecosystem/grpc-gateway/wiki/FAQ
