### ISSUE TITLE
Question: Is it possible to return XML data with application/xml content-type?

### ISSUE THREAD

**Issue by tuhao1020** [grpc-ecosystem/grpc-gateway#2234]
I have a grpc server which has a service that returns xml data in a string field,  is it possible to directly return the xml data with application/xml content-type through grpc-gateway?

**Comment by achew22** [comment]
@tuhao1020 please see our list of features which we have [no plan to support](https://github.com/grpc-ecosystem/grpc-gateway#no-plan-to-support). Thanks for checking us out!
