### ISSUE TITLE
protoc-gen-swagger should include optional fields

### ISSUE THREAD

**Issue by domWinter** [grpc-ecosystem/grpc-gateway#2237]
## 🚀 Feature
Hi,

when trying to generate swagger docs from proto files including the _optional_ keyword the following error message is shown:

`test.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-swagger hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--swagger_out:`

Example test.proto:

```
syntax = "proto3";
package test;

service Test {
  rpc GetTestMessage(TestMessage) returns (TestMessage);
}

message TestMessage {
  optional string test = 1;
}
```

Protoc command:

`
protoc --experimental_allow_proto3_optional  ./test/test.proto --swagger_out=logtostderr=true:./docs
`

Best regards
Dominik

**Comment by johanbrandhorst** [comment]
Hi Dominik,

Thanks for your issue. `protoc-gen-swagger` is deprecated in favour of our v2 version, `protoc-gen-openapiv2`. I recommend you change your installed version to use `protoc-gen-openapiv2`, which I believe supports this now? In any case, we probably won't fix this in v1, but I would be happy to review a fix if you're interested in doing it yourself.

**Comment by domWinter** [comment]
Hi,

thanks for the hint!

After adding a go_package option field, the following command worked (using _protoc-gen-openapiv2_):
```
protoc  ./test/test.proto --openapiv2_out=logtostderr=true:./docs
```
