### ISSUE TITLE
grpc-gateway v2 google.protobuf.FieldMask.paths contains invalid path when passing value with underscore

### ISSUE THREAD

**Issue by anthonycorbacho** [grpc-ecosystem/grpc-gateway#2239]
## 🐛 Bug Report

It seems that there is an issue while deserializing a json to the protobuf message.
I have a service that updates a list of "device" and it uses the `FieldMask`

if I do a curl with this json
```
{
   "devices":[
      {
         "name":"aname",
         "display_name":"newdisplayname"
      }
   ],
   "update_mask":"name"
}
```
there is no issue, the protobuf looks as expected.
but if I run the same curl and change the update_mask to `display_name`
```
{
   "devices":[
      {
         "name":"aname",
         "display_name":"newdisplayname"
      }
   ],
   "update_mask":"display_name"
}
```

then I get the following error
```
{
    "code": 3,
    "message": "proto: (line 8:18): google.protobuf.FieldMask.paths contains invalid path: \"display_name\"",
    "details": []
}
```

## To Reproduce
create a service with FieldMask and try to pass an argument with an underscore

eg:
```
// service
rpc BatchUpdateDevices(BatchUpdateDevicesRequest) returns (BatchUpdateDevicesResponse) {
        option (google.api.http) = {
            post: "/v1alpha1/{parent=orgs/*}/devices:batchUpdate"
            body: "*"
        };
    }

//
message BatchUpdateDevicesRequest {
    string parent = 1;
    repeated Device devices = 2;
    google.protobuf.FieldMask update_mask = 3;
}

message Device {
    string name = 1;
    string display_name = 2;
}
```

it should generate the following proto
```
type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
}
```

and set `runtime.WithMarshalerOption` to
```
runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{
			MarshalOptions: protojson.MarshalOptions{
				UseProtoNames:   true,
				EmitUnpopulated: true,
			},
}
```

## Expected behavior

`display_name` should have been correctly handled.

## Actual Behavior

curl with this body
```
{
   "devices":[
      {
         "name":"aname",
         "display_name":"newdisplayname"
      }
   ],
   "update_mask":"display_name"
}
```

result to this error
```
{
    "code": 3,
    "message": "proto: (line 8:18): google.protobuf.FieldMask.paths contains invalid path: \"display_name\"",
    "details": []
}
```

## Your Environment

Go version `go version go1.16.2 darwin/amd64`
latest grpc-gateway (`github.com/grpc-ecosystem/grpc-gateway/v2 v2.5.0`)

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I'm surprised this doesnt error when you supply "name". I don't know if you can use the update mask with a repeated field like this. Is this error happening in our custom field mask code or in the marshaler? Do you use the built-in patch feature?

If we want to be able to identify this bug, the best option would be to try and create a failing test case. If you believe the problem is with the patch feature, you can try adding a test case to https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/fieldmask_test.go. I'd be happy to help guide you, but I don't have the time to fix this myself.

**Comment by sunnyagg** [comment]
@johanbrandhorst Issue is with the snakecase. In the above examples, it works with `name` since that is single word

same api works fine if we pass mask value as camelcase

```
{
   "devices":[
      {
         "name":"aname",
         "display_name":"newdisplayname"
      }
   ],
   "update_mask":"name,displayName"
}
```

**Comment by sunnyagg** [comment]
i belive its not related to grpc gateway, seems like due to the following [check](https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/encoding/protojson/well_known_types.go#L883) in protobuf

**Comment by johanbrandhorst** [comment]
That echo's my expectation unfortunately - I think you're required to use the lower camel case format, as mentioned here: https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/encoding/protojson/well_known_types.go#L837-L840
