### ISSUE TITLE
ETCDclientv3 build error with the latest changes - github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go:114: undefined: jsonpb.Unmarshaler

### ISSUE THREAD

**Issue by Son-Lam** [grpc-ecosystem/grpc-gateway#226]
Hello,

I am haiving trouble testting ETCD latest version:

github.com/grpc-ecosystem/grpc-gateway/runtime
# github.com/grpc-ecosystem/grpc-gateway/runtime
github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go:114: undefined: jsonpb.Unmarshaler
github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go:128: undefined: jsonpb.Unmarshaler

Could you help looking onto it.

Thanks a lot,

**Comment by tmc** [comment]
@Son-Lam I suggest you upgrade your protobuf package as jsonpb is defined there. This project's build is currently clean so the problem is with your environment.

**Comment by Son-Lam** [comment]
@tmc 
Thanks a lot for your suggestion. I got the protobuf installed.

But now I got another problem with grpc 1.0.1GA breaks the balancer interface as described in "clientv3 compile fail #6529". Would you have any suggestion? How can I get the previous snashot of the not-breaking google/grpc (version 1.0.0)?

Best Regards,

**Comment by Son-Lam** [comment]
I figured out the exact github SHA and checked out the one and got it work. So GRPC team has broken the Balancer interface. Are you going to adapt to the new interface?

Best Regards,

**Comment by kris-nova** [comment]
@Son-Lam care to share this sha?
