### ISSUE TITLE
bug in processing template

### ISSUE THREAD

**Issue by vtolstov** [grpc-ecosystem/grpc-gateway#2260]
## 🐛 Bug Report

path template looks like /v1/ClientID/{ClientID}/list

## To Reproduce

after path template parsed it drops one ClientID after call Parse and Compile

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

latest grpc-gateway from master

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. Could you explain in a bit more detail what's happening. Do you have any suggestion as to why it breaks? Ideally a test that is broken would be a great starting point for a bug fix.

**Comment by vtolstov** [comment]
try adding in proto annotation path like /v2/name/{name}/create
and message that used in request like 
message Request {
  string name =  1;
}

after that parse template path /v2/name/{name}/create and check how much stuff you get

**Comment by vtolstov** [comment]
you move to internal some packages, but i can say:
call Parse https://github.com/grpc-ecosystem/grpc-gateway/blob/master/internal/httprule/parse.go#L19 for " /v2/name/{name}/create"
after that call Compile for returned compiler and check returned tpl
it must contains []string{"v2", "name","name",create"} but it contains []string{"v2", "name",create"}

**Comment by johanbrandhorst** [comment]
Interesting, so the suggestion is that having a template path with the same name as a variable breaks the template parsing? That sounds pretty bad. It also sounds like you have a test case that could be added to the Parse tests which would exercise this bug. With that start, finding a fix shouldn't be too far off! Would you be willing to contribute a fix for this?

**Comment by vtolstov** [comment]
i dont have time to fix also i'm not use grpc-gateway anymore (i'm write own trie based path processing)
