### ISSUE TITLE
go 1.16,command get install is not right

### ISSUE THREAD

**Issue by supine-win** [grpc-ecosystem/grpc-gateway#2263]
## 📚 Documentation

(A clear and concise description of what the issue is.)
go 1.16,command get install is not right
Try 'go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest google.golang.org/protobuf/cmd/protoc-gen-go@latest google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest' to install the latest version
and then 
```
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest google.golang.org/protobuf/cmd/protoc-gen-go@latest google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest 
```
show
```
go install: package google.golang.org/protobuf/cmd/protoc-gen-go provided by module google.golang.org/protobuf@v1.26.0
	All packages must be provided by the same module (github.com/grpc-ecosystem/grpc-gateway/v2@v2.5.0).
```

**Comment by johanbrandhorst** [comment]
I think this is a fundamental limitation of go Modules, and not a bug in the grpc-gateway. Please install it separately:

```
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
```
