### ISSUE TITLE
too many arguments in call to runtime.AnnotateIncomingContext

### ISSUE THREAD

**Issue by 511636330** [grpc-ecosystem/grpc-gateway#2273]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

xxx.pb.gw.go file
rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/proto.StudentInAppMessage/List", runtime.WithHTTPPathPattern("/s/messages"))

context.go file
func AnnotateIncomingContext(ctx context.Context, mux *ServeMux, req *http.Request, rpcMethodName string) (context.Context, error) 

when I run the project, errors came
too many arguments in call to runtime.AnnotateIncomingContext

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

**Comment by johanbrandhorst** [comment]
This happens if you have a newer version of the generator than the runtime library. Update the version of the runtime library dependency and this error will go away.

**Comment by 511636330** [comment]
> This happens if you have a newer version of the generator than the runtime library. Update the version of the runtime library dependency and this error will go away.

thank you very much, I'll try it

**Comment by Vincent-HD** [comment]
What is the the version of the generator without the "too many arguments in call to runtime.AnnotateIncomingContext", so without the "undefined: runtime.WithHTTPPathPattern" parameter, I'm asking that because I do not want to upgrade my runtime librairies, for now at least
