### ISSUE TITLE
How to use with gogofaster?

### ISSUE THREAD

**Issue by lx-world** [grpc-ecosystem/grpc-gateway#2274]
gateway use gogofaster?

**Comment by johanbrandhorst** [comment]
I wrote a blog post a few years ago on using GoGo protobuf with the gateway and other parts of the Go ecosystem: https://jbrandhorst.com/post/gogoproto/. It's mostly still relevant, except you have to use the v1 branch of the grpc-gateway now, as the `master` branch and v2 releases use the new APIv2, which is not compatible with gogoprotobuf.

That said, I would discourage you from using gogoprotobuf if you could at all avoid it. Hope that helps.

**Comment by lx-world** [comment]
> I wrote a blog post a few years ago on using GoGo protobuf with the gateway and other parts of the Go ecosystem: https://jbrandhorst.com/post/gogoproto/. It's mostly still relevant, except you have to use the v1 branch of the grpc-gateway now, as the `master` branch and v2 releases use the new APIv2, which is not compatible with gogoprotobuf.
> 
> That said, I would discourage you from using gogoprotobuf if you could at all avoid it. Hope that helps.

ok,  thank you
