### ISSUE TITLE
grpc-gateway_out does not entirely obey the -M parameter

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#229]
Hi,

I'm using grpc-gateway_out with the github.com/gogo/protobuf project and I came across a case where the grpc-gateway generated code is invalid when using the -M parameter to the compiler.

When using the
`google/protobuf/empty.proto`
and want to replace the generated file with one from
`github.com/gogo/protobuf/types/`
via
`grpc-gateway_out=Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types`
the generated code will import
`github.com/gogo/protobuf/types`
as expected, but the code still uses the
`empty.Empty`
to reference the Empty struct.

This results in both an unused import and an undefined reference compile error. The correct action should be to use `types.Empty` in the generated functions in this case.

**Comment by johanbrandhorst** [comment]
pinging @awalterschulze

**Comment by glenfordwilliams** [comment]
any updates on this issue? currently running into this. doing ```protoc \
	-I ./proto/ \
	-I ./vendor/ \
	-I ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	--grpc-gateway_out=grpc,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types:. \
 proto/restaurant.proto```

results in getting the proper import `"github.com/gogo/protobuf/types"`  but `empty.Empty` is being used in the generated code `	var protoReq empty.Empty`

**Comment by johanbrandhorst** [comment]
At work I wrote a post-generate workaround for this in python:

```python
def correct_grpc_gateway_imports(package):
    '''
    Workaround for https://github.com/grpc-ecosystem/grpc-gateway/issues/229.
    Replace instances of 'empty.Empty' with 'types.Empty' in any files.
    '''
    for root, dirs, filenames in os.walk(package):
        for filename in filenames:
            with open(os.path.join(root, filename), 'r') as f:
                file_contents = f.read()

            file_contents = file_contents.replace('empty.Empty', 'types.Empty')

            with open(os.path.join(root, filename), 'w') as f:
                f.write(file_contents)
```

**Comment by awalterschulze** [comment]
Is there any plan to properly fix this?

**Comment by achew22** [comment]
@awalterschulze, at this point I don't use gogoproto and so it isn't at the top of my priority queue. It is definitely a correctness issue, but I won't have the cycles to fix it. I don't think it would be extremely difficult to fix in the generator.

1.  Enhance the [flag parsing](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/main.go#L49) to handle the additional `M.*=.*` args.
2.  Enhance [the registry](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/descriptor/registry.go#L42:6) to register these mappings.
3.  Use those new mappings when rendering (there are a bunch of ways to do that and I'd leave it up to the implementer to decide which one to use)

**Comment by awalterschulze** [comment]
How is the `Empty` message and other well known messages currently working with golang/protobuf without using the `-M` parameter?
Are you simply hardcoding the paths?

**Comment by Mistobaan** [comment]
@achew22 why you don't use gogoproto? any particular reason?

**Comment by achew22** [comment]
I haven't had any need for it yet and I like to keep things as close to
stock as possible unless I have a good reason to deviate from the norm.

When that time comes I will definitely investigate, but right now I'm doing
fine without.

**Comment by ivanovaleksey** [comment]
Hi, as far as I can see the issue is still present?

**Comment by johanbrandhorst** [comment]
It is still an issue. Would you be interested in contributing a fix?

**Comment by ivanovaleksey** [comment]
Yes, I am interested though I am very newbie in dealing with proto files and definitions.
I looked at #647, there is no very much code there. I wonder is it still actual :)

**Comment by johanbrandhorst** [comment]
I think that should be a good start, but we will need permission from @Mistobaan if we want to merge that code verbatim.

**Comment by jijoxvr** [comment]
Try this
`--grpc-gateway_opt=Mgrpc-gateway_out=Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types`
