### ISSUE TITLE
URL path parameters should be non mandatory to be present in request message for method for OAS

### ISSUE THREAD

**Issue by akiagarwal** [grpc-ecosystem/grpc-gateway#2297]
## 🚀 Feature
Hi ,

As per my understanding of how GRPC-gateway works for generating OAS2 spec from the proto file in case of path parameters in URL is that it expects those path parameters to be always present in the request message as well.
There are cases where we dont include the path parameter in the proto request message and also where the method does not have any request at all but has path parameters. In these cases the swagger generation fails. 
Also there are cases where the path parameter is still sent as part of the request i.e it needs to be displayed both as a path parameter and also as a parameter in the request body , and the current implementation doesnt allow that as it will not show the path parameters as part of the request in the spec.
Dont know if i am missing something or my understanding is wrong but if that is the case then i think path parameters can be made non mandatory in request message and this will solve the above problems.

Please correct me if i am wrong here.
Thanks.

**Comment by johanbrandhorst** [comment]
I'm confused, I definitely wouldn't expect parameters to be in both the path and the body, what gives you that impression?

**Comment by akiagarwal** [comment]
@johanbrandhorst well thats a corner case and more than that a wrong practise , but thats not my original ask. My main point is that path parameters are mandatory to be present in the proto request message which causes an issue if the method takes no request or the request message does not mention those parameters. I dont see any need to define you path parameter keys as part of the proto message also (except for determining their type).

**Comment by johanbrandhorst** [comment]
I see. Well that's part of the http.proto spec I believe, which is the contract the grpc-gateway implements. How else would you determine the types of the path parameters?

**Comment by akiagarwal** [comment]
@johanbrandhorst the http.proto contains the annotations that the grpc-gateway uses . For the path parameters all i am trying to say is that making it mandatory for them to be present in the request message creates a problem because as i said its not always necessary that a method has an input request. If the request message is present and it contains the path parameter then great , but of its not present then the swagger generation should not be blocked - the type can be considered as string. Or there should be some other way by which the user can specify the type of their path parameters and need not have them in the proto request.

**Comment by johanbrandhorst** [comment]
Could you give me an example of a use case where you have "no input request" but still have path parameters? I don't think I understand how this could be. Surely any path parameters means you have an input?

**Comment by akiagarwal** [comment]
@johanbrandhorst For a very simple case consider an endpoint which takes in an ID as a path parameter as the only input and returns response based on that ID. Now in this case there is no need of any request body and hence no input type and it just has a path parameter. In such cases since the path parameters are not present in input request message the swagger generation fails.

rpc GetUser (google.protobuf.Empty) returns (UserNameByIDResponse) // URI: /v1/user/{ID}
The above endpoint needs no request.

**Comment by johanbrandhorst** [comment]
This is not describing a valid Protobuf contract, of course the generation fails. If this is the feature request, I'm going to go ahead and close this because we're not changing the underlying spec of protobuf or google.api.http.

**Comment by akiagarwal** [comment]
Well i dont understand why is that not a valid protobuf method?

**Comment by johanbrandhorst** [comment]
Because the ID is part of a request input, and all request imports are described in the input message. You cannot have an input message of `google.protobuf.Empty` and still want to have the path parameter. It has to be in the message.

**Comment by akiagarwal** [comment]
Right, but isnt that more like a recommendation and not a laid out convention. Because I can still get my path parameters with no need of an input request , and except for backward incompatibility issues i dont see any problem in doing so. Now because that is always a possibility , I believe that  users should not be blocked from using it because of it. Sorry for troubling you but I still think swagger generation should be handling that and not enforcing it.

**Comment by johanbrandhorst** [comment]
No, it's not a recommendation or convention, it's impossible to send that ID to the gRPC service that the grpc-gateway fronts. It is not supported by gRPC, Protobuf or the google.http.api spec that we support. I think there is a fundamental misunderstanding in your model of the grpc-gateway if you think this should work. How would you send that ID to the backing gRPC service?

**Comment by akiagarwal** [comment]
So i was specifically talking about HTTP services , where the path parameters can be determined from the router like mux.Vars or whatever router is being used. For gRPC I can understand what you are trying to say as gRPC services will get the request json only whereas HTTP based services can still find the path parameters from the URL.
