### ISSUE TITLE
Serving swagger.json from runtime mux?

### ISSUE THREAD

**Issue by philipithomas** [grpc-ecosystem/grpc-gateway#230]
It seems that the best practice for serving a swagger.json is to do it at the apex of the API. However, the runtime does not seem to easily support this. 

Is there a best practice for this? Does it make sense to create a custom handler for the swagger here?

**Comment by johanbrandhorst** [comment]
https://coreos.com/blog/gRPC-protobufs-swagger.html has a pretty cool example of how to set up your swagger definitions on top of your API server.

**Comment by philipithomas** [comment]
@johanbrandhorst That was actually really easy follow. Maybe I'll PR it into the README

**Comment by mikeatlas** [comment]
Came here wondering the same, also actually read the CoreOS post when I was attempting to serve up the `swagger.json` file. However, I run into issue hosting it - seems like the HTTP/2 mux doesn't like serving regular HTTP requests? 
`http2Server.HandleStreams received bogus greeting from client: "GET /swagger.json HTTP"`
and then the connection is reset. 

My gRPC-gateway code looks straightforward enough, especially just trying to serve up an empty `{}` endpoint:
```
   	mux := runtime.NewServeMux()
	opts := []grpc.DialOption{grpc.WithBlock(),
		grpc.WithInsecure(),
		grpc.WithTimeout(time.Millisecond * 1500)}
	err := grpcapi.RegisterServiceHandlerFromEndpoint(
		ctx, mux, "localhost:16384", opts)
	if err != nil {
		return err
	}

	swaggerMux := http.NewServeMux()
	swaggerMux.HandleFunc("/swagger.json", func(w http.ResponseWriter, req *http.Request) {
io.Copy(w, strings.NewReader(`{}`))
	})
	swaggerMux.Handle("/", mux)
```

@philipithomas @johanbrandhorst did either of you actually manage to serve the swagger JSON like in the blog post?

**Comment by mikeatlas** [comment]
Actually it looks like I just missed this part,
```
if r.ProtoMajor == 2 && strings.Contains(r.Header.Get("Content-Type"), "application/grpc") {
			grpcServer.ServeHTTP(w, r)
		} else {
			otherHandler.ServeHTTP(w, r)
		}
``` - that looks about right. Will edit this post again if that was the missing sauce.

**Comment by mikeatlas** [comment]
Hm, okay so I'm not using `ListenAndServeTLS` and there's a bunch of comments about Go 1.7 changing HTTP/2 related services. It's not very easy to serve two protocols from the same service, it seems. Doable, but risky since it appears to break across Go versions due to the newer HTTP/2 ...

**Comment by campoy** [comment]
For anyone looking into this issue and finding the link is broken, apparently CoreOS changed their blogging system and now it's case sensitive!

You can still find the post: https://coreos.com/blog/grpc-protobufs-swagger.html

**Comment by johanbrandhorst** [comment]
Thanks Francesc, I've updated my link 😄.

**Comment by vectorman1** [comment]
The link seems broken again, and this issue is the first thing that comes up when you search up `host swagger grpc-gateway` or related, so can we get an updated one? Thanks.

**Comment by johanbrandhorst** [comment]
Updated the link again to https://grpc.io/blog/coreos/
