### ISSUE TITLE
Forgotten PR #1968

### ISSUE THREAD

**Issue by alperengozeten** [grpc-ecosystem/grpc-gateway#2301]
## 🚀 Feature
Hi,

PR #1968 was a solution to the problem mentioned in #877. As I see this PR is not merged since February, so I assume it is forgotten. I'm currently trying to generate server stubs and models from the OpenAPI, so the names of the models matter to me. It would be great if we have the option of more concise names for models instead of prefixing the last part of the package name. Thanks.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. I would be happy to review an update of #1968 and have it merged into our code. Maybe you could take that branch, rebase it on `master` and create a new PR? As long as we can get @misberner to consent to the code being merged it should be okay :).

**Comment by alperengozeten** [comment]
I tried to rebase the PR in the master but when I run the main_test.go, I get the following output

`=== RUN   TestParseReqParam
--- PASS: TestParseReqParam (0.00s)
=== RUN   TestParseReqParam/Test_0
    --- PASS: TestParseReqParam/Test_0 (0.00s)
=== RUN   TestParseReqParam/Test_1
    --- PASS: TestParseReqParam/Test_1 (0.00s)
=== RUN   TestParseReqParam/Test_2
    --- PASS: TestParseReqParam/Test_2 (0.00s)
=== RUN   TestParseReqParam/Test_3
    --- PASS: TestParseReqParam/Test_3 (0.00s)
=== RUN   TestParseReqParam/Test_4
    --- PASS: TestParseReqParam/Test_4 (0.00s)
=== RUN   TestParseReqParam/Test_5
    --- PASS: TestParseReqParam/Test_5 (0.00s)
=== RUN   TestParseReqParam/Test_6
    --- PASS: TestParseReqParam/Test_6 (0.00s)
=== RUN   TestParseReqParam/Test_7
    --- PASS: TestParseReqParam/Test_7 (0.00s)
=== RUN   TestParseReqParam/Test_8
    --- PASS: TestParseReqParam/Test_8 (0.00s)
=== RUN   TestParseReqParam/Test_9
    --- PASS: TestParseReqParam/Test_9 (0.00s)
=== RUN   TestParseReqParam/Test_10
    --- PASS: TestParseReqParam/Test_10 (0.00s)
=== RUN   TestParseReqParam/Test_11
    --- PASS: TestParseReqParam/Test_11 (0.00s)
=== RUN   TestParseReqParam/Test_12
    --- PASS: TestParseReqParam/Test_12 (0.00s)
PASS
panic: unexpected call to os.Exit(0) during test

goroutine 1 [running]:
os.Exit(0x0)
	C:/Program Files/Go/src/os/proc.go:68 +0x74
main.main()
	_testmain.go:43 +0x153`

It seems like it passes all 12 tests, however, it throws panic at the end of the tests. I also tried to paste the changes one by one after forking the grpc-gateway repo, but still the same result. I couldn't really find the possible origin of this error. Do you have any idea about any possible reason for this error? Thank you.

The PR I created (which fails main_test.go) https://github.com/alperengozeten/grpc-gateway/tree/naming-strategy

**Comment by johanbrandhorst** [comment]
Curiously, the tests run just fine on my machine. I wonder if this is perhaps a windows thing 🤷🏻? I'm happy to hear that your interest in the project is leading you to learn about Go 🤗. Anyway, would you like to open this branch as a PR and we can take it from there?

**Comment by alperengozeten** [comment]
Thank you, that was the issue, I'm running on a Windows machine. I just opened a PR, #2310. Thanks again.
