### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by brumhard** [grpc-ecosystem/grpc-gateway#2302]
## 📚 Documentation

It would be great to add further documentation to https://grpc-ecosystem.github.io/grpc-gateway/docs/operations/health_check/ and add the example discussed in #1977.

Furthermore the combination of both would be nice to have one http endpoint on the gateway that calls the `check` method on the grpc server to really have a meaningful result for the health of the whole service.

If possible it would also be nice if it could be added to the options in `runtime.NewServeMux` like `WithHealthCheckEnabled(conn *grpc.ClientConn)`, to activate a "healthz" route with the described behaviour. I would guess that the need for healthchecks should be common enough for that.
If you think it shouldn't be integrated in this place, maybe there's also another place where this could fit in.

**Comment by johanbrandhorst** [comment]
Sounds great, would you be willing to help contribute this?

**Comment by brumhard** [comment]
Sure I'll be happy to look into this 👍

**Comment by brumhard** [comment]
Just like PR still stuck in bureaucracy...
