### ISSUE TITLE
Question: Any plan to support ServerInterceptor when using RegisterXXXServer?

### ISSUE THREAD

**Issue by Masterlvng** [grpc-ecosystem/grpc-gateway#2308]
As we know，in RegisterXXXServer, it calls the server method directly without executing interceptors in server.
In many cases,  server methods should rely on some interceptors, like server auth etc.

So, if any plan to support ServerInterceptor?

just like below, pass the interceptor when registering server and execute in it.
```go
func RegisterYourServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server YourServiceServer, interceptor grpc.UnaryServerInterceptor) error 
```

Thx

**Comment by johanbrandhorst** [comment]
There's no plan to implement this. The implementation avoids the use of gRPC altogether already. If you want to add middleware-like functionality to this, you can wrap the `mux` in any `http.Handler` type middleware before serving it.
