### ISSUE TITLE
support forward proxy

### ISSUE THREAD

**Issue by majorinche** [grpc-ecosystem/grpc-gateway#2312]
dear support,
    Can we support forward proxy in the grpc-gateway, like in linux, we do it like
setting "export http_proxy=xxx", and then curl some website directly.

and how to configure this proxy?

thanks
majorin

**Comment by johanbrandhorst** [comment]
Hi,

This sounds strictly outside the intended uses of the grpc-gateway. Maybe you want a [Go standard library reverse proxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy)?
