### ISSUE TITLE
Requesting new release of grpc-gateway containing "optional_nullable" option

### ISSUE THREAD

**Issue by srowles** [grpc-ecosystem/grpc-gateway#2326]
## 🚀 Feature

We would like to make use of this merged PR:

https://github.com/grpc-ecosystem/grpc-gateway/pull/2215

However we only make use of actual releases, we can't just use "master".

Can we get a new release which includes the PR so we can pick up this change.

Thank you.

**Comment by johanbrandhorst** [comment]
[v2.6.0](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.6.0) has been released :).
