### ISSUE TITLE
grpc-gateway is removing the Content-Type MIME info before it sends to the client

### ISSUE THREAD

**Issue by cjingadegithub** [grpc-ecosystem/grpc-gateway#2330]
## 🐛 Bug Report

Description:
------------
We are setting http header key “Content-Type” value to “application/json; charset=utf-8” in our code.
This is golang code and using grpc-gateway library to provide REST API to gRPC function.
But still response header is not set to as expected and getting only “application/json”.

GRPC Version : 1.14.6
-------------
Below is the golang code snipped for ref:
-----------------------------------------
func httpGrpcRouter(grpcServer *grpc.Server, httpHandler http.Handler) http.Handler {
   return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
      w.Header().Set("X-Content-Type-Options", "nosniff")
      w.Header().Set("Content-Type", "application/json; charset=utf-8")
      w.Header().Set("Grpc-Metadata-Content-Type", "application/grpc; charset=utf-8")
      if r.ProtoMajor == 2 && strings.Contains(r.Header.Get("Content-Type"), "application/grpc") {
         grpcServer.ServeHTTP(w, r)
      } else {
         httpHandler.ServeHTTP(w, r)
      }
   })

(Write your steps here:)

Request sent with ("Content-Type", "application/json; charset=utf-8")
Response received with ("Content-Type", "application/json")

## Expected behavior

grpc-gateway should not remove the Content-Type MIME info, in particularly "charset=utf-8"

## Actual Behavior

grpc-gateway is removing the Content-Type MIME info ("charset=utf-8") before it sends to the client.

## Your Environment

GRPC Version : 1.14.6
Golang version : 1.15.7

**Comment by johanbrandhorst** [comment]
Hi, thank you for your bug report. I think we unconditionally set this field depending on the defined content-type of the marshaler, as you can see here: https://github.com/grpc-ecosystem/grpc-gateway/blob/fbb11e42d2b0a6e8da52de238be394166cf31e30/runtime/handler.go#L156-L157. If you want a different content-type header, you should probably just create your own marshaler which returns this content-type from the ContentType method. You can create a new one by wrapping the existing one, see https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#customize-unmarshaling-per-content-type for a quick example of how to configure your own marshaler. I think that should allow you to create a marshaler which sets the desired content-type.
