### ISSUE TITLE
Duped field with snake_case and camelCase started to return error from v2

### ISSUE THREAD

**Issue by ttyfky** [grpc-ecosystem/grpc-gateway#2340]
## 🐛 Bug Report

An error is started to be returned from v2.0.0 when request message has snake_case and camelCase in the same request message. This was fine until v1.16.0.

Having snake_case and camelCase for the same fields sounds a bit weird, but a push request of GCP Pub/Sub actually does as follow. Given this restriction, receiving GCP Pub/Sub via grcp-gateway becoming a bit tricky.

https://cloud.google.com/pubsub/docs/push#receiving_messages
```
{
    "message": {
        "data": "..."
        "messageId": "2070443601311540",
        "message_id": "2070443601311540",
        "publishTime": "2021-02-26T19:13:55.749Z",
        "publish_time": "2021-02-26T19:13:55.749Z",
    },
   "subscription": "projects/myproject/subscriptions/mysubscription"
}
```

Error returned:
```
{
    "code": 400,
    "message": "proto: (line 8:9): duplicate field \"messageId\"",
    "details": []
}
```

## To Reproduce
* grpc-gateway version: v2.15.0

* Proto message of the request
  * dropping some fields from [original message](https://github.com/googleapis/googleapis/blob/7b6a2ceed6cacf676b3918b1703b3ddd6322444c/google/pubsub/v1/pubsub.proto#L219)
```
service DemoService {
   rpc PubSubPushNotification(PubSubPushNotificationRequest) returns (PubSubPushNotificationResponse) {
    option (google.api.http) = {
      post: "/pubsub/notification"
      body: "*"
    };
  }
}
message PubSubPushNotificationRequest {
  message Message {
    string data = 1;
    string message_id = 2;
  }
  Message message = 1;
  string subscription = 2;
}
mesage PubSubPushNotificationResponse{}
```

* MarshalerOption
  * Expecting snake_case by default
```
runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.HTTPBodyMarshaler{
	Marshaler: &runtime.JSONPb{
		MarshalOptions: protojson.MarshalOptions{
			UseProtoNames:   true, 
			EmitUnpopulated: false,
		},
		UnmarshalOptions: protojson.UnmarshalOptions{
			DiscardUnknown: true,
		},
	},
}),
```

* Sample request
  * Sending the request to an endpoint with request message above
```
curl --request POST '${HOST}/pubsub/notification' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": {
        "data": "foo",
        "message_id": "2070443601311540",
        "messageId": "2070443601311540",
        "publishTime": "2021-02-26T19:13:55.749Z",
        "publish_time": "2021-02-26T19:13:55.749Z"
    },
    "subscription": "projects/myproject/subscriptions/mysubscription"
}'
```

## Expected behavior

Accept filed with expecting format (which is in json tag of struct), and ignore additional fields.

## Actual Behavior

Returns dup error

**Comment by johanbrandhorst** [comment]
I think this is the behavior of our marshaler, the official Go JSON marshaler: https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson. You can create your own marshaler that will accept these, but there isn't much we can do in the gateway to circumvent this issue.

**Comment by ttyfky** [comment]
Ahh right, this would be caused by the behavior change of the marshaler where grpc-gateway doesn't have a control...

Thanks for the response.
