### ISSUE TITLE
How is etcd compatible？

### ISSUE THREAD

**Issue by why444216978** [grpc-ecosystem/grpc-gateway#2348]
I use github.com/coreos/etcd/v3 client，that must use google.golang.org/grpc@v1.26.0，but grpc-gateway must use google.golang.org/grpc@v1.40.0 to work，how to generate V1 pb.gw.go？
![image](https://user-images.githubusercontent.com/29140252/133970561-348b7395-91b9-402a-b578-1080df914324.png)

**Comment by why444216978** [comment]
![image](https://user-images.githubusercontent.com/29140252/133970791-a3732f71-a58e-4d15-aadc-5d06adb937f9.png)

**Comment by johanbrandhorst** [comment]
You'll need to use the v1 releases to work with etcd. You're trying to use V2, unfortunately etcd hasn't updated their Protobuf dependencies yet.
