### ISSUE TITLE
The register function always returns nil.

### ISSUE THREAD

**Issue by developerdong** [grpc-ecosystem/grpc-gateway#2362]
https://github.com/grpc-ecosystem/grpc-gateway/blob/ece6fbbd7ed5ab750ebce98554b1d9098a17076e/examples/internal/helloworld/helloworld.pb.gw.go#L1211

Hi, I am confused why the generated function literal includes returning an error, but actually the error is always nil.
Is this caused by negligence, or for backward compatibility? Should we change the function literal?

**Comment by johanbrandhorst** [comment]
Ha, interesting! It may have been missed when this functionality was originally implemented, but we can't change it now without breaking users, so nothing to do here.
