### ISSUE TITLE
allow responding with http status 204

### ISSUE THREAD

**Issue by ericlagergren** [grpc-ecosystem/grpc-gateway#240]
google.protobuf.Empty indicates an empty JSON response. I'd _prefer_ to send a 204 for services that respond with google.protobuf.Empty.

Right now all I could come up with is adding a `WithForwardResponseOption` and checks the message's type and calls `WriteHeader(http.StatusNoContent)` if the message is `*empty.Empty`.

This causes the call to `w.Write` (https://github.com/grpc-ecosystem/grpc-gateway/blob/7ba755f85a3dc73224047317dab675b32d3a91e0/runtime/handler.go#L115) to print an error.

Technically it all works, but it feels hacky.

**Comment by tmc** [comment]
It does seem like this should be achievable in a fairly clean fashion.

@EricLagergren what's the error that subsequent Write generates?

**Comment by EricLagergren** [comment]
No error is returned, instead one is printed out. (See: https://golang.org/src/net/http/server.go#L879)

**Comment by afking** [comment]
@tmc is there currently no way to propagate HTTP 2** status codes to the rest proxy?
