### ISSUE TITLE
Chunked data from server side streaming is coming in network response preview tab once all the chunked data is received

### ISSUE THREAD

**Issue by KrishnaAnanthi** [grpc-ecosystem/grpc-gateway#2400]
## 🐛 Bug Report

When using grpc-gateway server side streaming is not happening. In web browser i am receiving all the data together. 

## To Reproduce

I have taken grpc gateway example ListFeatures Post API call for server side streaming using python. In the python code i have added a sleep so achieve the delay so that streaming can be visible in UI. 
![image](https://user-images.githubusercontent.com/5318326/138422893-661e3a82-0415-4a8f-9ccc-715ddbd8779a.png)

I have added grpc-gateway server using go.

I have created an angular client which call HTTP post endpoint for listfeature. (localhost:8080/ListFeature)
![image](https://user-images.githubusercontent.com/5318326/138421821-2c966745-cbdf-4b66-b727-80e4ddb41053.png)

When the request is being made i am getting http 200 immediately and it wait for 10s and once it receives all data, response is being displayed in browser response tab.

## Expected behavior

Since its server side streaming, i am expecting chunked data to be displayed in http response tab as soon as browser receives it. So that once i receive a chunk i can update the data in UI.

 In client side i have used angular observables so that streams can be handled. subscribe method needs to be called for every chunk

## Actual Behavior

Browser displays the data once all the chunked data is being received.
In network response preview tab, data comes after 10s only.
Also subscribe method is called only once it receives all data.

![stream4](https://user-images.githubusercontent.com/5318326/138422124-db088dae-910c-465f-b99c-bddb68de4f82.png)
![satream3](https://user-images.githubusercontent.com/5318326/138422134-fe539fba-9d12-41b1-997f-5b056213e0e6.png)
![stream](https://user-images.githubusercontent.com/5318326/138422139-82bcacef-7d96-4ab3-8c48-ad7e9d4b4752.png)
![stream2](https://user-images.githubusercontent.com/5318326/138422149-17761abb-7359-4fd7-9529-654660b539a8.png)
.

## Your Environment

(Environment name, version and operating system.)
Debian 10 OS
Python  3.9.2
Go 1.17.2

**Comment by KrishnaAnanthi** [comment]
I am able to get it working with fetch. Thanks

**Comment by johanbrandhorst** [comment]
Glad to hear it!

**Comment by Manveer695** [comment]
@KrishnaAnanthi Can you please post the UI code snippet on how did you make it work with fetch, i am facing the same issue as you faced earlier.

**Comment by Manveer695** [comment]
anyone else if facing this issue, please check this link - https://stackoverflow.com/questions/62121310/how-to-handle-streaming-data-using-fetch
