### ISSUE TITLE
duplicate annotation error when the same endpoint is used by two different services

### ISSUE THREAD

**Issue by aronrichter** [grpc-ecosystem/grpc-gateway#2411]
## 🐛 Bug Report
When two different services have the same endpoint annotation, is not possible to generate the protogen files

## To Reproduce
service.proto file
```
service MyServiceNumberOne {
  rpc GetHealth(GetHealthRequest) returns (GetHealthResponse) {
    option (google.api.http) = {
      get : "/api/v1/health"
    };
  }
}

service MyServiceNumberTwo {
  rpc GetHealth(GetHealthRequest) returns (GetHealthResponse) {
    option (google.api.http) = {
      get : "/api/v1/health"
    };
  }
}

message GetHealthRequest {}
message GetHealthResponse {}
```

## Expected behavior
The expected behavior would be to generate the protogen files without error

## Actual Behavior
```
Failure: failed to map insertion points: unexpected response error: duplicate annotation: method=GET, template=/api/v1/health.
```

## Your Environment
go 1.17
grpc-gateway 2.6.0

## Aditional information
Searching about this error, I found this [issue](https://github.com/grpc-ecosystem/grpc-gateway/issues/1865) that might be the reason for this behavior, but I'm not sure about it.

**Comment by johanbrandhorst** [comment]
Whoops, that was likely introduces in that PR, yeah. Thanks for submitting a PR to fix it!
