### ISSUE TITLE
header list size violation on large JWT headers

### ISSUE THREAD

**Issue by clatko** [grpc-ecosystem/grpc-gateway#2417]
## 🐛 Bug Report

I get the error `header list size to send violates the maximum size (8192 bytes) set by server` with large headers.

## To Reproduce

(Write your steps here:)

Step 1: Follow the tutorial here - https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/ 

Step 2: Send a curl request with a large JWT header:
```
curl -X POST -k http://localhost:9999/jwt/users -d '{"user_type": 1}' --header 'authorization: Bearer <VERY_LARGE_BUT_VALID_JWT>'
```

## Expected behavior

I should get the list of users.

## Actual Behavior

I get error - `header list size to send violates the maximum size (8192 bytes) set by server`

## Your Environment

OSX (Monterey)
Apple M1

## Notes:

Adding the following DialOption does not work:
```
	opts := []grpc.DialOption{
		grpc.WithInsecure(),
		grpc.WithMaxHeaderListSize(math.MaxUint32),
	}
```

There was an issue with this in grpc/grpc-go that has been resolved - https://github.com/grpc/grpc-go/pull/2084

I updated to the newer version - v1.42.0 - but this still did not work.

The http2_client.go is indeed getting the `maxSendHeaderListSize`, but when making a curl request through the gateway, stream.go is creating a new client stream in transport, which is extracting the `maxSendHeaderListSize` option from the server config. The default of which is 8192 bytes.

There does not seem to be a way to modify the server configuration.

**Comment by johanbrandhorst** [comment]
Hi, thanks for the issue!

I'm confused - are you saying that a `grpc.ClientConn` created before instantiating the gateway is not obeying the dial options when the gateway uses it? Or is the gateway doing something wrong? I think we need some more details. What does the server configuration have to do with it?

**Comment by clatko** [comment]
I'm new to Golang so don't have a solid grasp of what is happening, the error is happening here - https://github.com/grpc/grpc-go/blob/aaff9e7ab90624f6be3da4555eeb27c68ba29e9d/internal/transport/http2_client.go#L731 - it appears a new client stream is created with the default header size. The error message says the value is set by the server.

The Protobuf is creating a new client stream with the dial options but I don't see a way to pass those dial options through the gateway-generated Protobuf.

Initially, I was assuming the server was involved, but looking at it again with fresh eyes, I think the error message is misstating where the header value is coming from.

**Comment by johanbrandhorst** [comment]
I think you're going to have to raise this issue against gRPC-Go - there's nothing about the grpc-gateway that's wrong here as far as I can tell. The gateway is a very small client wrapping the gRPC-Go client, so it's very unlikely that the error is in our code. Please report back if it does indeed turn out to be a gateway issue!

**Comment by clatko** [comment]
I believe the generated gateway Protobuf is not allowing the grpc dial options through. In the code, the call from pb.gw.go looks like:
`stream, err := client.ModelQueryApi(ctx, &protoReq)`
and the receding end of this is in pb.go:
`func (c *userQueryServiceClient) client.ModelQueryApi(ctx context.Context, in *model_request.ModelRequest, opts ...grpc.CallOption)`

If opts could be passed through here, it would solve the issue. I can manipulate the produced pb.gw.go code to see if this indeed solves the issue.

But overall, I think you are right and any stream should be respecting the http2 client settings so the best fix is in gRPC-Go. I'll investigate a little further and provide an update.

**Comment by johanbrandhorst** [comment]
If you need to provide grpc.CallOptions you can specify them in your dial options using https://pkg.go.dev/google.golang.org/grpc#WithDefaultCallOptions. If it's a dial option, you can specify it when dialling. I don't see anything the gateway can do differently here, but please let me know if I'm missing something!

**Comment by nicklas-delphai** [comment]
I just had the same issue and it wasn't a problem with neither `grpc-gateway` nor `grpc-go`.

I'm using `grpc-gateway` to proxy to a python grpc server. As it turned out the blocking factor was the python grpc server. Configuring `grpc.aio.server` did the trick:

```py
import grpc.aio

server = grpc.aio.server(options=[("grpc.max_metadata_size", 2**14)])
```

If you use a different server language, I would recommend to google for something like `max_header_list_size YOUR LANGUAGE grpc`.
