### ISSUE TITLE
examples: remove usage of `WithBlock` in examples

### ISSUE THREAD

**Issue by alissa-tung** [grpc-ecosystem/grpc-gateway#2425]
## 📚 Documentation

ref: https://github.com/grpc/grpc-go/pull/4858

**Comment by johanbrandhorst** [comment]
I guess that makes sense. Would you be willing to contribute a fix for this?

**Comment by johanbrandhorst** [comment]
As mentioned in #2428, I'm not convinced anymore that we want to make this change. Sorry to have wasted your time :(.
