### ISSUE TITLE
Replace abandoned ghodss/yaml with supported sigs.k8s.io/yaml package

### ISSUE THREAD

**Issue by numbsafari** [grpc-ecosystem/grpc-gateway#2427]
## 🚀 Feature

This package still relies on the (long) abandoned [`ghodss/yaml`](https://pkg.go.dev/github.com/ghodss/yaml) package. The kubernetes maintainers have created a maintained fork of that package ([`sigs.k8s.io/yaml`](https://pkg.go.dev/sigs.k8s.io/yaml)).

Switching to a maintained/supported package would make bug fixes and dependency updates available to this package, and its consumers as well.

**Comment by johanbrandhorst** [comment]
Sounds great, would you be willing to contribute a fix for this?
