### ISSUE TITLE
How to manually invoke EOF for client-side streaming?

### ISSUE THREAD

**Issue by ssm951** [grpc-ecosystem/grpc-gateway#2434]
## 📚 Documentation

I have been taking a look at the integration tests and documentation, but could not find anywhere on what message I need to send for dec.Decode() to return an EOF. Below is the generated code calling dec.Decode (adjusted for privacy):
```
func request_Echo_clientStream_0(ctx context.Context, marshaler runtime.Marshaler, client EchoClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var metadata runtime.ServerMetadata
	stream, err := client.clientStream(ctx)
	if err != nil {
		grpclog.Infof("Failed to start streaming: %v", err)
		return nil, metadata, err
	}
	dec := marshaler.NewDecoder(req.Body)
	for {
		var protoReq ClientStreamRequest
		err = dec.Decode(&protoReq)
		if err == io.EOF {
			break
		}
		if err != nil {
			grpclog.Infof("Failed to decode request: %v", err)
			return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
		}
		if err = stream.Send(&protoReq); err != nil {
			if err == io.EOF {
				break
			}
			grpclog.Infof("Failed to send request: %v", err)
			return nil, metadata, err
		}
	}

	if err := stream.CloseSend(); err != nil {
		grpclog.Infof("Failed to terminate client stream: %v", err)
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		grpclog.Infof("Failed to get header from client: %v", err)
		return nil, metadata, err
	}
	metadata.HeaderMD = header

	msg, err := stream.CloseAndRecv()
	metadata.TrailerMD = stream.Trailer()
	return msg, metadata, err

}
```

The reason why I need this is that I am trying to use the grpc-websocket-proxy as a wrapper to the grpc-gateway, and think that this is the knowledge needed to successfully implement client-side streaming using websockets. Currently, the issue is that the grpc-gateway client would not call CloseAndRecv() until it gets an EOF, therefore unable to get the response back from the server. Any ideas or thoughts on that?

Thanks in advance!

**Comment by johanbrandhorst** [comment]
Hm, `req.Body` should return io.EOF when there is no more body to be read. Judging by [the source](https://github.com/tmc/grpc-websocket-proxy/blob/e5319fda780223b9d4d06dba2059a26ebff67b8a/wsproxy/websocket_proxy.go#L215-L219), it seems to be triggered by the context cancellation, which in turn I think is triggered by ending the request on the client side. What does your client look like?

Also CC @tmc, author of grpc-websocket-proxy 😄.

**Comment by ssm951** [comment]
Yeah, so the client is implemented using the [browser's WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). Unfortunately, it can only send messages to the server, or close the whole connection. I'm thinking that maybe I can modify the code so if an empty or null message gets sent, it closes the client side stream and allow grpc-gateway to call CloseAndRecv()

**Comment by johanbrandhorst** [comment]
Ah, you want to close _and_ receive the last response? Yeah not sure how to do that.

**Comment by ssm951** [comment]
I have spent a lot of time researching this, and it seems that Websockets is still the only viable way in doing client-side streaming on the browser until the fetch API is more readily available. I'm trying to modify grpc-websocket-proxy to close the client-side stream, and am successfully able to do it. Unfortunately, I haven't figured out how to only close that pipe and leave the server response pipe open. @tmc any ideas?

**Comment by johanbrandhorst** [comment]
Have you investigated https://github.com/improbable-eng/grpc-web? It also uses websockets to allow client side streaming and might allow full duplex control.

Also, what are you trying to do? Client side streaming in the browser usually means uploading files, and there are more performant ways to do that than using websockets.

**Comment by ssm951** [comment]
What we are doing is streaming raw audio from the browser and returning a response from the server based on the audio. Since the audio can be long, it is quicker to stream the audio to the server and process it there than to create an audio file and upload it to the server.

I did look at that before. I did not know they allowed client-side streaming. Their documentation said they don't support it: https://github.com/improbable-eng/grpc-web#client-side-streaming

**Comment by ssm951** [comment]
Interesting, after digging deeper, it seems that they [do support it using websockets](https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web/docs/transport.md#socket-based-transports). Not sure why they didn't mention it in the main README. I'll take a look at it.

**Comment by johanbrandhorst** [comment]
I happen to be a maintainer of that repository too 😁. The reason websockets are not mentioned is because:

1. The transport is potentially unstable
2. It's not part of the grpc-web spec.

So while you can use it for bi-directional streaming in the browser (which it sounds like your use case requires), it's potentially going to be superceded by some [official grpc-web full duplex solution](https://github.com/grpc/grpc-web/issues/24).
