### ISSUE TITLE
The request's body is null in the ErrorHandlerFunc of  runtime.WithErrorHandler 

### ISSUE THREAD

**Issue by leeisman** [grpc-ecosystem/grpc-gateway#2435]
I considered the package utilities IOReaderFactory that need copy io.Reader ?

**Comment by johanbrandhorst** [comment]
Hi,

I'm a little confused. Could you describe the issue? A reproducible example would be best.

**Comment by crunk1** [comment]
I'm not sure what reporter's opening comment means, but I too discovered that the *http.Request that is passed to the ErrorHandlerFunc has a Body that has already been read. Gateway reads the request body to generate the proto message, which means the error handler can't read it.

In my case, I'm trying to log the request body when I encounter `codes.Internal` responses. An example:

```go
func errorHandler(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, req *http.Request, err error) {
  ...
  body, err := ioutil.ReadAll(req.Body)
  if err != nil {
    fmt.Println("error!")
    return
  } 
  fmt.Println(string(body))  // prints empty string even though I called with `{"id": "string"}`
  ...
}

// elsewhere in code
...
rmux := runtime.NewServeMux(runtime.WithErrorHandler(errorHandler))
...
```

**Comment by johanbrandhorst** [comment]
Hm, yes, I don't think we can realistically buffer the body for later re-reads. You could solve your use case with a custom http.Handler level middleware probably? You can set a custom response header to indicate that you want the body to be logged, maybe? I think that's the right place to fiddle with this sort of thing.

**Comment by crunk1** [comment]
I agree, seems reasonable to use some sort of handler middleware. Though, maybe gateway could utilize http.Request.GetBody somehow?

**Comment by johanbrandhorst** [comment]
If you've got a concrete suggestion I'm all ears :). Maybe the best solution for now would be to document this shortcoming in the signature of WithErrorHandler?
