### ISSUE TITLE
Bad json formatted output by ForwardResponseStream

### ISSUE THREAD

**Issue by Prabhjot-Sethi** [grpc-ecosystem/grpc-gateway#2438]
## 🐛 Bug Report

Formatting of json response by stream forwarder is bad, which cannot be interpreted by any standard browser or json decoder. stream sends a list of response that is supposed to be sent as a list in json, instead it sends 
<pre>
{
	"result": {
		"id": "199e4749-15ce-4193-9d50-aa315cf30c0b"
	}
}   <--------- wrong JSON format
{
	"result": {
		"id": "2a9e4749-1fce-4a93-ad50-aa315cf30c0b"
	}
}
</pre>
## To Reproduce
follow grpc-gateway example [here](https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/proto/example.proto#L37) implementing get for list of users

## Expected behavior

Output should be like 
<pre>
[
	{
		"id": "199e4749-15ce-4193-9d50-aa315cf30c0b"
	},
	{
		"id": "2a9e4749-1fce-4a93-ad50-aa315cf30c0b"
	}
]
</pre>
## Actual Behavior
<pre>
{
	"result": {
		"id": "199e4749-15ce-4193-9d50-aa315cf30c0b"
	}
}
{
	"result": {
		"id": "2a9e4749-1fce-4a93-ad50-aa315cf30c0b"
	}
}
</pre>

**Comment by Prabhjot-Sethi** [comment]
@johanbrandhorst Please have a look, i have fixed this for myself in a [little hacky way](https://github.com/Prabhjot-Sethi/grpc-gateway/commit/5645b7edcc8454d1bfa4e40da0d8c719c9799bf0). I would be happy to submit a fix if someone can guide me on various marshallers grpc-gateway looking forward to support.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! The streams from the grpc-gateway return newline delimited JSON with an envelope. This is intentional, to support returning errors in the middle of a stream. See #2189, #1254 for more discussion. Do you think we should add a section to the docs to explain why this is the way it is?

**Comment by Prabhjot-Sethi** [comment]
Hi @johanbrandhorst , both the issues probably don't highlight the problem i am refering to.
I do not have any problem specifically with encapsulation of messages in result/error, those can be parsed as long as the formatting is correct.

The moment it is more than one chunk (/Object) the message parsing goes bad. as it doesn't follow json encoding schematics of an array. Now are you suggesting that when we are using streams HTTP client needs to somehow parse the chunks individually ?
How would this work with browser interpretation? does grpc-gateway not support this?

**Comment by johanbrandhorst** [comment]
You'll need to parse it by splitting the response by newlines before parsing as JSON. I haven't written any parsers for this recently but I have done it in the past. Returning an array wouldn't let you parse the stream as you receive it from the server.

**Comment by Prabhjot-Sethi** [comment]
Thanks for the response well in that case we can not or should not use grpc stream for List operation in gateway purely from a standard HTTP/JSON response handling aspect.
I would be more than happy to see how and for what use case grpc-gateway is using streams here
as long as we document both the points, we should be covered.

for my use case i will look forward to switch using something like this (back to old school) instead of streams
<pre>
service UserService {
  ...
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    option (google.api.http) = {
      // Route to this method from GET requests to /api/v1/users
      get: "/api/v1/users"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "List users"
      description: "List all users on the server."
      tags: "Users"
    };
  }
}

// ListUsersRequest Users with a starting point and chunk size
message ListUsersRequest {
  int32 start = 1;
  int32 chunkSize = 2;
}

message User {
  string id = 1;
}

// ListUsersResponse provides the start point and the actual chunk size in response
// with list of users encoded
message ListUsersResponse {
  int32 start = 1;
  int32 chunkSize = 2;
  repeated User users = 3;
}

</pre>

**Comment by johanbrandhorst** [comment]
Yes, that makes sense. Streams are rarely the answer. I will close this issue for now but feel free to reply and reopening if you want.
