### ISSUE TITLE
protoc-gen-swagger/options for java

### ISSUE THREAD

**Issue by carlos-contreras-ruiz** [grpc-ecosystem/grpc-gateway#2441]
Hi, I'm trying to use the annotations for swagger in my proto file but I'm struggling to do that. 
Is there some documentation about how to use swagger annotations with maven?.
The problem is that my maven project can't find those annotations, is there a maven dependency already package?
Thanks in advance

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I'm really confused what you're trying to do. There is nothing about the grpc-gateway that requires Java or integrates with Java in any way. If you want to use the grpc-gateway with a Java gRPC server, you can deploy it as an independent proxy to the Java server. See https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/cmd/standalone/main.go for an example of a proxy that is implemented this way.
