### ISSUE TITLE
Concern about breaking change with PR #2398 (support grpc.ClientConnInterface in RegisterXXXHandler) was valid

### ISSUE THREAD

**Issue by shane-kerr** [grpc-ecosystem/grpc-gateway#2442]
## 🐛 Bug Report

This comment sums up the issue:

https://github.com/grpc-ecosystem/grpc-gateway/pull/2398#pullrequestreview-787395113

Basically, our code is riddled with things like:
```go
 	JSONRegister: system.RegisterSystemServiceHandler,
```

We can possibly fix this by changing all of our declarations of `*grpc.ClientConn` to `grpc.ClientConnInterface`. However, the `grpc.ClientConnInterface` claims:
```go
// ClientConnInterface defines the functions clients need to perform unary and
// streaming RPCs.  It is implemented by *ClientConn, and is only intended to
// be referenced by generated code.
```
Also, the `grpc.ClientConnInterface` is missing a `Close()` method, which means that we can't just do a search-and-replace of all uses of `*grpc.ClientConn` in our code base.

Looking at both the feature request and the PR, I don't see any motivation for this change. Can it be reverted? Or at least explained?

**Comment by johanbrandhorst** [comment]
Argh, I hate it when I'm right! That is really unfortunate. Changing to the interface means it's possible to slot in other implementations of the interface, such that you could be much more flexible with the underlying transport, if you wanted to. It seems an oversight that the interface does not define the `Close()` method, but not much we can do about that on our end. If you'd like to open a PR to revert the change we can get that out in a patch release soon, and again, apologies for breaking you 😢.

**Comment by shane-kerr** [comment]
Great I'll put a PR together! :+1:
