### ISSUE TITLE
Protobuf emptypb not found

### ISSUE THREAD

**Issue by mmellin** [grpc-ecosystem/grpc-gateway#2452]
## 🐛 Bug Report

I have a bazel `go_proto_library` rule which is failing when I use `@com_github_grpc_ecosystem_grpc_gateway_v2//protoc-gen-grpc-gateway:go_gen_grpc_gateway` as a compiler. The error mesage is as such:

```
bazel-out/k8-fastbuild/bin/devicemanager_go_proto_/example.com/device_onboarding.pb.gw.go:16:2: imported and not used: "github.com/golang/protobuf/ptypes/empty"
bazel-out/k8-fastbuild/bin/devicemanager_go_proto_/example.com/device_onboarding.pb.gw.go:172:15: undefined: emptypb
bazel-out/k8-fastbuild/bin/devicemanager_go_proto_/example.com/device_onboarding.pb.gw.go:181:15: undefined: emptypb
```

Within the autogenerated .pb.gw.go code, the following usage of Empty is:
```
package proto

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/ptypes/empty"
...
func request_DeviceOnboardingService_GetSupportedVendors_0(..) {
  var protoReq emptypb.Empty # Problem use of `emptypb`
...

```

The problem `.proto` file imports the following:
```
import "google/protobuf/empty.proto";
```
and then uses it like:
```
    // GetSupportedVendors
    //
    // RPC to list the supported vendors
    rpc GetSupportedVendors (google.protobuf.Empty) returns (GetSupportedVendorsOutput) {
        option (google.api.http) = {
            get: "/devicemanager/get-supported-vendors"
        };
    }
```
Problem Bazel BUILD rule:
```
go_proto_library(
    name = "devicemanager_go_proto",
    compilers = [
        "@io_bazel_rules_go//proto:go_grpc",
        "@com_github_grpc_ecosystem_grpc_gateway_v2//protoc-gen-grpc-gateway:go_gen_grpc_gateway",
    ],
    importpath = "example.com/mystuff//devicemanager/proto",
    proto = ":devicemanager_proto",
    visibility = ["//visibility:public"],
    deps = [
        "@io_bazel_rules_go//proto/wkt:empty_go_proto",
        "//mystuff//devicemanager/openconfig/openconfig_resource:openconfig_resource_proto_go",
        "//mystuff//deviceplugins/pkg/types:go_default_library",
        "//mystuff//devicemanager/pkg/gen:go_default_library",
        "//mystuff//devicemodel/pkg/gen:go_default_library",
        "@com_github_golang_protobuf//descriptor:go_default_library_gen",
        "@com_google_googleapis//google/api:annotations_go_proto",
        "@com_github_openconfig_gnmi//proto/gnmi:go_default_library",
        "//mystuff//api-server-lib/pkg/services/baseservices:baseservices_go_proto",
        "@io_bazel_rules_go//proto/wkt:struct_go_proto",
        "@io_bazel_rules_go//proto/wkt:field_mask_go_proto",
    ],
)
```

I'm trying to understand why this occurring and how to fix it from happening.  My software stack:

- Bazel 4.2.1
- grpc_gateway v2.7.1
- Gazelle 0.24
- io_bazel_rules_go v0.29.0

I'm no expert here on protobuf, but it seems to be related to the differing versions of repos at github.com/google/protobuf and github.com/protocolbuffers/protobuf-go and how the WORKSPACE rules are importing maybe one or both via `grpc_gateway` and `io_bazel_rules_go`.

## To Reproduce

I'm sorry I'm not 100% clear on how to reproduce this yet.

## Expected behavior

The Build would pass.

## Actual Behavior

Build errors out with the following error:

```
bazel-out/k8-fastbuild/bin/devicemanager_go_proto_/example.com/device_onboarding.pb.gw.go:16:2: imported and not used: "github.com/golang/protobuf/ptypes/empty"
bazel-out/k8-fastbuild/bin/devicemanager_go_proto_/example.com/device_onboarding.pb.gw.go:172:15: undefined: emptypb
bazel-out/k8-fastbuild/bin/devicemanager_go_proto_/example.com/device_onboarding.pb.gw.go:181:15: undefined: emptypb
```

## Your Environment

Build environment: Ubuntu 18

- Bazel 4.2.1
- grpc_gateway v2.7.1
- Gazelle 0.24
- io_bazel_rules_go v0.29.0

**Comment by johanbrandhorst** [comment]
Hi, sorry that this is affecting you. I would agree with your assessment that you're somehow depending on an old version of `empty.proto` which defines its import path as `github.com/golang/protobuf/ptypes/empty`. This is incompatible with v2 of the gateway, which uses the APIv2 types, hosted at `google.golang.org/protobuf`. You'll have to figure out where this dependency is coming from. Unfortunately I am no bazel expert either, but maybe a good starting point would be to check out OUR WORKSPACE file for comparison: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/WORKSPACE.

**Comment by thefallentree** [comment]
Did anyone ever find an solution to this? 

I actually think it might be related to protoc : grpc gateway correct generate code that use “emptypb” but for some reason the import code is wrong and still uses the old package. my guess is that the import is handled by  protoc directly but I have not been able to trace where

**Comment by johanbrandhorst** [comment]
It depends on the version of `protoc` that you use, yes. It's because `protoc` comes bundled with a well known types, and older versions of `protoc` will be using the older import path. Use a modern version of `protoc` (or `buf`) and it won't be a problem.

**Comment by Chellapandi** [comment]
I am using the same version used by grpc-gateway [here (3.22.2)](https://github.com/grpc-ecosystem/grpc-gateway/blob/47a587aa0197aac1b57636eb6550b12277b1a1d5/WORKSPACE#L18). But I am getting `error: "C++ versions less than C++14 are not supported."`. If I downgrade the version to 3.21.7, I am getting the `imported and not used: "github.com/golang/protobuf/ptypes/empty"`. What can I do now?

**Comment by johanbrandhorst** [comment]
I would recommend using the latest protoc and upgrade your C++ toolchain to 14 like we did here: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/.github/workflows/ci.yml#L79

**Comment by Chellapandi** [comment]
@johanbrandhorst Actually we tried it in `.bazelrc` which is not working. So we tried `bazel build --action_env=BAZEL_CXXOPTS="-std=c++20" //...` but we are getting `dyld[...]: missing symbol` called at `com_google_protobuf/src/google/protobuf/BUILD.bazel:117:8: Executing genrule @com_google_protobuf//src/google/protobuf:gen_wkt_cc_sources failed`.

**Comment by eko** [comment]
Hi, I am having the same issue. I don't have any solution at this time:

```
ERROR: /private/var/tmp/_bazel_vincent/443a65df8b3b85c50be17ec31dd89017/external/com_google_protobuf/src/google/protobuf/BUILD.bazel:117:8: Executing genrule @com_google_protobuf//src/google/protobuf:gen_wkt_cc_sources failed: (Aborted): sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_vincent/443a65df8b3b85c50be17ec31dd89017/sandbox/darwin-sandbox/2312/execroot/__main__ && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    TMPDIR=/var/folders/hz/qny6cxld1mxg7kmdc297g1g80000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_vincent/443a65df8b3b85c50be17ec31dd89017/sandbox/darwin-sandbox/2312/sandbox.sb /var/tmp/_bazel_vincent/install/47f1c25bb3cb1d9b4a99f26940323be5/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
        bazel-out/darwin-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/com_google_protobuf/src/google/protobuf/compiler/protoc_nowkt             --cpp_out=dllexport_decl=PROTOBUF_EXPORT:bazel-out/darwin-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/com_google_protobuf/src/google/protobuf/wkt             --proto_path=$(dirname $(dirname $(dirname external/com_google_protobuf/src/google/protobuf/any.proto)))             external/com_google_protobuf/src/google/protobuf/any.proto external/com_google_protobuf/src/google/protobuf/api.proto external/com_google_protobuf/src/google/protobuf/duration.proto external/com_google_protobuf/src/google/protobuf/empty.proto external/com_google_protobuf/src/google/protobuf/field_mask.proto external/com_google_protobuf/src/google/protobuf/source_context.proto external/com_google_protobuf/src/google/protobuf/struct.proto external/com_google_protobuf/src/google/protobuf/timestamp.proto external/com_google_protobuf/src/google/protobuf/type.proto external/com_google_protobuf/src/google/protobuf/wrappers.proto
    ')

dyld[8394]: missing symbol called

/bin/bash: line 1:  8394 Abort trap: 6           bazel-out/darwin-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/com_google_protobuf/src/google/protobuf/compiler/protoc_nowkt --cpp_out=dllexport_decl=PROTOBUF_EXPORT:bazel-out/darwin-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/com_google_protobuf/src/google/protobuf/wkt --proto_path=$(dirname $(dirname $(dirname external/com_google_protobuf/src/google/protobuf/any.proto))) external/com_google_protobuf/src/google/protobuf/any.proto external/com_google_protobuf/src/google/protobuf/api.proto external/com_google_protobuf/src/google/protobuf/duration.proto external/com_google_protobuf/src/google/protobuf/empty.proto external/com_google_protobuf/src/google/protobuf/field_mask.proto external/com_google_protobuf/src/google/protobuf/source_context.proto external/com_google_protobuf/src/google/protobuf/struct.proto external/com_google_protobuf/src/google/protobuf/timestamp.proto external/com_google_protobuf/src/google/protobuf/type.proto external/com_google_protobuf/src/google/protobuf/wrappers.proto
```
