### ISSUE TITLE
How to use in a micro-services oriented environemnt

### ISSUE THREAD

**Issue by eldad87** [grpc-ecosystem/grpc-gateway#2468]
Hi,
Given our eco-system is composed of multiple (different) micro-services, each service expose/implement a different Proto/gRPC.
What is the recommended way of using gRPC-gateway?

1. Run a single instance (or cluster) and have it bridge multiple services (not sure if thats possible).
2. Each service should have its own gRPC-GW. While an higher level solution (Kong, AWS APIGW, WSO2, Tyk, etc) is needed in order to aggregate all services into a single endpoint.

**Comment by johanbrandhorst** [comment]
Generally I would say each service has its own gateway. If your application is written in Go you can support this very easily. If it is not written in Go it becomes a little more work as you need to build a separate proxy for each application but can still work fine.

You can also serve all applications on the same gateway, you just need to import and register all of the types in a single `main.go`, but I would only recommend this if you weren't using Go for your backend.

**Comment by eldad87** [comment]
Hi @johanbrandhorst ,
Thank you for your answer.

I would like to run my services as Lambda. Would still recommend on running gRPC-GW from within my app `main.go`?


> You can also serve all applications on the same gateway, you just need to import and register all of the types in a single `main.go`

Can you please  point me to an example?

Thanks!

**Comment by johanbrandhorst** [comment]
> I would like to run my services as Lambda. Would still recommend on running gRPC-GW from within my app `main.go`?

Uh, potentially, yes, but I don't know how well gRPC services work within Lambdas. If the gRPC server is located somewhere else you'd probably need to run the gateway as a standalone binary.

> Can you please point me to an example?

Our integration tests register a lot of services in one binary: https://github.com/grpc-ecosystem/grpc-gateway/blob/71a544628daba2f0909584e29f4dcb58ecbd2c52/examples/internal/server/main.go#L17-L44.

**Comment by eldad87** [comment]
Hi @johanbrandhorst ,
Thank you for your response.

Since the gRPC-gateway can connect to multiple services and in turn, expose their APIs as Restful APIs - Is it possible that it will expose the gRPC functionality too?
In other words, act as an API Gateway for gRPC bases services?

**Comment by johanbrandhorst** [comment]
The gRPC gateway can't expose the gRPC server directly, but there's nothing stopping you from doing so. It's not uncommon to serve the gRPC gateway on one port and the gRPC server on another port and expose both.

**Comment by eldad87** [comment]
Hi @johanbrandhorst,
Yes, we can easily expose gRPC using a different port.
The question is if its possible to aggregate multiple endpoints into a single endpoint?

**Comment by johanbrandhorst** [comment]
I'm not sure what you mean by aggregating multiple endpoints into a single endpoint, sorry. Aggregating multiple services can be done by simply serving multiple generated gRPC-gateway clients on a single HTTP server. Does that answer the question?
