### ISSUE TITLE
Setting status code for the response

### ISSUE THREAD

**Issue by ivanjaros** [grpc-ecosystem/grpc-gateway#2469]
I have a need to return http status code from rpc service but even though it will be passed onto the client, thanks to `runtime.WithOutgoingHeaderMatcher`, the **200 OK** is the actual result while the `Status` header will also be present, but ignored. I have not seen documentation mentioning status codes, even though headers are documented, so I just wonder if there is undocumented solution or if this is just not possible?

**Comment by johanbrandhorst** [comment]
Returning a gRPC Status error will map to the correct status code automatically according to this mapping: https://github.com/grpc-ecosystem/grpc-gateway/blob/71a544628daba2f0909584e29f4dcb58ecbd2c52/runtime/errors.go#L34-L77. If you want behavior outside of this error mapping you will need a custom error handler.

**Comment by ivanjaros** [comment]
I am not returning error.

**Comment by johanbrandhorst** [comment]
Then I don't believe the gateway has any way to let you set the http status.

**Comment by ivanjaros** [comment]
I thought so, thanks for confirmation.
