### ISSUE TITLE
Location of the URL Get query marshaler

### ISSUE THREAD

**Issue by ivanjaros** [grpc-ecosystem/grpc-gateway#2487]
I am looking for the function that can take URL GET Query and marshal the fields into the PB message, but cannot find it. Can someone point it out to me, please?

**Comment by johanbrandhorst** [comment]
The logic for the default URL Query parser is here: https://github.com/grpc-ecosystem/grpc-gateway/blob/f9167a60f321a6cdd426b5ea917feb7f57de2014/runtime/query.go#L35-L329, is that what you're looking for?

**Comment by ivanjaros** [comment]
Yes, that looks like it. I will test it tomorrow. Thanks!
