### ISSUE TITLE
protoc-gen-openapiv2 generates additional paths when API includes several services with resource name based paths

### ISSUE THREAD

**Issue by oyvindwe** [grpc-ecosystem/grpc-gateway#2489]
## 🐛 Bug Report

When specifying a gRPC API with multiple services with resource name based paths, and these services have multiple methods for these paths, extra paths are generated in the OpenAPI file; each service in the proto file gets one extra set of paths per method per number of services below with the same path.

## To Reproduce

1. Make a proto definition of your API, e.g. `test/foo_api.proto`:
```
syntax = "proto3";

package test;

option go_package = "example.com/test";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

service FooService {
  rpc GetFoo(GetFooRequest) returns (Foo) {
    option (google.api.http) = {
      get: "/v1/{name=foos/*}",
    };
  }
  rpc DeleteFoo(DeleteFooRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=foos/*}"
    };
  }
}

message GetFooRequest {
  string name = 1;
}

message DeleteFooRequest {
  string name = 1;
}

message Foo { }

service BarService {
  rpc GetBar(GetBarRequest) returns (Bar) {
    option (google.api.http) = {
      get: "/v1/{name=bars/*}"
    };
  }
  rpc DeleteBar(DeleteBarRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=bars/*}"
    };
  }
}

message GetBarRequest {
  string name = 1;
}

message DeleteBarRequest {
  string name = 1;
}

message Bar { }
```

2. Make sure you have `google/api/annotations.proto` and `google/api/http.proto` available in the include path.

3. Generate the OpenAPIv2 file: `protoc -I . --go_out=. --go_opt=module=example.com/test --go-grpc_out=. --go-grpc_opt=module=example.com/test --openapiv2_out . test/foo_api.proto`

(I originally encountered this issue using `allowMerge=true`, but it occurs with a single file containing multiple services as well.)

## Expected behavior

The file should only contain paths `/v1/{name}` and `/v1/{name_1}`. Each path should only apply to one service.

## Actual Behavior

The resulting file contains three paths with get and delete operations, mixed between the two services (`responses` removed for readability):
```
  "paths": {
    "/v1/{name_1}": {
      "get": {
        "operationId": "BarService_GetBar",
        "parameters": [
          {
            "name": "name_1",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "bars/[^/]+"
          }
        ],
        "tags": [
          "BarService"
        ]
      },
      "delete": {
        "operationId": "FooService_DeleteFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      }
    },
    "/v1/{name_2}": {
      "get": {
        "operationId": "FooService_GetFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      },
      "delete": {
        "operationId": "BarService_DeleteBar",
        "parameters": [
          {
            "name": "name_2",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "bars/[^/]+"
          }
        ],
        "tags": [
          "BarService"
        ]
      }
    },
    "/v1/{name}": {
      "get": {
        "operationId": "FooService_GetFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      },
      "delete": {
        "operationId": "FooService_DeleteFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      }
    }
  }
```

## Your Environment

macOS: 12.0.1
protoc: `libprotoc 3.17.3`
go: `go version go1.17.2 darwin/amd64`
grpc-gateway: 2.7.2

**Comment by johanbrandhorst** [comment]
Thanks for the issue? Do you think you could try and figure out when this was introduced? Is it a regression or something that has always been present?

**Comment by oyvindwe** [comment]
With 2.7.1, I get paths `/v1/{name=bars/*}` and `/v1/{name=foos/*}`, so I guess this is a bug introduced in PR #2461. Unfortunately, I don't know go, so it's a bit hard for me to propose a fix.

**Comment by aethanol** [comment]
@johanbrandhorst @oyvindwe I have raised a PR that should fix this: https://github.com/grpc-ecosystem/grpc-gateway/pull/2496

**Comment by oyvindwe** [comment]
@aethanol Thank you very much! I'll try to get a dev environment up and see if I can verify the fix locally as well.

While you're at it, how connected is issue #1670?

**Comment by oyvindwe** [comment]
@aethanol I have tested your fix locally, and the additional paths are gone. Thank you very much for your effort!

**Comment by aethanol** [comment]
> @aethanol Thank you very much! I'll try to get a dev environment up and see if I can verify the fix locally as well.
> 
> While you're at it, how connected is issue #1670?

Hmm that I am not familiar with, can perhaps take a look in the future.
