### ISSUE TITLE
Add NGINX support

### ISSUE THREAD

**Issue by gsogol** [grpc-ecosystem/grpc-gateway#249]
Generate nginx configuration for reverse proxy vs custom reverse proxy. Use the best tool in the industry for reverse proxy. 

Better yet, allow a plugin to generate others like haproxy.

**Comment by tmc** [comment]
@gsogol can you comment further on what you have in mind here? It's not clear that this would be in-scope for this project.

**Comment by tmc** [comment]
Given the need to have awareness of the content of the messages I'm not sure what you're describing is achievable. I'm going to close this unless there's some sketch of what this would actually mean.

**Comment by tmc** [comment]
To comment further, there's nothing stopping you from putting nginx in front of grpc-gateway.
