### ISSUE TITLE
Mapping gRPC request to HTTP request

### ISSUE THREAD

**Issue by sorcererxw** [grpc-ecosystem/grpc-gateway#2491]
Is there anyway to convert gRPC request to HTTP+JSON request? With this feature, I could use gRPC client directly without refactoring the server to support gRPC.

```
    ┌───────────┐                ┌───────────┐         ┌────────┐
    │           │   gRPC req     │           │  JSON   │        │
    │  client   ├───────────────►│   gateway ├────────►│ server │
    │           │                │           │         │        │
    └───────────┘                └───────────┘         └────────┘

```

**Comment by johanbrandhorst** [comment]
This isn't something that's supported by the grpc-gateway (the reverse mapping), but if your other servers support something like OpenAPI you can generate a Go client for them.
