### ISSUE TITLE
Allow whitelisting of particular HTTP headers to map to metadata.

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#253]
In #252 we allow a fixed set of HTTP headers to be sent on to the grpc call in the form of metadata (with the 'grpcgateway-' prefix). There should be a mechanism to whitelist additional headers.

**Comment by tmc** [comment]
IMO the best way to do this is via a new https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#ServeMuxOption

**Comment by fiibbb** [comment]
Hi @tmc, does this mean allowing HTTP headers not with `grpcgateway-` prefix to be also passed to GRPC? If so, I'm interested in this feature. Is it actively being worked on?

**Comment by tmc** [comment]
@fiibbb it's not super specified but could encompass what you're describing

**Comment by tmc** [comment]
with #336 landed I think this can be considered closed.
