### ISSUE TITLE
merge files options are not used when set

### ISSUE THREAD

**Issue by marbar3778** [grpc-ecosystem/grpc-gateway#2539]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## To Reproduce
using the below plugin as mentioned in the docs. There are multiple files that are generated but when using `allow_merge=true,merge_file_name=openapi` one file is generated and overwritten every time, at the end it only houses the final proto files openapi docs

plugins:
  - name: openapiv2
    out: openapi
    strategy: all
    opt: allow_merge=true,merge_file_name=openapi

## Expected behavior

generate all file openapi docs into a single json file

## Actual Behavior

last proto file is the only openapi documentation displayed in the json file

## Your Environment

Mac/ docker

**Comment by johanbrandhorst** [comment]
Hi, thanks for the bug report. Could you provide a minimal reproducible example of the bug? I definitely would expect this to work, we have tests for it.

**Comment by marbar3778** [comment]
ah sorry, I figured out the issue,, it was a script that is being runs fault.
