### ISSUE TITLE
Skip unused messages while documentation generation

### ISSUE THREAD

**Issue by stumko-elamateam** [grpc-ecosystem/grpc-gateway#2543]
Suppose we write common grpc server for both internal and external communication like this
```proto
service Service {
    rpc ExternalMethod(ExternalMethodRequest) returns (ExternalMethodResponse) {
        option (google.api.http) = {
            get: "/api/v1/methods",
        };
    };

    rpc InternalMethod(InternalMethodRequest) returns (InternalMethodResponse) {};
}

message ExternalMethodRequest {
    string field = 1;
}

message ExternalMethodResponse {
    string field = 1;
}

message SomeAnotherMessage {
  string field = 1;
}

message InternalMethodRequest {
  SomeAnotherMessage field = 1;
}

message InternalMethodResponse {
    string field = 1;
}
```
Using openapiv2_out plugin doesn`t produce InternalMethod documentation, but SomeAnotherMessage/InternalMethodResponse are still in the documentation. Is there any annotation or plugin option to skip such messages?

**Comment by johanbrandhorst** [comment]
Hi, thanks for the issue! All the options available to the `openapiv2` generator are listed here: https://github.com/grpc-ecosystem/grpc-gateway/blob/e3f0402c2331a9910318e5bd7fd7c7d21e869d05/protoc-gen-openapiv2/main.go#L18-L39. There is no option to exclude messages that aren't used. I would recommend creating separate definitions for your external APIs, it is likely that they will diverge over time anyway.
