### ISSUE TITLE
cannot use example code to generate

### ISSUE THREAD

**Issue by LeeWong** [grpc-ecosystem/grpc-gateway#255]
protoc -I/usr/local/include -I.  -I$GOPATH/src  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis  --go_out=Mgoogle/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,plugins=grpc:.  /home/lee/IdeaProjects/go_api_gateway/src/api_gateway/rest/test_service.proto 
/home/lee/IdeaProjects/go_api_gateway/src/api_gateway/rest/test_service.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

**Comment by LeeWong** [comment]
protoc -I/usr/local/include -I. \
>  -I$GOPATH/src \
>  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
>  --grpc-gateway_out=logtostderr=true:. \
>  /home/lee/IdeaProjects/go_api_gateway/src/api_gateway/rest/test_service.proto 
/home/lee/IdeaProjects/go_api_gateway/src/api_gateway/rest/test_service.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

**Comment by tmc** [comment]
@LeeWong I'm going to close this as it isn't really a grpc-gateway problem but a protoc invocation issue. You need to supply a relative path to the .proto file. 

perhaps you should try: `protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --go_out=Mgoogle/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,plugins=grpc:. test_service.proto` with cwd = `/home/lee/IdeaProjects/go_api_gateway/src/api_gateway/rest`
