### ISSUE TITLE
Transcoding streaming HTTPBody responses leads to file downloads of size greater than expected

### ISSUE THREAD

**Issue by mcquackers** [grpc-ecosystem/grpc-gateway#2557]
## 🐛 Bug Report

Using ForwardResponseStream with a stream of HttpBody leads to extra bytes appended to data in Go

## To Reproduce

(Write your steps here:)

1. Create a Unary Request - Streaming Response grpc proto (FooServer (GetFooRequest) returns (stream google.api.HttpBody))
1. Generate go bindings with GRPC Gateway and go_grpc
1. In the implementation, retrieve a remote tar.gz (eg, gitlab project archive) and return the reader.
1. Read from the reader, and return stream responses with the read data
1. Invoke the handler and note that the final file download's size is different from the amount of bytes read from the reader.

## Expected behavior

I would expect that the downloaded file would have accurate byte size and not be corrupted (tar files fail to extract, for example)

## Actual Behavior

The downloaded file differs from the expected size by the number of stream responses sent

## Your Environment

MacOS Monterey 12.1
go version go1.17.6 darwin/arm64

This is the code I'm using to write from the reader to the stream:
```
func readOntoGetProjectZipStream(reader io.Reader, server proxyV1.ConfigurationProxyService_GetProjectZipServer) error {
	b := make([]byte, 16384)
	var total int
	var n int
	var nr int
	var err error
	for nr, err = reader.Read(b); nr > 0; nr, err = reader.Read(b) {
		total += nr
		body := &httpbody.HttpBody{
			ContentType: "application/x-tar",
			Data:        make([]byte, nr),
		} //made these allocations and copying very explicit to remove any chance of off-data
		copy(body.Data, b[:nr])
		server.Send(body)
		n++
	}
	fmt.Println(total) //6479278 - as expected
	fmt.Println(n)     //398 or 424 usually; final downloaded file is greater than expected 6479278 by this amount
	if err != nil && err != io.EOF {
		return err
	}
	return nil
}```

**Comment by johanbrandhorst** [comment]
Hm, i there any chance that the marshaler is inserting newlines between each of your messages? I've never tried to use HTTPBody in a stream, that's kinda interesting, but we do have a way to configure the stream separator: https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#Delimited. It appears the default HTTPBody marshaler doesn't implement this, but instead expects the user to embed a marshaler, so adopts its behavior, which is probably to insert newlines between stream calls: https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#JSONPb.Delimiter. We probably want to set the Delimiter to `""` for the `HTTPBodyMarshaler`.

It would be cool if you could contribute a fix with a test case for this. We have integration tests that this should fit pretty well into: https://github.com/grpc-ecosystem/grpc-gateway/tree/master/examples/internal/integration.

**Comment by mcquackers** [comment]
@johanbrandhorst I was wondering if you could offer some insight:
Are you suggesting updating the HTTPBodyMarshaler to implement the `Delimited` interface?  I was running through that, and then that causes some other breakages because HTTPBodyMarshaler serves as the Default Marshaler.

If this is the approach we should follow, easy enough.  I just want to verify there wasn't a better fit you were thinking of.

**Comment by johanbrandhorst** [comment]
Hm, that _was_ what I was thinking, but you're right that is a change of behavior. Maybe what we need is a new option on the `HTTPBodyMarshaler` that lets you set the delimiter, and default it to the current `\n` to preserve backwards compatibility. What do you think?

**Comment by mcquackers** [comment]
I think this is something I'm going to noodle on for a little bit.
The requisites to me seem to be:
1. Don't break existing functionality where the default marshaler is used
2. avoid bolting fields on to the HTTPBodyMarshaler if at all possible; existing implementations of other marshalers either have options from third party resources or have no options at all, but none of the existing marshalers have one-off options
3. The delimiter should be fully configurable.  A user may be sending data that contains newlines and wish to delimit on a different special character, or a user may not wish to delimit at all.

**Comment by mcquackers** [comment]
I've been able to achieve a successful streaming download by creating a custom marshaller that wraps HTTPBodyMarshaller and overrides the underlying JSONPb.Delimiter() method, so I'm able to proceed, but I still would like to find a win here.

Currently, I'm thinking of an option that exists outside the Marshaller that can then wrap the marshaller.  This isn't _ideal_ because Marshallers already implement Delimited, but Delimiter() is only ever called during Stream handlers, as far as I can tell.

An option type `ForwardResponseStreamOption`, which would be essentially be a `ForwardResponseOption` with the addition of the marshaller being added.

This would be more invasive than I'd like, and it would open up override options for the rest of the marshaller interface methods, which...at that point....is just a custom marshaller.

So I guess this is pretty much a no-op, as the winning implementation already exists

**Comment by black-06** [comment]
I had the same problem.
Maybe we can pass in messages to decide what delimiter to use, just like ContentType

```golang
type DelimitedByMessage interface {
	Delimiter(v interface{}) []byte
}

type HTTPBodyMarshaler struct {
	Marshaler
}

func (h *HTTPBodyDelimitedMarshaler) Delimiter(v interface{}) []byte {
	if httpBody, ok := v.(*httpbody.HttpBody); ok {
		return []byte("")
	}
	if d, ok := h.Marshaler.(Delimited); ok {
		return d.Delimiter()
	}
	if d, ok := h.Marshaler.(DelimitedByMessage); ok {
		return d.Delimiter(v)
	}
	return []byte("\n")
}
```

**Comment by johanbrandhorst** [comment]
Though unlikely, this change would be breaking behavior, and I think the workaround as described is sufficient, no?

**Comment by black-06** [comment]
> Though unlikely, this change would be breaking behavior, and I think the workaround as described is sufficient, no?

If users have multiple stream api and want their Delimiter to be different, we can't do it at present.
For example, https://github.com/black-06/grpc-gateway-file, which is used to support gateway file upload and download, will interfere with other stream api of the user.

**Comment by johanbrandhorst** [comment]
Hm, that is unfortunate. I suppose you could instantiate two different serve muxes with differen encoders, as long as the stream APIs are in different services, that should work?

**Comment by Gantushig77** [comment]
Hello, is this problem still not fixed? When I implement [KevinSnyderCodes](https://github.com/KevinSnyderCodes)'s solution, the upload does not work. Is there any other way to fix this?

**Comment by johanbrandhorst** [comment]
Uploads in general don't work great with the gateway. See https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/binary_file_uploads/. The solution should work for download streams though.

**Comment by Gantushig77** [comment]
I used the solution with "gatewayfile.WithHTTPBodyMarshaler()" (this line is below the solution), upload and download seem to be working now. I didn't test it thoroughly, I don't know what condition it won't work.

**Comment by andrewbcohere** [comment]
Ran into this problem while simply trying to provide file downloads over grpc gateway. It seems very strange that there is a default newline delimiter and this is quite a hard issue to track down, just wanted to mention that this is still relevant and causing confusion.

**Comment by johanbrandhorst** [comment]
Is this something that would be improved with a new section in the docs. Fundamentally we can't change the default behavior here without breaking users, and the streaming feature is really more about streaming messages than it is about streaming binary data. Perhaps we should add a "Binary file downloads" section to the docs?
