### ISSUE TITLE
Add option to append incoming transcoded request to OutgoingMetadata to support StreamServerInterceptor authorization

### ISSUE THREAD

**Issue by mcquackers** [grpc-ecosystem/grpc-gateway#2568]
## 🚀 Feature

Stream RPCs are easy to authenticate but difficult to authorize via Interceptors due to the way the go_grpc plugin generates code:
Even for a (Unary Request, Streaming Response), which arrives at the GRPC Server with the Request available at that point, Stream Interceptors, which can only operate on the Server, Stream, ServerStreamInfo, and Handler, have no way of viewing the incoming request data.
The data _could_ be read from the stream, at the interceptor level, but then that removes the message from the stream and does not allow for the GRPC handler to receive the message.

GRPCGateway can however make this initial request accessible by attaching a copy of the incoming request to the OutgoingMetadata.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! Can't users do this already today by just adding a HTTP level interceptor?

**Comment by mcquackers** [comment]
Ha I didn't consider that; you're absolutely right
