### ISSUE TITLE
Don't see the greater advantage in reverting #2398

### ISSUE THREAD

**Issue by alphashaw** [grpc-ecosystem/grpc-gateway#2569]
## 🚀 Feature

The pull request #2398  had the ***gprc.Client** changed to the interface **grpc.ClientConnInterface** in the generated  **RegisterXXXHandler** methods and this was reverted in #2444 . I wished for #2398 before it was implemented and fortunately it was implemented before I could ready to submit a PR.
The **RegisterXXXHandler** expects the connection to be created before it's called even though the connection is not necessarily being used until a request to be transcoded comes in. 

We have a use case where this eager connection creation is not desirable. So we have a delegating **grpc.ClientConnInterface** implementation like below:

```go
var _ io.Closer = &grpcLazyDelegateClientConn{}
var _ grpc.ClientConnInterface = &grpcLazyDelegateClientConn{}

type grpcLazyDelegateClientConn struct {
	serviceName  string
	mu           sync.Mutex
	grpcClient   grpc2.Client
	delegateConn *grpc.ClientConn
}

func (c *grpcLazyDelegateClientConn) Invoke(
	ctx context.Context,
	method string, args interface{}, reply interface{}, opts ...grpc.CallOption,
) error {
	conn, err := c.getConnection(ctx)
	if err != nil {
		return err
	}
	return conn.Invoke(ctx, method, args, reply, opts...)
}

func (c *grpcLazyDelegateClientConn) NewStream(
	ctx context.Context, desc *grpc.StreamDesc,
	method string, opts ...grpc.CallOption,
) (grpc.ClientStream, error) {
	conn, err := c.getConnection(ctx)
	if err != nil {
		return nil, err
	}
	return conn.NewStream(ctx, desc, method, opts...)
}

func (c *grpcLazyDelegateClientConn) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if conn := c.delegateConn; conn != nil {
		return c.grpcClient.CloseConnection(conn)
	}
	return nil
}

func (c *grpcLazyDelegateClientConn) getConnection(ctx context.Context) (grpc.ClientConnInterface, error) {
	if c.delegateConn != nil {
		return c.delegateConn, nil
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	// recheck again for any possible race condition
	if c.delegateConn != nil {
		return c.delegateConn, nil
	}
	zap.S().Debugf("Creating the lazy connection to service: %s", c.serviceName)
	conn, err := c.grpcClient.GetConnection(ctx, c.serviceName)
	if err != nil {
		return nil, err
	}
	c.delegateConn = conn
	return conn, nil
}
```
I think for externally managed client connections, it's best if these methods accepts the interface type instead. 
Are there any technical reasons beyond backward compatibility breaking  on why #2398 was reverted?

#2398 is really useful or will soon be to other teams I guess.

**Comment by johanbrandhorst** [comment]
I agree that I would like to see an interface here, but we do take backwards compatibility extremely seriously, so it is not acceptable for us to change this again if it risks breaking users.

**Comment by alphashaw** [comment]
Kk @johanbrandhorst, thanks for the clarity.
I don't know what it will cost, so is there a possibility of having another variant of the **RegisterXXXHandler** generated method? At least this could be a temporary solution. If so, I would love to give a try on that implementation. 
Thanks

**Comment by johanbrandhorst** [comment]
I suppose we could generate a new method that uses the new signature, maybe something like `RegisterXXXInterface`? The https://github.com/grpc-ecosystem/grpc-gateway/pull/2398 PR should be a good inspiration for how to implement this.
