### ISSUE TITLE
Forward Response Option - Context contains no request anotations

### ISSUE THREAD

**Issue by rogchap** [grpc-ecosystem/grpc-gateway#2571]
## 🐛 Bug Report

The context that is passed to `WithForwardResponseOption` function does not include any of the Annotation Options and therefore `runtime.HTTPPathPattern(ctx)` always returns empty.

The annotated context is created here: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L599 with variable `rctx`
```go
rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/{{$svc.File.GetPackage}}.{{$svc.GetName}}/{{$m.GetName}}", runtime.WithHTTPPathPattern("{{$b.PathTmpl.Template}}"))
```

However a new context is created here but it's parent is the original `ctx` rather than `rctx` https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L609 
```go
ctx = runtime.NewServerMetadataContext(ctx, md)
forward_{{$svc.GetName}}_{{$m.GetName}}_{{$b.Index}}(ctx, mux, outboundMarshaler, w, req, response_{{$svc.GetName}}_{{$m.GetName}}_{{$b.Index}}{resp}, mux.GetForwardResponseOptions()...)
```

A potential (easy) fix is to change the parent context:
```diff
--- ctx = runtime.NewServerMetadataContext(ctx, md)
+++ ctx = runtime.NewServerMetadataContext(rctx, md) 
```
But I'm unfamiliar if this would cause unwanted side effects... ie there must be a reason why we are creating a new metadata context.

Another option would be to re-hydrate the new context with the HTTP Path Pattern context key in the template Eg:
```go
ctx = runtime.NewServerMetadataContext(ctx, md)
ctx = runtime.WithHTTPPathPattern("/example/foo/bar")(ctx)
```

Happy to raise a PR, but would like some guidance on the correct approach.

## To Reproduce

```go
runtime.WithForwardResponseOption(func(ctx context.Context, w http.ResponseWriter, resp proto.Message) error {
    	if pattern, _ := runtime.HTTPPathPattern(ctx); pattern == "/example/foo/bar" {
                // DO WORK
		return nil
	}
        return nil
}))
```

## Expected behavior

Call stack should branch into the `if` statement when the HTTP path pattern matches `"/example/foo/bar"` and execute `DO WORK`

## Actual Behavior

`DO WORK` is never called, even when the pattern matches.

## Your Environment

N/A

**Comment by johanbrandhorst** [comment]
Hi, thanks for the bug report! I had to go all the way back to https://github.com/grpc-ecosystem/grpc-gateway/commit/a5edb0b39c61f3a90d5291cc04fe3e58f2fb77a7 to see where this `rctx` variable was introduced, and I can't tell why we'd only want to have the context annotated in the _incoming_ request path as supposed to both incoming and outgoing. I think we should try to just let `runtime.AnnotateContext` overwrite the context wholesale so we don't end up with this sort of thing down the line. Would you be willing to make this contribution? There are a few places beyond the one you mentioned where we create an `rctx` variable that can just use `ctx` instead, I think.

**Comment by rogchap** [comment]
Thanks for the clarification @johanbrandhorst ... PR incoming.
