### ISSUE TITLE
Custom HTTP health check endpoint path

### ISSUE THREAD

**Issue by antonioiubatti93** [grpc-ecosystem/grpc-gateway#2572]
## 🚀 Feature

Thank you @brumhard and @johanbrandhorst for having the following HTTP health check endpoint available through the gRPC gateway, this is very useful :tada: 
- #2302 
- #2319 

To further enhance that, I would suggest to customize the endpoint path in order to use any path other than `/healthz`, so that any existing health check endpoints shall not undergo any disruption.

**Comment by johanbrandhorst** [comment]
This sounds like a reasonable request. I'm not actually sure what the best way to accomplish this is... we might need a new `WithHealthEndpointPath` or something that does what `WithHealthzEndpoint` does but with a `path` parameter. Then `WithHealthzEndpoint` can be implemented as `WithHealthEndpointPath(healthCheckClient, "/healthz")`. @brumhard any thoughts?

**Comment by brumhard** [comment]
I already thought about that while implementing the PR but didn't come up with a nice solution and then lost track somehow. My idea was some kind of nested functional option, but I think your solution looks nicer than `WithHealthzEndpoint(healthCheckClient, WithPath("/health"))`. I can implement the `WithHealthEndpointPath` if you want 🙂

**Comment by antonioiubatti93** [comment]
@johanbrandhorst @brumhard those are indeed the two solutions I would have suggested myself :+1: 

Imho functional options may be overkill to simply apply a non-default endpoint path in this case, so I would favor more the idea of having a `WithHealthEndpointPath` mux option, and reuse it for `WithHealthzEndpoint`.
However, should anyone need to apply other non-default configuration, having functional options might become handy (I'm thinking about the `pathParams map[string]string` for example).

> I can implement the WithHealthEndpointPath if you want

@brumhard that would be awesome, thank you :smile: ofc I'm also available to give it a try myself if you prefer :+1: In that case, I'll try to take care of it according to your preferences on the above and ping you guys in review.

**Comment by brumhard** [comment]
@antonioiubatti93  sry was a bit afk last week but glad that you got it working to your needs 👍🏻

**Comment by antonioiubatti93** [comment]
@brumhard no problem, I had actually very little to do, the base feature was very nice already :smile:
