### ISSUE TITLE
"proto: no coders for int" printed whenever a gRPC error is returned over grpc-gateway.

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#259]
I've been able to reproduce this using the very example server suggested in the main README.md. Steps to reproduce:

1. Compile grpc-gateway-out and go_out of the example echo service.
2. Using the example server implementation, use `go run` to start the server. It will complain about not being able to connect to your backend gRPC server, but that's fine.
3. Send a simple cURL request to the HTTP API
```
curl -X POST http://localhost:8080/v1/example/echo
```

In the console of the grpc-gateway server you will get the `proto: no coders for int` message.

The source of the message is in https://github.com/golang/protobuf/blob/4bd1920723d7b7c925de087aa32e2187708897f7/proto/properties.go#L349.

The reason for it being printed appears to be that grpc-gateway creates an error struct with a `Code` of type `int`.

See https://github.com/grpc-ecosystem/grpc-gateway/blob/84398b94e188ee336f307779b57b3aa91af7063c/runtime/errors.go#L67.

This issue has been encountered in several places downstream already: https://github.com/gogo/protobuf/issues/178 and https://github.com/cockroachdb/cockroach/issues/10484 at the least.

**Comment by tmc** [comment]
PR #256 addresses this.
