### ISSUE TITLE
Allow raw JSON content as string without attempting to further unmarshal it.  

### ISSUE THREAD

**Issue by MJjainam** [grpc-ecosystem/grpc-gateway#2594]
## 🚀 Feature

I have a proto as follows:
```
message A {
    int Foo
    string Bar
}
```

Now the REST API body passed is 

```
{
    "Foo": 1,
    "Bar": {
        "Hello": "World"
     }
}
```
I was looking to make the above proto to work for this body. 

Currently the unmarshalling fails and complains that it cannot unmarshall Bar as a string. 

The closest I have gotten to is to write a custom Unmarshaller but that seems like an overkill. Is there any other better approach to solve this?

**Comment by oyvindwe** [comment]
`Bar` isn't passed as a string, so it's not a surprising response. I'm not sure what you are trying to accomplish here, but as far as I understand your suggestion is not valid per the Protobuf specification.

You could either send the value as a valid string from the client: `"Bar": "{\"Hello\": \"World\"}"`, or use a map type:
```
message A {
  int Foo = 1;
  map<string, string> Bar = 2;
}
```

or `Struct` if you want to pass any JSON object:
```
message A {
  int Foo = 1;
  google.protobuf.Struct Bar = 2;
}
```

**Comment by johanbrandhorst** [comment]
I agree with @oyvindwe, the premise is flawed. In any case, this isn't really something the gateway has control over, we use the `protojson` marshaler, which is what controls the behavior.
