### ISSUE TITLE
Timestamp as URL param causes bad request error

### ISSUE THREAD

**Issue by philipithomas** [grpc-ecosystem/grpc-gateway#260]
We have an endpoint where we need to query a date range. Here's the proto3:

```
message ShiftListRequest {
    string company_uuid = 1;
    string team_uuid = 2;
    google.protobuf.Timestamp shift_start_after = 3;
    google.protobuf.Timestamp shift_start_before = 4 ;
}
```

And the gateway spec:

```
	rpc ListShifts(ShiftListRequest) returns (ShiftList) {
		option (google.api.http) = {
			get: "/v1/companies/{company_uuid}/teams/{team_uuid}/shifts"
		};
	}
```

When we query it with no filter params, it defaults to null values and is fine. 

When we add query values, it returns an error.

Query with the zero-value datetime (but others have same issue):
```
GET /companies/e3bde7d9-0526-4830-6073-bcfe9999c528/teams/aade4334-61c2-4c85-6c8e-98e8fa4e99ad/shifts?shift_start_after=0001-01-01T00:00:00.000Z
```

Error:
```
{"error":"unsupported field type reflect.Value","code":3}
```

**Comment by tmc** [comment]
@philipithomas thanks for the report -- think you could demonstrate this in a failing test?

**Comment by JohanSJA** [comment]
Ran into similar issue today. Added the failing test case at https://github.com/grpc-ecosystem/grpc-gateway/pull/281 . It seems that `PopulateQueryParams` needs some update to fix this. Might need some guidance on how this could possibly be solved elegantly.

**Comment by JohanSJA** [comment]
Have a quick look at how `jsonpb` handle those `WellKnownTypes`. Added a fix for Timestamp support at URL param.

**Comment by tmc** [comment]
superseded by #281
