### ISSUE TITLE
Swagger Gen: underscores -> lowerCamelCase field names and refs

### ISSUE THREAD

**Issue by msample** [grpc-ecosystem/grpc-gateway#261]
Protobuf3 style guidelines suggest using underscores in Message field names in .proto files, and the JSON mappings will be translated to use lowerCamelCase field names (https://developers.google.com/protocol-buffers/docs/proto3).

For the same reasons (ie JSON encoding derived form the Swagger), shouldn't these field names be in lowerCamelCase format in the grpc-gateway-generated Swagger as well?

I am running into this issue using swagger-codegen on Swagger produced by grpc-gateway. The work around is to use the lowerCamelCase in original protobuf files - I am not sure if this introduces problems with other protoc codegen paths.

**Comment by tmc** [comment]
This is a little tricky since the marshaler can be customized -- IMO defaulting to the default marshaler `&JSONPb{OrigName: true}` is the most appropriate behavior here.

**Comment by achew22** [comment]
I would also be supportive of switching over to &JSPNpb{OrigName: true} as the default. This is another breaking change. Maybe we should wrap this up along with the context change and do a 2.0 release?

**Comment by tmc** [comment]
Just to be clear the current behavior is expected. Respecting the field names in the proto file vs the canonical json representation of proto3 (lowerCamelCase) was introduced in PR #151 (adding `OrigName: true`).

This probably merits a documentation additon.

If we want to discuss changing the default marshaler configuration (and the swagger output) we can in another issue.

**Comment by tmc** [comment]
opened #266

**Comment by yingzong** [comment]
> This is a little tricky since the marshaler can be customized -- IMO defaulting to the default marshaler &JSONPb{OrigName: true} is the most appropriate behavior here.

@tmc How do you customize the marshaler, specifically the OrigName: false in the --protoc-gen-swagger plugin?

**Comment by tmc** [comment]
@yingzong unfortunately there is not a mechanism to provide these options. You can open a feature request to allow providing an option of this sort.
