### ISSUE TITLE
Add Healthz endpoint in OpenAPI protoc-gen-openapiv2

### ISSUE THREAD

**Issue by GreyXor** [grpc-ecosystem/grpc-gateway#2612]
## 🚀 Feature

When activating WithHealthzEndpoint, the OpenAPI file does not contain the reference to this new endpoint /healthz. Is there a way to add it to openapi ?

**Comment by johanbrandhorst** [comment]
No, for this you'll need to define a custom HTTP mapping as usual. I don't think this is something we want to add especially as it's easy enough to do yourself.

**Comment by GreyXor** [comment]
Thanks i'll use custom HTTP mapping then
