### ISSUE TITLE
Support WithUnescapingMode in v1

### ISSUE THREAD

**Issue by feedmeapples** [grpc-ecosystem/grpc-gateway#2629]
## 🚀 Feature

`grpc-gateway v2` introduced an option to unescape special characters such as `/` when matching HTTP requests to gRPC methods

I would like to contribute and implement this feature in v1, as upgrading to v2 is too cumbersome due to [`protobuf-apiv2` changes](https://go.dev/blog/protobuf-apiv2).
If there are any blockers known in advance pls let me know

**Comment by feedmeapples** [comment]
related issue https://github.com/temporalio/ui/issues/392#issuecomment-1089878552

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! This is a bit of a tough one, as we'd really like users to stop using the v1 version of the grpc-gateway, and for us to be able to stop supporting it. Adding new features to an old release would potentially set a precedent that we accept contributions to this deprecated version.

Note that a new library that just landed yesterday may be able to help users of gogoproto migrate to APIv2: https://github.com/CrowdStrike/csproto. Maybe this could be used by Temporal to migrate to the v2 API?

**Comment by feedmeapples** [comment]
created a fork to address our UI issue as the bug was somewhat critical https://github.com/temporalio/grpc-gateway/

Ideally will look into migrating to v2 possibly using https://github.com/CrowdStrike/csproto as you've suggested. Closing the issue for now thx
