### ISSUE TITLE
protoc-swagger-generator messes up the comments if there is rpc method that does not have rest

### ISSUE THREAD

**Issue by ggeorgiev** [grpc-ecosystem/grpc-gateway#263]
In case there is rpc method that does not support rest api (or does not have option (google.api.http)) the json generation gets confused and misaligns the comment for the methods.

**Comment by tmc** [comment]
this is because (*Registry).loadServices in `github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor/services.go` skips over methods that don't define these mappings so the lookup by index gets off.

we should probably still create `*Method`s with no `Binding`s for this case
