### ISSUE TITLE
how to use different ServeMuxOption to different path??

### ISSUE THREAD

**Issue by misstt123** [grpc-ecosystem/grpc-gateway#2648]
i need a help

**Comment by johanbrandhorst** [comment]
I _think_ you're asking how to serve the grpc-gateway under a specific path? You can use [`http.Handle`](https://pkg.go.dev/net/http#Handle) or a [`http.ServeMux`](https://pkg.go.dev/net/http#ServeMux). You'll need to use [`http.StripPrefix`](https://pkg.go.dev/net/http#StripPrefix) for the gateway to serve the right paths:

```go
http.Handle("/gw/", http.StripPrefix("/gw/", gwMux))
```
