### ISSUE TITLE
Custom values for enum based query params

### ISSUE THREAD

**Issue by fantapop** [grpc-ecosystem/grpc-gateway#2656]
## 🚀 Feature

Ability to set custom names for query param values that map to an enum value.

### Problem I'm trying to solve

We're generating a gprc gateway from a set of protobuf definitions.  In those definitions we use enums that end up directly being used as values in the query params.  As our codebase has grown overtime, it became more apparent that we needed to adopt the [google recommended practice](https://developers.google.com/protocol-buffers/docs/style#enums) of prefixing our enums to avoid collisions in the global enum namespace.  Now some of our enums have PREFIXES_ in front of the values and some don't.  Ideally this hairy detail of how protobuf enums work wouldn't leak out to our api definition.   I was hoping to be able to set a custom mapping or automatically remove a known prefix.

Is there already a way to accomplish this?  As a potential solution, I was thinking there could be an annotation that's added to each enum value to override the name that's used in the api.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. We don't currently support a custom mapping as an annotation, and being honest, I doubt we're going to add a custom one. May I suggest two separate workarounds:

* You can use enum aliases to have multiple enum values in a single enum map to the same value. You just need to enable aliases for your enum. See https://developers.google.com/protocol-buffers/docs/proto3#enum.
* You can implement a custom [QueryParameterParser](https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#QueryParameterParser) and configure it via [SetQueryParameterParser](https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#QueryParameterParser).

Hopefully that makes sense!
