### ISSUE TITLE
Unable to get the first file upload by multipart/form-data

### ISSUE THREAD

**Issue by shivaluma** [grpc-ecosystem/grpc-gateway#2668]
## 🐛 Bug Report

I was not able to get the first file in the multipart form when I try to upload using this guide https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/binary_file_uploads/

## To reproduce

```go
if err := mux.HandlePath("POST", "/v2/apps", (&appExt.AppUpload{
		Config:   config,
		S3:       nil,
		Uploader: uploader,
	}).HandleBinaryFileUpload); err != nil {
		logger.Log.Fatal("failed to start HTTP gateway", zap.String("reason", err.Error()))
		return err
}

func (au *AppUpload) HandleBinaryFileUpload(w http.ResponseWriter, r *http.Request, params map[string]string) {
	r.Body = http.MaxBytesReader(w, r.Body, 500*1024*1024)

	f, header, err := r.FormFile("file")

	logger.Log.Info("File name: ", zap.Any("data", r.MultipartForm))

	if err != nil {
		logger.Log.Error("Error creating multipart reader", zap.Error(err))
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(err.Error()))
		return
	}

	fileName := r.FormValue("filename")

	response, err := json.Marshal(&AppUploadResponse{
		ID:     123,
		Object: "applications",
		Url:    "/v2/apps/" + fileName,
	})

	_, err = au.Uploader.Upload(&s3manager.UploadInput{
		Bucket:      aws.String(au.Config.S3.Bucket),
		Key:         aws.String("thanhvietnguyen/" + params["filename"]),
		Body:        f,
		ContentType: aws.String(header.Header.Get("Content-Type")),
	})

	w.Header().Set("request-id", "12345")
	w.WriteHeader(201)
	w.Write(response)

}

```

If i send a multipart form with a key-value like file-{the file I want to upload}, I receive no data about the form.

About the code and the log when i send with this multipart form 
<img width="519" alt="Screen Shot 2022-04-29 at 18 48 29" src="https://user-images.githubusercontent.com/33391636/165938703-96c53314-c445-497b-8b61-659aaabbd492.png">

## Expected behavior

<img width="671" alt="Screen Shot 2022-04-29 at 18 47 14" src="https://user-images.githubusercontent.com/33391636/165938555-526f1143-c78b-487b-931a-9b113aade503.png">

## Actual Behavior
No err was throw and ` r.MultipartForm` contains value of the `file` in multipart form

## Your Environment

Golang 1.18.1 arm64
Same on Golang 1.18 amd64

**Comment by shivaluma** [comment]
I have tested with gorilla/Mux and a new http server, its work like normal

**Comment by shivaluma** [comment]
Would you mind take a look at this issue @johanbrandhorst

**Comment by johanbrandhorst** [comment]
Do you need to call https://pkg.go.dev/net/http#Request.ParseMultipartForm somewhere?

**Comment by shivaluma** [comment]
The function Request.ParseMultipartForm is called in the request.FormFile function, if I add the request.ParseMultipartForm, the issue still happen, the first file will be lost.

**Comment by johanbrandhorst** [comment]
I'm not sure what the issue is. I'm happy to try to help debug this, but I don't think this is the right place for it. Your problem has nothing to do with the grpc-gateway since you're not even using the example code. This is just a generic Go problem. I would recommend going to the [Gophers Slack ](https://invite.slack.golangbridge.org/) or one of the mailing lists for help. You can find me under `@jbrandhorst` on the Gophers Slack.
