### ISSUE TITLE
Verbose response for Any messages

### ISSUE THREAD

**Issue by Closius** [grpc-ecosystem/grpc-gateway#2676]
I have following .proto:

```protobuf
message NotificationStreaming_response {
    message Evaluation {
        string t_m_resp = 1;
    }
    message Calculation {
        string method = 1;
    }
    message State {
        string name = 1;
        int32 value = 2;
    }
    message Notification {
        string name = 1;
        int32 value = 2;
        google.protobuf.Any data = 3;
    }
    Notification message = 1;
}
```

In the Swagger doc file I have:

![image](https://user-images.githubusercontent.com/10291820/167678396-c00e9c8d-5062-487a-9ce5-11da3d753155.png)

Is it possible to shomehow document State , Calculation , Evaluation  messages as well?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. The generated documentation depends on your RPC definitions, but you havne't included any in your example. Could you share your whole protobuf file?

**Comment by Closius** [comment]
[main.zip](https://github.com/grpc-ecosystem/grpc-gateway/files/8667760/main.zip)

**Comment by Closius** [comment]
`syntax = "proto3";
package myapi;

import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "myapi/grpc_client_web";
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
    info: {
        title: "toolkit";
        version: "0.1.0";
        contact: {
          name: "My API";
          email: "ant.kavalerov@google.com";
    };


  };
  external_docs: {
    url: "myapi/grpc_client_web";
    description: "gRPC-gateway for my API";
  }
  schemes: HTTPS;
};


service MyAPI {
    rpc NotificationStreaming(google.protobuf.Empty) returns (stream NotificationStreaming_response) {
        option (google.api.http) = {
            post: "/api/NotificationStreaming"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            tags: "Notification system"
        };
    }
}


message NotificationStreaming_response {
    message Evaluation {
        string t_m_resp = 1;
    }
    message Calculation {
        string method = 1;
    }
    message State {
        string name = 1;
        int32 value = 2;
    }
    message Notification {
        string name = 1;
        int32 value = 2;
        google.protobuf.Any data = 3;
    }
    Notification message = 1;
}`

**Comment by Closius** [comment]
I I've found a semi-automatic solution:

```protobuf
    rpc NotificationStreaming(google.protobuf.Empty) returns (stream NotificationStreaming_response) {
        option (google.api.http) = {
            post: "/api/NotificationStreaming"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "some descr"
            tags: "Notification system"
            responses: { key: "200"; value: { description: "A successful response.(streaming responses)"; schema: { json_schema: {
                            ref: ".myapi.NotificationStreaming_response";
            }}}}
            responses: { key: "200 @type 0"; value: { description: "State"; schema: { json_schema: {
                            ref: ".myapi.NotificationStreaming_response.State";
            }}}}
            responses: { key: "200 @type 1"; value: { description: "Calculation"; schema: { json_schema: {
                            ref: ".myapi.NotificationStreaming_response.Calculation";
            }}}}
            responses: { key: "200 @type 2"; value: { description: "Evaluation"; schema: { json_schema: {
                            ref: ".myapi.NotificationStreaming_response.Evaluation";
            }}}}
        };
    }
```

**Comment by johanbrandhorst** [comment]
I think the reason it's not showing up in the generated doc is because the message are never used. If you added some new fields to your `NotificationStreaming_response` using the messages then they should show up:

```protobuf
message NotificationStreaming_response {
    message Evaluation {
        string t_m_resp = 1;
    }
    message Calculation {
        string method = 1;
    }
    message State {
        string name = 1;
        int32 value = 2;
    }
    message Notification {
        string name = 1;
        int32 value = 2;
        google.protobuf.Any data = 3;
    }
    Notification message = 1;
    State state = 2;
    Calculation calculation = 3;
    Evaluation evaluation = 4;
}
```

Does that make sense?

**Comment by Closius** [comment]
@johanbrandhorst Not really.. I don't use fields ```state```, ```calculation```, ```evaluation``` in ```NotificationStreaming_response```. That is why the structure which you've proposed will have never used fields which is confusing.

Actually ```Any``` protobuf message might have any kind of message which are defined in .proto which is not really good. Would be nice to have ability to specify which type of messages might be used in the particular ```Any``` filed. Because in the case above if I add another messages. they might be used in ```Any``` field.. And ofcourse in this case it is not possible to generate the swagger file, because this ```Any``` message might be really any..

**Comment by johanbrandhorst** [comment]
If you never use the messages:
1. Why do they exist?
2. Why do you expect them to show up in the swagger.json?

As an alternative to any, might I suggest using a `oneof` field?

**Comment by Closius** [comment]
The reason is pretty simple: I want my field ```data``` has capability to be ```Evaluation``` or ```Calculation``` or ```State``` in different messages. The name of field should not be changed as it happens if I use ```oneof```

**Comment by johanbrandhorst** [comment]
Yeah this is fundamentally impossible with Protobuf, which encourages you to strongly type your APIs. I would encourage you to use a oneof. The JSON representation isn't perfect but it works.
