### ISSUE TITLE
protoc-gen-openapiv2: Description is sometimes not set in parameter spec.

### ISSUE THREAD

**Issue by CHneger** [grpc-ecosystem/grpc-gateway#2681]
## 🐛 Bug Report
I generate swagger for a post method with request body
but the method message has no "parameters.schema.description " field when I set the option " json_schema.description" for the message

## To Reproduce

(Write your steps here:)

1. this is my protobuf
2. 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/38717535/168068152-6b95bf7b-4bd3-4d85-9734-45ebc4261a54.png">

```protobuf
service Test{
    rpc AMethod (AMessage) returns (SomeResponse) {
        option (google.api.http) = {
            post: "/v1/projects/someotherpath"
            body: "*"
        };
    }
    rpc BMethod (AMessage) returns (SomeResponse) {
        option (google.api.http) = {
            post: "/v1/projects/someotherpath/{project_id}"
            body: "*"
        };
    }
}
message AMessage {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        json_schema:{
            title:"TITITI测试时"
            description: "PPPPPP"
        };
    };
    string project_id = 1;
    string other_field = 2;
}
```
3. generated swagger paths  is following:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/38717535/168068442-fcce80b1-3749-498d-bf2f-f70f9d379bbf.png">

## Expected behavior
 "/v1/projects/someotherpath"  and  "/v1/projects/someotherpath/{projectId}" both have a parameter named  [body]  with [schema.description] field 

## Actual Behavior
"/v1/projects/someotherpath/{projectId}" path has a parameter named  [body] with a [schema.description] field
but  "/v1/projects/someotherpath"  parameter named  [body]  has  no   [schema.description] field 

## Your Environment
version is 2.10.0

**Comment by johanbrandhorst** [comment]
I would expect the `description` and `title` for the parameter to `AMethod` to be in the definition of `authorityAMessage`, which is referenced. The reason these two use different schemas is because the second does _not_ allow the `project_id` to be specified in the body, since it is in the path. This is correct behavior. Can you share your whole swagger file? I don't think there's a bug here.

**Comment by CHneger** [comment]
> ```proto
> service Test{
>     rpc AMethod (AMessage) returns (SomeResponse) {
>         option (google.api.http) = {
>             post: "/v1/projects/someotherpath"
>             body: "*"
>         };
>     }
>     rpc BMethod (AMessage) returns (SomeResponse) {
>         option (google.api.http) = {
>             post: "/v1/projects/someotherpath/{project_id}"
>             body: "*"
>         };
>     }
> }
> message AMessage {
>     option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
>         json_schema:{
>             title:"TITITI测试时"
>             description: "PPPPPP"
>         };
>     };
>     string project_id = 1;
>     string other_field = 2;
> }
> ```

This is my whole swagger file
`{
  "swagger": "2.0",
  "info": {
    "title": "kbase/arch/authority/test.proto",
    "version": "version not set"
  },
  "tags": [
    {
      "name": "Test"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/projects/someotherpath": {
      "post": {
        "operationId": "Test_AMethod",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authoritySomeResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/authorityAMessage"
            }
          }
        ],
        "tags": [
          "Test"
        ]
      }
    },
    "/v1/projects/someotherpath/{projectId}": {
      "post": {
        "operationId": "Test_BMethod",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authoritySomeResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "projectId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "otherField": {
                  "type": "string"
                }
              },
              "description": "PPPPPP",
              "title": "TITITI测试时"
            }
          }
        ],
        "tags": [
          "Test"
        ]
      }
    }
  },
  "definitions": {
    "authorityAMessage": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "otherField": {
          "type": "string"
        }
      },
      "description": "PPPPPP",
      "title": "TITITI测试时"
    },
    "authoritySomeResponse": {
      "type": "object"
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string",
          "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n`path/google.protobuf.Duration`). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme `http`, `https`, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n* If no scheme is provided, `https` is assumed.\n* An HTTP GET on the URL must yield a [google.protobuf.Type][]\n  value in binary format, or produce an error.\n* Applications are allowed to cache lookup results based on the\n  URL, or have them precompiled into a binary to avoid any\n  lookup. Therefore, binary compatibility needs to be preserved\n  on changes to types. (Use versioned type names to manage\n  breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com.\n\nSchemes other than `http`, `https` (or the empty scheme) might be\nused with implementation specific semantics."
        }
      },
      "additionalProperties": {},
      "description": "`Any` contains an arbitrary serialized protocol buffer message along with a\nURL that describes the type of the serialized message.\n\nProtobuf library provides support to pack/unpack Any values in the form\nof utility functions or additional generated methods of the Any type.\n\nExample 1: Pack and unpack a message in C++.\n\n    Foo foo = ...;\n    Any any;\n    any.PackFrom(foo);\n    ...\n    if (any.UnpackTo(\u0026foo)) {\n      ...\n    }\n\nExample 2: Pack and unpack a message in Java.\n\n    Foo foo = ...;\n    Any any = Any.pack(foo);\n    ...\n    if (any.is(Foo.class)) {\n      foo = any.unpack(Foo.class);\n    }\n\n Example 3: Pack and unpack a message in Python.\n\n    foo = Foo(...)\n    any = Any()\n    any.Pack(foo)\n    ...\n    if any.Is(Foo.DESCRIPTOR):\n      any.Unpack(foo)\n      ...\n\n Example 4: Pack and unpack a message in Go\n\n     foo := \u0026pb.Foo{...}\n     any, err := anypb.New(foo)\n     if err != nil {\n       ...\n     }\n     ...\n     foo := \u0026pb.Foo{}\n     if err := any.UnmarshalTo(foo); err != nil {\n       ...\n     }\n\nThe pack methods provided by protobuf library will by default use\n'type.googleapis.com/full.type.name' as the type URL and the unpack\nmethods only use the fully qualified type name after the last '/'\nin the type URL, for example \"foo.bar.com/x/y.z\" will yield type\nname \"y.z\".\n\n\nJSON\n====\nThe JSON representation of an `Any` value uses the regular\nrepresentation of the deserialized, embedded message, with an\nadditional field `@type` which contains the type URL. Example:\n\n    package google.profile;\n    message Person {\n      string first_name = 1;\n      string last_name = 2;\n    }\n\n    {\n      \"@type\": \"type.googleapis.com/google.profile.Person\",\n      \"firstName\": \u003cstring\u003e,\n      \"lastName\": \u003cstring\u003e\n    }\n\nIf the embedded message type is well-known and has a custom JSON\nrepresentation, that representation will be embedded adding a field\n`value` which holds the custom JSON in addition to the `@type`\nfield. Example (for message [google.protobuf.Duration][]):\n\n    {\n      \"@type\": \"type.googleapis.com/google.protobuf.Duration\",\n      \"value\": \"1.212s\"\n    }"
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    }
  }
}
`

**Comment by CHneger** [comment]
> 

In fact, the [/v1/projects/someotherpath] path i prefer the parameters is:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/38717535/168199454-529b215e-3265-4552-8e10-d05ecb235550.png">

But there is no [description] field
<img width="614" alt="image" src="https://user-images.githubusercontent.com/38717535/168199578-0549f299-b041-4cb6-aa78-c794e62eee50.png">

**Comment by johanbrandhorst** [comment]
As I said, the description and title appears in your definitions:
```
  "definitions": {
    "authorityAMessage": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "otherField": {
          "type": "string"
        }
      },
      "description": "PPPPPP",
      "title": "TITITI测试时"
    },
    "authoritySomeResponse": {
      "type": "object"
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string",
          "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n`path/google.protobuf.Duration`). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme `http`, `https`, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n* If no scheme is provided, `https` is assumed.\n* An HTTP GET on the URL must yield a [google.protobuf.Type][]\n  value in binary format, or produce an error.\n* Applications are allowed to cache lookup results based on the\n  URL, or have them precompiled into a binary to avoid any\n  lookup. Therefore, binary compatibility needs to be preserved\n  on changes to types. (Use versioned type names to manage\n  breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com.\n\nSchemes other than `http`, `https` (or the empty scheme) might be\nused with implementation specific semantics."
        }
      },
      "additionalProperties": {},
      "description": "`Any` contains an arbitrary serialized protocol buffer message along with a\nURL that describes the type of the serialized message.\n\nProtobuf library provides support to pack/unpack Any values in the form\nof utility functions or additional generated methods of the Any type.\n\nExample 1: Pack and unpack a message in C++.\n\n    Foo foo = ...;\n    Any any;\n    any.PackFrom(foo);\n    ...\n    if (any.UnpackTo(\u0026foo)) {\n      ...\n    }\n\nExample 2: Pack and unpack a message in Java.\n\n    Foo foo = ...;\n    Any any = Any.pack(foo);\n    ...\n    if (any.is(Foo.class)) {\n      foo = any.unpack(Foo.class);\n    }\n\n Example 3: Pack and unpack a message in Python.\n\n    foo = Foo(...)\n    any = Any()\n    any.Pack(foo)\n    ...\n    if any.Is(Foo.DESCRIPTOR):\n      any.Unpack(foo)\n      ...\n\n Example 4: Pack and unpack a message in Go\n\n     foo := \u0026pb.Foo{...}\n     any, err := anypb.New(foo)\n     if err != nil {\n       ...\n     }\n     ...\n     foo := \u0026pb.Foo{}\n     if err := any.UnmarshalTo(foo); err != nil {\n       ...\n     }\n\nThe pack methods provided by protobuf library will by default use\n'type.googleapis.com/full.type.name' as the type URL and the unpack\nmethods only use the fully qualified type name after the last '/'\nin the type URL, for example \"foo.bar.com/x/y.z\" will yield type\nname \"y.z\".\n\n\nJSON\n====\nThe JSON representation of an `Any` value uses the regular\nrepresentation of the deserialized, embedded message, with an\nadditional field `@type` which contains the type URL. Example:\n\n    package google.profile;\n    message Person {\n      string first_name = 1;\n      string last_name = 2;\n    }\n\n    {\n      \"@type\": \"type.googleapis.com/google.profile.Person\",\n      \"firstName\": \u003cstring\u003e,\n      \"lastName\": \u003cstring\u003e\n    }\n\nIf the embedded message type is well-known and has a custom JSON\nrepresentation, that representation will be embedded adding a field\n`value` which holds the custom JSON in addition to the `@type`\nfield. Example (for message [google.protobuf.Duration][]):\n\n    {\n      \"@type\": \"type.googleapis.com/google.protobuf.Duration\",\n      \"value\": \"1.212s\"\n    }"
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    }
  }
```

I still don't see a bug here, so I'm going to close this issue. Please feel free to reply if you still need more help.

**Comment by olegvelikanov** [comment]
Hi, @johanbrandhorst
I was looking for an opportunity to contribute a little into an open source project and eventually decided to try to fix this bug.  This is my first attempt to participate in open source, so I may be wrong about something. I will be glad to receive any feedback.
PR - https://github.com/grpc-ecosystem/grpc-gateway/pull/2773
