### ISSUE TITLE
Request to GRPC handler fails when calling gateway with curl --http2-prior-knowledge

### ISSUE THREAD

**Issue by majelbstoat** [grpc-ecosystem/grpc-gateway#2682]
## 🐛 Bug Report

When trying to use Cloud Run to serve the gateway and GRPC from the same port, you must enable Cloud Run's http2 end to end support. This requires that the server support being called like `curl -i --http2-prior-knowledge`

Common guides for serving GRPC and HTTP on the same port use cmux as an example. However, cmux is not usable for GCP Cloud Run because it works at the connection layer and Cloud Run reuses the same connection for different protocols. An alternative approach is described [here](https://ahmet.im/blog/grpc-http-mux-go/).

Using that approach, I have a grpc-gateway server that, when called with curl -i -http2-prior-knowledge, correctly:

a) Serves GRPC directly, and can be connected to by grpcui,
b) Serves additional HTTP handlers added to the runtime.ServeMux, and
c) Serves grpc-gateway GET requests that call a GRPC Handler.

However, when calling a grpc-gateway POST endpoint in the same way, and using for example `--data-raw={"field":"value"}`, I get the error `stream terminated by RST_STREAM with error code: PROTOCOL_ERROR`.

## To Reproduce

1. Follow the guide above, but replace the httpHandler with a simple grpc-gateway server.
2. curl -i --http2-prior-knowledge on your GET endpoint.
3. Observe that it works
4. curl -i --http2-prior-knowledge your POST endpoint.

## Expected behavior

The GRPC request is served as expected from a POST endpoint.

## Actual Behavior

stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

## Your Environment

I can reproduce this in Cloud Run, and locally on macos running go 1.18.

**Comment by majelbstoat** [comment]
Ok, so, not actually a bug in grpc-gateway, so I'll close, and leave this for posterity.

I traced the error down to the length of the GRPC request body not matching the supplied Content-Length header. The h2s server was failing to read the body because of that (https://cs.opensource.google/go/x/net/+/2871e0cb:http2/server.go;l=1713). That error was swallowed by grpc somewhere and turned into the obscure stream termination error.

The reason the Content-Length header didn't match is because I had set an incomingHeaderMatcher to propagate some headers as-is, and Content-Length was one of them. Thus, the Content-Length that the GRPC server was receiving was the one originally sent to the gateway.

This explains why it worked for GET requests - the Content-Length header for the request to the gateway wasn't set, so it wasn't propagated incorrectly.

Thank you for inadvertently being my rubber duck! 🦆

**Comment by johanbrandhorst** [comment]
This is very interesting, thanks for sharing!

**Comment by TimelyToga** [comment]
Thank you @majelbstoat for the solution. 

This is what I had before: 

```go
func CustomHeaderMatcher(key string) (string, bool) {
	key = strings.ToLower(key)
	switch key {
	case someSpecificKeys, someOtherKey:
		return key, true
       // Other filters
	default:
		return key, true
	}
}
```

Then just added a case for `content-length`: 

```go
func CustomHeaderMatcher(key string) (string, bool) {
	key = strings.ToLower(key)
	switch key {
	case someSpecificKeys, someOtherKey:
		return key, true
	case "content-length":
		return key, false
// Other filters
	default:
		return key, true
	}
}
```
