### ISSUE TITLE
Equivalent paths are not allowed.

### ISSUE THREAD

**Issue by jackwootton** [grpc-ecosystem/grpc-gateway#2683]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)
Invalid OpenAPI specifications are generated when the same path is used for different HTTP verbs.

This issue has previously been reported and closed: https://github.com/grpc-ecosystem/grpc-gateway/issues/1486.

Is there a workaround? Can the previous issue be reopened?

Unfortunately this behavior seems to 

## To Reproduce

See https://github.com/grpc-ecosystem/grpc-gateway/issues/1486.

## Expected behavior

A valid swagger definition should be generated

## Actual Behavior

Various Open API validators report that "Equivalent paths are not allowed".

## Your Environment

linux/amd64

**Comment by johanbrandhorst** [comment]
Reopening the other issue instead
