### ISSUE TITLE
Ignore buf lint comment in swagger definition title

### ISSUE THREAD

**Issue by davix** [grpc-ecosystem/grpc-gateway#2684]
## 🐛 Bug Report

The definition title in swagger uses comment as title, but even if the comment is buf lint, it still uses the lint comment as title.

## To Reproduce

Given below message with inline buf ignore
```
// buf:lint:ignore FIELD_LOWER_SNAKE_CASE
message GetDataResponse {
}
```

## Expected behavior

The generated swagger title should ignore the buf:lint and use `GetDataResponse`.

## Actual Behavior

The title is `// buf:lint:ignore FIELD_LOWER_SNAKE_CASE`

**Comment by johanbrandhorst** [comment]
I doubt there is much we can do here. You can override the title explicitly with the openapi annotations: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto#L237.

**Comment by wei-huang-aruba** [comment]
@johanbrandhorst , yeah, explicit annotation can do this. But everywhere else the default generated swagger has been quite well, just because of introducing `buf lint`, good experience is gone.
Still suggest to consider ignoring buf comments!

**Comment by davix** [comment]
@johanbrandhorst , yeah, explicit annotation can do this. But everywhere else the default generated swagger has been quite well, just because of introducing buf lint, good experience is gone.
Still suggest to consider ignoring buf comments!
