### ISSUE TITLE
Turn off camelCase in swagger file generation

### ISSUE THREAD

**Issue by Closius** [grpc-ecosystem/grpc-gateway#2690]
Hello,

I'm trying to use field names with underscores. Here is my .proto file:

![image](https://user-images.githubusercontent.com/10291820/168811816-6df790a8-02c6-4551-8084-2b9f31d931ab.png)

But after generation swagger I have camelCase:

![image](https://user-images.githubusercontent.com/10291820/168811223-ad595b3a-b7cd-4434-95b5-5f889fca1fef.png)

In generated _pb2.* file I have correct field names with underscores:

![image](https://user-images.githubusercontent.com/10291820/168812220-226a844b-f702-4510-9af2-72e809056577.png)

Is it possible to fix?

**Comment by johanbrandhorst** [comment]
The default JSON representation for Protobuf is camelcase. See https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/#we-now-use-the-camelcase-json-names-by-default for how to get snake_case.

**Comment by Closius** [comment]
Thank you so much!
