### ISSUE TITLE
protoc-gen-openapiv2: RPC visibility setting is not transitively applied to request and response messages

### ISSUE THREAD

**Issue by elb3k** [grpc-ecosystem/grpc-gateway#2691]
## 🐛 Bug Report

Definitions of some internal only grpc request/responses are still visible on generated spec.
Even if endpoints are specifically marked as `INTERNAL` using `option (google.api.method_visibility).restriction = "INTERNAL";`

## To Reproduce

Sample proto defintions:
```proto
syntax = "proto3";
option go_package = "sample.service";
package service;

import "protoc-gen-openapiv2/options/annotations.proto";
import "google/api/annotations.proto";
import "google/api/visibility.proto";

message HelloRequest {
    string name = 1;
}

message HelloReply {
    string message = 1;
}

message ByeRequest {
    string name = 1;
}

message ByeReply {
    string message = 1;
}

service Service {
    rpc Hello(HelloRequest) returns (HelloReply){
        option (google.api.method_visibility).restriction = "INTERNAL";
        option (google.api.http) = {
            post: "/hello"
            body: "*"
          };
          option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "Sample message",
          };
    }

    rpc Bye(ByeRequest) returns (ByeReply){
        option (google.api.http) = {
            post: "/bye"
            body: "*"
          };
          option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "Sample message",
          };
    } 
}
```
buf.yaml:
```yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
breaking:
  use:
    - FILE
```
buf.gen.yaml:
```yaml
version: v1
plugins:
  - name: openapiv2
    out: oapi
    opt:
      - json_names_for_fields=false
```

generated `sample.swagger.json`
```json
....
"definitions": {
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "serviceByeReply": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "serviceByeRequest": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "serviceHelloReply": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
....
```

You can see it is generating definition for `serviceHelloReply`, which is only used in `rpc Hello`, and explicitly set as `INTERNAL`.
It is not desired to disclose response of `INTERNAL` endpoint to public oapi spec.

## Expected behavior
Criteria for the visibility of message should be:
1. It is used on public endpoint (may be inside another message).
1. Not explicitly set as `INTERNAL,BETA,...`

## Actual Behavior

As one can see from the example, definition of `HelloReply` is still present in generated file.

## Your Environment

- Ubuntu 20.04
- GRPC Gateway v2.10.0
- Buf 1.4.0
- Go 1.18.1

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! Indeed, hiding of objects is not transitive right now, which seems to be what you expect here (if the service is hidden, so should it's messages). Is that right? This would be cool to add, but it's probably going to be quite complicated, so the easier workaround is obviously to mark both the RPC and the Message as internal. Have you tried that?

**Comment by elb3k** [comment]
> Hi, thanks for your issue! Indeed, hiding of objects is not transitive right now, which seems to be what you expect here (if the service is hidden, so should it's messages). Is that right? This would be cool to add, but it's probably going to be quite complicated, so the easier workaround is obviously to mark both the RPC and the Message as internal. Have you tried that?

Right, I know it is gonna be a big change. Have tried to set `(google.api.message_visibility).restriction = 'INTERNAL` for the internal messages, but no luck. And I thought that `message_visibility` was not used in openapi, is it?

**Comment by johanbrandhorst** [comment]
Ah, I spoke too soon, message visibility is not yet supported. The visibility setting is _only_ used in our openapi generation, it doesn't actually ignore a field/message/rpc in the handlers.

It might be possible to support message visibility but I assume there was a reason it wasn't added with the others in https://github.com/grpc-ecosystem/grpc-gateway/pull/2578 CC @BCook98.

Would you be willing to help implement this?

**Comment by elb3k** [comment]
Yeah

> Ah, I spoke too soon, message visibility is not yet supported. The visibility setting is _only_ used in our openapi generation, it doesn't actually ignore a field/message/rpc in the handlers.
> 
> It might be possible to support message visibility but I assume there was a reason it wasn't added with the others in #2578 CC @BCook98.
> 
> Would you be willing to help implement this?

Yeah

**Comment by erademacher** [comment]
Hi. This is impacting my team as well, but I'm confused as to why the fix needs to be complicated. Currently, if a message isn't used by any methods, it doesn't make its way into the spec. Couldn't you simply treat hidden methods as nonexistent?

**Comment by erademacher** [comment]
Skipping hidden methods when walking the dependency tree seems to work!
https://github.com/grpc-ecosystem/grpc-gateway/pull/2868
