### ISSUE TITLE
Installation instruction for scala gRPC project would be highly appreciated

### ISSUE THREAD

**Issue by ShellyWEI** [grpc-ecosystem/grpc-gateway#2696]
## 📚 Documentation

Hi team,

According to the FAQ, it's possible to use grpc-Gateway in a scala gRPC server: https://grpc-ecosystem.github.io/grpc-gateway/docs/faq/#my-grpc-server-is-written-in-scala-or-c-or-ruby-or-haskell-etc-is-there-a-scala-or-c-or-ruby-or-haskell-etc-version-of-grpc-gateway
However, I am having a hard time pulling grpc-Gateway into my project. An installation instruction for scala would be highly appreciated!

The current issue I have is the below error
```
[info] Compiling 1 protobuf files to /Users/workspace/servo-service/target/scala-2.13/src_managed/main/scalapb
servo.proto:10:1: warning: Import google/api/annotations.proto is unused.
[info] compiling 1 Scala source to /Users/workspace/servo-service/target/scala-2.13/classes ...
[error] /Users/workspace/servo-service/target/scala-2.13/src_managed/main/scalapb/servo/ServoProto.scala:11:20: object annotations is not a member of package com.google.api
[error]     com.google.api.annotations.AnnotationsProto
[error]                    ^
[error] /Users/workspace/servo-service/target/scala-2.13/src_managed/main/scalapb/servo/ServoProto.scala:185:22: object annotations is not a member of package com.google.api
[error]       com.google.api.annotations.AnnotationsProto.javaDescriptor
[error]                      ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
```

after adding the below dependency into "protoc.sbt":
`libraryDependencies += "com.google.api.grpc" % "googleapis-common-protos" % "0.0.3" % "protobuf"`

I was following the second installation option from Readme file: "additional .proto modifications to use a custom mapping" and was trying to import "google/api/annotations.proto"

Thanks!

**Comment by johanbrandhorst** [comment]
Hi, thank you for your issue! I'm not sure how much we'll be able to help here, but I want to note a few things that might be able to help you:

- If you want to use any openapiv2 annotations, you'll need to generate scala files for our protobuf files. This is probably easiest to do by using `buf`. With a `buf.gen.yaml`:
   ```
   $ buf generate buf.build/grpc-ecosystem/grpc-gateway
   ```
- You seem to be using `googleapis-common-protos`. I assume this is named after https://github.com/googleapis/api-common-protos, which is [deprecated](https://github.com/googleapis/api-common-protos/issues/88#issuecomment-814242096). You should probably just use `googleapis` (if it exists).

No idea about your particular error.
