### ISSUE TITLE
support for ARM64 (Mac M1)

### ISSUE THREAD

**Issue by namqdam** [grpc-ecosystem/grpc-gateway#2705]
## 🚀 Feature

Using `go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway` does not install protoc-gen-grpc-gateway binary file in go bin.
Please add support for Mac ARM processors.

**Comment by johanbrandhorst** [comment]
On recent Go versions you'll need to use `go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest` to install the binary into your Go bin. It should definitely work for ARM processors already, but yt ou make a good point about adding pre-built binaries for ARM64.

**Comment by johanbrandhorst** [comment]
Done https://github.com/grpc-ecosystem/grpc-gateway/commit/d161009efb445a1a4a14ec9518463382f0a7c257
