### ISSUE TITLE
the latest version can not build with go1.16,  should update to go 1.17

### ISSUE THREAD

**Issue by chengyizhoucode** [grpc-ecosystem/grpc-gateway#2713]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/54266096/170167097-60bf7ea0-7aad-4346-ac9b-c320f1d8e549.png)

## To Reproduce

(Write your steps here:)

go build will fail, the error is  "go:build comment without // +build "

## Your Environment

go 1.16

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I'm confused, but I _think_ what you're saying is that you're trying to build with Go 1.16 and you're getting an error. I don't know what the shared screenshot is supposed to illustrate. I assume the error is here: https://github.com/grpc-ecosystem/grpc-gateway/blob/32ac6fd93a3c9ef9597956500d45194501450a9c/runtime/query_fuzz_test.go#L1?

We currently only test with go 1.17 and go 1.18, but 1.16 sounds reasonable since we do expose a library. Would you be willing to contribute this fix?

**Comment by johanbrandhorst** [comment]
> Thanks @johanbrandhorst. It looks like there's a similar case in `examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go:19` (I guess a generated file?). Probably best to add Go 1.16 to CI if you want to support this (I'd recommend it ... not everyone can or has upgraded to Go 1.17/1.18 easily).

I'm confused, I don't see any build tags in there? This file: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go#L19?

**Comment by benhoyt** [comment]
Oh, sorry, I was confused by the output of `go test ./...` with Go 1.16:

```
$ go1.16.15 test ./...
examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go:19:2: //go:build comment without // +build comment
examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go:19:2: //go:build comment without // +build comment
```

It's referring to the build constraint of the imported package, which is the `runtime` one you've already fixed.

**Comment by chengyizhoucode** [comment]
> I believe this was broken with the release of version v2.10.2, when that fuzz file was introduced. See also https://stackoverflow.com/a/72455753/68707. All that needs to happen is to add a `// +build go1.18` line below the `//go:build go1.18` one, similar to [this file](https://github.com/benhoyt/goawk/blob/932202d8dd959cebd0eebfe063f65a3a5d9ed66b/interp/fuzz_test.go#L3-L4).

year,   that is what wo want to  say , 
I also agree with this solution
haha ha

**Comment by johanbrandhorst** [comment]
PSA: Since 1.19 is released, the new release of the grpc-gateway will require Go 1.17+. I hope this is acceptable to you.
