### ISSUE TITLE
feature request / idea: generating JSONRPC2 client proxies from GRPC

### ISSUE THREAD

**Issue by joeblew99** [grpc-ecosystem/grpc-gateway#272]
I noticed that this code gens a swagger document from which you can use the swagger project to generate client proxy code. All great but i am thinking that code generating JSONRPC2 from GRPC is a much tighter match.

Essentially my clients are coded in Dart and dart has great support for JSONRPC2.
There is not GRPC support yet, and it looks a long way off because of web browser issues. Long story.

So, from my basic checking, it looks like GRPC --> JSONRPC2 is pretty simple translation.
Here is a great example of 2 in pure GRPC & JSONRPC2:
https://blog.gopheracademy.com/advent-2015/etcd-distributed-key-value-store-with-grpc-http2/

It shows how GRPC and JSONRPC2 is so similar, and so its reasonable to conclude that Client code that is generated will also be similar.

Curious what other people think..

**Comment by achew22** [comment]
@joeblew99 Thanks for your interest in the project. Unfortunately it doesn't look like anyone has the time/energy combined with the need to implement this. The two solutions (gRPC and JSONRPC2) are similar enough that, for my use case, I'm happy to just use gRPC. If you're interested in taking that task on, I would personally be interested in seeing your implementation. This project may not be the right place for it. Feel free to add me to a PR in a new repo if you decide to take this task on.

I'm also going to close the issue to help keep things tidy but I hope to see you around in the future.
