### ISSUE TITLE
Pre-fill request parameters

### ISSUE THREAD

**Issue by sir-farfan** [grpc-ecosystem/grpc-gateway#2722]
## 📚 Documentation

I went a little through the [custom output](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/) page but didn't find if it's possible or not.

Can I somehow set default/sample values for (mandatory) parameters?

Let's say, in the following example, I'd like the values in the required parameters to be already in the text box when I click "try it out". I know comments already shows above the field :)

```
message UserInfoReq {
  // use account abc1234 for testing
  string user_id = 1 [ (validate.rules).string.min_len = 3 ];
  // try out with 2022-02-20T10:00:20.021Z
  google.protobuf.Timestamp from_date = 2 [ (validate.rules).timestamp.required = true ];
  string scope = 3;
}

message OK {
  int32 status=1;
}

service InfoService {
  rpc InfoReq(UserInfoReq) returns (OK) {
    option (google.api.http) = {
      get : "/UserInfoReq"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary : "User info"
      description : "Get details about the user"
    };
  }
}
```

**Comment by johanbrandhorst** [comment]
Might be able to use the `default`? https://github.com/grpc-ecosystem/grpc-gateway/blob/dca9acb8fd17aead94aed83e259c6d690a763b8a/examples/internal/proto/examplepb/a_bit_of_everything.proto#L295-L301

**Comment by sir-farfan** [comment]
Thanks, that's what I was looking for :)
