### ISSUE TITLE
Upgrading from v2.10.0 to v2.10.3 causes BUILD error for `protoc_gen_openapiv2` build rule.

### ISSUE THREAD

**Issue by togiles** [grpc-ecosystem/grpc-gateway#2770]
## 🐛 Bug Report

The following error is seen upon upgrading from v2.10.0 to v2.10.3:

```
every rule of type protoc_gen_openapiv2 implicitly depends upon the target '@com_google_protobuf//:well_known_type_protos', but this target could not be found because of: no such target '@com_google_protobuf//:well_known_type_protos': target 'well_known_type_protos' not declared in package '' defined by /private/var/tmp/_bazel_tgiles/fa974e1be95e4cc589c5b71ea3a3a4aa/external/com_google_protobuf/BUILD
```

## To Reproduce

Upgrade version, attempt to build any of our `protoc_gen_openapiv2` bazel build targets, get the above error.

## Expected behavior

The build to succeed.

## Actual Behavior

Error :(

## Your Environment

bazel build system

**Comment by johanbrandhorst** [comment]
Argh, sorry for this. It seems my fix in https://github.com/grpc-ecosystem/grpc-gateway/pull/2716 caused problems after all. I'm not entirely sure what the appropriate fix is, let me summon our Bazel expert, @achew22 :).

**Comment by johanbrandhorst** [comment]
https://github.com/protocolbuffers/protobuf/pull/9988#issuecomment-1139140818 might have a clue.

**Comment by togiles** [comment]
It looks like upgrading our protobuf version from 3.19.1 to 3.21.1 fixes this - so just a version mismatch between two libraries.

**Comment by johanbrandhorst** [comment]
Thanks for following up with your fix!
