### ISSUE TITLE
Class name is prefixed with package name

### ISSUE THREAD

**Issue by pkohout** [grpc-ecosystem/grpc-gateway#2778]
## 🚀 Feature

Hi,
if I have the following gRPC service method, which uses a class from a different package, the class names that are generated are not nice to read.

```
  rpc RemoveHost(HostId) returns (api_host_to_fcs.ResponseStatus) {
    option (google.api.http) = {
      post: "/v1/remove-host"
      body: "*"  // puts all message fields in body
    };
  }
```
The resulting OpenApi class looks like the following:
```
    "api_host_to_fcsResponseStatus": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/definitions/ResponseStatusCode",
          "description": "Response status code"
        },
        "message": {
          "type": "string",
          "description": "Optional message describing the returned status code."
        }
      }
    },
```

Is it possible to get rid of the `api_host_to_fcs` in front of the ResponseStatus? If not, is it planned to support something like this in the future?
So the result I would like would be the following:
```
    "ResponseStatus": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/definitions/ResponseStatusCode",
          "description": "Response status code"
        },
        "message": {
          "type": "string",
          "description": "Optional message describing the returned status code."
        }
      }
    },
```

Thanks a lot,
Peter

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I'm not sure, but maybe you can change the generated title using the `title` annotation of the message? See https://github.com/grpc-ecosystem/grpc-gateway/blob/0ebdfba80649c56b0da0777376c970d17c3c9540/examples/internal/proto/examplepb/a_bit_of_everything.proto#L237 for an example.

**Comment by pkohout** [comment]
I checked out the example you refered here, but also here the generaded model has the name: `examplepbABitOfEverything` where `examplepb` is the package name.

**Comment by johanbrandhorst** [comment]
Good point, but that has reminded me that we have a separate option for this in the generator: [`openapi_naming_strategy`](https://github.com/grpc-ecosystem/grpc-gateway/blob/6d7d485a14951c9cf314d1926362044b7d289853/protoc-gen-openapiv2/main.go), which can take either `legacy`, `fqn` or `simple`. I should thing `openapi_naming_strategy=simple` might do what you want.

**Comment by pkohout** [comment]
@johanbrandhorst Thanks a lot, changing the `openapi_naming_strategy` to `simple` worked!

Now the message looks like the following:

```
    "ResponseStatus": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/definitions/Code",
          "description": "Response status code"
        },
        "message": {
          "type": "string",
          "description": "Optional message describing the returned status code."
        }
      }
    },
```
which is exaclty what I wanted!

**Comment by johanbrandhorst** [comment]
Glad to hear it :). Would you be willing to contribute something to our docs to help others discover this feature?

**Comment by pkohout** [comment]
> Glad to hear it :). Would you be willing to contribute something to our docs to help others discover this feature?

Sure, but I am on vaccation right now, but will create a PR once I am back in the office. Will happen at the begin of August.
