### ISSUE TITLE
Cut another release

### ISSUE THREAD

**Issue by gyuho** [grpc-ecosystem/grpc-gateway#278]
Could somebody cut another release with latest commits?
etcd is trying to vendor `grpc-gateway` with tagged version.

Reference https://github.com/coreos/etcd/issues/4821.

Thanks!

**Comment by achew22** [comment]
@yugui I think it is about time that we cut another release for grpc-gateway as well. If you would like I can tag and push a release annotated with a changelog. Would you like me to do that?

**Comment by xiang90** [comment]
@yugui Can we cut a new release?

**Comment by tzneal** [comment]
@tmc @yugui I would appreciate a new release tag as well.

**Comment by tmc** [comment]
I think this is satisfied with v1.2.0.
