### ISSUE TITLE
What is the best way to know if a request came via HTTP?

### ISSUE THREAD

**Issue by alcortesm** [grpc-ecosystem/grpc-gateway#2783]
## 📚 Documentation

This is not an issue but a question, apologies if this is not the right place for questions.

Let's say you are writing a handler for a gRPC server. What would be the best way to know if the request came via HTTP instead of gRPC?

The best solution I have been able to find so far is to check for the presence of the headers the reverse proxy adds to the incoming requests (`X-Forwarded-For`, `X-Forwarded-Host`). But it looks brittle and not too reliable, for example, a gRPC client can also add those same headers to its original request, tricking me into thinking the request came via HTTP instead of gRPC.

Maybe I could add some middleware to the reverse proxy to inject my own header instead of relying on the default ones.

I understand one of the goals of grpcgateway is not having to care if the request came via HTTP or gRPC, but I'm trying to use grpcgateway in a legacy environment where this distinction is important.

Any suggestions?

**Comment by johanbrandhorst** [comment]
Hi Alberto, thanks for your issue! Your suggested solution, checking for one of the grpc metadata values that the grpc-gateway adds automatically is the easiest solution. Naturally, as you say, if you cannot _trust_ clients to your gRPC server, you cannot tell the difference between a gRPC request that was forwarded by the gateway and one that was formed by an attacker. If this is really the case, you have two options:

* Add a [WithMetadata](https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#WithMetadata) option to your `ServeMux` initialization that sets some secret agreed-upon-value for every request. In your gRPC server, you can check for the presence of this value. Naturally, this is only as safe as your ability to keep the secret value secret.
* Set up the grpc-gateway gRPC client with a client-side certificate and perform server side validation of the clients certificate. This conversely requires you to maintain a PKI infrastructure for your client and server, and is going to be more work than the other option, but also safer, as there is now no secret material exchanged over the client-server connection (the grpc-gateway clients private key has to be kept secret, obviously).

Hope that helps!

**Comment by alcortesm** [comment]
Thanks for your answer Johan, the details and approaches you describe are very helpful, it is exactly what I need to move forward with my design.
