### ISSUE TITLE
Catching the code 5 : Not Found

### ISSUE THREAD

**Issue by sir-farfan** [grpc-ecosystem/grpc-gateway#2785]
## 🚀 Feature

Is there a way to catch requests on unknown endpoints to log and customize the response (optional)?

I tried playing around with HandlePath() and a few of the runtime.DefaultXXX() functions without much success.

I discovered I can use Gorilla Mux together with Gateway but the later handles the Not Found before Gorilla knows about it, so the handler never gets called.

Any advice?

```go
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

func main() {
	port := ":8000"
	gateway := runtime.NewServeMux()
	r := mux.NewRouter()

	r.PathPrefix("/").Handler(gateway)
	// r.PathPrefix("/api/").Handler(gateway)
	r.NotFoundHandler = http.HandlerFunc(NotFound)

	log.Printf("Starting gorilla/gateway at %s\n", port)
	log.Println("try curl localhost:8000/bla")
	_ = http.ListenAndServe(port, r)
}

func NotFound(w http.ResponseWriter, r *http.Request) {
	log.Println("stdout -> I don't know such endpoint")
	_, _ = w.Write([]byte("http -> I don't know such endpoint"))
}
```

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I think you can use https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#WithRoutingErrorHandler?
