### ISSUE TITLE
Extracting path pattern in HTTP middlewares

### ISSUE THREAD

**Issue by spy16** [grpc-ecosystem/grpc-gateway#2787]
## 📚 Documentation

We are trying to add a middleware (i.e., `func (next http.Handler) http.Handler`) to the gateway instance to add some instrumentation. For this we need to be able to extract the path-pattern. 

We came across [Operations / Extracting the HTTP path pattern for a request](https://grpc-ecosystem.github.io/grpc-gateway/docs/operations/annotated_context/) which has a snippet on how to use `runtime.WithMetadata()`. Initially it looked like what we need. But we are not able to figure out how to get that metadata back in our middleware.

```golang
wrappedHandler := http.HandlerFunc(func(wr http.ResponseWriter, req *http.Request) {
        // how do we get the path-pattern here?
       pathPattern, ok := runtime.HTTPPathPattern(req.Context())
       // ^ this does not work because annotation is happening inside the below ServeHTTP()
 
        gatewayInstance.ServeHTTP(wr, req)
})
```

**Comment by johanbrandhorst** [comment]
I think you will need to get the metadata in your gRPC handler, not as a HTTP middleware. Does that work? I agree the documentation is not clear. In any case, you will need to call `runtime.HTTPPathPattern` _after_ the gRPC gateway handler has had a chance to add the information to the context.

**Comment by spy16** [comment]
yea, I went  through the implementation of `RegisterXXX` functions. It looks like the context is annotated just before the RPC server implementation is invoked. So only place I can extract this information is inside the RPC handler implementation. 

I would just leave this feedback here (may be in future versions when this goes through a refactor or something): It would be awesome to be able to have some way to have a hook right after AnnotateContext() and before the gRPC server is invoked so that middleware-like patterns can be built.

**Comment by johanbrandhorst** [comment]
If you're working at the HTTP middleware level, at least you have access to the request path through `req.URL.Path` :). If you think there's anything we can add to the docs, please open a PR and I would be happy to review it.
