### ISSUE TITLE
Option to Allow Swagger for DELETEs with a body

### ISSUE THREAD

**Issue by msample** [grpc-ecosystem/grpc-gateway#279]
Retro-specifying some legacy REST services in GRPC+REST annotations causes swagger generation from the GRPC to fail when rpc methods use http delete and have a request body.   

Using a body with delete is certainly bad style so this check should not be implicitly disabled.  I have a PR  #280 that adds a bool "allow_delete_body" plugin parameter that defaults to false.

**Comment by tmc** [comment]
The related issue is merged now.
