### ISSUE TITLE
What does rpc error: code = Unknown desc = not support mean?

### ISSUE THREAD

**Issue by richzw** [grpc-ecosystem/grpc-gateway#2807]
We got the following error 

`rpc error: code = Unknown desc = not support`

from 

```go
func CustomHTTPError(ctx context.Context, _ *runtime.ServeMux, marshaler runtime.Marshaler, rsp http.ResponseWriter, req *http.Request, err error) {
	log.error("grpc gateway error = %+v, uri=%+v", err, req.URL.Path)
}

mux := runtime.NewServeMux(
	runtime.WithErrorHandler(CustomHTTPError),
       ....
```
After searching the codes of gRPC and gRPC-gateway, we failed to find the error `desc = not support`. Could someone help us or something is missing?

grpc-gateway v1.3.1
grpc v1.38.0

**Comment by johanbrandhorst** [comment]
This isn't an error that's returned by the grpc-gateway, it must be something that one of your gRPC server handlers is responding with.
