### ISSUE TITLE
How to specify OpenAPI configuration file when merging multiple protos into single OpenAPI file?

### ISSUE THREAD

**Issue by kkolur** [grpc-ecosystem/grpc-gateway#2808]
**Question:** How do I specify the `file` in [OpenAPI configuration file](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/unannotated_echo_service.swagger.yaml#L4) when working with and merging multiple generated open api yamls into one single file?

**Context:**
Currently, I have a script that finds all proto files that end in `api.proto` in the directory `./proto/api `and generates a single open api file by merging all of the outputs. There are basically three proto files in `PROTOS`: `main_api.proto`, `sub_api.proto`, `internal_api.proto`:
```
PROTOS=$(find ./proto/api -type f -name "*api.proto" -print)

protoc \
    -I=proto \
    --openapiv2_out $OUTPUT_DIR \
    --openapiv2_opt grpc_api_configuration=api.yaml \
    --openapiv2_opt allow_merge=true \
    --openapiv2_opt merge_file_name=api \
    --openapiv2_opt output_format=yaml \
    $PROTOS
```

The above works. Now, I want to introduce an OpenAPI Configuration file `api.swagger.options.yaml` so that I can set the title of the OpenAPI, so I added this `opt` to the above `protoc` command: `--openapiv2_opt openapi_configuration=api.swagger.options.yaml \`

Here is snippet of `api.swagger.options.yaml`:
```
openapiOptions:
  file:
    # the file name must be the same as one passed to protoc when generating generating .swagger.json
    - file: "./proto/api/main_api.proto"
      option:
        info:
          title: API Service
```

First, since im merging all of the outputs of the files in `PROTOS` into a single file, I do not know what to supply for the `file` flag in `api.swagger.options.yaml`. 
Im getting this error even though `./proto/api/main_api.proto` exists:
`--openapiv2_out: failed to register option in api.swagger.options.yaml: no file ./proto/api/main_api.proto found`

**Comment by johanbrandhorst** [comment]
Hi Kishan, thanks for your issue! I frankly have no idea how these two options interact, so it doesn't surprise me that it's confusing to you. Sorry about that! I believe we recently did some work on how the file merge treats openapi annotations, but that was with annotations set as proto options inside each file. I know this case works, so is that an option for you? I.e., instead of using an external file, put the options inside one of the files, like this: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto#L19.

**Comment by kkolur** [comment]
> Hi Kishan, thanks for your issue! I frankly have no idea how these two options interact, so it doesn't surprise me that it's confusing to you. Sorry about that! I believe we recently did some work on how the file merge treats openapi annotations, but that was with annotations set as proto options inside each file. I know this case works, so is that an option for you? I.e., instead of using an external file, put the options inside one of the files, like this: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto#L19.

Hey @johanbrandhorst thank you for the reply! Unfortunately, it is probably not an option since we want to keep our proto file unannotated :( Is it possible to achieve this scenario while keeping the proto completely unannotated?

**Comment by johanbrandhorst** [comment]
It certainly should be something that we should support, so if it doesn't work today we can hopefully work together to make it work. Could you try to get the external annotations working as expected _without_ doing any merging, and then see if that works?

**Comment by kkolur** [comment]
> It certainly should be something that we should support, so if it doesn't work today we can hopefully work together to make it work. Could you try to get the external annotations working as expected _without_ doing any merging, and then see if that works?

@johanbrandhorst Nope, it isnt working even for just a single file! I even tried removing the `openapi_configuration` opt and just doing the regular swagger generation for single file and it seems to not be working now :(

For reference here is my directory structure

```
proto
  api
    api.proto
    sub_api.proto
    internal_api.proto
  ...
api.config.yaml
swagger.config.yaml
Makefile
```

**Comment by kkolur** [comment]
> It certainly should be something that we should support, so if it doesn't work today we can hopefully work together to make it work. Could you try to get the external annotations working as expected _without_ doing any merging, and then see if that works?

@johanbrandhorst I got it working! The file in the yaml should have been provided as `api/main_api.proto`. This might have something to do with the `-I=proto` so i had to shave off the `proto` from the path
