### ISSUE TITLE
Support array-type response body by default

### ISSUE THREAD

**Issue by armsnyder** [grpc-ecosystem/grpc-gateway#2809]
## 🚀 Feature

EDIT: I was able to resolve this by finding the `allow_repeated_fields_in_body=true` plugin option. However, I suggest changing that option default from `false` to `true`.

~~I would like the openapiv2 and grpc-gateway plugins to support mapping an HTTP response to a repeated field, so that we can have array-type response bodies.~~

~~For example, I want my response body to look like:~~

```json
[{"id":1},{"id":2}]
```

~~Instead of:~~

```json
{"pets":[{"id":1},{"id":2}]}
```

~~Example proto:~~

```proto
import "google/api/http.proto";

service PetService {
  rpc GetPets(GetPetsRequest) returns (GetPetsResponse) {
    option (google.api.http) = {
      get: "/pets"
      response_body: "pets"
    };
  }
}

message GetPetsRequest {}

message GetPetsResponse {
  repeated Pet pets = 1;
}

message Pet {
  uint64 id = 1;
}
```

~~Plugin output:~~

```
Failure: plugin openapiv2: repeated field not allowed in field path: pets in pets
Failure: plugin grpc-gateway: repeated field not allowed in field path: pets in pets
```

~~I read the previous discussion in #317; however there are situations where you need an array-type response body, like when you are implementing an existing REST API spec while migrating a codebase to gRPC.~~

~~[The documentation for the `google.api.http`](https://github.com/googleapis/googleapis/blob/de1ace47a265f06f6d7da31f10f1679d685812a3/google/api/http.proto#L310-L313) is clear that mapping a repeated field to `response_body` can be supported.~~

> If an API needs to use a JSON array for request or response body, it can map
> the request or response body to a repeated field. However, some gRPC
> Transcoding implementations may not support this feature.

~~Thank you 👐~~

**Comment by johanbrandhorst** [comment]
Hi Adam. This is an interesting point, and I agree that it would be nice to turn this on by default. Would you be willing to contribute a flip of this option from off-by-default to on-by-default?

**Comment by armsnyder** [comment]
I'll take a look. 😄
