### ISSUE TITLE
Support tags in service annotations

### ISSUE THREAD

**Issue by kkolur** [grpc-ecosystem/grpc-gateway#2817]
It seems that the `service` option in OpenAPI configuration file is not working, or at least I am unable to get it to work. 

The `protoc` compiles and successfully generates the swagger but the `tags` is not getting updated with the description set by the `service` tag. Here is [OpenAPIServiceOption](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/internal/descriptor/openapiconfig/openapiconfig.proto#L27)

I also checked [unannotated_echo_service.swagger.yaml](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/unannotated_echo_service.swagger.yaml#L68) and could not find the corresponding service description in [unannotated_echo_service.swagger.json](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/unannotated_echo_service.swagger.json) (which im assuming is the generated swagger output of `unannotated_echo_service.swagger.yaml`)

However, in the [a_bit_of_everything.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto#L501) where the annotations are in the proto file, it seems the tags for the service are properly generated in [a_bit_of_everything.swagger.json](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.swagger.json#L17)

**Comment by kkolur** [comment]
I found this which may indicate that its still a TODO? https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/options/openapiv2.proto#L96

**Comment by johanbrandhorst** [comment]
I think it is just the tags, as you say, not the entire service option. I have updated the title. Would you be interesting in helping implement this?

**Comment by johanbrandhorst** [comment]
See also: https://github.com/grpc-ecosystem/grpc-gateway/issues/2751

**Comment by y-takuya** [comment]
Hi @johanbrandhorst, can I try to work on this issue?

**Comment by Rajarshi1998** [comment]
I would like to contribute to fix this issue. Thank you!!

**Comment by johanbrandhorst** [comment]
We have an open PR already: https://github.com/grpc-ecosystem/grpc-gateway/pull/2858. No need to start work on this.
