### ISSUE TITLE
Enable OpenAPI Responses to be deleted on a per operation basis

### ISSUE THREAD

**Issue by jpbarela** [grpc-ecosystem/grpc-gateway#2849]
## 🚀 Feature

Currently the response OpenAPI object is only built additively using both the `responses` values from a `grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger` option and the responses value of the `grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation` option. There is no way to remove a response once it is added. 

Enabling a method for removing the response key can support use cases like adding a `403` response option to an entire API 
where the majority of operations require authentication via a `grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger` option but one or two operations do not require authentication. Another use case is #2243 where an individual operation may want to define success using another 200 series code instead of a `200` response.

A potential implementation is use `google.protobuf.Empty` or an empty message(`{}`) as a sentinel value to remove the response object from the response array.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I think my current thoughts on this is that it is a little bit too much configurability, at the cost of simplicity of both the options and the implementation. Am I understanding right that the user can simply not provide a file-wide response if they only want the response to apply to some of the operations?

**Comment by jpbarela** [comment]
`grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger` is API wide not file wide. If you have 30 authenticated endpoints and 2 unauthenticated endpoints you end up adding a lot of boilerplate by requiring responses on all of the authenticated endpoints rather than removing the response on the 2 unauthenticated endpoints.

**Comment by johanbrandhorst** [comment]
Fair point. Be that as it may, I'd still prefer not to add this functionality, as there is a "workaround" available. As an alternative to adding this functionality, you could also post-process the generated swagger.json. Thanks for your interest in the project!
