### ISSUE TITLE
service refer to external Message with Oneof { enum } field, make invalid gw code.

### ISSUE THREAD

**Issue by dadadamarine** [grpc-ecosystem/grpc-gateway#2850]
## 🐛 Bug Report

when service is using external Message with Oneof { enum } field, and generate pb.gw.go with proto (with service), gen code is not works.

## To Reproduce

1. make proto files like below

**test/example/a/test.proto**
```

syntax = "proto3";

package proto.test.example.a;

import "test/example/b/external.proto";
import "google/api/annotations.proto";

option go_package = "example.com/project/protos/a";

service TestService {
  rpc TestRpc(b.ExternalMsg) returns (b.ExternalMsg) {
    option (google.api.http) = {
      put: "/",
      body:"example_enum"
    };
  }
}
```

**test/example/b/external.proto**

```
syntax = "proto3";

package proto.test.example.b;

option go_package = "github.com/daangn/location/gen/go/test/example/b";

enum ExampleEnum {
  EXAMPLE_ENUM_UNSPECIFIED = 0;
  EXAMPLE_ENUM_FIRST = 1;
}

message ExternalMsg {
  oneof one {
    ExampleEnum example_enum = 1;
  }
}
```

2. generate test.pb.gw.go with `protoc-gen-grpc-gateway`
```
// gen code line number 35
func request_TestService_TestRpc_0(ctx context.Context, marshaler runtime.Marshaler, client TestServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq b.ExternalMsg
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if protoReq.One == nil {
		protoReq.One = &ExternalMsg_ExampleEnum{}
	} else if _, ok := protoReq.One.(*ExternalMsg_ExampleEnum); !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "expect type: *ExternalMsg_ExampleEnum, but: %t\n", protoReq.One)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq.One.(*ExternalMsg_ExampleEnum).ExampleEnum); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.TestRpc(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}
```

## Expected behavior
all the `ExternalMsg_ExampleEnum` codes -> b.ExternalMsg_ExampleEnum

`ExternalMsg_ExampleEnum` is external package's struct type, so it needs package reference. 

## Actual Behavior
only `ExternalMsg_ExampleEnum`is written, so it doesn't refer right struct type.

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/28672263/184627293-4aad7c3d-4839-4b16-8287-bbc87d5452e4.png">

## Your Environment
- os : macOS Monterey 12.0.1
- protoc-gen-grpc-gateway v2 any version.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your bug report! This does indeed look like a bug. I guess this is related to the introduction of this functionality in https://github.com/grpc-ecosystem/grpc-gateway/pull/2739. Maybe there's a simple fix? CC @aesadde.

**Comment by isbang** [comment]
@johanbrandhorst Maybe passing `currentPackage` into `AssignableExpr` and `AssignableExprPrep` function is the simple fix. May I try? CC @dadadamarine

**Comment by johanbrandhorst** [comment]
Could certainly be worth trying it :)
