### ISSUE TITLE
V2.  runtime.WithForwardResponseOption.

### ISSUE THREAD

**Issue by Rascal0814** [grpc-ecosystem/grpc-gateway#2863]
## 🚀 Feature

How do I return a custom data format through runtime.WithForwardResponseOption?
gateway-version：v2

**Comment by johanbrandhorst** [comment]
If you want a custom data format altogether, you probably want a custom marshaler: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#message-serialization. `WithForwardResponseOption` is used for setting things like headers or overwriting the response in some cases.
