### ISSUE TITLE
grpc-gateway - module had invalid dependency: empty digest.

### ISSUE THREAD

**Issue by mcf-rocks** [grpc-ecosystem/grpc-gateway#2907]
A build is failing with the following error, the build has worked in the past.
Any clues?
```
tools/bin/buf generate
buf: downloading buf.build/grpc-ecosystem/grpc-gateway:3d91372e5af6451c8af137f3b5594ac6
Failure: module had invalid dependency: empty digest.
```

**Comment by johanbrandhorst** [comment]
Could you try running  `buf mod update` and then rerun the command? That's an old commit version you're using.

**Comment by mcf-rocks** [comment]
pls see comment ser

**Comment by johanbrandhorst** [comment]
Hah, good point, that's weird. It looks like a problem with buf though. Maybe you could reach out [on their slack channel](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w)? I don't think there's much we can do here.
