### ISSUE TITLE
Question: Where is the right way to decode JWT?

### ISSUE THREAD

**Issue by sizovilya** [grpc-ecosystem/grpc-gateway#2908]
Where is the right way to decode JWT(or a different token) before it is sent to service via grpc and before it is caught by the interceptor?
I looked on middlewares `runtime.With...` and didn't find anything appropriate.

**Why**: I want to decode the token on the api-gateway part of the application and then send userID and role to services using the grpc metadata.

Image for clarification:

<img width="666" alt="Screenshot 2022-09-27 at 17 44 04" src="https://user-images.githubusercontent.com/4721883/192573001-98eddf14-0757-4ec1-87d0-54c81f24e61f.png">

**Comment by achew22** [comment]
Hey @sizovilya, generally speaking it is considered an anti-pattern to decode the token on the edge and then pass the user information downstream. Have you considered writing a library that can be used in `service{1..3}` that could be reused to perform token decoding? If you want to learn more about why this is a dangerous thing to do there are a lot of articles about networks that are "Crunchy on the Outside & Chewy on the Inside".

**Comment by sizovilya** [comment]
Hello @achew22, thank you for the explanation. I didn't know about networks that are "Crunchy on the Outside & Chewy on the Inside", good that you mentioned it.
I see that the architecture is adopted to use auth things on the gRPC server side, as well as interceptors. 
Okay, let's assume we do like that, I see 2 possible solutions:
1. Write JWT encoding lib, and use it in the interceptor. The pros are simplicity and etc., and the cons are if you use something more complex than just JWT decoding. I mean some kind of sessions(white lists, black lists, etc.) which you store, for instance, in Redis. In that case, the lib became responsible to go to Redis, and maybe to the database as well. It could break the responsibility principles of the app because the auth logic exists in each service. Also, we need to provide JWT secrets to each service.
2. Incapsulate auth logic in some service, let's name it auth-service. Write lib to use in interceptors, which contain grpc client to call auth-service each time we need authentication. In response, we have, for instance, userID and role. The pros - we have encapsulated logic in one place. 

That is like I see the concept.
Which way does the community usually use? Something different, maybe?
