### ISSUE TITLE
protoc-gen-openapiv2: Add x-tagGroups to swagger/openapi generation for grouping tags

### ISSUE THREAD

**Issue by kkolur** [grpc-ecosystem/grpc-gateway#2912]
## 🚀 Feature

Use [x-tagGroups](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups/) to group tags in the Reference docs navigation sidebar. Add it to the root OpenAPI/Swagger object.

![x-tag-group](https://user-images.githubusercontent.com/54222395/192844173-97679c5c-7814-4a5e-a7ab-5a1923b72950.png)

**Comment by johanbrandhorst** [comment]
This seems like a vendor extension and not one supported by the OpenAPI v2 spec: https://swagger.io/specification/v2/. If this is correct, I don't think we will add support for this in the generator. What do you think?

**Comment by kkolur** [comment]
> This seems like a vendor extension and not one supported by the OpenAPI v2 spec: https://swagger.io/specification/v2/. If this is correct, I don't think we will add support for this in the generator. What do you think?

@johanbrandhorst i agree on that I guess. How do you suggest we get the vendor extensions in the output generated file? We autogenerate the swagger yaml file on every commit and are afraid that the vendor extension will be removed on every autogeneration

**Comment by johanbrandhorst** [comment]
I'm afraid you will have to do some post-processing. It's not unusual for users to parse the generated swagger back into a language of their choice and make some changes before marshaling out again. Alternatively, if the changes are simple enough, you could try simple search replace or `sed`. It's beyond the scope of this project but I'd be happy to help you if you need more guidance, join our support channel #grpc-gateway on [Gophers Slack](https://invite.slack.golangbridge.org/) 😄.
