### ISSUE TITLE
Add option to disable rendering service level tags

### ISSUE THREAD

**Issue by kkolur** [grpc-ecosystem/grpc-gateway#2917]
## 🚀 Feature

[here](https://github.com/grpc-ecosystem/grpc-gateway/blob/3849b8a0cf8a66fe2799ff9dc1857f0097d13411/protoc-gen-openapiv2/options/openapiv2.proto#L98) it looks like tags at the root level are still `TODO`. Is this planned to be prioritized?Right now, in the output, the tags are automatically generated with the service(s) names but I would prefer to override that behavior by defining my own set of tags at the root level. OR, we can make the rendering of service tags optional and defaulted to true through command line flags?

Also, according to OpenAPI docs, [extensions are supported for tags as well](https://swagger.io/docs/specification/2-0/swagger-extensions/). Could we add this as well?

How difficult would this be overall?

**Comment by johanbrandhorst** [comment]
There are a few settings already for how the tags are generated I believe: https://github.com/grpc-ecosystem/grpc-gateway/blob/b2fed3ce9c921d47c82c6b888ebeae0469f6cb5d/protoc-gen-openapiv2/main.go#L31. I'm not sure exactly what you're asking for. Do you want the ability add tags? How do you want to map those tags to objects? What do you want to do with extensions in tags? I think the use case has to be compelling enough that I could see it being useful to many of our users. Notably, you are the first to ask for this, which is not a great indicator of the need.

**Comment by kkolur** [comment]
@johanbrandhorst I want the option to not automatically render service tags. RIght now the service tags are automatically generated [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/e78f570b573df28b85203f1242c949ade8e5bfc9/protoc-gen-openapiv2/internal/genopenapi/template.go#L1592). If we could have some sort of command line flag that could let us disable that is what I was asking for. 

Using ReDoc, after we added tags to each endpoint, the service level tags were still displayed in the left hand side nav bar which we dont want to display for the users of the docs. We could write a post process script that removes the root level tags object, but I figured it wouldn't hurt if we added a cli flag thats defaulted to true but have the option to set it to false

**Comment by johanbrandhorst** [comment]
I see, thanks for clarifying. I could see a flag that disables tags altogether, but I'm not convinced the need is good enough yet. Maybe we can leave this issue open and see if there are more users who want this functionality before we decide to add it?

**Comment by davix** [comment]
We have the same requirement.
We use the swagger at API gateway which exposes a few backend grpc services. Because backend services' name are inappropriate to be exposed, we define custom tags for the APIs with different grouping strategy. But the service tags still exist now.
Would like to contribute if there are guidance.

**Comment by kkolur** [comment]
I think I have a decent idea of what to do while perusing the codebase so I can take the task on  as well @davix 🙂

**Comment by kkolur** [comment]
@johanbrandhorst [PR here ](https://github.com/grpc-ecosystem/grpc-gateway/pull/2928) 😊
