### ISSUE TITLE
Advice: could we simplify the flow as the below

### ISSUE THREAD

**Issue by jmzwcn** [grpc-ecosystem/grpc-gateway#292]
From a consumer side, could we simplify the flow as the below: e.g

User just need to read all of the proto files(provided one time), then startup the gateway(one cmd). After that, we will could access RESTful api by default config. If this gateway is another microservice and  separated from rpc server, it will be awesome. ^_^

**Comment by achew22** [comment]
@jmzwcn That sounds like an interesting idea. What do you think about putting together a PR where you implement some of those ideas? I'm going to close this issue and we can pick up the conversation in your PR.

Looking forward to your contribution!
