### ISSUE TITLE
Parse trailing comments in protoc-gen-openapiv2

### ISSUE THREAD

**Issue by ionling** [grpc-ecosystem/grpc-gateway#2929]
https://github.com/grpc-ecosystem/grpc-gateway/blob/0443675f6acea5bddca361673c6f0bc241dcb644/protoc-gen-openapiv2/internal/genopenapi/template.go#L2179-L2191

The current `protoc-gen-openapiv2` only parse leading comments, no trailing.
And I think trailing is better for short comments, like this:

```proto
message SearchRequest {
  string query = 1;              // Query string
  int32 page_number = 2;         // Page number
  int32 result_per_page = 3;     // Per page result count
}
```

instead of:

```proto
message SearchRequest {
  // Query string
  string query = 1;
  // Page number
  int32 page_number = 2;
  // Per page result count
  int32 result_per_page = 3;
}
```

So how about add this feature?

**Comment by johanbrandhorst** [comment]
Sure, sounds reasonable. What should the behavior be if there are both leading and trailing comments? I'm guessing we could just append them? Would you be willing to contribute a fix for this?

**Comment by ionling** [comment]
No problem, I'll submit a PR when I'm free.
