### ISSUE TITLE
Add header annotations to OpenAPIv2 generator

### ISSUE THREAD

**Issue by amitavaghosh1** [grpc-ecosystem/grpc-gateway#2932]
I am generating openapi v2 documentation. using `buf generate`

```
service PageService {
  option (grpc.gateway.protoc_gen_swagger.options.openapiv2_tag) = {
    info: {
      title: "Create and view pages to group notes";
    };
  };

  rpc CreatePage (CreatePageRequest) returns (ApiResponse) {
    option(google.api.http) = {
      post: "/api/pages/{id}",
      body: "*"
    };
  }

  rpc GetPageDetails(GetPageRequest) returns (ApiResponse) {
    option(google.api.http) = {
      get: "/api/pages/{id}"
    };
  }
}

message CreatePageRequest {
  string id = 1;
  string description = 2;

  google.protobuf.Timestamp dated_at = 3;
}

message GetPageRequest {
  string id = 1;
  bool show_items = 2;
}

/* more code */
```
this is a part of how my proto file looks like. I was wondering if there is any way to use annotations to generate the swagger.json such that it shows up in headers like.

```
api_key:
  type: apiKey
  name: api_key
  in: header
```

**Comment by johanbrandhorst** [comment]
Yep! https://github.com/grpc-ecosystem/grpc-gateway/blob/38561b377d5a9e2938d58a8ad44b106e90035033/examples/internal/proto/examplepb/a_bit_of_everything.proto#L20-L207 contains some examples of how to add security definitions and also response headers. Hope that helps!

**Comment by amitavaghosh1** [comment]
I meant http request headers like say X-Request-ID not security definitions.

Also i made a simple setup script for a barebones setup

https://github.com/amitavaghosh1/setup/tree/main/golang/grpcproj

**Comment by johanbrandhorst** [comment]
It doesn't look like you can specify request headers, no.

**Comment by ikouchiha47** [comment]
@johanbrandhorst is there any way to add support for this? In the openapiv2.proto file, the message definition is there. Openapi supports request header.

So what to do now?

**Comment by johanbrandhorst** [comment]
We'd have to add the definitions for specifying headers into the annotations ([here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/options/openapiv2.proto)). I'm not actually sure where the header definitions would go, probably on an `Operation`? You'd have to look through the OpenApiv2 spec to see where it fits, the definitions should be somewhat 1:1 to the spec.

Once we have the annotation option in place we need to add parsing of the option into the openapiv2 generator, to produce the output in the final file.

**Comment by ikouchiha47** [comment]
Okay,. I haven't gone through the code yet, but i will try.

**Comment by amitavaghosh1** [comment]
We also, don't have support for parameters?

```
"parameters": [
    {
      "name": "petId",
      "in": "path",
      "description": "ID of pet that needs to be updated",
      "required": true,
      "type": "string"
    },
]
```
this, https://swagger.io/specification/v2/ Operation By Example

**Comment by amitavaghosh1** [comment]
I think we should have a `message Parameters` and then in there we can have headers and path. Because the specs go like:

```
 "parameters": [
    {
      "name": "petId",
      "in": "path",
      "description": "ID of pet that needs to be updated",
      "required": true,
      "type": "string"
    },
    {
      "name": "name",
      "in": "formData",
      "description": "Updated name of the pet",
      "required": false,
      "type": "string"
    },
 {
      "name": "token",
      "in": "header",
      "description": "access token",
      "required": true,
      "type": "string"
    },
]
```

**Comment by johanbrandhorst** [comment]
Hm, the problem with using `parameters` is that it lets users mess with the information generated from the RPC definitions themselves. I would really prefer things like parameters, URL path, etc to be impossible to break by adding annotations to the protobuf files. Maybe we could add parameters but only allow headers to be specified? Also not that it will _always_  be in addition to what the RPC interface itself guarantees, which makes the specifying of headers itself brittle.

**Comment by amitavaghosh1** [comment]
Okay. I will try and make those changes.

**Comment by krak3n** [comment]
Implementation in #3010
