### ISSUE TITLE
default enum value is omitted

### ISSUE THREAD

**Issue by fiibbb** [grpc-ecosystem/grpc-gateway#294]
Consider the following IDL
```
enum MyEnum {
  CASE_A = 0;
  CASE_B = 1;
}
message MyMsg {
  MyEnum my_value = 1;
}
```  

When a `MyMsg` is sent to an HTTP client (in my case curl) over grpc-gateway with value set to `CASE_A` (0), the client seem to receive and empty json object with the field `my_value` omitted all together.
IE, we receive
```
{}
```
instead of
```
{
  "my_value": "CASE_A"
}
```
In `jsonpb`, we can set `jsonpb.Marshaler.EmitDefaults` to `true` to avoid this behavior. Is that also supported in grpc-gateway?

**Comment by tmc** [comment]
This is possible by supplying an option via https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption
