### ISSUE TITLE
Support extensions for tags

### ISSUE THREAD

**Issue by kkolur** [grpc-ecosystem/grpc-gateway#2942]
## 🚀 Feature

Tags have been implemented at the root level as a result of this [PR](https://github.com/grpc-ecosystem/grpc-gateway/pull/2939).  According to OpenAPI [extensions](https://swagger.io/docs/specification/openapi-extensions/) should be available to the Tag object as well.

For example, ReDoc has some [vendor extensions](https://github.com/Redocly/redoc/blob/main/docs/redoc-vendor-extensions.md#tag-object) available for Tag Objects. You can see [here](https://redocly.com/docs/api-reference-docs/specification-extensions/x-trait-tag/) how its used and how its rendered

**Comment by johanbrandhorst** [comment]
Thanks for the feature request! I think we need to take a holistic view at extensions, the page you linked details all the places where extensions can exist in the OpenAPIv2 spec. It would make sense to me to add a message to describe the extension type and then add that to all the places extensions can be specified. What do you think?

**Comment by kkolur** [comment]
> Thanks for the feature request! I think we need to take a holistic view at extensions, the page you linked details all the places where extensions can exist in the OpenAPIv2 spec. It would make sense to me to add a message to describe the extension type and then add that to all the places extensions can be specified. What do you think?

@johanbrandhorst sorry im having trouble understanding the following, can you provide an example?

`It would make sense to me to add a message to describe the extension type and then add that to all the places extensions can be specified`

For most places already in `protoc-gen-openapiv2`, extensions are added to the messages (Swagger, Operation, Info, etc) like so: [Example here](https://github.com/grpc-ecosystem/grpc-gateway/blob/3849b8a0cf8a66fe2799ff9dc1857f0097d13411/protoc-gen-openapiv2/options/openapiv2.proto#L101)

I was thinking we just follow the same pattern by adding the following line of code to the [Tag Message](https://github.com/grpc-ecosystem/grpc-gateway/blob/3849b8a0cf8a66fe2799ff9dc1857f0097d13411/protoc-gen-openapiv2/options/openapiv2.proto#L528):

`map<string, google.protobuf.Value> extensions = 3;`

And then do the necessary Go changes 

Thoughts?

**Comment by johanbrandhorst** [comment]
You're right, I didn't think we already had extensions in some places, so lets just go ahead and continue that pattern.

**Comment by johanbrandhorst** [comment]
Fixed in #2950
