### ISSUE TITLE
jsonpb convert int64 to integer instead of string

### ISSUE THREAD

**Issue by arun0009** [grpc-ecosystem/grpc-gateway#296]
// 64bit integer types are marshaled as string in the default JSONPb marshaler.
// TODO(yugui) Add an option to declare 64bit integers as int64.
I see the above comment in code., but just wondering is there a way to generate swagger docs with int64 proto type to integer instead of string?

**Comment by tmc** [comment]
This is defined in the proto3->json mapping here https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by tmc** [comment]
I'm not sure this is an appropriate change as we don't currently have a way to expose marshaler customization to the swagger generation path -- I'm open to an issue that represents that but until then I don't consider this a problem.
