### ISSUE TITLE
"connection closed before server preface received" when try Using the default mapping

### ISSUE THREAD

**Issue by whtjs** [grpc-ecosystem/grpc-gateway#2966]
Hi Fellas!

I was following README and "Using the default mapping" in 4th step

But when i try to call gRPC client through gateway it throws an error
`rpc error: code = Unavailable desc = connection closed before server preface received
exit status 1`

I make new repo that i was testing to be clear
[https://github.com/whtjs/grpc-gateway-example](https://github.com/whtjs/grpc-gateway-example)

The step of my test
1. `go run greeter_server/main.go`
2. `go run greeter_gateway/main.go`
3. `go run greeter_client/main.go`

I understand that grpc-gateway works for
1.  transfer REST call and mapping
2. for micro services, gateway accept from one endpoint and spread it to appropriate micro service

I was trying to make 2

is there any mistake in my code or misunderstanding? or README has missing process?

thanks for help!

**Comment by johanbrandhorst** [comment]
Your client is using `grpc.Dial` to dial the grpc-gateway. If you want to use gRPC, just dial the gRPC server directly. If you want to use the gRPC-Gateway, you will need to make a HTTP request manually, not via gRPC.

**Comment by whtjs** [comment]
> Your client is using `grpc.Dial` to dial the grpc-gateway. If you want to use gRPC, just dial the gRPC server directly. If you want to use the gRPC-Gateway, you will need to make a HTTP request manually, not via gRPC.

oh.. i misunderstand about feature, I'm sorry for bother. Thank you!
