### ISSUE TITLE
Repeated fields in parameter are parsed as a single string v.s. a slice of string (incompatible with `gapic-generator-go`)

### ISSUE THREAD

**Issue by HuairuoYang** [grpc-ecosystem/grpc-gateway#2971]
## 🐛 Bug Report
I am using `grpc-gateway` to generate HTTP-GRPC gateway that can have my generated [gapic-generator](https://github.com/googleapis/gapic-generator-go) REST/HTTP clients talk to the server with both GRPC and HTTP. 
I thought both this and `grpc-gateway` are popular tools and they all generate code from protobuf so that they should be compatible with each other.
However I noticed that the repeated field parameter in `get` requests didn't work well.

I think people would be more than happy if the generated REST Clients can be directly used against `grpc-gateway`!

Thanks!
(A clear and concise description of what the bug is.)

## To Reproduce

(Write your steps here:)
1. 
My proto is similar to this:
```proto
rpc List(ListRequest) returns (ListResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=*}/lists"
    };
}

message ListRequest {
    enum Types {
        A=0;
        B=1;
    }
    repeated Types = 1; 
}
```
So I can send a request with Types = [0, 1].

2. 
And in the generated REST client's `List` method, the `Types` is set in this way
```
		if req.GetTypes() != nil {
			params.Add("types", fmt.Sprintf("%v", req.GetTypes()))
		}
```
This sets a single string `[0,1]` to the parameter `types`.

3. 
Whereas in the server side, `grpc-gateway` receives the request and parses the parameter using [this method: Parse](https://github.com/grpc-ecosystem/grpc-gateway/blob/v1/runtime/query.go#L37), where the input `values` is the `request.Form` which contains the parameter k-v pair.

And it will parse the above `types: "[0,1]"` to `key: types`, `value: "[0,1]"` (Note, it is a string `"[0,1]"`). And it will fail saying that `[0,1]` is not a correct enum type.

## Expected behavior
Expected the grpc-gateway can be used out-of-box to connect to the `gapic` clients:
The grpc-gateway should be able to parse the string of a slice, i.e in a form `"[A B C D E]"` as a slice `[A B C D E]`.

(Write what you thought would happen.)

## Actual Behavior

The grpc-gateway parses the string of a slice, i.e in a form `"[A B C D E]"` as a string `"[A B C D E]"`.
(Write what happened. Add screenshots, if applicable.)

## Your Environment

  - Programming language: Golang
  - OS: MacOS
  - Language runtime version: v1.17.13
  - grpc-gateway V1/V2 
(Environment name, version and operating system.)

This is the mirror issue I created in the `gapic-generator` for google: https://github.com/googleapis/gapic-generator-go/issues/1160

**Comment by HuairuoYang** [comment]
[gapic-generator](https://github.com/googleapis/gapic-generator-go/issues/1160#issuecomment-1285684640) replied that this seems to be a bug on their side.

But It would still be a nice feature that if we can parse the slice of stirngs like `[A B C D E]` directly into slices.
Thanks!

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue report. I don't think it's desireable for us to implement this in the gateway, but note that if you want this sort of behavior supported you can implement your own `QueryParameterParser` and replace the default one with https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#SetQueryParameterParser.
