### ISSUE TITLE
Expose OpenAPI/Swagger specification document from protoc-gen-openapiv2

### ISSUE THREAD

**Issue by kamiKAZIK** [grpc-ecosystem/grpc-gateway#2983]
## 🚀 Feature
Hello, would it be possible to expose the generated OpenAPI / Swagger JSON or YAML file as a variable or function that returns string or byte array of the specification document. This could be very useful when customizing gateway HTTP server and adding SwaggerUI mddleware, for example:

```
filePath := fmt.Sprint(pathPrefix, "/", "generated_swagger.json")
swaggerPath := fmt.Sprint(pathPrefix, "/", i, "/swagger")
router.Handle(filePath, http.StripPrefix(pathPrefix, http.FileServer(http.Dir("./docs/"))))
opts := middleware.SwaggerUIOpts{
    Path: swaggerPath, SpecURL: filePath,
}
sh := middleware.SwaggerUI(opts, nil)
router.Handle(swaggerPath, sh)
```

basically, it would be very useful if it would be possible to access `generated_swagger.json` as some sort of variable or function, which could be then exposed as HTTP server asset.

**Comment by johanbrandhorst** [comment]
Hi, this is commonly done already and there's no need to change anything in the gateway, you can simply add a handler to your Go HTTP server. Here's an example: https://github.com/johanbrandhorst/grpc-gateway-boilerplate (see https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/gateway/gateway.go#L24-L34).

**Comment by kamiKAZIK** [comment]
@johanbrandhorst I don't think that this solves the issue, for example if we have a git repository where we store generated golang types and gateway from proto files, e.g.: generated_go_gw@1.2.0, then if we want to import that as go module in another project, there is no way to access the generated_swagger.json from that go module. I understand that it all would work well if the proto files and HTTP server code would be in the same repository / module.

**Comment by johanbrandhorst** [comment]
I see what you're saying, but I don't know that there's anything we can do with the gateway. That sounds like a Go modules problem. Maybe you can generate the swagger document only to your repositories using `buf`?

**Comment by kamiKAZIK** [comment]
Maybe it would be possible to make use of:
//go:embed
and embed the generated swagger file as a variable that could be accessed from anywhere?

**Comment by johanbrandhorst** [comment]
Yes, you could do this in a file in the same repository as your generated swagger file. The boilerplate repo does this: https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/third_party/embed.go#L7
