### ISSUE TITLE
Details (e.g., description, title, etc.) for message-type fields are not translated to Swagger doc

### ISSUE THREAD

**Issue by tmccnnll** [grpc-ecosystem/grpc-gateway#2984]
## 🐛 Bug Report

Details (e.g., description, title, etc.) for message-type fields are not displayed in `definitions.<schema object>.properties` within generated Swagger doc.

It looks like this is a regression from `protoc-gen-openapiv2` `v2.11.3` to `v2.12.0`. I actually used `v2.11.3` to generate the expected Swagger doc example found below in the ticket.

## To Reproduce

`example/v1alpha1/example_service.proto`:
```proto
service ExampleService {
  rpc ExampleList (ExampleListRequest) returns (ExampleListResponse) {
    option (google.api.http) = {
      get: "/list"
    };
  }
}

message ExampleListRequest {}

message ExampleListResponse {
  Nested nested = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "A field using the Nested message"
    }
  ];
}

message Nested {
 option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      description: "The Nested message."
    }
  };

  string field1 = 1;
}

```

Use `protoc-gen-openapiv2` `v2.12.0` to create Swagger doc from the above protobuf snippet

## Expected behavior

`definitions.v1alpha1ExampleListResponse.properties.nested` has a `description` field with a value of `"A field using the Nested message"`

Expected Swagger doc:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "example/v1alpha1/example_service.proto",
    "version": "version not set"
  },
  "tags": [
    {
      "name": "ExampleService"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/list": {
      "get": {
        "operationId": "ExampleService_ExampleList",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1alpha1ExampleListResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "ExampleService"
        ]
      }
    }
  },
  "definitions": {
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "v1alpha1ExampleListResponse": {
      "type": "object",
      "properties": {
        "nested": {
          "$ref": "#/definitions/v1alpha1Nested",
          "description": "A field using the Nested message"
        }
      }
    },
    "v1alpha1Nested": {
      "type": "object",
      "properties": {
        "field1": {
          "type": "string"
        }
      },
      "description": "The Nested message."
    }
  }
}
```

## Actual Behavior

`definitions.v1alpha1ExampleListResponse.properties.nested` has **no** `description` field.

Resulting Swagger doc:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "example/v1alpha1/example_service.proto",
    "version": "version not set"
  },
  "tags": [
    {
      "name": "ExampleService"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/list": {
      "get": {
        "operationId": "ExampleService_ExampleList",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1alpha1ExampleListResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "ExampleService"
        ]
      }
    }
  },
  "definitions": {
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "v1alpha1ExampleListResponse": {
      "type": "object",
      "properties": {
        "nested": {
          "$ref": "#/definitions/v1alpha1Nested"
        }
      }
    },
    "v1alpha1Nested": {
      "type": "object",
      "properties": {
        "field1": {
          "type": "string"
        }
      },
      "description": "The Nested message."
    }
  }
}
```

## Your Environment

- `libprotoc` `3.18.1`
- `protoc-gen-openapiv2` `2.12.0`

**Comment by johanbrandhorst** [comment]
I think this was actually a bug fix introduced in #2904. See https://github.com/grpc-ecosystem/grpc-gateway/pull/2904#issuecomment-1263744686. Apparently no fields other than `$ref` should appear next to the ref. Is the problem that the comment has disappeared entirely now?

CC @gostajonasson

**Comment by tmccnnll** [comment]
Thanks for the quick reply and linking the comment.

That comment links to [JSON Schema Draft 3](https://datatracker.ietf.org/doc/html/draft-zyp-json-schema-03), but according to the [Swagger specification for the Schema Object](https://swagger.io/specification/v2/#schemaObject), we should be looking at JSON Schema Draft 4 instead. I read through the JSON Schema Draft 4 and didn't see a similar section talking about siblings of `$ref` fields being ignored (but I may have missed it).

The issue I see with this change in behaviour is that there is no way to provide a description for a message field that is independent of that message's definition. I imagine creating a common message to be used in several spots, where each of those instances might benefit from a unique description, is a common pattern.

If the old behaviour from `< v2.11.3` is viewed as a bug, then how could the use case I just described above be supported? Would there be any interest in the composition pattern shown in the ["Models with Composition" example from the Swagger 2.0 definition of the Schema Object](https://swagger.io/specification/v2/#schemaObject)?

**Comment by johanbrandhorst** [comment]
Thanks for your quick response, even that page you linked contains two different references to JSON schema drafts, the link under `ref` links to https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03 while the overall definition mentions draft 4 - I'm happy to assume draft 4 in this case as I agree that this is useful functionality. I'm sorry this caused a breakage for you and I'd be happy to reintroduce these fields, though it may not be as simple as just removing the checks introduced in #2904 (though it also may be just that simple 😂). Would you like to give it a try?

**Comment by gostaj** [comment]
Hi @tmccnnll and sorry if my PR has caused issues for you.
I personally also think there is a point in having descriptions next to $ref fields but [the Swagger docs](https://swagger.io/docs/specification/using-ref/) states:

> Any members other than $ref in a JSON Reference object are ignored. 

Also look at their "$ref and Sibling Elements" section at the bottom of [that page](https://swagger.io/docs/specification/using-ref/).

**Comment by gostajonasson** [comment]
Hi @tmccnnll and sorry if my PR has caused issues for you.
I personally also think there is a point in having descriptions next to $ref fields but [the Swagger docs](https://swagger.io/docs/specification/using-ref/) states:

> Any members other than $ref in a JSON Reference object are ignored. 

Also look at their "$ref and Sibling Elements" section at the bottom of [that page](https://swagger.io/docs/specification/using-ref/).

**Comment by johanbrandhorst** [comment]
I'm tempted to say that this page does not apply to is as it is covering OpenAPI v3, and we only support OpenAPI v2. I couldn't find the equivalent statements in the v2 page: https://swagger.io/docs/specification/2-0/basic-structure/.

**Comment by gostajonasson** [comment]
> I'm tempted to say that this page does not apply to is as it is covering OpenAPI v3, and we only support OpenAPI v2. I couldn't find the equivalent statements in the v2 page: https://swagger.io/docs/specification/2-0/basic-structure/.

Aha! I didn't know that. If that's the case we could perhaps just remove the checks ([#1](https://github.com/grpc-ecosystem/grpc-gateway/pull/2904/files#diff-c904837bc1a47dae3fba9863430f2ab46fa8a1bd0c9e25475308ab426a0d4efeR519-R523) and [#2](https://github.com/grpc-ecosystem/grpc-gateway/pull/2904/files#diff-c904837bc1a47dae3fba9863430f2ab46fa8a1bd0c9e25475308ab426a0d4efeR1241-R1245)) that I introduced.
The most important part in the PR was [removing code](https://github.com/grpc-ecosystem/grpc-gateway/pull/2904/files#diff-c904837bc1a47dae3fba9863430f2ab46fa8a1bd0c9e25475308ab426a0d4efeL2657-L2659) that filtered away the "required" property.

**Comment by tmccnnll** [comment]
Thanks to both of you, @johanbrandhorst and @gostajonasson, for being so quick to reply and considering a change here.

@gostajonasson, are you able to remove those checks you highlighted in a new PR? If not, I can probably spend some time on this but will need to get setup on this repo first.

**Comment by johanbrandhorst** [comment]
If you have access to Github Codespaces you can create a virtual environment with all the setup you need: 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/6604151/199308399-e7da0298-7d71-4f89-9953-c2fb591621e0.png">

**Comment by gostajonasson** [comment]
Added a PR that hopefully fixes this :point_up:, please have a look.

**Comment by johanbrandhorst** [comment]
I'll make a patch release for this.

**Comment by johanbrandhorst** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.13.0
