### ISSUE TITLE
Partial resource update RPCs include the update mask in the swagger specification

### ISSUE THREAD

**Issue by peterwillis** [grpc-ecosystem/grpc-gateway#2988]
## 🐛 Bug Report

RPCs can perform partial resource updates through the use of a `patch` binding and `google.protobuf.FieldMask` as described [here](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature/). The swagger specification generated still includes an `updateMask` field which is ultimately ignored by the gRPC-Gateway.

## To Reproduce

Generate the swagger specification for the "a bit of everything" [example](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto).

## Expected behavior

The updateMask field is not included in the swagger specification

## Actual Behavior

The updateMask field is [included](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.swagger.json#L5952)

## Your Environment

v2.12.0

**Comment by johanbrandhorst** [comment]
Hi Peter, thanks for your issue! I thought we already supported this but evidently we don't. Considering that the patch feature is the default behavior on the gateway I think we should definitely add this when detecting a field called `update_mask` of type `.google.protobuf.FieldMask` at the top level of a request (as explained in [the docs](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature/)). If this surprises users, we can introduce a flag to disable the behavior later. Would you be willing to help contribute this? I think we'd start by defining a failing test in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template_test.go. Feel free to copy one of the existing tests and adapting it to your use case. This file is a bit of a mess so be warned 😅. I then think we'd start at https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template.go#L436 and add some special case logic for this scenario. What do you think?

**Comment by peterwillis** [comment]
Thank you for the pointers, I would be very happy to help.

**Comment by csh995426531** [comment]
> Hi Peter, thanks for your issue! I thought we already supported this but evidently we don't. Considering that the patch feature is the default behavior on the gateway I think we should definitely add this when detecting a field called `update_mask` of type `.google.protobuf.FieldMask` at the top level of a request (as explained in [the docs](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature/)). If this surprises users, we can introduce a flag to disable the behavior later. Would you be willing to help contribute this? I think we'd start by defining a failing test in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template_test.go. Feel free to copy one of the existing tests and adapting it to your use case. This file is a bit of a mess so be warned 😅. I then think we'd start at https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template.go#L436 and add some special case logic for this scenario. What do you think?



> Hi Peter, thanks for your issue! I thought we already supported this but evidently we don't. Considering that the patch feature is the default behavior on the gateway I think we should definitely add this when detecting a field called `update_mask` of type `.google.protobuf.FieldMask` at the top level of a request (as explained in [the docs](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature/)). If this surprises users, we can introduce a flag to disable the behavior later. Would you be willing to help contribute this? I think we'd start by defining a failing test in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template_test.go. Feel free to copy one of the existing tests and adapting it to your use case. This file is a bit of a mess so be warned 😅. I then think we'd start at https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/internal/genopenapi/template.go#L436 and add some special case logic for this scenario. What do you think?

Hi, I'd love to help fix this as a first contribution, but I have some doubts about the logical handling, I think there should be some special handling for HTTPMethod == "PATCH" around line 1268, right?
