### ISSUE TITLE
Unexpected route with verb pattern

### ISSUE THREAD

**Issue by cclien0725** [grpc-ecosystem/grpc-gateway#2990]
## 🐛 Bug Report

Assume there are three handler patterns as follows:

1. `POST /api/v1/organizations:verb`
2. `POST /api/v1/organizations`
3. `POST /api/v1/dummies:verb`

Request to `POST /api/v1/organizations:verb` but it routes to the unexpected handler which handles the pattern for `POST /api/v1/organizations`.

## To Reproduce

By extending the `TestMuxServeHTTP` test with the following test cases:

```go
		{
			patterns: []stubPattern{
				{
					method: "POST",
					ops: []int{
						int(utilities.OpLitPush), 0,
						int(utilities.OpLitPush), 1,
						int(utilities.OpLitPush), 2,
					},
					pool: []string{"api", "v1", "organizations"},
					verb: "verb",
				},
				{
					method: "POST",
					ops: []int{
						int(utilities.OpLitPush), 0,
						int(utilities.OpLitPush), 1,
						int(utilities.OpLitPush), 2,
					},
					pool: []string{"api", "v1", "organizations"},
					verb: "",
				},
				{
					method: "POST",
					ops: []int{
						int(utilities.OpLitPush), 0,
						int(utilities.OpLitPush), 1,
						int(utilities.OpLitPush), 2,
					},
					pool: []string{"api", "v1", "dummies"},
					verb: "verb",
				},
			},
			reqMethod: "POST",
			reqPath:   "/api/v1/organizations:verb",
			headers: map[string]string{
				"Content-Type": "application/json",
			},
			respStatus:     http.StatusOK,
			unescapingMode: runtime.UnescapingModeAllCharacters,
			respContent:    "POST /api/v1/organizations:verb",
		},
```

Output:

```
=== RUN   TestMuxServeHTTP/0
    mux_test.go:115: w.Body = "POST /api/v1/organizations"; want "POST /api/v1/organizations:verb"; patterns=[{POST [2 0 2 1 2 2] [api v1 organizations] verb} {POST [2 0 2 1 2 2] [api v1 organizations] } {POST [2 0 2 1 2 2] [api v1 dummies] verb}]; req=&{POST https://host.example/api/v1/organizations:verb HTTP/1.1 1 1 map[Content-Type:[application/json]] {} 0x1046b2fc0 0 [] false host.example map[] map[] <nil> map[]   <nil> <nil> <nil> 0x14000026108}
--- FAIL: TestMuxServeHTTP (0.00s)
    --- FAIL: TestMuxServeHTTP/0 (0.00s)
FAIL
```

## Expected behavior

Route to `POST /api/v1/organizations:verb`

## Actual Behavior

Route to `POST /api/v1/organizations`

## Your Environment

- `v2.12.0`
- `v2.13.0`

**Comment by johanbrandhorst** [comment]
I believe this is because of the last one wins behavior of service configurations. I could be mistunderstanding. See https://github.com/grpc-ecosystem/grpc-gateway/issues/224#issuecomment-426091809 for more discussion.

**Comment by cclien0725** [comment]
Hi @johanbrandhorst thanks for your quick reply, that said I open this since the same test case would be okay before `v2.11.3` but I'm facing the unexpected handler when I upgrade to `v2.12.0`. It seems to be a side-effect of fixing #2870.

**Comment by johanbrandhorst** [comment]
Hm, I see. @jonathaningram any thoughts from you? Sorry to hang you out but I've sort of forgotten about this fix.

**Comment by jonathaningram** [comment]
@johanbrandhorst @cclien0725 having a look 👀

**Comment by jonathaningram** [comment]
@cclien0725 can you please put your test case into a PR/branch so I can pull it down locally and run and debug it?

**Comment by cclien0725** [comment]
Hi @jonathaningram thanks for your reply, have already put the test case into the draft PR #2997. You can take a look. Thanks!
