### ISSUE TITLE
Generate swagger.json documentation using openapiv2

### ISSUE THREAD

**Issue by dddhhhjjj** [grpc-ecosystem/grpc-gateway#2992]
Hello, I have a problem with the use of the openapiv2 plugin: 

When I use the openapiv2 plugin to generate swagger.json from my proto file, 

how do I add descriptive information about the interface?

Below is my proto file:

![微信图片_20221104131753](https://user-images.githubusercontent.com/48084332/199895973-4a179ba9-5253-4090-ae47-a89b2f85aa9d.jpg)

last generated result:

![4](https://user-images.githubusercontent.com/48084332/199896243-c5c3ea7f-5bba-4f09-b41c-09435f440950.png)

But I want the final result to look like this:

![8](https://user-images.githubusercontent.com/48084332/199896623-ad1ccd15-ddde-4015-8bf5-f009112abda4.jpg)

Below is my build command：

`protoc -I ./  -I D:/Work/Program/gopath1/src -I D:/Work/Program/gopath1/src/google/api --openapiv2_out=. --openapiv2_opt logtostderr=true --openapiv2_opt json_names_for_fields=true result.proto`

Is there any good way?

**Comment by johanbrandhorst** [comment]
You can customize the openapiv2 output by using annotations in your protobuf file. See https://github.com/grpc-ecosystem/grpc-gateway/blob/c2e1a3d23c4f1ad85c1259af0ec6e8a50f4f81ee/examples/internal/proto/examplepb/a_bit_of_everything.proto#L671-L672 for an example of changing the description and summary of an RPC. See https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/ for more information.
