### ISSUE TITLE
Getting 'grpc-gateway_out: duplicate annotation' error when using multiple proto file paths

### ISSUE THREAD

**Issue by MichaKnoe** [grpc-ecosystem/grpc-gateway#3005]
## 🐛 Bug Report

Using proto input files from more than one root folder throws an error using the ```google.api.http``` anotations. The error is:
```-grpc-gateway_out: duplicate annotation: method=GET, template=/v1/path```.

The following folder structure is used to be able to have a centralized model definition for multiple API flavours. e.g. ```internal``` and ```public```.

- model
  - model.proto
- internal
  - internal.proto

## To Reproduce

1. Create a splitted proto folder package structure:

- proto
   - model
   - internal

2. Create model.proto file inside ```proto/model``` directory
```protobuf
syntax = "proto3";

package model;
option go_package = "github.com/YourOrg/YourRepoRoot/proto/model";
message TestMessage {
    string message = 1;
  }
```
4. Create internal.proto file inside ```proto/internal``` directory
```protobuf
syntax = "proto3";

package internal;

import "model/model.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/YourOrg/YourRepoRoot/proto/internal";

service TestService {

  rpc TestFunction(google.protobuf.Empty) returns (model.TestMessage) {
    option (google.api.http) = {
        get: "/v1/internal/test"
    };
  }
 }
```
5. Run protoc for generating the ```model``` outputs
```bash
protoc -Iproto proto/model/*.proto \
	  --go_opt=module=github.com/YourOrg/YourRepoRoot \
	  --go_out=.  \
	  --go-grpc_opt=module=github.com/YourOrg/YourRepoRoot \
	  --go-grpc_out=. proto/model/*.proto \
```
6. Run protoc for gernerating the ```internal``` folder outputs
```bash
protoc -Iproto proto/internal/*.proto \
	  --go_opt=module=github.com/YourOrg/YourRepoRoot\
	  --go_out=.  \
	  --go-grpc_opt=module=github.com/YourOrg/YourRepoRoot \
	  --go-grpc_out=. proto/internal/*.proto \
	  --grpc-gateway_out=proto/internal \
	  --grpc-gateway_opt=logtostderr=true \
	  --grpc-gateway_opt=paths=source_relative \
	  --grpc-gateway_opt=allow_delete_body=true \
	  --grpc-gateway_opt=standalone=true \
	  --openapiv2_out=docs/swagger \
	  --openapiv2_opt allow_delete_body=true \
	  --openapiv2_opt allow_merge=true \
	  --openapiv2_opt merge_file_name=test-internal.json \
```

## Expected behavior

```proto/internal/internal_grpc.pb.go``` file is created properly without throwing an error

## Actual Behavior

Error is thrown ```--grpc-gateway_out: duplicate annotation: method=GET, template=/v1/internal/test``` 

## Your Environment

OS: linux 5.10.16.3-microsoft-standard-WSL2 x86_64
Shell: bash 5.0.16(1)-release
Protoc version: libprotoc 3.21.5
Grpc-Gateway: github.com/grpc-ecosystem/grpc-gateway/v2 v2.10.0
GRPC: google.golang.org/grpc v1.46.2
Go version: go version go1.19.1 linux/amd64

**Comment by MichaKnoe** [comment]
I think I found a solution myself.
Changing step 6 ```gateway_out``` path to ```proto/internal/gw``` seems to solve it:
protoc -Iproto proto/internal/*.proto \
	  --go_opt=module=github.com/YourOrg/YourRepoRoot\
	  --go_out=.  \
	  --go-grpc_opt=module=github.com/YourOrg/YourRepoRoot \
	  --go-grpc_out=. proto/internal/*.proto \
	  --grpc-gateway_out=proto/internal/gw \
	  --grpc-gateway_opt=logtostderr=true \
	  --grpc-gateway_opt=paths=source_relative \
	  --grpc-gateway_opt=allow_delete_body=true \
	  --grpc-gateway_opt=standalone=true \
	  --openapiv2_out=docs/swagger \
	  --openapiv2_opt allow_delete_body=true \
	  --openapiv2_opt allow_merge=true \
	  --openapiv2_opt merge_file_name=test-internal.json \


Maybe a more speaking error message would be nice to point to the root cause.

**Comment by MichaKnoe** [comment]
And again after some further fixing.....

- Use ```source_relative``` whereever possible
- Do NOT use ```module``` option as it is not needed with ```source_relative```
- Remove ```--grpc-gateway_opt=standalone=true```
- Add proto files to be considered explicitly at the end

```shell
protoc -Iproto \
 --proto_path proto/internals \
 --proto_path proto/model \
 --go_out proto \
 --go_opt paths=source_relative \
 --go-grpc_out proto \
 --go-grpc_opt paths=source_relative \
 --grpc-gateway_out proto \
 --grpc-gateway_opt logtostderr=true \
 --grpc-gateway_opt allow_delete_body=true \
 --grpc-gateway_opt paths=source_relative \
 --openapiv2_out docs/swagger \
 --openapiv2_opt allow_delete_body=true \
 --openapiv2_opt allow_merge=true \
 --openapiv2_opt merge_file_name=test-internals.json  \
  proto/internals/internals.proto \
  proto/model/model.proto 
```

**Comment by johanbrandhorst** [comment]
Glad you figured it out. I would recommend checking out our step by step tutorial if you are new to protobuf: https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/introduction/. I would recommend using `buf` instead of `protoc`. I would also recommend reading their style guide: https://docs.buf.build/best-practices/style-guide#files-and-packages.

**Comment by MichaKnoe** [comment]
Many thanks four the advice. Will look deeper into buf. Sounds promising.
