### ISSUE TITLE
Question: Why passing context to RegisterMyServiceHandler is required? 

### ISSUE THREAD

**Issue by c4milo** [grpc-ecosystem/grpc-gateway#301]
Why not getting it from `http.Request` inside each `mux.Handle`? I'm curious

**Comment by ilius** [comment]
Go's "net/http" package is HTTP/1, and the context it has is as in "context" package
GRPC is HTTP/2 and it's context is  "golang.org/x/net/context"
Package "context"  is not even imported the .go file generated by protoc

**Comment by tmc** [comment]
@c4milo this capability is exposed behind a flag at the moment and we have #313 open as well
