### ISSUE TITLE
Javascript does not detect dots in objected query parameters

### ISSUE THREAD

**Issue by Ja7ad** [grpc-ecosystem/grpc-gateway#3016]
## 🐛 Bug Report

Hi
We have a problem with objected query parameters in javascript. There is an unknown dot as an object when we create query parameters in JS `(files?paginated.filters[categoryId]=12335325)`.

## To Reproduce

1. create request message for get method.
2. add nested object with name paginated.
3. after generated gprc gateway pb.
4. all fields in paginated is object field for example (paginated.page or paginated.filters[x])

## Expected behavior

**javascript standard (serialized):**
```console
files?paginated[filters][categoryId]=12335325
```

**standard of javascript code**
```javascript
      let filters = {
        paginated: {
          filters: {
            categoryId: 12335325
          }
        }
      }
      const resp = await this.$axios({
        method: 'get',
        url: newUrl || this.url,
        baseURL: this.baseUrl.length ? this.baseUrl : this.$axios.defaults.baseURL,
        params: filters,
        paramsSerializer: qs.stringify,
        headers: headers
      })
```

## Actual Behavior

![Screenshot from 2022-11-16 12-08-02](https://user-images.githubusercontent.com/56496801/202132671-a7570a13-2684-4221-8a8a-219de39571c7.png)
![Screenshot from 2022-11-16 12-17-18](https://user-images.githubusercontent.com/56496801/202132678-97f42d83-7a5b-4158-aa0c-434ded957571.png)

**generated by grpc-gateway:**
```console
files?paginated.filters[categoryId]=12335325
```

**after handle this issue in javascript**
```javascript
    let params = {}
      for (const property in this.gridView.params) {
        params['paginated.'+property] = this.gridView.params[property]
      }
      const resp = await this.$axios({
        method: 'get',
        url: newUrl || this.url,
        baseURL: this.baseUrl.length ? this.baseUrl : this.$axios.defaults.baseURL,
        params: params,
        paramsSerializer: qs.stringify,
        headers: headers
      })
```

## Your Environment

- ubuntu 20.04
- libprotoc 3.6.1
- protoc-gen-go-grpc 1.2.0

```shell
$ protoc-gen-grpc-gateway -version  
Version dev, commit unknown, built at unknown

```

```shell
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/.go/pkg/mod"
GONOPROXY="git.ramooz.org"
GONOSUMDB="git.ramooz.org"
GOOS="linux"
GOPATH="/home/user/.go"
GOPRIVATE="git.ramooz.org"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3978196985=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by johanbrandhorst** [comment]
What do you mean by
> generated by grpc-gateway:
> `files?paginated.filters[categoryId]=12335325`
?

The grpc-gateway has two generators, one which generates Go code and one which generates swagger descriptions, neither of which will generate this sort of data. Do you mean that this is the format you have to use to provide data of this format as a query parameter?

**Comment by Ja7ad** [comment]
@johanbrandhorst 

I check generator grpc-gateway have problem.

>  Do you mean that this is the format you have to use to provide data of this format as a query parameter?

yes

**Comment by johanbrandhorst** [comment]
That query parameter format looks correct to me. You expect it to be
```
 files?paginated[filters][categoryId]=12335325
```
instead of
```
 files?paginated.filters[categoryId]=12335325
```
? If so, that doesn't make any sense to me, the square bracket syntax is only used for maps, where the key is specified by the user. The field `filters` is known, and so it shouldn't be a square bracket lookup. Maybe I'm misunderstanding you?

**Comment by Ja7ad** [comment]
> That query parameter format looks correct to me. You expect it to be
> ```
>  files?paginated[filters][categoryId]=12335325
> ```
> instead of
> ```
>  files?paginated.filters[categoryId]=12335325
> ```
> ? If so, that doesn't make any sense to me, the square bracket syntax is only used for maps, where the key is specified by the user. The field `filters` is known, and so it shouldn't be a square bracket lookup. Maybe I'm misunderstanding you?

You right, but for nested message, this happen paginated is as object with dot.

```go
paginated.filters[categoryId]=12335325
```

**Comment by johanbrandhorst** [comment]
I'm not sure I understand what you're saying. `filters` is a field on `PaginatedListRequest`, so naturally it will be accessed as `paginated.filters`. If you want `paginated[filters]`, you have to make `PaginatedListRequest`(the whole thing) a map directly in your `ListCaseFileRequest`.

**Comment by Ja7ad** [comment]
> I'm not sure I understand what you're saying. `filters` is a field on `PaginatedListRequest`, so naturally it will be accessed as `paginated.filters`. If you want `paginated[filters]`, you have to make `PaginatedListRequest`(the whole thing) a map directly in your `ListCaseFileRequest`.

Your meaning is:

```go
ListCaseFileRequest {
    string case_id = 1;
    map<string, string> paginated = 2;
}
```

?

**Comment by Ja7ad** [comment]
> No, what I mean is
> ```
> ListCaseFileRequest {
>     string case_id = 1;
>     map<string, string> paginated = 2;
> }
> ```
> 
> But this is obviously worse than what you have. I think you just have to work with the field as it is, I don't really understand the problem, just use a `.` instead of `[]`?

Just problem is, in JavaScript query parameters don't detect `.` as objects in serialization.

**Comment by johanbrandhorst** [comment]
What you can do is write your own query parameter parser if you want to use a different structure for your query parameters, but I think this would be a mistake. You can specify this option when creating your gateway: https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#SetQueryParameterParser. There's nothing much else we can do here so I'm going to close this issue.
