### ISSUE TITLE
Feature request: custom content type per service and rpc

### ISSUE THREAD

**Issue by c4milo** [grpc-ecosystem/grpc-gateway#302]
We would like to version services and individual operations through their content-type and accept headers. For this, we would need a way  of declaring Swagger's `produces` and `consumes` in the protobuf file. Any thoughts?

**Comment by achew22** [comment]
@c4milo, seems like an interesting idea. To do this you will have to modify the [upstream proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) that this project implements. We have decided that we don't want to modify it locally to prevent an accidental fork from the spec.

If you decide to open a dialogue on [googleapis/googleapis](https://github.com/googleapis/googleapis/) about this please add me on the issue. I would love to see how things play out.

I'm going to close this until the upstream proto is changed.
