### ISSUE TITLE
PATCH a repeated field of type google.protobuf.Any returns a 502

### ISSUE THREAD

**Issue by veith** [grpc-ecosystem/grpc-gateway#3078]
## 🐛 Bug Report

When you send a repeated field of type `any` the gateway always returns a 502. This is because the check in runtime/fieldmask.go only proves for `hasTypeField := v.(map[string]interface{})["@type"]`.  

As i understood the documentation repeated fields must be send completely and must be at the end of the list, i am not sure about nested repeated fields. But adding a check `&& !fd.IsList() ` to https://github.com/grpc-ecosystem/grpc-gateway/blob/530490313c30c645d2ab496ca8eb369683fa0c25/runtime/fieldmask.go#L67 will run and result in correct fieldmask.

```go
if isProtobufAnyMessage(fd.Message()) && !fd.IsList() {
					_, hasTypeField := v.(map[string]interface{})["@type"]
					if hasTypeField {
						queue = append(queue, fieldMaskPathItem{path: k})
						continue
					} else {
						return nil, fmt.Errorf("could not find field @type in %q in message %q", k, item.msg.Descriptor().FullName())
					}

				}
```

## To Reproduce

1. Define a repeated field of type google.protobuf.Any
2. Define a fieldmask for the request type

## Expected behavior
Do not try to go deeper in repeated fields of type google.protobuf.Any

## Actual Behavior
Gateway returns a 502

**Comment by johanbrandhorst** [comment]
Hi, thanks for your bug report. Honestly this logic is confusing even to me, but if you've got a use case that we can easily add a test for and this patch doesn't break any existing tests, we should go ahead and apply it :). Are you interested in contributing this fix?
