### ISSUE TITLE
Package imported but not used

### ISSUE THREAD

**Issue by fische** [grpc-ecosystem/grpc-gateway#310]
Hi!
When a service method uses a type `T` from an imported proto and does not define the option `google.api.http` to get exposed by the grpc-gateway, `protoc-gen-grpc-gateway` tries anyway to import the package, where the type `T` is defined, and therefore I get the following message when I try to compile the gateway:
```
./main.pb.gw.go:17: imported and not used: "github.com/golang/protobuf/ptypes/empty"
```

Here's an example of such service:
```protobuf
syntax = "proto3";

import "google/api/annotations.proto";
import "github.com/golang/protobuf/ptypes/empty/empty.proto";

package tester;

service Service {
  rpc MethodExposed (Message) returns (Message) {
    option (google.api.http) = {
      post: "/exposed"
      body: "*"
    };
  }

  rpc MethodImportingEmpty (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message Message {
	string value = 1;
}
```

**Comment by tmc** [comment]
@fische thanks for the report -- could you put an example into a failing test case?

**Comment by fische** [comment]
The example I've put above is a failing test case.
It tries to import the `empty.proto` which defines the message type `Empty`. However the method of `Service`, that uses this message type, does not define the option `google.api.http`, so that it does not get exposed by the `grpc-gateway`. During the code generation of the gateway, `protoc-gen-grpc-gateway` will add anyway the import of the `empty` package to the `pb.gw.go`, even if it is not used.

**Comment by tmc** [comment]
@fische I mean can you add a test case that demonstrates the failure (perhaps to #312)
