### ISSUE TITLE
The http header mapping behavior is different from documentation

### ISSUE THREAD

**Issue by shuz** [grpc-ecosystem/grpc-gateway#3102]
## 📚 Documentation

The documentation says:
> HTTP headers that start with 'Grpc-Metadata-' are mapped to gRPC metadata (prefixed with grpcgateway-).

I expected the metadata being prefixed with `grpcgateway-`. However they are not. After digging into the code, it turns out that the code doesn't add the prefix to the metadata:

```
// DefaultHeaderMatcher is used to pass http request headers to/from gRPC context. This adds permanent HTTP header
// keys (as specified by the IANA) to gRPC context with grpcgateway- prefix. HTTP headers that start with
// 'Grpc-Metadata-' are mapped to gRPC metadata after removing prefix 'Grpc-Metadata-'.
func DefaultHeaderMatcher(key string) (string, bool) {
	key = textproto.CanonicalMIMEHeaderKey(key)
	if isPermanentHTTPHeader(key) {
		return MetadataPrefix + key, true
	} else if strings.HasPrefix(key, MetadataHeaderPrefix) {
		return key[len(MetadataHeaderPrefix):], true
	}
	return "", false
}
```

Since our code base relies on this behavior, fixing the code may break existing users. So maybe it's good to just change the documentation to align with the code.

**Comment by johanbrandhorst** [comment]
Seems like we could definitely update the docs here. I think the important distinction is that the `grpcgateway-` prefix is added for any Permanent HTTP Headers (as defined by the IANA), but not generally for all headers. Would you be willing to contribute this fix?
