### ISSUE TITLE
openapiv2_schema should extend google.protobuf.MethodOptions but instead extends google.protobuf.MessageOptions

### ISSUE THREAD

**Issue by MarcoFaccani** [grpc-ecosystem/grpc-gateway#3122]
## 🐛 Bug Report

I've a gRPC proto file from which I want to autogenerate a swagger file.
In order to customize and add more details to the swagger, as shown in [this](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#using-proto-options) guide, I've added the following two proto files to my project:

- [protoc-gen-openapiv2/options/openapiv2.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/options/openapiv2.proto)
- [protoc-gen-openapiv2/options/annotations.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/options/annotations.proto) (imports the above proto file)

## To Reproduce

1. Create a proto file with a gRPC endpoint as described in [this](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#using-proto-options) guide

2. Import in your project [protoc-gen-openapiv2/options/openapiv2.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/options/openapiv2.proto)

3. Import in your project [protoc-gen-openapiv2/options/annotations.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/options/annotations.proto)

> In order to be able to generate the swagger you will need in your project also `buf.gen.yaml`, `buf.work.yaml` and `buf.yaml`

## Expected behavior

Generation of the swagger file by running the command `buf generate`

## Actual Behavior

Command returns the following error: `protoc-gen-openapiv2/options/annotations.proto:29:29:extension with tag 1042 for message google.protobuf.MethodOptions already defined at protoc-gen-openapiv2/options/annotations.proto:22:35`

## Your Environment

Local environment, OSX

**Comment by johanbrandhorst** [comment]
Could you share the contents of your `buf.yaml`? I have a suspicion that this error is because you're both adding the files and depending on the repository via buf. This error implies that you have two copies of this file. Unless you know of another file in your protobuf hierarchy that extends MethodOptions with tag 1042?

**Comment by johanbrandhorst** [comment]
Great, as I suspected, you've got two instance of the protobuf files. Simply remove the `google` folder (https://github.com/MarcoFaccani/issue-proto-file/tree/main/api/src/main/proto/google/api) from your structure. Buf supplies this directory at generation time when you specify a dependency, no need to manage files yourself!

I'm going to close this as this is a configuration issue. Let me know if that still doesn't fix your problem!

**Comment by MarcoFaccani** [comment]
I've given it a shot but by deleting the google folder and running `buf generate` I get` proto/google/api/annotations.proto: does not exist`. You mentioned buf is supposed to autogenerate it?

I've also given another look at [this](https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/adding_annotations/#generating-the-grpc-gateway-stubs) part of the guide but it seems to me that everything is as it is supposed to be. What am I missing?

Thank you for your time, Johanbrandhorst

**Comment by johanbrandhorst** [comment]
Are you importing it via the path `proto/google/api/annotations.proto`? You'll need to use `import "google/api/annotations.proto";`.

**Comment by smaliziola** [comment]
Hi Johanbrandhorst, sorry if I jump in but @MarcoFaccani and I are working on the same issue.
Yes, the import is correct:
```
syntax = "proto3";

package mypackage.service;

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

...
```

**Comment by johanbrandhorst** [comment]
The repository shared by Marco has another issue; https://github.com/MarcoFaccani/issue-proto-file/blob/main/api/src/main/proto/v1/MyTest.proto#L7 this should be `protoc-gen-openapiv2/options/annotations.proto`. You can see the example imports here: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/proto/examplepb/a_bit_of_everything.proto#L17.

**Comment by johanbrandhorst** [comment]
This might be easier to debug if you join [Gophers Slack](https://join.slack.com/t/gophers/shared_invite/zt-1n8c0wnv7-Xp8VXAK47f3OM2ioR~08Wg) and join the #grpc-gateway channel. This issue tracker isn't great for this sort of back and forth.
