### ISSUE TITLE
deprecate 1.6 and embrace (*http.Request).Context by default

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#313]
I'm opening this to gather feedback. With 1.8's release I think we should now talk about removing 1.6 support by default and allow per-http request. This will enable things like tracing over gateway calls.

**Comment by achew22** [comment]
+1, I think following the release cycle of Go closely will help keep down the clutter. This will represent a breaking change. Does that mean a 2.x series?

**Comment by tmc** [comment]
while I'm skeptical of semver, yes I think so. We should get another 1.x release out before cutting a 2.x

**Comment by achew22** [comment]
This is now available by a flag.
