### ISSUE TITLE
feat: ServeMux add OnHandle to support callback when mux.Handle is called

### ISSUE THREAD

**Issue by hnlq715** [grpc-ecosystem/grpc-gateway#3133]
## 🚀 Feature

(A clear and concise description of what the feature is.)

This is helpful to register generated route path to any framework like echo.

I'll send a PR if this sounds interesting. Thanks.

**Comment by hnlq715** [comment]
For those frameworks do not support http.Handler, the OnHandle callback would help to register router from the runtime.ServeMux.

Take echo server as an example:
```
	server := echo.New()

	mux := runtime.NewServeMux(
		runtime.WithOnHandle(func(mux *runtime.ServeMux, method string, pat runtime.Pattern) {
			server.Add(method, pat.String(), echo.WrapHandler(mux))
		}),
	)

	_ = testproto.RegisterGreeterServiceHandlerServer(context.Background(),
		mux, new(yell.FooServer))

```

**Comment by johanbrandhorst** [comment]
I see. This isn't something we're interested in supporting in the gRPC-Gateway. The standard library http.Handler is a well established standard for interoperating between different HTTP libraries, and we already support that. Thanks for understanding.

**Comment by hnlq715** [comment]
That's alright :-)

I've also implement the protoc plugin to generate RegisterXXXHandler for any HTTP server, and get better performance.
