### ISSUE TITLE
OpenAPI configuration through external configuration file

### ISSUE THREAD

**Issue by tomasbasham** [grpc-ecosystem/grpc-gateway#3155]
## 🚀 Feature

I'd like to be able to configure OpenAPI/Swagger within a separate file, similar to how HTTP rules can be defined within a separate configuration file for the `protoc-gen-grpc-gateway` plugin. Currently there is an [option](https://github.com/grpc-ecosystem/grpc-gateway/commit/cecba55bf487e27651338795431df86ef327c103#diff-044e792b475757b046056e718802b4d299dd719a8db52989991b1452243fb5c9R22) within the `protoc-gen-openapiv2` binary to pass in a configuration file but this file may only contain HTTP rules, as defined [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/f4bacf79f3379bf0c3afcde895d9072350dbe47f/internal/descriptor/apiconfig/apiconfig.pb.go#L33).

This feature would be useful so that resultant generated language stubs do not contain reference to external annotations that are subsequently not used. Whilst in Golang this is not much of an issue, because the necessary packages are available online, this is not the case for other languages.

For example this is what is generated by the Ruby protoc generator plugin:

```ruby
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/service/metadata/v1/metadata.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'protoc-gen-openapiv2/options/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  # ... omitted for brevity
end
```

where, to the best of my knowledge, `protoc-gen-openapiv2/options/annotations_pb` is not a gem available online. Furthermore this import is not used anywhere within the code. Whilst an alternative would be to additionally generate the code for this annotations file, I don't believe this is practical.

Being able to configure these annotations from an external files allows for the annotations to be removed from the `.proto` file entirely and therefore the imports are not included in the resultant code.

Ideally I would prefer to keep all the configuration within a single protocol buffer file, and be able to omit imports from generated code, but I suspect this would require a change to the `protoc` code.

**Comment by johanbrandhorst** [comment]
Hi Tomas, maybe you missed the `openapi_configuration` option defined a bit further down: https://github.com/grpc-ecosystem/grpc-gateway/blob/70c4deb1cdf6953f94d8a581da01fed1aecf6608/protoc-gen-openapiv2/main.go#L37

I think this should let you define the annotations outside of your protobuf file. https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/grpc_api_configuration/#using-an-external-configuration-file has a small example. Thanks for the unique perspective on this feature though, I hadn't considered that 😄. Let me know if that doesn't do what you want and I'll reopen the issue.

**Comment by tomasbasham** [comment]
I certainly did miss that. Thanks for pointing it out.
