### ISSUE TITLE
Support map type in query string

### ISSUE THREAD

**Issue by tamalsaha** [grpc-ecosystem/grpc-gateway#316]
Is it possible to support map[string]string in the query parameters?

**Comment by sagikazarmark** [comment]
Something like `?filters[key]=value` would be nice

**Comment by tmc** [comment]
I think this would be a nice addition -- the http.proto documentation doesn't describe map field population from query arguments so my only concern here would be a divergence from how any equivalent google service would behave (e.g. cloud endpoints).

**Comment by TamalSaha** [comment]
@tmc, that might be just an artifacts of the fact that original protobuf did not have map types and http.proto was defined before proto 3 (my guess).
