### ISSUE TITLE
Swagger docs validate failed when enums_as_ints=true 

### ISSUE THREAD

**Issue by hnlq715** [grpc-ecosystem/grpc-gateway#3162]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

Related issue: https://github.com/go-swagger/go-swagger/issues/2890

## To Reproduce

(Write your steps here:)

Details can be found in this pr https://github.com/hnlq715/proto/pull/3/files

## Expected behavior

Pass validation.
(Write what you thought would happen.)

## Actual Behavior
```
The swagger spec at "gen/go/api/helloworld/v1/helloworld.swagger.json" is invalid against swagger specification 2.0.
See errors below:
- in operation "GreeterService_SayHello", default value in response 200 does not validate its schema
- 200.data.sex.default in body must be of type integer: "string"
- 200.data.sex.default in body should be one of [1 2]
- in operation "GreeterService_SayHello2", default value in response 200 does not validate its schema
- definitions.v1Sex.default in body must be of type integer: "string"
- definitions.v1Sex.default in body should be one of [1 2]
```
(Write what happened. Add screenshots, if applicable.)

## Your Environment

(Environment name, version and operating system.)

**Comment by hnlq715** [comment]
The root case I found is the `Enum` and `Default` type is still string even when enums_as_ints set to true.

https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/internal/genopenapi/types.go#L182

**Comment by johanbrandhorst** [comment]
Hi, thanks for your bug report! This does indeed seem wrong. You've also already identified where the problem is - well done! I'm wondering if instead of `interface[]`, this might be a good use case for generics? We could use

```
type IntOrString interface {
    string | int
}
```.

I've no idea if this makes sense, but maybe it would? Would you be interested in helping fix this? If we can't use generics, we can use `interface[]` instead of course.

**Comment by hnlq715** [comment]
There's a lot limitation about generics for now, I tried but failed :-)
So I submit a implementation with `interface{}`.
