### ISSUE TITLE
grpc gateway with rest server running into grpc limits on both validation and regular requests

### ISSUE THREAD

**Issue by sandakith** [grpc-ecosystem/grpc-gateway#3169]
## 🐛 Bug Report

We are using grpc multi server with both rest and grpc protocols implemented as indicate below. The issue now is how can we set/increase grpc limits when we are calling http calls as we are running into 
{"code":8, "message":"grpc: received message larger than max (5228203 vs. 4194304)", "details":[]} 

```

	"golang.org/x/net/context"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/google/uuid"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/reflect/protoreflect"
	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/protoc-gen-go/descriptor"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	errdetails "google.golang.org/genproto/googleapis/rpc/errdetails"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"google.golang.org/grpc/reflection"


        restServer := &http.Server{}
	grpcServer := grpc.NewServer()

        m0 "gen/go/analytics/v1rc0"


        type m0_server struct {
	        m0.UnimplementedAnalyticsServiceServer
        }

       ctx := context.Background()

	dopts := []grpc.DialOption{grpc.WithInsecure(), grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(*sizeFlag), grpc.MaxCallSendMsgSize(*sizeFlag))}

	gwmux := runtime.NewServeMux(
		runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{
			MarshalOptions: protojson.MarshalOptions{
				UseProtoNames: true,
				EmitUnpopulated: true,
			},
		}),
	)

		m0.RegisterAnalyticsServiceServer(grpcServer, &m0_server{})
		err := m0.RegisterAnalyticsServiceHandlerFromEndpoint(ctx, gwmux, fmt.Sprintf("localhost%s", grpcPort), dopts)

	mux := http.NewServeMux()
	handler := httpHeaderHandler(gzipResponseHandler(gwmux))
	mux.Handle("/", handler)

	restServer.Addr = restPort
	restServer.Handler = mux

	grpcMultiServer := &http.Server{}
	grpcMultiServer.Addr = grpcPort
	grpcMultiServer.Handler = grpcHandlerFunc(grpcServer, mux)
	go func() {
		err := grpcMultiServer.ListenAndServe()
		if err != nil {
			log.Printf("GRPC server on %s: %v", grpcPort, err)
		}
	}()
```

Is there a way we can increase limits when we call rest server ? Please share any related details. TIA

**Comment by johanbrandhorst** [comment]
Hi Sandakith, thanks for your issue! This is a generic gRPC error, and you can tweak the maximum request and response limits (both client and server side) using [DialOptions](https://pkg.go.dev/google.golang.org/grpc#DialOption) and [ServerOptions](https://pkg.go.dev/google.golang.org/grpc#ServerOption). In your case, that would be https://pkg.go.dev/google.golang.org/grpc#MaxRecvMsgSize when creating your gRPC server. Hope that helps!

**Comment by sandakith** [comment]
I am not sure why you close the issue, what I am saying is its working on grpc and not with http mux rest API ?

**Comment by johanbrandhorst** [comment]
The  error you're seeing is not an error from the gRPC-Gateway. There is nothing we can fix on this end. I can see the dial options you've specified for your client, but what are the server options you specified for your gRPC server? That is where you need to make the change.

**Comment by sandakith** [comment]
I think the code that I pasted had a issue, not updated, we think with codegen we are updating the server correctly registering server with opts

**Comment by johanbrandhorst** [comment]
I still can't see where you are creating the gRPC server.

**Comment by sandakith** [comment]
Thanks for your reply. I have added server init commands. However as per your documentation dial options are added when after server creation and at the point of registrating handlers as we have done above?

**Comment by johanbrandhorst** [comment]
```
	grpcServer := grpc.NewServer()
```

This is the problem. You need to set the server max recv size when you create it. Replace it with

```
	grpcServer := grpc.NewServer(grpc.MaxRecvMsgSize(4*1024*1024)) // 4MiB, or whatever value you want.
```

This is the option I pointed out in my original comment. It still has nothing to do with the gRPC-Gateway.

**Comment by sandakith** [comment]
Thanks for the suggestion, we have tested with it but not luck, Is there a way to confirm when was this change added and we might be in a old version or the gateway and libs ?

**Comment by johanbrandhorst** [comment]
This setting has been available for many years. If you're still getting the error I'm not sure what to tell you, there's also a MaxSendMsgSize that you might want to tweak. Again, this has nothing to do with the gateway, it is not a bug in this repo. Please consult the grpc-go documentation.

**Comment by sandakith** [comment]
Thanks for your suggestions, we can test this and report here.
