### ISSUE TITLE
Export swagger with go embed

### ISSUE THREAD

**Issue by AlmogBaku** [grpc-ecosystem/grpc-gateway#3195]
## 🚀 Feature

By specifying a flag `go_embed=true`, the swagger generator will also export a file named `base/%s.swagger.go` which embeds the file using go embed:

```go
import "embed"

//go:embed %s.swagger.%ext
var f embed.FS
```

If that's accepted, I can work on a PR. (I already have an idea how to implement this)

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I don't think this is something we want to support, it's easy enough for a user to do this themselves if they want to, and any new flag adds maintenance cost.

**Comment by AlmogBaku** [comment]
The current implementation is quite challenging to use in conjunction with a tool such as buf(or remote buf) or any other solution which declares the autogenerated package as a standalone package.

To solve it, I must create some (ugly) script that fetches the file from the gopkg and copy it.


I think this feature is much more elegant, and I'm willing to implement it :)

**Comment by johanbrandhorst** [comment]
I'm confused, what's challenging about using the current implementation? I use it with embed in our grpc-gateway boilerplate repo: https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/main/third_party/embed.go.

**Comment by johanbrandhorst** [comment]
How are you using the BSR in a way that produces `swagger.json` files that are not in your hierarchy? The remote packages only support JS and Go, so you'd have to use a remote plugin, which should output the swagger file locally. Unless a remote Go package with the swagger file embedded is exactly what you mean? If so, that seems a very narrow usecase to me.

**Comment by AlmogBaku** [comment]
> remote Go package with the swagger file embedded
yep


However, it's not only that - theoretically, if you want to gitignore the generated directory, it's also a bit cumbersome...

**Comment by johanbrandhorst** [comment]
Thanks for jumping in here, I'm still going to say no. I think this is wildly outside of the responsibilities of the swagger generator. Thank you for sharing your workaround for this niche use case.
