### ISSUE TITLE
Use of macros for multipart-formdata bytes fields [enchancement]

### ISSUE THREAD

**Issue by KiK0S** [grpc-ecosystem/grpc-gateway#3198]
Hi! First of all, thanks for creating and supporting grpc-gateway.
We at neiro.ai use it for our ML APIs that process media files such as audio and video. For us, grpc-gateway was an easy way to support both rest and grpc in our API. However, almost every request has a media file in bytes. There must be a more convenient way to handle files then explicitly converting them to base64 in REST API. There is a section in the documentation about how to do binary upload and it looks like "handle raw data by yourself", but we wanted to keep our data structure and use the advantages of your proxy.

Right now docs do not give you much information about how to handle this. Grpc-gateway doesn't support it too.

We solved this issue with ad-hoc macros processing. How it works: you send multipart/form-data with your request and media files. In your request body, you mark media files with macroses. Then, our middleware recursively parses json and looks for a place to expand macros with the file content. Then it goes the standard way through grpc-gateway proxy. Yes, it may be extra latency, but for manual testing, it was a must-have for us.

Example (out speech recognition request):
```jsx
{
    "token": "",
    "audio": {
        "data": "$speech"
    }
}
```

```bash
curl $HOST/v1/asr -X POST 
                -F 'data=@json/asr.json' -F '$speech=@voice.wav'
```

Technically, what we do inside is filter multipart/form-data requests, get their json body in reserved field `data`, and then create standard json request with substitutions

```golang
func EncodeAndSubstitute(jsonData map[string]interface{}, r *http.Request, res *map[string]interface{}) error {
	for name, val := range jsonData {
		rec_map, ismap := val.(map[string]interface{})
		if ismap {
			(*res)[name] = map[string]interface{}{}
			rec_res, _ := (*res)[name].(map[string]interface{})
			err := EncodeAndSubstitute(rec_map, r, &rec_res)
			if err != nil {
				return err
			}
		} else if valStr, ok := val.(string); ok && strings.HasPrefix(valStr, "$") {
			data, err := GetFormFile(r, valStr)
			if err != nil {
				return fmt.Errorf("can not get file %s", val.(string))
			}
			(*res)[name] = base64.StdEncoding.EncodeToString(data)
		} else {
			(*res)[name] = val
		}
	}
	return nil
}
```

It seems like this approach can be used in other projects as well. Maybe we should add another section in https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/binary_file_uploads/ or another page in the documentation? Maybe it can be implemented as part of grpc-gateway? What do you think?

**Comment by johanbrandhorst** [comment]
Hi Konstantin, thanks for sharing this! It is a very interesting approach to supporting uploads in the gateway. I have some concerns though:

1. This is subject to the per-message size limit in unary gRPC requests. You can technically set the limit to be arbitrarily large with [MaxCallSendMsgSize](https://pkg.go.dev/google.golang.org/grpc#MaxCallSendMsgSize) and [MaxRecvMsgSize](https://pkg.go.dev/google.golang.org/grpc#MaxRecvMsgSize) but you're going to hit problems at larger sizes. Maybe you can dictate the maximum size of any request and this is not a problem for you.
2. The user is using multipart uploads which is good but you still have to buffer the whole request in memory in the gateway _and_ in the gRPC handler.
3. Using base64 encoding to store binary data in JSON is going to be expensive for larger files and further increases the data use. Your JSON unmarshaler is going to be working very hard to create the gRPC requests.

We typically recommend using a custom multipart upload handler instead, as you hint at. https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/binary_file_uploads/ has a small give to how to attach this handler to the normal gateway mux. You could even write a multipart upload handler that parses your multipart uploads and stream it to your gRPC server. I would think this would be a more suitable solution, unless you're only handling small files.

Regardless, this is really cool and thanks again for sharing. I don't think we'll want to integrate this into the gateway or change our general recommendation for file uploads, but if you write a blog post about this I'd be happy to add a link to the docs to your blog.

What do you think?

**Comment by KiK0S** [comment]
I fully understand your performance concerns. In our case, we use this approach mostly for convenient manual testing. We designed our API customizable so it either takes cloud object storage links or raw `bytes` field and it is up to the client and their use case.

We have planned to share this approach in some kind of blog post as well. Discussing with grpc-gateway authors if our idea can be contributed to either framework or docs was the first step. So yeah, I think now we will create a blog post and I'll return to you with the link. The final decision if it should be added to docs is up to you, but I really think it may help someone working with grpc-gateway in the future.

Thanks for your answer!

**Comment by ghostiam** [comment]
In my project, I made a custom unmarshaler for "multipart/form-data" that accepts fields and files.

https://gist.github.com/ghostiam/48acd974f2044e25ba43f090316e6f2d

**Comment by KiK0S** [comment]
@johanbrandhorst Hi! I'm here again, now with a blog post and public github example: https://medium.com/neiro-ai/grpc-gateway-for-media-api-by-neiro-9033caab12c8. https://github.com/mynalabsai/grpc_gateway_media_example
If you find it usedul, feel free to add it to docs.

**Comment by johanbrandhorst** [comment]
Great! If you'd like to make a PR, we could add it to the "More examples" section of the README.

**Comment by KiK0S** [comment]
@johanbrandhorst created https://github.com/grpc-ecosystem/grpc-gateway/pull/3247, feel free to suggest changes
