### ISSUE TITLE
Github Action `push_bsr_plugins` is failing

### ISSUE THREAD

**Issue by gunturaf** [grpc-ecosystem/grpc-gateway#3202]
## 🐛 Bug Report

The job [push_bsr_plugins](https://github.com/grpc-ecosystem/grpc-gateway/actions/runs/4246481305/jobs/7383348765#logs) is failing, I think it's due to the change in the URL path of the plugin from https://buf.build/grpc-ecosystem/grpc-gateway to https://buf.build/grpc-ecosystem/gateway.

I can't seem to find the documentation of how to push the plugin to buf.build , but I assume that we only need to do little adjustment to the `docker push` command.

In the meantime before this fixed, can you help by manually pushing the v2.15.1 to buf.build?

## To Reproduce

https://github.com/grpc-ecosystem/grpc-gateway/actions/runs/4246481305/jobs/7383348765#logs

## Expected behavior

The push to buf.build succeeds.

## Actual Behavior

```
Error: buildx failed with: ERROR: failed to solve: failed to push plugins.buf.build/grpc-ecosystem/grpc-gateway:v2.15.1-1: failed commit on ref "manifest-sha256:2b3a737a779e4f4a6e6746240c63c7c53904ad7275905d9866aa87c5b4581fa9": unexpected status: 400 Bad Request
```

**Comment by johanbrandhorst** [comment]
Buf is handling the publishing of these plugins now, so we should really remove them. v2.15.1 is now available on the registry: https://buf.build/grpc-ecosystem/gateway.
