### ISSUE TITLE
gRPC gateway REST service which sends proto as a response not JSON

### ISSUE THREAD

**Issue by scarshad** [grpc-ecosystem/grpc-gateway#3256]
I am using gRPC gateway for the backward compatibility support but I encountered an issue where in our REST APIs we are using the Protobuf with REST. But in gRPC gateway we are using JSON as a response type.
Now when we have migrated towards gRPC, but I am not seeing any option where I will receive the response as a proto type not the JSON type. Can someone please help me in this?

I am getting `content-type` with the REST url: `application/json`
What I need: `application/x-protobuf`

EDIT:
I have this service contract
```proto
service TestService {
  rpc GetBattleStatusByEntityIds(ProtoRequest) returns (ProtoResponse) {
    option (google.api.http) = {
      get : "/test"
    };
  }
}
```

When I am hitting this `/test` url then I am receiving the response with content type `application/json` but I need the data in `application/x-protobuf` format. I checked the grpc-gateway code and it is using a marshaller which change the response from protobuf to json. Can you please help me to keep it like json any code sample would help.

https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/marshal_jsonpb.go

Picture of wanted response type: https://i.stack.imgur.com/jvR3w.png

**Comment by johanbrandhorst** [comment]
If you really want the gateway to respond with protobuf, you can register a marshaler against the content type of your choice using https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption.

I'm a little confused though, if you're using gRPC, just hit the gRPC server directly? There's no need to go via the gateway in that case.

I'm going to close this issue as this is not a problem with the gateway. Please reach out on our support channel (#grpc-gateway on Gophers Slack) if you still need help.

**Comment by scarshad** [comment]
Just for the devs facing same problem, this solved my problem
```go
//REGISTER GIN WITH GRPC SERVER
	gatewayMux := runtime.NewServeMux(
		// custom marshaller for the protobuf response for the requests which have the `Accept header` as `application/protobuf`
		// used the grpc gateway proto marshaller
		runtime.WithMarshalerOption("*/*", &runtime.ProtoMarshaller{}),
	)
```
