### ISSUE TITLE
Move to stdlib context over x/net/context

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#326]
Placeholder issue.

We'll wait to do this until https://github.com/grpc/grpc-go/issues/711 closes.

**Comment by TamalSaha** [comment]
cc: @sadlil

**Comment by AlekSi** [comment]
Not really required with Go 1.9 aliases.

**Comment by achew22** [comment]
Not really required, but I assume the x/net/context package will eventually go away so we should proably just do it.
