### ISSUE TITLE
yaml support gRPC gateway

### ISSUE THREAD

**Issue by debankur1** [grpc-ecosystem/grpc-gateway#3261]
do the grpc gateway support Yaml on the northbound REST API?

**Comment by johanbrandhorst** [comment]
Hi, you can configure a custom marshaler, including one responding with yaml, using `WithMarshalerOption`: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#custom-serializer. It sounds abit cursed though, don't you think 😁?
