### ISSUE TITLE
How can I use slash symbol in path parameter?

### ISSUE THREAD

**Issue by KimuraYu45z** [grpc-ecosystem/grpc-gateway#3263]
e.g.

```
GET /api/categories/{category_name}
```

if I input `electronics/camera` into `{category_name}`, I thought that I need to encode the value like `electronics%2Fcamera`, however it also doesn't work.

How can I handle this?

**Comment by johanbrandhorst** [comment]
I think you'll want to use a multi-segment variable capture, e.g.

```
GET /api/categories/{category_name=**}
```

See the spec: https://github.com/googleapis/googleapis/blob/0fac9e8428f71e402ac920ca6b8a935d6a2bdcc1/google/api/http.proto#L227-L264.

Hopefully that helps.

**Comment by qwertzguy** [comment]
@johanbrandhorst  In the spec is says that %2F should not be decoded by the server: https://github.com/googleapis/googleapis/blob/0fac9e8428f71e402ac920ca6b8a935d6a2bdcc1/google/api/http.proto#L260
But seems like grpc-gateway does it, which seems incorrect.

**Comment by johanbrandhorst** [comment]
Hi, could you raise a separate issue with an example that reproduces the issue? Thanks!
