### ISSUE TITLE
The PathLengthFallback option picks fallback methods non-deterministically

### ISSUE THREAD

**Issue by nacx** [grpc-ecosystem/grpc-gateway#3266]
## 🐛 Bug Report

When the `disablePathLengthFallback` option is enabled (the default behavior), the handler selection is non-deterministic, leading to unexpected (and potentially dangerous behavior, especially if DELETE methods are present in the handler.

The following code in `mux.go`, iterates over the map of handlers, but map iteration order is non-deterministic. The method assumes a fallback to POST, but if a DELETE method was defined for the same request path, it could be selected by mistake.
https://github.com/grpc-ecosystem/grpc-gateway/blob/836817217b6fe57bd95421b5fe7589c542e549d8/runtime/mux.go#L392-L441

This could be an important issue as a deletion handler could be called by mistake, potentially destroying data.

## To Reproduce

Say the following URIs and methods are valid methods of an API:
```
GET /resources/foo
DELETE /resources/foo
```
And someone by mistake runs a request to: `POST /resources/foo`.
If the fallback mechanism is enabled, it will fallback either to the GET or the DELETE handler (because if the POST request has a body the `isPathLengthFallback` method would return `true`). If the DELETE method is selected, a DELETE operation could be triggered by mistake.

## Expected behavior

The fallback mechanism should only fallback from GET to POST, but not to other HTTP verbs.

## Actual Behavior

The fallback mechanism fallbacks to any other method in a non-deterministic way.

**Comment by johanbrandhorst** [comment]
Hi, thanks for raising this issue. That's definitely a bug (whoops!). Would you be interested in implementing a fix? At the very least we should make this deterministic, but you're right that it should probably also prioritize GETs.

**Comment by nacx** [comment]
Sure! I've raised a small PR changing the logic to only allow fallback for POST -> GET, as looking at the original feature discussions, I think that's the only case this code was targeting.
