### ISSUE TITLE
Fresh install no longer generates necessary `google/api/annotations.pb.go` & `google/api/http.pb.go` files.

### ISSUE THREAD

**Issue by marcusljx** [grpc-ecosystem/grpc-gateway#327]
Fresh install no longer generates necessary `google/api/annotations.pb.go` & `google/api/http.pb.go` files.

**Action**
```
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
go get -u github.com/golang/protobuf/protoc-gen-go
```

generate a proto project `someproject.pb.go` file, which contains
```
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
```

**Expected**
`annotations.pb.go` and `http.pb.go` generated successfully in `github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api`, and compilation completes properly.

**Actual**
Files not generated, and compilation fails with the error:
```
...../grpc-gateway/third_party/googleapis/google/api' has no buildable Go source files.
```

**Comment by tmc** [comment]
@marcusljx thank you for your issue report. can you share your full protoc invocation (privately if . needed) as you should get lines more like `import _ "google.golang.org/genproto/googleapis/api/annotations"`

**Comment by tmc** [comment]
Just to be clear we intentionally moved to the published go code published at `https://godoc.org/google.golang.org/genproto`

**Comment by dong77** [comment]
I'm having this very issue right now. How to fix it ?

**Comment by tmc** [comment]
@dong77 thanks for chiming in -- if your generated go files have 'github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api' references then you're using an outdated `protoc-gen-grpc-gateway`

**Comment by biolee** [comment]
@tmc 
```bash
go get -u github.com/philips/grpc-gateway-example
grpc-gateway-example serve
```
![screenshot](https://cloud.githubusercontent.com/assets/7426917/23981161/7adfa5c8-0a3f-11e7-94c3-6d52c04d82a3.png)
no buildable Go source files

**Comment by biolee** [comment]
its philips/grpc-gateway-example's makefile not update, my problem solved

**Comment by tmc** [comment]
I opened https://github.com/philips/grpc-gateway-example/pull/15 to reflect this change.

**Comment by marcusljx** [comment]
As stated in the above makefile example, this was due to an outdated `go_out=` parameter.
