### ISSUE TITLE
body refer to inner most field in nested message structure

### ISSUE THREAD

**Issue by qazwsxedckll** [grpc-ecosystem/grpc-gateway#3278]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## To Reproduce

(Write your steps here:)

```
rpc CreateTemplate(CreateTemplateRequest) returns (Template) {
	option (google.api.http) = {
		post: "/v1/templates"
		body: "template"
	};
}

message Template {
	string name = 1;
	string description = 2;
	string template = 3;
}
```

when I send a request with
```
{
    "template": {
        "name": "test",
        "description": "test",
        "template": "test"
    }
}
```

I got

```
{
    "code": 3,
    "message": "proto: (line 2:22): invalid value for string type: {",
    "details": []
}
```

## Expected behavior

`body:"template"` should refer to outer template
`body:"template.template"` should refer to inner template

## Actual Behavior

It seems `body:"template"` is refering the inner one.

## Your Environment

(Environment name, version and operating system.)

**Comment by johanbrandhorst** [comment]
This is a configuration error, you need to use `body: "*"` if you want to match the whole message. Hope that helps!

**Comment by qazwsxedckll** [comment]
@johanbrandhorst
how about this situation:
```
{
    "template": {
        "name": "test",
        "description": "test",
        "template": "test"
    },
    "template_id": "mytemplate"
}
```
I am implementing google AIP and it says

> Note: For REST APIs, the user-specified ID field, {resource}_id, is provided as a query parameters on the request URI.

**Comment by qazwsxedckll** [comment]
'''
rpc CreateTemplate(CreateTemplateRequest) returns (Template) {
	option (google.api.http) = {
		post: "/v1/templates"
		body: "template"
	};
}

message Template {
	string name = 1;
	string description = 2;
	string template = 3;
}

{
    "name": "test",
    "description": "test",
    "template": "test"
}
'''

This works fine. Thanks for your time.
