### ISSUE TITLE
Support `examples` field in OpenAPI request objects spec

### ISSUE THREAD

**Issue by int64max** [grpc-ecosystem/grpc-gateway#3287]
## 🚀 Feature

When specifying the openapi spec options, currently, `examples` field is supported in the response object: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/options/openapiv2.proto#L287

I want to add multiple request examples too. The OpenAPI spec supports multiple examples in the request: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/3.0.0.md#example-object-example

From what I understand, this isn't supported. If it is, can you please show me how? If not, can we please have it? Thanks.

**Comment by johanbrandhorst** [comment]
Request examples are supported: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/options/openapiv2.proto#L443. Here's an example of an example: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/proto/examplepb/a_bit_of_everything.proto#L239.

**Comment by int64max** [comment]
Thanks for helping. I'm not talking about a single example in the request. I'm asking about adding multiple examples. For example, in the response object, "examples" is a map where you can add several named examples. On the other hand, in the request object, "example" is a plain string. I'm wondering how I can show multiple request examples.

If I'm missing something basic, I'd appreciate an example. The link you shared shows how to add a single example instead of several (unless I'm completely misreading things).

Thanks.

**Comment by johanbrandhorst** [comment]
I see, sorry for the confusion. It seems to me that OpenAPIv2 (the version supported by our plugin) does not share the same definition as OpenAPIv3 for it's request examples: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#fixed-fields-13. As you can see, "example" here is an "any", not a map.
