### ISSUE TITLE
is there interest in a http client generator in this project?

### ISSUE THREAD

**Issue by jstrachan** [grpc-ecosystem/grpc-gateway#3296]
## 🚀 Feature

we've found it super useful to code generate a golang http client along with the http server code for `grpc-gateway` generated gRPC code.   This means the same go tests can be used to test either GRPC client + server or the http client + server binding code to verify things work over both APIs

I'll happy submit it as a PR as an optional code generator & little client library. I thought I'd check if there was interest first before submitting

**Comment by johanbrandhorst** [comment]
Hi again James. Thanks for your issue! I personally don't think a Go client generator has a place in this repo, there are plenty of existing OpenAPI generators for Go and if you want to generate your client - why aren't you just using gRPC or [Connect](https://connect.build)? I see the primary use case for the gateway to be users who don't have that liberty and need to provide a pure HTTP/JSON API for some reason. We already have integration tests running to verify that the server behaves as expected given the generated OpenAPI spec with multiple third party OpenAPI generators as test oracles (for Go and JS). I hope that makes sense, and thanks again for offering.
