### ISSUE TITLE
Go get breaks with autogenerated code

### ISSUE THREAD

**Issue by jdoliner** [grpc-ecosystem/grpc-gateway#331]
We're seeing an issue when users attempt to `go get` a library that contains `pb.go` files which were built with grpc-gateway enabled. The issue seems to be that the files will include the line:

```go
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
```

Which doesn't contain any buildable go src files. It looks like it used to contain some but it currently doesn't in master. This results in the error:

```
package github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api: no buildable Go source files in /go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api
```

I can think of a couple ways to fix this:
- don't import that package, it seems like it can't be having much effect if there's no buildable src files in it
- add an empty go file that just says `package api` in it so that `go get` will work
- readd the compiled source for the protos, although presumably they were taken out for a reason so that might not be a good idea

Sorry if I'm missing something obvious here and misusing the library.

**Comment by tmc** [comment]
@jdoliner thanks for the issue report. This likely means you have an outdated "M" mapping in your protoc invocation. Can you share how you are invoking protoc?

Your protoc line should appear as something akin to:

```
protoc -I. \
	-I${GOPATH}/src \
	-I${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	--go_out=plugins=grpc:. \
	foobar.proto
```

**Comment by jdoliner** [comment]
@tmc, thanks for the quick response. That probably explains it here's our invocation:

```
protoc \
	-I${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	-I${GOPATH}/src/github.com/gogo/protobuf \
	-I${GOPATH}/src \
	-Isrc \
	--gogo_out=plugins=grpc,\
Mgoogle/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,\
Mgogoproto/gogo.proto=github.com/gogo/protobuf/gogoproto,\
Mclient/pfs/pfs.proto=github.com/pachyderm/pachyderm/src/client/pfs,\
Mclient/pps/pps.proto=github.com/pachyderm/pachyderm/src/client/pps,\
Mserver/pfs/fuse/fuse.proto=github.com/pachyderm/pachyderm/src/server/pfs/fuse,\
:src \
foobar.proto
```

Looks like the incorrect "M" mapping we're using is the one for annotations? What should we be using instead?

**Comment by tmc** [comment]
@jdoliner - I think you just need to eliminate 'Mgoogle/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,' -- please report back.

**Comment by jdoliner** [comment]
@tmc seems to have done the trick :), many thanks.

**Comment by tmc** [comment]
@jdoliner thanks!
