### ISSUE TITLE
How can I set global level "Bearer" or "x-api-key"  Security in Swagger? 

### ISSUE THREAD

**Issue by DasyDong** [grpc-ecosystem/grpc-gateway#3314]
It is not a Bug

As I could not find documentation on how to use more advanced features of swagger with grpc-gateway,   I could set a global x-api-key for all routes on swagger.json using securityDefinitions,  but I could not find any way to set global x-api-key for grpc-gateway . 

 
## swagger：
In swagger.json, when we use "securityDefinitions",  we could authorize all routes by set the key on swagger page .
Here's an example swagger.json file
```
"securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    }
  },
```
<img width="1116" alt="image" src="https://github.com/grpc-ecosystem/grpc-gateway/assets/9334289/4c4e60c8-efcb-422e-a1b4-26c1ddfaa162">

<img width="677" alt="image" src="https://github.com/grpc-ecosystem/grpc-gateway/assets/9334289/312ea77e-0c62-4958-9a2f-86ce90cee4f4">

## grpc-gateway
I try to use openapiv2_operation,it works , but it is only for route level , I don't want to add manually for every routes.  
```
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "helloproto/v1;helloproto";

service EchoService {
  rpc Hello(HelloReq) returns (HelloResp) {
    option (google.api.http) = {get: "/api/hello"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "X-Foo";
          description: "Foo Header";
          type: STRING,
          required: true;
        } 
      };
    };
  }
}

```
<img width="615" alt="image" src="https://github.com/grpc-ecosystem/grpc-gateway/assets/9334289/e94e7fc5-bd16-477e-8443-0bdc9903606d">

How can I define this in proto so that protoc-gen-swagger can generate above swagger.json with the global security option?

**Comment by johanbrandhorst** [comment]
I don't think we have a way to add a required parameter to all routes as you suggest. If adding this annotation manually is unacceptable, you might be best of doing some post-processing on the generated swagger file to add the required parameter. The point of the `securityDefinitions` is to do this for you, but clearly that is not solving the problem you want to solve. Sorry!
