### ISSUE TITLE
Failed to parse: parsing time \"2023-05-18T17:09:26 05:30\" as \"2006-01-02T15:04:05.999999999Z07:00\": cannot parse \"\" as \"Z07:00\"

### ISSUE THREAD

**Issue by parthyadav3105** [grpc-ecosystem/grpc-gateway#3316]
### Brief
When passing the Time value(lets us say `2023-05-18T14:17:23+05:30`) for [timestamp.Timestamp](google.golang.org/protobuf/types/known/timestamppb) type in the HTTP request, The request works fine for method **`POST`** but giving a parsing error for the **`GET`** method.

## To Reproduce

<details>
    <summary>Installing prerequisites.</summary>
    
      sudo apt install -y protobuf-compiler make gcc;
      
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1;
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0;
      go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.6.0;
      go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.6.0;
 
</details>

1. Create Folder `foo` and add `foo.proto` and `main.go` files with the following contents:
**foo.proto**
```protobuf

syntax = "proto3";

package foo;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "./main";

service Foo {
	rpc FooGet(Request) returns (Response) {
		option (google.api.http) = {
			get: "/api/v1/foo",
			response_body: "msg"
		};
	}

	rpc FooPost(Request) returns (Response) {
		option (google.api.http) = {
			post: "/api/v1/foo",
			body: "*",
			response_body: "msg"
		};
	}
}

message Request {
	google.protobuf.Timestamp when = 1;	
}

message Response {
	string msg = 1;
}
``` 

**main.go**
```go

package main

//go:generate protoc -I . -I ./third_party/ --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --grpc-gateway_out . --grpc-gateway_opt paths=source_relative foo.proto
//go:generate go fmt ./...

import (
	"context"
	"net"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/soheilhy/cmux"
	"google.golang.org/grpc"
)

type Foo struct {
	UnimplementedFooServer
}

func (f *Foo) Run(req *Request) (*Response, error) {
	msg := "We got time as " + req.GetWhen().AsTime().String()
	return &Response{
		Msg: msg,
	}, nil
}

func (f *Foo) FooGet(ctx context.Context, req *Request) (*Response, error) {
	return f.Run(req)
}

func (f *Foo) FooPost(ctx context.Context, req *Request) (*Response, error) {
	return f.Run(req)
}

func main() {
	ctx := context.Background()
	foo := &Foo{}

	server(ctx, foo)
}

func server(ctx context.Context, foo *Foo) error {

	listener, err := net.Listen("tcp", ":9090")
	if err != nil {
		return err
	}

	m := cmux.New(listener)
	grpcListener := m.MatchWithWriters(cmux.HTTP2MatchHeaderFieldSendSettings("content-type", "application/grpc"))
	httpListener := m.Match(cmux.Any())

	{ // start grpc server
		server := grpc.NewServer()
		RegisterFooServer(server, foo)
		go server.Serve(grpcListener)
	}

	{ // start http server
		opts := []grpc.DialOption{grpc.WithInsecure()}
		mux := runtime.NewServeMux()

		err := RegisterFooHandlerFromEndpoint(ctx, mux, ":9090", opts)
		if err != nil {
			return err
		}

		router := gin.Default()
		router.Group("/api/v1/*{grpc_gateway}").Any("", gin.WrapH(mux))
		go http.Serve(httpListener, router)
	}

	return m.Serve()
}
```
2. Run the following commands to setup and run server:
```bash
go mod init foo;
wget https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto -P third_party/google/api/;
wget https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/http.proto -P third_party/google/api/;
go generate ./...;
go mod tidy;
go get -d;
go run *.go;
```
3. **For reproducing error output:**

**Case 1:** Error(in get method):
```
curl --location --request GET 'http://localhost:9090/api/v1/foo?when=2023-05-18T17:09:26+05:30' \
--header 'Content-Type: application/json' 
```
*Output:*
```
{"code":3,"message":"parsing field \"when\": parsing time \"2023-05-18T17:09:26 05:30\" as \"2006-01-02T15:04:05.999999999Z07:00\": cannot parse \"\" as \"Z07:00\"","details":[]}
```

**Case 2:** Works fine(in post method):
```
curl --location --request POST 'http://localhost:9090/api/v1/foo' \
--header 'Content-Type: application/json' \
--data-raw '{
    "when": "2023-05-18T17:09:26+05:30"
}';
```
*Output:*
```
"We got time as 2023-05-18 11:39:26 +0000 UTC"
```
## Expected behavior

Should parse successfully in the **`GET`** method also.

## Actual Behavior

Gives parsing error for parsing time as bellow:
```
parsing field \"when\": parsing time \"2023-05-18T17:09:26 05:30\" as \"2006-01-02T15:04:05.999999999Z07:00\": cannot parse \"\" as \"Z07:00\"
```

## Your Environment

(Environment name, version and operating system.)
operating system: `Ubuntu 22.04.2 LTS (Jammy Jellyfish)`
golang: `go version go1.19.4 linux/amd64`
protoc: `libprotoc 3.12.4`
protoc-gen-go-grpc: `protoc-gen-go-grpc 1.1.0`
protoc-gen-go: `protoc-gen-go v1.27.1`
protoc-gen-grpc-gateway: `protoc-gen-grpc-gateway v2.6.0`
protoc-gen-openapiv2: `protoc-gen-openapiv2 v2.6.0`

**Comment by johanbrandhorst** [comment]
Hi, thanks for the thorough bug report! The default query parameter parser uses the `time.RFC3339Nano` format when parsing query parameters: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/query.go#L256. As you can see, this is readily reproducible: https://go.dev/play/p/7K6XurHR_gP. Using your original string however does work, (https://go.dev/play/p/sny8dB6Lq46), so I'm left to assume that there has to be a problem in your query escaping. Can you try formatting your query with pre-escaped values (like this: `http://localhost:9090/api/v1/foo?when=2023-05-18T17%3A09%3A26%2B05%3A30`, see https://go.dev/play/p/NiAki6WbkuZ)? I don't know why `curl` would do the wrong thing here, but have you tried any other clients?

**Comment by parthyadav3105** [comment]
Thank's @johanbrandhorst , This helps.

So, just to conclude my take aways from this as follow:
* In linux bash, the `curl` command seems to implicitly encode string passed in `--data-raw` flag but it is not the case for other arguments(like the url above). This led to above behaviour for post and get requests.
* Go did not seems to be happy with RFC3339 formatted time string obtained from linux [`date`](https://man7.org/linux/man-pages/man1/date.1.html) (v8.32) command using flag `--rfc-3339`. The work around is to use `--iso-8601` flag for shell. i.e. `date --iso-8601` as RFC3339 uses subset of ISO 8601 extended format.
