### ISSUE TITLE
Import alias issue with protoc-gen-grpc-gateway

### ISSUE THREAD

**Issue by hdkshingala** [grpc-ecosystem/grpc-gateway#3337]
## 🐛 Bug Report

With release `v2.15.2` and `v2.16.0`, we are seeing errors like below:
```
# github.com/fluxninja/aperture/v2/api/gen/proto/go/aperture/info/v1
gen/proto/go/aperture/info/v1/info.pb.gw.go:22:2: "google.golang.org/grpc/status" imported as status_0 and not used
gen/proto/go/aperture/info/v1/info.pb.gw.go:30:7: undefined: status
make[1]: *** [Makefile:46: buf-generate] Error 1
```

We found a PR which fixed this in past: https://github.com/grpc-ecosystem/grpc-gateway/pull/1757
Is something changed the way it should be tackled?

It is working as expected with release `v2.15.1`.

We use buf plugins https://buf.build/grpc-ecosystem/gateway and https://buf.build/grpc-ecosystem/openapiv2

## To Reproduce

1. Checkout https://github.com/fluxninja/aperture/commit/03861123ddc735e403898ace2c3c6d18a485a753
2. Run `make generate-api`

## Expected behavior

It should complete the make command successfully and generate the go packages from proto.

## Actual Behavior

It throws the errors as mentioned above.

## Your Environment

OS: Ubuntu

**Comment by mberwanger** [comment]
I am also seeing the same behavior.

**Comment by johanbrandhorst** [comment]
Hi, thanks for the bug report! Seems like we introduced a regression here, sorry about that. I'll have a look and see if there's an obvious culprit.

**Comment by johanbrandhorst** [comment]
Can't see anything obvious in https://github.com/grpc-ecosystem/grpc-gateway/compare/v2.15.1...v2.16.0 that would've caused this.

**Comment by amstee** [comment]
This issue has been introduced in buf https://buf.build/grpc-ecosystem/gateway v2.15.2, using 2.15.1 works just fine.

**Comment by pkwarren** [comment]
This patch has been reverted in v2.15.2 and v2.16.0 plugins - please give it another shot and let us know if you continue to encounter issues.

**Comment by johanbrandhorst** [comment]
I'll close this for now, please let me know if you're still seeing this issue, thanks!
