### ISSUE TITLE
docs: provide example of WithMarshalerOption use

### ISSUE THREAD

**Issue by warrenzhu25** [grpc-ecosystem/grpc-gateway#334]
As I know, grpc gateway support to put camel case filed in the request body, and it will automatically map to protoc underline split field. But if this, rest request and response are inconsistent.

**Comment by tmc** [comment]
@warrenzhu25 does the ability to customize marshalers not satisfy your use case?

**Comment by warrenzhu25** [comment]
I think customize marshalers can stisfy my use case. But I can't find documentation about how to use this feature. Could you show me how to use customize marshalers? Thanks a lot.

**Comment by tmc** [comment]
godoc.org has an integration with sourcegraph that allows you to look at other instances of its use.

https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption (hover to the right of the function name) ->
https://sourcegraph.com/github.com/grpc-ecosystem/grpc-gateway/-/blob/runtime/marshaler_registry.go#L77:33

That said this could be better documented or put into a functional example. I'm going to change this issue to reflect that.

**Comment by srikrsna** [comment]
`mux := runtime.NewServeMux(runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{OrigName:false}))`

This should do the trick

**Comment by achew22** [comment]
@srikrsna this would be a great thing to add in the `docs/` folder if you're interested

**Comment by srikrsna** [comment]
@achew22 Sure. Should I add it somewhere [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/_docs/customizingyourgateway.md)?

**Comment by drewwells** [comment]
this looks closeable to me

**Comment by johanbrandhorst** [comment]
Thanks for the reminder!
