### ISSUE TITLE
[protoc-gen-openapi] How the string type supports enum option

### ISSUE THREAD

**Issue by zhb127** [grpc-ecosystem/grpc-gateway#3341]
## 🚀 Feature

How the string type supports enum option：

```proto
  string sort_direction = 1 [
    (validate.rules).string = {
      in: [
        'asc',
        'desc'
      ]
    },
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      enum: [
        'asc',
        'desc'
      ]
    }
  ];
```

protoc-gen-openapiv2 actual output: 

```json
          {
            "name": "sort_direction",
            "in": "query",
            "required": false,
            "type": "string"
          }
```

expect output:

```json
          {
            "name": "sort_direction",
            "in": "query",
            "required": false,
            "type": "string",
            "enum": [
              "asc", 
              "desc"
            ]
          }
```

**Comment by johanbrandhorst** [comment]
This sounds like a bug, I would expect that to populate the enum field as you expect. I expect it would do the right thing if the field type was an enum, but we should be able to support this annotation too. Would you be willing in helping to fix this? You probably want to start looking here: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/internal/genopenapi/template.go#L321

**Comment by zhb127** [comment]
> Would you be willing in helping to fix this

Code is committed and unit tests are added. 

Please review.
