### ISSUE TITLE
Use of Glog is problematic for users of Klog

### ISSUE THREAD

**Issue by kn100** [grpc-ecosystem/grpc-gateway#3342]
## 🐛 Bug Report

In repos that use Klog, Glog causes problems. This is because Glog has an uncontrollable init() func that registers flags that may have been registered elsewhere in the codebase. For my use case, it is specifically `protoc-gen-grpc-gateway` and `protoc-gen-openapiv2` that pose the problem. I see in other areas of grpc-gateway `grpclog` has been swapped in for Glog ([for example](https://github.com/grpc-ecosystem/grpc-gateway/pull/3205)). It seems Glog is not actively maintained anymore.

Would the repository owners be amenable to a PR that swaps out Glog for grpclog for these two areas? If so, I'm happy to make one.

## To Reproduce

1. Have a project that depends on grpc-gateway `protoc-gen-grpc-gateway` and `protoc-gen-openapiv2`
1. Add klog as a dependency of that project, and initialise the flags.
1. Observe errors relating to flags being redeclared.

## Expected behavior

I would not expect an upstream logging dep to break our logging solution.

## Actual Behavior

```

panic: v1.test flag redefined: log_dir
--
  |  
  | goroutine 1 [running]:
  | flag.(*FlagSet).Var(0xc0000e0120, {0x3037f28, 0xc00057e3f0}, {0x2c43256, 0x7}, {0x2c8ce5e, 0x2f})
  | /usr/local/go/src/flag/flag.go:982 +0x3bb
  | flag.(*FlagSet).StringVar(...)
  | /usr/local/go/src/flag/flag.go:847
  | flag.(*FlagSet).String(0x4089600?, {0x2c43256, 0x7}, {0x0, 0x0}, {0x2c8ce5e, 0x2f})
  | /usr/local/go/src/flag/flag.go:860 +0xbe
  | flag.String(...)
  | /usr/local/go/src/flag/flag.go:867
  | github.com/golang/glog.init()
```

## Your Environment
* k8s.io/klog/v2 v2.90.1
* github.com/grpc-ecosystem/grpc-gateway/v2 v2.15.1

**Comment by johanbrandhorst** [comment]
Yep we should get rid of glog, I'd be happy to see that contribution if you have the time. Thanks for the detailed issue.

On a sidenote, I recommend versioning generators using `go install`, which might avoid this sort of issue (https://jbrandhorst.com/post/plugin-versioning/).
