### ISSUE TITLE
Does protoc-gen-openapiv2 support macbook M2?

### ISSUE THREAD

**Issue by HoaiDang-work** [grpc-ecosystem/grpc-gateway#3355]
## 🐛 Bug Report

I cannot find an instruction to install protoc-gen-openapiv2 on macbook M2. Is it supported? 

## To Reproduce

Calling protoc with openapiv2_out option

```
protoc --experimental_allow_proto3_optional -I. \
          -I$currentDir/proto-common/src/main/proto \
          -I$currentDir/proto-$folderName/src/main/proto \
          -I$currentDir/proto-$folderName/build/extracted-include-protos/main \
          --openapiv2_out swagger/ \
          --openapiv2_opt logtostderr=true,allow_delete_body=true \
          $currentDir/proto-$folderName/src/main/proto/$name.proto
```

## Expected behavior

Generate OpenAPI specs successfully

## Actual Behavior
Error out: <GOBINPATH>/protoc-gen-openapiv2: cannot execute binary file

## Your Environment

Macbook pro M2, OS Ventura 13.3

**Comment by johanbrandhorst** [comment]
Yep, the M2 is supported, you want https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v2.16.0/protoc-gen-openapiv2-v2.16.0-darwin-arm64. You may have downloaded the wrong version. You can also try building the generator directly:
```
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
```

**Comment by HoaiDang-work** [comment]
Thank you for the support, I made it work!
