### ISSUE TITLE
need some examples of using enum. 

### ISSUE THREAD

**Issue by nicezic** [grpc-ecosystem/grpc-gateway#3368]
## 📚 Documentation

(A clear and concise description of what the issue is.)

* in proto file.
```
service AuthService {
  rpc SendAuthCode(SendAuthCodeRequest) returns (SendAuthCodeResponse){
      option (google.api.http) = {
          post: "/v1/auth/sendAuthCode"
          body: "*"
      };
  };
}

enum VerificationType{
  SIGN_UP = 0;
  SIGN_IN = 1;
  PASSWORD_RESET = 2;
  WITHDRAWAL = 3;
  DANAL = 4;
}

enum VerificationMethod {
  EMAIL = 0;
  MOBILE = 1;
  OAUTH = 2;
  SMS = 3;
}

message SendAuthCodeRequest {
  string verificationAddress = 1;
  VerificationType verificationType = 2;
  VerificationMethod verificationMethod = 3;
}
```
And, I call with these params.
```
{
    "verificationAddress": "gAAAAABkeXFGrjbUfchcSnC6t1aro5_R9ghNXHHGCPtu0Xf8herYWl9x_jlyB2oQ4HLnL5UkaesTEXesbNVvMwnKu1LgTy5oD_fdwXvZI8ATYhDqaGTHKoQ=",
    "verificationMethod": 0, <-- int
    "verificationType": "SIGN_UP" <-- string
}
```

However, my grpc node.js(ts) server don't get enum types.
```
async sendAuthCode( sendAuthCodeRequest: authPackage.SendAuthCodeRequest )
... 
sendAuthCodeRequest.verificationAddress <- ok.
sendAuthCodeRequest.verificationType <- undefined.
VerificationMethod.verificationMethod  <- undefined.
```

Can you help me?
I need some examples of using enum.

**Comment by nicezic** [comment]
I found the solution. It was reeeeeeeeeeaally hard to find.
I had to go around other grpc gateway proeject using yaml. 
I tried the enum option to my project...
so... hard to find. 

```
GO_OPT="--go_opt=paths=source_relative"
GO_GRPC_OPT="--go-grpc_opt=paths=source_relative"
GO_GATEWAY_OPT="--grpc-gateway_opt=paths=source_relative"

protoc \
	--proto_path=./libs/shared/src/lib/proto \
	--go_out=apps/gateway/packages/authPackage $GO_OPT \
	--go-grpc_out=apps/gateway/packages/authPackage $GO_GRPC_OPT \
	--grpc-gateway_out=apps/gateway/packages/authPackage $GO_GATEWAY_OPT \
	./libs/shared/src/lib/proto/auth.interface.proto
```


```
GO_OPT="--go_opt=paths=source_relative"
GO_GRPC_OPT="--go-grpc_opt=paths=source_relative"
GO_GATEWAY_OPT="--grpc-gateway_opt=paths=source_relative"
GO_OPENAPIV2_OPT="--openapiv2_opt=enums_as_ints=true --openapiv2_opt=omit_enum_default_value=true

protoc \
	--proto_path=./libs/shared/src/lib/proto \
	--go_out=apps/gateway/packages/authPackage $GO_OPT \
	--go-grpc_out=apps/gateway/packages/authPackage $GO_GRPC_OPT \
	--grpc-gateway_out=apps/gateway/packages/authPackage $GO_GATEWAY_OPT \
	--openapiv2_out=apps/gateway/packages/authPackage $GO_OPENAPIV2_OPT \
	./libs/shared/src/lib/proto/auth.interface.proto
```

**Comment by nicezic** [comment]
I cannot still pass the enum param to grpc server. How can I pass?

**Comment by nicezic** [comment]
```
{
    "verificationAddress": "gAAAAABkeXFGrjbUfchcSnC6t1aro5_R9ghNXHHGCPtu0Xf8herYWl9x_jlyB2oQ4HLnL5UkaesTEXesbNVvMwnKu1LgTy5oD_fdwXvZI8ATYhDqaGTHKoQ=",
    "verificationMethod":  ,
    "verificationType": "SIGN_UP"
}
```
My grpc gateway detect wrong enum. However, If i set current enum value (int or string), The Server cannot get enum types.
```
{
    "code": 3,
    "message": "proto: (line 3:27): invalid value for enum type: \"0\"",
    "details": []
}
```

**Comment by nicezic** [comment]
PS: Postman's grpc call  to the server is okay.  I think grpc gaway's bug about the enum.

**Comment by johanbrandhorst** [comment]
Hm, something that strikes me as strange (though I'm not sure this is the problem) is the formatting of the field names in your protobuf file. Protobuf uses snake case by default, could you try renaming your fields `verification_address` etc and see if that changes the behavior?

**Comment by nicezic** [comment]
```
protoc --proto_path=./libs/shared/src/lib/proto --go_out=apps/gateway/packages/authPackage --go_opt=paths=source_relative --go-grpc_out=apps/gateway/packages/authPackage --go-grpc_opt=paths=source_relative --grpc-gateway_out=apps/gateway/packages/authPackage --grpc-gateway_opt=paths=source_relative --grpc-gateway_opt=enums_as_ints=true ./libs/shared/src/lib/proto/auth.interface.proto
protoc-gen-grpc-gateway: no such flag -enums_as_ints
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.
```

How can I enable enum_as_int for grpc gateway?

**Comment by nicezic** [comment]
@johanbrandhorst Hi,
I figured out what the problem is.
My nodejs(ts) use grpc from jest package.
The jest package can handle enum as int but not string or grpc enum object(??).

A Postman's grpc call sends enum as int, and that why postman's grpc call to the server works out.
In the other hand, a grpc gateway sends enum as grpc_enum_object(?) to the server, and it doesn't not work out for the node server.

I made a golang grpc server for test, and it work out for the gateway. it processes the grpc_enum_object(?).
```
$ which  tsproto
/home/nicezic/src/waybit-workspace/node_modules/.bin/tsproto
$ tsproto version
1.0.20
```
in package.json
```
tsproto 1.0.20
    "nestjs-google-pubsub-microservice": "^4.3.0",
    "nestjs-proto-gen-ts": "1.0.20",
```

**Comment by nicezic** [comment]
I think there's an workaround for this grpc-gateway, using https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#enums-as-integers to avoid the bug of nestjs. 
```
protoc --proto_path=./libs/shared/src/lib/proto --go_out=apps/gateway/packages/authPackage --go_opt=paths=source_relative --go-grpc_out=apps/gateway/packages/authPackage --go-grpc_opt=paths=source_relative --grpc-gateway_out=apps/gateway/packages/authPackage --grpc-gateway_opt=paths=source_relative --grpc-gateway_opt=enums_as_ints=true ./libs/shared/src/lib/proto/auth.interface.proto
protoc-gen-grpc-gateway: no such flag -enums_as_ints
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.
```

How can I enable enum_as_int for grpc gateway?

**Comment by johanbrandhorst** [comment]
The `enums_as_ints` option is for the openapiv2 generator, the gateway already accepts both the string and integer value when parsing.

**Comment by nicezic** [comment]
@johanbrandhorst Yes, gateway has no probelm of parsing. 
when the gateway send to a grcp server, somehow my nestjs's grpc server cannot process enum types( undefined). 

The gateway can send enum value as int to grcp server? 
Is `enums_as_ints ` supoosed to work like that?

**Comment by johanbrandhorst** [comment]
Hm, no, that sounds like a bug in nestjs's gRPC server, there is only one format for enums in the protobuf wire format and it is not configurable. I'm going to close this issue, sorry that I can't be of more help.
