### ISSUE TITLE
Support passing key-value pairs on the command line and using them in comment Go templates.

### ISSUE THREAD

**Issue by jgiles** [grpc-ecosystem/grpc-gateway#3388]
## 🚀 Feature

protoc-gen-openapiv2 supports using Go templates to customize comment strings that are used in OpenAPI output: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#using-go-templates-in-proto-file-comments

It would be very useful to support setting a parameter on the CLI like `--openapiv2_opt go_template_args=my_key=my_value` and then in the Go templates access that value like `{{  .Args.my_key }}`. For example, to we could interpolate different external documentation URLs when rendering documentation for different environments.

**Comment by johanbrandhorst** [comment]
This doesn't sound like an unreasonable request to me. Use of the new argument would obviously also require `use_go_templates` to be true, and it should be possible to provide it multiple times. Would you be interested in adding this support?

**Comment by suriya-ganesh** [comment]
\assign

**Comment by johanbrandhorst** [comment]
Hi Suriya, if you're interested in working on this, feel free to just submit a PR.
