### ISSUE TITLE
Add SOAP proxy

### ISSUE THREAD

**Issue by tgulacsi** [grpc-ecosystem/grpc-gateway#339]
Hi,

I have a SOAP proxy with WSDL generator under github.com/UNO-SOFT/soap-proxy.
Can you give some guidance how to add that to grpc-gateway?

**Comment by tmc** [comment]
@tgulacsi thanks for your comment and for publishing your work there. It's not immediately clear to me how/if a SOAP bridge is appropriate in this projec. I imagine with some hinting information a custom marshaller could get you most of the way there. Please propose enhancements to this project if there is something limiting your ability to implement this.

**Comment by tgulacsi** [comment]
I do have a working JSON and SOAP proxy for gRPC.
I've moved with json to grpc-gateway, and wanted to move with the SOAP proxy, too.

I can generate the WSDL and have the Marshal/Unmarshal code for the SOAP HTTP handler.
I wanted to get some suggestions how to integrate it into grpc-gateway.

A SOAP bridge is just as appropriate as a JSON bridge - although I do hate SOAP, I have to support it.
But if this is too much of a maintenance hurdle and nobody is interested in SOAP, I'll keep that generator and handler separate.

**Comment by gedw99** [comment]
@tmc i would def use this !!!!
@tgulacsi this sounds really useful. I hate SOAP too but have to use it ...

**Comment by achew22** [comment]
@tgulacsi what an interesting project! I'd never even thought of using protos to define WSDLs. Neat!

Can you help me understand why you want this integrated into gRPC gateway directly? It doesn't appear to have any overlapping code and I think could be installed in parallel with a gRPC gateway server. What would the advantage of commingling the repositories over leaving them separate and composable?

**Comment by tgulacsi** [comment]
@achew22 you're right, grpc-gateway and soap-proxy has no common code yet, but that can change easily: beside the wsdl generating code, the HTTP server that receives the json/soap, decodes it, calls the gRPC endpoint, encodes the response and sends it back has a lot in common. 

And grpc-gateway can become a nice general gateway to gRPC - in this form this is just a json proxy, tbh.
I have code for XML-RPC, too :)

I do understand though if we keep grpc-gateway almost as-is, and provide these additional encoders/decoders as some sort of plugins/additions.

**Comment by gedw99** [comment]
@tgulacsi 
i was wondring if you would be ok with putting a working example for the WSDL and xml-rpc in your repo ? From the looks of it its expecting a PB thats not in the source.

I am playing around with different gateways just like your code does. So having the REST with WSDL and xml.rpc is really useful. 

On other thing i am looking at trying out with code gen, which your currently doing from the PB, is to map the PB types to Minio for durable storage and also incorporating NATS with it.

**Comment by achew22** [comment]
Looks like you've created this already, cool! I look forward to seeing your project grow

https://github.com/UNO-SOFT/soap-proxy
