### ISSUE TITLE
Swagger: JSON definitions aren't SnakeCase

### ISSUE THREAD

**Issue by yanjinbin** [grpc-ecosystem/grpc-gateway#3394]
## 🚀 Feature

need swagger parameters support snake case style , people love snake case ,
but now  switch to camel case 
need an option to support it

**Comment by johanbrandhorst** [comment]
I think you probably want `json_names_for_fields=false` as an option. See https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/main.go for a full list of options.
