### ISSUE TITLE
Format option of array type is located in the wrong place

### ISSUE THREAD

**Issue by far4599** [grpc-ecosystem/grpc-gateway#3403]
## 🐛 Bug Report

This bug relates to `protoc-gen-openapiv2`. 

It looks like `format` option with array type is placed in the wrong place when compiled to json. Now `format` is placed at the root of the property object. But according to the [spec](https://swagger.io/specification/v2/#items-object): `items` option describes the type of items in the array. So `format` shall be a part of `items` object as the other item type descriptors.

The problem is located here: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/internal/genopenapi/template.go#L2751C5-L2751C5
where all the type properties (except `format`) are set to the `Items` object.  

## To Reproduce

```proto
repeated string uuids = 1 [
  (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    type: ARRAY,
    format: "uuid",
    min_items: 1,
    max_items: 10000,
    unique_items: true,
  }
];
```

complied json schema:
```json
"properties": {
  "uuids": {
    "type": "array",
    "format": "uuid", <- now is here
    "items": {
      "type": "string",
      "uniqueItems": true
    },
    "maxItems": 10000,
    "minItems": 1
  }
},
```

## Expected behavior

```json
"properties": {
  "uuids": {
    "type": "array",
    "items": {
      "type": "string",
      "format": "uuid", <- shall be here
      "uniqueItems": true
    },
    "maxItems": 10000,
    "minItems": 1
  }
},
```

**Comment by far4599** [comment]
Just to prove that the current location is wrong here is a sample yaml to copy-paste to https://editor.swagger.io/

When `items.format` the UI generates UUID for an example of request properly

```yaml
openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
paths:
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        tags:
          type: array
          items: 
            type: string
            format: uuid
```

**Comment by adambabik** [comment]
Hi @far4599! Thanks for reporting the issue and locating the source. Would you be willing to send a PR fixing it along with a test case? Happy to help with any questions.
