### ISSUE TITLE
 *HelloReply does not implement protoreflect.ProtoMessage (missing method ProtoReflect)

### ISSUE THREAD

**Issue by Shibbaz** [grpc-ecosystem/grpc-gateway#3408]
Hi, I'm trying to go past tutorial https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/
Generating stubs using buf
All code is here
https://github.com/Shibbaz/Golang-learn/tree/main/gateway

`
func request_Users_SayHello_0(ctx context.Context, marshaler runtime.Marshaler, client UsersClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.SayHello(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_Users_SayHello_0(ctx context.Context, marshaler runtime.Marshaler, server UsersServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.SayHello(ctx, &protoReq)
	return msg, metadata, err

}`

The problem lies in the return, currently I get  *HelloReply does not implement protoreflect.ProtoMessage (missing method ProtoReflect)

I've read that the problem is with the versions, yet I've not resolved it yet.

Any idea what next step is?

**Comment by adambabik** [comment]
@Shibbaz Try `go mod tidy` and `buf generate` after that. Check out https://github.com/bufbuild/buf-examples for more examples. It's not a problem with grpc-gateway.

**Comment by Shibbaz** [comment]
@adambabik It's not the solution.

**Comment by johanbrandhorst** [comment]
You're using the wrong version of the protobuf generator. Please install the latest version of `protoc-gen-go` and try again.
