### ISSUE TITLE
docs: show example of tracing over http->grpc boundary

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#348]
We should show how to propagate an incoming traced http request over the grpc boundary.

Further, perhaps this just be supported out of the box.

**Comment by maxkondr** [comment]
Is here any news? Any examples,docs will be appreciated

**Comment by uschen** [comment]
I believe the stackdriver trace works with grpc-gateway.

**Comment by maxkondr** [comment]
@uschen  If I understood correctly, stackdriver works in google cloud and AWS only. I want to use tracing in own solution.

**Comment by tmc** [comment]
@maxkondr you can use stackdriver trace if your workloads aren't in google's cloud.

**Comment by smthpickboy** [comment]
Any examples or docs for supporting opentracing? Thanks!

**Comment by maxkondr** [comment]
there is a ready for use solution from github.com/opentracing-contrib/go-stdlib/nethttp lib:

```
import "github.com/opentracing-contrib/go-stdlib/nethttp"

...
return http.ListenAndServe(fmt.Sprintf(":%d", myPort),
		nethttp.Middleware(
			opentracing.GlobalTracer(),
			mux,
			nethttp.MWComponentName(os.Getenv("MY_POD_NAME")),
		),
	)
```

**Comment by ZachEddy** [comment]
Not sure if this is the right place to ask questions, but I didn't know where else to post.

Does the gRPC Gateway client need to be initiated with a tracing interceptor? I struggled to get @theRealWardo's example to work until I added a client-side interceptor. If so, I think it would be helpful to bring this up in the documentation (happy to open a PR for this).

There's some relevant information [here](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/tracing/opentracing#opentracing-interceptors), but I wanted to double check.

**Comment by johanbrandhorst** [comment]
Hi @ZachEddy, we'd happily welcome any documentation improvements you could contribute. I haven't got any experience with this myself so your knowledge would be very good to capture.

**Comment by ZachEddy** [comment]
Sounds good! Some additional documentation would be useful, but I like the original suggestion to add tracing support out of the box.

Maybe this can be accomplished by adding another [`ServeMuxOption`](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/mux.go#L32) to the `runtime` package?

Something like `runtime.WithTracer(tracer opentracing.Tracer)` perhaps? Not sure really sure, but I'll tinker around with it.

**Comment by kristiandrucker** [comment]
Hi. @johanbrandhorst asked me to write how I have forwarded span from gateway -> grpc server. Well after a few hours of debugging this is my final code. For tracing in gateway I have used `nethttp.Middleware()` and for actually sending the span via metadata I wrote my own function that returns `metadata.MD` map.

Implementation of nethttp:
``` go
func NewTracedRuntimeMuxServer(tracer opentracing.Tracer, mux *runtime.ServeMux) *http.Server {
	return &http.Server{
		Handler: nethttp.Middleware(
			tracer,
			mux,
			nethttp.OperationNameFunc(func(r *http.Request) string {
				return fmt.Sprintf("HTTP-gRPC %s %s", r.Method, r.URL.String())
			}),
		),
	}
}
```

Custom metadata from span function:
``` go
func MetadataFromSpan(span opentracing.Span) metadata.MD {
	ctx := span.Context()
	carrier := make(map[string]string)

	span.Tracer().Inject(
		ctx,
		opentracing.TextMap,
		opentracing.TextMapCarrier(carrier),
	)

	return metadata.New(carrier)
}
```

Implementation of the custom metadata from span function:
``` go
mux := runtime.NewServeMux(
	runtime.WithMetadata(
		func(ctx context.Context, r *http.Request) metadata.MD {
			span := opentracing.SpanFromContext(ctx)
			tracing.MetadataFromSpan(span)

			return tracing.MetadataFromSpan(span)
		},
	),
)
```

Getting the values in gRPC is done via this package `github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing`. There I have created a UnaryInterceptor for grpc, but you can also create a StreamInterceptor and pass the UnaryServerInterceptor or the StreamServerInterceptor along with a tracer to create a trace for every call to the gRPC service and also it will enable you to create the span from context.
