### ISSUE TITLE
consider a temporary flag to control output location of "context" package.

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#349]
Refs #343

**Comment by simonpasquier** [comment]
Trying to get away from `golang.org/x/net/context` for my own projects, I wonder if it wouldn't be possible for grpc-gateway to switch using `context` from the standard library now. Specifically wouldn't it be ok to change this [line](https://github.com/grpc-ecosystem/grpc-gateway/blob/9a7c952d3c7e6c0239ddb5d1d351e0fdb6c3c8d3/protoc-gen-grpc-gateway/gengateway/generator.go#L47) to `"context"`?

**Comment by johanbrandhorst** [comment]
I'd say yes. We should have the same support guarantees as the standard library which means current release - 2, which still leave us at 1.9. Context was added in 1.7. Would you be interested in contributing a fix for this?

**Comment by simonpasquier** [comment]
@johanbrandhorst sure, I'll send something soon...
