### ISSUE TITLE
import protoc-gen-grpc-gateway is a program, not an importable package

### ISSUE THREAD

**Issue by labasubagia** [grpc-ecosystem/grpc-gateway#3515]
## 🐛 Bug Report
there is an error, when installation
`import "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" is a program, not an importable package`

## To Reproduce
1. add tools package
```go
// +build tools

package tools

import (
    _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"
    _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2"
    _ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
    _ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
```
1. run `go mod tidy`

## Expected behavior
No Error

## Actual Behavior
Error
![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/31754766/dd54d132-9a01-424c-a202-37f15991d99a)

## Environment
go 1.21.0
linux mint 21.1

**Comment by rishi-diwaker1** [comment]
in case the program were a main.go file? with package main
Can it be ignored then?
