### ISSUE TITLE
swagger: Unclear comments' parser behaviour

### ISSUE THREAD

**Issue by utrack** [grpc-ecosystem/grpc-gateway#352]
```
// SumRequest is a request for Summator service.
message SumRequest {
  // A is the number we're adding to. Can't be zero for the sake of example.
  int64 a = 1;
  // B is the number we're adding.
  int64 b = 2;
}
```

This proto message is generated to corresponding doc:
```
...
      "properties": {
        "a": {
          "type": "string",
          "format": "int64",
          "description": "a is the number we're adding to. can't be zero for the sake of example."
...
```

But if we'll remove the trailing dot in A's comment then description becomes title:
```
      "properties": {
        "a": {
          "type": "string",
          "format": "int64",
          "title": "A is the number we're adding to. Can't be zero for the sake of example"
```

and this title is invisible in the model's outline (see the screenshot).

It is intended judging by the code, but this behaviour clearly breaks Swagger UI.

![scrot-20170406_103406](https://cloud.githubusercontent.com/assets/3862920/24742849/a5306404-1ab4-11e7-9a39-7362cd1a95c6.jpg)

**Comment by achew22** [comment]
Huh, this is strange. Especially strange given that it looks like we have [code to handle it](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L72). I don't have an answer on what's going on here, but want to document what I have looked at

Doesn't look like we are setting the title at all.

```
~/Projects/grpc-gateway (master)$ grep "Title =" . -rn
./protoc-gen-swagger/genswagger/template.go:638:                usingTitle = true
```

Could it be that we are copying the struct from proto into the swagger types somewhere? I didn't think we did that and also It seems like the interfaces would be incompatible and disallow that but that's the best theory I have off the top of my head.

**Comment by utrack** [comment]
@achew22 We've got the (weird) code that decides if comment is description or title [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L648).
It sets Title and Description through reflection (prolly I could refactor it?)

**Comment by achew22** [comment]
The parser has been updated a lot since this bug was filed and I think it's likely fixed if you wanna take another look at it.
