### ISSUE TITLE
Empty value omitted

### ISSUE THREAD

**Issue by sagikazarmark** [grpc-ecosystem/grpc-gateway#355]
Given the following message:

```
message NameCheckResponse {
    Result result = 1;
}
```

Result is an enumeration. Whenever the 0 value is returned, grpc-gateway returns an empty JSON object, instead of `{"result": 0}`.

Is this behaviour intended?

**Comment by tmc** [comment]
This is currently as expected, see discussion on https://github.com/grpc-ecosystem/grpc-gateway/pull/242
