### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#357]
Changes considered:
- [x] by default use request.Context https://github.com/grpc-ecosystem/grpc-gateway/issues/313
- [x] reconsider metadata+header prefixes https://github.com/grpc-ecosystem/grpc-gateway/issues/311 / https://github.com/grpc-ecosystem/grpc-gateway/pull/336
- [x] consider emitting empty values by default https://github.com/grpc-ecosystem/grpc-gateway/pull/242

**Comment by AlekSi** [comment]
Please consider tagging a new release from current `master` and move other items to 1.4. [There are](https://github.com/grpc-ecosystem/grpc-gateway/compare/v1.2.2...master) some good changes including `allow_delete_body`.

**Comment by tmc** [comment]
@AlekSi thanks for the feedback. We are probably due to cut a new release.

**Comment by AlekSi** [comment]
Bump.

**Comment by AlekSi** [comment]
@tmc @achew22 @tamalsaha 1.3.0 was released. Should this ticket be closed or updated to 1.4.0?

**Comment by achew22** [comment]
I did all those things (I think). It's a bug if they aren't working. Please file another bug if those aren't working in 1.3.0
