### ISSUE TITLE
swagger uses camel, which should have been the name defined in proto after set UseProtoNames: true

### ISSUE THREAD

**Issue by tanxiao1990** [grpc-ecosystem/grpc-gateway#3594]
protoc-gen-go v1.31.0
protoc-gen-go-grpc 1.3.0
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

After setting the variables as described in this article, 
https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/#we-now-use-the-camelcase-json-names-by-default
the swagger page still displays the fields in the form of a camel, instead of the proto field definition

Here are my relevant settings
![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/38320121/c2e56650-ed73-45ae-949e-de10d686a6c9)

protoc command:
	protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative \
	--go-grpc_out=pb --go-grpc_opt=paths=source_relative \
	--grpc-gateway_out=pb --grpc-gateway_opt=paths=source_relative \
	--openapiv2_out=doc/swagger --openapiv2_opt=allow_merge=true,merge_file_name=agent_manager \
	--openapiv2_out=json_names_for_fields=false:./doc/swagger \
	proto/*.proto

the swagger:
![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/38320121/aee79376-bc70-4ad1-a95c-66dff968aa64)

my proto file:
![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/38320121/6737ab1c-4428-470c-bcd4-75663d4a36be)

thank you !

**Comment by johanbrandhorst** [comment]
Should this
```
 --openapiv2_out=json_names_for_fields=false:./doc/swagger 
```

Be
```
 --openapiv2_opt=json_names_for_fields=false:./doc/swagger 
```
?

**Comment by tanxiao1990** [comment]
> 

Thanks for @johanbrandhorst , but actually protoc doesn't exist for this command line parameter （--openapiv2_opt）, and if you change it to opt you'll get an error straight away!  

`2023/09/13 09:26:06 FATAL: Error parsing flags: cannot set flag json_names_for_fields=false:./doc/swagger: parse error
--openapiv2_out: protoc-gen-openapiv2: Plugin failed with status code 1.`

**Comment by tanxiao1990** [comment]
> Yeah the problem is the rest of your invocation, not the option. You need
> 
> ```
> protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative
> --go-grpc_out=pb --go-grpc_opt=paths=source_relative
> --grpc-gateway_out=pb --grpc-gateway_opt=paths=source_relative
> --openapiv2_out=doc/swagger 
> --openapiv2_opt=allow_merge=true,merge_file_name=agent_manager,json_names_for_fields=false
> proto/*.proto
> ```
> 
> This should fix it.

it works. Thank you.
