### ISSUE TITLE
v2/protoc-gen-grpc-gateway is missing

### ISSUE THREAD

**Issue by lynnprent** [grpc-ecosystem/grpc-gateway#3606]
## 🐛 Bug Report

/v2/protoc-gen-grpc-gateway appears to have moved.

## To Reproduce

(Write your steps here:)

1. `go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest`

## Expected behavior

What used to happen was that it would install the latest version

## Actual Behavior

```
$ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest: module github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway: Get "https://proxy.golang.org/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway/@v/list": dial tcp 142.251.221.81:443: i/o timeout
```
```
$ wget https://proxy.golang.org/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway/@v/list
--2023-09-18 10:37:34--  https://proxy.golang.org/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway/@v/list
Resolving proxy.golang.org (proxy.golang.org)... 142.251.221.81, 2404:6800:4006:809::2011
Connecting to proxy.golang.org (proxy.golang.org)|142.251.221.81|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-09-18 10:37:35 ERROR 404: Not Found.
```

## Your Environment

ubuntu 23.04

**Comment by lynnprent** [comment]
Also happens in ubuntu 22.04

**Comment by johanbrandhorst** [comment]
I was just able to run this successfully locally. The path hasn't changed recently (since the v2 release). The error you're seeing is likely a result of local networking restrictions. Your second command is incorrect, I think you want 
```
$ wget https://proxy.golang.org/github.com/grpc-ecosystem/grpc-gateway/v2/@v/list
```

`protoc-gen-grpc-gateway` is not its own module.
