### ISSUE TITLE
 metadata.NewOutgoingContext is undefined

### ISSUE THREAD

**Issue by aaronjwood** [grpc-ecosystem/grpc-gateway#364]
This breaks programs that link against `grpc-gateway` directly or indirectly (such as https://github.com/coreos/etcd/issues/7763)

**Comment by TamalSaha** [comment]
@aaronjwood , may be use a released version of grpc-gateway. The real fix is, you need the next release of grpc go. https://github.com/grpc/grpc-go/issues/1187

**Comment by aaronjwood** [comment]
Thanks, we're working on a vendoring strategy so we'll be sure to catch this. Glad to hear it's fixed in the next release.

**Comment by tmc** [comment]
@aaronjwood for clarity, grpc-go introduced an api deprecation and we adopted this in 1.2.2 -- use 1.2.0 if you need to use an older version of grpc-go.

**Comment by tmc** [comment]
For posterity's sake (and googlebot), this sort of issue would likely render as:

```
# github.com/your/sweet/project/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime
vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go:97: undefined: metadata.NewOutgoingContext
```

Somewhat relatedly, these sorts of errors likely mean you need to re-generate your .pb.gw.go files with a newer grpc-gateway:
```
protos/servicea/rpc.pb.gw.go:614: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
protos/servicea/rpc.pb.gw.go:616: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
```

**Comment by tmc** [comment]
@aaronjwood perhaps a valuable documentation addition would be a small vendoring guide. Would love to see some shared tips!

**Comment by aaronjwood** [comment]
Thanks for the info @tmc! Let me sort out our internal issues at work from this and then I can come back to some sort of vendoring doc :)

**Comment by tmc** [comment]
@aaronjwood that'd be awesome!

**Comment by tmc** [comment]
I opened https://github.com/grpc-ecosystem/grpc-gateway/issues/365 to track.
