### ISSUE TITLE
Swagger: incorrect documentation for proto wrapper types

### ISSUE THREAD

**Issue by charles-crain** [grpc-ecosystem/grpc-gateway#367]
If you have a response object that looks like this:

```
message FooResponse {
  google.protobuf.DoubleValue some_value = 1;
}
```

Then the generated Swagger says the response looks like:

```
{
  "some_value" : {
    "value" : 0
  }
}
```

When in fact the JSON returned from calling the method looks like:

```
{
  "some_value" : 0
}
```

**Comment by tmc** [comment]
@charles-crain thank you for your issue report. That's an unfortunate divergence there. One solution might be to add protobuf WKT support in the swagger generation. Perhaps we can be smarter.
