### ISSUE TITLE
Should metadata annotator include the headers from incoming matcher?

### ISSUE THREAD

**Issue by TamalSaha** [grpc-ecosystem/grpc-gateway#368]
@tmc https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/context.go#L97

Currently metadataAnnotator is passed the original `ctx` which does not include the metadata / headers. We can consider passing a context with the headers to metadata annotator. This will allow custom logic inside metadata annotator that depends on the http headers.

cc: @ilius

**Comment by TamalSaha** [comment]
To be clear, any custom logic in metadata annotator can be also performed on the grpc server side after passing the full header. An example can be adding  a new header `x-cookie-key1` by parsing the `Cookie` header.

**Comment by TamalSaha** [comment]
On second thought, this is not needed. Custom logic can read the original `req`.

**Comment by ilius** [comment]
I'm not sure it's related to this, but I think we should be able to add one specific cookie (or all of them) to the incoming metadata.MD of context, so that we don't have to iterate over cookies, every time.
Specially inside the grpc ecosystem (where there is no http1/REST) in micro-service architecture, we frequently set and get a specific metadata key, and we don't want to iterate over `md["cookie"]` every time. Even the term `cookie` should not be used when you are inside grpc ecosystem. Cookie is for HTTP1 / REST, not GRPC.

**Comment by TamalSaha** [comment]
@ilius , `Cookie` is a valid concept in both Http and [Http/2](http://httpwg.org/specs/rfc7540.html#rfc.section.4.3) (including gRPC). IMO, your server should work whether the cookie comes via Http or Http/2. If you want to parse cookie on the gRPC side, this is what I do:
 - Create a http.Request from ctx. e.g. https://github.com/grpc/grpc-go/issues/1174#issuecomment-292923366
 - Then use req.Cookie("") for parsing

But if you want to only support cookie at gateway layer, this is what you can do:
```
runtime.NewServeMux(runtime.WithMetadata(func(ctx context.Context, req *http.Request) (metdata.MD) {
	return metdata.Pairs("x-cookie-k1", req.Cookie("k1"))
}));
```

**Comment by ilius** [comment]
We don't expose grpc to the outside world (only for inter-service communication), we only expose REST to outside. So I will the second approach.
Thanks

**Comment by ilius** [comment]
The second approach does not seem to be working for us.

	s.grpcMux = runtime.NewServeMux(runtime.WithMetadata(func(ctx context.Context, req *http.Request) metadata.MD {
		tokenCookie, _ := req.Cookie(auth.AuthTokenCookieKey)
		if tokenCookie == nil {
			return nil // metadata.Pairs()
		}
		fmt.Printf("WithMetadata: tokenCookie: %#v\n", tokenCookie) // correctly set
		return metadata.Pairs(auth.AuthTokenContextKey, tokenCookie.Raw)
	}))


But I get this metadata:

	md=metadata.MD{"token":[]string{""}, "grpcgateway-cookie":[]string{"token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTI2MDQwMTQsInRlbmFudCI6Im5ldy1hdXRoLXRlc3QiLCJ1c2VyX2lkIjoiNjAxMTI3ODAzNzkyIn0.sIlYco9EPdl-6nFOe7CUiDeaeLK0Gt1zV3I53NvX-ss0dgGXdAS8i1z75jkJ1jRRivviwInzDKtyG7QZrlIRZyzh7r6jCXlCHXEmMz6MUBolmjIYvmtZ1ph96uJUeor58Of4xEvnaI0sskTR2fwXvUKwbTjmo3sgp17N3F1kcy__jWVvzdJDFWr430TFzu1g6Abl8IHRGwwOTC-gR3AWrZTi6tyCSNXHP5FF-gkAOzV0_TLbZeN5l4Uj2G6PyUGU9JzElt7NEjkTQVGm5crnsG7sh78irSnXPpFmKq8cS88L41OonEQqIQqhktqQ-JKNJrrhG1lftZJMs_6to3Ob_A"}, ":authority":[]string{"api.dev.sora.ai"}, "grpcgateway-user-agent":[]string{"Go-http-client/2.0"}, "x-forwarded-host":[]string{"api.dev.sora.ai:15000"}, "x-forwarded-for":[]string{"127.0.0.1"}}


It give empty `"token":[]string{""}`

**Comment by ilius** [comment]
I also tried with both ServeMuxOptions to `NewServeMux`, `WithMetadata` only add an empty context key.

**Comment by tmc** [comment]
@ilius are you seeing that behavior if you supply a literal value instead of "tokenCookie.Raw" there in your example?

**Comment by TamalSaha** [comment]
@ilius , you should be using `Cookie.String()`, not `Cookie.Raw`. From https://golang.org/src/net/http/cookie.go, you can see that Raw is set for SetCookie header, but there is no SetCookie header in http request.

**Comment by ilius** [comment]
My apology.
I should have used `cookie.Value`
Thanks

**Comment by TamalSaha** [comment]
Glad it worked for you!
