### ISSUE TITLE
Wrong mapping of REST endpoint to rpc handler.

### ISSUE THREAD

**Issue by kamesh-09** [grpc-ecosystem/grpc-gateway#3687]
## 🐛 Bug Report

I am facing similar issue as mentioned here - 
https://github.com/grpc-ecosystem/grpc-gateway/issues/2254

If there are 2 rest endpoints as given below: suppose both of them are POST:

1. api/user/{userID}/details
2. api/user/{userID}/{permission}

then making a rest call to 1st API is getting mapped to 2nd RPC handler which results in wrong response.
This somewhere happens in runtime/mux.go and runtime/pattern.go file.
It matches the `details` as permission variable.

I am facing this while migrating away from grpc-gateway v1 to v2.
Mentioning specific version of v2 - v2.11.3

Ideally the path should be matched first with fixed path params.

I see that this change was introduced to - Implement last-match-wins behaviour in mux, but that default behaviour break this case.

**Comment by johanbrandhorst** [comment]
Yes this is an intentionally breaking change from v1 to v2. The v1 behavior was not correctly following the http.proto spec. The [original issue](https://github.com/grpc-ecosystem/grpc-gateway/issues/224) has more information, but this is working as intended.
