### ISSUE TITLE
Definitions containing URLs with trailing slashes won't compile

### ISSUE THREAD

**Issue by zweizeichen** [grpc-ecosystem/grpc-gateway#370]
Hi,
Thank you for maintaining this project! Just a quick question. I just tried compiling my definition containing a URL containing a trailing slash:

```protobuf
get: "/v1/my/endpoint/param/{param_value}/"
```

When I try to compile that definition, I get this error:

> --grpc-gateway_out: segment neither wildcards, literal or variable: expected "{" but got "\x00": /v1/my/endpoint/param/{param_value}/

See: [parse.go:150](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c0b378a74040eeb5ef415c5289258a193be0e94/protoc-gen-grpc-gateway/httprule/parse.go#L150)
Seems like it does not expect the segment started by the trailing slash to end instantly. Without the trailing slash everything just works. Is this a deliberate design choice or simply a bug? If it is a design choice, providing a more helpful error message might be a good idea. If it's a bug, it should be fairly easy to fix.

**Comment by TamalSaha** [comment]
@zweizeichen , gateway follows Google's http.proto spec https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L214

This spec does not allow trailing slash.

**Comment by zweizeichen** [comment]
Thanks! That answers my question.
