### ISSUE TITLE
NOOP file generation for protoc-gen-grpc-gateway

### ISSUE THREAD

**Issue by ghstahl** [grpc-ecosystem/grpc-gateway#3712]
## Generate a gw file even though there are no bindings.  

Specifically in my case an empty ```Register{{servicename}}Server``` func.

```go
func   RegisterGreeterHandlerServer(ctx context.Context, mux *runtime.ServeMux, server GreeterServer) error {
  return nil
}
func RegisterGreeterHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
  return nil
}
etc...

```
really any Register* funcs.  

I have my own generator that builds out helpers to register these services in a DI and I rely on that ```Register{{servicename}}Handler``` being there.  I was looking through your gen code to see if I could duplicate your logic to determine if a binding is there.
```
var methodWithBindingsSeen bool
```
If there is an easy way to check for these same http binding with just using google stuff that would work for me.  There is just too much code to bring over from this project just to determine if your generator produced anything. 

The ask is;
produce something even if all the funcs are empty.

Maybe an option to produce noop output.   

**Side Question**: Is there any way that I could tag my proto service to say ```hint=blah```, where my hint is to tell my generator that there is bindings there.  A cheat, but anything to just get a true/false.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. I'm a little confused, are you saying that you'd like an option for the generator to generate a `foo.pb.go` file with all empty `RegisterFooHandlerServer` etc functions? If so, it sounds like you want to write your own protobuf generator, which you can easily do to generate a file like this. The official Go protobuf library has a package you can use to create your own generators: https://github.com/protocolbuffers/protobuf-go/blob/master/compiler/protogen/protogen.go. The grpc-gateway doesn't use this because it was created long before this was available, but I heartily recommend it for new projects. Does that satisfy your need?

**Comment by ghstahl** [comment]
The short answer is yes I can roll my own and I am already doing this.  It relies on your protogen to have also run.  Mine is just an enhancement that pulls both the grpc server and the grpc-gateway into a single way to register it in my di.  

The root of the issue is that I need to know if any methods have bindings.  true/false.
This will tell me if the service has any gateway stuff and if not then My ```RegisterHandler``` is just a noop.  If true, it calls yours, which will now exist.

The amount of code I saw that you guys wrote to get that answer is too much to steal, so hoping for a quick fix on your end to lay down an empty Registration funcs.

I realize it's a bit hacky but does no harm.

Mine produces something like this assuming everyone has bindings.
```go
// Register the server with grpc gateway
func (srv *mystreamserviceServer) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
	RegisterMyStreamServiceHandler(context.Background(), gwmux, conn)
}

// Register the server with grpc
func (srv *mystreamserviceServer) Register(s *grpc.Server) {
	RegisterMyStreamServiceServer(s, srv)
}
```

However, if my service proto doesn't have any bindings then the following on your end doesn't get created.
``` 
RegisterMyStreamServiceHandler(context.Background(), gwmux, conn)
```
If that is the case mine should have been this.
```go
// Register the server with grpc gateway
func (srv *mystreamserviceServer) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
	// this service doesn't have any bindings.
}

// Register the server with grpc
func (srv *mystreamserviceServer) Register(s *grpc.Server) {
	RegisterMyStreamServiceServer(s, srv)
}
```

Anyway, just hoping you would think its an acceptable hack.

**Comment by johanbrandhorst** [comment]
That said, it's unlikely that we'll add an option for this to the generator, to be clear. It seems extremely niche and there are probably workarounds available for your use case. I'm sure you understand.
