### ISSUE TITLE
calling Enum by string name in requests using gogo/protobuf results in error.

### ISSUE THREAD

**Issue by foolusion** [grpc-ecosystem/grpc-gateway#372]
With the standard protoc_gen_go I can reference Enum's by their string name when using grpc-gateway. This is not the case when I use gogo binaries. 

The related issue gogo/protobuf#286

**Comment by johanbrandhorst** [comment]
This is because the grpc-gateway uses the golang/protobuf registered enum map for lookups. Like suggested in the link you provided you should use the `goproto_registration` extension to enable dual registration for your proto files.

**Comment by johanbrandhorst** [comment]
See https://github.com/gogo/protobuf/blob/master/gogoproto/doc.go#L151

**Comment by tmc** [comment]
I'd love to get this into wiki/docs.

**Comment by foolusion** [comment]
The `goproto_registration` extension solved my issue. Thanks!
