### ISSUE TITLE
Bzlmod support

### ISSUE THREAD

**Issue by aaliddell** [grpc-ecosystem/grpc-gateway#3759]
## 🚀 Feature

At present your Bazel support and dependencies are managed via your WORKSPACE file. Bazel 6 introduced Bzlmod for managing project dependencies using a registry, which helps to solve the transitive dependency problem.

I am attempting to support grpc-gateway under bzlmod [here](https://github.com/rules-proto-grpc/rules_proto_grpc/tree/next), but both paths I have tried presently do not work (direct plugins and Gazelle). My third option is to maintain a patchset on top of grpc-gateway that fixes dependency loads to work under bzlmod, which really won't be pleasant. Before I do this, are you considering adding Bzlmod support? Looking at what's presently in your WORKSPACE, I don't see any major blockers.

Some useful links:
- https://bazel.build/external/migration
- https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md

**Comment by johanbrandhorst** [comment]
This sounds like a great idea, but will it break existing users of Bazel? What does the Bazel team recommend maintainers do? We do have existing Bazel users and I don't want to suddenly spring this on them.

CC @achew22, our resident Bazel expert ;)

**Comment by aaliddell** [comment]
It's possible to offer support for both at the same time, but it is understandably more work to do so. Most projects [that have published modules](https://github.com/bazelbuild/bazel-central-registry/tree/main/modules) have got support for both methods, but personally I am cutting a major release of rules_proto_grpc that drops one and adds the other since WORKSPACE has been a collossal source of pain. There's a helpful project template [here](https://github.com/bazel-contrib/rules-template/tree/main) that helps automate the release process.

At the moment, bzlmod is an opt-in flag under Bazel 6, but from Bazel 7 (whose release [is imminent](https://github.com/bazelbuild/bazel/issues/18548)) bzlmod will [be enabled by default](https://github.com/bazelbuild/bazel/issues/18958). This flag flip won't immediately break things, since in the absence of a MODULE.bazel file, the WORKSPACE is used instead. But the path appears to be that WORKSPACE is on the way out over a long deprecation period.

**Comment by johanbrandhorst** [comment]
Thanks for that extra context, I expect we'll want to support both.

**Comment by SanjayVas** [comment]
In case it helps, I have a Bazel module for grpc-gateway in [my own registry](https://github.com/SanjayVas/bazel-registry/tree/main/modules/grpc-gateway). Note that it depends on the googleapis module in that registry, as that [does not have an official module yet](https://github.com/bazelbuild/bazel-central-registry/issues/1113).

**Comment by SanjayVas** [comment]
> This registers BCR and @SanjayVas registry.

I just wanted to give fair warning about using that registry directly. It's only intended to be used by other repos in that organization. There won't be any effort to avoid breaking other users. You may instead want to copy those modules into your own registry.
