### ISSUE TITLE
Support Google Flatbuffers

### ISSUE THREAD

**Issue by pcariel** [grpc-ecosystem/grpc-gateway#376]
Hi, gateway support Flat?

**Comment by achew22** [comment]
@pcariel, unfortunately we don't support Google's Flatbuffers effort at this time in any way. Are you hoping to have the gateway translate from ProtoBuf to Flatbuffers or are you looking to enhance the interface description language for Flatbuffers to support RPCs?

**Comment by pcariel** [comment]
To improve the interface description language.

**Comment by achew22** [comment]
@pcariel, this sounds like an interesting endeavour. Do you think you could get in touch with the Flatbuffers people to see if they are receptive to the idea and get back to me when you have all the details worked out?

I'm going to close this so it doesn't linger in our backlog but please reopen if you have any more thoughts.
