### ISSUE TITLE
Problem with Generated annotations.proto file

### ISSUE THREAD

**Issue by kigsmtua** [grpc-ecosystem/grpc-gateway#377]
The generated annotations file has proto3 as the syntax but parts of the stubs generated have proto2 

`
syntax = "proto3";

package google.api;

import "google/api/http.proto";
import "google/protobuf/descriptor.proto";

option go_package = "google.golang.org/genproto/googleapis/api/annotations;annotations";
option java_multiple_files = true;
option java_outer_classname = "AnnotationsProto";
option java_package = "com.google.api";
option objc_class_prefix = "GAPI";
 
/// NOT SUPPORTED IN
extend google.protobuf.MethodOptions {
  // See `HttpRule`.
  optional HttpRule http = 72295728;
}
`

**Comment by achew22** [comment]
Can you try going through our tutorial one more time making small changes and verifying as you go? I think this may have gone off the rails in the dev stage. If you have more issues please reopen/file a new issue.
