### ISSUE TITLE
I cannot get the default value from client side

### ISSUE THREAD

**Issue by zweich1212** [grpc-ecosystem/grpc-gateway#380]
My struct is like 
type TestMetric struct {
        TestA   int64 `protobuf:"varint,1,opt,name=testa" json:"testa,omitempty"`
        TestB  int64 `protobuf:"varint,2,opt,name=testb" json:"testb,omitempty"`
        TestC int64 `protobuf:"varint,3,opt,name=testc" json:"testc,omitempty"`
}
When I init each element of the struct with zero value, I cannot get it from HTTP client, while , I can get it, if I set them to -1 or other value.

What could be the root cause? 

Many thanks for your answers.

**Comment by achew22** [comment]
There has been a lot of work on the code since this was filed and I think it's likely that this is fixed. If you have more issues please reopen/file a new issue.
