### ISSUE TITLE
multi-folder not generating correct swagger file

### ISSUE THREAD

**Issue by zZHorizonZz** [grpc-ecosystem/grpc-gateway#3809]
## 🐛 Bug Report

The OpenAPI generator does not correctly generate Swagger documentation. It only generates documentation from the first found proto file, which doesn't even contain any service, and fails to merge other services into it. This results in an incomplete and inaccurate swagger file.

## To Reproduce

1. Set up the Go environment, and install `protoc` and required `protoc` plugins (as detailed in the provided script).
2. Run a script to remove directories other than 'common' and 'sdk' in 'kumo'.
3. Execute the command to generate Go files from proto files, aiming to generate a merged OpenAPI specification.
4. Observe that the generated `.swagger` file only contains information from `google/api/resource.proto` and does not include the expected services from `sdk/v1/fleet.proto` and `sdk/v1/project.proto`.

The github action for running:
```yaml
- name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install protoc and required protoc plugins
      run: |
        apt-get update && apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

    - name: Remove other directories
      run: |
        echo "Removing directories other than 'common' and 'sdk' in 'kumo'..."
        cd kumo
        find . -maxdepth 1 ! -name '.' ! -name '.git' ! -name 'common' ! -name 'sdk' -exec rm -rf {} +
        echo "Directories removed."

    - name: Generate Go files from proto files
      run: |
        mkdir -p out
        export PATH="$PATH:$(go env GOPATH)/bin"
        # Print the files to be processed
        find . -name '*.proto' -exec echo '{}' \;
        find . -name '*.proto' -exec protoc -I . \
          --go_out ./out --go_opt paths=source_relative \
          --go-grpc_out ./out --go-grpc_opt paths=source_relative \
          --grpc-gateway_out ./out --grpc-gateway_opt paths=source_relative \
          --openapiv2_out ./out --openapiv2_opt openapi_naming_strategy=fqn --openapiv2_opt logtostderr=true --openapiv2_opt include_package_in_tags=false --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api \
          '{}' \;
```
I know this is a github action but from my tests, this is also a problem when trying in other environments.
[api.zip](https://github.com/grpc-ecosystem/grpc-gateway/files/13650546/api.zip)

## Expected behavior

The expected behavior is that the OpenAPI specification would be correctly generated and merged from all relevant proto files, including services defined in `sdk/v1/fleet.proto` and `sdk/v1/project.proto`.

## Actual Behavior

The actual behavior is that the OpenAPI spec is not merged as expected. When the merge option is enabled, a `.swagger` file is generated, but it only contains basic information from `google/api/resource.proto` and omits the services from `sdk/v1/fleet.proto` and `sdk/v1/project.proto`.

Generated result:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "protoc-gen-openapiv2/options/annotations.proto",
    "version": "version not set"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {},
  "definitions": {
    "google.protobuf.Any": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "google.rpc.Status": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/google.protobuf.Any"
          }
        }
      }
    }
  }
}
```

## Your Environment

- GitHub Actions / Ubuntu
- Go version: 1.20
- Operating System: [The operating system used in the GitHub Actions runner / Tested on Debian as well]

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. It looks like this is the generation command:
```
 find . -name '*.proto' -exec protoc -I . \
          --go_out ./out --go_opt paths=source_relative \
          --go-grpc_out ./out --go-grpc_opt paths=source_relative \
          --grpc-gateway_out ./out --grpc-gateway_opt paths=source_relative \
          --openapiv2_out ./out --openapiv2_opt openapi_naming_strategy=fqn --openapiv2_opt logtostderr=true --openapiv2_opt include_package_in_tags=false --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api \
          '{}' \;
```
Perhaps I'm misunderstanding, but isn't this going to execute the command once per protobuf file? If you want to merge all the files into a single file, you need to give them to the same `protoc` invocation, otherwise you'll just and up overwriting the same file over and over again.

FWIW, protoc is super hard to use, perhaps you could try using `buf` instead?

**Comment by zZHorizonZz** [comment]
> Perhaps I'm misunderstanding, but isn't this going to execute the command once per protobuf file? If you want to merge all the files into a single file, you need to give them to the same protoc invocation, otherwise you'll just and up overwriting the same file over and over again.

Yes, that seems to be the case. The file 'api.swagger.json' has been overwritten for every .proto file.

> FWIW, protoc is super hard to use, perhaps you could try using buf instead?

Thank you for the tip it's really easier to use, and it works like a charm.
