### ISSUE TITLE
is it ready for production use?

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#382]

**Comment by tmc** [comment]
While we don't publish benchmarks I know of several folks putting moderate traffic through the gateway. It's not a very complicated piece of software once you have it configured.

If under any evaluation you find any deficiencies that should be addressed please do open issues so they can get attention. Thank you for your interest!

**Comment by jinleileiking** [comment]
which version is stable？Can give me  a release note?
