### ISSUE TITLE
Handling of grpc trailer metadata

### ISSUE THREAD

**Issue by tamalsaha** [grpc-ecosystem/grpc-gateway#386]
Grpc-gateway prefixes trailer metadata returned from grpc server with `Grpc-Trailer-` . But this seems unnecessary for metadata that grpc server itself prefixes with `grpc-` prefix. For example, for the [new grpc status,](https://github.com/grpc/grpc-go/pull/1156/files) grpc server returns the metadata with `grcp-status` and `grpc-status-details-bin`. The same can be said for any custom application metadata that might be prefixed at the application level.

- Should grpc- prefixed metadata be handled as a special case for response and passed as-is?
- Should there be a `OutgoingTrailerMatcher` option in `ServeMux`?

**Comment by TamalSaha** [comment]
cc: @tmc @achew22

**Comment by tmc** [comment]
+1 on OutgoingTrailerMatcher. I think prefixing ```grpc-``` headers is unnecessary.

**Comment by c4milo** [comment]
Could this issue be in some way related to https://github.com/grpc-ecosystem/grpc-gateway/issues/405?
