### ISSUE TITLE
For a field of type google.protobuf.Empty, FieldMaskFromRequestBody does not generate any fieldmask

### ISSUE THREAD

**Issue by sbansal7** [grpc-ecosystem/grpc-gateway#3866]
## 🐛 Bug Report

I have a PATCH rpc with request containing one of the fields being google.protobuf.Empty (i.e., message with no fields). When this RPC is called with the field set, FieldMaskFromRequestBody does not generate any fieldmask

## To Reproduce
```
syntax = "proto3";
...
service SomeService {
    rpc UpdateData(UpdateDataRequest) returns (Data) {
        option (google.api.http).patch = "/";
        option (google.api.http).body = "data";
    }
}
message UpdateDataRequest {
    Data data = 1;
    google.protobuf.FieldMask update_mask = 2;
}
message Data {
    google.protobuf.Empty empty = 1;
}
```

## Expected behavior

With the above definition, If I send `empty: {}`, I expect fieldmask to be set to "empty".

## Actual Behavior

I get no values in fieldmask. 
## Your Environment
MacOS, go1.21.4, grpc-gateway v2.15.0.

**Comment by sbansal7** [comment]
Here are the diffs for a failing test:
```
diff --git a/runtime/fieldmask_test.go b/runtime/fieldmask_test.go
index 1af66ab4..846ace85 100644
--- a/runtime/fieldmask_test.go
+++ b/runtime/fieldmask_test.go
@@ -28,6 +28,13 @@ func TestFieldMaskFromRequestBody(t *testing.T) {
                        name:     "empty",
                        expected: newFieldMask(),
                },
+               {
+                       name: "empty",
+
+                       msg:      &examplepb.ABitOfEverything{},
+                       input:    `{"oneof_empty": {}}`,
+                       expected: newFieldMask("oneof_empty"),
+               },
                {
                        name: "simple",
```

**Comment by johanbrandhorst** [comment]
Thanks for your issue! I'm a little confused - you have a field where the _presence_ of an empty message is significant? Surely an empty value isn't set or unset, it's just empty? What is the semantic meaning of a "set" empty value?

That said, if you want to contribute a fix for this, I'm all for it. I just don't really get it.

**Comment by sbansal7** [comment]
Thanks for response. Empty messages are useful as default choice in oneof. Similar to how it is defined here: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/proto/examplepb/a_bit_of_everything.proto#L295

Here is another example. Lets say, you want the user to select a site or give the use an option to explicitly select "all_sites", you could define a oneof like this:
```
oneof site_option {
    google.protobuf.Empty all_sites = 1;
    string site = 2;
  }
```

Now, when someone sends `all_sites`, I was hoping that I will get `all_sites` set in fieldMask, but it is not set.
