### ISSUE TITLE
generate swagger schema title and description failed

### ISSUE THREAD

**Issue by lucklyt** [grpc-ecosystem/grpc-gateway#3867]
I want to generate both tile and desc for message field, I checked template.go source file and fount tile and desc split by 
const paragraphDeliminator = "\n\n",so I  modify the comment bellow:
![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/150762476/ef796bcc-5ba0-460d-af6c-f7b10c1bc590)
but the generated file still has only title, and \n\n  seems to have been escaped, how to fix it?
![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/150762476/86909e8d-5ce3-4e31-9d53-d07cef61483b)

**Comment by johanbrandhorst** [comment]
I think you probably want to make the comment above the field instead:
```protobuf
message GetTokenInfoResponse {
  // Title here
  //
  // Description goes here
  TokenInfo token_info = 1;
}
```

**Comment by lucklyt** [comment]
> I think you probably want to make the comment above the field instead:
> 
> ```proto
> message GetTokenInfoResponse {
>   // Title here
>   //
>   // Description goes here
>   TokenInfo token_info = 1;
> }
> ```

yes, my problem solved , thx!
