### ISSUE TITLE
Issue with importing "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"

### ISSUE THREAD

**Issue by htnphu** [grpc-ecosystem/grpc-gateway#3882]
## 📚 Documentation

I am encountering an issue with the import statement for "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" in the tools package of my Go project. The program is not importing as expected, and I'm seeking assistance to resolve the issue. Thank you!

**Environment:**
- Go version: go version go1.21.4 linux/amd64
- Operating System: ubuntu 22.04

![Screenshot from 2024-01-11 11-47-30](https://github.com/grpc-ecosystem/grpc-gateway/assets/83742949/68cc1fa0-fb81-4b5c-b8d5-15bfc41ad761)

**Comment by htnphu** [comment]
I tried to use "go get -u github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" and then it is fixed, thanks

**Comment by htnphu** [comment]
I think this way is not allowed in version 1.21. (import  _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"
)

**Comment by johanbrandhorst** [comment]
We recommend you use `go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest` to install the plugin nowadays. Tool dependencies have some other problems, though I'm not sure why this wouldn't be working.

**Comment by htnphu** [comment]
thank you so much @johanbrandhorst
