### ISSUE TITLE
Output file will not compile if the .proto file does not contain a service with parameters in the url path

### ISSUE THREAD

**Issue by wrrn** [grpc-ecosystem/grpc-gateway#389]
If there is a .proto file that look like this:

```proto
syntax = "proto3";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

package status;

service HealthCheck {
  rpc GetStatus(google.protobuf.Empty) returns (Status){
    option (google.api.http) = {
      get: "/status" // notice that it does not have any parameters in the path
    };
  }
}

message Request{}

message Status {
  uint32 status = 1;
}
```

The resulting ```status.gw.pb.go``` file will not compile. ```go build``` results in ```./status.pb.gw.go:24: imported and not used: "google.golang.org/grpc/status"```

**Comment by tmc** [comment]
@wrrn thank you for your issue report. @TamalSaha hopped on this at https://github.com/grpc-ecosystem/grpc-gateway/pull/387

**Comment by wrrn** [comment]
Awesome Thanks
