### ISSUE TITLE
[Question] How do I use semantic versions?

### ISSUE THREAD

**Issue by fiibbb** [grpc-ecosystem/grpc-gateway#392]
I use `glide` to fetch semantic version releases. But the compiler plugin `protoc-gen-grpc-gateway` or `protoc-gen-swagger` need to be get with `go get`, which always fetches the latest commit (as far as I know). So sometimes my runtime library is the latest released version, eg `1.2.0`, but my compiler plugin is generating code with commits ahead of `1.2.0`, and the generated code is not compatible with runtime library. How do people solve this problem?

**Comment by TamalSaha** [comment]
You can install those plugins from the vendor folder. See here: https://github.com/grpc-ecosystem/grpc-gateway/issues/384#issuecomment-300863457

**Comment by fiibbb** [comment]
That works. Thanks a lot.
