### ISSUE TITLE
[question]can give a url with query sting demo?

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#394]
eg: 

`curl xxxx:8989/aaa/bbb?a=5&c=6`

**Comment by TamalSaha** [comment]
@jinleileiking . gateway implements https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L27 . You will find useful information in the proto file.

**Comment by jinleileiking** [comment]
Very useful . Thanks.
