### ISSUE TITLE
snake_case response

### ISSUE THREAD

**Issue by shijting** [grpc-ecosystem/grpc-gateway#3943]
Hi guys, how do I change the JSON field of the response to snake_case when using grpc-gateway as an api gateway?

**Comment by johanbrandhorst** [comment]
https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/#we-now-use-the-camelcase-json-names-by-default has a guide on how to set this consistently.
