### ISSUE TITLE
how to handle arbitrary (json) structs

### ISSUE THREAD

**Issue by lucas-natraj** [grpc-ecosystem/grpc-gateway#395]
i haven't been able to find an example of how to support arbitrary json -> map[string]interface{}.
i've defined my `message` as:
```proto
message Entity {

    // The entity's key.
    string key = 1;

    // The entity's properties.
    google.protobuf.Struct data = 2;
}
```

as `Struct` seems to be the appropriate json equivalent in protobuf.

however, i am unable to invoke the corresponding REST endpoint using 
```json
{
    "key": "xyz",
    "data": {
        "name": "joe",
        "age": 28
    }
}
```

is there a way to support arbitrary json content and have it mapped to basically a `map[string]interface{}`?

not sure how I need to define my proto messages / services to support this.

**Comment by TamalSaha** [comment]
This is not a gateway question, rather what you can map into protocol buffer. The short answer is, you can't define arbitrary `map[string]interface{}` in protocol buffer.  Please check here: https://developers.google.com/protocol-buffers/docs/proto3#oneof

**Comment by lucas-natraj** [comment]
yeah, i understand that `map[string]interface{}` isn't really _supported_. i was just using it as an example of handling arbitrary content.

the `struct` [message](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto) does, in fact, use `oneof` and I am able to receive it on the grpc service side.

however, when using the gateway, i have to send the json request body as 
```json
{
  "key": "xyz",
  "data": {
    "fields": {
      "name": {
        "stringValue": "joe"
      },
      "age": {
        "numberValue": 28
      }
    }
  }
}
```

which, while not ideal, does actual get parsed correctly by the gateway.
i was wondering whether there was a way to achieve the more natural json representation (mentioned earlier).

**Comment by TamalSaha** [comment]
I don't think you can do any better with `oneof`.

**Comment by TamalSaha** [comment]
As an alternative, you could use `map[string]string`, then deal with type conversion in your code. In that case, `json` form might look a bit nicer.

**Comment by lucas-natraj** [comment]
hmm.. somewhat doable, although things quickly get mucky with nested objects.

oh well.. guess i'm outta luck.

thanks for your time @TamalSaha.

**Comment by bobbytables** [comment]
I'm pretty sure this can solve this for anyone else that finds this issue: https://godoc.org/github.com/golang/protobuf/jsonpb#Unmarshal

**Comment by derekperkins** [comment]
@bobbytables Not quite sure what you mean. How does that let you map arbitrary json to a field?

**Comment by derekperkins** [comment]
This worked for us: https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct

**Comment by vnt32** [comment]
> yeah, i understand that `map[string]interface{}` isn't really _supported_. i was just using it as an example of handling arbitrary content.
> 
> the `struct` [message](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto) does, in fact, use `oneof` and I am able to receive it on the grpc service side.
> 
> however, when using the gateway, i have to send the json request body as
> 
> ```json
> {
>   "key": "xyz",
>   "data": {
>     "fields": {
>       "name": {
>         "stringValue": "joe"
>       },
>       "age": {
>         "numberValue": 28
>       }
>     }
>   }
> }
> ```
> 
> which, while not ideal, does actual get parsed correctly by the gateway. i was hoping there was a way to achieve the more natural json representation I mentioned earlier.

Thanks, I barely found how to use this thing, because. not in one guide google this is not written. Used shnake_case instead of camelCase based on type from proto file
