### ISSUE TITLE
api_visibility doesn't transitively apply to rpc request/response messages

### ISSUE THREAD

**Issue by Place1** [grpc-ecosystem/grpc-gateway#3962]
## 🐛 Bug Report

Hello, it seems like `visibility_restriction_selectors` don't apply transitively to rpc messages when using the service option for `api_visibility`. 

Here's an example grpc spec:

```protobuf
service Example {
    option (google.api.api_visibility).restriction = "INTERNAL";

    rpc Greet(GreetRequest) returns (GreetResponse) {}
}

message GreetRequest {}

message GreetResponse {}
```

The `GreetRequest` and `GreetResponse` messages should not be included in the generated openapi spec if the `visibility_restriction_selectors` excludes the service but currently they will be included.

I believe the bug is occurring here: https://github.com/grpc-ecosystem/grpc-gateway/blob/bc00be5a204f0a2632437f8c4212469151e8c72e/protoc-gen-openapiv2/internal/genopenapi/template.go#L433-L440

Looks like the above code needs to check for service visibility and conditionally skip the service.

Here are some other spots where the service visibility **is** correctly checked for reference:

- https://github.com/grpc-ecosystem/grpc-gateway/blob/bc00be5a204f0a2632437f8c4212469151e8c72e/protoc-gen-openapiv2/internal/genopenapi/template.go#L1151-L1153
- https://github.com/grpc-ecosystem/grpc-gateway/blob/bc00be5a204f0a2632437f8c4212469151e8c72e/protoc-gen-openapiv2/internal/genopenapi/template.go#L1151-L1153

The above two spots mean that the service **is** correctly hidden from the openapi spec's service tags and routes/operations.

I believe messages should be transitively skipped to match the behaviour of the `method_visibility` option which also had this bug a while ago (https://github.com/grpc-ecosystem/grpc-gateway/issues/2691)

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue, that seems reasonable to me! Would you be interested in contributing a fix for this?

**Comment by Place1** [comment]
No problem. Here's a PR with a new test case as well: https://github.com/grpc-ecosystem/grpc-gateway/pull/3966
