### ISSUE TITLE
protoc-gen-grpc-gateway and protoc-gen-openapiv2 return incorrect version

### ISSUE THREAD

**Issue by TheRoSS** [grpc-ecosystem/grpc-gateway#3967]
## 🐛 Bug Report

The installed binaries protoc-gen-grpc-gateway and protoc-gen-openapiv2 do not return correct version information if you call them with --version argument

## To Reproduce

1. go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.19.1
2. go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.19.1
3. protoc-gen-grpc-gateway --version
4. protoc-gen-openapiv2 --version

## Expected behavior

Some string with v2.19.1

## Actual Behavior

Version dev, commit unknown, built at unknown
Version dev, commit unknown, built at unknown

## Your Environment

Ubuntu 22.04.3 LTS
go version go1.20.9 linux/amd64

**Comment by johanbrandhorst** [comment]
Building the version from source does not install the version information unless you provide the relevant build time constants. You will need to manually set the linker flags to populate the global variables here: https://github.com/grpc-ecosystem/grpc-gateway/blob/400fac1c484d2a58fc8882fa2101c9613b8517a2/protoc-gen-openapiv2/main.go#L56-L60

Something like
```
$ go install -ldflags="-X 'github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/main.version=v2.19.1'" github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.19.1
```

Might work? In any case, the binaries available from our releases page should contain the version information. I'm going to go ahead and close this as I don't think there's anything we can do about this on the source side of things.
