### ISSUE TITLE
Is there any way to generate python gateway code?

### ISSUE THREAD

**Issue by chaitanya9186** [grpc-ecosystem/grpc-gateway#398]

**Comment by achew22** [comment]
@chaitanya9186 Can you elaborate a little bit more. How do you mean "python gateway code"?

**Comment by chaitanya9186** [comment]
Currently there is a way to generate grpc gateway or rest proxy server code in golang. Is there anyway we can generate similar code in python?

**Comment by chaitanya9186** [comment]
Sample golang gateway generated code: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/examplepb/echo_service.pb.gw.go

**Comment by achew22** [comment]
The code that is generated in that case is highly dependent on the rest of the code in this library. Without a complete rewrite of the core of this project I'm not sure we will be able to generate python code that works.

There is a project similar to the efforts here, [grpc-jersey](https://github.com/fullcontact/grpc-jersey) which does this for Java and Jersey. You could use these two projects as a template for doing something in python.

I look forward to hearing about your work :smile:

**Comment by chaitanya9186** [comment]
@achew22 Thanks for the clarification.
