### ISSUE TITLE
returned errors should conform to google.rpc.Status

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#399]
refs https://cloud.google.com/apis/design/errors

**Comment by TamalSaha** [comment]
If you use the grpc-go/status package, you are automatically following this proto. https://github.com/grpc/grpc-go/blob/master/status/status.go#L49

Is any further change needed?

**Comment by kazegusuri** [comment]
Yes, status proto as error was introduced via https://github.com/grpc-ecosystem/grpc-gateway/pull/378.

**Comment by tmc** [comment]
I'm referring to the fields that are encoded on the errorBody type

**Comment by tmc** [comment]
This is addressed by #378, my mistake.
