### ISSUE TITLE
Dependency on google.golang.org/grpc/health/grpc_health_v1  conflicts with custom proto marshallers

### ISSUE THREAD

**Issue by andrewmed-prop** [grpc-ecosystem/grpc-gateway#4000]
## 🐛 Bug Report

Proto APIv2 supports implementing custom marshalers through [this](https://github.com/grpc/grpc-go/blob/05db80f1185060521de1b0c24f06faf9c9003354/codec.go#L42-L42)  interface

Implementing health check marshaller  creates implementation of health check which conflicts and panics in runtime due to dependency introduced in grpc-gateway in [this](https://github.com/grpc-ecosystem/grpc-gateway/commit/db9c664000c1c15ade14789de28772325a1c8bcc) commit on [default](https://github.com/grpc/grpc-go/tree/05db80f1185060521de1b0c24f06faf9c9003354/health/grpc_health_v1) implementation of health check, in calling [init()](https://github.com/grpc/grpc-go/blob/05db80f1185060521de1b0c24f06faf9c9003354/health/grpc_health_v1/health.pb.go#L258-L258)

## To Reproduce

1. Generate marshaller for a health check [proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto)  using any custom marshaller for example [vtproto](https://github.com/planetscale/vtprotobuf)

```
protoc *.proto -I=.  -I=$GOPATH/src/github.com/googleapis/googleapis -go_out=paths=source_relative:. --go-vtproto_out=paths=source_relative:.
```

2. Run program with dependency on generated stubs and on grpc-gateway

## Expected behavior

Compiles and runs

## Actual Behavior

Compiles and panics

```
panic: proto: file "grpc/health/v1/health.proto" has a name conflict over grpc.health.v1.HealthCheckResponse
	previously from: "github.com/propellerads/rotator/internal/servers/grpc/healthcheck"
	currently from:  "google.golang.org/grpc/health/grpc_health_v1"
See https://protobuf.dev/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x102c16c80?, 0x1400047ceb0?}, {0x102c16c80?, 0x1400047cef0})
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/protobuf@v1.32.0/reflect/protoregistry/registry.go:56 +0x1fc
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile.func1({0x102c23180, 0x14000582c30})
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/protobuf@v1.32.0/reflect/protoregistry/registry.go:154 +0x228
google.golang.org/protobuf/reflect/protoregistry.rangeTopLevelDescriptors({0x102c26df8, 0x140004eac40}, 0x1400063f8d0)
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/protobuf@v1.32.0/reflect/protoregistry/registry.go:417 +0x13c
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0x1400000e348, {0x102c26df8?, 0x140004eac40?})
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/protobuf@v1.32.0/reflect/protoregistry/registry.go:149 +0x5c4
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x102a719df, 0x2c}, {0x1031d4e40, 0x22d, 0x22d}, 0x1, 0x2, 0x0, 0x1, {0x102c1adc0, ...}, ...})
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/protobuf@v1.32.0/internal/filedesc/build.go:112 +0x1a0
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x102a719df, 0x2c}, {0x1031d4e40, 0x22d, 0x22d}, 0x1, 0x2, 0x0, 0x1, {0x0, ...}, ...}, ...})
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/protobuf@v1.32.0/internal/filetype/build.go:138 +0x15c
google.golang.org/grpc/health/grpc_health_v1.file_grpc_health_v1_health_proto_init()
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/grpc@v1.61.0/health/grpc_health_v1/health.pb.go:303 +0x168
google.golang.org/grpc/health/grpc_health_v1.init.0()
	/Users/a.medvedev/code/go/pkg/mod/google.golang.org/grpc@v1.61.0/health/grpc_health_v1/health.pb.go:258 +0x1c
```

## Your Environment

go 1.22

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. This seems like a classic protobuf dependency management issue, and I actually think the way to fix this is in your protobuf file hierarchy.

The root cause of this issue is that protobuf files are globally namespaced but very easily importable from different paths. It seems you are generating a health check Go file from the protobuf source somewhere in your tree, instead of importing the Go gRPC package which is intended for this purpose: https://pkg.go.dev/google.golang.org/grpc/health/grpc_health_v1. If you change your protobuf hierachy such that instead of generating a Go file from the protobuf sources, you import the https://pkg.go.dev/google.golang.org/grpc/health/grpc_health_v1 package, this issue should go away.

Please let me know if you have any further questions!

**Comment by johanbrandhorst** [comment]
Can you not avoid using vtproto on this case? It's binary compatible, right?

**Comment by andrewmed-prop** [comment]
The issue will be with any custom marshaller that implements grpc [Codec](https://github.com/grpc/grpc-go/blob/05db80f1185060521de1b0c24f06faf9c9003354/codec.go#L42-L42)

So the question is should we allow custom marshalers or not. As it is a standard interface and frequent feature for high load services, introducing dependency in a library on a particular (default) implementation IMO is a bug.

**Comment by johanbrandhorst** [comment]
I'm still not convinced. I'm sympathetic to your issue but I don't think this is something worth removing the health check feature in the gateway for. I recommend you either fork this project and perform the necessary changes or turn off the runtime panic using the setting https://protobuf.dev/reference/go/faq/#namespace-conflict.
