### ISSUE TITLE
Swagger Codegen Duplicate Operation Ids With Additional Bindings

### ISSUE THREAD

**Issue by brandoncole** [grpc-ecosystem/grpc-gateway#406]
If we use the `additional_bindings` option in our *.proto like this:

```proto
  rpc Update(UpdateRequest) returns (UpdateResponse) {
    option (google.api.http) = {
      put: "/v1/credentials/{locator.drn}"
      body: "*"
      additional_bindings {
        put: "/v1/accounts/{locator.drn}/versions/{locator.version}"
      }
    };
  };
```

The swagger that gets generated has `operationId` collisions: 

```json
"/v1/accounts/{locator.drn}": {
  "put": {
    "summary": "Updates an Account.",
    "operationId": "Update",
    "responses": {
      "200": {
        "description": "",
        "schema": {
          "$ref": "#/definitions/accountsUpdateResponse"
        }
      }
    },
    
    ..
            

"/v1/accounts/{locator.drn}/versions/{locator.version}": {
  "put": {
    "summary": "Updates an Account.",
    "operationId": "Update",
    "responses": {
      "200": {
        "description": "",
        "schema": {
          "$ref": "#/definitions/accountsUpdateResponse"
        }
      }
    },
```

This causes the Swagger editor to show:

> Semantic error at paths./v1/accounts/{locator.drn}/versions/{locator.version}.update.operationId
operationIds must be unique

Although the `operationId` values are not needed for the generated Go code or clients, it seems like this is a bit of tidying that may need addressed.  Let me know if I can help.

**Comment by tmc** [comment]
@brandoncole is just omitting operationId a reasonable solution? only include it for the first?

**Comment by makkalot** [comment]
is it possible swagger generator to skip operationId generation ? @tmc

**Comment by brandoncole** [comment]
@tmc @makkalot Omitting is fine for some languages like Go.  Python requires it for server side implementations.

**Comment by makkalot** [comment]
I tried to generate a client with duplicated `operationId` and got this  (used go-swagger tool):

```
swagger generate client -f service.swagger.json
The swagger spec at "service.swagger.json" is invalid against swagger specification 2.0. see errors :
- "Get" is defined 2 times
- "Update" is defined 2 times
- "Delete" is defined 2 times
```

Also when omit the `operationId` the generated code is very very ugly the method names are unreadable.

**Comment by anweiss** [comment]
Would be great if we could customize the generated `operationId` via an `additional_bindings` option

**Comment by achew22** [comment]
@anweiss, I think you can do it through the operation annotation
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/options/openapiv2.proto#L57

Example that touches nearby fields but not the `operationId`
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/examplepb/a_bit_of_everything.proto#L162

**Comment by anweiss** [comment]
Thanks @achew22, although how would I denote multiple `operation_id` fields to reflect the `additional_bindings` under the same rpc method? Only a single `grpc.gateway.protoc_gen_swagger.options.openapiv2_operation` option type is allowed per rpc method

**Comment by johanbrandhorst** [comment]
🎉 good enough for me
