### ISSUE TITLE
Support disabling default response rendering in bazel rule

### ISSUE THREAD

**Issue by rajukrishnamurthy** [grpc-ecosystem/grpc-gateway#4123]
## 🚀 Feature
Disable default response was already implemented in [pull/3006](https://github.com/grpc-ecosystem/grpc-gateway/pull/3006), however, this is not surfaced in the [protoc_gen_openapiv2](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/defs.bzl#L258C1-L258C21) rule.

I believe this might be relatively trivial and I've attached a [patch](https://github.com/grpc-ecosystem/grpc-gateway/files/14644511/disable_default_responses.openapis.patch).

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. Please feel free to just open a PR with the patch :).
