### ISSUE TITLE
[question]Is there any example for  http headers process?

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#420]
I need example :(

**Comment by tamalsaha** [comment]
Are you referring to example for WithIncomingHeaderMatcher, etc?

**Comment by jinleileiking** [comment]
yes. I have know how to use it, later I will update wiki.

**Comment by jinleileiking** [comment]
updated wiki

**Comment by tamalsaha** [comment]
I have some example code in https://github.com/cowrypay/dealer/blob/master/pkg/apiserver/cmd/server.go#L114

You can see how it is used. There is not a lot of documentation yet, sorry!
