### ISSUE TITLE
google/protobuf/descriptor.proto: File not found

### ISSUE THREAD

**Issue by jwalters-gpsw** [grpc-ecosystem/grpc-gateway#422]
When trying to compile the proto file for https://github.com/philips/grpc-gateway-example/tree/master/echopb

get the error: google/protobuf/descriptor.proto: File not found

Either don't have the right descriptor.proto installed, or something about protoc args need to be changed. Any ideas?

Both
./github.com/googleapis/googleapis/third_party/nanopb/generator/proto/google/protobuf/descriptor.proto
and
./github.com/googleapis/googleapis/third_party/protobuf/src/google/protobuf/descriptor.proto

are in my $GOPATH/src

Golang: 1.8.3
OS: darwin

Makefile:
```
protoc -I/usr/local/include -I. \
		-I${GOPATH}/src \
		-I${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
		--go_out=google/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,plugins=grpc:. \
		service.proto

```

```
$ make
protoc -I/usr/local/include -I. \
		-I/Users/jwalters/go/src \
		-I/Users/jwalters/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
		--go_out=google/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,plugins=grpc:. \
		service.proto
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
service.proto: Import "google/api/annotations.proto" was not found or had errors.
make: *** [all] Error 1

```

**Comment by AlekSi** [comment]
That's the problem with include directories. Do you have `/usr/local/include/google/protobuf` directory? Did you run protobuf's `make install`?

**Comment by upeediak** [comment]
As AlekSi mentioned, it is missing includes. If you downloaded and extracted the `protoc-xyz-os-....zip` file, there should be an `include` folder. Make sure you move the content of that folder to somewhere under your PATH (eg: `/usr/local/include/`)

**Comment by achew22** [comment]
If you continue having issues please reopen or file a new issue.

**Comment by oseiskar** [comment]
Encountered this issue and solved it on Debian Stretch Linux by installing `libprotobuf-dev` and `libprotoc-dev` packages (not sure which one was needed or both).

This was in a different context not related to grpc-gateway but googling the error brought me and hence this seems like the best forum for sharing this solution.

**Comment by martinscholz83** [comment]
I know this is an old thread but i run into similar problem. This is my proto file

```
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
``` 

When using with C# everything work like expected. When i try to use the same proto file with C++ and run `protoc.exe` i get the following error
```
google/protobuf/empty.proto: File not found.
google/protobuf/wrappers.proto: File not found.
grpc.proto: Import "google/protobuf/empty.proto" was not found or had errors.
grpc.proto: Import "google/protobuf/wrappers.proto" was not found or had errors
````

Something is missed?

**Comment by rafee** [comment]
> Encountered this issue and solved it on Debian Stretch Linux by installing `libprotobuf-dev` and `libprotoc-dev` packages (not sure which one was needed or both).
> 
> This was in a different context not related to grpc-gateway but googling the error brought me and hence this seems like the best forum for sharing this solution.

This solved my issue by installing `libprotobuf-dev`

**Comment by lookbackagain** [comment]
At window10, '/usr/local/include/' shoud replace with wath your download protobuf path

**Comment by gaoshanyu** [comment]
Does any one meet the same error on macOS? I've installed `protobuf` via `brew install protobuf` already.

```
➜  ~ brew info protobuf                                 
protobuf: stable 3.11.0 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/protocolbuffers/protobuf/
/usr/local/Cellar/protobuf/3.6.1 (256 files, 17.2MB) *
  Poured from bottle on 2018-11-03 at 19:07:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, python ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 41,926 (30 days), 140,726 (90 days), 455,949 (365 days)
install-on-request: 18,303 (30 days), 61,550 (90 days), 207,336 (365 days)
build-error: 0 (30 days)
```

**Comment by gaoshanyu** [comment]
Still get this error after upgrade protobuf.

```
➜  ~ brew info protobuf   
protobuf: stable 3.11.0 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/protocolbuffers/protobuf/
/usr/local/Cellar/protobuf/3.11.0 (268 files, 19.5MB) *
  Poured from bottle on 2020-01-14 at 11:59:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, python ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 41,926 (30 days), 140,726 (90 days), 455,949 (365 days)
install-on-request: 18,303 (30 days), 61,550 (90 days), 207,336 (365 days)
build-error: 0 (30 days)
```

**Comment by johanbrandhorst** [comment]
Hi, this isn't an issue with the gRPC-gateway, so please try to find help elsewhere. The error implies that you have an incorrect protobuf installation. Perhaps raise the issue with the package maintainers?

**Comment by chengyayu** [comment]
> Does any one meet the same error on macOS? I've installed `protobuf` via `brew install protobuf` already.
> 
> ```
> ➜  ~ brew info protobuf                                 
> protobuf: stable 3.11.0 (bottled), HEAD
> Protocol buffers (Google's data interchange format)
> https://github.com/protocolbuffers/protobuf/
> /usr/local/Cellar/protobuf/3.6.1 (256 files, 17.2MB) *
>   Poured from bottle on 2018-11-03 at 19:07:25
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb
> ==> Dependencies
> Build: autoconf ✔, automake ✔, libtool ✔, python ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 41,926 (30 days), 140,726 (90 days), 455,949 (365 days)
> install-on-request: 18,303 (30 days), 61,550 (90 days), 207,336 (365 days)
> build-error: 0 (30 days)
> ```

Has the problem been solved?

**Comment by kuchaguangjie** [comment]
In addition to copy `protoc/include/google` into `/usr/local/include/`.

For `Goland` (or other Jetbrains IDE), need do following:

- preference -> language & framework -> protocol buffers,
- uncheck "configure automatically",
- add import path as `/usr/local/include`.

**Comment by shivshankarramprasad** [comment]
usr/local/include location ? where in C://
