### ISSUE TITLE
Change the path though http header

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#424]
normal proto:

```
41 service Greeter {¬
  42   // Sends a greeting¬
  43   rpc SayHello (HelloRequest) returns (HelloReply) {¬
  44     option (google.api.http) = {¬
  46     post: "/Action/2017-01-01"¬
  47     body: "*"¬
  48   };¬
  49 }¬
```

For me, I need change the `post: "/Action/2017-01-01"` to  `post: "/{{Action}}/{{Version}}"`

which Action and Version is http header.

**Comment by achew22** [comment]
I think this sort of change would require a change in the http<=>proto spec. Please feel free to open an issue in that repo and CC me.
