### ISSUE TITLE
generate code use context not "golang.org/x/net/context"

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#430]
The gate way generated code, use `"golang.org/x/net/context"` 

Plz , use context instead.

**Comment by alecholmez** [comment]
All of gRPC-go needs to switch to `context` for that matter

**Comment by achew22** [comment]
We are aware of this and have attempted to make the switch along with grpc-go. Unfortunately without this projects dependencies being moved over, we can't move over. I'm going to close this in favour of older bugs. Feel free to subscribe to those to track progress.

#349 #343

**Comment by thurt** [comment]
brief comment for others: my interface implementation file automatically added a "context" import. so i just have to manually change that to "golang.org/x/net/context" in order to prevent getting an error from RegisterServiceServer
