### ISSUE TITLE
How to remove @type or type_url after marshal google.protobuf.Any?

### ISSUE THREAD

**Issue by DouFuJuShi** [grpc-ecosystem/grpc-gateway#4309]
How to remove @type or type_url after marshal google.protobuf.Any?

**Comment by johanbrandhorst** [comment]
What you're talking about is the proper JSON representation of the `google.protobuf.Any` type: https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/any.proto#L101-L126. Perhaps you want to use something else?

**Comment by DouFuJuShi** [comment]
> What you're talking about is the proper JSON representation of the `google.protobuf.Any` type: https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/any.proto#L101-L126. Perhaps you want to use something else?

In order to return a unified response body,  define a messge type and Custom Marshaler ：
`message Response {
  int32 code = 1;
  string message = 2;
  google.protobuf.Any data = 3;
}`


`type CustomMarshaler struct {
	*runtime.JSONPb
}

func (cm *CustomMarshaler) Marshal(v interface{}) ([]byte, error) {
	// 调用JSONPb Marshal
	if reply, ok := v.(proto.Message); ok {
		data, _ := anypb.New(reply)
		resp = &errors.Response{
			Code:    errors.BizCodeOK,
			Message: errors.BizCodeText(errors.BizCodeOK),
			Data:    data,
		}
		return cm.JSONPb.Marshal(resp)
	}

	return cm.JSONPb.Marshal(v)
}`


Because `google.protobuf.Any`，The  json will have @type.
I want to remove @type, how can I do it ?
