### ISSUE TITLE
RESOURCE_EXHAUSTED -> 503

### ISSUE THREAD

**Issue by jhspaybar** [grpc-ecosystem/grpc-gateway#431]
Right now it appears that HTTPStatusFromCode converts a RESOURCE_EXHAUSTED into a 403.  I'd like to convert this to a 503, and it looks like I need to do this by calling withProtoErrorHandler and passing in my mux?  I will be more or less copy/pasting the DefaultProtoErrorHandler method just swapping out the status mapping function and before I went this route, wanted to see if there was a better way to pull this off.

Thanks.

**Comment by achew22** [comment]
Unfortunately I'm not sure of a better way without changing things in grpc-gateway. I think a case could be made that 403 isn't the right code for this (that is forbidden, right?) and I'd be open to changing it to something different. Could you send a PR?
