### ISSUE TITLE
swagger title and version hardcoded

### ISSUE THREAD

**Issue by bamnet** [grpc-ecosystem/grpc-gateway#437]
Currently the swagger files generated by protoc-gen-swagger have `title` and `version` attributes which aren't very useful - 

e.g.
```json
"info": {
    "title": "proto/file.proto",
    "version": "version not set"
  },
```

It would be great if these values better matched the spec, including a title for the service and some version information.

**Comment by bamnet** [comment]
Two implementation ideas come to mind:
1. Pass title and version as CLI flags.
2. Parse values from the proto.  The `service` name in the proto coud map to the swagger `title` and some clever regexing could extract version info from the http paths /v1/method => "v1".

**Comment by erwinvaneyk** [comment]
It might be more consistent with other configuration for particular plugins to add it as options in the proto file: https://developers.google.com/protocol-buffers/docs/proto3#options

**Comment by achew22** [comment]
@erwinvaneyk, I think that would be a great way to approach this. Options defined in the proto would be great. @bamnet, would you like to take that on?

**Comment by bamnet** [comment]
I'm not as familiar with the landscape of plugins using custom options for configs, can you point me to a sample or two in the wild using custom options?  I'm curious to see the other use cases for them.

Sticking this in the proto is a much better idea than passing them as CLI flags 😄, but I'm not sure of a simple use case where service couldn't translate to title, and version couldn't be parsed from an http annotation following the style guide. Getting a basic version and service name automagically might be helpful for developers who don't want to do any work to the custom options.  I can see options giving developers more control if they're not satisfied with the automatic extraction.

**Comment by c4milo** [comment]
FWIW, I did solve this and other customizations using a Makefile and jq to merge the files. I'm happy to share if anyone is interested.

**Comment by AlekSi** [comment]
Related to #303

**Comment by patrickwmcgee** [comment]
@c4milo I'd love your `Makefile` & `jq` magic until this gets resolved in the actual tooling :)

**Comment by c4milo** [comment]
@patrickwmcgee, sure, this is what I do in my apis repo: https://gist.github.com/c4milo/01e344c369ed2f9e0253ca168047197d

**Comment by achew22** [comment]
I believe you can do this now, thanks to Ivan. Thanks Ivan!
