### ISSUE TITLE
OpenAPI gen doesn't work default mapping.

### ISSUE THREAD

**Issue by SpeedReach** [grpc-ecosystem/grpc-gateway#4374]
## 🐛 Bug Report

OpenAPI generation doesn't work default mapping.

## To Reproduce

Have a normal proto file using default mapping to http paths.
```proto
service AuthService{
  rpc EmailLogin(EmailLoginRequest) returns (EmailLoginResponse) {}
}
message EmailLoginResponse{
  string userId = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message EmailLoginRequest{
  string email = 1;
  string password = 2;
}
```
Generate swagger doc.
`protoc -I . --openapiv2_out ./gen --openapiv2_opt=preserve_rpc_order=true  .\auth.proto`

## Expected behavior

The generated swagger should have default paths.

## Actual Behavior
Paths are empty.

![image](https://github.com/grpc-ecosystem/grpc-gateway/assets/37238439/740657fd-39eb-4439-8b04-6c71f8fcb1e2)

## Your Environment

(Environment name, version and operating system.)
windows11 , latest protobuf and grpc-ecosystem.

**Comment by johanbrandhorst** [comment]
The generated openapiv2 document has no paths because there are no HttpRule annotations in your rpc definitions. If you are using `generate_unbound_methods=true` with `protoc-gen-grpc-gateway`, you need to use `generate_unbound_methods=true` with `protoc-gen-openapiv2` too.
