### ISSUE TITLE
choose some return fields omit or  not omit by configure

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#439]
We know than through 
marashaller: `EmitDefaults: true`

Can let all the json fields not omitempty, the return will show all the fields.

Can we make some configure to let the json field show or not show by conf? 

Not show all or show none

**Comment by achew22** [comment]
You should be able to implement this with a custom marshaller. Marshall the fields you care about and don't for the ones you don't.
