### ISSUE TITLE
Grpc gateway project starter script

### ISSUE THREAD

**Issue by akoserwal** [grpc-ecosystem/grpc-gateway#4410]
## 📚 Documentation
Hi Team, I have created a script which helps set up the grpc-gateway project with a few inputs in a quick manner.

- https://github.com/akoserwal/gen-grpc-gateway-api
- Blog: https://medium.com/p/015759f1e51b

The above script can be added to the documentation or as a reference for quick-start setup guide.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! This is really cool, perhaps it could be added to the [related projects](https://grpc-ecosystem.github.io/grpc-gateway/docs/related_projects/) page? You can contribute the addition yourself by editing this file: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/docs/docs/related_projects.md.
