### ISSUE TITLE
How do I override maxMsgSize?

### ISSUE THREAD

**Issue by fiibbb** [grpc-ecosystem/grpc-gateway#445]
One of my request is getting the following error message:

```
{"error":"grpc: received message larger than max (7696103 vs. 4194304)","code":8}
```

I was able to override the maxMsgSize on the gprc server side. I believe this is due to grpc-gateway uses a client to read the response from the actual grpc server, and that client has a maxMsgSize limit? Is there a hook to override that?

Thanks!

**Comment by paulbdavis** [comment]
I was looking for this same answer and eventually came on this solution, for anyone else looking

```golang
opts := []grpc.DialOption{grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(16777216))}
```

This will set that message size on all calls for that endpoint hndler, not sure if this is the best solution, but it worked for me
