### ISSUE TITLE
recursive inputs for GETs with protoc-gen-swagger stalls program

### ISSUE THREAD

**Issue by heedson** [grpc-ecosystem/grpc-gateway#446]
When a message used for input into a GET request (with annotations) contains a recursive structure, the swagger generation will lock up and get stuck. Here is a simple (albeit useless) snippet of code that can produce the effect:

```
syntax = "proto3";

// Example
//
// Example is a super important central data store used to... store data.
package example;

import "google/api/annotations.proto";

service ExampleStore {
    rpc GetData(Foo) returns (Bar) {
        option (google.api.http) = {
            get: "/api/v1/example/data"
        };
    }
}

message RecursiveMessage {
    RecursiveMessage rec_msg = 1;
}

message Foo {
    RecursiveMessage a_message_use_case = 1;
}

message Bar {
    int64 fizz = 1;
}
```

The command I was running was:
```
protoc ./example/example.proto --swagger_out=logtostderr=true,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types:./ -I/usr/local/include -I./ -I./vendor/github.com/googleapis/googleapis/ -I./vendor/ -I/home/heedson/go/src
```

Interestingly, when `rec_msg` is a `repeated RecursiveMessage` it will once again work.
It will also work if the `option (google...` is changed to a POST.

I'm unsure whether the input to a GET is allowed to be recursive or if it's supposed to graceful exit with an error but irrespective of this, the current implementation does neither.

I believe the problem is at this line https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L112 .

**Comment by achew22** [comment]
That's a really interesting example case. Can you describe to me the how you would expect to be calling this in a get?

Also, just to confirm, protoc is hanging, not the swagger generator?
