### ISSUE TITLE
Configurable AllowUnknownFields in jsonpb?

### ISSUE THREAD

**Issue by lantame** [grpc-ecosystem/grpc-gateway#448]
Now unknown object fields are silently dropped.
If I want to handle such cases, I have to provide a custom unmarshaller (likely by copying all unmarshalling stuff from runtime/marshal_jsonpb.go and changing AllowUnknownFields to false). Isn't it better to make this parameter configurable?

P.S. There will probably be some API change:
type JSONPb jsonpb.Marshaler will likely change to
type JSONPb struct{...} 
Which will require existing code modification.

**Comment by buchanae** [comment]
Does [WithMarshalerOption](https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption) solve your issue? 

We use this to configure a jsonpb.Marshaler the way we like:
```
customMar := jsonpb.Marshaler{
	Indent: "  ",
        EmitDefaults: true,
}
mar := runtime.JSONPb(customMar)
rpcMux := runtime.NewServeMux(runtime.WithMarshalerOption("*/*", &mar))
```

**Comment by buchanae** [comment]
Oh, no, it does not solve your issue. The offending line is here:
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/marshal_jsonpb.go#L114

That unmarhsaler should be configurable. Maybe `run.time.JSONPb.SetUnmarshaler()` should be added?

**Comment by racevedoo** [comment]
@buchanae @Lantame any update on this? I'm having the exact same problem
