### ISSUE TITLE
Add UNIX socket support

### ISSUE THREAD

**Issue by fifthaxe** [grpc-ecosystem/grpc-gateway#451]
Hi all,

What do you think about generating code that would support UNIX socket instead of TCP over loopback for communication between reverse proxy and gRPC server ?
I don't know if this make sense (maybe it could be better to call the gRPC methods directly from the HTTP Handler?) but it would be great to skip TCP overhead in order to decrease latency and CPU usage.

Let me know what do you think about this.

**Comment by achew22** [comment]
Right now I am using grpc gateway with UNIX sockets in a project. Maybe you could document what you've tried and we can work together to figure out what's going on.

**Comment by pmiam999** [comment]
This is an enhancement request to support more options when using protoc with grpc-gateway_out plugin. Beeing able to choose between TCP socket / Unix docker or direct function call for performances purposes.

Taken this proto3 file :  
[car.txt](https://github.com/grpc-ecosystem/grpc-gateway/files/1287874/car.txt)

`protoc -I/usr/local/include -I. ${GOPATHLIST} --grpc-gateway_out=logtostderr=true:. car.proto

This will generate a reverse proxy stub with the following prototype : 

=========================================================
// RegisteCarHandler registers the http handlers for service Car to "mux".                                                                                                                                                                                                                                                                                          
// The handlers forward requests to the grpc endpoint over "conn".                                                                                                                                                                                                                                                                                                         
func RegisterCarHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {                                                                                                                                                                                                                                                                      
    client := NewCarClient(conn)  
...
...
=========================================================

The main issue with current implementation is that this will create a mux that will dial over "conn" to gRPC endpoint using a TCP socket, ie much more overhead than direct executing RPC or using UNIX socket as a transport.

**Comment by achew22** [comment]
Have you tried creating your connection over a unix socket? Untested pseudocode to follow:

```go
conn, err := grpc.Dial(addr, []grpc.DialOption{grpc.WithDialer(net.DialTimeout("unix", addr, timeout))})
// Error handling

s.RegisterCarHandler(ctx, mux, conn)
```
What happens?

It looks like grpc may also support grpc.WithNetwork("unix") which would be even simpler (but wouldn't have support for a timeout).

**Comment by tmc** [comment]
I think this would be a good documentation topic as some folks are
uncomfortable going over loopback.
