### ISSUE TITLE
How to define this restful api using pb?

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#452]
I have a customize response:
```
{
    "code":0,
    "msg":"",
    "data":{
        "response":[
            {
                "key1":1474596715
            },
            {
                "key2":-1
            },
           {
                "........":-1
            }
 
        ]
    }
}
```

The key1, key2, .... are collected in the runtime. I do not know the keys.

**Comment by achew22** [comment]
What have you tried already?

**Comment by vaporz** [comment]
"code", "msg", "data", so familiar to me, lol....  
In your case, I think "json schema" may be helpful.  
You can define "data" as a "string" in pb, but validate the format to its value with "json schema".

**Comment by jinleileiking** [comment]
After 3 hour google , I use struct.proto to solve this f**king problem.

**Comment by vaporz** [comment]
What is " struct.proto"? Any reference? Thanks.

**Comment by jinleileiking** [comment]
https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto

**Comment by vaporz** [comment]
Thanks!
