### ISSUE TITLE
How to get HTTP headers in custom Marshaller?

### ISSUE THREAD

**Issue by tymbaca** [grpc-ecosystem/grpc-gateway#4530]
## 📚 Documentation

I want to send data from client in multipart/form-data. And I want to parse it into proto-object with custom Marshaller.

```go
mux := runtime.NewServeMux(
	runtime.WithMarshalerOption("multipart/form-data", mymarshaller.MyMarshaller{...}),
)
```

But to parse multipart/form-data I need to know the boundary, which is specified inside of Content-Type header: `multipart/form-data; boundary=<BOUNDARY>`

Inside of `NewDecoder(r io.Reader) runtime.Decoder` method I get io.Reader with only request body. At the same time, in debugger I see that io.Reader's underlying byte buffer contains the whole request (with headers), but the offset is set right before the body.

Is there any options to get `r io.Reader` with headers?

**Comment by johanbrandhorst** [comment]
You won't be able to pass headers into the marshaler, but you can combine a custom marshaler with a forwardResponseOption as described in https://github.com/grpc-ecosystem/grpc-gateway/issues/4483#issuecomment-2213672294.
