### ISSUE TITLE
support google.api.HttpBody

### ISSUE THREAD

**Issue by theRealWardo** [grpc-ecosystem/grpc-gateway#457]
I'd like my gateway to understand that I'm returning a `google.api.HttpBody` proto that should be the actual HTTP body of the response.

this ended up not being so easy because of the way the `Content-Type` handling is being done now. In order to do this properly, the following diff is necessary:

```
-       // ContentType returns the Content-Type which this marshaler is responsible for.
-       ContentType() string
+       // ContentType returns the response Content-Type for "v".
+       ContentType(v interface{}) string
```

further, in order to do this I'd propose a new Marshaler that wraps the current `JSONPb` Marshaler. the new Marshaler would be the new default as well as I believe most users want this behavior. does this seem reasonable?

**Comment by achew22** [comment]
I'm going to consolidate this into just the PR #458
