### ISSUE TITLE
How to pass the error 400 in fieldmask if a unknow field is send?

### ISSUE THREAD

**Issue by ldepaulatrac** [grpc-ecosystem/grpc-gateway#4579]
hello, i have a problem right now that i use a patch with n fields, the problem is if the front send a field that is not mapped in the proto i receive a error , a 400,  that is in 
https://github.com/grpc-ecosystem/grpc-gateway/blob/v2.21.0/runtime/fieldmask.go#L51
i know the idea behind a error with a unknown field for fieldmask, but i have some what of just skip this error?

**Comment by johanbrandhorst** [comment]
Hm, unfortunately that function is exported, so we can't make any changes to the signature. If we wanted to support an option to allow unknown fields, we need a separate function that can be called from the generator. I'm not convinced the need is great enough here yet, but it is a possibility in the future. For now, I recommend you disable the field mask handler and handle it manually in your application instead.
