### ISSUE TITLE
google.protobuf.Empty as response serializes to not empty response on REST client depending on request headers

### ISSUE THREAD

**Issue by abraxasjoshuricke** [grpc-ecosystem/grpc-gateway#4583]
## 🐛 Bug Report
We are using protobuf with grpc-gateway for our go application. When returning google.protobuf.Empty we are getting an not empty response. This happens depending on what request headers are being sent.
These two headers in combination result in the faulty behaviour:
'Accept: text/html'
'Content-Type: application/x-www-form-urlencoded'

I debugged pretty deep into the protobuf source code and found out that the fields getting serialized to the response are from the message field 'coderMessageInfo' -> https://github.com/protocolbuffers/protobuf-go/blob/v1.31.0/internal/impl/codec_message.go#L22
Sadly I was not able to figure out where and why these fields are getting serialized.

## To Reproduce
Send a REST request to an endpoint returning google.protobuf.Empty with the following HTTP headers set:
'Accept: text/html'
'Content-Type: application/x-www-form-urlencoded'

## Expected behavior
An empty response, regardless of what headers are being sent.

## Actual Behavior
We get this response:
Flags=3&denseCoderFields=null&initDone=1&isMessageSet=false&needsInitCheck=false&numRequiredFields=0&sema=0&sizeCache=0&state=0&unknownPtrKind=false

## Your Environment
go 1.22,
github.com/grpc-ecosystem/grpc-gateway v1.16.0
github.com/golang/protobuf v1.5.3,
google.golang.org/protobuf v1.31.0,
google.golang.org/grpc v1.59.0,
Linux: alpine 3.19

**Comment by johanbrandhorst** [comment]
Huh, interesting. Are you registering a marshaler for this content type? Could you share a minimal working example?

**Comment by abraxasjoshuricke** [comment]
Thank you for your input. I just saw that we are in fact injecting some custom marshalers deep in our code base. I will debug those and report my findings back.
Thanks!

**Comment by johanbrandhorst** [comment]
Thanks for reporting back! Glad you were able to resolve the issue :).
