### ISSUE TITLE
Path error with oneof submessage field 

### ISSUE THREAD

**Issue by mcos** [grpc-ecosystem/grpc-gateway#460]
When using sub-messages with `oneof` fields, an error arises when a field of the submodel is used in the URL path. This is a particular issue when the `additional_bindings` field of the HTTP options is use.

```proto
message Foo {
  string foo = 1;
  string bar = 2;
}

message Bar {
  string bar = 1;
  string baz = 2;
}

message GetFooRequest {
  oneof sample {
    Foo foo = 1;
    Bar bar = 2;
  }
}

message GetFooResponse {
}

service FooService {
 rpc GetFoo (GetFooRequest) returns (GetFooResponse) {
    option (google.api.http) = {
      post: "/v1/foo/{foo.bar}/"
      body: "*"
      additional_bindings {
          post: "/v1/bar/{bar.baz}/"
          body: "*"
      }
    };
  }
```

The HTTP error received from the following request for the `foo` oneof message:

```
POST /v1/foo/foobarbazstring
{
  'foo': {
    'foo': 'a different string'
  }
}
```

```
{
    "error": "type mismatch, parameter: foo.bar, error: field already set for sample oneof",
    "code": 3
}
```

This doesn't seem like it should return an error, as my expectation is be that the field in the `oneof` message in the body should be set by the corresponding field in the path. If the values are different, I agree it should throw an error. If, however, the value is unset in the body, it should be populated by the path value.

**Comment by achew22** [comment]
When I've had problems like this I find the best way to go about it to put together a little testcase that serializes to JSON and then post that back to the server. Could you try adding a new endpoint that takes an empty message and returns a GetFooRequest with a value set, then post the result to your existing endpoint?
