### ISSUE TITLE
Support explicit omitempty annotation in proto

### ISSUE THREAD

**Issue by MakDon** [grpc-ecosystem/grpc-gateway#4633]
## 🚀 Feature

Support explicit omitempty annotation in proto.

Suppose we have a proto message like:
```proto
message Foo{
  Enum Type{
    enum Foo {
    DEFAULT = 0;
    TYPE1 = 1;
  }
  Type type = 1;
  int num = 2;
}
```
  
And we want to return json without field `type` when `type`=`DEFAULT` for backward compatibility, But we keep `num` un-omitted for a better readibility:

```json
{"num" :0}
```

If we set [`EmitUnpopulated`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) to `true`, `"type": "DEFAULT"` will be emitted. 

If we set `EmitUnpopulated` to `false`, the `num` field would be omitted.

It would be better if we could explicit control this behaviour like:
```proto
message Foo{
  Enum Type{
    enum Foo {
    DEFAULT = 0;
    TYPE1 = 1;
  }
  Type type = 1[omitempty = true];
  int num = 2[omitempty = false];
}
```

**Comment by johanbrandhorst** [comment]
This isn't really feasible as a feature of the gateway. You will have to use a custom marshaler.
