### ISSUE TITLE
Handle empty POST requests 

### ISSUE THREAD

**Issue by chris-rock** [grpc-ecosystem/grpc-gateway#464]
@vjeffrey and I observed some behavior of the POST requests where the body is empty. If I define a new POST endpoint with no body:

```
rpc NewContent (Content) returns (Empty) {
  option (google.api.http) = {
    post: "/content"
  };
};
```

The following request works:

```
http --verify=no POST https://localhost:2000/content
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json
Date: Thu, 21 Sep 2017 16:12:44 GMT
Grpc-Metadata-Trailer: Grpc-Status
Grpc-Metadata-Trailer: Grpc-Message
Grpc-Metadata-Trailer: Grpc-Status-Details-Bin

{}
```

Now, I am going to add body without specific mapping:

```
rpc NewContent (Content) returns (Empty) {
	option (google.api.http) = {
		post: "/content"
		body: "*"
	};
};
```

Now, the parsing fails. 

```
http --verify=no POST https://localhost:2000/content          
HTTP/1.1 400 Bad Request
Content-Length: 24
Content-Type: application/json
Date: Thu, 21 Sep 2017 16:06:48 GMT

{
    "code": 3,
    "error": "EOF"
}
```

Any non-empty body would work. The reason is a missing check for the content length before we start parsing. I propose we are going to add a check like `if req.ContentLength > 0 {}` to https://github.com/grpc-ecosystem/grpc-gateway/blob/1a03ca3bad1e1ebadaedd3abb76bc58d4ac8143b/protoc-gen-grpc-gateway/gengateway/template.go#L207-L211

I am happy to push a PR if you agree with the solution.

**Comment by achew22** [comment]
Can you also add a test that exercises this invariant and I think I'm comfortable with this. @tmc, does that work for you?

**Comment by chris-rock** [comment]
@achew22 sure thing, will do

**Comment by syhpoon** [comment]
Any hope for this to be moved forward? We're also having this issue and it seems to affect any request with empty body (providing the same setup) not only POST.

**Comment by achew22** [comment]
@syhpoon I think all the context that is need is right here. Feel free to send in a PR that does this along with some tests and we can merge it ASAP.

**Comment by syhpoon** [comment]
@achew22 And how were those examplepb/*.pb.go and examplepb/*.pg.gw.go files genereated?
Is there a script somewhere?
That is I want to extend `a_bit_of_everything` service to include the test endpoint for this case but I'd need to re-generate pb files after that.

**Comment by syhpoon** [comment]
Never mind, I found the Makefile
