### ISSUE TITLE
Add default support for proto over http

### ISSUE THREAD

**Issue by MatthewDolan** [grpc-ecosystem/grpc-gateway#465]
Add support for serialized protos to be sent to the http endpoints in addition to json. Use a different content type to differentiate between them.

This requires adding a new marshaller for []byte -> proto.

PR here: https://github.com/grpc-ecosystem/grpc-gateway/pull/459

**Comment by achew22** [comment]
If you want to resurrect that PR, I think I'd be happy to merge it

**Comment by MatthewDolan** [comment]
Re-opened. Thanks.

**Comment by achew22** [comment]
Merged it. Thanks for your contribution!
