### ISSUE TITLE
support trailing slash in url

### ISSUE THREAD

**Issue by dhrp** [grpc-ecosystem/grpc-gateway#472]
We're trying to standardize all our API's to use trailing slashes in the URL's. E.g. `/v1/tasks/` instead of `/v1/tasks`. Now, grpc gateway doesn't seem to support that. If I add a slash in the option I get an error like:

```
--grpc-gateway_out: segment neither wildcards, literal or variable: expected "{" but got "\x00": /v1/queue/
make: *** [all] Error 1
```

Would it be possible to support such scheme?

**Comment by achew22** [comment]
Just for my clarification, I would expect both urls ["/v1/tasks", "/v1/tasks/"] to route given my understandings of the go http server. Are you experiencing something different? Is this mostly about getting the urls defined in proto to be uniform or the client libraries? Could you elaborate a bit more on what doesn't work here.

If you wanted to expand [the parser](https://github.com/grpc-ecosystem/grpc-gateway/blob/0c0b378a74040eeb5ef415c5289258a193be0e94/protoc-gen-grpc-gateway/httprule/parse.go#L150) to handle trailing slashes that also might be a way to approach this.

**Comment by srenatus** [comment]
The same applies to this attempt at a workaround:
``` 
    option (google.api.http).get = "/foo/bar";
        option (google.api.http).additional_bindings = {
          get: "/foo/bar/"
    };
```
the plugin fails with `--grpc-gateway_out: segment neither wildcards, literal or variable: expected "{" but got "\x00": /foo/bar/`

**Comment by torkelrogstad** [comment]
If the issue here is getting `grpc-gateway` to accept paths with a trailing slash as equal to paths without a trailing slash, this HTTP handler can be applied before the gRPC -> REST handler: 

```go
func removeTrailingSlash(h http.Handler) http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if strings.HasSuffix(request.URL.Path, "/") {
			newUrl, err := url.Parse(strings.TrimSuffix(request.URL.String(), "/"))
			if err != nil {
				panic(err)
			}
			request.URL = newUrl
		}

		h.ServeHTTP(writer, request)
	})
}
```

**Comment by MJjainam** [comment]
If there are query params in your URL, you will have to tweak the above function:

```
func removeTrailingSlash(h http.Handler) http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if strings.HasSuffix(request.URL.Path, "/") {
		         request.URL.Path = strings.TrimSuffix(request.URL.Path, "/")
			newUrl, err := url.Parse(request.URL.String())
			if err != nil {
				panic(err)
			}
			request.URL = newUrl
		}

		h.ServeHTTP(writer, request)
	})
}

```
