### ISSUE TITLE
Lack of "google/protobuf/descriptor.proto"

### ISSUE THREAD

**Issue by navygg** [grpc-ecosystem/grpc-gateway#476]
The file "third_party/googleapis/google/api/annotations.proto" line 20: import "google/protobuf/descriptor.proto";

But there is not a directory named "protobuf" under "grpc-gateway/third_party/googleapis/google" and not a file named "descriptor.proto".

Fix suggestion:
create "protobuf" directory under "grpc-gateway/third_party/googleapis/google", and copy "https://github.com/google/protobuf/tree/master/src/google/protobuf/descriptor.proto" to it.

**Comment by achew22** [comment]
This shouldn't be necessary. It is preferable to load those in from the protoc distribution that is where you got your `protoc` from to ensure no versioning issues. In the docs there is the line

```
protoc -I/usr/local/include -I. \
...
```

`/usr/local/include` is where I would expect those protos to live.

Please reopen if you have any more issues :smile:
