### ISSUE TITLE
protoc-gen-grpc-gateway" is a program, not an importable packagego list

### ISSUE THREAD

**Issue by mikeheft** [grpc-ecosystem/grpc-gateway#4766]
## 📚 Documentation
In the [compile-from-source](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/README.md#compile-from-source) part of the README, it says to import `_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"`. But I get an error, albeit just a linting error.

```go
import "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" is a program, not an importable packagego list
Command protoc-gen-grpc-gateway is a plugin for Google protocol buffer compiler to generate a reverse-proxy, which converts incoming RESTful HTTP/1 requests gRPC invocation. You rarely need to run this program directly. Instead, put this program into your $PATH with a name "protoc-gen-grpc-gateway" and run

protoc --grpc-gateway_out=output_directory path/to/input.proto
See README.md for more details.
```

Is this just something to do with the linting setting I may have in VSCode?
These are my vscode `settings.json` for go

```json
"go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.testFlags": ["-v"],
    "go.testOnSave": true,
    "go.testTimeout": "30s",
    "go.enableCodeLens": {
      "runtest": true
    },
    "[go]": {
        "editor.formatOnSave": true, // Enable format on save for Go files
        "editor.tabSize": 2,
        "editor.insertSpaces": true, // Ensure spaces are used instead of tabs
        "editor.codeActionsOnSave": {
          "source.organizeImports": "always"
        },
        "editor.quickSuggestions": {
          "other": true,
          "comments": true,
          "strings": true
        }
    },
```

**Comment by mikeheft** [comment]
I finally pushed this up to my repo and got this error in the github action logs

>Error: tools/tools.go:4:2: import "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" is a program, not an importable package
make: *** [Makefile:33: test] Error 1
Error: Process completed with exit code 2.

**Comment by johanbrandhorst** [comment]
Are you using an underscore import as detailed in the docs? It's using the tool dependency pattern, you can't just import the package itself. The build tag is used to stop it from being built. I would recommend copying the example completely and reading more about tool dependencies (there is a link in the docs). I'm going to close this, but let me know if you need more help.

**Comment by mikeheft** [comment]
@johanbrandhorst , I did afaict. This was from a golang udemy course I was following, so I'm still super new to golang 😅 
I'll read more from the docs too, 😄 

```go
//go:build tools

package tools

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2"
	_ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
	_ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
```

**Comment by mikeheft** [comment]
Ok So I think it either has something to do with a step that I either missed or the video course omitted. I followed the steps again and it was still giving the error. But looking more closely at the steps it had the `tools.go` not in a sub directory, but instead in the root. I did that and the errors went away 🤦

**Comment by johanbrandhorst** [comment]
Glad you hear you got it working!
