### ISSUE TITLE
Support JSON-RPCv2

### ISSUE THREAD

**Issue by stevenroose** [grpc-ecosystem/grpc-gateway#477]
The tagline of the project says gRPC to JSON proxy. However, "JSON" is just a data format. Somehow a RESTful service is created instead of using an existing JSON-based RPC protocol, i.e. JSON-RPC (v2).

What is the motivation of this decision? Why not support JSON-RPC instead of REST?

**Comment by AlekSi** [comment]
That would be a totally different project.

**Comment by stevenroose** [comment]
@AlekSi I realize that. Just curious why REST was chosen? REST (being resource-centric) and RPC are fundamentally different. JSON-RPC defines a JSON & HTTP-based RPC protocol, why wasn't it picked over REST?

**Comment by achew22** [comment]
The decision was to implement the [gRPC http spec](https://cloud.google.com/service-management/reference/rpc/google.api#http) which is a standard part of gRPC implemented by several projects in the same way ([Envoy](https://www.envoyproxy.io/envoy/configuration/http_filters/grpc_json_transcoder_filter), [grpc-httpjson-transcoding](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding), [grpc-jersey](https://github.com/fullcontact/grpc-jersey), and in the paid product side [Cloud Endpoints for gRPC APIs](https://cloud.google.com/endpoints/docs/grpc/about-grpc)). Deviating from the standard would make us incompatible with a wide swath of the gRPC ecosystem.

**Comment by achew22** [comment]
I'm going to close this since it seems to be stuck. If you have any more issues, please reopen/make a new one.
