### ISSUE TITLE
Best practices for handling decode failures in a websocket connection

### ISSUE THREAD

**Issue by ianbbqzy** [grpc-ecosystem/grpc-gateway#4795]
## 📚 Documentation

(A clear and concise description of what the issue is.)

I wasn't able to find any documentation around handling decoding failures. I'm new to GRPC ecosystem and we have a GRPC server that needs to accept requests from clients that don't use GRPC. often times, our clients do not follow the best practices of GRPC and send invalid requests. such as

```
2024/10/02 11:02:05 ERROR: Failed to decode request: proto: (line 1:14): invalid google.protobuf.Timestamp value "2024-10-02T11.02.05.5880000Z"
2024/10/04 13:43:29 ERROR: Failed to decode request: proto: (line 1:190): invalid google.protobuf.Duration value "1.541S"
```

This a developer error but the problem I'm running into is that there is no easy way for us to communicate with our clients of these issues. As a results, these requests just get dropped in our websocket streaming connection and never reach our GRPC servers. So everytime, this happens, we can only retroactively inform our users of these issues.

Any advice on this issue would be greatly appreciated!

**Comment by johanbrandhorst** [comment]
Hi, this isn't really the right forum for this, as we don't manage the decoder. You either want to ask in https://github.com/grpc/grpc-go or maybe https://github.com/protocolbuffers/protobuf-go. If you are using this software though, you might be interested in the custom error handler documentation: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#error-handler.

**Comment by ianbbqzy** [comment]
Hi Johan, thanks for the response. I dug a little deeper and I think the issue can be remedied in this repo at https://github.com/grpc-ecosystem/grpc-gateway/blob/26f25a953793949c1949ccb874cfd70f42abd3e9/protoc-gen-grpc-gateway/internal/gengateway/template.go#L466

If I understand correctly, the decode error is logged but not exposed to the caller. What do you think? I can submit a pull request to do so if that makes sense to you. Also if you agree, I can also open a new feature request or bug report. Let me know if I'm missing something that prompted the original authors to handle the error the current way intentionally. Thanks!

**Comment by johanbrandhorst** [comment]
Sorry, I'm confused. I only just noticed that you were talking about websocket connections. Are you using the https://github.com/tmc/grpc-websocket-proxy to perform bidirectional streaming in the gateway? The gateway doesn't natively support websockets, and as you noticed bidirectional streaming is pretty poorly supported. I'm happy to review a PR if you think you can make something work though.

**Comment by ianbbqzy** [comment]
correct that we are using https://github.com/tmc/grpc-websocket-proxy

**Comment by jimmyd-sudo** [comment]
Hi @johanbrandhorst do you happen to still have link to details on the bug that the PR's introduced/how to reproduce it?

**Comment by johanbrandhorst** [comment]
I'm not sure what you're asking? Introduced what?
