### ISSUE TITLE
HTTP response is not correct json encoded if the grpc return stream of objects.

### ISSUE THREAD

**Issue by lingwangsj** [grpc-ecosystem/grpc-gateway#481]
I run the examples, then:
POST http://{{host}}:{{port}}/v1/example/a_bit_of_everything/bulk with payload {"uuid": "1234"}.

after that I run
GET http://{{host}}:{{port}}/v1/example/a_bit_of_everything the http response is {"result": {"uuid":"7d96031c1eaeffa392245718677778755db9c0f267b66a75"}}, everything is great.

then I do another POST
POST http://{{host}}:{{port}}/v1/example/a_bit_of_everything/bulk with payload {"uuid": "abcd"}.

now the GET return
{"result":{"uuid":"7d96031c1eaeffa392245718677778755db9c0f267b66a75"}}{"result":{"uuid":"7e96031c1eaeffa392245718677778755db9c0f267b66a75"}}

the response body is no longer a valid JSON string.

**Comment by achew22** [comment]
Can you tell me if reverting https://github.com/grpc-ecosystem/grpc-gateway/commit/b0be3cdef0ed27e3c420795e2efbfe9c27e839cc fixes the problem?

**Comment by lingwangsj** [comment]
After reverting the line in the runtime/handler.go, I got response with a new line between two results like this. It is still not a valid JSON string. 
{"result":{"uuid":"0f41e1059fafe87988473bd1531f5749feff4b019fa4e248"}}
{"result":{"uuid":"0c41e1059fafe87988473bd1531f5749feff4b019fa4e248"}}

**Comment by achew22** [comment]
Could you describe the process you used to run the examples?

**Comment by lingwangsj** [comment]
I ran into this issue with my own grpc server and grpc gateway server. Then I want to find out whether the issue was caused by my own code. So I checked the example and I found the stream.proto has the same API pattern as my service. So this is what I did.

I did the three go get commands mentioned in the readme

go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
go get -u github.com/golang/protobuf/protoc-gen-go

I run the example grpc server using command:
/usr/local/go/bin/go run /home/ling/Projects/go/src/github.com/grpc-ecosystem/grpc-gateway/examples/server/cmd/example-server/main.go

I run the proxy using command:

/usr/local/go/bin/go run /home/ling/Projects/go/src/github.com/grpc-ecosystem/grpc-gateway/examples/main.go

**Comment by lingwangsj** [comment]
I actually run make, then restarted the grpc server and the proxy. now I got empty response. (with the runtime/handler.go changes I made before.

**Comment by achew22** [comment]
This is very strange. When I'm running this on my desktop I don't have this problem. Can you try running the e2e test that is in the Makefile?

**Comment by lingwangsj** [comment]
Could you tell me how to run the e2e test?

**Comment by achew22** [comment]
You can use the `.travis.yml` files as a guide. Run the operations in the script and before-script section

https://github.com/grpc-ecosystem/grpc-gateway/blob/b0be3cdef0ed27e3c420795e2efbfe9c27e839cc/.travis.yml#L25-L32

**Comment by lingwangsj** [comment]
I followed the steps, after resolved few dependency issues, the test run without any failure. for what is worth, I am using "go version go1.9 linux/amd64" and centOs7.

**Comment by achew22** [comment]
So I'm rereading this now looking for additional clues. Is the bug is state dependent and only fails on the 2nd `GET` request?

**Comment by lingwangsj** [comment]
When there is only one record, the HTTP response payload is a good json format like this:

{"result": {"uuid":"7d96031c1eaeffa392245718677778755db9c0f267b66a75"}}

the moment I added more record, and there are multiple items  returns via the stream gRpc API, the HTTP response payload is invalid. does not matter the record count is 2 or 3 or more, like this:
{"result":{"uuid":"7d96031c1eaeffa392245718677778755db9c0f267b66a75"}}{"result":{"uuid":"7e96031c1eaeffa392245718677778755db9c0f267b66a75"}}

**Comment by achew22** [comment]
I think this should be resolved now. Can you try it out? I'm going to preemptively close it but if you continue to have problems please reopen.
