### ISSUE TITLE
error:protoc-gen-grpc-gateway: program not found or is not executable

### ISSUE THREAD

**Issue by AyushSisodiaRZP** [grpc-ecosystem/grpc-gateway#4829]
protoc \
    --go_out=system_proto \
    --go_opt=paths=source_relative \
    --go-grpc_out=system_proto \
    --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=:system_proto \
    payments.proto
protoc-gen-grpc-gateway: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.

Facing the above error while running the proto command. 

output of which protoc-gen-grpc-gateway is follows
>protoc-gen-grpc-gateway not found

When I execute the following command
>ls -l ~/go/bin

I can see the protoc-gen-grpc-gateway file present. How do I update the path correctly? Currently, GOPATH, GOROOT, and GOBIN are empty.

**Comment by johanbrandhorst** [comment]
You need to add `~/go/bin` to your PATH variable with something like `export PATH=$PATH:~/go/bin` in your `~/.bashrc`.
