### ISSUE TITLE
bug: uncapitalized service name causes runtime error unknown function in service.pb.gw.go

### ISSUE THREAD

**Issue by thurt** [grpc-ecosystem/grpc-gateway#484]
see title.

Steps to reproduce:

1. define a service with a name that has a lowercase first letter in your `service.proto`
1. generate the `service.pb.go` (notice that the generated code includes `func NewNameClient` -- it is capitalized `Name`)
1. generate the `service.pb.gw.go` (notice that the generated code attempts to call `NewnameClient` -- uncapitalized `name` which leads to the runtime error)

this looks similar to #300 and looks like it could be fixed in the same way.

the style guide, https://developers.google.com/protocol-buffers/docs/style, says you should capitalize service names, but seems it does not say it requires capitalized. So i think this is a valid bug

**Comment by achew22** [comment]
I think you're totally correct. This would be a nice contribution for a first timer. I'll even point you to the appropriate code if you want :wink:
