### ISSUE TITLE
When using go templates to customize OpenAPI output, where is the information about the parameters passed into the go template (markdown)?

### ISSUE THREAD

**Issue by hy911** [grpc-ecosystem/grpc-gateway#4841]
## 📚 Documentation
[[grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway/tree/main)/[examples](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/examples)/[internal](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/examples/internal)/[proto](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/examples/internal/proto)/[examplepb](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/examples/internal/proto/examplepb)
/use_go_template.proto
(A clear and concise description of what the issue is.)
](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#using-go-templates-in-proto-file-comments)

**Comment by johanbrandhorst** [comment]
The logic for this can be found in this file: https://github.com/grpc-ecosystem/grpc-gateway/blob/69459a5ffd70a509e01647e5394e369eb4468095/protoc-gen-openapiv2/internal/genopenapi/template.go#L2528-L2562.
