### ISSUE TITLE
Part Body post double pointer

### ISSUE THREAD

**Issue by owenhaynes** [grpc-ecosystem/grpc-gateway#485]
If converting the body to part of a message a double pointer is produced which causes the following error
```json
{"error":"unexpected type **Foo does not implement proto.Message","code":3}
```
google.api.http says it is possible.

Example 
```
    rpc CreateResourceType(CreateFoo) returns (FooRes) {
        option (google.api.http) = {
            post: "/v1/foo"
            body: "foo"
        };
    }


message CreateFoo {
  Foo foo = 1;

}

message FooRes {
}

message Foo {
  string id = 1;
}

```

**Comment by achew22** [comment]
What version of protoc are you using? What version of grpc-gateway are you using? Have you made any local modifications to any thing?

**Comment by owenhaynes** [comment]
Using 1.3 of grpc.
Using gogo protoc latest version

**Comment by achew22** [comment]
gRPC 1.3 was released on Apr 28. Could you try upgrading to 1.7.3 (released 2 days ago)
Could you try it with the regular golang protobuf compiler?

**Comment by owenhaynes** [comment]
sorry 1.3 of grpc-gateway should of had my morning coffee and v1.7.3 of grpc.

Will try with regular compiler. Only using gogo proto for the better time support.

**Comment by owenhaynes** [comment]
Ok same problem with normal protobuf compiler latest version.

looks to be to do with the double pointer being generated in the gateway code, and the decoder fails to 

```
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Foo); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

```

**Comment by achew22** [comment]
Is that code sample from the generated code? I'm pretty confused by that error, I don't really know what would be causing this. Do you have a custom marshaller installed maybe? Can you try installing a custom marshaller? Is there any indication where the error is coming from specifically?
