### ISSUE TITLE
Path params generated with `expand_slashed_path_patterns=true` have type `number`

### ISSUE THREAD

**Issue by czabaj** [grpc-ecosystem/grpc-gateway#4865]
## 🐛 Bug Report

This is a follow-up to the issue https://github.com/grpc-ecosystem/grpc-gateway/issues/4784 (closed PR https://github.com/grpc-ecosystem/grpc-gateway/pull/4813) - the path parameters generated with the `expand_slashed_path_patterns=true` compiler option have an OpenAPI type `type: number` with `format: double`.

## To Reproduce

Have a protobuf definition with Google AIP style path parameters, e.g. 

```proto
rpc GetBook(GetBookRequest) returns (Book) {
  option (google.api.http) = {
    get: "/v1/{name=publishers/*/books/*}"
  };
}
```

and enable the new  `expand_slashed_path_patterns=true` compiler option (not yet released).

When you generate the OpenAPI file from this, it will generate

```JSON
{
 "/v1/publishers/{publisher}/books/{book}": {
      "get": {
        "parameters": [
          {
            "name": "publisher",
            "in": "path",
            "required": true,
            "type": "number",
            "format": "double"
          },
 {
            "name": "book",
            "in": "path",
            "required": true,
            "type": "number",
            "format": "double"
          },
        ]
      }
    }
}
```

The path parameters `publisher` and `book` are inferred from the proto pattern, but their type is `number` - it should be a `string`.

## Expected behavior

The path parameters generated when expanding the path pattern should have a type of `string`.

## Actual Behavior

The path parameters generated when expanding the path pattern have a type `number` with format `double`.

**Comment by austingebauer** [comment]
Thanks. Also looking for this to land in a release soon!

**Comment by johanbrandhorst** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.23.0 has been released!
