### ISSUE TITLE
Appengine Standard Environment: "not an Appengine context"

### ISSUE THREAD

**Issue by buchanae** [grpc-ecosystem/grpc-gateway#487]
I have an existing API built with grpc-gateway that I'd like to serve in the Appengine Standard Environment. For this app, the benefits of the standard env. outweigh the flexible env. significantly.

Using the Appengine dev server, I get errors like `panic: not an App Engine context`. As far as I can tell, there's no good way to allow application code to create this context and get it into the grpc handlers. I've tried hacking around in the generated grpc-gateway code, injecting `appengine.WithContext` manually, but I can't seem to find the right place where both the request and context are available. It also seems like the Appengine context needs to be created on the grpc-server-side.

I wonder if #46 is the right solution. Seems like that issue was closed because the amount of work needed seemed overwhelming, but not because it was a bad idea.

**Comment by achew22** [comment]
With the submission of #454 I think this might be possible since you can control the handler. Note that you will *NOT* have interceptor support. Beyond that I think all the pieces are there. Please report back with your findings if you have any. Closing since this should be possible.
