### ISSUE TITLE
Map of list

### ISSUE THREAD

**Issue by mavle** [grpc-ecosystem/grpc-gateway#493]
Hello, I have a bit of an oddball inquiry. I am wanting to model:
```json
{
  "http": {
    "/mypath": [
      {
        "action": "GET",
        "requestAttributes": {
          "query": {
            "user": "*"
          }
        }
      }
    ]
  }
}
```
Which is a map of arrays. Proto3 doesn't support repeated values in maps so they force a message wrapper. i.e.
```proto
message Request {
  map<string, RouteArray> http = 6;
}

message RequestAttributes{
  map<string, string> headers = 1;
  string ip = 2;
}

message RouteArray {
  repeated RoutePolicy routePolicies = 1;
}

message RoutePolicy {
  string actions = 1;
  RequestAttributes requestAttributes = 2;
}
```
This is unfortunate as its passed to the user in a bad form. I'm curious if you all would allow a PR for some sort of annotation that would flatten the nested message into a map of arrays?

**Comment by achew22** [comment]
If you want to go about this I think the correct place to do it would be in http://github.com/google/protobuf. We don't control the spec for JSONification of protos so I think this is not the correct abstraction layer for that code.
