### ISSUE TITLE
Backwards incompatible change to chunked encoding

### ISSUE THREAD

**Issue by jacksontj** [grpc-ecosystem/grpc-gateway#495]
Recently we attempted to update our dependency on grpc-gateway, but after doing so we noticed that streamed responses where no longer formatted the same on the response. Previously each chunk had a newline at the end, so the clients would simply buffer until a newline, then decode a chunk. After digging into the code it seems that this was changed in b0be3cdef0ed27e3c420795e2efbfe9c27e839cc -- without much explanation as to why.

The entire commit message is `runtime: fix chunk encoding` -- which is confusing since it doesn't reference an issue or anything else. At this point this breaks all my clients (meaning I have to remain on an older version) and I'm not even sure this is a change we'd want (as it makes client implementations a bit more of a pain).

I attempted to find an issue explaining the reasoning, but was unsuccessful. IMO that commit should be reverted (although I'd keep the test-- just change it). But if there was a reason to make this change I'd like to understand why.

**Comment by achew22** [comment]
What marshaller are you using? Does it implement the Delimiter interface?

**Comment by jacksontj** [comment]
From looking more in the code it seems that if the json marshaller doesn't implemented the delimited interface it defaults to *no* delimiter (https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/handler.go#L41) which seems wrong. My expectation would be the default would be a newline (as defined in documentation, and the behavior of previous releases) and if the user wanted to have something else (such as no-delimiter) they'd implement the interface.

**Comment by jacksontj** [comment]
I've submitted a PR which maintains the new interface, but keeps it backwards compatible.
