### ISSUE TITLE
Timestamps in year 0000 are accepted as query parameters

### ISSUE THREAD

**Issue by jakec-github** [grpc-ecosystem/grpc-gateway#4967]
## 🐛 Bug Report

Affects APIs with a `google.protobuf.Timestamp` field on a GET request.

When `grpc-gateway` parses the timestamp query parameter it does return an error for dates in the year 0. This is inconsistent with the behavior described in the [well known type test](https://github.com/protocolbuffers/protobuf-go/blob/30f628eeb303f2c29be7a381bf78aa3e3aabd317/types/known/timestamppb/timestamp_test.go#L26) and with the behavior implemented in protojson.

Parsing of the timestamp field is done [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/query.go#L289)

I am happy to submit a fix and include tests for min/max timestamp if this bug is considered an issue.

Seen in `v2.19.1`

## To Reproduce

1. Define an API that uses `google.protobug.Timestamp` as a field on a GET request
1. Make the request with `0000-01-01T00%3A00%3A00.00Z`
1. See that this does not cause an error

## Expected behavior

Should return a 400 Bad Request error

## Actual Behavior

Request is accepted

## Your Environment

N/A

**Comment by johanbrandhorst** [comment]
Thanks for the issue, that does seem wrong! Should we perhaps just add a `t.IsValid()` check after the creation of the type? Would be happy to see a PR.

**Comment by jakec-github** [comment]
Thanks for merging! Will there be a patch release with this fix?

**Comment by johanbrandhorst** [comment]
Yeah we've had a bunch of changes in the last week, I'll tag a release soon!
