### ISSUE TITLE
Struggling using different marshallers

### ISSUE THREAD

**Issue by WscriChy** [grpc-ecosystem/grpc-gateway#499]
I am trying to use different marshallers, not even writing new myself, but using the existing Proto marshaller. However, I am sure it is very simple few lines of code, however there are no tutorials or examples. Adding one two examples would be a great asset to the project.

**Comment by achew22** [comment]
Could you put together some information on things you've tried? Maybe together we could create the tutorial/examples that you would have needed. What do you think of that?
