### ISSUE TITLE
Support bytes fields in path parameter

### ISSUE THREAD

**Issue by yugui** [grpc-ecosystem/grpc-gateway#5]
Should decode percent encoding to support bytes fields

**Comment by IceMan81** [comment]
@yugui Are oneofs supported?

**Comment by yugui** [comment]
@IceMan81 good point.  Since the API of oneof in go protobuf has changed, we need to care of that too.

**Comment by IceMan81** [comment]
@yugui Explains why it didnt work when I tried a oneof today; code generation ran without any errors, but the gateway code was unable to map the request params to the protobuf fields.

**Comment by tschottdorf** [comment]
This issue is referenced from the README as covering `enum` support, which isn't mentioned here. It should be added or filed as a new issue so that it doesn't get lost.
