### ISSUE TITLE
Cut a minor release for https://github.com/grpc-ecosystem/grpc-gateway/issues/495

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#506]
Release 1.3.0 has a small bug in the streaming responses in that the delimiter is no longer kept when the marshaller doesn't implement the delimiter interface. This was fixed in https://github.com/grpc-ecosystem/grpc-gateway/pull/497, and I'd appreciate a minor version bump with this fix included.

**Comment by tmc** [comment]
Release 1.3.1 has been tagged.
