### ISSUE TITLE
protoc-gen-swagger not using description field of info swagger object

### ISSUE THREAD

**Issue by lukasmalkmus** [grpc-ecosystem/grpc-gateway#511]
`protoc-gen-swagger` is not respecting the `description` field of the `info` object. While the field is present in the implementation [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/8cc3a55af3bcf171a1c23a90c4df9cf591706104/protoc-gen-swagger/options/openapiv2.proto#L78) and [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/8cc3a55af3bcf171a1c23a90c4df9cf591706104/protoc-gen-swagger/genswagger/types.go#L22) its usage is not implemented. I think this bit might be missing [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/4af01107cac728413c31cfa9c2c97240633d5f9b/protoc-gen-swagger/genswagger/template.go#L719).

Am I missing something or is this just a simple bug?

EDIT: Noticed the above is also true for the `terms_of_service` field.

**Comment by tmc** [comment]
Thank you for this report. These both appear to be simple omission bugs. Do you think you could write a small patch for this?

**Comment by lukasmalkmus** [comment]
#512

**Comment by tmc** [comment]
Thanks. Will review.

**Comment by tmc** [comment]
Thanks for your contribution.
