### ISSUE TITLE
1.3.1 Breaks backward compatibility by renaming generated files.

### ISSUE THREAD

**Issue by domgreen** [grpc-ecosystem/grpc-gateway#516]
It looks like there has been a breaking change in `1.3.1` that now changes the name of the generated files in the `protoc-gen-grpc-gateway/gengateway/generator.go Generate` function.

Commenting out [this line](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/gengateway/generator.go#L82) correctly generates the file with the name / location as it was prior to `1.3.1`.

If I inspect the `name` and `output` variables with the line commented out I get what I expect e.g. prior to 1.3.1:

```
name: base/serverstatus.proto output: base/serverstatus.pb.gw.go
``` 

Adding the line back in overrides `name` and ends up with:

```
name: improbable.io/proto/base/serverstatus.proto output: improbable.io/proto/base/serverstatus.pb.gw.go
```

I have tried adding a combination of different `options go_package` to get around this but does not seem to help revert the name or location of the file to be as it was prior to the change.

How do you propose that I work around this?

**Comment by tmc** [comment]
@domgreen thanks for your report. If that was changed between 1.3.0 being tagged and 1.3.1 then it should not have been included in the point release.

**Comment by achew22** [comment]
My understanding of `option go_package` is that it should end up in `file.GoPkg.Path` appended with the filename. What happens if you set `option go_package = "improbable.io/proto/base";`?
