### ISSUE TITLE
add support for the google.api.HttpBody proto as a request

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#528]
My request is:

curl http://xxx.xxx -d "id=aaaa&starttime=111"

**Comment by jinleileiking** [comment]
https://github.com/googleapis/googleapis/blob/master/google/api/httpbody.proto

**Comment by jinleileiking** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/pull/458/commits/136b1437c1d20758a28765ee4736ce8e3bbefeba

**Comment by jinleileiking** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/pull/458

**Comment by theRealWardo** [comment]
I think your request is actually a dupe of #7

**Comment by jinleileiking** [comment]
@theRealWardo Your code does not show where does the code put in. https://github.com/jinleileiking/grpc-gateway/commit/bb153b3f2cfcdb086b39bdc2edbbc9216951eb97 
I put to the right place

**Comment by jinleileiking** [comment]
@yugui @tmc Is it the good way to finish this feature?

My solustion seems not good. Any advice?
