### ISSUE TITLE
Incorrect error message when execute protoc-gen-grpc-gateway to HTTP GET method with BODY

### ISSUE THREAD

**Issue by budougumi0617** [grpc-ecosystem/grpc-gateway#531]
I try to compile by protoc-gen-grpc-gateway the below definition to generate reverse-proxy file.

```yaml
service TaskManager {
  rpc GetTask (GetTaskRequest) returns (Task) {
    option (google.api.http) = {
       get: "/v1/tasklist-gateway/task/{id}" // "id" is defined in GetTaskRequest
       body: "*"
    };
  }
}

message GetTaskRequest {
  int32 id = 1;
}
```

protoc returns error with below text.

**needs request body even though http method is GET: GetTask**

```bash
protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --grpc-gateway_out=logtostderr=true:. proto/task_list.proto
--grpc-gateway_out: needs request body even though http method is GET: GetTask
```

However, solution for the error is remove body statement.

```
  rpc GetTask (GetTaskRequest) returns (Task) {
    option (google.api.http) = {
       get: "/v1/tasklist-gateway/task/{id}" // "id" is defined in GetTaskRequest
    };
  }
```

I think HTTP GET request should not include BODY. It it correct error text?

# Detail

Related implementation codes are below.

https://github.com/grpc-ecosystem/grpc-gateway/blob/5e029d0af7129901db06b2803fc874e480f9215c/protoc-gen-grpc-gateway/descriptor/services.go#L75-L79
```go
		case opts.GetGet() != "":
			httpMethod = "GET"
			pathTemplate = opts.GetGet()
			if opts.Body != "" {
				return nil, fmt.Errorf("needs request body even though http method is GET: %s", md.GetName())
			}
```
It seems "if statement" validates that request body has no string, but error text is recommending set the request body. Also, I think DELETE method has same issue.
https://github.com/grpc-ecosystem/grpc-gateway/blob/5e029d0af7129901db06b2803fc874e480f9215c/protoc-gen-grpc-gateway/descriptor/services.go#L89-L94
```go
		case opts.GetDelete() != "":
			httpMethod = "DELETE"
			pathTemplate = opts.GetDelete()
			if opts.Body != "" && !r.allowDeleteBody {
				return nil, fmt.Errorf("needs request body even though http method is DELETE: %s", md.GetName())
			}
```

And, I created below pull request for this issue.
[https://github.com/grpc-ecosystem/grpc-gateway/pull/532](https://github.com/grpc-ecosystem/grpc-gateway/pull/532)

 I would appreciate it if you could check this issue, and PR.

**Comment by achew22** [comment]
Thank you for your thorough issue report and pull request. The behavior you specified is indeed incorrect. Sorry about that. I've merged your PR and you shouldn't have that sort of problem again.

Thanks so much for contributing!

**Comment by lixin9311** [comment]
I think we should reconsider this issue.

FYI, https://stackoverflow.com/questions/978061/http-get-with-request-body

Any HTTP request message is allowed to contain a message body.

Although it's not a common way, at least provide an option for it, like DELETE.

**Comment by johanbrandhorst** [comment]
Maybe I can help you fix this issue without adding GET body parsing. What problem are you having? Feel free to drop by #grpc-gateway on the Gophers slack https://invite.slack.golangbridge.org/.
