### ISSUE TITLE
grpc-gateway_out: unexpected token "{" after segments "posts/slug={slug}"

### ISSUE THREAD

**Issue by thurt** [grpc-ecosystem/grpc-gateway#534]
see title for error.
I am getting this error when trying to use protoc with `--grpc-gateway_out` and `--swagger_out`

some example:
```
// example.proto
message PostBySlugRequest {
    string slug = 1;
}

rpc GetPostBySlug(PostBySlugRequest) returns (Post) {
    option (google.api.http) = {
        get: "/posts/slug={slug}"
    }
}
```
The offensive code is `"/posts/slug={slug}"`

here is where the error is being generated from https://github.com/grpc-ecosystem/grpc-gateway/blob/0c0b378a74040eeb5ef415c5289258a193be0e94/protoc-gen-grpc-gateway/httprule/parse.go#L110

as far as im aware, this should be valid syntax, `/slug={slug}`, although i don't think its very prevalent. i have found this discussion https://stackoverflow.com/a/9743414/3072751 which espouses some of its benefits.

i have confirmed that [editor.swagger.io](http://editor.swagger.io) considers this valid syntax
```yaml
swagger: '2.0'
info:
  title: test
  version: version not set
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts/slug={slug}:
    get:
      operationId: GetPostsBySlug
      responses:
        '200':
          description: "test"
          schema:
            $ref: '#/definitions/Post'
      parameters:
        - name: slug
          in: path
          required: true
          type: integer
          format: int64
definitions:
  Post:
    type: object
    properties:
      id:
        type: integer
        format: int64
```

a simple workaround is to specify the resource path with an extra path segment like, `/posts/slug/{slug}` instead which prevents the error from occurring

**Comment by yugui** [comment]
Sorry for the confusing error message. But I don't think `/posts/slug={slug}` is a valid syntax because a segment can be either a wildcard, a `LITERAL` or a `VARIABLE`.
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/third_party/googleapis/google/api/http.proto#L214
