### ISSUE TITLE
import_path option not working as intended

### ISSUE THREAD

**Issue by shynie** [grpc-ecosystem/grpc-gateway#536]
This option doesn't work the same way it does with protoc-gen-go. The latter has option `M` that allows us to associate a set of *.proto files with package given in import_path, so all of the generated *.go files will have the same package name.

>Mfoo/bar.proto=quux/shme - declares that foo/bar.proto is associated with Go package quux/shme. This is subject to the import_prefix parameter.

protoc-gen-grpc-gateway should support that option too. Now importh_path only changes the path but doesn't affect package names.

**Comment by achew22** [comment]
@shynie, thanks for the bug report!

Unfortunately, I'm not at all familiar with the argument you're attempting to use. Do you think you could point to some documentation that has more information? Additionally it would be extremely helpful if you could write a test that demonstrates this failure. With that it will be a lot easier to figure out what next steps should be.
