### ISSUE TITLE
autoreconf not found

### ISSUE THREAD

**Issue by karysto** [grpc-ecosystem/grpc-gateway#549]
What happened:
I expected the installation as described on the repo installation section to install grpc-gateway

What occurred:
Following the installation instructions on the repo homepage, I got the error below
```
mkdir tmp
cd tmp
git clone https://github.com/google/protobuf
cd protobuf
./autogen.sh
./configure
make
make check
sudo make install
```

When running the `autogen.sh` script, I get the following error:
```
$ ./autogen.sh
+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 50: ./autogen.sh: autoreconf: not found
```

Tried looking for a package called autoreconf, but doesn't seem to exist. Anything I'm missing for the installation?

OS: Ubuntu 16.04
Protoc version: 3.5.1

**Comment by achew22** [comment]
It looks to me like you're trying to compile protoc. If you want help with that project I would request you file a bug against that project. Best of luck and when you start using the gateway of you have any issue don't hesitate to file another bug
