### ISSUE TITLE
Can you differentiate between an empty map vs field not provided?

### ISSUE THREAD

**Issue by Ianwww** [grpc-ecosystem/grpc-gateway#552]
With this proto definition
```
 message UpdateMessage {
    string id = 1;
    map[string]string my_map = 2;
 }

 service YourService {
  rpc Echo(UpdateMessage) returns (StringMessage) {
    option (google.api.http) = {
      patch: "/update"
      body: "*"
    };
  }
 }
``` 

I'd like to send a request like 
`{"id":"myid","my_map":{}}`
and set MyMap to an empty map.  

Is this possible?  Currently, when this field is provided, my service thinks this field is unset(MyMap==Nil).  I'm working in golang.

**Comment by achew22** [comment]
I, unfortunately, am not as expert with protos as I probably should be, but I don't believe there is a easy way to do that that doesn't involve fieldmasks which we don't currently support. That said there is some interest in implementing that in the gateway. Would you be interested in taking that sort of project on?

**Comment by Ianwww** [comment]
thanks for the response.  I had to move forward and use a wrapper around a map to handle this.  I'm not going to be able to work on this with my present workload.

**Comment by johanbrandhorst** [comment]
You have to use field masks. This will be automatically supported with #671.

**Comment by mayank-dixit** [comment]
> With this proto definition
> 
> ```
>  message UpdateMessage {
>     string id = 1;
>     map[string]string my_map = 2;
>  }
> 
>  service YourService {
>   rpc Echo(UpdateMessage) returns (StringMessage) {
>     option (google.api.http) = {
>       patch: "/update"
>       body: "*"
>     };
>   }
>  }
> ```
> I'd like to send a request like
> `{"id":"myid","my_map":{}}`
> and set MyMap to an empty map.
> 
> Is this possible? Currently, when this field is provided, my service thinks this field is unset(MyMap==Nil). I'm working in golang.

Use this maybe: https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/StringValue
