### ISSUE TITLE
Support for 'Any' protobuf type?

### ISSUE THREAD

**Issue by maciejj04** [grpc-ecosystem/grpc-gateway#554]
Hi,

As far as i understand, plugin should support 'Any' protobuf message type. The thing is that at the moment when my application returns response which contains optional Any type field (that contains simply ByteString) to proxy app (which translates REST call to grpc), it returns 500 - internal server error with { "code": 2  } or "unknown message type \"\'"". The problem appears only when response from my service contains some informations in that field. Any idea why this is happening? Or did I misunderstood current capabilities of the plugin?

**Comment by achew22** [comment]
Maybe you could elaborate a bit more on what you're trying to do along with some sample code. I don't think I have enough context to understand what is going on just yet.

**Comment by maciejj04** [comment]
I got a request which contains - among other fields - boolean flag. If this flag is passed with 'true' value, it forces grpc service to return some additional data. This 'data' is in form of Any protobuf type. So when I send a request with this flag appended and as a result additional data is present in mentioned field (of protobufs type 'Any') of service response, rest-grpc-proxy app returns error mentioned in my previous post. Ofc.,  in case when request does not contain flag, response is returned properly.

**Comment by maciejj04** [comment]
Also I've noticed that ByteString returned in response from service is not returned as String from grpc-proxy app. Is that proper behaviour?
Example use case mentioned in above posts:
.proto definitions:
message ListRQ {
  ObjAtId ObjAId= 1;
  bool addContent = 2;
}
message DomainItem {
  int64 ObjectId = 1;
  Pic Pic = 2;
  int64 timestamp = 3;
  google.protobuf.Any Content = 4;
  bool inWork = 5;
}
So, as I've pointed before: when addContent flag in ListRQ is true, grpc service returns DomainItem with 'Content' field included (otherwise Content is not present is response). 

Sample json Request to sidecar-app:
{
  "ObjAId": {
    "Org": "TT",
    "Grp": "B4T0",
    "Code": "A"
  },
"addContent": true
}
Then response from grpc-proxy: { "code": 2 } or "unknown message type "'"". I've debugged service and it returns proper proto response.
While request does not contain "addContent":
{
  "ObjAId": {
    "Org": "TT",
    "Grp": "B4T0",
    "Code": "A"
  }
}
Then response is propper:
{
  "ObjAId": {
    "Org": "TT",
    "Grp": "B4T0",
    "Code": "A"
  }
}
Response looks properly:
{
    "ObjAId": {
        "Org": "TT",
        "Grp": "B4T0",
        "Code": "A"
    },
    "DomainItem": [
        {
            "ObjectId": {
                "Type": "Test",
                "Id": "7b52e04e-f04a-44e8-8b3d-854f9e4bd2f8"
            },
            "Pic": {},
            "timestamp": "1519873738747",
         },
        {
            "ObjectId": {
                "Type": "TEST",
                "Id": "fa257c34-7ac2-4aa1-ada0-8e014f5d4101"
            },
            "Pic": {},
            "timestamp": "1519875743822",
        }
    ]
}

**Comment by ayenter** [comment]
Bump!

**Comment by johanbrandhorst** [comment]
It is still unclear to me what this issue is about. As far as I know marshalling the any.Any type should work as expected. Can you make a test case to show that it doesn't work in a PR? That would be a great starting point for a fix.

**Comment by akhenakh** [comment]
I can confirm same things is happening when response contains an any.Any
`{"error":"unknown message type \"\"","message":"unknown message type \"\"","code":2}`

**Comment by johanbrandhorst** [comment]
I think I have an idea of what might be happening. Unmarshalling `any.Any` requires the process to have the wrapped proto type in its protobuf registry, e.g. by importing the message package that defines the type. If you run the grpc-gateway in a separate process, or the process that the gateway is run within never imports this type, you could get an error like this. In @akhenakh's case, I think it should be possible to fix by defining a custom HTTPError function to override the default `runtime.HTTPError` that imports the type that is inside the `any.Any` type. Does that make sense?

**Comment by akhenakh** [comment]
Sorry for the late answer.
That makes sense, this solution is maybe a bit too much since it makes the final user understand he has to register a type in a first place for a proto he maybe does not know about very well... 
But there is maybe more options:
Any is just a []byte and a string to describe the type, maybe it can simply be unmarshalled and transfered as is to the http gw.
One more solution is simply omit Any for now ...

**Comment by johanbrandhorst** [comment]
I'd recommend trying to avoid using Any where you don't know exactly what types that might contain, sorry!

**Comment by akhenakh** [comment]
I do as the proto maintener but a final user of grpc-gateway may not

**Comment by flowerinthenight** [comment]
I can't find any information on this issue other than this so I'll just mention it here anyway. If you're running grpc-gateway as a separate process and it's not able to handle Any, you can just import the generated pb.go file to your proxy source, something like
```go
import (
  ...

  _ github.com/username/pkgwithpbgo
)
```

This works for me.
