### ISSUE TITLE
Support transferring from http to grpc directly?

### ISSUE THREAD

**Issue by hnlq715** [grpc-ecosystem/grpc-gateway#555]
This could turn grpc serivces into http services directly, instead of network transport.

I'm wonderring if this is a good point to improve performance and maintenance.

**Comment by hnlq715** [comment]
https://github.com/hnlq715/grpc-gateway/commit/488d9e367e40e0de392202dfe818be792e6e25ff

Simple demo here...

**Comment by achew22** [comment]
I think https://github.com/grpc-ecosystem/grpc-gateway/pull/454 can be used to provide this functionality already. Can you comment to indicate if you think that isn't sufficient?

**Comment by hnlq715** [comment]
@achew22 Thanks for reply, is there any example implementing the client interface?

**Comment by achew22** [comment]
The idea is that you wouldn't generate the client interface in grpc-gateway, you would instead use the normal grpc client/server generation code to create your server/client and that you wire them up through `Register....HandlerClient`

**Comment by hnlq715** [comment]
So here is the question, how to create my own server/client? And frankly speaking, this is awful...

**Comment by hnlq715** [comment]
Alright, maybe you misunderstand what I mean...
I just want to write the grpc services, and register the service implementations to support http api through `Register...HandlerServer`
In this way, we do not need to write the http code which is redundant.

**Comment by achew22** [comment]
Right, so to put a very fine point on it by using `echo_service.proto`, you can implement by implementing the `EchoServiceClient` interface and passing it into `func RegisterEchoServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client EchoServiceClient) error {`.

Can you help me understand why that doesn't work for you?

**Comment by hnlq715** [comment]
So to support grpc service, we have to implement the `EchoServiceServer` interface.

And to support http service, we just need to pass the implemented `EchoServiceServer` instance into `func RegisterEchoServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, srv EchoServiceServer) error {`, instead of implementing another `EchoServiceClient` interface, which is more elegant and less redundant.

**Comment by hellupline** [comment]
@achew22 while your solution does work, its not clear how to handle things like the calloption 

eg: 
```go
type internalgrpcclient struct { s MyServiceServer }

func (c internalgrpcclient) Echo (ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
        return c.s.Echo(ctx, in)
}
```

and then using the `...RegisterClient`, my grpc service does not receive the http readers,
