### ISSUE TITLE
Transition API to less confusing package names

### ISSUE THREAD

**Issue by tep** [grpc-ecosystem/grpc-gateway#558]
Go packages names like `utilities` and `runtime` tend to cause continual problems for developers and are highly discouraged . The name `utilities` is overly generic and `runtime` is the name of a standard library package. While package renaming on import is quite common in other languages, it goes against Go best practices and should be avoided at all cost.

Renaming these packages will, in the long run, eliminate a great many problems that can easily be avoided.

Please see the  [Package Names](https://github.com/golang/go/wiki/CodeReviewComments#package-names) and [Imports](https://github.com/golang/go/wiki/CodeReviewComments#imports) sections of **Go Code Review Comments**, the  [Package Names](https://golang.org/doc/effective_go.html#package-names) section of **Effective Go** and the section labelled *Avoid unnecessary package name collisions* in [Sameer's Blog Post](https://blog.golang.org/package-names) from 2015.

Luckily, [Go-1.9 introduced *type aliases*](https://golang.org/doc/go1.9) -- which make such a change a whole lot easier -- and Russ Cox was kind enough to give us a [really good write-up](https://talks.golang.org/2016/refactor.article) on how to pull this off.

**Comment by achew22** [comment]
This sounds like a great idea! I really look forward to having a discussion in a PR about what those names should be.

**Comment by tmc** [comment]
I support this. Looking forward to a proposal.

**Comment by tep** [comment]
Package `runtime` could be renamed `grpcgw` and, in my opinion, the `utilities` package could be folded into the former (it containing only a few constants and the `DoubleArray` type).

The existing packages would, of course, remain in place (for a time) but be redefined to reference elements of package `grpcgw` -- either by alias or direct assignment -- along w/ a [deprecation notice](https://rakyll.org/deprecated/). They would eventually be removed when/if the major version number changes.

If ever there comes a time for sub-packages under `grpcgw` these could be prefaced w/ `gw` -- e.g. `grpcgw/gwfoo` (similar to `io` and `io/ioutil`). `internal` packages need not follow such a convention.

**Comment by achew22** [comment]
Since you're merging the two packages together, how would you keep the old, aliased, packages having the exact same exported interface?

**Comment by tep** [comment]
tl/dr; [Like so](https://goo.gl/PSXXWy)*

AFAIK, packages cannot be aliased, only types.  Package level vars, funcs and constants are merely referenced via assignment.

*Note: in the commit referenced above I have a) renamed `runtime` to `grpcgw`, b) merged `utilities` into `grpcgw` and c) updated the original `utilities` to reference elements in `grpcgw`.  I've done nothing, so far, WRT package `runtime`; will get to that RSN.
