### ISSUE TITLE
chunked transfer encoding for streaming responses

### ISSUE THREAD

**Issue by theRealWardo** [grpc-ecosystem/grpc-gateway#562]
I have a use case that requires streaming responses. others on the interwebs have done chunked transfer of JSON in order to improve client performance as well. for example, https://github.com/eBay/jsonpipe 

has anyone tried to tackle this? are there any problems with adding this support and would this project be accepting of a PR that adds support or is the preferred approach a wrapper similar to what @tmc did with websockets in https://github.com/tmc/grpc-websocket-proxy?

**Comment by achew22** [comment]
I think the best way to go about it would be to imitate what @tmc did. It is a nice, clean, solution to the problem at hand and doesn't increase the API surface area for grpc-gateway. I would love to add your project to the official docs so please tell me where your projet ends up so I can add reference to it.

PS: Would you still be interested in getting https://github.com/grpc-ecosystem/grpc-gateway/pull/458 merged?

**Comment by theRealWardo** [comment]
sounds good. I'm a fan of that approach as well. shall we leave this ticket open until I can share a repo for that or do you wanna close this out and say nope then?

yep totally interested in getting #458 merged. I'll give it a quick poke right now so someone can on the review there.

**Comment by theRealWardo** [comment]
with a few patches on top of #458 - this actually works without writing any kind of a wrapper. I was pleasantly surprised. of course I'll merge those into that PR.

in our proto's service definition, we just have `rpc DoTheThing(Request) returns (stream google.api.HttpBody)` and it works great!

**Comment by johanbrandhorst** [comment]
Seems like this will be fixed by #458
