### ISSUE TITLE
Impossible to use gogo/protobuf registered types in gRPC Status errors

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#576]
The gRPC-Gateway uses the gRPC `status` package for writing rich gRPC errors to the JSON response of a gRPC call. Unfortunately, the use of `status.Details()` directly assumes all proto message types stored in the status are registered with the `golang/protobuf` proto type registry. Ideally the gRPC Gateway would simply allow the JSON marshaller to marshal the messages, which would leave such type resolution to the marshaller, and not the runtime.

To be specific, this bug refers to the handling of the status in https://github.com/grpc-ecosystem/grpc-gateway/blob/58f78b988bc393694cef62b92c5cde77e4742ff5/runtime/errors.go#L100-L109

**Comment by tmc** [comment]
If this is the only issue from using gogo types we should absolutely get this fixed.

**Comment by johanbrandhorst** [comment]
Yeah I think this will go some way but it's not the only problem. Please see the grpc-gateway section of my post on gogoproto compatibility: https://jbrandhorst.com/post/gogoproto/. Theres nothing that cant be worked around though.
