### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by Stoakes** [grpc-ecosystem/grpc-gateway#605]
Hi
To begin with thank you for the grpc-gateway, on which we rely for several of our projects.

I'd like to know if you plan to have a release in the coming weeks ?
It's been several months since there haven't been one, whereas some interesting new features such as #535 (Support for map type in query string) have been added.

**Comment by johanbrandhorst** [comment]
Bump

**Comment by achew22** [comment]
A new release has been cut. Thanks for the reminder!

https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.4.0
