### ISSUE TITLE
Do not import 	"github.com/grpc-ecosystem/grpc-gateway/xxxx" in the  code

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#610]
It is difficult to setup a private repo for internal use. 

we should change github.com to ---> yourcomany.gitlab.com....

for example: handler.go:

```
handler.go 5.54 KB  

package runtime

import (
	"fmt"
	"io"
	"net/http"
	"net/textproto"

	"context"
	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/ptypes/any"
	"github.com/grpc-ecosystem/grpc-gateway/runtime/internal"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)
```

**Comment by achew22** [comment]
> we should change github.com to ---> yourcomany.gitlab.com....

I'm not sure I understand what you're trying to say here. We are hosted on GitHub, I think changing the host to something else would confuse the matter.

Could you elaborate a bit more on what you would like?

**Comment by jinleileiking** [comment]
`	"github.com/grpc-ecosystem/grpc-gateway/runtime/internal"`
This import will cause some problems.

I want to do some modify for source code. But the github donot give a merge. 
So I clone bare this repo to my private repo. such as my.com/grpc-ecosystem/grpc-gateway

when build from my own project, handler.go will use `github.com/grpc-ecosystem/grpc-gateway/runtime/internal`

**Comment by yugui** [comment]
I thinks go15vendor feature can be a workaround for the issue, by allowing you to have a local copy of this repository.

But at the same time, in my personal opinion, I always try to avoid such local modification of third-party libraries because local modification makes my application hard to maintain. Instead, I try to generalize my specific requirement to something common and develop a generic solution. For example, I often send a PR which makes something pluggable and extensible.

**Comment by achew22** [comment]
To expand on @yugui's answer, I find that I regularly wish a library had an additional piece of functionality or that the ergonomics of its interface are more generic than my problem requires. Often times I am able to whip up a package that wraps the library and reexports the interface in a more narrow context. For example, most of my projects have a logging library that wraps logrus and exposes a method to get a preconfigured logger that is completely filled out based on the context object.
