### ISSUE TITLE
how to use client pool in the gateway?

### ISSUE THREAD

**Issue by chuangyou** [grpc-ecosystem/grpc-gateway#612]
# Please follow the general troubleshooting steps first:

- [ ] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [ ] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [x] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Fill in the following sections with explanations of what's gone wrong.

Steps you follow to reproduce the error:

Your steps here.

What did you expect to happen instead:

Your answer here.

What's your theory on why it isn't working:

Your theory here.

**Comment by achew22** [comment]
What have you tried?

**Comment by chuangyou** [comment]
I want registered the endpoint and it can have multiple connection to service,mean is client pool.

**Comment by achew22** [comment]
That sounds like an interesting problem. Could you explain what you have tried thus far?

**Comment by chuangyou** [comment]
I tried edit the "*.pb.gw.go-regxxxMethod Grpc.Dial" , I also tried registered multiple same endpoint,but this is very troublesome,maybe have plugin mechanism?

**Comment by chuangyou** [comment]
registered multiple same endpoint was no useful

**Comment by achew22** [comment]
​​I'm not aware of a native connection pooling mechanism built into
grpc-go. Could you elaborate on what you're using to achieve pooling? Maybe
you could also elaborate on why you need connection pooling given the
multiplexed nature of gRPC?

**Comment by chuangyou** [comment]
@rogerhub  I want a endpoint used multiple connections to improve throughput,not multiple endpoints by multiple connections,athough H2 multiplexing,but a connection the throughput is always limited.
