### ISSUE TITLE
code.NotFound should return a 404 instead of a 405

### ISSUE THREAD

**Issue by bobbytables** [grpc-ecosystem/grpc-gateway#630]
# Please follow the general troubleshooting steps first:

- [x] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [x] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [x] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Steps you follow to reproduce the error:

* Create a grpc endpoint that returns a NotFound (Code 5)
* Hit grpc-gateway for corresponding endpoint
* Receive a 405 (Method Not Allowed)

What did you expect to happen instead:

* The Code 5 should indicate to the grpc-gateway to return a 404, not a Method Not Allowed. In fact, no GET / HEAD request should return this. Per mozilla documentation:

> Note: The two mandatory methods, GET and HEAD, must never be disabled and it should not return this type of error.

(https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)

What's your theory on why it isn't working:

I'm guessing the code mapping from grpc -> http is a little off.

**Comment by achew22** [comment]
Interesting that you get that result. This is [the code](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go#L30) where we do that conversion. Are you doing anything non-standard in your setup? I've been using this error code for years in my application without trouble, I'd be interested in running down the problem.

**Comment by bobbytables** [comment]
Just realized what it is, it's a `HEAD` call actually.

**Comment by bobbytables** [comment]
I did `curl -I` which sets the method type to `HEAD`.

**Comment by bobbytables** [comment]
I think I had a possible misunderstanding here, but why does a HEAD request fail it. Technically HEAD should also return an `Allowed` header per RFC: https://tools.ietf.org/html/rfc2616#section-10.4.6

**Comment by achew22** [comment]
The logic behind this is that we require you to be explicit about the request methods you intend to receive. If you want to receive a `HEAD` then you will need to use a [CustomHttpPattern](https://cloud.google.com/service-management/reference/rpc/google.api#google.api.CustomHttpPattern).

See the documentation line

> The custom pattern is used for specifying an HTTP method that is not included in the pattern field, such as HEAD, or "*" to leave the HTTP method unspecified for this rule. The wild-card rule is useful for services that provide content to Web (HTML) clients.

Per the [HttpRule](https://cloud.google.com/service-management/reference/rpc/google.api#google.api.HttpRule) documentation.

**Comment by achew22** [comment]
WRT [RFC2616 10.4.6](https://tools.ietf.org/html/rfc2616#section-10.4.6), that is another in a long line of things we MUST do according to the RFC, but don't perfectly implement because no one has needed them yet. I would love to merge a PR that adds it.

If compliance with that spec is the name of the game you could also implement a handler that responds to HEAD requests appropriately.

**Comment by bobbytables** [comment]
Roger that, sorry for the confusion. Closing.

**Comment by achew22** [comment]
No worries, have a good day!
