### ISSUE TITLE
bazel rule protoc_gen_swagger creates clashing outputs if used multiple times in the same package

### ISSUE THREAD

**Issue by ensonic** [grpc-ecosystem/grpc-gateway#638]
Lets take this example:
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/BUILD.bazel#L61
```
protoc_gen_swagger(
    name = "expamplepb_protoc_gen_swagger",
    proto = ":examplepb_proto",
)
```
the proto attr points to a proto_library with multiple (6) direct sources. The protoc_gen_swagger() rule will create for each of those protos a related xxx.swagger.json (substituting .proto for .swagger.json). This is problematic if I were to add another rule to this package like:
```
protoc_gen_swagger(
    name = "expamplepb_protoc_gen_swagger_with_services",
    grpc_api_configuration = "unannotated_echo_service.yaml",
    proto = ":examplepb_proto",
)
```
See https://github.com/grpc-ecosystem/grpc-gateway/pull/632#issuecomment-385907368

The problem is this part of the code:
```
swagger_file = actions.declare_file(
          "%s.swagger.json" % proto.basename[:-len(".proto")],
          sibling = proto,
      )
```
We produce a set of files unrelated to the rule-name, next to the original .proto files (due to sibling=proto). First 'sibling=proto' is problematic since this will enfocre that the protoc_gen_swagger rules has to be in the same package as the proto_library. I don't see a good reason for that.

Creating a new directory with the action name is not really possible too (I did not manage to). One could of course produce a zip containing the protos, but that is annoying for further use.

**Comment by achew22** [comment]
Yeah, it would be better if the swagger name was derived from the name of the rule. That wouldn't be a pretty easy PR to do after #632 is merged

**Comment by ensonic** [comment]
Do we have docs that list all options for protoc_gen_swagger ?
