### ISSUE TITLE
protoc_gen_swagger should use target_name.swagger.json as out

### ISSUE THREAD

**Issue by achew22** [grpc-ecosystem/grpc-gateway#640]
By default protoc_gen_swagger should use target_name.swagger.json as the output file and use something like https://github.com/grpc-ecosystem/grpc-gateway/pull/591 to generate a single file output of that name.

**Comment by achew22** [comment]
@cy-zheng would you like to pick up where #591 left off? It wouldn't be too much more work to enhance with a test then I'll merge it and do the Bazel change. What do you think?

**Comment by cy-zheng** [comment]
Well, I'll take a look at it this weekend. It seems make it work by just adding some test cases.

**Comment by achew22** [comment]
Yep, that's exactly what we need to get it submitted :smile:

**Comment by cy-zheng** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/pull/643
