### ISSUE TITLE
proto-gen-* --version

### ISSUE THREAD

**Issue by stevenroose** [grpc-ecosystem/grpc-gateway#649]
For a lot of projects, especially open-source ones, you want all contributors to use the same version of all the protobuf (and grpc) tools. Otherwise pull requests for small changes in proto files could potentially have huge changes in generated code if the contributor has a different version.

A good solution for this, is to provide a generation script within the project that contributors should use to generate the code. In this script, the version of the tools can be checked.

Currently, protoc --version gives you the version of protoc. It would be nice if protoc-gen-grpc-gateway and protoc-gen-swagger could also somehow expose their version through a command. Preferably the same as protoc.

**Comment by tmc** [comment]
@stevenroose that's a great idea!

**Comment by llimllib** [comment]
Pretty sure this should be closed by https://github.com/grpc-ecosystem/grpc-gateway/commit/538c6622a488546f4c7edb2a26de6c1d1406b170#diff-876ec625d85d9f69d24a74b15c7f4487 ?

**Comment by johanbrandhorst** [comment]
Thanks @llimllib, I'd missed this issue :D
