### ISSUE TITLE
proto-gen swagger: use service + method name as the opeartionId

### ISSUE THREAD

**Issue by wanghong230** [grpc-ecosystem/grpc-gateway#661]
In the case, there are two services in the same proto file. If method names are duplicated, the swagger generated won't be valid, since operationId is not unique.

The idea is to use service name + method name to increate the uniqueness.

**Comment by weisd** [comment]
+1

**Comment by lpabon** [comment]
This is really important. Anyone working on this? @johanbrandhorst ?

**Comment by achew22** [comment]
@lpabon, I don't think anyone is working on this. Would you be interested in taking a stab at it? What information do you need to get started on adding this as a flag?

**Comment by johanbrandhorst** [comment]
I think there's an open PR for allowing the operation id to be configured. I'm not working on it myself.

**Comment by johanbrandhorst** [comment]
See https://github.com/grpc-ecosystem/grpc-gateway/pull/739 and #40

**Comment by lpabon** [comment]
Thanks @johanbrandhorst , but I think #739 is not exactly what I thought the solution would be. The solution in that PR is one way, but I was thinking of having the `OperationID` equal to the proto rpc Service name + the Method name. Adding the service name would make it 'like' the gRPC model.

What do you think?

**Comment by johanbrandhorst** [comment]
I think we can have both, since the current default is to leave it empty, we can change that default in line with this issue but also allow it to be configured per #740. #739 has stalled so if you could pick that up in a separate PR I'd be happy to help you get that merged.

**Comment by lpabon** [comment]
Sweet, will do
