### ISSUE TITLE
how to install swagger-codegen@2.2.2?

### ISSUE THREAD

**Issue by dmacthedestroyer** [grpc-ecosystem/grpc-gateway#670]
I'm trying to contribute to this project with #379 but am running into issues getting the tests to run properly, due to having a too recent version of swagger installed.

I'm on a Mac, and homebrew installs v2.3+. I've gone down many rabbit holes to get the older version installed, but can't seem to figure it out. How did you all get your setup running?

**Comment by dmacthedestroyer** [comment]
running this brew command will install 2.2.2: `brew install https://homebrew.bintray.com/bottles/swagger-codegen-2.2.2.sierra.bottle.tar.gz`

**Comment by achew22** [comment]
Sounds like you've got it worked out. Closing. I look forward to your contribution!
