### ISSUE TITLE
Consider removing project-specific semantics from descriptor package

### ISSUE THREAD

**Issue by tmc** [grpc-ecosystem/grpc-gateway#672]
Especially having openapi semantics in the descriptor package is suspect. I think it can (and should) be separate from the semantics from either the proxy generation and openapi generation. I think I made the first mistake here by merging #280

**Comment by ivucica** [comment]
This is unclear to me. #280 doesn't seem to relate to OpenAPI, and `descriptor` package doesn't seem to refer to OpenAPI either. Can you expand a bit on what OpenAPI semantics are you referring to?
