### ISSUE TITLE
inconsistent identifier capitalization between protoc-gen-go and protoc-gen-grpc-gateway

### ISSUE THREAD

**Issue by palohan** [grpc-ecosystem/grpc-gateway#683]
In the following proto file, notice the underscores, numbers (and possibly other characters) in identifiers:
```
syntax = "proto3";
import "google/api/annotations.proto";
package template;

service Greeter {
  rpc Sen_dGet (Temp_lateRequest) returns (template_response) {
      option (google.api.http).get = "/get";
  }
  rpc SendGe2t (Temp_lateRequest) returns (template_response) {
      option (google.api.http).get = "/get";
  }
}

message Temp_lateRequest {
  string name = 1;
}

message template_response {
  string name = 1;
}
```
After compiling such file, building the executables produces these errors:
```
../template/template.pb.gw.go:36:15: undefined: Temp_lateRequest
../template/template.pb.gw.go:43:20: client.Sen_dGet undefined (type GreeterClient has no field or method Sen_dGet)
../template/template.pb.gw.go:53:15: undefined: Temp_lateRequest
../template/template.pb.gw.go:60:20: client.SendGe2t undefined (type GreeterClient has no field or method SendGe2t, but does have SendGe2T)
```

Looking at the pb.go file, we can see the identifiers are different from those in pb.gw.go file
```
type GreeterClient interface {
	SenDGet(ctx context.Context, in *TempLateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	SendGe2T(ctx context.Context, in *TempLateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
}
```
Judging from the code, this happens because protoc-gen-go uses CamelCase
```
./grpc/grpc.go:159:	servName := generator.CamelCase(origServName)
./grpc/grpc.go:283:	methName := generator.CamelCase(origMethName)
```

whereas protoc-gen-grpc-gateway simply calls strings.Title
```
./protoc-gen-grpc-gateway/gengateway/template.go:85:		svcName := strings.Title(*svc.Name)
./protoc-gen-grpc-gateway/gengateway/template.go:89:			methName := strings.Title(*meth.Name)
```

**Comment by johanbrandhorst** [comment]
I think the easiest fix here will be copy-pasting the `protoc-gen-go` generator logic into the generator, but it is problematic since long term they will inevitably deviate. This here is another source of incompatibility with `protoc-gen-gogo` as well since the latter allows a custom name to be used. I wish we could have some way of reading from the file we use but I don't think it's possible.

This should be reasonably easy to fix, anyway.

**Comment by waveywaves** [comment]
@johanbrandhorst I am starting work on this issue. Do let me know if there is something I need to keep in mind.

**Comment by johanbrandhorst** [comment]
@waveywaves thanks! I don't think there's anything particular to keep in mind if we can easily port the logic from `protoc-gen-go`.

**Comment by waveywaves** [comment]
UPDATE:
@johanbrandhorst Steps I followed to reproduce your issue.

Copied the proto file and compiled it with the following command.
```sh
$ protoc -I/usr/local/include -I. \
-I$GOPATH/src \
-I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
--plugin=protoc-gen-grpc-gateway=$GOPATH/bin/protoc-gen-grpc-gateway \
--grpc-gateway_out=logtostderr=true:.  \
$GOPATH/src/echo/echo.proto
```
Upon running the above command a echo.pb.gw.go file wasgenerated.

After creating an empty project, I ran `go install project` after which I got a similar error which said.

```sh
#echo/echo 
echo/echo.pb.gw.go:36:15: undefined: Temp_lateRequest
echo/echo.pb.gw.go:53:15: undefined: Temp_lateRequest
```
To test this further I removed the underscores in `Temp_lateRequest` in the .proto file giving me `TemplateRequest`. After compiling this new proto file and running `go install project` I got the following error.

```sh
# echo/echo
echo/echo.pb.gw.go:36:15: undefined: TemplateRequest
echo/echo.pb.gw.go:53:15: undefined: TemplateRequest
```
After the above error, all underscores were removed from the echo.proto file to get the following file which was compiled.

```proto
syntax = "proto3";

import "google/api/annotations.proto";

package echo;

service Greeter {
  rpc SendGet (TemplateRequest) returns (templateresponse) {
      option (google.api.http).get = "/get";
  }
  rpc SendGe2t (TemplateRequest) returns (templateresponse) {
      option (google.api.http).get = "/get";
  }
}

message TemplateRequest {
  string name = 1;
}

message templateresponse {
  string name = 1;
}
```

And upon running `go install project` I got the following errors.
```sh
# echo/echo
echo/echo.pb.gw.go:36:15: undefined: TemplateRequest
echo/echo.pb.gw.go:43:20: client.SendGet undefined (type GreeterClient has no field or method SendGet, but does have SenDGet)
echo/echo.pb.gw.go:53:15: undefined: TemplateRequest
```

This seems to happen only during compilation of the app.
