### ISSUE TITLE
Output swagger seems incorrect

### ISSUE THREAD

**Issue by lpabon** [grpc-ecosystem/grpc-gateway#688]
I'm using protoc 3.3.1 and proto-gen-go 1.1.0. When I output the swagger for [api.proto](https://github.com/libopenstorage/openstorage/blob/master/api/api.proto) and diff it with the previous output of grpc-gateway version 1.4.1 I get the following incorrect output diff:

```diff
       "post": {
-        "summary": "Create",
+        "summary": "Enumerate lists all the nodes in the cluster.",
         "operationId": "Create",
         "responses": {
           "200": {
@@ -90,7 +90,7 @@
     },
     "/v1/cloudbackup/catalog/{backup_id}": {
       "get": {
-        "summary": "Catalog",
+        "summary": "Restores a volume to a specified snapshot",
         "operationId": "Catalog",
         "responses": {
           "200": {
@@ -122,7 +122,7 @@
     },
     "/v1/cloudbackup/deleteall": {
       "post": {
-        "summary": "DeleteAll",
+        "summary": "Clear the alert for a given resource",
         "operationId": "DeleteAll",
         "responses": {
           "200": {
@@ -149,7 +149,7 @@
```

Seems something is incorrect. Is this due to a version issue or a bug in the swagger output?

**Comment by johanbrandhorst** [comment]
This is because https://github.com/grpc-ecosystem/grpc-gateway/pull/667, which fixed the Summary being taken from the comment on the RPC method. It is a _feature_. Do you wish to keep this issue open to argue that this is undesirable behaviour? Otherwise please close it.

**Comment by lpabon** [comment]
Ah, interesting. Thanks for the info.
