### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by jsha** [grpc-ecosystem/grpc-gateway#689]
For the Trillian project (https://github.com/google/trillian/pull/1220), I am trying to vendor all dependencies. Right now, Trillian depends on a specific version of `protoc-gen-grpc-gateway`. However, even if we pull that specific version, we don't currently have a good guarantee that we are getting a consistent set of dependencies pulled into `protoc-gen-grpc-gateway`. Would you consider vendoring this project's dependencies using `dep`? Vendoring represents the dependency management plan that the Go team is moving forwards with: https://blog.golang.org/versioning-proposal. Go's end goal won't be exactly like `dep` but will be similar, and the Go team has committed to a smooth transition.

**Comment by tmc** [comment]
I think going the Gopkg route as a temporary measure makes sense. @johanbrandhorst can you take that on?

**Comment by johanbrandhorst** [comment]
@tmc I'm on it
