### ISSUE TITLE
Support openapiv2_tag option in swagger generator

### ISSUE THREAD

**Issue by achow14** [grpc-ecosystem/grpc-gateway#690]
Hey guys, 

I'm trying to use grpc-gateway to create a swagger.json directly from a .proto file
I was wondering if the tag option
option (grpc.gateway.protoc_gen_swagger.options.openapiv2_tag)
was working?

I pasted this tag option inside a service and it should change the description for the service "tag" if I'm not mistaken. When I do this and generate a swagger.json file, the services do not have descriptions appended to them. (Snippet Below)

service APIService {

  option (grpc.gateway.protoc_gen_swagger.options.openapiv2_tag) = {
	description: "Some Description";
  };
 rpc someService(Request) returns (Response)
}

In addition, for passing parameters, is there any kind of header support? Reading through the documentation, I've figured out that you have an optional body field and an automatic query parameter generation from the requests you pass into the rpc. However, is there any header parameter support that isn't in the documentation?

Thank you for the help.

**Comment by johanbrandhorst** [comment]
Sounds like adding support for the `tag` option is a good first PR :).

**Comment by johanbrandhorst** [comment]
Passing parameters via headers is not currently supported. Headers map to gRPC metadata.

**Comment by drorventura** [comment]
Hi, did someone stated fixing this issue?

**Comment by drorventura** [comment]
I might :) 
i'll try to make time for it soon

**Comment by rcgoodfellow** [comment]
PR for this: https://github.com/grpc-ecosystem/grpc-gateway/pull/1866
