### ISSUE TITLE
protoc-gen-swagger: No comments for path parameters

### ISSUE THREAD

**Issue by utrack** [grpc-ecosystem/grpc-gateway#694]
Currently Swagger generator loses comment description if I reference any field of an RPC request object in path.

Say, RPC is defined as
```
service Summator {
  rpc Sum(SumRequest) returns (SumResponse) {
    option (google.api.http) = {
                                // uncomment get or post+body or use YAML annotation
                                //get: "/v1/example/sum/{a}/{b}"
                                post: "/v1/example/sum/{a}"
                                body: "b"
    };
  }
}
// SumRequest is a request for Summator service.
message SumRequest {
  // A is the number we're adding to. Can't be zero for the sake of example.
  int64 a = 1;
  // B is the number we're adding.
  NestedB b = 2;
}
```

Swagger generates a method as
```
...
        "parameters": [
          {
            "name": "a",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "int64"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/sumpbNestedB"
            }
          }
...
```
Param `a` can (and should) have a comment, but it's not pulled.

I'll try to fix it if no one gets to it sooner - it can be messy though since `PathParam` loses almost any info about its target field.

**Comment by frolickingferret445** [comment]
Are you sure that you are still seeing this issue?  If I understand your issue correctly, I was seeing the same issue, but it disappeared when I pulled the latest version of grpc-gateway.

**Comment by johanbrandhorst** [comment]
Could you try against master? Might be time for us to cut a new release with this fix.

**Comment by johanbrandhorst** [comment]
A new release has been made, this should be fixed.
