### ISSUE TITLE
Does grpc-gateway support the HTTP 2.0 protocol?

### ISSUE THREAD

**Issue by ncepuwanghui** [grpc-ecosystem/grpc-gateway#703]
According to the figure below, it can be seen that grpc-gateway only support HTTP 1.1. We want to use HTTP2.0+JSON to access the inner service. Does grpc-gateway have a plan to support HTTP 2.0 in the future?
![image](https://user-images.githubusercontent.com/6895399/42919818-4c99b9cc-8b46-11e8-98c1-201b60f6df7c.png)

**Comment by rogerhub** [comment]
It doesn't need to explicitly support h2. You can attach a grpc-gateway handler to the standard `net/http` Server, which will handle both http/1.1 and h2 (see [examples/gateway/main.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/gateway/main.go) for an example).
