### ISSUE TITLE
APIs with grpc-gateway (S3,WebDav)

### ISSUE THREAD

**Issue by moscicki** [grpc-ecosystem/grpc-gateway#709]
[please point me to a better place for such questions if not here]

I am looking into having S3-compatible and WebDav-compatible gateways connecting to grpc upstream services. Would it make sense to try to use grpc-gateway for that? Is there an existing project doing that?

**Comment by achew22** [comment]
@moscicki, maybe you could elaborate a bit on your question a bit. gRPC is not a file storage protocol, it is a set of tools for creating a protocol. If you want to build a file transfer protocol on top of gRPC that would be an interesting effort, but probably beyond the scope of this repo. WRT being S3 or WebDAV compatible, I took a cursory glance at the protocol expectations of S3 and WebDAV and it doesn't look like it will be easy to shoe-horn into grpc-gateway. If you decide to advance down this path, feel free to comment into this issue to point to your repo, I'd love to see what you end up building. I'm going to close this but if you have more questions feel free to reopen it, comment on it still, or open another issue
