### ISSUE TITLE
Is there any way we can remove fields from the response json in grpc-gateway?

### ISSUE THREAD

**Issue by chaitanya9186** [grpc-ecosystem/grpc-gateway#710]

**Comment by johanbrandhorst** [comment]
If you set your marshaller to not EmitDefaults, and then return the zero value of that field, it will not be included in the returned JSON.

This begs the question though, what are you trying to do here?

**Comment by vtolstov** [comment]
does it possible to modify EmitDefaults per Service in runtime.NewServeMux ?

**Comment by vtolstov** [comment]
i have compat api and new api. In compat i need to EmitDefaults: true, but in new - not

**Comment by vtolstov** [comment]
thanks, but how to deal with two different ServeMux in one http.Server ?

**Comment by vtolstov** [comment]
https://github.com/mennanov/fieldmask-utils this is works fine

**Comment by johanbrandhorst** [comment]
Closing this as OP seems inactive.
