### ISSUE TITLE
google/protobuf/descriptor.proto: File not found. ?

### ISSUE THREAD

**Issue by lei314121077** [grpc-ecosystem/grpc-gateway#713]
# Please follow the general troubleshooting steps first:

- [x] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [x] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [x] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Fill in the following sections with explanations of what's gone wrong.

Steps you follow to reproduce the error:

Your steps here.

What did you expect to happen instead:

Your answer here.

What's your theory on why it isn't working:

Your theory here.

**Comment by achew22** [comment]
Please fill out the issue template or file another bug. This is not enough information to allow us to understand what went wrong so we can help you. Thanks!

**Comment by lei314121077** [comment]
sorry  I have solved it. Thanks! @achew22

**Comment by AlirezaHaghshenas** [comment]
@lei314121077  How did you solve your problem?

**Comment by achew22** [comment]
@AlirezaHaghshenas if you're having problems, please feel free to open another issue describing the issues you're having, and the steps you've already attempted to overcome your issues. Thanks!
