### ISSUE TITLE
Travis CI fails on master branch

### ISSUE THREAD

**Issue by doroginin** [grpc-ecosystem/grpc-gateway#714]
### Bug reports:

Travis CI on master branch fails now (last commit https://github.com/grpc-ecosystem/grpc-gateway/commit/209d7ce1a333550d4ce54dad94432192eeb2041b)

I forked original repo and run Travis CI test in my fork on master branch, and it fails now.
Link to the report https://travis-ci.org/doroginin/grpc-gateway/builds/410715427

**Comment by johanbrandhorst** [comment]
Thanks for raising this, some discussion has already taken place in https://github.com/grpc-ecosystem/grpc-gateway/pull/711. I think the next step to debug this is to try and run all the CI steps manually and see which one is causing the incorrectly generated files.

**Comment by johanbrandhorst** [comment]
I think this was fixed by https://github.com/grpc-ecosystem/grpc-gateway/pull/715?
