### ISSUE TITLE
why gateway proxy can not distribute the http request to local server?  prompt 404

### ISSUE THREAD

**Issue by toranger** [grpc-ecosystem/grpc-gateway#722]
![image](https://user-images.githubusercontent.com/23206440/43989835-1969a4ae-9d84-11e8-8477-662e2bee5209.png)
did‘t trigger the grpc call at all

**Comment by johanbrandhorst** [comment]
I'm gonna need a lot more information to be able to help you. What does your protofile look like? What is the exact curl command you ran? It looks to me from that screenshot that you're just calling the wrong URL. A gRPC-Gateway would not reply with an error like this, (notice the `Powered By Jetty://` error).

**Comment by toranger** [comment]
Pre: I run two local raft master node srv and one local grpc-gateway to distribute http request
such like this rpc function, protofile like this:
![image](https://user-images.githubusercontent.com/23206440/43990150-22f4a720-9d8a-11e8-98cc-19cb71a6a852.png)
![image](https://user-images.githubusercontent.com/23206440/43990121-a03c96b2-9d89-11e8-917d-c260eb1eb1ce.png)
Ps: the http request can arrived at gateway node, but also tell me transport is closing. *^*
![image](https://user-images.githubusercontent.com/23206440/43990145-150089e0-9d8a-11e8-87e5-69bb0a7fec05.png)

**Comment by achew22** [comment]
@toranger, could you include not  a screenshot, but a copy/paste'd version of the go code you're using to register the grpc gateway handlers and also to start the server?

**Comment by toranger** [comment]
@achew22,
[svr.txt](https://github.com/grpc-ecosystem/grpc-gateway/files/2280736/svr.txt)
[gateway.txt](https://github.com/grpc-ecosystem/grpc-gateway/files/2280737/gateway.txt)

**Comment by achew22** [comment]
Can you write a bit about what it is you've tried and what you think might be wrong too? I'm happy to help with a specific problem but I don't have time to dig through a couple hundred lines of code and dozens of linked libraries -- sorry

**Comment by toranger** [comment]
Sorry, the problem is  I start two svr ( 0.0.0.0:9090 and 0.0.0.0:9092 ) and gateway( listen 8090), though http request can arrive at gateway but svr did't trigger the  grpc method. It always present "transport is closing".  Does it mean svr  has problem with  grpc? or?

**Comment by achew22** [comment]
Can you write a bit about what it is you've tried and what you think might be wrong too? Are you getting any other error messages for example?

**Comment by toranger** [comment]
There are no other error messages, I tried use curl to call the rpc function, but all remind me "transport is closing",  if gateway can't connect server it will remind "all sub connection failed", so I think maybe use gateway to trigger rpc failed.

**Comment by achew22** [comment]
Are you curling to the gRPC endpoint or to the http exposed endpoint? What is the curl command you're running?

**Comment by toranger** [comment]
curl -H "Content-Type:application/json" -d '{"module_name":"cos-cgi", "env_name":"dev", "category":"ap-shanghai"}' -X POST -k http://118.89.226.213:8090/v1/getagentinfo/module, all did not work

**Comment by achew22** [comment]
when your run that command with the additional arguments `-vvv` what do you get?

**Comment by toranger** [comment]
A long time later, it will show:
* upload completely sent off: 69 out of 69 bytes
< HTTP/1.1 503 Service Unavailable
< Content-Type: application/json
< Date: Mon, 13 Aug 2018 02:27:50 GMT
< Content-Length: 42
< 
* Connection #0 to host 118.89.226.213 left intact
Add the log to the svr port, It seems no problem. I start all server on one machine to test.
I0813 10:36:48.370241   15174 main.go:67] current gateway server is: {:8090 0xc42007bb00 <nil> 0s 0s 0s 0s 0 map[] <nil> <nil> ... }

**Comment by achew22** [comment]
Can you include the complete output of the curl command? All the way from invocation to the end of the output? When you paste it in here, if you follow [these](https://help.github.com/articles/creating-and-highlighting-code-blocks/) instructions on how to create a code block, it will be much easier for me to read.

**Comment by toranger** [comment]
Finally, found it works wrong with the raft connection, thank you very much .
