### ISSUE TITLE
Let service choose it's own marshaller

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-gateway#725]
# Please follow the general troubleshooting steps first:

- [ ] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [ ] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [ ] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Fill in the following sections with explanations of what's gone wrong.

Steps you follow to reproduce the error:

Your steps here.

What did you expect to happen instead:

Your answer here.

What's your theory on why it isn't working:

Your theory here.

**Comment by johanbrandhorst** [comment]
It's possible to choose your own marshaller already with the `runtime.WithMarshalerOption` option: https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#WithMarshalerOption.

**Comment by jinleileiking** [comment]
@johanbrandhorst  I mean.

each api have its own marshaller:

```
/api/json ---> use jsonpb marshaller
/api/form ---> user formpb marshaller
```

**Comment by johanbrandhorst** [comment]
Do you want the ability to control the marshaller per-method? You could do this kind of thing with two different gRPC-Gateway servers on the same `http.Server` if you split traffic in a separate handler. Would that work for you?

**Comment by jinleileiking** [comment]
> Do you want the ability to control the marshaller per-method? 

Yes

@johanbrandhorst Can you give me an example? Thanks.
