### ISSUE TITLE
Cannot set `consumes` definition per operation

### ISSUE THREAD

**Issue by Arttii** [grpc-ecosystem/grpc-gateway#726]
# Please follow the general troubleshooting steps first:

- [x] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [x] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [x] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Cannot set `consumes` definition per operation, even though the `consumes` field is present in the `openapiv2_operation` message  definition. This leads to problem with using the generated swagger spec to generate test server or client for non GRPC clients.

Steps you follow to reproduce the error:

1. Set `consumes` via `openapiv2_swagger` 
2. Set `consumes` via `openapiv2_operation` for a seperate rpc method

What did you expect to happen instead:

1. The consumes option should overwrite the global one, but its not

What's your theory on why it isn't working:

Looking at [this](https://github.com/grpc-ecosystem/grpc-gateway/blob/de0b679b7b2e83123304a21180e92b10b52f4f7c/protoc-gen-swagger/genswagger/template.go#L779) it seems the per operation `consumes` is not being considered

**Comment by johanbrandhorst** [comment]
Indeed, it seems `Consumes` is hardcoded. Do you want to contribute a fix for this? It looks like it should be rather straightforward.

**Comment by Arttii** [comment]
I can give a try

**Comment by johanbrandhorst** [comment]
Yes :)

**Comment by Arttii** [comment]
I am a bit unsure how to write the test I cannot seem to find any examples how to actually pass in options with `MethodDescriptorProto`

**Comment by johanbrandhorst** [comment]
If you put up a PR we can review it and help you create some tests for it!

**Comment by stomy13** [comment]
Hello @johanbrandhorst,
Created PR to contribute this fix, please check.
