### ISSUE TITLE
Client grabbing errors

### ISSUE THREAD

**Issue by ayenter** [grpc-ecosystem/grpc-gateway#728]
### This is not technically a bug with grpc-gateway, but more of a request for information/help for usage.

**Steps you follow to reproduce the error:**

1. Setup and run a grpc-gateway with no backend service running (so that all requests fail).
2. Send a legitimate REST call using a python `requests` client or php `guzzle` client.
3. Send the same command using curl.
4. Compare the error responses. (Curl command gives use information.)

**What did you expect to happen instead:**

I expected that the clients would pick-up the error message that curl did.
In the aforementioned situation, Curl returns useful information such as:
`{"error":"transport is closing","message":"transport is closing","code":14}`
or 
`{"error":"all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 123.45.678.910:12345: connect: operation timed out\"","code":14}`

But the client will only return `503 Service Unavailable`

**What's your theory on why it isn't working:**

I suspect that the errors are chunked or in the trailer, but I am unsure how to capture them using a client. I am hoping somebody could give me some insight towards a solution. Thanks!

**Comment by johanbrandhorst** [comment]
If `curl` does the right thing and `requests` and `guzzle` doesn't, it's probably up to how those have been configured, right? I bet you can get the same reponse data from both of those clients. This is probably not the best place to ask for help with configuring your python of PHP client unfortunately, so I will close this issue and direct you to the [requests documentation](http://docs.python-requests.org/en/master/).

**Comment by johanbrandhorst** [comment]
Think this was closed by mistake
