### ISSUE TITLE
Question/Enhancement: how to wrap the gateway's response?

### ISSUE THREAD

**Issue by veqryn** [grpc-ecosystem/grpc-gateway#734]
At my organization, all of our http rest endpoints return a basic structure that looks like this:
```
{
    "data": [],
    "info: {
        "errors": []
    }
}
```

Regardless of whether there is a repeating or non-repeating resource, it gets returned within the `data` array above.
Any errors go into the `errors` field.

So, some actual examples:
Here we are with a singular resource:
```
{
    "data": [
        {
            "name": "DKIM",
            "status": "new",
            "domain_count": 3
        }
    ],
    "info: {
        "errors": []
    }
}
```

Here is an error:
```
{
    "data": [],
    "info: {
        "errors": [
            {
                "error_code": 3000
                "error_message": "Required field missing"
            }
        ]
    }
}
```

Is there absolutely any way I can possibly get the GRPC Gateway to output something in this format?

**Comment by johanbrandhorst** [comment]
Streaming responses use something like this already:
Success:
```json
{
    "result": <stuff>
}
```
Failure:
```json
{
    "error": "grpc-error-string"
}
```
See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/handler.go#L181.

However, I think the way you would solve this is to design your proto messages to output in this format, and then implement a custom [`HTTPError`](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go#L61) for when you have errors. It's not particularly ergonomic, but it should work.

**Comment by veqryn** [comment]
Hm... this would mean making every single proto response message into a `repeated` field called `data.
That may work, but I was hoping not to have to mangle the proto/grpc side just to get the rest side looking good.
Is it possible to change `result` to `data` for streaming responses?

**Comment by johanbrandhorst** [comment]
I think if you want to wrap the entire response you're better just wrapping the ServeMux with a custom handler middleware for rewriting responses. The streaming response isn't configurable as far as I know.

**Comment by aldogint** [comment]
if i'm not mistaken, documentation imply that it's possible using WithForwardResponseOption, see [docs](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/_docs/customizingyourgateway.md#mutate-response-messages-or-set-response-headers).  
but it's actually doesn't take any effect when i do this
```go
runtime.WithForwardResponseOption(func(ctx context.Context, w http.ResponseWriter, resp proto.Message) error {
				// for example setting it to nil
                                resp = nil
				return nil
			}),
```
it's possible using custom `ResponseForwarder` but i think there's to many codes need to be duplicated just to wrap the response. i'll try using middleware to rewrite the response but i think it'll be cool if we're able to wrap the response using `forwardResposeOption`.
