### ISSUE TITLE
Uint64 is represented as type:"string" in the swagger docs.

### ISSUE THREAD

**Issue by trusch** [grpc-ecosystem/grpc-gateway#735]
# Please follow the general troubleshooting steps first:

- [ x ] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [ x ] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [ x ] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Steps you follow to reproduce the error:

1. create a message with one uint64 field
2. create a service using the message
3. generate swagger doc for it
4. it lists the type as `{type: string, format: uint64}`

What did you expect to happen instead:

The swagger doc should list the type as `{type: integer, format: int64, min: 0}`

What's your theory on why it isn't working:

The well-known-type Uint64 is hardcoded to map to the result we currently see.

**Comment by johanbrandhorst** [comment]
This kind of thing has been discussed before at length: https://github.com/grpc-ecosystem/grpc-gateway/issues/438. Is this a fundamentally different issue? I will pre-emptively close this, but please let me know if I'm wrong.
