### ISSUE TITLE
Go1.11: http.CloseNotifier is deprecated

### ISSUE THREAD

**Issue by SpikesDivZero** [grpc-ecosystem/grpc-gateway#736]
Hi all,

I was checking if we could upgrade our project to Go 1.11 now that it's released, and one of our static analysis tools is erring with "http.CloseNotifier is deprecated". I tried upgrading my binaries locally, and then checked the git repo and see that it's still present in template.go on the master branch.

Could the template be upgraded so that we're no longer relying on deprecated code? (I'll admit that I don't know what the GRPC-Gateway compatibility promise is, and if such an upgrade would break that.)

Thanks,
-Spikes

**Comment by johanbrandhorst** [comment]
I think this should be a reasonably easy first PR for anyone wanting to do it - the CloseNotifier code is only there for when the request context isn't available. Feel free to submit a PR with it removed :).

**Comment by eundoosong** [comment]
@johanbrandhorst I would like to work on this issue. 
Does this mean below CloseNotifier should be removed?
```go
    if cn, ok := w.(http.CloseNotifier); ok {
      go func(done <-chan struct{}, closed <-chan bool) {
        select {
        case <-done:
        case <-closed:
          cancel()
        }
      }(ctx.Done(), cn.CloseNotify())
    }
```

**Comment by johanbrandhorst** [comment]
Yeah, we can safely remove that whole if-clause I think.

**Comment by maros7** [comment]
@srikrsna are you planning on finishing the PR https://github.com/grpc-ecosystem/grpc-gateway/pull/752 related to this issue? Or would it be okay if I finished it?

**Comment by johanbrandhorst** [comment]
@maros7 before you do anything, I suggest waiting for #777 to be merged, it should be imminently. It will remove any CI issues we had.

**Comment by johanbrandhorst** [comment]
I intend to bump all the open PRs once that is in master

**Comment by johanbrandhorst** [comment]
This is a great first issue for anyone looking for an easy contribution!
