### ISSUE TITLE
operation_id setting for proto-gen-swagger is ignored

### ISSUE THREAD

**Issue by robbert229** [grpc-ecosystem/grpc-gateway#740]
### Bug reports:

Fill in the following sections with explanations of what's gone wrong.

## Steps you follow to reproduce the error:

1. create a service that has an rpc with the operation id set.
```proto
	rpc Echo(grpc.gateway.examples.sub.StringMessage) returns (grpc.gateway.examples.sub.StringMessage) {
		option (google.api.http) = {
			get: "/v1/example/a_bit_of_everything/echo/{value}"
		};
		option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
			operation_id: "performEcho";
		};
	}
```
2. generate a swagger spec for it.

## What did you expect to happen instead:

1. I expected that the generated swagger spec would have an operation id of "performEcho" instead of Echo.

## What's your theory on why it isn't working:

This is happening because the operationID property on the Swagger Operation option wasn't being checked.

**Comment by vtolstov** [comment]
any progress?
