### ISSUE TITLE
"error" and "message" fields in error response

### ISSUE THREAD

**Issue by GoingFast** [grpc-ecosystem/grpc-gateway#768]
its being duplicated and I dont see use case for it. talking about this commit: https://github.com/grpc-ecosystem/grpc-gateway/commit/7951e5b80744558ae3363fd792806e1db15e91a4. any way to get rid of it or can I just comment it out?

**Comment by johanbrandhorst** [comment]
We have to keep both for backwards compatibility; we may remove the "error" field in 2.0, but we cannot do it without breaking existing users for now.

**Comment by ti** [comment]
add "message" fields is meaningless for now

**Comment by johanbrandhorst** [comment]
No, it's not meaningless, the gateway is tightly coupled with gRPC and protobuf, where the googleapis Status type is the correct way to return errors. The gateway added the message field to be more consistent with this practice.
