### ISSUE TITLE
Use Echo/Gin as request multiplexer

### ISSUE THREAD

**Issue by rexlv** [grpc-ecosystem/grpc-gateway#769]
Is that possible using echo/gin/httprouter as request multiplexer instead of runtime.ServeMux?

**Comment by johanbrandhorst** [comment]
Not currently as far as I know. The `runtime.ServeMux` implements `http.Handler` though, so you can use your own router and only use the ServeMux to handle a subset of routes.

**Comment by eldad87** [comment]
@rexlv, 

Like @johanbrandhorst mentioned, here is my working proposal for [grpc-gateway running with Gin-gonic](https://github.com/eldad87/go-boilerplate/commit/29bd2836142aa041330e1940c5ccce95e07bec23#diff-9e8f6f8fdec41b0a5b9062dbad4fb6f0R267).

**Comment by dvcrn** [comment]
This is a little older but I had the same question. Here's how you do it in chi:

```

	mux := runtime.NewServeMux()
	opts := []grpc.DialOption{grpc.WithInsecure()}
	err = apiv1.RegisterXXXXXHandlerFromEndpoint(ctx, mux, fmt.Sprintf("localhost:%s", env.GRPCServerPort), opts)
	if err != nil {
		return err
	}

	r := chi.NewRouter()
	r.HandleFunc("/api/*", func(w http.ResponseWriter, r *http.Request) {
		// gateway is generated to match for /v1/ and not /api/v1
		// we could update the gateway proto to match for /api/v1 but
		// it shouldn't care where it's mounted to, hence we just rewrite the path here
		r.URL.Path = strings.Replace(r.URL.Path, "/api", "", -1)
		mux.ServeHTTP(w, r)
	})
```

In short, make sure that either gateway is generated to match the correct URLs or use a handler to replace whatever prefix you added

**Comment by jaronnie** [comment]
my example:
```go
mux := runtime.NewServeMux()
opts := []grpc.DialOption{grpc.WithInsecure()}
proto.RegisterCoreHandlerFromEndpoint(context.Background(), mux, "0.0.0.0:"+"9603", opts)
engine := gin.Default()
engine.Any("/*any", gin.WrapF(mux.ServeHTTP))
engine.Run("0.0.0.0:8090")
```

**Comment by valiner** [comment]
> my example:
> 
> ```go
> mux := runtime.NewServeMux()
> opts := []grpc.DialOption{grpc.WithInsecure()}
> proto.RegisterCoreHandlerFromEndpoint(context.Background(), mux, "0.0.0.0:"+"9603", opts)
> engine := gin.Default()
> engine.Any("/*any", gin.WrapF(mux.ServeHTTP))
> engine.Run("0.0.0.0:8090")
> ```

niuB
