### ISSUE TITLE
`error` and `message`  field  repeat in error output ?

### ISSUE THREAD

**Issue by ti** [grpc-ecosystem/grpc-gateway#778]
in https://github.com/grpc-ecosystem/grpc-gateway/pull/718, the status code change.
before this merge:
```
{
    "error": "error_enmu",
    "code": 3
}
```
after:

```
{
    "error": "error_enmu",
    "message": "error_enmu",
    "code": 3
}
```
and this code is really affect our public restful document, here is my point:
in http document:
the `error` is some enmu for program to handle it, the `message` is just something details for debug, it is not the samething.

in  https://github.com/grpc-ecosystem/grpc-gateway/pull/718 's detail,  the reason of this code, is just `local ESP a bit annoying`, this is some ...  arbitrary 😢。

## Question:

Does anyone have same problem for restful current document? how to fix it if i use envoy grpc2restful gateway?

@ffredsh  @yugui

**Comment by achew22** [comment]
It should be very easy to post-process the yaml and remove anything that doesn't fit. You could also submit a PR to disable it by flag and then in 2.0 we can make it the default.

Which path interests you more or would you be interested in forging a third path?

**Comment by ti** [comment]
@johanbrandhorst  you can not config runtime.HTTPError in   envoy grpc2restful gateway.

**Comment by johanbrandhorst** [comment]
The envoy grpc gateway is not related to this project, as far as I know, you will have to ask them.

**Comment by ti** [comment]
the envoy is just a example. this change is will affect most of projects use grpc-gateway, such as go-micro.

@johanbrandhorst do you think the in https://github.com/grpc-ecosystem/grpc-gateway/pull/718 is really ok? , i mean the @achew22 's answer is the right way, "You could also submit a PR to disable it by flag and then in 2.0 we can make it the default."

**Comment by johanbrandhorst** [comment]
Personally, yeah, I think mapping the gRPC server response to a JSON marshalling of the `google.rpc.Status` type makes a lot of sense. I think that should be the default in 2.0, but it's obviously up for discussion. As for what we can do right now, turning it off with a flag is fine as well, but we can't change the default behaviour, and if you absolutely _must_ change this, it's already possible with a custom `HTTPError` method, so I don't think we need a flag at all.

**Comment by johanbrandhorst** [comment]
This will be fixed in v2
