### ISSUE TITLE
How can I support different versions of APIs with same proto?

### ISSUE THREAD

**Issue by vaishalig2693** [grpc-ecosystem/grpc-gateway#780]
Consider I have proto which has 4 fields - {a,b,c,d}
For Apis, I want v1 version to show it as - {A,B,C} // Note: here one field is skipped and all are in caps.
For v2 version, I want it as - {a,b} // Here two fields are skipped and names remain same.

How can I configure to achieve the above?

**Comment by johanbrandhorst** [comment]
I think you have to define two different methods:
```
service MyServer {
    rpc MyMethodV1(MyMethodV1Request) returns (MyMethodResponse) {
        option (google.api.http) = {
            post: "/api/v1/my_method"
        };
    }
    rpc MyMethodV2(MyMethodV2Request) returns (MyMethodResponse) {
        option (google.api.http) = {
            post: "/api/v2/my_method"
        };
    }
}

message MyMethodV1Request {
    string a = 1;
    string b = 1;
    string c = 1;
}

message MyMethodV2Request {
    string a = 1;
    string b = 1;
}
```
Though I'm unsure what you mean by the capilisation or and extra variables? Is this what you wanted?
