### ISSUE TITLE
Mac OS X - Note about your tutorial

### ISSUE THREAD

**Issue by Emixam23** [grpc-ecosystem/grpc-gateway#787]
## macOS High Sierra Version 10.31.6

Hey !

Can you add that for mac os x users? The following lines might be usefull in order to follow your tutorial/README.md

    sudo chown -R $(whoami) /usr/local/share/man/man8
    brew install automake
    brew install libtool

Also, be careful because `make check` doesn't seems to work for mac os x

    MacBook-Pro-de-Emixam23:protobuf emixam23$ make check
    Making check in .
    /Applications/Xcode_9.4.1.app/Contents/Developer/usr/bin/make  check-local
    Making lib/libgmock.a lib/libgmock_main.a in gmock
    /bin/sh: line 0: cd: third_party/googletest/googletest: No such file or directory
    make[2]: *** [check-local] Error 1
    make[1]: *** [check-am] Error 2
    make: *** [check-recursive] Error 1

I also had to remove `protoc-gen-go/generator/generator.go` because I had the following warning:

    MacBook-Pro-de-Emixam23:src emixam23$ go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
    # cd /........PATH__TO__PROJECT.........../src/github.com/golang/protobuf; git pull --ff-only
    error: Your local changes to the following files would be overwritten by merge:
	protoc-gen-go/generator/generator.go
    Please commit your changes or stash them before you merge.
    Aborting
    Updating aa810b6..5e707b2
    package github.com/golang/protobuf/proto: exit status 1

Hope it helps :)

**Comment by johanbrandhorst** [comment]
I'm confused, what were you trying to do? You shouldn't need to run make at all. All you need is to go get the binary. Which tutorial are you referring to?

**Comment by Emixam23** [comment]
I am talking about the https://github.com/grpc-ecosystem/grpc-gateway/blob/master/README.md, sorry if I confused you

**Comment by johanbrandhorst** [comment]
Yeah we really need to update these instructions, they are _ancient_. You don't need to build protoc anymore, v3 is out of beta for... 2 years :joy:.

**Comment by Mnw2212** [comment]
Hi @johanbrandhorst , I faced the same issue and it took me a couple of hours of googling to get here.
Would love to update the documentation. It might save time for a lot of people.

**Comment by Emixam23** [comment]
Thanks @Mnw2212 :)
