### ISSUE TITLE
Why the rctx is substituted by a new empty context?

### ISSUE THREAD

**Issue by curelyreas** [grpc-ecosystem/grpc-gateway#788]
https://github.com/grpc-ecosystem/grpc-gateway/blob/ab0345bb328757bfef2f3d7d4e642e182eb985b9/protoc-gen-grpc-gateway/gengateway/template.go#L427

It breaks the life cycle of a request information delivery.

**Comment by johanbrandhorst** [comment]
This only adds things to the existing context, see the signature of runtime.AnnotateContext: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/context.go#L59
