### ISSUE TITLE
REST gateway over RPCS?

### ISSUE THREAD

**Issue by vaishalig2693** [grpc-ecosystem/grpc-gateway#789]
I have some existing rpc clients which communicate over http1.1. Thus I cannot update my server to grpc server but still want to provide REST support to new clients. Is there a way to achieve it without moving to grpcs? If there is any other workaround possible without changing the clients, that will also be helpful.

**Comment by johanbrandhorst** [comment]
Hi @vaishalig2693. This isn't really an issue so I will try to answer your question and then close it and redirect you to the channels we recommend in the issue template.

It's possible to expose both gRPC and REST on the same server, or even the same port. See https://coreos.com/blog/grpc-protobufs-swagger.html for an example. I'm not sure exactly what you're asking though. Can you direct your further questions to the `#grpc-gateway` channel on gopher slack?

**Comment by johanbrandhorst** [comment]
See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/ISSUE_TEMPLATE.md#i-still-have-a-problem.

**Comment by vaishalig2693** [comment]
As I said, I can't run a grpc server as it is over http2 protocol and my existing clients using http1.1 protocol will fail

**Comment by ivucica** [comment]
I've successfully used [cmux](https://github.com/soheilhy/cmux) to put both HTTP/2 + gRPC frontend and an HTTP/1.1 frontend on the same port.
