### ISSUE TITLE
Proposal: pre-compiled per-platform release binaries

### ISSUE THREAD

**Issue by jgiles** [grpc-ecosystem/grpc-gateway#790]
Currently it can be tricky for teams to ensure they are using consistent versions of protoc-gen-grpc-gateway (and protoc-gen-swagger). For example, the installation instructions on the repo suggest `go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` - which recently led to out-of-sync generated code when new folks joined our team.

Version management is particularly important here because these tools are typically part of build processes which are meant to be reproducible.

It would be great to have pre-compiled, per-platform release binaries, similar to protoc https://github.com/protocolbuffers/protobuf/releases or dep https://github.com/golang/dep/releases

A set of release binaries would also make grpc-gateway easy to integrate with version-management tooling such as https://github.com/asdf-vm/asdf

(I'm happy to help with this, but attaching binaries to releases is something you can't do in a PR)

**Comment by johanbrandhorst** [comment]
Hi @jgiles, thanks for the suggestion! I don't see why not, but we don't have a way to create them automatically in CI so they'd just be binaries uploaded by the maintainer who makes the release. I think the assumption thus far has been that you have go installed and so can build the specific version you need. If you're using `dep` for example you can specify `protoc-gen-grpc-gateway` as a required dependency and then install the binary from vendor. But, again, sure why not! Are you particularly interested in any specific releases? I can upload the last 5 or so for Linux, Windows and OSX trivially.

**Comment by johanbrandhorst** [comment]
I've uploaded some pre-built binaries for v1.5.1 (the latest release): https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.5.1. Do you need any other release made?

**Comment by jgiles** [comment]
Thank you! It would also be nice to have `protoc-gen-swagger` in addition to `protoc-gen-grpc-gateway`.

I'm planning to publish an asdf https://github.com/asdf-vm/asdf plugin for installing versions by release tag, so *ideally* we'd have pre-compiled binaries for each release (existing and future). But without automation I guess that gets a little tedious :-/. I've never used CircleCI before, but it looks like it could be configured to publish the releases? https://circleci.com/blog/publishing-to-github-releases-via-circleci/

**Comment by johanbrandhorst** [comment]
That's sounds fantastic - I'll see what we can do!

**Comment by johanbrandhorst** [comment]
I've added `protoc-gen-swagger` binaries as well and I'm investigating automating this for future releases, thanks for the heads up!
