### ISSUE TITLE
Tests possibly failing in release v1.5.1

### ISSUE THREAD

**Issue by nicolasStevenin** [grpc-ecosystem/grpc-gateway#792]
Hi,
I'm using go 1.11

**command: go test -buildmode pie -compiler gc -ldflags "-X github.com/grpc-ecosystem/grpc-gateway/version.commit=fdcb0d026242e8895d157a6637c7366e612f2594 -X github.com/grpc-ecosystem/grpc-gateway/version=1.5.1 -extldflags '-Wl,-z,relro  '"**

```
github.com/grpc-ecosystem/grpc-gateway/runtime
--- FAIL: TestJSONPbEncoder (0.00s)
    marshal_jsonpb_test.go:274: strings.Contains("{\"singleNested\":{},\"uuid\":\"6EC2446F-7E89-4127-B3E6-5C05E6BECBA7\",\"nested\":[{\"name\":\"foo\",\"amount\":12345}],\"uint64Value\":\"18446744073709551615\",\"repeatedStringValue\":[],\"oneofString\":\"bar\",\"mapValue\":{\"a\":\"ONE\",\"b\":\"ZERO\"},\"mappedStringValue\":{},\"mappedNestedValue\":{},\"timestampValue\":\"1970-01-01T00:00:00Z\",\"repeatedEnumValue\":[]}", "ONE") = true; want false
FAIL
exit status 1
FAIL    github.com/grpc-ecosystem/grpc-gateway/runtime  0.025s

```

Thanks

**Comment by johanbrandhorst** [comment]
Hi @nicolasStevenin. I don't really understand this issue. The tests are passing in our CI tests. What is your concern? Are the tests failing on version 1.5.1? We need more information here.

**Comment by johanbrandhorst** [comment]
I'm gonna close this as the original reporter hasn't clarified their issue.
