### ISSUE TITLE
Support for Any types

### ISSUE THREAD

**Issue by codefx9** [grpc-ecosystem/grpc-gateway#80]
I am using `Any` type as described in https://github.com/golang/protobuf/issues/60. But GRPC gateway will transform this into a base64 encoded string from  a byte[]. How can Any type be converted into a JSON object given the byte[] is JSON data?

**Comment by yugui** [comment]
I am not sure, but maybe go-protobuf does not yet support fields of `Any` type?

**Comment by sadlil** [comment]
@yugui we can use `Any` type currently with custom Marshaller. IE.

```
func MarshalAny(instance proto.Message) (*Any, error) {
	name := proto.MessageName(instance)
	marshaledInstance, err := proto.Marshal(instance)
	if err != nil {
		return nil, err
	}
	return &Any{
		TypeUrl: name,
		Value:   marshaledInstance,
	}, nil
}

func (a *Any) UnMarshal() (interface{}, error) {
	messageType := proto.MessageType(a.TypeUrl).Elem()
	instance := reflect.New(messageType).Interface().(proto.Message)
	err := proto.Unmarshal(a.Value, instance)
	if err != nil {
		return nil, err
	}
	return instance, nil
}
``` 

Using it with the gateway just converts the any struct into json with the []byte feilds with base64 encoded string.

**Comment by peter-edge** [comment]
https://github.com/golang/protobuf/issues/50
https://go.pedge.io/pb

**Comment by sadlil** [comment]
@yugui probably they are adding any [golang/protobuf](https://github.com/golang/protobuf/commit/1cc4d6fa4abfabc2fe9cb202f3f1dde0e1032e86)

**Comment by TamalSaha** [comment]
@yugui, any plans to add support for any types?
