### ISSUE TITLE
Unable to add protobuf wrappers in url template option

### ISSUE THREAD

**Issue by mayank-dixit** [grpc-ecosystem/grpc-gateway#808]
## Pre
1. Using string value from: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto
2. protoc version: 3.6.1

## Steps
My proto file looks like this:
>[helloworld.proto](https://github.com/mayank-dixit/examples/blob/master/grpc-gateway/protobuf-wrappers-in-url-template/helloworld.proto)
```
syntax = "proto3";

package helloworld;

import "google/api/annotations.proto";
import "google/protobuf/wrappers.proto";

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      get: "/say/{strVal}"
    };
  }
}

message HelloRequest {
  google.protobuf.StringValue strVal = 5;
}

message HelloReply {
  string message = 1;
}

```

And then I try compile protos:
```
protoc -I/usr/local/include -I. \
  -I$GOPATH/src \
  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
  --go_out=plugins=grpc:. \
  helloworld/helloworld.proto
```
Works fine. And then I try to generate reverse proxy using:
```
protoc -I/usr/local/include -I. \
  -I$GOPATH/src \
  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
  --grpc-gateway_out=logtostderr=true:. \
  helloworld/helloworld.proto
```

### expected:
Successful compilation

### result: 
```
--grpc-gateway_out: aggregate type TYPE_MESSAGE in parameter of Greeter.SayHello: strVal
```

**Comment by johanbrandhorst** [comment]
I've no idea why this is erroring, have you had a chance to do some debugging?

**Comment by mayank-dixit** [comment]
Yes, I tried to debug:
Error is thrown from:
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/descriptor/services.go#L221
Where it doesn't find `*target.TypeName`(_.google.protobuf.StringValue_) to be a well known type.

Recognised well-known types are added here:
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/descriptor/types.go#L453

**Comment by johanbrandhorst** [comment]
Huh, interesting, perhaps we just need to add the rest of the well known types there?

**Comment by mayank-dixit** [comment]
I'm adding other types. It's passing. I'll verify end to end once. if all goes fine, I'll raise a PR?

**Comment by johanbrandhorst** [comment]
Yes, thanks a lot!

**Comment by achew22** [comment]
Fixed by #809. Thanks for your PR!

**Comment by johanbrandhorst** [comment]
It appears the MR discussed #809 just generates invalid code. @mayank-dixit are you interested in submitting a PR which adds the functions?

**Comment by johanbrandhorst** [comment]
Nevermind, still confused, continue discussion in #809

**Comment by johanbrandhorst** [comment]
Reopening as there's definitely a problem with the current code, see https://github.com/grpc-ecosystem/grpc-gateway/pull/809#discussion_r233921470

**Comment by johanbrandhorst** [comment]
_Still_ not fixed, reopening
