### ISSUE TITLE
Please release the repo, IOReaderFactory is not available on the latest release!

### ISSUE THREAD

**Issue by moorara** [grpc-ecosystem/grpc-gateway#823]
The `IOReaderFactory` on `github.com/grpc-ecosystem/grpc-gateway/utilities` is not available on latest release (1.5.1). As a result, when using dependency manager tools like dep, a generated `*.pb.gw.go` file cannot be compiled.

**Comment by johanbrandhorst** [comment]
This is only true if you don't version the generator together with the runtime library. If you're using `dep` it will mean adding it as a required dependency and installing from vendor:

```
required = [
    "github.com/grpc-ecosystem/grpc-gateway-boilerplate/protoc-gen-grpc-gateway"
]
```
```sh
$ go install ./vendor/github.com/grpc-ecosystem/grpc-gateway-boilerplate/protoc-gen-grpc-gateway
```

**Comment by johanbrandhorst** [comment]
That said, we do need a release. I will close this though since it's not really an issue.
