### ISSUE TITLE
A question about generating file protoc-gen-grpc-gateway/gengateway/template.go

### ISSUE THREAD

**Issue by DaHuMao** [grpc-ecosystem/grpc-gateway#864]
Hello:
        I am a rookie. I have a question. When I modified the template.go file in the github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/gengateway/ directory, the *.pb.gw.go file did not change.
        Looking forward to your reply！

**Comment by achew22** [comment]
@DaHuMao, per the issue template, can you please document the steps that you have tried to alleviate your problem?

**Comment by DaHuMao** [comment]
@achew22 I need to insert some custom code into the *.pb.gw.go, but I don't want to have to modify it every time I generate a *.pb.gw.go file, so I tried to modify the generated template file in gprc-gateway: template.go.After the modification, I generated the *.pb.gw.go file again. I found that template.go was not called at all when the file was generated。Is the generated template not the template.go file in the github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/gengateway/ directory?

**Comment by johanbrandhorst** [comment]
@DaHuMao did you reinstall the generator after changing the template file? If there's something you want changed about the generated file, why not raise an issue and make a pull request, maybe everyone who uses this project could use it?

**Comment by DaHuMao** [comment]
@johanbrandhorst I am just a rookie ,who just starting to learn this aspect.
I want to change the build template because of the specific requirements of the project. Do you mean i should reinstall protobuf if i want to change it.

**Comment by DaHuMao** [comment]
@johanbrandhorst  I had reinstalled protobuf ,but i did not work

**Comment by johanbrandhorst** [comment]
I mean `protoc-gen-grpc-gateway`, not `protoc`. After changing the template you need to run `go install ./protoc-gen-grpc-gateway` from the root of this repo. That should fix your problem.

**Comment by johanbrandhorst** [comment]
I'm going to close this as it's not really an issue related to the repo. Please join the slack channel if you need more direct assistance.

**Comment by DaHuMao** [comment]
@johanbrandhorst  OK，Thank you very much！

**Comment by yugui** [comment]
@DaHuMao 
I did not expect users would need to modify `template.go` when I wrote it. If you do, obviously you need to rebuild protoc-gen-grpc-gateway itself, reinstall it and then you need to regenerate your codes.

But before trying directly modifying `template.go`, please take a look at https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html. It might give a better solution.
Also please note that you don't need to modify the generated code if you just need to *add* some methods and/or variables into the package. Golang allows you to simply add another hand-written .go file into the same package.

**Comment by DaHuMao** [comment]
@yugui Thank you for your advice. But i want to handle the error and the message in *.pb.gw.go,befor they  passed into the client function,not just add some function  to *.pb.gw.go
