### ISSUE TITLE
swagger error

### ISSUE THREAD

**Issue by vtolstov** [grpc-ecosystem/grpc-gateway#867]
i have proto that contains:
```
service VolumesService {                                                                            
  rpc VolumesImport(stream Chunk) returns (VolumesImportRsp) {                                      
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {                        
      operation_id: "VolumesImport";                                                                
    };                                                                                              
    option (google.api.http) = { put: "/api/v2/volumes/{volume_id}"; body:"*"; };      
  }                                                                                                 
}
```

when i'm try generate swagger, it oututs:
--swagger_out: cannot use path parameter in client streaming

as i understand in case of stream from client, i can't use path like "/api/v2/volumes/{volume_id}".
How to deal with this? I have method that via post create new volume and returns it uuid, after that i can put to it data via stream.

**Comment by johanbrandhorst** [comment]
The gRPC gateway does not support client side streaming at this time. If you want to upload a file you will have to use multi-part uploads on a separate handler.

Closing as this has been covered in other issues. Please let me know if there's anything else you would like to ask.

**Comment by vtolstov** [comment]
but why i can't generate swagger? i don't want to use grpc-gateway, i'm use only swagger generator from proto files.

**Comment by achew22** [comment]
The provided gateway doesn't support it, that's why you can't generate swagger for it. if you would like to extend the swagger generator to support this, I would be happy to merge your pull request.
