### ISSUE TITLE
Improve README with AWS API Gateway findings

### ISSUE THREAD

**Issue by fahernandez** [grpc-ecosystem/grpc-gateway#868]
After trying to import swagger generated documentation into AWS API gateway I discover some helpful information that can be shared in README file to help other people through this process:

1. Remove model circular dependencies.
2. Remove security-related annotations (This annotation aren't well supported by the import functionality).
3. Max length of the fields is reviewed by the parser but the errors aren't self-explanatory. Review the [documentation](https://swagger.io/specification/v2/) to verify that the requirements are met.
4. API gateway errors aren't good enough for troubleshooting so I recommend using this [page](https://apidevtools.org/swagger-parser/online/) for structure validation.

**Comment by fahernandez** [comment]
Documentation was added on [this](https://github.com/grpc-ecosystem/grpc-gateway/pull/869)

**Comment by johanbrandhorst** [comment]
Closed by #869
