### ISSUE TITLE
& is escaped as \u0026 in restful response

### ISSUE THREAD

**Issue by muyuren** [grpc-ecosystem/grpc-gateway#871]
& is escaped as \u0026 in restful response

**Comment by johanbrandhorst** [comment]
Could you provide an example of this happening? Is it being escaped in the output JSON? It doesn't sound right if so.

**Comment by muyuren** [comment]
Use the code shown below in grpc server
```
func (s *server) Echo(ctx context.Context, in *pb.StringMessage) (*pb.StringMessage, error) {
	return &pb.StringMessage{Value: "test.com?a=1&b=2"}, nil
}
```
then
```
curl localhost:8080/v1/example/echo -X POST -d "value=xxx"
```
the output is 
```
{"value":"test.com?a=1\u0026b=2"}
```

**Comment by johanbrandhorst** [comment]
Interesting, this could be testable by using the `jsonpb` marshaller to marshal this type manually. Can you see what `jsonpb.MarshalToString(&pb.StringMessage{Value: "test.com?a=1&b=2"})` prints? Where `jsonpb` is https://github.com/golang/protobuf/tree/master/jsonpb.

**Comment by muyuren** [comment]
The result is still
```
{"value":"test.com?a=1\u0026b=2"}
```

**Comment by johanbrandhorst** [comment]
Great, could you please raise an issue against https://github.com/golang/protobuf instead then? This is not something we can change in the grpc-gateway, sorry! You can always configure your own marshaler though.
