### ISSUE TITLE
Update the build environment Dockerfile to Go 1.12

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#885]
It's currently locked to using Go 1.11 as per https://github.com/grpc-ecosystem/grpc-gateway/pull/884. Upgrading to 1.12 was causing some builds to fail, so it should be made as part of a separate pull request.

**Comment by johanbrandhorst** [comment]
Might want to consider other dependencies in the same file at the same time, namely `protoc` is still 3.1.0.

**Comment by MichaHoffmann** [comment]
Hey, is this still up for grabs?

**Comment by johanbrandhorst** [comment]
It's going to be a little hard to do without push access to the build-env-image docker hub repo, so I assigned it to myself. Sorry it's probably a bit poorly labeled.
