### ISSUE TITLE
Change in behavior of streaming request body (1.4.1 vs 1.8.1)

### ISSUE THREAD

**Issue by happyalu** [grpc-ecosystem/grpc-gateway#894]
### Steps you follow to reproduce the error:

I was using grpc-gateway (1.4.1) with github.com/tmc/grpc-websocket-proxy for using websockets to do bidirectional streaming. I recently updated to 1.8.1 and noticed that my web client was not behaving as expected. Further analysis showed that:
- the websocket proxy was reading messages from the browser appropriately and forwarding them to grpc-gateway,
- my grpc server was not receiving any messages.

I also saw that [this issue](https://github.com/tmc/grpc-websocket-proxy/issues/14) has been reported on the websocket-proxy project. 

It seems that the communication between the websocket proxy and the grpc server is blocked by ioutil.ReadAll. If I used a modified websocket proxy code that closes the request body after a few messages, the grpc server receives all the messages.

### What did you expect to happen instead:
The grpc server should receive each message as the websocket sends it. 

### What's your theory on why it isn't working:

This does seem to be related to the ioutil.ReadAll on the request Body.

**Comment by johanbrandhorst** [comment]
Thanks for reporting this bug, as discussed this should be fairly easily resolved for the bidi and client streaming case by not using the ReaderUtil method (since we don't need it there anyway).

**Comment by johanbrandhorst** [comment]
See https://github.com/tmc/grpc-websocket-proxy/issues/14#issuecomment-469600346 for more information.
