### ISSUE TITLE
"make test" fails with go mod error

### ISSUE THREAD

**Issue by happyalu** [grpc-ecosystem/grpc-gateway#895]
Step 5 in the [Contributing Guide](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md) asks to run "make test". 

When I ran `make test`, the tests failed with:
```
go: google.golang.org/cloud@v0.36.0: parsing go.mod: unexpected module path "cloud.google.com/go"
```

It [seems](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/.circleci/config.yml) that the CI is not running "make test". 

Running `go test ./...` on a fresh clone ran without errors.

**Comment by johanbrandhorst** [comment]
Thanks for raising this issue. We need to look into what `make test` does that `go test ./...` doesn't cover, if anything. It may be we no longer need `make test`. The go mod error is indicative of something wrong with the mod file though which is also worrying.

**Comment by johanbrandhorst** [comment]
See also: https://github.com/grpc-ecosystem/grpc-gateway/issues/915. We'd love help to fix this!

**Comment by zachgersh** [comment]
@johanbrandhorst - I think I've taken care of this now. `make test` does work now. Think you can close.

@happyalu - try it again if you have time!
