### ISSUE TITLE
Allow gRPC-Gateway to forward gRPC traffic to downstream server on Gateway port

### ISSUE THREAD

**Issue by chrispsommers** [grpc-ecosystem/grpc-gateway#905]
Can grpc-gateway be used to proxy in front of an existing gRPC service? I'd like to present a unified TLS server like in the examples, which would either pass gRPC directly to another gRPC server, or else translate REST into the equivalent gRPC and pass onto another server. I don't want to implement any of the services in the gateway itself. Then I can just drop it inline with an existing service (listening on localhost) and present an external combined REST/gRPC service. Thanks.

**Comment by achew22** [comment]
Hey @chrispsommers, thanks for reaching out.

> Can grpc-gateway be used to proxy in front of an existing gRPC service? I'd like to present a unified TLS server like in the examples, which would either pass gRPC directly to another gRPC server, or else translate REST into the equivalent gRPC and pass onto another server. I don't want to implement any of the services in the gateway itself. Then I can just drop it inline with an existing service (listening on localhost) and present an external combined REST/gRPC service. Thanks.

If I'm parsing your question correctly, yes I believe grpc-gateway is capable of doing that. You could compile a gateway binary and deploy it as a separate program next to your main gRPC server. When you say "unified TLS server" does that mean a TLS server that handles both HTTP (translating them into gRPC requests and proxies gRPC directly to the upstream server? If that's the case, we don't have any provisions for proxying gRPC directly as of today. I believe there are a few projects that do proxy gRPC requests and you could probably stitch the two together but I don't know of any examples that you could use as a guide, sorry.

**Comment by chrispsommers** [comment]
Hi @achew22 Thanks for the quick reply. I was indeed asking about using this gateway to proxy to another gRPC server; it wouldn't sit alongside it as much as in front of it. I'm thinking about what I saw in https://github.com/grpc/grpc-web where they use Envoy https://www.envoyproxy.io/ to translate from gRPC-web (supported by browsers) into gRPC protobufs. It would be neat if this grpc-gateway could do that too, so the whole solution could be smaller and the code easier to customize. Just a thought! ANyway this is a neat project.

**Comment by johanbrandhorst** [comment]
I've renamed the issue to make it clearer what the feature requested is. I'm not sure exactly how this would work right now, but it might be possible to combine the gateway mux with https://github.com/mwitkow/grpc-proxy.

**Comment by chrispsommers** [comment]
@johanbrandhorst  Thanks, I looked at https://github.com/mwitkow/grpc-proxy and indeed it looks like it does the proxying like I'd imagined, it even allows deciding based on the service being called. Putting that director/reverse proxy just "above" the internal gRPC servicer in this gateway would let it handle some services via REST/gRPC and redirect others to another gRPC server. That would be very powerful.
