### ISSUE TITLE
go get: error loading module requirements go 1.11

### ISSUE THREAD

**Issue by labulaka521** [grpc-ecosystem/grpc-gateway#915]
## I still have a problem!
 go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding grpc.go4.org latest
go get: error loading module requirements

go version:
go version go1.11.5 darwin/amd64

**Comment by johanbrandhorst** [comment]
What command did you run to get this error?

**Comment by labulaka521** [comment]
i run command  `go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` in my project , and project container file go.mod,  then get errors,  my project file go.mod container golang.org/x/lint, i guess they confiect,
but when i run this command in other directory without go.mod, it is successful, because it is installed my global env.

**Comment by johanbrandhorst** [comment]
Thanks for your bug report. I'll just add this to #895 as that already lists similar errors, we should fix them together.
