### ISSUE TITLE
401 Unauthorized response doesn't contain WWW-Authenticate header

### ISSUE THREAD

**Issue by philippgille** [grpc-ecosystem/grpc-gateway#917]
I asked in the official gRPC Gitter channel, but didn't get a response so far: https://gitter.im/grpc/grpc?at=5ca0e2c1016a930a453cdc6d

Working on https://github.com/lightningnetwork/lnd/issues/2332, where this question came up.

Maybe related to grpc-gateway issues #4, #221 and #309.

### Steps you follow to reproduce the error:

When returning a `code.Unauthenticated` gRPC error, grpc-gateway maps this to a response with a 401 Unauthorized HTTP status code.

The response doesn't contain a WWW-Authenticate error though.

### What did you expect to happen instead:

According to the HTTP specification https://tools.ietf.org/html/rfc7235#section-3.1, a 401 Unauthorized response "MUST" be accompanied by a WWW-Authenticate header.

I understand that no static value like `WWW-Authenticate: Basic realm="simple"` can be used, as it completely depends on the used authentication scheme, but maybe there can be a way to _easily_ configure this when setting up the gateway?

I know that error responses can be customized (apparently in two different ways: via [response forwarder](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/_docs/customizingyourgateway.md#replace-a-response-forwarder-per-method) and via [custom error handler](https://mycodesmells.com/post/grpc-gateway-error-handler)), but shouldn't there be a way for grpc-gateway to adhere to the HTTP specification by default?

Also, from my understanding you can't just add a header in those response customizations, but instead you have to create a complete response, which could lead to inconsistent responses or breaking changes, but I'm not sure about this.

### What's your theory on why it isn't working:

I think setting the WWW-Authenticate header is just not implemented and I didn't find an easy way to set one (other than using one of the above mentioned response customizations).

I think the implementation is this one: https://github.com/grpc-ecosystem/grpc-gateway/blob/7aca14d0a16247151f6e423f4cbfbd75a1bd4776/runtime/errors.go#L88

**Comment by johanbrandhorst** [comment]
Thanks for this bug report! This sounds like something we could enable by default as you say. What would be a reasonable value to put in the authenticate header if one isn't set?

Would you be interested in contributing this? I think it's be as simple as changing the behaviour of the DefaultHTTPError method as you say. We could detect this error code and set the header to a default value and also allow the user the configure the string value returned. What can I do to help you make this a reality?

**Comment by philippgille** [comment]
Thanks for the quick reply! Yes I'm interested in contributing this.

I'm not sure if we can set a reasonable default value though, I think we might need to rely on a user configured value.

I didn't work with grpc-gateway a lot yet, so I don't know where the user typically passes configuration in a programmatical way. Maybe as a `runtime.ServeMuxOption` when calling `runtime.NewServeMux()`?

**Comment by johanbrandhorst** [comment]
That would be the usual way, yes. Obviously, those are all optional, so the only other option is to only return this header when the user has supplied an option, which is _still_ in violation of the HTTP spec :cry:.

Another alternative altogether is to introduce an automatic translation of some magic gRPC metadata value to the `WWW-Authenticate` header and rely on users setting this magic metadata value (we could export a named constant that users could set whenever they return `codes.Unauthenticated`. I guess that still doesn't get us quite into compliance territory since we would depend on users to set that magic value.

What do you think?

**Comment by philippgille** [comment]
I didn't work with gRPC metadata yet. It sounds to be more flexible when you can set it in a different way for each returned error instead of having to configure it up front when creating the SeverMux. On the other hand this might make it more verbose as well, having to set that with each `Unauthenticated` error (or lead to one more level of indirection when having to call some factored out function that sets the metadata and returns the error).

One requirement to keep in mind is that within a single app multiple authentication schemes could be supported. For example it's probably common that a web service accepts `Basic` credentials, as well as a `Bearer` token for OAuth. Depending on some internal logic the web service could determine which of the schemes is required for the specific request and set the `WWW-Authenticate` header accordingly, on a per-request basis.

**Comment by johanbrandhorst** [comment]
I think setting the header automatically for when we return 401, but allowing the user to override the content via a magic gRPC metadata value seems best. That would make us compliant with the spec, which I think is a reasonable excuse for breaking backwards compatibility in this case.

Would you be interested in contributing this? I could help you get started.

**Comment by jefferai** [comment]
So this got marked as stale, but 401 responses still violate the RFC by not returning this header, which makes this rather timeless until it's fixed. Can it be reopened? :-)

**Comment by momom-i** [comment]
Thank you very much for your kind instruction. It helped me a lot.
I'm not too confident but I intend to complete test so would you check that before moving on?
