### ISSUE TITLE
Read the Http Post Body 

### ISSUE THREAD

**Issue by lakstap** [grpc-ecosystem/grpc-gateway#921]
Suggest me how to do this. 
1) Rest Gateway : Http handler will read the post body (json)
2) Call Rest api to send the request body for metrics collection
3) serve the http request to grpc server.

In short collect the metrics and also send it to grpc server. I am trying to use Ioutil.readall in the second step, after that i am losing request body.

**Comment by johanbrandhorst** [comment]
Hi, missed this the first time around, normally you would do metrics in a gRPC interceptor, so it works for both REST and gRPC traffic. Does that answer the question? I'm gonna close this as it's not a gateway issue, but feel free to ask for more help in #grpc-gateway on Gophers slack.
