### ISSUE TITLE
Merging swagger specs fails to use rpc comments (again)

### ISSUE THREAD

**Issue by co3k** [grpc-ecosystem/grpc-gateway#923]
This is same issue with https://github.com/grpc-ecosystem/grpc-gateway/issues/664 but the current version of grpc-gateway (it might be v1.6.3 or later) has this issue again.

### Steps you follow to reproduce the error:

1. Create `a.proto` and `b.proto` by following https://github.com/grpc-ecosystem/grpc-gateway/issues/664#issue-328698410 instruction
2. Generate the swagger spec without merging: 
```
protoc -I=. \
        -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway \
        -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
        --swagger_out=logtostderr=true:. \
        a.proto b.proto
```
3.  Generate the swagger spec with merging: 
```
protoc -I=. \
        -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway \
        -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
        --swagger_out=logtostderr=true,allow_merge=true:. \
        a.proto b.proto
```
### What did you expect to happen instead:

b.swagger.json has valid summary and description for "ListBars" operation but apidocs.swagger.json doesn't.

### What's your theory on why it isn't working:

I've confirmed v1.6.2 generates a valid merged swagger spec. Changes of v1.6.3 might break this feature: https://github.com/grpc-ecosystem/grpc-gateway/compare/v1.6.2...v1.6.3

Oh, I've tried revert https://github.com/grpc-ecosystem/grpc-gateway/commit/8140d9885335da81d10ae02cff62afff36fb4ae4 and I could get the expected behavior.

**Comment by johanbrandhorst** [comment]
Hi @co3k, sorry this has broken again :disappointed:. I'm a little confused, did you establish that it was working without https://github.com/grpc-ecosystem/grpc-gateway/commit/8140d9885335da81d10ae02cff62afff36fb4ae4 applied?

**Comment by co3k** [comment]
> did you establish that it was working without 8140d98 applied?

Yes. I've confirmed "fix" this problem by the following step.

1. `$ git checkout v1.6.3`
2. `$ git revert 8140d98`
3.  build protoc-gen-swagger
4. you will confirm "resolved" this problem

Of course we really need the 8140d98 changes but these might have some side effects which we should also fix.

**Comment by johanbrandhorst** [comment]
Hm, ideally what we need here is a way to reproduce this with a test case, so we can iterate quickly on a fix and ensure this error doesn't happen again in the future. Would you be interested in trying to fix this? I don't have the time to investigate further.

**Comment by prestonvanloon** [comment]
Has there been any update on this? It seems that it's still broken.

**Comment by johanbrandhorst** [comment]
Not that I know. I think we'll have to revert https://github.com/grpc-ecosystem/grpc-gateway/commit/8140d9885335da81d10ae02cff62afff36fb4ae4 for now and make another release. I'll get on that.
