### ISSUE TITLE
why google/api/http.proto annotations.proto Field Numbers is 72295728 ?

### ISSUE THREAD

**Issue by RedDragonet** [grpc-ecosystem/grpc-gateway#925]
```go
extend google.protobuf.MethodOptions {
  // See `HttpRule`.
  HttpRule http = 72295728; // WHY IS THIS 72295728 ?
}
```
https://github.com/googleapis/googleapis/blob/be3005c8a16e8424d0330e977ac78f2976bf01d3/google/api/annotations.proto#L30

**Comment by achew22** [comment]
I would recommend opening an issue against the googleapis repo, we have no control over those numbers.

**Comment by RedDragonet** [comment]
ok
