### ISSUE TITLE
JSON stream response not available

### ISSUE THREAD

**Issue by issacnitin** [grpc-ecosystem/grpc-gateway#926]
I'm always getting

{"error":"all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake","message":"all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake","code":14}

No idea what is going wrong. Set it all up as mentioned

**Comment by johanbrandhorst** [comment]
This is a generic gRPC error and means your grpc-gateway couldn't connect to it's gRPC server. Please double check your setup and compare against existing examples. This is not something we can fix in the gateway.

If you need more help, swing by the #grpc-gateway channel on Gophers slack.
