### ISSUE TITLE
i import a new gateway.Endpoint without recompile

### ISSUE THREAD

**Issue by developersPHP** [grpc-ecosystem/grpc-gateway#937]
# if i add a new proto file,how can i import a new gateway.Endpoint without recompile.
# Whether or not you can't do that
 Looking forward to your reply
 thank you

**Comment by johanbrandhorst** [comment]
Hi @developersPHP. If you want to add more services to your gateway, you must generate a new gateway file with our protobuf generator plugin. Does that answer the question?

If you have follow up questions please reach out to the #grpc-gateway channel on Gophers slack.

**Comment by developersPHP** [comment]
thank you answer my question!! 
But I don't want to add it statically into my code, can I have an API for dynamic import?

**Comment by johanbrandhorst** [comment]
We don't support anyway of dynamically adding endpoints at this time, no.
