### ISSUE TITLE
json 1.1 api support for grpc-ecosystem to use queryparams with filter

### ISSUE THREAD

**Issue by gauravkasliwal8** [grpc-ecosystem/grpc-gateway#938]
Support this alternative query parameter method.

**Comment by gauravkasliwal8** [comment]
This works : https://myserver.com?filter[name]=test
This does not work https://myserver.com?filter[name][startsWith]=te
When I try to populate query parameters.

**Comment by gauravkasliwal8** [comment]
I am trying to write get api supporting json 1.1 standards.  I am able to write GET api as below : filter[name]=test but not this : filter[name][startsWith]=te as PopulateQueryParameters function does not support this. I would really appreciate any help supporting this. Source : https://jsonapi.org/format/1.1/#query-parameters-families

**Comment by johanbrandhorst** [comment]
The gRPC gateway does not support this standard for query parameters, as you can tell. We support normal dot-separated query parameters at this time which should support your data format already.

If you'd like to, I'd be happy to help you in adding support for this alternative query parameter format. I do not personally have the time to do so though.

Let me know how you wish to proceed.

**Comment by gauravkasliwal8** [comment]
Hi @johanbrandhorst,

Thank you for your reply. Could you please give me example for normal dot-separated query parameters to support my data format? I will try that.

**Comment by johanbrandhorst** [comment]
What does your proto message type look like? AFAIK you can't do nested maps with proto, so I don't understand what you're doing.

**Comment by johanbrandhorst** [comment]
A good source of inspiration for your query parameters are the tests: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query_test.go. You can see the use of maps and nested messages.

**Comment by gauravkasliwal8** [comment]
Hi @johanbrandhorst,

My current proto definition is : map<string, string> filter
and it works with filter[x]=y.

I am looking for how to support JSON 1.1 API standards and change my proto where filter[x][y]=z is also allowed.

**Comment by johanbrandhorst** [comment]
What does `filter[x][y]=z` mean? Assign `z` to both key `x` and key `y`? The grpc-gateway does not support this standard (yet?) so you need to explain what you're trying to do.

**Comment by gauravkasliwal8** [comment]
@johanbrandhorst 

by filter[x][y]=z I mean

say filter[name][startsWith]=ab
filter[age][gte]=10
(gte = greater than equal)
filter[key][operator]=value

**Comment by johanbrandhorst** [comment]
Ah I see. This isn't really possible to auto translate with a gRPC server backend. You'd have to handle that manually. I don't think this is really feasible from the gateway so I'm going to close this. If you have an idea for how to add support for this please reply and I can reopen it.

Something like filter.field=age&filter.operator=GTE&filter.comparator=10 might work but you have to define the whole structure in your proto message.
