### ISSUE TITLE
grpc: received message larger than max

### ISSUE THREAD

**Issue by Lyafei** [grpc-ecosystem/grpc-gateway#943]
help！

    {
        "error": "grpc: received message larger than max (4870953 vs. 4194304)",
        "message": "grpc: received message larger than max (4870953 vs. 4194304)",
        "code": 8
    }

I have modified the grpc configuration：

    grpc.NewServer(grpc.MaxRecvMsgSize(52428800), grpc.MaxSendMsgSize(52428800))

But that doesn't help, right

**How do I set the return value size in the grpc-gateway**

**Comment by johanbrandhorst** [comment]
The value can be configured in the call to register your client, either when creating the `grpc.ClientConn` or when calling `RegisterXServiceHandler`. It is a `grpc.CallOption`: https://godoc.org/google.golang.org/grpc#MaxCallRecvMsgSize, use https://godoc.org/google.golang.org/grpc#WithDefaultCallOptions to configure it for a connection.
