### ISSUE TITLE
protoc-gen-grpc-gateway descriptor pkg and generator visibility

### ISSUE THREAD

**Issue by dan-compton** [grpc-ecosystem/grpc-gateway#951]
Hey folks.  I noticed that the the protoc-gen-grpc-gateway/descriptor package is not visible to external Bazel projects, yet contain exported types.  This means that if you intended to use the [descriptor.Registry](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/descriptor/registry.go#L16) you must *disable visibility checking* during your bazel build.

### Steps you follow to reproduce the error:

1. Import grpc-gateway into external WORKSPACE and write code that depends
on exported types in protoc-gen-grpc-gateway/descriptor.  descriptor.Registry 
is an example of one such type.
2. `bazel //:gazelle && bazel clean --expunge && bazel sync && bazel build ...`

> @com_github_grpc_ecosystem_grpc_gateway//protoc-gen-grpc-gateway/descriptor:go_default_library' is not visible from target '//tools/build_rules/protoc_gen_grpc_gateway_cors:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate

### What did you expect to happen instead:

Be able to depend on exported types in protoc-gen-grpc-gateway descriptor package.

### What's your theory on why it isn't working:

Visibility settings in BUILD files in descriptor package.

**Comment by achew22** [comment]
Interesting question. Can you help me understand the way you're using that registry object? The only things I would expect to call that are internal to the protoc plugin, are you extending the generator in some way? Could we convince you to upstream that code instead?

**Comment by dan-compton** [comment]
I'm cleaning up an old protoc-plugin for quick CORS configuration.  It simply generates an rscors [cors.Options](https://godoc.org/github.com/rs/cors#Options), which can subsequently be used to wrap the ServeMux.   I doubt the use of descriptor.Registry is strictly necessary, but it seems convenient and its exported.

I'd be happy to contribute this if you're interested in a quick way to configure CORS that is more functional than what's seen in the examples.  However, I think that there are more interesting things that could be done upstream on this front without the dependency on rscors.

**Comment by johanbrandhorst** [comment]
@dan-compton feel free to upstream the CORS stuff, but as you say it'd ideally be without any third party dependencies. Can rscors be cut out of the loop?

**Comment by dan-compton** [comment]
@johanbrandhorst  -- It can, yes.
