### ISSUE TITLE
Why grpc gateway does not call grpc callback directly?

### ISSUE THREAD

**Issue by eyudkin** [grpc-ecosystem/grpc-gateway#952]
As I see, grpc gateway works as reverse proxy: it receives http request and calls grpc server via grpc dial to localhost (usually to localhost).
And I dont fully understand, why does it work so complex?
If it works `http -> proto-request -> grpc -> grpc-callback` it theoretically can be simplified to `http -> proto-request -> grpc-callback`.
I mean, if gateway converts http request to proto structure and calls grpc client, then we can call grpc server callback instead of the client part and avoid extra loop ;)

**Comment by achew22** [comment]
@eyudkin great question! The answer is because no one has written it yet. What tools/resources would you need to implement this feature request? How can I help you create the future you want to live in?

**Comment by johanbrandhorst** [comment]
#947 will fix this

**Comment by johanbrandhorst** [comment]
#947 has been merged with support for unary calls directly to the backend server.
