### ISSUE TITLE
EOF when calling Send for client streams

### ISSUE THREAD

**Issue by gustavocovas** [grpc-ecosystem/grpc-gateway#961]
@jonasarilho and I are working on a service with a client-side streaming RPC. We noticed that grpc-gateway does not handle correctly errors that occur before it is done processing the request body. For instance:

1. The gateway receives a request that will result in an UNAUTHENTICATED status from the back-end service, because of invalid credentials that will be forwarded via metadata.
2. The back-end service receives the RPC call and returns the expected status.
3. If the gateway is not done processing the request, [the generated code](https://github.com/grpc-ecosystem/grpc-gateway/blob/0d29f14a9afe84adfbc8760b9fad6b394436fd3e/protoc-gen-grpc-gateway/gengateway/template.go#L256-L259) calls `stream.Send`, which returns `io.EOF`, as described in [the docs](https://godoc.org/google.golang.org/grpc#ClientStream).
4. The returned `io.EOF` results in a `500` status, instead of a `401`.

We believe that adding a verification for `io.EOF` on the generated code template should fix this issue:
```go
if err = stream.Send(&protoReq); err != nil {
	if err == io.EOF {
		break
	}
	grpclog.Infof("Failed to send request: %v", err)
	return nil, metadata, err
}
```

Is this solution in the right direction? Since this would be our first contribution, we appreciate help to turn this into a PR.
Thanks

**Comment by johanbrandhorst** [comment]
TIL we support client side streaming. Cool! This suggestion sounds good to me. Please feel free to open a PR, but we'll probably want to add some tests here as well. I think it'd be cool to add something to the [integration tests](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/integration/integration_test.go). What do you think?
