### ISSUE TITLE
Please make a new release!

### ISSUE THREAD

**Issue by moorara** [grpc-ecosystem/grpc-gateway#963]
When generating our source codes using `protoc`, we always install the latest version of `grpc-gateway` since `protoc` does not work in Go modules mode.

When importing generated codes in our repos, we use Go modules and we use the latest release of `grpc-gateway`.

**Problem**:

Currently, `grpc-gateway` has a breaking change on `master` branch which is not yet released. So, we cannot fix it our repos unless we import the `grpc-gateway` module from `master` instead of semantically versioned releases.

**Comment by johanbrandhorst** [comment]
What error are you seeing? I was under the impression the last error was fixed with the latest release.

**Comment by johanbrandhorst** [comment]
Also, there's no reason protoc shouldn't work in go modules mode that I know of, this repo uses modules and protoc successfully. I would recommend that you version the generator together with your runtime dependency. With Go modules that is done via tool dependencies: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by moorara** [comment]
@johanbrandhorst The `runtime.NewPattern` accepts one more argument which is `runtime.AssumeColonVerbOpt(true)`

**Comment by johanbrandhorst** [comment]
This is included in the `1.9.2` release: https://github.com/grpc-ecosystem/grpc-gateway/blob/v1.9.2/runtime/pattern.go. `1.9.2` should work with `master` (though you should ideally still not use master and a release at the same time). Are you seeing this problem on `1.9.2`?

**Comment by moorara** [comment]
@johanbrandhorst You're right. `1.9.2` includes that change. For some reason, when I run `go mod` does not pick up the `1.9.2` and it picks up `1.9.0` release for our projects.

**Comment by johanbrandhorst** [comment]
I've just released 1.9.3, FYI.
