### ISSUE TITLE
Bazel tests are flaky

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#968]
The bazel tests fail with connection refused errors every now and then. Seems we might need to wait a little longer for the test server to start.

**Comment by johanbrandhorst** [comment]
Happened again today, but seems to be bazel consuming too many resources and the host killing the process? Not quite sure. 

https://circleci.com/gh/grpc-ecosystem/grpc-gateway/3484

**Comment by achew22** [comment]
My vote is that we activate the Bazel team's CI and deactivate the CircleCI based one. Step 1 in that process is here https://github.com/grpc-ecosystem/grpc-gateway/pull/983

**Comment by srenatus** [comment]
Cool. So, in buildkite.com/bazel, test fail consistently. Like this one: https://buildkite.com/bazel/grpc-ecosystem-grpc-gateway/builds/104#8f57d1c1-3082-4a3d-8ad3-f1c35f0bf987

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples/integration:go_default_test
-----------------------------------------------------------------------------
E0911 09:09:51.099595      14 main.go:73] Failed to listen and serve: listen tcp :8080: bind: address already in use
cannot run gateway service: listen tcp :8080: bind: address already in use
```
(from the uploaded test logs in buildkite artifacts)

👀 I guess it's either running test in parallel that shouldn't, or... something else is bound to 8080. Either way, making the tests use a random available port (i.e. binding to `:0`, then retrieving the port that was used) could be an alternative 🤔

**Comment by johanbrandhorst** [comment]
TIL. Sounds like unintentional parallelism to me. Unfortunately I understand nothing of how this works, so I defer to @achew22.

**Comment by srenatus** [comment]
Well, I'm sure our tests would be more robust if they _could_ run in parallel. 😃 But yeah, that's the harder route for sure.

**Comment by drigz** [comment]
FYI, if you add [tags = ["exclusive"]](https://docs.bazel.build/versions/master/test-encyclopedia.html#tag-conventions) for a Bazel test it will not be run in parallel with other tests, so you can use this for tests that bind to a fixed port.

**Comment by johanbrandhorst** [comment]
Flipping stale bot giving me lip

**Comment by johanbrandhorst** [comment]
Still flaky: https://circleci.com/gh/grpc-ecosystem/grpc-gateway/5222

**Comment by johanbrandhorst** [comment]
Sigh

**Comment by adasari** [comment]
@johanbrandhorst still there tests which is uses ports (secondary) in test. listener.Close() is not synchronous and never guarantee that port is available for immediate use in other test. Using unique ports fixes the problem.

**Comment by johanbrandhorst** [comment]
Thanks for pointing that out, it could be worth doing something about, but this issue is specifically around the bazel tests, which are failing independently of the other tests (which run the same tests) due to what looks like resource constraints a lot of the time.

**Comment by johanbrandhorst** [comment]
Might be fixed by caching the bazel artifacts and using explicit limits
