### ISSUE TITLE
why response use enum's name

### ISSUE THREAD

**Issue by t2krew** [grpc-ecosystem/grpc-gateway#970]
I have rewrote code with grpc-gateway, but got the different response.
this is the response what i want:
```json
{
"code": -100,
"info": "缺少参数userid",
"RecordLists": []
}
```
but now i got :
```
{
"code": "PARAMERR",
"info": "缺少参数userid",
"RecordLists": []
}
```
the code in response I use the enum.

and this is my .proto's enum 
```protobuf
// 返回码
enum CODE {
	UNKNOWN = 0;
	OK = 1; // 成功
	REJECT = -1; //
	MISSBIZNO = -10;  // 缺少参数bizno
	MISSBIZTYPE = -11; // 缺少参数biztype
	MISSUSERID = -12; // 缺少参数userid
	MISSNUM = -13; // 缺少参数num
	MISSSIGN = -14; // 缺少参数sign
	INVALIDBIZNO = -20; // 无效的bizno
	UNUSUALBIZNO = -22; // bizno信息异常
	INVALIDBIZTYPE = -21; // 无效的biztype
	UNUSUALBIZTYPE = -23; // biztype信息异常
	INVALIDSIGN = -30; // 签名错误
	INVALIDUSER = -40; // 非会员用户

	PARAMERR = -100; // 参数错误
	UNLOGIN = -101;  // 未登录

	INTERNALERR = -999; // 内部错误
}
```

how to solve this ?

**Comment by johanbrandhorst** [comment]
You can configure your JSON marshaller to output enums as ints.

```go
m := runtime.JSONPb{
    EnumsAsInts: true,
}
mux := runtime.NewServeMux(runtime.WithMarshalerOption("*", &m))
```

**Comment by t2krew** [comment]
@johanbrandhorst it works, thank you so much! :-)

**Comment by johanbrandhorst** [comment]
@t2krew I'm glad it worked for you, but in the future please read the issue template and reach out to us on gophers slack (#grpc-gateway) instead of opening issues. This would've saved us both a lot of time.

**Comment by t2krew** [comment]
@johanbrandhorst ok, i will. Thanks again
