### ISSUE TITLE
Route HTTP calls based on body contents.

### ISSUE THREAD

**Issue by dacruz21** [grpc-ecosystem/grpc-gateway#971]
I have a quick question about "fanning out" calls to the same URL to different gRPC methods based on the body. 

As an example, I have two routes in my gRPC service called `AcceptFriendRequest` and `RejectFriendRequest`. I would like for both of these routes to live on the same HTTP endpoint, differentiated by a `status` field in the body. i.e. if I `PUT /api/friendrequests/{request_id}` with body `{"status":"accepted"}` it calls `AcceptFriendRequest`, and if I call the same route with body `{"status":"rejected"}` it calls `RejectFriendRequest`. 

Is this possible? Thanks!

**Comment by johanbrandhorst** [comment]
I don't think this is possible at the moment - if you made it part of the request path we could route it to different endpoints. We're bound by the definitions in https://github.com/googleapis/googleapis/blob/master/google/api/http.proto, so any additional routing would have to be added as a feature there first.
