### ISSUE TITLE
Is it possible to use protoc-gen-swagger options in my own protos?

### ISSUE THREAD

**Issue by rmilejcz** [grpc-ecosystem/grpc-gateway#976]
I'm trying to use these: https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger/options

I've seen a few disparate examples of people doing things like:

```proto3
import "protoc-gen-swagger/options/openapiv2.proto
```
or:
```proto3
import "grpc-gateway/protoc-gen-swagger/options/annotations.proto
```

but I cannot get this to work and it isn't documented anywhere. I assume I could import it via it's package name so long as it can be found in my $GOPATH but this:
```proto3
import "grpc/gateway/protoc_gen_swagger/options/annotations.proto"
```

also fails with the error:
```
file was not found or had errors
```

I have followed the installation steps to a T and have no issues importing the google options from `"google/api/annotations.proto"` but the protoc-gen-swagger options are eluding me and without any documentation (that I could find) I'm feeling pretty lost.

**Comment by achew22** [comment]
@rmilejcz, thanks for filing an issue. Sorry you're not having a great time.

> [...] I cannot get this to work and it isn't documented anywhere.

and

> [...] the protoc-gen-swagger options are eluding me and without any documentation (that I could find) I'm feeling pretty lost.

@rmilejcz, on the home page for the repo, in 24px font it says "[Check out our documentation!](https://github.com/grpc-ecosystem/grpc-gateway#check-out-our-documentation)", could you help me understand the process you took to get here where you concluded that there was no documentation? Further, the homepage (and therefore the README.md) of the repo is self-contained documentation for driving the project.

What have you tried doing? What documentation have you been referring to? Do you have prior experience with proto and protoc? Have you gone through any tutorials on that front to help you understand how protos and their imports work?

My guess is that you're trying to import in a `.proto` file but haven't manipulated the proto import path as described in section 3 of our [usage documentation](https://grpc-ecosystem.github.io/grpc-gateway/docs/usage.html). Could you share the command you invoked that resulted in this error as well as a complete reproduction of the problem?

**Comment by rmilejcz** [comment]
>@rmilejcz, on the home page for the repo, in 24px font it says "Check out our documentation!", could you help me understand the process you took to get here where you concluded that there was no documentation?

@achew22, in the first sentence of this issue:

>I'm trying to use these: https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger/options

and the title of my question it says:

> Is it possible to use protoc-gen-swagger options in my own protos?

I have followed ALL the steps in the documentation, and have a working gRPC server, gateway, and client. ALL I am trying to do is use the specific options found here: https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger/options

You say *manipulate the import path* as if that should be apparent but it isn't, what does that mean? Section three descibres *Generate a gRPC stub*, which I have done, I have followed every step already to build my own already working gRPC server with gateway that I don't need help with because I read the documentation.

Here is the command I'm invoking to compile my protos:

```bash
  protoc -I/usr/local/include                                                                                                       \
    -I"$GOPATH/src"                                                                                                                    \  
    -I"$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis" \
    --grpc-gateway_out=logtostderr=true:./gateway/protos                                                   \
    --go_out=plugins=grpc:./gateway/protos                                                                            \
    --swagger_out=logtostderr=true:./gateway/swaggerui/swagger                                      \
    --proto_path=./protos                                                                                                            \
    ./protos/*.proto
```

which works **excellently** as long as I don't try to import the **specific files found here**:  https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger/options when I try to import those files it doesn't work, via relative path or absolute path or package name or go package name or anything. My protos do compile without issue otherwise. I have no trouble with any other thing in the documentation found here,  I am only trying to find specific documentation to help me understand the best way to consume those specific files.

I am specifically looking for documentation on how to consume the options defined here: https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger/options specifically `annotations.proto` and `openapiv2.proto`. I specifically am unable to find any documentation with regards to using those options in my own protos to alter the generated `swagger.json` files

**Comment by rmilejcz** [comment]
>@rmilejcz, on the home page for the repo, in 24px font it says "Check out our documentation!", could you help me understand the process you took to get here where you concluded that there was no documentation? Further, the homepage (and therefore the README.md) of the repo is self-contained documentation for driving the project.

I only meant specifically that I couldn't find any documentation with regards to the `protoc-gen-swagger` options. I have already followed the documentation and have a working gRPC server, gateway, and client. Now I'm just trying to find out how to properly import [protoc-gen-swagger/options/annotations.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/options/annotations.proto) and [protoc-gen-swagger/options/openapiv2.proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/options/openapiv2.proto) into my own protos.

>What have you tried doing? What documentation have you been referring to? Do you have prior experience with proto and protoc? Have you gone through any tutorials on that front to help you understand how protos and their imports work?

I've tried importing them via various different names, including absolute and relative paths, their package names, and even desperately their go package names. According to the [proto3 language guide: ](https://developers.google.com/protocol-buffers/docs/proto3#importing-definitions)

>The protocol compiler searches for imported files in a set of directories specified on the protocol compiler command line using the -I/--proto_path

Based on that, I'm invoking this command:

```bash
  protoc -I/usr/local/include                                                     \
    -I"$GOPATH/src"                                                               \
    -I"$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis" \
    -I"$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/"                       \
    --grpc-gateway_out=logtostderr=true:"$abspath"/gateway/protos                 \
    --go_out=plugins=grpc:"$abspath"/gateway/protos                               \
    --swagger_out=logtostderr=true:"$abspath"/gateway/swaggerui/swagger           \
    -I"$abspath"/protos                                                           \
    "$abspath"/protos/*.proto
```
Which I assume should allow me to do this:
```proto3
import "protoc-gen-swagger/options/annotations.proto"
```
since those files can be found under `-I"$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/"`, but when I run that command I get this error:
```
protoc-gen-swagger/options/annotations.proto: File not found.
auth_service.proto:6:1: Import "protoc-gen-swagger/options/annotations.proto" was not found or had errors.
```
I have already followed this *excellent* documentation, and I hope I did not offend anyone with that miscommunication. At this point all I'm trying to do is improve the generated `swagger.json` files via the provided annotations, but I'm having trouble getting it to work and I can't find any reference for how to consume those files. I'm certain I'm doing something wrong but I'm having a hard time figuring out exactly what that is.

**Comment by johanbrandhorst** [comment]
@rmilejcz I think your problems at this point are to do with protoc import paths, which is a problem outside the domain of this repo. This repo contains examples of how to use the annotation in your own protofiles, but it assumes some familiarity with protoc. The reason you can use different import paths in your own protofiles is because the path is relative to your provided protoc import paths.

**Comment by rmilejcz** [comment]
>The reason you can use different import paths in your own protofiles is because the path is relative to your provided protoc import paths.

But `protoc-gen-swagger/options/annotations.proto` *is* relative to `-I"$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/"` which I am passing when running protoc, so what am I missing?

**Comment by rmilejcz** [comment]
@johanbrandhorst yeah I made a foolish mistake, the issue was that I failed to update a script unfortunately and I was running code that did **not** include the protos I wanted via `protoc --proto_path=`. Once I altered the correct script to include:
```bash
-I"$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/"
```
I could properly import without issue
```proto3
import "protoc-gen-swagger/options/annotations.proto"
```

All I can say is thanks for being patient and sorry for the ultimately pointless github issue lol

**Comment by johanbrandhorst** [comment]
Thanks for getting back to us, we've all made a mistake like that at some point 😄!
