### ISSUE TITLE
I want to know how to transfer http+proto to grpc.

### ISSUE THREAD

**Issue by hbgongen** [grpc-ecosystem/grpc-gateway#977]
i want to know how i transfer http+proto to grpc,not http+json to grpc.I find many cases don't solve this problem.

**Comment by johanbrandhorst** [comment]
You can do this with a custom content type and marshaller using runtime.WithMarshaler. The documentation has examples of this.

**Comment by hbgongen** [comment]
> You can do this with a custom content type and marshaller using runtime.WithMarshaler. The documentation has examples of this.

oh~thanks.Is the official grpc-gateway documents in the Readme.md?
I'm very appreciated if you can support the url path.Thanks a lot.

**Comment by johanbrandhorst** [comment]
The docs are here: https://grpc-ecosystem.github.io/grpc-gateway/
