### ISSUE TITLE
undefined: runtime.AssumeColonVerbOpt

### ISSUE THREAD

**Issue by yujinsong88** [grpc-ecosystem/grpc-gateway#978]
err msg:too many arguments in call to runtime.NewPattern  undefined: runtime.AssumeColonVerbOpt

**Comment by achew22** [comment]
@yujinsong88, can you please fill out the bug template? There isn't enough information here to help you with this problem. Thanks!

**Comment by johanbrandhorst** [comment]
Dupe of #963
