### ISSUE TITLE
Returning a primitive type as a response instead of proto messages 

### ISSUE THREAD

**Issue by dayadev** [grpc-ecosystem/grpc-gateway#994]
I am having a use case if returning a primitive type as response even though the underlying grpc doesn't support returning primitive types as a response.

Wondering if its possible that I can return just a string as a response using grpc-gateway for below example rpc
```
rpc Echo(EchoReq) returns (EchoRes){
        option (google.api.http) = {
            get: "/api/echo/{message}"
        };
    }
  message EchoReq{
    string message=1;
  }
 message EchoRes{
    string echomessage=1;
}
```

Is it possible for the REST endpoint to just return string response without the the echomessage key?

**Comment by johanbrandhorst** [comment]
Could you show the exact JSON output you want?

**Comment by dayadev** [comment]
> Could you show the exact JSON output you want?

Its just a string without any keys more like html text.
Like when I hit the Rest endpoint` /api/echo/welcome ` on a web browser, it should render the response html string on the browser. Response string is something like below
```

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Page</title>
</head>
<body>
<p>test html body </p>
</body>

</html>
```

**Comment by johanbrandhorst** [comment]
You can try using the `google.api.HttpBody` type which gives you complete control over the returned data. See https://grpc-ecosystem.github.io/grpc-gateway/docs/httpbody.html. I think that should cover your needs.

**Comment by dayadev** [comment]
> You can try using the `google.api.HttpBody` type which gives you complete control over the returned data. See https://grpc-ecosystem.github.io/grpc-gateway/docs/httpbody.html. I think that should cover your needs.

That returns HttpBody as raw binary instead of actual html on a browser

**Comment by achew22** [comment]
Can you upload a sample program that exhibits that behavior? That would be a great test case for us to add. Thanks!

**Comment by dayadev** [comment]
> Can you upload a sample program that exhibits that behavior? That would be a great test case for us to add. Thanks!
Sure, the standard example when I added below option  to mux `gruntime.WithMarshalerOption(gruntime.MIMEWildcard, &gruntime.JSONPb{OrigName: false, EmitDefaults: true})`

[https://grpc-ecosystem.github.io/grpc-gateway/docs/httpbody.html](https://grpc-ecosystem.github.io/grpc-gateway/docs/httpbody.html)

**Comment by johanbrandhorst** [comment]
The docs say that you need to use the `runtime.HTTPBodyMarshaler` (https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#HTTPBodyMarshaler) when starting the runtime, are you doing that?

**Comment by johanbrandhorst** [comment]
The code you shared uses the `JSONPb` marshaler.

**Comment by dayadev** [comment]
> The docs say that you need to use the `runtime.HTTPBodyMarshaler` (https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#HTTPBodyMarshaler) when starting the runtime, are you doing that?

Using this will return the original proto names something like `prod_name` instead I am trying to set the `OrigName=false `and return camel case `prodName`

**Comment by dayadev** [comment]
> The code you shared uses the `JSONPb` marshaler.
The internal implementation also uses `JSONPb`
```

// SetHTTPBodyMarshaler overwrite the default marshaler with the HTTPBodyMarshaler
func SetHTTPBodyMarshaler(serveMux *ServeMux) {
	serveMux.marshalers.mimeMap[MIMEWildcard] = &HTTPBodyMarshaler{
		Marshaler: &JSONPb{OrigName: true},
	}
}
```

**Comment by johanbrandhorst** [comment]
The `HTTPBodyMarshaler` embeds the `Marshaler` interface. Use `m := runtime.HTTPBodyMarshaler{&runtime.JSONPb{}}` and set whatever properties you want on the inner marshaller. Also, these kind of questions are better answered in the slack channel, please try there before raising an issue in the future.

**Comment by captainhorsepower** [comment]
Have a look at `google/protobuf/wrappers.proto`, there are StringValue, BoolValue, etc. protos
